### ISSUE TITLE
After upgrade node version to 6.11.3, problem happens when execute command "node index.js"

### ISSUE THREAD

**Issue by yinguangluoren** [Automattic/node-canvas#1006]
## Issue or Feature

when i upgrade the node.js version from v4.4.4 to v6.11.3 on my server where the project contains canvas successfully deployed on , after the upgradation done , try to use node index.js to compile my file contains canvas, it shows that :
![image](https://user-images.githubusercontent.com/16773412/30576498-ef3e7028-9d3a-11e7-873a-1353c0f95e58.png)

## Steps to Reproduce

var Canvas = require('canvas');
var ctx = canvas.getContext('2d');

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 1.3.7
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 6.11.3 at CentOS release 6.6

**Comment by zbjornson** [comment]
You need to rebuild or reinstall canvas after upgrading.

**Comment by LinusU** [comment]
Yep, after upgrading major Node.js version you'll have to run `npm rebuild`
