### ISSUE TITLE
TypeError: self.canvas.streamJPEGSync is not a function

### ISSUE THREAD

**Issue by daffy6537** [Automattic/node-canvas#1008]
self.canvas.streamJPEGSync(bufsize, quality, progressive, function(err, chunk){
              ^

TypeError: self.canvas.streamJPEGSync is not a function
    at JPEGStream._read (/root/data/pp_node/node_modules/_canvas@2.0.0-alpha.5@canvas/lib/jpegstream.js:57:15)
    at JPEGStream.Readable.read (_stream_readable.js:445:10)
    at resume_ (_stream_readable.js:825:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Your Environment
* Version of node-canvas (2.0 alpha5):
* Environment (e.g. node 8 on centOS 7.3):

**Comment by zbjornson** [comment]
Are you using 2.x and did you install libjpeg? See https://github.com/Automattic/node-canvas/wiki/Installation---Windows#3-installing-libjpeg-turbo-optional-for-jpeg-support-node-canvas-20-and-later. canvas-prebuilt supports JPEG also if you don't want to install that manually.

**Comment by LinusU** [comment]
> Are you using 2.x and did you install libjpeg?

> 2.0 alpha5

The sync stream have been removed, please use `.jpegStream()` instead.

**Comment by zbjornson** [comment]
[`streamJPEGSync`](https://github.com/Automattic/node-canvas/blob/master/lib/jpegstream.js#L57) is the name used internally for JPEG streams btw.

**Comment by LinusU** [comment]
Aha, I guess we should fix that?

**Comment by zbjornson** [comment]
Yeah probably. My PR that "removed sync streams" just removed the methods with those names from the public API, but some of the streams are still sync under the hood. There's sort of a lot of TLC that needs to go into the streams and `toBuffer` APIs, and each bit is a few hours of work probably.

**Comment by LinusU** [comment]
Ah, yes of course 👍
