### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by DasCalamity** [Automattic/node-canvas#1009]
PS C:\Users\zeisl\Desktop\Commander> npm i canvas

> canvas@1.6.7 install C:\Users\zeisl\Desktop\Commander\node_modules\canvas
> node-gyp rebuild

C:\Users\zeisl\Desktop\Commander\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
..\src\CanvasRenderingContext2d.cc(801): warning C4458: declaration of 'constructor' hides class member [C:\Users\zeisl
\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
  c:\users\zeisl\desktop\commander\node_modules\canvas\src\CanvasRenderingContext2d.h(72): note: see declaration of 'Co
  ntext2d::constructor' (compiling source file ..\src\CanvasRenderingContext2d.cc)
..\src\Canvas.cc(154): warning C4457: declaration of 'data' hides function parameter [C:\Users\zeisl\Desktop\Commander\
node_modules\canvas\build\canvas.vcxproj]
  ..\src\Canvas.cc(150): note: see declaration of 'data'
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
     Creating library C:\Users\zeisl\Desktop\Commander\node_modules\canvas\build\Release\canvas.lib and object C:\Users
  \zeisl\Desktop\Commander\node_modules\canvas\build\Release\canvas.exp
Canvas.obj : error LNK2001: unresolved external symbol png_destroy_write_struct [C:\Users\zeisl\Desktop\Commander\node_
modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_bKGD [C:\Users\zeisl\Desktop\Commander\node_modules\canv
as\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_write_user_transform_fn [C:\Users\zeisl\Desktop\Commande
r\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_surface_destroy [C:\Users\zeisl\Desktop\Commander\no
de_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_longjmp_fn [C:\Users\zeisl\Desktop\Commander\node_module
s\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_get_stride [C:\Users\zeisl\Desktop\Com
mander\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_get_format [C:\Users\zeisl\Desktop\Com
mander\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_destroy [C:\Users\zeisl\Desktop\Commander\node_modul
es\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_get_io_ptr [C:\Users\zeisl\Desktop\Commander\node_modules\ca
nvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_surface_finish [C:\Users\zeisl\Desktop\Commander\nod
e_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_get_data [C:\Users\zeisl\Desktop\Comma
nder\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_pdf_surface_set_size [C:\Users\zeisl\Desktop\Command
er\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_write_info [C:\Users\zeisl\Desktop\Commander\node_modules\ca
nvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_packswap [C:\Users\zeisl\Desktop\Commander\node_modules\
canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_write_image [C:\Users\zeisl\Desktop\Commander\node_modules\c
anvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_get_error_ptr [C:\Users\zeisl\Desktop\Commander\node_modules
\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_get_height [C:\Users\zeisl\Desktop\Com
mander\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_pdf_surface_create_for_stream [C:\Users\zeisl\Deskto
p\Commander\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_create [C:\Users\zeisl\Desktop\Command
er\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_status_to_string [C:\Users\zeisl\Desktop\Commander\n
ode_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_filter [C:\Users\zeisl\Desktop\Commander\node_modules\ca
nvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_surface_flush [C:\Users\zeisl\Desktop\Commander\node
_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_svg_surface_create_for_stream [C:\Users\zeisl\Deskto
p\Commander\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_compression_level [C:\Users\zeisl\Desktop\Commander\node
_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_surface_status [C:\Users\zeisl\Desktop\Commander\nod
e_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_IHDR [C:\Users\zeisl\Desktop\Commander\node_modules\canv
as\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_write_fn [C:\Users\zeisl\Desktop\Commander\node_modules\
canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_create_info_struct [C:\Users\zeisl\Desktop\Commander\node_mo
dules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_set_filler [C:\Users\zeisl\Desktop\Commander\node_modules\ca
nvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_write_end [C:\Users\zeisl\Desktop\Commander\node_modules\can
vas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_get_width [C:\Users\zeisl\Desktop\Comm
ander\node_modules\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_error [C:\Users\zeisl\Desktop\Commander\node_modules\canvas\
build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol __imp_cairo_create [C:\Users\zeisl\Desktop\Commander\node_module
s\canvas\build\canvas.vcxproj]
Canvas.obj : error LNK2001: unresolved external symbol png_create_write_struct_2 [C:\Users\zeisl\Desktop\Commander\node
_modules\canvas\build\canvas.vcxproj]
CanvasGradient.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_add_color_stop_rgba [C:\Users\zeisl\
Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasGradient.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_create_radial [C:\Users\zeisl\Deskto
p\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasGradient.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_create_linear [C:\Users\zeisl\Deskto
p\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasGradient.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_destroy [C:\Users\zeisl\Desktop\Comm
ander\node_modules\canvas\build\canvas.vcxproj]
CanvasPattern.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_create_for_surface [C:\Users\zeisl\De
sktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_path_destroy [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_in_fill [C:\Users\zeisl\Desktop\Co
mmander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_select_font_face [C:\Users\zeisl\D
esktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_operator [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_surface_mark_dirty_rectangle [C:\U
sers\zeisl\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_save [C:\Users\zeisl\Desktop\Comma
nder\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_matrix [C:\Users\zeisl\Desktop
\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_arc_negative [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_stroke_preserve [C:\Users\zeisl\De
sktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_rectangle [C:\Users\zeisl\Desktop\
Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_line_join [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_get_filter [C:\Users\zeisl
\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_source_surface [C:\Users\zeisl
\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_fill [C:\Users\zeisl\Desktop\Comma
nder\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_line_cap [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_source [C:\Users\zeisl\Desktop
\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_mask_surface [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_set_filter [C:\Users\zeisl
\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_fill_extents [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_show_page [C:\Users\zeisl\Desktop\
Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_restore [C:\Users\zeisl\Desktop\Co
mmander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_font_extents [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_line_to [C:\Users\zeisl\Desktop\Co
mmander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_fill_rule [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_paint [C:\Users\zeisl\Desktop\Comm
ander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_push_group [C:\Users\zeisl\Desktop
\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_stroke [C:\Users\zeisl\Desktop\Com
mander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_move_to [C:\Users\zeisl\Desktop\Co
mmander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_line_cap [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_pattern_set_extend [C:\Users\zeisl
\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_operator [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_text_path [C:\Users\zeisl\Desktop\
Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_clip [C:\Users\zeisl\Desktop\Comma
nder\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_antialias [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_source_rgba [C:\Users\zeisl\De
sktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_copy_path_flat [C:\Users\zeisl\Des
ktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_source [C:\Users\zeisl\Desktop
\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_scale [C:\Users\zeisl\Desktop\Comm
ander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_user_to_device_distance [C:\Users\
zeisl\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_show_text [C:\Users\zeisl\Desktop\
Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_surface_mark_dirty [C:\Users\zeisl
\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_font_size [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_fill_preserve [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_rotate [C:\Users\zeisl\Desktop\Com
mander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_stroke_extents [C:\Users\zeisl\Des
ktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_matrix_init [C:\Users\zeisl\Deskto
p\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_text_extents [C:\Users\zeisl\Deskt
op\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_pop_group_to_source [C:\Users\zeis
l\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_dash [C:\Users\zeisl\Desktop\C
ommander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_miter_limit [C:\Users\zeisl\De
sktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_append_path [C:\Users\zeisl\Deskto
p\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_new_path [C:\Users\zeisl\Desktop\C
ommander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_identity_matrix [C:\Users\zeisl\De
sktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_line_join [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_in_stroke [C:\Users\zeisl\Desktop\
Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_paint_with_alpha [C:\Users\zeisl\D
esktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_antialias [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_dash_count [C:\Users\zeisl\Des
ktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_dash [C:\Users\zeisl\Desktop\C
ommander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_transform [C:\Users\zeisl\Desktop\
Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_close_path [C:\Users\zeisl\Desktop
\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_arc [C:\Users\zeisl\Desktop\Comman
der\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_line_width [C:\Users\zeisl\Des
ktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_clip_preserve [C:\Users\zeisl\Desk
top\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_line_width [C:\Users\zeisl\Des
ktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_set_miter_limit [C:\Users\zeisl\De
sktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_get_current_point [C:\Users\zeisl\
Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_translate [C:\Users\zeisl\Desktop\
Commander\node_modules\canvas\build\canvas.vcxproj]
CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol __imp_cairo_curve_to [C:\Users\zeisl\Desktop\C
ommander\node_modules\canvas\build\canvas.vcxproj]
Image.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_create_from_png [C:\Users\zeisl\Desktop
\Commander\node_modules\canvas\build\canvas.vcxproj]
Image.obj : error LNK2001: unresolved external symbol __imp_cairo_image_surface_create_from_png_stream [C:\Users\zeisl\
Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
init.obj : error LNK2001: unresolved external symbol __imp_cairo_version_string [C:\Users\zeisl\Desktop\Commander\node_
modules\canvas\build\canvas.vcxproj]
C:\Users\zeisl\Desktop\Commander\node_modules\canvas\build\Release\canvas.node : fatal error LNK1120: 111 unresolved ex
ternals [C:\Users\zeisl\Desktop\Commander\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\zeisl\Desktop\Commander\node_modules\canvas
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\zeisl\Desktop\Commander\package.json'
npm WARN canvas-constructor@0.3.0 requires a peer of canvas@github:Automattic/node-canvas but none was installed.
npm WARN Commander No description
npm WARN Commander No repository field.
npm WARN Commander No README data
npm WARN Commander No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zeisl\AppData\Roaming\npm-cache\_logs\2017-09-24T01_53_06_936Z-debug.log
PS C:\Users\zeisl\Desktop\Commander>

**Comment by mojoaxel** [comment]
node-canvas depends on Cairo. 
see [Windows install instructions]( https://github.com/Automattic/node-canvas/wiki/Installation---Windows)
