### ISSUE TITLE
Corrupt PDF output when using composite operations with MODE_MIME images

### ISSUE THREAD

**Issue by kayahr** [Automattic/node-canvas#1010]
## Issue

I want to render a JPEG image to a PDF and mask it with a composite operation (source-in in my case) and I want to retain the original image in the PDF, so I set the data mode of the image to MODE_MIME. This results in a corrupt image output:

![screenshot](https://user-images.githubusercontent.com/580493/30797412-36bb0c28-a1d6-11e7-90cb-07106f40d35e.jpeg)

I'm not sure if composite operations are even possible in PDF while retaining the original images but I guess even when this is not possible then node-canvas should generate a correct output by ignoring the data mode or it should bail out with an error message saying that composite operations are not supported for images with MIME data mode.

## Steps to Reproduce

```typescript
import * as Canvas from "canvas";
import * as fs from "fs";

// Create PDF canvas
const canvas = new Canvas(1000, 1000, "pdf");
const ctx = canvas.getContext("2d");

// Draw mask for composite operation
ctx.beginPath();
ctx.moveTo(0, 500);
ctx.lineTo(500, 0);
ctx.lineTo(1000, 500);
ctx.lineTo(500, 1000);
ctx.closePath();
ctx.fillStyle = "black";
ctx.fill();

// Render a JPEG into the mask
const image = new Canvas.Image();
image.dataMode = Canvas.Image.MODE_MIME;
image.src = "/tmp/image.jpeg";
ctx.globalCompositeOperation = "source-in";
ctx.drawImage(image, 0, 0, 1000, 1000);

// Save PDF
fs.writeFileSync("/tmp/out.pdf", canvas.toBuffer());
```

## Your Environment
* node-canvas 1.6.7
* Node 8.5.0
* Debian Linux 9
* Cairo 1.14.8

**Comment by zbjornson** [comment]
I think this is because "source-in" compositing isn't natively supported by PDF:

> Even if a backend supports a MIME type, that does not mean cairo will always be able to use the attached MIME data. For example, if the backend does not natively support the compositing operation used to apply the MIME data to the backend. In that case, the MIME data will be ignored. Therefore, to apply an image in all cases, **it is best to create an image surface which contains the decoded image data and then attach the MIME data to that**. This ensures the image will always be used while still allowing the MIME data to be used whenever possible.
> \- https://cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-set-mime-data

Emphasis is my own. To do that, you can do `image.dataMode = MODE_MIME | MODE_IMAGE` (which, I know, defeats the intent of embedding a JPEG, but I think this is a PDF limitation).
