### ISSUE TITLE
Access violation on Windows

### ISSUE THREAD

**Issue by ghost** [Automattic/node-canvas#1021]
### Description
Maybe you're aware of this issue, but anyway, I'm filing it because crashes should not be allowed in a serious application. If you explicitly construct `Canvas.Context2d`, accessing any of the methods of the resulting instance will cause access violation. I know nobody is supposed to do such thing, but if someone accidentally do it, the application will crash immediatelly without reporting any errors to the Node.js environment or error handlers. After Node.js process exit, type `echo %errorlevel%` into cmd and it will be `-1073741819`.

### Steps to Reproduce

```JavaScript
new(require('canvas').Context2d)().rect
```

### Environment
* **Version of node-canvas:** 1.6.7
* **Environment:** Node v8.6.0 on Windows 8.1

**Comment by LinusU** [comment]
Yeah, this should be fixed 👍 

PRs welcome!

**Comment by Hakerh400** [comment]
This is fixed by #1054
