### ISSUE TITLE
Canvas installation issue on Mac (via Terminal)

### ISSUE THREAD

**Issue by marcomorettim** [Automattic/node-canvas#1026]
argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
200 error node v6.11.5
201 error npm  v3.10.10
202 error path /Users/marcomoretti/.npm/nan/2.7.0
203 error code EACCES
204 error errno -13
205 error syscall mkdir
206 error Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/nan/2.7.0'
206 error     at Error (native)
206 error  { Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/nan/2.7.0'
206 error     at Error (native)
206 error   errno: -13,
206 error   code: 'EACCES',
206 error   syscall: 'mkdir',
206 error   path: '/Users/marcomoretti/.npm/nan/2.7.0',
206 error   parent: 'canvas' }
207 error Please try running this command again as root/Administrator.
208 verbose exit [ -13, true ]

**Comment by LinusU** [comment]
`Error: EACCES: permission denied, mkdir '/Users/marcomoretti/.npm/nan/2.7.0'`

It seems like your user cannot write to that folder, maybe you have accidentally used sudo on your local installation?

I'm not sure exactly how to solve it, but potentially removing the `.npm` folder and installing from scratch would fix it. You can probably open an issue on the npm project to get more help.
