### ISSUE TITLE
Crashes when debugging with VSCode

### ISSUE THREAD

**Issue by hillin** [Automattic/node-canvas#1030]
## Issue or Feature
When debugging a server side node app with VSCode, whenever a breakpoint hits in a context with a Canvas variable, the node process crashes.

The crash message:

> **Microsoft Visual C++ Runtime Library**
>
> Assertion failed!
> 
> Program: ...s\canvas-prebuilt\canvas\build\Release\canvas.node
> File: c:\projects\node-canvas-prebuilt\no...\nan_obj..._wrap.h
> Line: 33
> 
> Expression: object->InternalFieldCount() > 0
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts
> 

## Steps to Reproduce
1. Create a server nodejs side app, I use expressjs
2. Do something with a Canvas
3. Add a breakpoint in VSCode where the ambient contains the Canvas
4. Debug and try to make the breakpoint hit

## Your Environment
* Version of node-canvas: 1.6.5-prerelease.1 (canvas-prebuilt)
* Environment: node v8.7.0 on Windows 10 version 1709, VSCode 1.17.2

**Comment by hillin** [comment]
Sorry, seems this is a duplicate of https://github.com/Automattic/node-canvas/issues/855. Strangely I haven't found it when I did a rough search. Closing.

**Comment by zbjornson** [comment]
@hillin can you try with canvas@next please? I think it's fixed there.

**Comment by hillin** [comment]
@zbjornson thanks Zach. For some reason I have to use a prebuilt version in our production environment, but canvas-prebuilt hasn't caught up yet. So I guess I'll just walk around this issue for now and try it later when canvas-prebuilt has a new release.
