### ISSUE TITLE
Invalid EOI for JPEG files

### ISSUE THREAD

**Issue by binarykitchen** [Automattic/node-canvas#1032]
https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format says end of jpeg images must be `FF D9` (EOI) but in your unit tests I can see you aren't testing for that

https://github.com/Automattic/node-canvas/blob/9ae8fdc3fd6f9aa6b6aa81df4d28e3adb91c4637/test/canvas.test.js#L1283

There are tests for jpeg headers but not for EOIs. And it looks like EOI isn't amended at the end of buffer in the source code. Has this been forgotten or is this by intention?

**Comment by zbjornson** [comment]
libjpeg (3rd-party dependency) is responsible for actually encoding JPEGs and adds the EOI that you're referring to. I'm not sure that testing for the EOI would do much to improve the tests, although it's easy to add. Is that what you're asking?

**Comment by binarykitchen** [comment]
yeah, please add EOI tests please for JPEGs, this to make sure nothing is borken - thanks heaps

**Comment by zbjornson** [comment]
Please feel free to submit a pull request for it :)

**Comment by binarykitchen** [comment]
@zbjornson here u go https://github.com/Automattic/node-canvas/pull/1034

**Comment by zbjornson** [comment]
Fixed by #1034
