### ISSUE TITLE
Are you aware v2 alphas are installed by default from npm?

### ISSUE THREAD

**Issue by lukechilds** [Automattic/node-canvas#1035]
Running `npm install canvas` currently installs `canvas@2.0.0-alpha.6`.

In the readme it states:

> Alpha versions of 2.0 can be installed using `npm install canvas@next`.

Which implies `canvas@1` is the latest stable and would be installed via `npm install canvas`.

Related: https://github.com/lukechilds/merge-images/issues/22

**Comment by LinusU** [comment]
Sorry about that, should be fixed now:

```
$ npm dist-tag ls                           
latest: 1.6.7
next: 2.0.0-alpha.6
```
