### ISSUE TITLE
Could not load font to the system's font host

### ISSUE THREAD

**Issue by DominikSerafin** [Automattic/node-canvas#1036]
## Issue

After installing node-canvas correctly it has worked alright until I tried to register custom font. 

After registering custom font with proper path I've got error saying "Could not load font to the system's font host".

This only happened to one of my fonts that was generated using fontspring.com ordered font webfont generator. Which works great when included using @font-family on client side. 

After I've passed that font through https://transfonter.org/ it started to work correctly.

Both fonts files can be found here: https://we.tl/PmwpU3f3BM (but only use them for testing this thing, they are under fontspring license)

Also, I do not & did not have any of this fonts in my system fonts at all, so this wasn't the cause of an issue.

## Steps to Reproduce
```js

  ...

  const Canvas = require('canvas');

  // not working...
  Canvas.registerFont(path.join(SOME_ABSOLUTE_DIR, '/CoreSansA45-webfont.ttf'), {
    family: 'CoreSansA', weight: 'normal', style: 'normal'
  });

  // working...
  /* Canvas.registerFont(path.join(SOME_ABSOLUTE_DIR, '/CoreSansA45-transfonter.ttf'), {
    family: 'CoreSansA', weight: 'normal', style: 'normal'
  }); */

  var canvas = new Canvas.createCanvas(1200, 630);
  var ctx = canvas.getContext('2d');

  ctx.font = '30px CoreSansA';
  ctx.fillText('Awesome!', 50, 100);

  ...

```

## Your Environment
* node-canvas 2.0.0-alpha6
* Node 8.6.0
* Windows 10 x64

**Comment by chearon** [comment]
That message means passing it to the OS didn't work, I've never actually seen it happen now that we check for the existence of the file. The only other reason I can think of is permissions.

Did you try installing it in Windows and see if you could use it regularly, like in Word or something? I don't have Windows right now or I would try it myself.

**Comment by DominikSerafin** [comment]
Thanks for quick reply @chearon,

And yeah, it seems you're right, the one not working on node-canvas also can't be installed on my OS.

Maybe it's some clever "DRM" applied by the FontSpring, that allows me to use it only as a webfont.

So, yeah, I think it's a problem on my side instead library side.

Thanks for the great work on the node-canvas!

**Comment by chearon** [comment]
I feel like I've installed WebFonts from there before, though. It'd be interesting to hear about it if you figure out what it is. Seems like it's not an issue with node-canvas though, so closing. Thanks!

**Comment by DominikSerafin** [comment]
@chearon this font as a webfont declared with @font-face in browser worked great, hence my confusion when it stopped working with node-canvas
