### ISSUE TITLE
Resize textbox event

### ISSUE THREAD

**Issue by msbir** [Automattic/node-canvas#1040]
What is the event that handles the textbox resize?

When writing a text in Hebrew (RTL) and changing the font (I register the fonts) the width of the textbox is not changing but the text width is getting changed. 
When resizing the textbox (bigger or smaller) the width of the textbox is getting fixed by the text width

![hebrewtext](https://user-images.githubusercontent.com/29798064/33136605-5064efd0-cfae-11e7-8f20-6e13eb7e0998.png)

In english text it all looks good

![englishtext](https://user-images.githubusercontent.com/29798064/33136616-5656da5c-cfae-11e7-95e2-f6e3a9d81f23.png)

I am trying to handle this problem. 
any suggestions?

**Comment by zbjornson** [comment]
Not sure I understand. Did you mean to post this to fabric.js maybe? Could you show your code?

**Comment by msbir** [comment]
Hey, just realized that I posted the wrong repo =)
Thanks
