### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by Sparki2002** [Automattic/node-canvas#1041]
Hi,
I'm using (have to use) version 2.
Can you please add Node.js support again?

**Comment by LinusU** [comment]
Do you mean version 2 as in io.js version 2? I didn’t know that anybody at all was using it, so would you mind telling me why? :)

Version 1.x of canvas supports Node.js 0.8 and up, and it’s still being actively maintained. Is there anything in particular from 2.x that you need?

**Comment by LinusU** [comment]
Just realized that you probably meant that you are using version 2.x of node-canvas. In that case, what version of Node.js are you using?

**Comment by Sparki2002** [comment]
I'm using the latest LTS 8.9.1

**Comment by LinusU** [comment]
This project should definitely work then, what is it that isn’t working?
