### ISSUE TITLE
Custom fonts not working on master branch

### ISSUE THREAD

**Issue by rikumax25** [Automattic/node-canvas#1043]
## Issue or Feature
Custom fonts are not working and always using the fallback Arial font. 

## Steps to Reproduce

```js
const Canvas = require('canvas')
Canvas.registerFont("./font/BebasNeue Bold.ttf",{family:"BebasNeue Bold"})
var profile = Canvas.createCanvas(1059,787);
var pfCtx = profile.getContext('2d');
pfCtx.font = '180px "BebasNueue Bold"';
pfCtx.fillStyle = '#000000';
pfCtx.fillText("some text", 90,645);
```

## Your Environment
* Version of node-canvas: 2.0.0-alpha.6 
* Environment : Node 8.6.0 (Ubuntu) and Node 9.1.0 (Windows)
Both environments give the same results

**Comment by chearon** [comment]
You have a typo.

```
pfCtx.font = '180px "BebasNueue Bold"';
```

should be

```
pfCtx.font = '180px "BebasNeue Bold"';
```

**Comment by rikumax25** [comment]
(node.exe:11384): Pango-WARNING **: couldn't load font "Bebas Neue Bold Not-Rotated 180px", falling back to "Sans Bold Not-Rotated 180px", expect ugly output.

still getting the same error

**Comment by rikumax25** [comment]
wait nvm it did load
