### ISSUE TITLE
Cannot build on osx high sierra

### ISSUE THREAD

**Issue by ta3pks** [Automattic/node-canvas#1045]
## Issue or Feature

its impossible to build on osx high sierra make exits with error code 
## Steps to Reproduce

`brew install pkg-config cairo pango libpng jpeg giflib`
`xcode-select --install`
`npm i canvas`

## Your Environment
* Version of node-canvas (e.g. 1.4.0):`1.3.5`
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):`node v8.9.1 on osx 10.13.2`

![](https://i.imgur.com/m0k2FYC.png)

**Comment by ellismichaelc** [comment]
Also getting this.

**Comment by NikosEfthias** [comment]
@ellismichaelc im running my project inside a docker pm2 container with `--net=host` parameter for development it just works fine since theres no answer from the contributors this is the only way seems like

**Comment by chearon** [comment]
> since theres no answer from the contributors

Sorry, I just haven't experienced the same issue - coincidentally I did a fresh install of macOS High Sierra today, and had no problems compiling node-canvas with xcode and `brew install pango cairo`.

**Comment by pearjelly** [comment]
![image](https://user-images.githubusercontent.com/1700913/34096215-7c5a291e-e40f-11e7-999e-9c4fa27cd702.png)
i got the same

**Comment by ericontech** [comment]
Same issue.  Log attached.

[npm-debug.log](https://github.com/Automattic/node-canvas/files/1653719/npm-debug.log)

**Comment by chearon** [comment]
@ericontech what happens if you do (inside your project directory)

```
$ cd node_modules/canvas
$ ../node-gyp/bin/node-gyp.js
```

?

Your error says `node-gyp` returned `1` but doesn't provide any output from it, so I wonder if it's even being found.
