### ISSUE TITLE
Cant install/build Canvas on Windows 10

### ISSUE THREAD

**Issue by rikumax25** [Automattic/node-canvas#1046]
## Issue or Feature
when trying to install Canvas through npm it gets to an error saying :
"C:\Users\user\.node-gyp\9.2.0\x64\node.lib : fatal error LNK1107: inva
lid or corrupt file: cannot read at 0x250DE9 [C:\Users\user\Desktop\path to project\node_modules\canvas\build\canvas.vcxproj]

## Your Environment
* Node 9.2.0

**Comment by zbjornson** [comment]
Have you tried deleting `node_modules/canvas` and trying again, in case it was just a bad download?

**Comment by rikumax25** [comment]
same error

**Comment by rikumax25** [comment]
tried to compile on a different drive, same error

**Comment by oshri551** [comment]
same for me ...

C:\Users\user\.node-gyp\8.4.0\x64\node.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x259183 [C:\git-projects\project-name\node_modules\canvas\build\canvas.vcxproj]

**Comment by rikumax25** [comment]
no clues?

**Comment by zbjornson** [comment]
Need more info to help precisely, but try deleting `C:\Users\<yourusername>\.node-gyp` and then re-installing node-canvas.

**Comment by zbjornson** [comment]
Closing since there was no response, but will reopen if needed.
