### ISSUE TITLE
LoadImage throwing error (Error while reading from input stream)

### ISSUE THREAD

**Issue by pixelJavascript** [Automattic/node-canvas#1048]
## Issue or Feature

When I try to use loadImage I get this error

```

(node:1016) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: error while reading from input stream

```

This is the code that actually centers around the error

```js

const loadImageIf = (condition, src, func) => {

  if(condition) loadImage(src).then((image) => {func(image)}); else func()

}

```

And then later in my code

```

loadImageIf(targetStats.profileSettings.usedBackground != undefined, `./../backgrounds/${client.config.commands.profile.backgrounds[targetStats.profileSettings.usedBackground]}`, (image) => {

  if(image) ctx.drawImage(0, 0, config.width, config.height)



  ...More stuff to add to the canvas here, not more images...



  message.channel.send({ files: [canvas.toBuffer()] })

})

```

So let me explain, in the sibling directory of this module are my backgrounds, in this instance I am trying to use `"fox_in_snow.png"`, (which is the 0th index of `client.commands.profile.backgrounds`) if, the user has set `usedBackground` (Which they do in this case), if they do not it will run the code without the image, which works fine. I am also sending this all to a buffer which I am 

sending via Discord.js, which works fine.

## My Environment

* node-canvas version 2.0.0-alpha.6
* Environment node 6.11.2 on Windows 10, version 1709

**Comment by LinusU** [comment]
Are you sure that the image exists? Could you upload it here so we could see if it's something wrong with the image?

**Comment by pixelJavascript** [comment]
Here ya go
![fox_in_snow](https://user-images.githubusercontent.com/29942916/33863608-c5f04ffa-dea5-11e7-8b0a-bd436fe86ac8.png)

**Comment by LinusU** [comment]
It works for me, but if I change the name to something that doesn't exist I get the exact same error you are getting. Are you sure that you are calling `loadImage` with a path that is correct?

**Comment by littlehansel** [comment]
This error occurs when you have something other than the images in your layer folders. For instance if you have a folder or an mp4 file in one of your layer folders , the code will go through every layer folder and try to pick each item , one at a time .. so if it picks up at random a folder or an mp4 (or anything else other than the image) the code will try to parse it but fail throwing an "Error while reading from input stream". Just keep your layer folders clean.. ✌️
