### ISSUE TITLE
Can't install Canvas.

### ISSUE THREAD

**Issue by DoctorDarkMagic** [Automattic/node-canvas#1050]
## Issue or Feature
Can't install canvas 2.0.0-alpha.7.

## Steps to Reproduce
Add canvas to the package.json with the version `^2.0.0-alpha.7`.
Returns:
```
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): ?
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 8.1.2 on Mac OS 10.13.1

**Comment by LinusU** [comment]
Have you installed the required dependencies?

```sh
brew install pkg-config cairo pango libpng jpeg giflib
```

**Comment by DoctorDarkMagic** [comment]
Yes, I did and something went wrong I think. I reinstalled them and it started working, thanks anyway!
