### ISSUE TITLE
Create and draw image with raw ARGB32 data

### ISSUE THREAD

**Issue by paramaggarwal** [Automattic/node-canvas#1052]
## Feature
I want to render image on the canvas from raw RGBA32 data - the same format data that is the output from canvas.toBuffer('raw'). Please guide me on how to expose the relevant variable.

The final else condition here: [src/Image.cc#L256-L28](https://github.com/Automattic/node-canvas/blob/master/src/Image.cc#L256-L287) needs to be to set the raw buffer as is - that should enable this usecase.

Please help - thanks.

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(1, 1);
var ctx = canvas.getContext('2d');

var i = new Image();
i.src = new Buffer('F000', 'hex'); // single red pixel image - raw RGBA32
i.onerror = console.error;
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0 alpha
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 9.3.0 on High Sierra

**Comment by zbjornson** [comment]
Does `ctx.putImageData` satisfy your use case? That's in RGBA32 order already.

(I could see adding support for ARGB32 since `putImageData` does a sort of byte-swapping from RGBA to ARGB that isn't especially fast right now.)

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData

**Comment by paramaggarwal** [comment]
Oh, wow - hadn't found this when I was searching. Thanks a lot @zbjornson!

The byte-swapping is fine as it's still better than encoding/decoding PNG. Going to close this issue now - thanks!

**Comment by paramaggarwal** [comment]
Hello, I have a small follow-up question - what is the difference between the custom `canvas.toBuffer('raw')` and the standard `ctx.getImageData()`? Both of them seem to give the raw canvas data.
