### ISSUE TITLE
Recurrent pixman not found on path

### ISSUE THREAD

**Issue by staminna** [Automattic/node-canvas#1065]
After installing pixman from source, I set it on bash_profile after rebuilding node-gyp

`> node-gyp rebuild

Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code`

I also tried installing pixman with brew and macports, but the issue always resets to this error message, even after successful install.

My Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (e.g. node 8.1.0 on Mac OS X 10.13.1):

**Comment by jayrmotta** [comment]
Any updates on this?

**Comment by jayrmotta** [comment]
I had to install via brew (since I'm on a mac) pixman, cairo and pango.

Now it works!

**Comment by evaristoc** [comment]
Hi,

Having same error as for this issue when trying npm. Part of my error output:

```
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

**Comment by evaristoc** [comment]
Ok: I found this:
https://github.com/Automattic/node-canvas/issues/1319

**Comment by paleo** [comment]
On Ubuntu 20.04:

```sh
sudo apt install libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev
```

**Comment by LordRampantHump** [comment]
> On Ubuntu 20.04:
> 
> ```shell
> sudo apt install libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev
> ```

This was the solution for me. Thank you

**Comment by lrettig** [comment]
Ran into this today and installing these packages didn't do it. Using earlier versions of Python and Node did the trick - canvas doesn't seem to play nice with Node 15 (and node-gyp doesn't like Python 3.9). See https://github.com/Automattic/node-canvas/issues/1319#issuecomment-757505904.

**Comment by williamscs** [comment]
This seems to have been fixed in the 2.7.0 release. I was able to run an `npm install` using Node 15 without any failures from node-gyp.

Using one of the 2.6.x versions, I was hitting the same pixman errors mentioned above.

**Comment by owenventer** [comment]
> I had to install via brew (since I'm on a mac) pixman, cairo and pango.
> 
> Now it works!

How did you do that?

**Comment by nb312** [comment]
> On Ubuntu 20.04:
> 
> ```shell
> sudo apt install libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev
> ```

Thanks for the solutions.

**Comment by thomasaarholt** [comment]
> > I had to install via brew (since I'm on a mac) pixman, cairo and pango.
> > Now it works!
> 
> How did you do that?

I installed it like this:

`brew install pixman cairo pango`

I had to do this in order to install the development version of jupyterlab

**Comment by Ginxo** [comment]
This command for Fedora
`dnf install libjpeg-devel giflib-devel pixman-devel cairo-devel pango-devel`

**Comment by TANK-RICHARD** [comment]
> On Ubuntu 20.04:
> 
> ```shell
> sudo apt install libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev
> ```

It's really usefully on Ubuntu 18.04, Thank U.

**Comment by sharq88** [comment]
Rocky linux 9 `giflib-devel` was not available needed a flag: 
```
dnf --enablerepo=devel install -y cairo-devel pango-devel libjpeg-turbo-devel giflib-devel pixman-devel
```

**Comment by sanchisingh01** [comment]
i'm trying to install pixman on windows 11 using msys2, i'm having a lot of trouble installing pixman and i'm thinking if i should just switch to Ubuntu?

**Comment by paulo-roberto-rosa** [comment]
> This seems to have been fixed in the 2.7.0 release. I was able to run an `npm install` using Node 15 without any failures from node-gyp.
> 
> Using one of the 2.6.x versions, I was hitting the same pixman errors mentioned above.

what do you mean by using 2.7.0? the latest canvas version as of 2023 is 2.11.2

**Comment by paulo-roberto-rosa** [comment]
> I had to install via brew (since I'm on a mac) pixman, cairo and pango.
> 
> Now it works!

**For those homebrew did not work (as of me for example):**

I am using Mac OSX with M1 Chip and I was not able to install dependencies and also not able to run unit tests because of that. After trying several solutions, I found out the cause, it was homebrew that was not configuring pkg-config properly after installing it.

So what solved was to use [Mac Ports](http://macports.org/) to install pkg-config and pango:
after running: sudo port install pkgconfig pango

and wait for long 40 minutes, I can finally install everything properly on the project and no more canvas errors showing up and I can finally run unit tests again :) thank god. i spent 1 week trying to solve that one.

**Comment by ambroselittle** [comment]
You're

**Comment by ambroselittle** [comment]
You're a 👑, @paulo-roberto-rosa. That worked on my M3, too. 🤗

**Comment by Marcel-Tronco** [comment]
> On Ubuntu 20.04:
> 
> sudo apt install libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev

Still working. Ubuntu 22.04

**Comment by karlhorky** [comment]
For anyone looking for a GitHub Actions workflow solution on `ubuntu-latest`, the step in the node-canvas CI workflow appears to work:
 
- https://github.com/Automattic/node-canvas/blob/master/.github/workflows/ci.yaml#L22-L25

```yaml
      # Install dependencies for node-canvas to avoid `Package pixman-1
      # was not found in the pkg-config search path` errors
      # - 
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
```

- Commit: https://github.com/upleveled/security-vulnerability-examples-next-js-postgres/pull/278/commits/b0477d5109a1e036d1105e5c6e6230ecc7dfa169
