### ISSUE TITLE
fontWeight bold bug

### ISSUE THREAD

**Issue by msbir** [Automattic/node-canvas#1069]
Hey, when font have fontWeight:bold setup, the width of the text increase and goes outside the canvas frame which makes it 'buggy'

![screen shot 2017-12-27 at 13 27 01](https://user-images.githubusercontent.com/29798064/34380378-aeaa4830-eb09-11e7-8eb8-124f438a97d6.png)

![screen shot 2017-12-27 at 13 27 08](https://user-images.githubusercontent.com/29798064/34380386-c1adb9bc-eb09-11e7-92da-7867958f50d2.png)

* the fact that it is not in English doesn't need to be a problem for this issue

node-canvas version : 2.0.0-alpha.5
node version : 6.11.3

**Comment by LinusU** [comment]
I think that this is intended behaviour, since bold text does indeed take up more horizontal space. Would it be possible for you to increase the canvas width?

**Comment by msbir** [comment]
Hey, thanks for the reply
I am afraid this is not an option. 
even if it was, increase the canvas width by what?

**Comment by LinusU** [comment]
> I am afraid this is not an option.

Well, what do you expect bold to do? The text will get wider when it's bold...

> even if it was, increase the canvas width by what?

I'd use `measureText` to see how wide it should be...

**Comment by msbir** [comment]
well, I have an app the let the user add text on canvas and than creating a file from it. so, I would expect that when rendering the text on the server side, the text object will be set like the user have set it on the front side and will not get wider.

**Comment by zbjornson** [comment]
I don't quite understand the issue you're hitting. Bold font faces are wider than regular font faces, there's nothing that can be done about that. If you're seeing slight differences in rendering between a web browser and node-canvas, that's also essentially impossible to fix due to the nature of font rendering engines.

**Comment by asturur** [comment]
I do not understand why we are comparing bold with normal.
Is the user on the browser using bold font too?

**Comment by msbir** [comment]
yes.
on the browser it looks good for the user, but then when rendering with node-canvas it's getting stretch and looks like the attached image.

**Comment by asturur** [comment]
I think on the browser the loading process of the font is not finished yet when you draw and you are getting the normal font. Regular weight. ( using a fontface does not mean having a loaded a font )
Since on node-canvas font load is syncronous you are getting the real bold font.

**Comment by 6-8-axnw1bom81v5xa3nh48c** [comment]
I'm curious, does the text from the attached image mean `"Hey what's going on"` in hebrew?

**Comment by msbir** [comment]
It is more like 'whats up?' =)

**Comment by zbjornson** [comment]
I think this is working as intended. If not, please comment and I'll reopen.

**Comment by sanathfp** [comment]
> It is more like 'whats up?' =)

I'm facing the same problem in my use case. Did you end up fixing it?

**Comment by msbir** [comment]
@sanathfp hmm it was long time ago so I'm not sure, but I think we used different fonts that didn't cause this issue..
