### ISSUE TITLE
make: Entering directory...node_modules/canvas/build'

### ISSUE THREAD

**Issue by bt-zz** [Automattic/node-canvas#1070]
[xxx@xxx xxx]$ npm install canvas

\>canvas@1.6.9 install /home/ysh/dev/CrazyVonoi-server/node_modules/canvas
\>node-gyp rebuild

make: Entering directory `/home/xxx/xxx/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o

 Killed
[xxx@xxx xxx]$   CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  COPY Release/canvas.node

 make: Leaving directory `/home/xxx/xxx/node_modules/canvas/build'
<img width="728" alt="wx20171228-233255 2x" src="https://user-images.githubusercontent.com/4394024/34415047-7d0bbf92-ec27-11e7-9d96-00d999fb8f33.png">

## Issue or Feature
terminal all ways stop this interface (above) after 'npm install canvas'.

## Environment
* CentOS 7

**Comment by zbjornson** [comment]
Did you make sure that another process doesn't have node-canvas's files in use/locked? That can make the build appear to hang indefinitely. Otherwise this doesn't seem to be a node-canvas issue...

**Comment by bt-zz** [comment]
@zbjornson May be  one process  have node-canvas's files in use/locked.  Re-install node-canvas after i restart OS .  successfully! 
Thx.
