### ISSUE TITLE
canvas not working after successful install -> createCanvas is not a function

### ISSUE THREAD

**Issue by nbremer** [Automattic/node-canvas#1073]
## Issue or Feature
By using the recommended `brew install pkg-config cairo pango libpng jpeg giflib` followed by `npm install canvas` I think I successfully installed node-canvas. At least, I didn't get any errors. However, if I now want to run even the simplest of function:
```js
var Canvas = require('canvas')
var canvas = Canvas.createCanvas(320, 320)
```

I get the following error message when I run it
```js
var canvas = Canvas.createCanvas(320, 320)
                    ^

TypeError: Canvas.createCanvas is not a function
```

When I try to run it through browserify, I get the following error

```js
Uncaught SyntaxError: Invalid or unexpected token
```

I have to admit, I'm quite new to node, needing it now to output a large and high quality canvas image, so maybe I'm just forgetting something. (not sure if if it matters, but on the install at first I didn't have `pango` because I used the installation example from the [npm site](https://www.npmjs.com/package/canvas), which doesn't contain `pango`, so installed that later)

## Your Environment
* Mac OS X 10.13.2
* node-canvas v1.6.9
* node v9.2.1
* npm v5.6.0
* pkg-config v0.29.2
* cairo 1.14.12
* pango 1.40.14
* libpng 1.6.34
* jpeg 9b
* giflib 5.1.4

**Comment by nbremer** [comment]
After trying out a few more things, I did manage to get the code working (`node index.js` I mean) if I wrote it like this:
```js
var Canvas = require("canvas")
	
var canvas = new Canvas(320, 320)
var ctx = canvas.getContext("2d")
```
However, when trying to send it to the browser with browserify, to make it easier for me to develop the HTML5 canvas code, I still get the same error as in before, even with this adjustment in code.

**Comment by zbjornson** [comment]
Looks like you figured it out, but that syntax is for canvas 2, and you installed 1.6. The 1.6 docs are here:

https://github.com/Automattic/node-canvas/tree/v1.x

Or you can install 2.x with browserify support with `npm install canvas@next`.

**Comment by zbjornson** [comment]
Derp, and I didn't read your edited comment :-).
