### ISSUE TITLE
[Feature Request] Text Multiline and word-wrap

### ISSUE THREAD

**Issue by mikeccuk2005** [Automattic/node-canvas#1077]
## Feature Request

I'd like to work wrap a text field in a box.
Say you have a very long sentence and a limited square space to put the text. The text need to word wrap in multiple lines, also provide the ... at the end 

Something similar to html:
```
<div style="
        width: 400px;
        border: 1px solid #000000;
        vertical-align: bottom;
        text-align: center;
        word-wrap: break-word;
        font-size: 30px;
        -webkit-line-clamp: 3;
        display: -webkit-box;
        -webkit-box-orient: vertical;
        overflow: hidden;"
>This paragraph contains a very long word this is a veryveryveryveryveryvery longword. The lsdfsdfdsfdsf sdf dsf sdf sfd ong word will break and wrap to the next line.</div>

```

**Comment by LinusU** [comment]
The goal of this module is to mirror the HTML5 Canvas API. I would recommend making this suggestion to the relevant W3 working group instead of here.

In the mean time, here is a implementation that you can use outside together with this module: https://stackoverflow.com/a/16221307/148072

**Comment by chearon** [comment]
There's also [txtjs](https://github.com/diverted247/txtjs) although it seems slightly abandoned and I haven't tried it. I have an implementation of word wrapping/proper leading/span attributes/etc which has worked well for a while now. I may try to open source it some time.

**Comment by GDur** [comment]
I had the same issue.
Here is a working example from someone else (Peter Hrynkow) on codepen:
https://codepen.io/peterhry/pen/AGIEa
