### ISSUE TITLE
npm install error: "node-waf configure build"` failed with 1

### ISSUE THREAD

**Issue by mahemoff** [Automattic/node-canvas#108]
I tried install this on Node 0.4, but got an error (perhaps related to what's described here), so I updated to latest (0.5.3-pre), but get the same error.

-> npm install canvas

> canvas@0.7.0 preinstall /path/to/node_modules/canvas
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node prefix                 : not found
Checking for library gif                 : not found
Checking for library jpeg                : not found
Checking for cairo                       : yes
'configure' finished successfully (0.879s)
Waf: Entering directory `/path/to/node_modules/canvas/build'
[1/9] cxx: src/Canvas.cc -> build/default/src/Canvas_1.o
[2/9] cxx: src/CanvasGradient.cc -> build/default/src/CanvasGradient_1.o
../src/Canvas.cc:13:25: error: node_buffer.h: No such file or directory
../src/Canvas.cc: In static member function ‘static int Canvas::EIO_AfterToBuffer(eio_req*)’:
../src/Canvas.cc:162: error: ‘Buffer’ was not declared in this scope
../src/Canvas.cc:162: error: ‘buf’ was not declared in this scope
../src/Canvas.cc:162: error: ‘Buffer’ is not a class or namespace
../src/Canvas.cc:163: error: ‘Buffer’ is not a class or namespace
../src/Canvas.cc: In static member function ‘static v8::Handle<v8::Value> Canvas::ToBuffer(const v8::Arguments&)’:
../src/Canvas.cc:225: error: ‘Buffer’ was not declared in this scope
../src/Canvas.cc:225: error: ‘buf’ was not declared in this scope
../src/Canvas.cc:225: error: ‘Buffer’ is not a class or namespace
../src/Canvas.cc:226: error: ‘Buffer’ is not a class or namespace
../src/Canvas.cc: In function ‘cairo_status_t streamPNG(void*, const uint8_t*, unsigned int)’:
../src/Canvas.cc:241: error: ‘Buffer’ was not declared in this scope
../src/Canvas.cc:241: error: template argument 1 is invalid
../src/Canvas.cc:241: error: invalid type in declaration before ‘=’ token
../src/Canvas.cc:241: error: ‘Buffer’ is not a class or namespace
../src/Canvas.cc:242: error: ‘Buffer’ is not a class or namespace
../src/Canvas.cc:242: error: base operand of ‘->’ is not a pointer
../src/Canvas.cc:245: error: base operand of ‘->’ is not a pointer
Waf: Leaving directory `/path/to/node_modules/canvas/build'
Build failed:  -> task failed (err #1):
        {task: cxx Canvas.cc -> Canvas_1.o}
npm ERR! error installing canvas@0.7.0 Error: canvas@0.7.0 preinstall: `node-waf configure build`
npm ERR! error installing canvas@0.7.0 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing canvas@0.7.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing canvas@0.7.0     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing canvas@0.7.0     at ChildProcess.onexit (child_process.js:246:12)
npm ERR! canvas@0.7.0 preinstall: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR!
npm ERR! Failed at the canvas@0.7.0 preinstall script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Darwin 10.6.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /path/to/npm-debug.log
npm not ok

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
