### ISSUE TITLE
question: the first example. show me error. 

### ISSUE THREAD

**Issue by hhniao** [Automattic/node-canvas#1081]
ehh, im a newbie. 
const { createCanvas, loadImage, version } = require('canvas');
console.log(createCanvas, loadImage, version);//undefined undefined '1.6.9'
what wrong?
tahnks.

**Comment by zbjornson** [comment]
That syntax is for node-canvas 2.x. You can install it with `npm install canvas@next`, or you can look at the 1.x documentation here: https://github.com/Automattic/node-canvas/blob/v1.x/Readme.md.

**Comment by hhniao** [comment]
thanks.
it is very usefull for me.
