### ISSUE TITLE
Invalid color on boundaries of downscaled image

### ISSUE THREAD

**Issue by ikokostya** [Automattic/node-canvas#1084]
## Issue

If draw downscaled image on canvas with default texture filtering mode, it has invalid color on boundaries. 

## Steps to Reproduce

I created repository for easy reproduce error: https://github.com/ikokostya/node-canvas-downscale-bug

The code below duplicates code from the repository.

```js
'use strict';

const fs = require('fs');
const Canvas = require('canvas');

const canvas = new Canvas(1057, 474);
const ctx = canvas.getContext('2d');

const img1 = new Canvas.Image();
img1.src = fs.readFileSync(`${__dirname}/img1.jpeg`);
ctx.drawImage(img1, -170, -203, 352, 352);

const img2 = new Canvas.Image();
img2.src = fs.readFileSync(`${__dirname}/img2.jpeg`);
ctx.drawImage(img2, 182, -203, 352, 352);

canvas.jpegStream({quality: 100}).pipe(fs.createWriteStream('out.jpeg'));
```

Where `img1.jpeg` is 

![img1](https://user-images.githubusercontent.com/328125/35698544-6ee8cd50-079e-11e8-816f-f21268acfee8.jpeg)

and `img2.jpeg` is 

![img2](https://user-images.githubusercontent.com/328125/35698561-775aa8aa-079e-11e8-8df9-5172ef315df0.jpeg)

## Actual result

![out](https://user-images.githubusercontent.com/328125/35698598-9d9cfc02-079e-11e8-815a-ce6dc1aa1250.jpeg)

**Note** 1-pixel vertical line on boundary between images.

## Expected result

There is no any vertical pixel line between images. Like in browser version:

![download](https://user-images.githubusercontent.com/328125/35698680-dd74f154-079e-11e8-95d0-33817f5061e6.png)

Code:

```html
<style>
#canvas {
    border: 1px solid #000000;
}
</style>

<canvas id="canvas" width="1057" height="474"></canvas>

<script>
const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');

const img1 = new Image();
img1.src = 'img1.jpeg';
img1.onload = () => {
    ctx.drawImage(img1, -170, -203, 352, 352);
};

const img2 = new Image();
img2.src = 'img2.jpeg';
img2.onload = () => {
    ctx.drawImage(img2, 182, -203, 352, 352);
};
</script>
```

## Your Environment
* Version of node-canvas `1.6.9`. Also reproduced on latest version from master.
* Environment
  * node `v8.9.0`
  * Ubuntu `16.04`, `Linux 4.13.0-26-generic`

***

## Possible cause of the problem

When image is downscaling color of pixels is computed using color of surrounding pixels, but color outside of the source pattern is black (default canvas fill). That's why boundary pixels of the downscaled image is more dark.

If enable `Nearest-neighbor interpolation` filtering mode (i.e.
 setup [CanvasRenderingContext2D#patternQuality](https://github.com/Automattic/node-canvas#canvasrenderingcontext2dpatternquality) to `nearest`), problem is solved, but resulting image quality is bad:

![out](https://user-images.githubusercontent.com/328125/35699349-d522aec2-07a0-11e8-9300-63a31fd16dab.jpeg)

## Possible solution

The following patch completely resolves problem: 

```diff
diff --git a/src/CanvasRenderingContext2d.cc b/src/CanvasRenderingContext2d.cc
index c133187..8120d6b 100755
--- a/src/CanvasRenderingContext2d.cc
+++ b/src/CanvasRenderingContext2d.cc
@@ -946,6 +946,7 @@ NAN_METHOD(Context2d::DrawImage) {
   // Paint
   cairo_set_source_surface(ctx, surface, dx - sx, dy - sy);
   cairo_pattern_set_filter(cairo_get_source(ctx), context->state->patternQuality);
+  cairo_pattern_set_extend(cairo_get_source(ctx), CAIRO_EXTEND_REFLECT);
   cairo_paint_with_alpha(ctx, context->state->globalAlpha);

   cairo_restore(ctx);
```

**Comment by chearon** [comment]
Good work finding the issue, so the problem is caused by the fact that `drawImage` paints from another surface, and `CAIRO_EXTEND_REFLECT` would make the bilinear interpolation choose a color from the edge of the image rather than the blank/black canvas.

If you open a PR, I'll merge it. Thanks!
