### ISSUE TITLE
Installation error on Ubuntu (node-gyp / has_lib.sh)

### ISSUE THREAD

**Issue by j-a-m-l** [Automattic/node-canvas#1085]
I'm trying to install `node-canvas`, but I'm blocked by this error:

```
> canvas@1.6.9 install /ark-mobile/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: 1: ./util/has_lib.sh: Permission denied
gyp: Call to './util/has_lib.sh freetype' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/ark-mobile/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-91-generic
gyp ERR! command "/.nvm/v8.3.0/bin/node" "/ark-mobile/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /ark-mobile/node_modules/canvas
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

* I'm using Node v8.3.0 on Ubuntu 17.04.

Any suggestions?

<sub>edited for formatting - ZB</sub>

**Comment by zbjornson** [comment]
I can't tell how you tried to do the installation (e.g. `npm install canvas` in a node project directory, or `npm install -g canvas`, or something else; with or without sudo?). It looks like you might be in a root directory where you don't have permissions to execute the files?

**Comment by j-a-m-l** [comment]
I tried first installing the project, which has `node-canvas` as a dependency. Since it doesn't work, I tried installing it directly with `npm install canvas`. Always without `sudo`.

**Comment by j-a-m-l** [comment]
I've tried `rm -rf node_modules` and `npm install` again and it worked.

**Comment by ujjawaljaiswal2017** [comment]
Hi, I have the same issue but your solution doesn't work for me. Can you suggest any alternative?
