### ISSUE TITLE
Can not use `#ifdef CAIRO_FORMAT_RGB30` to detect support for RGB30 of cairo.

### ISSUE THREAD

**Issue by wsw0108** [Automattic/node-canvas#1086]
## Issue or Feature

Can not use `#ifdef CAIRO_FORMAT_RGB30` to detect support for RGB30 of cairo.

## Steps to Reproduce

```c
#include <cairo.h>

int main() {
#ifdef CAIRO_FORMAT_RGB30
  printf("has RGB30\n");
#endif
  printf("nothing\n");
  return 0;
}
// gcc -I /usr/include/cairo test.c
// ./a.out, willl print "nothing"
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.9
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): cairo version 1.10.2

**Comment by zbjornson** [comment]
I think that's working as expected. `CAIRO_FORMAT_RGB30` was added in Cairo 1.12, and your post says you're using Cairo 1.10.2.
