### ISSUE TITLE
text maxWidth does not work for the first text render in the image & is inconsistent on second render

### ISSUE THREAD

**Issue by germanoeich** [Automattic/node-canvas#1088]
## Issue
When using the maxWidth argument of either fillText or strokeText, if the text being width limited is the first text on the image, maxWidth will not work. If any text is rendered before, the subsequent text render will be resized but will be inconsistent and shorter than it should unless it has the same text. All text renders after the first and second will work properly.

This issue is better explained with code and images:

## Steps to Reproduce
```js
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext('2d');

ctx.font = '18px Helvetica'
ctx.fillText('I should be resized', 0, 20, 90)
ctx.fillText('I should be resized', 0, 40, 90)
ctx.fillText('I should be resized', 0, 70, 90)
ctx.fillText('I should be resized', 0, 100, 90)
ctx.fillText('I should be resized', 0, 130, 90)
ctx.fillText('I should be resized', 0, 170, 90)
```

The code above generates this image:
![image](https://user-images.githubusercontent.com/17045274/35780239-971722ae-09bf-11e8-8570-48af180f3c9f.png)

Now we change the text for the first text render:

```js
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext('2d');

ctx.font = '18px Helvetica'
ctx.fillText('I should be resized a', 0, 20, 90)
ctx.fillText('I should be resized', 0, 40, 90)
ctx.fillText('I should be resized', 0, 70, 90)
ctx.fillText('I should be resized', 0, 100, 90)
ctx.fillText('I should be resized', 0, 130, 90)
ctx.fillText('I should be resized', 0, 170, 90)
```

The result is:
![image](https://user-images.githubusercontent.com/17045274/35780251-c322d5e6-09bf-11e8-9cd1-40bb15e68ed8.png)

Notice that the second text is smaller than the others.

The behaviour above is consistent even if we remove the maxWidth property from the first fillText call.

![image](https://user-images.githubusercontent.com/17045274/35780277-020f8ed4-09c0-11e8-9eca-44f84417e10c.png)

The image above is the same code, just without maxWidth on the first fillText call and a longer text on it. It seems that the longer the first text, the smaller the second one will be.

strokeText is also affected in the same way.

## Environment
* Version of node-canvas: 2.0.0-alpha.9
* Environment: OS X 10.13.3

**Comment by germanoeich** [comment]
After opening the issue, I realized the problem may be an inconsistence in maxWidth overall. This image is the same code with the texts changed a a 90px width rect for reference:
![image](https://user-images.githubusercontent.com/17045274/35780467-faa7e67a-09c2-11e8-8803-0da9fafb989f.png)

**Comment by chearon** [comment]
Thanks for posting the issue. I'm looking at the code and it definitely looks suspicious (the string argument to the helper function used by `strokeText`/`fillText` isn't even being used). I'll have a fix sometime soon.

**Comment by pravdomil** [comment]
I got a same issue if I set `maxWidth`
