### ISSUE TITLE
Can't install on windows server 2016

### ISSUE THREAD

**Issue by freetnt5852** [Automattic/node-canvas#1089]
I've followed the guide and installed it via the choco commands but still getting too many errors on the npm part 
Here's a picture of errors, sorry if picture is not clear let me know if you can't see it properly.
![screenshot_2018-02-05-01-19-54](https://user-images.githubusercontent.com/31079629/35783182-93db3ebe-09af-11e8-9426-3e431f151371.png)

**Comment by SharpBit** [comment]
you're on a vps on a phone? 🤔

**Comment by zbjornson** [comment]
The chocolatey instructions don't quite work. Someone put a warning on the wiki page about that until someone gets around to fixing them. Please try the manual windows instructions again, or use `canvas-prebuilt` instead.
