### ISSUE TITLE
registerFont Memory usage...

### ISSUE THREAD

**Issue by smaznet** [Automattic/node-canvas#1093]
Hi i tested registerFont and ... this is result of

![image](https://user-images.githubusercontent.com/10239885/36135811-a1215794-10a2-11e8-801e-d690d47449fe.png)

``` js
const Canvas = require('canvas');


for(let i = 0 ; i < 10000 ; i++){
	Canvas.registerFont("../data/fonts/font.ttf",{family: "font"})
}
```

**Comment by chearon** [comment]
Well shoot that's not good. There is a lot of memory (de)allocations that happen there so it's not hard to believe. I'll take a look when I get a chance.
