### ISSUE TITLE
g.lineWidth changes unexpectedly

### ISSUE THREAD

**Issue by 6-8-axnw1bom81v5xa3nh48c** [Automattic/node-canvas#1095]
## Issue

Accessing internal setter of `canvas.width` or `canvas.height` modifies rendering context's `lineWidth` property. I'm not sure if it is according to the standard. At least in all modern browsers it works properly, so I suppose it is some kind of a bug with node-canvas.

## Steps to reproduce

Code which demonstrates the issue:

```JavaScript
var g = new Canvas(1, 1).getContext('2d');
console.log(g.lineWidth); // 1
g.canvas.width |= 0;
console.log(g.lineWidth); // 2
```

## Your Environment
* **Version of node-canvas:** master
* **Environment:** Node.js latest version (master), os: Windows 8.1

**Comment by chearon** [comment]
You're right. Looks like Cairo defaults to 2 and we're not resetting it on resurface, only when the context is created.
