### ISSUE TITLE
Make it installable for python v3.x

### ISSUE THREAD

**Issue by binarykitchen** [Automattic/node-canvas#1106]
Or is this too much to ask? Cos on my system don't have v2 and installing that would cause a mess here ...

**Comment by zbjornson** [comment]
That's a limitation of gyp and node-gyp, nothing we can do unfortunately.

**Comment by LinusU** [comment]
We could potentially look at cmake.js, I think it's quite awesome!

Not sure if we should have an open issue about that, seems like the main benefits would be using cmake instead of gyp, which potentially is easier for developers...

**Comment by chearon** [comment]
I didn't read all of it but if cmake.js's goal is to enable CMake to build node modules.... that sounds awesome! #992 also would help here. `node-canvas-prebuilt` is up to 100k downloads a month so it may be time to start thinking about it again.
