### ISSUE TITLE
[Request] Would it be possible to parse a buffer to drawImage?

### ISSUE THREAD

**Issue by eNepper** [Automattic/node-canvas#1107]
I'm wondering if it would be possible to skip the creation of a new image with a source and just pase a buffer containing a supported image format directly to drawImage?

I know there might be a problem with drawImage not being a async function, but it could return a promise or take a callback when a buffer is parsed directly?

-- Esben N.

**Comment by zbjornson** [comment]
I think this would only be an API convenience. Internally the image buffer still needs to be decoded, which is what happens when you set `img.src = mybuffer`. Are you trying to get better performance, or just a nicer API?

**Comment by zbjornson** [comment]
I don't think there's anything actionable here since it wouldn't increase performance and would be a non-standard API.
