### ISSUE TITLE
Attempting to install from non-source causes a build error due to 404.

### ISSUE THREAD

**Issue by dragonfire535** [Automattic/node-canvas#1108]
## Issue or Feature

Attempting to install from non-source causes a build error. `node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.10/canvas-prebuilt-v2.0.0-alpha.10-node-v59-linux-x64.tar.gz`. This is likely due to the fact that the latest release on the prebuilt repo is for alpha.5. While I don't even like the idea of having the pre-build script (it brings in _so_ many dependencies, including all of the request module), this would be a good thing to fix.
## Steps to Reproduce

```
npm install
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.10
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 9.8.0 on Ubuntu 16.04.4 LTS

**Comment by chearon** [comment]
Uh oh, it's been a long time now but when I created the PR I thought it was falling back to build, not sure why it isn't doing that...

> I don't even like the idea of having the pre-build script (it brings in so many dependencies, including all of the request module)

Definitely agree with you there. I was even thinking about just writing a quick script to do it. I think `prebuild-install` had even _more_ dependencies.

**Comment by sthielen** [comment]
Is there an easy workaround until this is fixed?

**Comment by zbjornson** [comment]
You could install a prior release, like `2.0.0-alpha.9`.

**Comment by sthielen** [comment]
@zbjornson I tried that and was wondering why it wasn't working, turns out I missed the `^` in the dependency version. Working now. Thanks!

**Comment by LinusU** [comment]
> (it brings in so many dependencies, including all of the request module)

Ugh, maybe we could make some pull requests to them to use a smaller module, the request module is known for being very bloated...

**Comment by dragonfire535** [comment]
Looking at the source for `node-pre-gyp`, they even lock the request version down, which has caused a number of issues in the past (mapbox/node-pre-gyp#349, mapbox/node-pre-gyp#347), and the last time request was brought up, the issue was ignored (mapbox/node-pre-gyp#340). Maybe it'd be better to find a different library than that.
