### ISSUE TITLE
Possible issue with low alpha blending

### ISSUE THREAD

**Issue by einaros** [Automattic/node-canvas#111]
I'm seeing a sort-of strange issue with blended transparent painting operations with fillRect / drawImage / etc. when the alpha value for each single painting operation is low enough. node-canvas tends to yield a slightly darker result than the browsers I've tested this with. Any thoughts on why?

Blending multiple colors, and especially when the colors are in the light-ish range, will yield even more obvious differences between browsers and node-canvas. For an example of that, try painting a few strokes at http://draw.2x.io, with the top right brush, set to opacity 0.1 and a light color. Mix a few colors, then reload the page to see what node-canvas produces.

Here's a testable piece of code to see the difference for 10 stacked fillRects with 0.008 alpha.

``` javascript
var canvas = require('canvas');
var express = require('express');

function paint(ctx) {
    ctx.fillStyle = 'rgba(255,0,0,0.008)';
    for (var i = 0; i < 10; ++i) {
        ctx.fillRect(0, 0, 20, 20);
    }
}

var webServer = express.createServer();
webServer.listen(8000);
webServer.get('/state', function(req, res) {
    res.header('Cache-Control', 'no-cache');
    res.contentType('image/png');
    var ctx = new canvas(20, 20).getContext('2d');
    paint(ctx);
    var stream = ctx.canvas.createPNGStream();
    stream.on('data', function(chunk) {
        res.write(chunk);
    });
    stream.on('end', function(chunk) {
        res.end();
    });
});
webServer.get('/', function(req, res) {
    res.header('Cache-Control', 'no-cache');
    res.send('<img src="/state"></img><canvas id=canvy width=20 height=20 />' + 
             '<script>var ctx = document.getElementById("canvy").getContext("2d");' + 
             paint.toString().replace(/.*?{\n/, '').replace(/\s*\n}$/, '') + 
             '</script>');
});
```

**Comment by zbjornson** [comment]
Sounds like this is working acceptably.
