### ISSUE TITLE
Can't seem to be able use custom font

### ISSUE THREAD

**Issue by Wodki** [Automattic/node-canvas#1117]
## Issue or Feature
I can't seem to be able to use custom font. I get no errors or anything, its just that the end result doesn't have any text written on it.

## Steps to Reproduce

```js
const { registerFont, createCanvas, Image } = require('canvas');
registerFont('./assets/fonts/some_font.ttf', {family: 'custom_font'});

var canvas = createCanvas(200, 200);
var ctx = canvas.getContext('2d');
var img = new Image();

img.src = fs.readFileSync('./assets/images/some_random_image.png');
ctx.drawImage(img, 0, 0);

ctx.font = '20px custom_font';
ctx.fillText(100, 100, 'Something!');
fs.writeFileSync('./assets/canvas_images/result.png', canvas.toBuffer());
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.11
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v8.10.0 on win7

**Comment by Hakerh400** [comment]
`ctx.fillText(100, 100, 'Something!');`

should be

`ctx.fillText('Something!', 100, 100);`

**Comment by LinusU** [comment]
It would be interesting to see if the browsers throw any errors in a similar situation, in that case, we should as well.
