### ISSUE TITLE
undefined symbol Image::error while compiling with VS 2015 (win)

### ISSUE THREAD

**Issue by timknip** [Automattic/node-canvas#1123]
Building using `mingw64` and `VS 2015` [borks here](https://github.com/Automattic/node-canvas/blob/master/src/Image.cc#L385) when using `HAVE_RSVG`. `Image::error` doesn't seem to be implemented. Strange thing is it compiles fine on Linux. Maybe a compiler thing?
Anyway: seems a good idea to implement `Image::error`.

Note: the combination `mingw64` / `VS 2015` works great, also with `HAVE_RSVG`.
Checked out some [windows code here](https://github.com/node-gfx/node-canvas-prebuilt)

**Comment by zbjornson** [comment]
You linked to a line with `Canvas::Error` -- is that what you meant?

**Comment by timknip** [comment]
@zbjornson Yes. `error` is [declared](https://github.com/Automattic/node-canvas/blob/master/src/Image.h#L89) in `Image.h`, but there's no implementation. Hence the undefined symbol.

**Comment by zbjornson** [comment]
Oh! I see it now :).

GCC might be treating that as the `error` function attribute, not sure.

**Comment by timknip** [comment]
@zbjornson Unrelated: a `npm i` on `alpha.10` borks on with a 404 on a non-existing pre-built url (makes sense as there's no pre-built binaries for `alpha.10`. Would expect a fallback on build though. `npm i` doesn't get there.

**Comment by zbjornson** [comment]
@timknip I think that's #1111. 2.0.0-alpha.11 falls back to a build.

**Comment by Khorynthium** [comment]
I've got a fix for related #1205. But It was closed as a dup of this issue. So, here we go: https://github.com/Automattic/node-canvas/pull/1206
