### ISSUE TITLE
Drop support for Node.js 4.x?

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#1126]
Node.js 4.x goes out of life in little over a month. How do we feel about dropping support for that version (and 5.x) in Canvas 2.0?

I think it could be a good idea to get this in before releasing 2.0, since we otherwise need to support Node 4.x for the entire lifespan of 2.x. This might not seem problematic right now, but might be in the future as Node moves forward.

It seems like people have been better moving away from Node.js 4.x than they were with 0.x. When 0.10 went EOL it had an 11% market share. When 0.12 went EOL it had a 5% market share. Version 4.x currently holds at 7%.

ref: [node market share](https://docs.google.com/spreadsheets/d/1J6TxXIfGOqV9cx1qEFGSXHCma4JHfKPzlsMWfbGmDbE/edit#gid=0), [node versions](https://github.com/nodejs/Release)

ping @zbjornson @chearon

**Comment by chearon** [comment]
You certainly won't hear me complain about it. We'd get rest, spread, and my favorite - destructuring.

**Comment by zbjornson** [comment]
Done in #1177
