### ISSUE TITLE
Not installing on Ubuntu 11.04

### ISSUE THREAD

**Issue by adamjv90** [Automattic/node-canvas#113]
From a clean install this was my prep:

sudo apt-get install build-essential
sudo apt-get install libssl-dev
sudo apt-get install libcairo2-dev libjpeg8-dev

also install most current version of node and npm exactly how instructions tell you to.

when trying to install i get this:

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /home/ubuntu/local/node 
Checking for library gif                 : not found 
Checking for library jpeg                : yes 
Checking for cairo                       : yes 
'configure' finished successfully (0.275s)
Waf: Entering directory `/home/ubuntu/local/node/lib/node_modules/canvas/build'
[1/9] cxx: src/CanvasRenderingContext2d.cc -> build/default/src/CanvasRenderingContext2d_1.o
[2/9] cxx: src/CanvasGradient.cc -> build/default/src/CanvasGradient_1.o
../src/CanvasRenderingContext2d.cc: In constructor ‘Context2d::Context2d(Canvas*)’:
../src/CanvasRenderingContext2d.cc:128:25: warning: converting to non-pointer type ‘short int’ from NULL
[3/9] cxx: src/PixelArray.cc -> build/default/src/PixelArray_1.o
[4/9] cxx: src/color.cc -> build/default/src/color_1.o
../src/color.cc:189:1: warning: converting to non-pointer type ‘uint32_t’ from NULL
[5/9] cxx: src/Canvas.cc -> build/default/src/Canvas_1.o
../src/Canvas.cc: In static member function ‘static v8::Handle<v8::Value> Canvas::ToBuffer(const v8::Arguments&)’:
../src/Canvas.cc:201:73: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Canvas.cc:201:73: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
Waf: Leaving directory `/home/ubuntu/local/node/lib/node_modules/canvas/build'
Build failed:  -> task failed (err #1): 
	{task: cxx Canvas.cc -> Canvas_1.o}
npm ERR! error installing canvas@0.7.0 Error: canvas@0.7.0 preinstall: `node-waf configure build`
npm ERR! error installing canvas@0.7.0 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing canvas@0.7.0     at ChildProcess.<anonymous> (/home/ubuntu/local/node/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing canvas@0.7.0     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing canvas@0.7.0     at ChildProcess.onexit (child_process_legacy.js:246:12)
npm ERR! canvas@0.7.0 preinstall: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the canvas@0.7.0 preinstall script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.38-8-virtual
npm ERR! command "node" "/home/ubuntu/local/node/bin/npm" "install" "-g" "canvas"
npm ERR! cwd /home/ubuntu
npm ERR! node -v v0.5.5-pre
npm ERR! npm -v 1.0.26
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/npm-debug.log
npm not ok

**Comment by LinusU** [comment]
Closing this since we aren't using node-waf anymore...
