### ISSUE TITLE
Builds are broken for macOS on node versions 4-6

### ISSUE THREAD

**Issue by chearon** [Automattic/node-canvas#1134]
## Issue or Feature

Build fails on node versions 4-6

## Steps to Reproduce

Using `nvm` or similar, if you `npm install canvas@next` while on node versions 4, 5, and 6, you'll get `fatal error: 'cstdint' file not found` from `color.h`.

You can see which (ABI) versions worked/didn't work by the binaries available [here](https://github.com/node-gfx/node-canvas-prebuilt/releases/tag/v2.0.0-alpha.12).

It's because the Node version determines the libc++ version, and the older versions of Node use a clang version that I guess doesn't have that `cstdint` for some reason. I think the fix might be to use `cstdint.h`. I'll open a PR.

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.12
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 4-6 on macOS

**Comment by zbjornson** [comment]
Aye... v6.x:

https://github.com/nodejs/node/blob/fe71f19b4d5a727ba3d5060d02351e8d302538c6/common.gypi#L399-L402

v8.x:

https://github.com/nodejs/node/blob/ce751b15db0b84d4e0a70223dda734fbc064751a/common.gypi#L403-L407

using libc++ enables Clang's C++11 mode, and cstdint came with C++11.
