### ISSUE TITLE
[question] node-canvas wrong image data

### ISSUE THREAD

**Issue by nnwy** [Automattic/node-canvas#1136]
## Issue or Feature
i tried using image data on node-canvas and I experienced wrong values in buffer

## Steps to Reproduce

this is my code, I pasted in node.js and in browser and got different outputs, how can it be possible?

```js
const {Canvas} = require(".\\node_modules\\canvas");

const ctx = new Canvas(2, 1).getContext("2d");
const imgd = ctx.createImageData(2, 1);
const data = imgd.data;

data.forEach((a, b) => data[b] = b);
ctx.putImageData(imgd, 0, 0);
ctx.drawImage(ctx.canvas, 1, 0);

const result = ctx.getImageData(0, 0, 2, 1).data;
console.log(result);
```

here is output:

* **Chrome:** `Uint8ClampedArray [ 0, 0, 0, 3, 0, 0, 0, 9 ]`
* **Node-canvas:** `Uint8ClampedArray [ 0, 0, 0, 3, 0, 0, 0, 10 ]`

why does node-canvas output 10 instead of 9 at the end? Is this a bug, or ?

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 200
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 980 on windows 10

**Comment by zbjornson** [comment]
In Firefox I get `[ 0, 85, 85, 3, 25, 51, 51, 10 ]`.
In Safari 11 I get `[0, 0, 0, 3, 0, 0, 0, 10]`.

So maybe by majority ... the 10 is correct, and the 0s are correct? :)

I'm not sure what's going on here. It might be how images are sampled at the edges, which I don't think is in the Canvas spec.

**Comment by nnwy** [comment]
@zbjornson 
Maybe I have choosen a bad example. Sampling edges is not well-defined in the standard, but drawing images should be precisely defined. Take a look at this example:

```js
var ctx = new Canvas(500, 500).getContext("2d");

ctx.fillStyle = "#fff";
ctx.fillRect(0, 0, 500, 500);

ctx.fillStyle = "#000";
ctx.fillRect(0, 0, 10, 10);
ctx.drawImage(ctx.canvas, 10, 10);
```

# All modern browsers

![](https://user-images.githubusercontent.com/33158743/37957021-327dc800-31ad-11e8-8086-22441b7eaeb1.png)

# node-canvas

![](https://user-images.githubusercontent.com/33158743/37957011-2f9becd4-31ad-11e8-87f2-e8a28d66ebe4.png)

**Comment by chearon** [comment]
Looks like the issue is with drawing the canvas to itself? I don't know if the `getImageData` numbers indicate anything more than a small rounding difference though.

**Comment by nnwy** [comment]
@ chearon,

probably you are right, that is why I said that I had choosen a bad example. But anyway, this example demonstrates unexpected behavior, right? I mean, is this a bug, or is this allowed to happen, so should I change the title from `[question]` to `[bug]`?

sorry my bed english

**Comment by chearon** [comment]
All good, thanks for reporting it! It's definitely a bug, and I was able to reproduce it. We probably need to copy the canvas to a buffer before drawing it.
