### ISSUE TITLE
'CAIRO_STATUS_INVALID_SIZE was not declared' error in V1.6.10

### ISSUE THREAD

**Issue by heyiwang** [Automattic/node-canvas#1138]
The following error occurred when I tried to install v1.6.10

../src/Image.cc: In member function ‘cairo_status_t Image::loadGIFFromBuffer(uint8_t*, unsigned int)’:
../src/Image.cc:543:12: error: ‘CAIRO_STATUS_INVALID_SIZE’ was not declared in this scope
     return CAIRO_STATUS_INVALID_SIZE;
            ^

gcc version:    4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)

installed all dependencies by yum.

And If anyone is encountering the same problem, just try to install v1.6.9, this works fine for me.

**Comment by zbjornson** [comment]
RHEL 4 I think is from 2009 with most support ending in March 2017. It would be good to look at upgrading your OS.
