### ISSUE TITLE
heroku installation woes

### ISSUE THREAD

**Issue by jgreene** [Automattic/node-canvas#114]
I've been attempting to install node-canvas on heroku the last couple of days and have hit a brick wall.  The problem boils down to it's dependence upon the cairo library and the "node-waf configure build" wscript that checks for it's existence.  Since we can't install libraries directly on heroku I attempted placing the precompiled libraries in the /app/bin folder (which is in heroku's $PATH), then I set the PKG_CONFIG_PATH to /app/bin/pkgconfig so that "pkg-config --libs cairo" could find the library (which is basically what the wscript calls to see if it exists), finally I ensured that the .pc files in the /app/bin/pkgconfig directory were modified to properly point to the libraries/header files in /app/bin.

All of this works fine on my local machine, so I'm not really sure this should be considered an _issue_ for the node-canvas project, but I've been unable to get around this limitation in heroku and was hoping someone with more knowledge could help me get it running, or suggest some changes to the node-canvas package that could help with the cairo dependency issues.

**Comment by zbjornson** [comment]
I just successfully installed canvas 2.0.0-alpha.12 and 1.6.11 on the vanilla heroku-16 stack. Both just worked thanks to prebuilds. If anyone has a need to make a from-source build work, I can look into it.

**Comment by bensheldon** [comment]
Wooot! 🎉
