### ISSUE TITLE
Error loading shared libraries on alpine because of prebuilt(?)

### ISSUE THREAD

**Issue by iCrawl** [Automattic/node-canvas#1140]
I recently decided to upgrade from the master build I was running off this repo which was around `2.0.0-alpha.9` to the latest `2.0.0-alpha.12` just to get greeted with some nice errors on my alpine docker container.

I am aware that I can stay at `alpha.9` but it would be in my best interest to keep my software updated, esp when I see commits like `[...] fixed memory leak [...]`

## Issue or Feature
Any version above `2.0.0-alpha.9` throws
```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/Tohru/node_modules/canvas/build/Release/libpixman-1.so.0)
```
in Alpine Linux after installing and executing the code.

First thing I tried was adding `--build-from-source` to `yarn install` but that obviously didn't work out as I expected it to.
I assume what's happening here is that it tries to always use a prebuilt version regardless and that it correlates to this issue afterwards? https://github.com/node-gfx/node-canvas-prebuilt/issues/31

## Steps to Reproduce
Just run any Alpine Dockerfile (for reproduce cases `node:8-alpine` I guess) with those packages.

```Dockerfile
#  Install dependencies
RUN apk add --update \
&& apk add --no-cache ffmpeg opus pixman cairo pango giflib ca-certificates \
&& apk add --no-cache --virtual .build-deps git curl build-base jpeg-dev pixman-dev \
cairo-dev pango-dev pangomm-dev libjpeg-turbo-dev giflib-dev freetype-dev python g++ make \
\
# Install node.js dependencies
&& yarn install --build-from-source \
\
# Clean up build dependencies
&& apk del .build-deps
```

It will work fine on `2.0.0-alpha.9` but not anything above that (since node-pre-gyp got added) basically.
Is there anyway to go back to the old behavior that alpha.9 used? Since that works perfectly fine.

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.10 - 2.0.0-alpha.12
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 8.x.x on Alpine Linux

**Comment by chearon** [comment]
It should not try to use prebuilt with that argument, no. Did you install it like this?

```
yarn add canvas@next --build-from-source
```

It worked for me. In NPM that argument doesn't work if it goes before the package name.

**Comment by iCrawl** [comment]
Not really?

As you can see above I am using a simple `yarn install` or `yarn` (since those are interchangeable) to install all my packages defined in the package.json after copying over the `package.json` and the `yarn.lock` file and it doesn't seem to apply in this case.

**Comment by Dev-Yukine** [comment]
I agree to what @iCrawl said since i encountere exactly the same issue and would love to have that fallback method to build itself so i could actuall use the newest beta version.

**Comment by chearon** [comment]
No longer a problem in the next release thanks to #1156

**Comment by ryedin** [comment]
This seems to still be an issue, unless I'm just doing something wrong.

After `npm install canvas@next`, I get `"canvas": "^2.0.0-alpha.12",` in my package.json...

My dockerfile has this:
```
RUN apk --no-cache --virtual .build-deps add \
        python \
        make \
        g++ \
    && apk --no-cache --virtual .canvas-build-deps add \
        build-base \
        cairo-dev \
        jpeg-dev \
        pango-dev \
        giflib-dev \
        pixman-dev \
        pangomm-dev \
        libjpeg-turbo-dev \
        freetype-dev \
    && apk --no-cache add \
        pixman \
        cairo \
        pango \
        giflib \
    && npm install \
    && apk del .build-deps \
    && apk del .canvas-build-deps
```

And I still get the following error:
`Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/built/node_modules/canvas/build/Release/libpixman-1.so.0)`

I'm unsure what to do based on this thread, which seems to indicate it "should just work now"

**Comment by ryedin** [comment]
ugh, nevermind. I was missine the `--build-from-source` flag in my `npm install` command. I guess I was assuming that @chearon's last comment here was indicating it would somehow detect that I was in an environment not supported by the prebuilts (alpine). 

I was also missing `libjpeg` but I think I'm now on my way.

**Comment by Ugzuzg** [comment]
@ryedin, your expectations were correct, but there was no release since that commit, so nothing actually changed.

**Comment by ryedin** [comment]
ah :) - makes total sense now. I just assumed since that was May 4th that a release had been made. My bad!

ty

**Comment by JakinMiao** [comment]
> ugh, nevermind. I was missing the `--build-from-source` flag in my `npm install` command. I guess I was assuming that @chearon's last comment here was indicating it would somehow detect that I was in an environment not supported by the prebuilts (alpine).
> 
> I was also missing `libjpeg` but I think I'm now on my way.

i have the same problem. can you send me your dockerfile to me?
