### ISSUE TITLE
Do results of drawing methods depend on platform/OS?

### ISSUE THREAD

**Issue by szimek** [Automattic/node-canvas#1141]
## Issue
I'm writing tests for my drawing library. Unfortunately, while all tests pass on my Mac, they fail on Linux (I tried it with Docker and Travis CI).

In my tests I'm comparing raw image data via `ctx.getImageData(...)`, because `Canvas#toDataURL` seems likely to be platform dependent as well (https://github.com/Automattic/node-canvas/issues/853). However, I'm getting slightly different image data on Mac and Linux.

Is it supposed to work like this? Is there any option I can set to make results independent of the platform/OS?

## Steps to Reproduce
I'm clearing the canvas with `"rgba(0,0,0,0)"` color and then I draw with `"black"` color.

The whole drawing code looks like this:
```js
ctx.beginPath();
ctx.fillStyle = "black";

// in a loop
ctx.moveTo(x, y);
ctx.arc(x, y, width, 0, 2 * Math.PI, false);

ctx.closePath();
ctx.fill();
```

It looks like alpha channel values are slightly higher on Linux. This is a small gist of the diff between images (it's `<Linux RGBA> !== <Mac RGBA> at <pixel index>`):
```
0,0,0,148 !== 0,0,0,144 at 28039
0,0,0,210 !== 0,0,0,207 at 28040
0,0,0,255 !== 0,0,0,254 at 28041
0,0,0,238 !== 0,0,0,239 at 28070
0,0,0,184 !== 0,0,0,182 at 28071
0,0,0,119 !== 0,0,0,118 at 28072
0,0,0,1 !== 0,0,0,0 at 28074
0,0,0,18 !== 0,0,0,15 at 28341
0,0,0,75 !== 0,0,0,74 at 28342
```

## Your Environment
* canvas-prebuilt 1.6.5-prerelease.1, jsdom 11.6.2 and jest 22.4.3
* node v9.11.1 on Mac OS X 10.3.4
* node v9.11.1 on Docker `node:latest` image

**Comment by advanceddeveloper** [comment]
See https://github.com/Automattic/node-canvas/issues/1136

As I know, WHATWG standard doesn't define how image should look like at pixel level. Therefore, image data may slightly differ between implementations (and between platforms as well). Node-canvas uses cairo-graphics as it's backed, so their algorithms may differ between platforms (just guessing).

Also, as I can see from your log, only alpha values differ. That is probably the result of sampling images at the edges, as mentioned in the comments of the linked issue.

**Comment by szimek** [comment]
Thanks! 

That sucks though, because I hoped to use `node-canvas` together with [Jest](https://facebook.github.io/jest/) to generate snapshots of the canvas based on a hash (e.g. md5) of raw image data.

I guess I'll need to figure out something else for my tests. I could store all image data (instead of just a hash) and make the test pass if values are "close enough", but it feels wrong ;)

**Comment by LinusU** [comment]
@szimek I would recommend looking at [looks-same](https://www.npmjs.com/package/looks-same)
