### ISSUE TITLE
Canvas.Font works in macOS but fails in Ubuntu

### ISSUE THREAD

**Issue by challakoushik** [Automattic/node-canvas#1147]
the code I'm using goes like this

```
var Canvas = require('canvas')
var Chalkduster = new Canvas.Font(
    'Chalkduster',
    path.join(__dirname, '../public/fonts', 'chalkduster.ttf')
)
Chalkduster.addFace(path.join(__dirname, '../public/fonts', 'chalkduster.ttf'), 'bold');

//jsdom code
var canvas_dom = window.document.createElement('canvas')
canvas_dom.width = 594;  canvas_dom.height = 420;
var context = canvas_dom.getContext("2d");
context.addFont(Chalkduster)
context.font = 'normal 14px Chalkduster';

context.fillStyle = '#000000';
context.fillText('Sample Text',0.5*canvas_dom.width,0.5*canvas_dom.height)
```

The same code works in my macbook but doesnt work on my ubuntu server. I get standard arial type font on the output in ubuntu

**Comment by challakoushik** [comment]
I found the fix to this issue after almost giving up.
need to uninstall pango, uninstall canvas and then reinstall canvas as mentioned in  https://github.com/kangax/fabric.js/issues/3272


s```
udo apt remove libpango1.0-dev
npm uninstall canvas
npm install canvas
```

**Comment by fadonascimento** [comment]
@challakoushik This

> I found the fix to this issue after almost giving up.
> need to uninstall pango, uninstall canvas and then reinstall canvas as mentioned in [fabricjs/fabric.js#3272](https://github.com/fabricjs/fabric.js/issues/3272)
> 
> ```
> sudo apt remove libpango1.0-dev
> npm uninstall canvas
> npm install canvas
> ```

This work like a charm, Thanks a lot @challakoushik! We save me a lot of time.
