### ISSUE TITLE
C4324: 'canvas_jpeg_error_mgr': structure was padded due to alignment specifier & 'v8::String::Utf8Value::Utf8Value': was declared deprecated

### ISSUE THREAD

**Issue by advanceddeveloper** [Automattic/node-canvas#1159]
Hello, its me again

I am trying to build node canvas from source, but I am getting few warnings:

```console
warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated
warning C4324: 'canvas_jpeg_error_mgr': structure was padded due to alignment specifier
```

The first one is repeated multiple times and in multiple files, but the second one appears in image.cc, so I am guessing utf8value:utf8value should be replaced with something other, since it says it is deprecated. I dont get such warning in node v8.5.0, but only in node 10.

Is the second warning indicating that something is wrong, or are you aware of it? I mean, it says that something is padded, should it be padded, or should it not be padded?

r_

**Comment by zbjornson** [comment]
The alignment warning can be ignored. A few more bytes will be used but no harm otherwise. We can either silence it, or embed the base `jpeg_err_mgr` in another struct instead of extending it.

**Comment by advanceddeveloper** [comment]
> We can silence it

That would be nice. Every time I compile I think something is wrong when I see yellow text all over my screen.

But what about Utf8Value deprecation? I think it will be permanently removed in a few semvermajor node versions (when it gets removed from v8), which will break build completely. I think v8 team explained in their blog which alternative functions should be used instead.

**Comment by zbjornson** [comment]
Yep, definitely a to-do.
