### ISSUE TITLE
Greyscale JPEGs are interpreted as color.

### ISSUE THREAD

**Issue by aperiodic** [Automattic/node-canvas#117]
Pretty much what it says on the tin. For example, if I load up [a greyscale image of the yalta conference](http://i.imgur.com/BrPWa.jpg), the output is [horizontally compressed to one-third of its previous width](http://i.imgur.com/eg2Nc.png).  For reference, I gisted [the script used to generate that output](https://gist.github.com/1225735).

**Comment by zbjornson** [comment]
This was fixed (in 2012) in https://github.com/Automattic/node-canvas/commit/4a3caeb25fde2e02455b847c2c82173e191b42a9. Test added in #1246.
