### ISSUE TITLE
Writing text on image in custom Language, with custom fonts.

### ISSUE THREAD

**Issue by drexdelta1** [Automattic/node-canvas#1174]
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (version 2.0.0-alpha):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

I am writing 'Hindi' language text on image ('यह.  मिसिसिपी   है') . This is the text. 
![kmkxt](https://user-images.githubusercontent.com/38881717/41023203-57cfdddc-6989-11e8-89b8-072a40f81b11.png)

The written text is grammatically wrong. I have also asked same question in SO as well. but no response yet :( .

**Comment by drexdelta1** [comment]
https://github.com/Automattic/node-canvas/issues/1169

Found related problem here. says can't be done due to system fonts properties. not node-canvas problem.

**Comment by chearon** [comment]
Yours sounds more lie a shaping issue, since all the glyphs are there.

Which operating system are you on? Could you try `canvas-prebuilt` instead of `canvas`? It has more up-to-date dependencies.
