### ISSUE TITLE
Can't find Python executable "python" using YARN ADD

### ISSUE THREAD

**Issue by mike03081972** [Automattic/node-canvas#1181]
Downloaded python from : https://www.python.org/downloads/release/python-361/
Install it to : C:\Python36\
Set environment variable PYTHON to : C:\Python36\python.exe
Set python to YARN config : yarn config set python 'C:\Python36\python.exe'

Install canvas to my project like this : yarn add canvas --dev

Error received :

`yarn add v1.7.0
warning package.json: No license field
info No lockfile found.
warning canvas-test@0.0.1: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\canvas-test\node_modules\canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\canvas-test\viewer\node_modules\canvas
Output:
C:\canvas-test\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "'C:\Python36\python.exe'", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\canvas-test\node_modules\canvas
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Comment by zbjornson** [comment]
node-gyp needs python 2; python 3 won't work. Not sure if that's the only issue, but start with that...

**Comment by zbjornson** [comment]
Closing since there's been no reply and the likely issue is python 3 vs. python 2.
