### ISSUE TITLE
PiTFT image is streamed to /dev/sd1 but its shifted/interlaced

### ISSUE THREAD

**Issue by brainlessboy** [Automattic/node-canvas#1182]
Hi,

## Issue
back a few weeks you supported us streaming canvas output straight to a PiTFT hat. The screen i used (HyperPixel) it works very well, but when i use another PiTFT it fails and only shows an image that is recognisable but pixels are sifted and wrong colors.

## Steps to Reproduce
is use following code directly executed on the RaspbrerryPi
```
var fs = require('fs');
var fb = fs.openSync(Visualizer.frame_buffer_target, "w");
var buff = canvas.toBuffer("raw"); // buff is a Buffer containing RGB15_565 data
fs.writeSync(fb, buff, 0, buff.byteLength, 0);
```
epending of the scrren you are using it might show a good result or show a interlaced/shifted image that will show a barely recognisable image.

i use the latest node.js 10.x and canvas@next which runs smoothly on the raspberryPi 3

## Request/Question
Probably the pixel format is not exactly correct for some PiTFT screens, i use fbi to test if the screen is well placed and every thing is well soldered, in all cases i get a smooth image when using fbi to send an image to the PiTFT. 
Is there a way to play with the formats or to tinker a bit in order to figure out how the format should be ?

thanks !

**Comment by zbjornson** [comment]
That suggests that the canvas size is wrong, that the PiTFT doesn't use 565, and/or that it pads scan lines or something. Your best bet is to use ioctl to query the device. You could try [this](https://github.com/jerome-pouiller/ioctl) or maybe [this](https://www.npmjs.com/package/ioctl) to do so. (2nd one looks harder to use.)

**Comment by brainlessboy** [comment]
@zbjornson thanks!

i tried both and i failed with both, i am really not sure what the output would or could be from any of the methods, the first method fails at compiling on the raspberry. for the second method i get the following error message when trying to probe the /dev/fb1 (where the pitft is connected), also i really don't know what i am actually doing ...

```
/home/pi/spghty/ioctl.js:37
    var ret = ioctl(fd, TCGETA, info.ref());
              ^

Error: ENOTTY, Inappropriate ioctl for device
    at /home/pi/spghty/ioctl.js:37:15
    at FSReqWrap.oncomplete (fs.js:169:20)
```
also when i run my script to output canvas /dev/fb1 images i get 

```
frame buffer is set to on but no frame buffer is present Error: EFBIG: file too large, write
```

also an indicator that for 320x240 the image is probably to large (again it does display something but stretched and scrabled but recognisasble)

what kind of infromation would you expect from ioctl?

thans again

**Comment by brainlessboy** [comment]
i retested with fbi with the following output (may be an indicator)
```
sudo fbi -T 2 -d /dev/fb1 -noverbose -a adapiluv320x240.jpg

Fontconfig warning: ignoring UTF-8: not a valid region tag
using "DejaVu Sans Mono-16", pixelsize=16.67 file=/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
```

**Comment by brainlessboy** [comment]
i tried the following,
```
const canvas = createCanvas(320, 240, {pixelFormat: "RGB16_565"});
or
const canvas = createCanvas(320,240);
```

but has no effect ...

**Comment by zbjornson** [comment]
I don't have much experience with this stuff to help more. The goal was to get the resolution and any other potential nuances about the device from ioctl. You'd probably be better off asking on https://raspberrypi.stackexchange.com/ or similar where you'll hopefully get some people with hardware experience.

**Comment by brainlessboy** [comment]
AH!
i went through the documentaiton one more time ... i changed it to

```
const canvas = createCanvas(320,240);
const ctx = canvas.getContext('2d',{pixelFormat: "RGB16_565"});
```

the create canvas with the pixelformat is wrong it has to be provided to the getContext function ... 
now it works!!

**Comment by brainlessboy** [comment]
many thanks!
