### ISSUE TITLE
toBuffer callback never called

### ISSUE THREAD

**Issue by pravdomil** [Automattic/node-canvas#1184]
## Bug
Try to run code bellow and the toBuffer callback will be never called.

## Steps to Reproduce
```js
const { createCanvas } = require("canvas")

const canvas = createCanvas(100, 100, "pdf")
canvas.toBuffer((err, buf) => {
  console.log("result", { err, buf }) // never called
})
```

## Your Environment
* Version of node-canvas: 2.0.0-alpha.12
* Environment: node 10.1.0, macOS 10.13.5

**Comment by zbjornson** [comment]
See #821.
