### ISSUE TITLE
Can't install via npm: stack Error: EACCES: permission denied

### ISSUE THREAD

**Issue by ArthurMalet** [Automattic/node-canvas#1188]
Hi everyone, 
I can't get to install Canvas. Still having the same issue.
I tried to follow the step by step guide, tried to install via home-brew, tried to run the command as admin, and I always got the same error:

## Issue

```
> canvas@1.6.11 install /Users/me/Dev/project/node_modules/canvas
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/me/Dev/project/node_modules/canvas/build'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/9.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/Dev/project/node_modules/canvas
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN socket@1.0.0 No description
npm WARN socket@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.11 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/me/.npm/_logs/2018-06-25T12_51_45_488Z-debug.log
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): None
* Node version: v9.5.0
* NPM version: 6.1.0
* OS: Mac Os High Sierra 10.13.4

Any help would be very nice...
Many thanks in advance...

**Comment by ArthurMalet** [comment]
Hmm... Well...
I had the 'illegal group name" message. So I just ran` sudo chown -R yourusername: ~/Dev/project.` (without group name).
It worked... 
I don't understand because I was running `npm install canvas ` as administrator. I'm gonna read some things about that... 
Thank you so much, sorry for being so attended

**Comment by chearon** [comment]
No worries!

**Comment by GaganHC** [comment]
@chearon Hi, I'm getting the same error with few modules. I tried the command you suggested but it does nothing. What does it suppose to do?

**Comment by chearon** [comment]
`chown -R yourusername:yourusername folder` sets the owner and group of all files and folders to your user and group. If it didn't output anything that means it was successful, but maybe try `chmod -R 755 folder` too. The first command fixes issues caused by running npm or yarn from sudo, so make sure you're not doing that!

**Comment by Mephiztopheles** [comment]
> `chown -R yourusername:yourusername folder` sets the owner and group of all files and folders to your user and group. If it didn't output anything that means it was successful, but maybe try `chmod -R 755 folder` too. The first command fixes issues caused by running npm or yarn from sudo, so make sure you're not doing that!

good idea man!
i was running npm install with sudo... changing the owner temporary and installed as normal user

**Comment by horlah** [comment]
I also had similar issue, I got the solution here https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by oussama1elottri** [comment]
!!
don't forget : before apply what guys says above , remove the current file that come from your attempts to install by run `npm remove <here type software you want install (truffle or canvas .... )>`
