### ISSUE TITLE
fillText/strokeText MaxWidth Not Implemented?

### ISSUE THREAD

**Issue by jeffv** [Automattic/node-canvas#119]
It appears that when using fillText and strokeText the optional maxWidth parameter does nothing.

http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#text-0

**Comment by denkan** [comment]
Seems like this still hasn't been implemented yet, tested @2.0.0-alpha.1.
Would be nice to have it working like the browsers; squeezing the font to more narrow style to make it fit. 

Would help if I could. Really appreciate your effort on this package.

**Comment by chearon** [comment]
All it does in Chrome (last I checked) is `scale(maxWidth / actualWidthOfText)` if the actual width is bigger. It'd be very easy for us to implement but also easy to do outside of canvas if you don't want to wait.

**Comment by denkan** [comment]
@chearon: nice one, I give it a try
