### ISSUE TITLE
node-pre-gyp Can't find module ../

### ISSUE THREAD

**Issue by Krajiyah** [Automattic/node-canvas#1200]
## Context
I need the v2 features of font changes for text overlays, so need to use alpha version of this module.

## Environment
* Version of node-canvas: 2.0.0-alpha.12
* Environment: node 10.1.0, npm 6.0.1, azure linux OS (web app resource)

## Issue
I am able to install the alpha module locally just fine (npm i canvas@next --save). However, when I am trying to deploy this to my azure web app resource (same node and npm version), I am not able to install canvas. I have ssh'd into the resource and gone through installation steps for an ubuntu/debian OS before I tried to deploy. I have verified that other node modules in my app have installed, its just the canvas module that is giving me issues. 

This is the error message from the azure deployment:

```sh
Running "/opt/nodejs/10.1.0/bin/node" "/opt/npm/6.0.1/node_modules/npm/bin/npm-cli.js" install --production

> canvas@2.0.0-alpha.12 install /home/site/wwwroot/node_modules/canvas
> node-pre-gyp install --fallback-to-build
remote: internal/modules/cjs/loader.js:573
remote: 
remote:     throw err;
remote:     ^
remote: 
remote: Error: Cannot find module '../'
remote:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
remote:     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
remote:     at Module.require (internal/modules/cjs/loader.js:626:17)
remote:     at require (internal/modules/cjs/helpers.js:20:18)
remote:     at Object.<anonymous> (/home/site/wwwroot/node_modules/node-pre-gyp/bin/node-pre-gyp:15:20)
remote:     at Module._compile (internal/modules/cjs/loader.js:678:30)
remote:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
remote:     at Module.load (internal/modules/cjs/loader.js:589:32)
remote:     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
remote:     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

**Comment by Rutulpatel7077** [comment]
+1 need help installation

**Comment by luankefei** [comment]
+1

**Comment by Rutulpatel7077** [comment]
### Here I found the solution is:
**Remove** node_modules
**remove** package-lock.json
**Delete this folder** "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\"

Restart your computer.... 


Do **npm install** 

and then **npm install node-canvas**

**Comment by JinRi-coding** [comment]
I meet same situation.

So I did do like this!

npm install
npm install canvas

And run it!
