### ISSUE TITLE
node-pre-gyp permission denied issue.

### ISSUE THREAD

**Issue by gete76** [Automattic/node-canvas#1210]
## Issue or Feature

npm install fails with

canvas@2.0.0-alpha.12 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 126

when installing on Vagrant Ubuntu16.04 
## Steps to Reproduce

```
npm install canvas
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.12
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Vagrant/VirtualBox ubuntu/xenial  and VMWare ubuntu/xenial VM. 
Node 8.11.3

## Notes
I eventually got the install to work by upgrading the node-pre-gyp package. 
It seems the canvas package always wants to use its local node-pre-gyp which 
currently requires a 0.9 version.   Upgrading that package to .10 allowed the install to complete properly. I think the solution might be to increase the version number for node-pre-gyp in the package.json file

**Comment by zbjornson** [comment]
package.json is set to use 0.11.0 now. If you're still having issues, let us know and I'll reopen.

**Comment by gavserve** [comment]
I'm experiencing the same problem.
