### ISSUE TITLE
GIF output?

### ISSUE THREAD

**Issue by wassgha** [Automattic/node-canvas#1214]
I am able to read from a gif, however only the first frame is rendered, is there a way to output an animated gif?

**Comment by zbjornson** [comment]
No, there's no built-in way to read a specific frame from a GIF or to write a multi-frame animated gif. You could use something like this: https://www.npmjs.com/package/gifencoder#example-streaming-api---reads

**Comment by frizurd** [comment]
> I am able to read from a gif, however only the first frame is rendered, is there a way to output an animated gif?

Sorry. super late but were you able to animate GIF on node-canvas?
