### ISSUE TITLE
pre-built binaries missing for canvas@2.0.0-alpha.13

### ISSUE THREAD

**Issue by marcsyp** [Automattic/node-canvas#1217]
## Issue or Feature
I've been building to a Docker container for a few months now with success (albeit a lot of deprecation warnings).  My package.json had my node version set to "^2.0.0-alpha.12", so my most recent build tried to install alpha.13, and failed.

It appears that pre-built binaries are missing when installing alpha.13.

## Steps to Reproduce
Install 
## Your Environment
* Node 9.7.1 on Windows 10
* ^2.0.0-alpha.12 
* Built in a docker container pushed to Heroku

Here is the log from the failed 2.0.0-alpha.13:

`> canvas@2.0.0-alpha.13 install /node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.13/canvas-prebuilt-v2.0.0-alpha.13-node-v57-linux-glibc-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for canvas@2.0.0-alpha.13 and node@8.11.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.87-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/node_modules/canvas/build/Release/canvas-prebuilt.node" "--module_name=canvas-prebuilt" "--module_path=/node_modules/canvas/build/Release" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /node_modules/canvas
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/node_modules/canvas/build/Release --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.9.87-linuxkit-aufs
node-pre-gyp ERR! command "/usr/local/bin/node" "/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node_modules/canvas
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/node_modules/canvas/build/Release --napi_version=1 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.0.0-alpha.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.0.0-alpha.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-05T23_07_22_497Z-debug.log
The command '/bin/sh -c npm install --production' returned a non-zero code: 1
 !    Error: docker build exited with 1`

And the log from the successful 2.0.0-alpha.12:

'=== Building web (C:\Users\marcs\Documents\Bitbucket\hashgear-server\Dockerfile)
Sending build context to Docker daemon  32.59MB
Step 1/5 : FROM node:8
 ---> 4635bc7d130c
Step 2/5 : COPY package.json package.json
 ---> dc355161b1f4
Step 3/5 : RUN npm install --production
 ---> Running in 7eba3e4c7064
npm WARN deprecated libcipm@1.6.3: This version mistakenly dropped node@4 compatibility in a semver-patch release. Please stay on 1.6.2 or update to 2 or latest
npm WARN deprecated npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN notice [SECURITY] mime has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.3.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.9.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> canvas@1.6.11 install /node_modules/text2png/node_modules/canvas
> node-gyp rebuild

make: Entering directory '/node_modules/text2png/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function 'boolean empty_closure_output_buffer(j_compress_ptr)':
../src/JPEGStream.h:42:108: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at ../../../../nan/nan.h:929) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, argv);
                                                                                                            ^
../src/JPEGStream.h: In function 'void term_closure_destination(j_compress_ptr)':
../src/JPEGStream.h:63:113: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at ../../../../nan/nan.h:929) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, data_argv);
                                                                                                                 ^
../src/JPEGStream.h:71:112: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at ../../../../nan/nan.h:929) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, end_argv);
                                                                                                                ^
../src/Canvas.cc: In static member function 'static void Canvas::ToBufferAsyncAfter(uv_work_t*)':
../src/Canvas.cc:221:31: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../../../nan/nan.h:1618) [-Wdeprecated-declarations]
     closure->pfn->Call(1, argv);
                               ^
../src/Canvas.cc:226:31: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../../../nan/nan.h:1618) [-Wdeprecated-declarations]
     closure->pfn->Call(2, argv);
                               ^
../src/Canvas.cc: In function 'cairo_status_t streamPNG(void*, const uint8_t*, unsigned int)':
../src/Canvas.cc:377:102: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at ../../../../nan/nan.h:929) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure->fn, 3, argv);
                                                                                                      ^
../src/Canvas.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)':
../src/Canvas.cc:446:103: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at ../../../../nan/nan.h:929) [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);
                                                                                                       ^
../src/Canvas.cc:452:103: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at ../../../../nan/nan.h:929) [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);
                                                                                                       ^
../src/Canvas.cc: In function 'cairo_status_t streamPDF(void*, const uint8_t*, unsigned int)':
../src/Canvas.cc:476:77: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at ../../../../nan/nan.h:929) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), closure->fn, 3, argv);
                                                                             ^
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
../src/Image.cc: In member function 'void Image::loaded()':
../src/Image.cc:380:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../../../nan/nan.h:1618) [-Wdeprecated-declarations]
     onload->Call(0, NULL);
                         ^
../src/Image.cc: In member function 'void Image::error(v8::Local<v8::Value>)':
../src/Image.cc:393:26: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../../../nan/nan.h:1618) [-Wdeprecated-declarations]
     onerror->Call(1, argv);
                          ^
../src/Image.cc: At global scope:
../src/Image.cc:685:13: warning: 'void jpeg_mem_src(j_decompress_ptr, void*, long int)' defined but not used [-Wunused-function]
 static void jpeg_mem_src (j_decompress_ptr cinfo, void* buffer, long nbytes) {
             ^
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  COPY Release/canvas.node
make: Leaving directory '/node_modules/text2png/node_modules/canvas/build'

> canvas@2.0.0-alpha.12 install /node_modules/canvas
> node-pre-gyp install --fallback-to-build

[canvas] Success: "/node_modules/canvas/build/Release/canvas-prebuilt.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
added 899 packages in 29.758s
Removing intermediate container XXXX
 ---> XXXX
Step 4/5 : COPY . .
 ---> XXXX
Step 5/5 : CMD ["npm","start"]
 ---> Running in XXXX
Removing intermediate container XXXX
 --->XXXX
Successfully built XXXX
Successfully tagged registry.heroku.com/hashgear-server/web:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
=== Pushing web (C:\Users\marcs\Documents\Bitbucket\hashgear-server\Dockerfile)
The push refers to repository [registry.heroku.com/hashgear-server/web]
-snip-
Your image has been successfully pushed. You can now release it with the 'container:release' command.
 !    heroku container:push no longer creates a release.
 !    Run heroku container:release to create a release with this image.'

**Comment by chearon** [comment]
[Done](
https://github.com/node-gfx/node-canvas-prebuilt/releases/tag/v2.0.0-alpha.13)
