### ISSUE TITLE
can't install canvas 1.6.11，key word:CAIRO_STATUS_INVALID_SIZE was not declared

### ISSUE THREAD

**Issue by Athrunsky** [Automattic/node-canvas#1220]
i try to install canvas 1.6.11 on CentOS 6.5
node version is v9.3.0
gcc version is 4.9.1

when i check 'sudo npm install' and dialog throw error like this:
../src/Image.cc:543:12: ERROR：‘CAIRO_STATUS_INVALID_SIZE’ was not declared in this filed.
     return CAIRO_STATUS_INVALID_SIZE;
            ^
make: *** [Release/obj.target/canvas/src/Image.o] err 1
make: Leaving directory `/data1/nodejs_api/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/node-v9.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 2.6.32-431.23.3.el6.x86_64
gyp ERR! command "/root/node-v9.3.0-linux-x64/bin/node" "/root/node-v9.3.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data1/nodejs_api/node_modules/canvas
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN baas@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-08T10_28_33_663Z-debug.log

shoud i update my GCC version?

**Comment by Athrunsky** [comment]
by the way :
i read Installation and check this beforce npm install:

```
[root@iZ25hvjm22fZ nodejs_api]# sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel
Loaded plugins: security
Setting up Install Process
Package cairo-1.8.8-6.el6_6.x86_64 already installed and latest version
Package cairo-devel-1.8.8-6.el6_6.x86_64 already installed and latest version
Package cairomm-devel-1.8.0-2.1.el6.x86_64 already installed and latest version
Package libjpeg-turbo-devel-1.2.1-3.el6_5.x86_64 already installed and latest version
Package pango-1.28.1-11.el6.x86_64 already installed and latest version
Package pango-devel-1.28.1-11.el6.x86_64 already installed and latest version
Package pangomm-2.26.0-1.el6.x86_64 already installed and latest version
Package pangomm-devel-2.26.0-1.el6.x86_64 already installed and latest version
Package giflib-devel-4.1.6-3.1.el6.x86_64 already installed and latest version
Nothing to do
```
i think this problem is not about dependencies?

**Comment by LinusU** [comment]
> ERROR：‘CAIRO_STATUS_INVALID_SIZE’ was not declared in this filed.

Hmm, could it be that the version of Cairo is too old? 🤔

**Comment by LinusU** [comment]
Yeah, seems like you need at least Cairo 1.10.

https://cairod.github.io/cairoD/api/cairo/c/cairo/cairo_status_t.CAIRO_STATUS_INVALID_SIZE.html

We should probably document this somewhere...

**Comment by Athrunsky** [comment]
@LinusU thanks recive quickly
I will update my Cairo and try again
thanks:)

**Comment by Athrunsky** [comment]
@LinusU sorry for bothering again
I have roll back my servers without any cairo env
and download cairo 1.15 from cairographics.org
after tar, './configure --prefix=/usr/local' and 'make && make install'
npm install still failed and throw same infomation again

should i update some env about cairo?
btw,when i make install cairo,there have no error but say this:
`----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------`

it means i need to update LD_LIBRARY_PATH?

**Comment by LinusU** [comment]
Hmm, yeah, I think you need to make sure that `LD_LIBRARY_PATH` includes `/usr/local/lib`.

Something like this would probably do it:

```js
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
npm install canvas
```

Also, sorry that you are having troubles with this. Getting native dependencies to be a smooth experience haven't gone too well. I hope that in the future we'll be able to utilise WebAssembly or the [replacement for node-pre-gyp from NearForm](
https://www.nearform.com/blog/the-future-of-native-modules-in-node-js/) to make this easier!

**Comment by Athrunsky** [comment]
@LinusU 
Thanks.
I follow your instructions but problem still exists.
Sorry that i have to solved with other way because my project deadline is coming 
I uninstall CentOS 6.5 and change CentOS 7.4 on it, and error is gone, code is running on my new OS
I think there are some software version problems in CentOS6 with default env.

Thank you for your patience in answering my question.

**Comment by brian-d3view** [comment]
Hi, I was running into this exact issue with CentOS 6.4. I didn't have the option to upgrade to CentOS 7 as Athrunsky was able to. 

I have installed Cairo 1.10.0, which according to make install installed to /usr/local/lib, and updated my LD_LIBRARY_PATH as follows:
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" 

Doing so gave me the same issue, so I replaced the header files in /usr/include/cairo with the files in /usr/local/include/cairo and everything worked on CentOS 6.4. (I don't know if this is the best approach, but trying to add the header files path /usr/local/include to C_INCLUDE_PATH didn't work)
