### ISSUE TITLE
cannot find module '../build/release/canvas.node' error

### ISSUE THREAD

**Issue by naveen-gowda** [Automattic/node-canvas#1221]
I was able to successfully install canvas module as per their documentation and to meet my requirement i had to update the canvas module binding.gyp file to support the jpeg files

I was able to rebuild the canvas successfully without any errors except a bunch of warnings. But post build i even notice that the file canvas.node exists in the specified path. However when i try to consume it in my application it shoots up the error "The specified module could not be found" '../build/release/canvas.node'. I'm not sure if i'm missing something here, please suggest.

If I set "with_jpeg%" flag to false and rebuild then i do not see any errors while consuming the canvas module.

System Configuration

Windows Server 2016 - 64 Bit
node - v8.11.3
npm - v5.6.0
node-gyp - v3.8.0

canvas - v1.6.11

python - v2.7.14
msvs_version - 2015
GTK - gtk+-bundle_2.22.1-20101229_win64
jpeglib - libjpeg-turbo-1.5.3-vc64

binding.gyp changes for jpeg support
```
'with_jpeg%': 'true', 
'libjpeg_root%': 'C:/libjpeg-turbo64',
..
['with_jpeg=="true"', {
  'defines': [
    'HAVE_JPEG'
  ],
  'conditions': [
    ['OS=="win"', {
     'copies': [{
        'destination': '<(PRODUCT_DIR)',
        'files': [
          '<(libjpeg_root)/bin/jpeg62.dll',
        ]
      }],
      'libraries': [
         '-l<(libjpeg_root)/lib/jpeg.lib'
      ],
      'include_dirs': [
        '<(libjpeg_root)/include'
      ]
    }, {
      'libraries': [
        '-ljpeg'
      ]
    }]
  ]
}]
```

Test Code which i'm executing

`var Canvas = require('canvas');`

Error
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: The specified module could not be found.
\\?\c:\..\build\Release\canvas.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\IQCanvas\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by naveen-gowda** [comment]
I tried with the latest version of canvas2.0 and i see the same issue even there

**Comment by zbjornson** [comment]
1.x doesn't support JPEG on Windows, so I wouldn't expect what you described in the first post to work.

With 2.x/master, you used the unmodified binding.gyp file, or did you still have modifications?

**Comment by naveen-gowda** [comment]
Your comment about 1.x doesn't support on Windows has got me into more confusion and the reason being, I tried the installation of canvas 1.x with JPEG support on my laptop which has Windows 10.1 - 64 bit it worked without any issues. I even tried by dumping the compiled libraries from my laptop to the Windows Server 2016 machine and i still noticed the same issue.

With 2.x, i set only the 'with_jpeg%': 'true'
node ./util/win_jpeg_lookup had the right paths and rebuild was successful as well.

**Comment by naveen-gowda** [comment]
I'm sorry for being incomplete in my previous post, even after the successful rebuild the issue still persists.

**Comment by blueboomer76** [comment]
After renaming `freetype6.dll` to `libfreetype-6.dll` as in #1192, I tested `const c = require("canvas")` and got the same error at module.js, line 681, the same error in the mentioned issue and this one.

    Error: The specified module could not be found.
    \\?\C:\Users\Q2\Desktop\kendraBot\node_modules\canvas\build\Release\canvas.node

I opened the file `node_modules/canvas/lib/bindings.js` in the error stack and saw this code:

    'use strict';
    
    module.exports = require('../build/Release/canvas.node');

I looked at `node_modules/canvas/build/Release/canvas.node` and just see a random bunch of characters when opening with Notepad++. I am on 32-bit Windows 10 with node 8.11.1 and canvas 1.6.12.

**Comment by zbjornson** [comment]
@blueboomer76 that's different from the original issue in this thread. I'll reply in #1192 to keep this issue on-topic.

**Comment by zbjornson** [comment]
Er, in #704 since that's the relevant open issue.

**Comment by tettusud** [comment]
Any luck? I have the same issue as mentioned.succesfully installed canvas-prebuilt but when i launch the application it throws error

**Comment by akinnee** [comment]
I seem to get this after installing a new dependency. But if I delete node_modules and reinstall this error goes away.

**Comment by das-solo** [comment]
> I seem to get this after installing a new dependency. But if I delete node_modules and reinstall this error goes away.

@akinnee Did you just do a normal npm install to get it working. I have tried a normal install, node gyp and building from source with no success?
