### ISSUE TITLE
How can I install canvas on a Linux Distro named "Solus" it uses eopkg.?

### ISSUE THREAD

**Issue by TheOnlyArtz** [Automattic/node-canvas#1222]
How can I install canvas on a Linux Distro named "Solus" it uses eopkg.

**Comment by TheOnlyArtz** [comment]
Ok so I managed to find the right packages and managed to successfully install Canvas.
`sudo eopkg it libjpeg-turbo6 libjpeg-turbo-devel` 
Hope this helps for any Solus user out there!

**Comment by LinusU** [comment]
Feel free to add it to the wiki 👍

**Comment by zbjornson** [comment]
https://github.com/Automattic/node-canvas/wiki/Installation:-Solus added, along with my guess at the full list of packages you need (ignoring what might already be installed, e.g. cairo and pango).

**Comment by Underground992** [comment]
tc://?v=2&id=2e786ae5b50b23f164f64ea169082bbeb19bcfe08421791d62cb7c5c946d4f70&r=%7B%22manifestUrl%22%3A%22https%3A%2F%2Ftonstakers.com%2Fdapp%2Ftonconnect-manifest.json%22%2C%22items%22%3A%5B%7B%22name%22%3A%22ton_addr%22%7D%5D%7D
