### ISSUE TITLE
Make Image’s src property configurable

### ISSUE THREAD

**Issue by azangru** [Automattic/node-canvas#1224]
There was a [pull request](https://github.com/Automattic/node-canvas/pull/1049) this winter to make the `currentTransform` property on the Context2d prototype configurable. The reason being, `Jest`, in its infinite wisdom, tries to do its magic in watch mode and [breaks](https://github.com/facebook/jest/issues/3552#issuecomment-322303946) if an exported module has a property set with `Object.defineProperty` method without the `configurable` option.

Now, it seems that 2 months ago the `Image` prototype was refactored, and it now gets its `src` property [using `Object.defineProperty`](https://github.com/Automattic/node-canvas/blob/master/lib/image.js#L18-L73). It means that Jest is now failing again:

![image](https://user-images.githubusercontent.com/6834224/44436090-e688ea00-a5bb-11e8-83f1-10d8c8879a7b.png)

Should the `configurable` option be added when defining the `src` property on Image, just as it was done for the `currentTransform` property on Context2d?

**Comment by zbjornson** [comment]
It's configurable in Chrome at least, so that's good with me:

```
> Object.getOwnPropertyDescriptor(Image.prototype, "src")
{get: ƒ, set: ƒ, enumerable: true, configurable: true}
```

PR welcome, should be an easy change! Thanks for finding.
