### ISSUE TITLE
Your wiki page for Windows installation has been defaced.

### ISSUE THREAD

**Issue by louh** [Automattic/node-canvas#1226]
Your wiki page for Windows, installation, currently linked from the package's [README](https://www.npmjs.com/package/canvas), appears to have been defaced. See here: https://github.com/Automattic/node-canvas/wiki/Installation---Windows/544a5db9e14dc4a5ae9841987ed9ad8e81ebdcc9

The last good revision appears to be four revisions back: https://github.com/Automattic/node-canvas/wiki/Installation---Windows/dc81104b4ffaf89c1c50b0e04b1b7794ea706cd4

**Comment by zbjornson** [comment]
Thanks. That page isn't even supposed to exist, the correct one is https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows. I keep deleting it and it keeps coming back. Deleted again.
