### ISSUE TITLE
node-canvas crashes when encoding big canvas

### ISSUE THREAD

**Issue by hhelwich** [Automattic/node-canvas#1232]
When i encode a big canvas to a JPG stream, node-canvas crashes instead of reporting an error.

## Steps to Reproduce

Run the following script with node:

```js
const Canvas = require('canvas');
const size = 123456789;
const canvas = new Canvas(size, size);
const stream = canvas.jpegStream();
stream.on('error', () => { console.log('error'); });
stream.on('end', () => { console.log('end'); });
```

It crashes and returns exit code `1`. The `error` and `end` callbacks are not called.

## Environment
* Version of node-canvas: 1.6.11
* Environment: node 9.11.1 on Ubuntu 17.10

**Comment by hhelwich** [comment]
@Hakerh400 Will it also be merged in the current version (1.x branch)?

**Comment by zbjornson** [comment]
Closing since 2.0 is finally out 🚀
