### ISSUE TITLE
Optional FFmpeg support

### ISSUE THREAD

**Issue by Hakerh400** [Automattic/node-canvas#1244]
According to the number of [open issues](https://github.com/Automattic/node-canvas/issues?q=is%3Aissue+is%3Aopen+label%3A%22Images+%26+Formats%22) labeled as `Images & Formats`, it seems that users need more than node-canvas internal image decoding implementation can offer. The idea described in this feature request is to add optional FFmpeg support for decoding such image formats.

The FFmpeg would be optional. Node-canvas doesn't need to ship with FFmpeg binaries. The algorithm would work like this:

```
loadImage:
  Try to load the image using standard node-canvas implementation
  If the image is loaded successfully:
    Done
  else, if there is no FFmpeg present in the PATH:
    Throw an error like before
  else (if there is FFmpeg available):
    Try to decode the image using FFmpeg
    If it succeeds:
      Construct an image from the obtained image data
    else:
      Throw an error
```

This solution:

1. Doesn't increase node-canvas dependencies - FFmpeg is optionally installed by a user, independently of node-canvas
2. Doesn't break existing code - if there's no FFmpeg, standard error would be thrown as before
3. Solves 14 open issues and probably more issues that may be reported in the future

### Tests

There may be tests, but it requires installing FFmpeg binaries in the Travis environment.

### Further actions

Relying on FFmpeg support for some formats doesn't mean node-canvas can't have internal support for those formats in the future. Once node-canvas starts supporting a new image format, that implementation will be used, but until then, node-canvas may rely on FFmpeg, making it transparent for users (users that have FFmpeg installed doesn't need to worry about spawning FFmpeg process, nor about intalling 3rd-party dependencies that provide FFmpeg support - everything should be done internally by node-canvas lib).

/cc @zbjornson @LinusU
I would like to hear your opinion. If you think this would improve user experience, I'll open PR.

**Comment by zbjornson** [comment]
Interesting idea! A lot of the open issues are from sort of unusual images (uncommon header chunks) -- does FFmpeg handle all of the example images in those issues? (Guessing it does since it's the Swiss Army Knife.)

BTW I stumbled across some abandoned commits a few months ago from @c-spencer that look like they might fix a few of the open issues: https://github.com/c-spencer/node-canvas/commit/b43a6de1d249fd5dba094150e973c5e8f27d121a, https://github.com/c-spencer/node-canvas/commit/9bbce4b69abc01edce21128adb9d0ea0577c9bf6. Sometime I'd like to look at pulling them in (or whoever gets a chance to before me).

**Comment by Hakerh400** [comment]
> Does FFmpeg handle all of the example images in those issues?

Yes. Besides that, FFmpeg supports 350 different file formats and more than 200 pixel formats.

>  I stumbled across some abandoned commits a few months ago from @͏c-spencer that look like they might fix a few of the open issues

That's great. But that's also not a problem here, since FFmpeg should be just a fallback option.

I'm preparing PR and will probably open it next week.
