### ISSUE TITLE
prebuilt is missing librsvg

### ISSUE THREAD

**Issue by ckirmse** [Automattic/node-canvas#1248]
## Issue or Feature
Hi node-canvas team! Thanks for making and continuing to build a great project. I am using the new svg reading support using librsvg, and it it works great for me. However, I believe that the prebuilt files that you distribute do not include librsvg and so building/deploying is more difficult than it is to use the other libraries (gif, jpeg, etc.). Would you mind including librsvg and a canvas.node that depends on in going forward?

## Your Environment

* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha-13
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 10 on Linux

**Comment by chearon** [comment]
I can do that when I release the newest alpha. See also node-gfx/node-canvas-prebuilt#12.

**Comment by chearon** [comment]
SVG builds are working but not released yet. In the past, changing the builds on existing versions caused problems. @LinusU if we expect the next version to be 2.0.2, I can publish the new builds tonight.

**Comment by LinusU** [comment]
@chearon just tagged and released 2.1.0 👌
