### ISSUE TITLE
Prebuilt: runtime error `undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv` after creating multiple canvases

### ISSUE THREAD

**Issue by Ytawo** [Automattic/node-canvas#1252]
## Issue
After creating a large number of canvases, the process crashes with the error message:
```
node: symbol lookup error: /path/to/project/node_modules/canvas/build/Release/canvas.node:
undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv
```

When testing with a standalone file that does nothing but creating canvases, it crashes after creating 100 canvases, but in my real application it crashes after creating the 3rd canvas. I'm guessing that it has to do with the total memory used by the process (as the error kind of indicate)s, which is much higher in my real application than in the standalone file.

I'm on Linux, and this error only happens when the cairo package is not installed. When it's installed everything works well.

## Steps to Reproduce
```js
var Canvas = require('canvas');
var list = [];
for (var i = 0; i < 100; i++) {
  var canvas = Canvas.createCanvas(200, 200);
  var ctx = canvas.getContext('2d');
  list.push({canvas, ctx});
}
```

## Your Environment
* node-canvas `v2.0.0-alpha-14`
* Ubuntu 16.04
* package `libcairo2` NOT installed

**Comment by zbjornson** [comment]
Odd, this same issue came up in opencv 11 days ago: https://github.com/justadudewhohacks/opencv4nodejs/issues/408.

That's a v8 symbol, not cairo, so I don't know why that would matter. Did you rebuild node-canvas after installing libcairo2? If yes, the error would make more sense.

**Comment by Ytawo** [comment]
Indeed the problem came from Node.js, upgrading to the latest version solved the issue! Cairo was not the problem, I must have done something more than installing/uninstalling it during my tests.

Thanks for the help!

**Comment by azangru** [comment]
@zbjornson I too had the same error: when I upgraded node-canvas from `2.0.0-alpha.7` to `2.0.1` and ran my test suite on Node v8.9.4, I was getting the error `undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv` coming from `/node_modules/canvas/build/Release/canvas.node`. The error went away after upgrading Node to the last LTS (`v8.12.0`), at least on my dev machine.

**Comment by matonga** [comment]
Had the same problem, using nodejs from ubuntu/bionic repo (v8.10). After reading comment from @zbjornson decided to switch to nodejs.org repos (to upgrade to v8.12) and it worked. Should report this to Ubuntu maintainers... or wait until they decide to update upstream anyway.

**Comment by vishalpawar048** [comment]
I am already on node 8.12.0 still I have been facing symbol look up error.

**Comment by vishalpawar048** [comment]
My canvas version is 2.0.1 , node 8.12.0, node-gyp 3.8.0. Could anyone please help?

**Comment by matonga** [comment]
Hi @vishalpawar048 I have node 8.12.0 and canvas 2.0.1 too, working fine here. Don't know how to get my node-gyp version, though. What distro are you using? And how do I get my node-gyp version so we can compare?

**Comment by matonga** [comment]
Ok, that's very strange now, I have node-gyp version 3.8.0 too (got it with /usr/lib/node_modules/npm/bin/node-gyp-bin/node-gyp --version)

**Comment by gavinr** [comment]
@zbjornson you are saying that it's fixed at node `v8.12.0`. Since Lambda is at Node v8.10.0, does this mean this bug is preventing usage of this library in AWS Lambda until Lambda updates to `v8.12`?

**Comment by zbjornson** [comment]
@gavinr Yes, I think that is all correct. (That bug in Node.js would affect any library that uses that particular v8 API though.)

**Comment by zbjornson** [comment]
My guess is that it happens when we adjust the externally allocated memory tracking, but I'm not positive. If that's the case, it isn't strictly necessary, but I'm hesitant to remove it also as it aids the GC.

It's a bit cludgey, but you can spawn another version of Node from your Lambda function. I used to do this three years ago when Lambda only supported 0.10: https://github.com/zbjornson/lambda-deploy

Looks like someone just published an updated module that does the same thing:
https://hackernoon.com/so-i-still-cant-run-my-node-js-10-code-on-aws-lambda-or-can-i-d2a9e8b1eeec
