### ISSUE TITLE
Screencasts link in Readme does not work

### ISSUE THREAD

**Issue by curtisj44** [Automattic/node-canvas#1259]
## Issue

The "Screencasts" link in Readme.md does not seem to work: http://screenr.com/CTk

https://github.com/Automattic/node-canvas/blame/master/Readme.md#L57

**Comment by Hakerh400** [comment]
`screenr.com` is down for some reason. The video can be downloaded [here](https://github.com/Automattic/node-canvas/files/2425165/screencast.zip).

**Comment by zbjornson** [comment]
Link removed in #1272. If you guys think it's useful to have still, we can add a direct link, but it's a pretty old screencast now.
