### ISSUE TITLE
Vulnerable dependency

### ISSUE THREAD

**Issue by Doges** [Automattic/node-canvas#1261]
## Issue or Feature
Issue:
Theres a vulnerable dependency on package which is making synk tests failing on canvas package. Package: node-pre-gyp@0.9.1.
If you guys can update that, i will be very thankful to you guys.
also, not a high severity vulnerability, just a medium severity - TOCTOU

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```
Run a check on snyk or another vulnerability check on canvas dependencies

## Your Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
canvas@2.0.0-alpha.16
Windows 10 x64 v1803

**Comment by LinusU** [comment]
Fixed in `2.0.0-alpha.17`, thanks for the report 👍
