### ISSUE TITLE
Trying to create Discord Spoiler Bot, stuck on NPM Install Canvas

### ISSUE THREAD

**Issue by ThatOneDeafKid** [Automattic/node-canvas#1270]
It has been a long time since I have done any type of coding or anything, and I have been trying to do this for a friend's discord server. I am having very little success and am on the 4th fresh attempt.

So far what I have done: 

in my current progress I downloaded chocolatey using Windows Powershell in administrative mode and ran `choco install -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo`, then downloaded GTK (64bit) and extracted it to C:/GTK. I have tried running the command `npm install canvas` like it says, which didn't work. So i created a folder in user/name/projects/spoilerbot, targeted it, tried again with no success. Tried executing the command in CMD, Powershell, and python command line (although I can't figure out how to change the target folder in command line). 

Other things I have tried is installing GTK2 from the website directly, and into c:/gtk2, which i couldnt find cairo within, I made sure c:/GTK and python27 were both in the path, and I tried a whole bunch of things I can't exactly remember yesterday because i was just going in circles, but always got stuck there. 

If you can help, please give very specific instructions (IE what program to run the specific commands and what the exact codes are) as I have not done anything like this in many years. Thank you. 

EDIT: Forgot this:

Full tutorial link im following: https://www.npmjs.com/package/discord-spoiler-bot

Current part (setting up the canvas node): https://github.com/Automattic/node-canvas/wiki/Installation:-Windows

EDIT 2: Ok so i figured out I need to use either node.js command prompt or developer command prompt for VS 2017. However, when i type 
`npm install canvas`
I get these errors
`**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>cd c:/discordbots/spoiler bot

c:\Discordbots\Spoiler Bot>npm install canvas

> canvas@1.6.12 install c:\Discordbots\Spoiler Bot\node_modules\canvas
> node-gyp rebuild

c:\Discordbots\Spoiler Bot\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Discordbots\Spoiler Bot\node_modules\canvas
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'c:\Discordbots\Spoiler Bot\package.json'
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN Spoiler Bot No description
npm WARN Spoiler Bot No repository field.
npm WARN Spoiler Bot No README data
npm WARN Spoiler Bot No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robby\AppData\Roaming\npm-cache\_logs\2018-10-04T22_18_35_660Z-debug.log

c:\Discordbots\Spoiler Bot>`

**Comment by zbjornson** [comment]
Are you able to use `canvas-prebuilt`, either by using Canvas 2.x (automatic prebuilds) or canvas-prebuilt explicitly? See https://github.com/primitybio/cellengine/issues/2480.

I'd avoid the chocolatey instructions because they seem to cause more harm than good (I might delete them even). The manual instructions usually work reliably, although it's possible you'll continue having problems if you have an MSVC setup issue. I haven't seen the particular issues you posted and am not finding much by googling.

**Comment by ThatOneDeafKid** [comment]
I'm not sure what you mean exactly with canvas-prebuilt. The chocolatey instructions seem to get me as far as a friend of mine made it in manual instructions no problem, but I just added git.exe to my paths. 

on "npm install discord-spoiler-bot --save"
git cmd returns this 
C:\Discordbots\botproject>npm install discord-spoiler-bot --save

> canvas@1.6.10 install C:\Discordbots\botproject\node_modules\canvas
> node-gyp rebuild


C:\Discordbots\botproject\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Discordbots\botproject\node_modules\canvas\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Discordbots\botproject\node_modules\canvas
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robby\AppData\Roaming\npm-cache\_logs\2018-10-04T23_07_33_528Z-debug.log

C:\Discordbots\botproject>

while node.js cmd returns this:
C:\Discordbots\botproject>npm install discord-spoiler-bot --save
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/woor/discord.io.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robby\AppData\Roaming\npm-cache\_logs\2018-10-04T23_13_52_633Z-debug.log

C:\Discordbots\botproject>

**Comment by zbjornson** [comment]
Sorry, I pasted the wrong link. That was supposed to be https://github.com/Automattic/node-canvas/wiki/Installation%3A-Prebuilt. That version requires no local compilation.

**Comment by ThatOneDeafKid** [comment]
so in order to use canvas-prebuilt, where would I extract those files to? that seems to be my biggest issue, I don't know where these things need to go

**Comment by zbjornson** [comment]
Since canvas is a dependency of discord-bot, I think the easiest thing to do is fork discord-bot and change its canvas dependency to `canvas-prebuilt` or `canvas@latest` (i.e. run `npm uninstall --save canvas`, `npm install --save canvas-prebuilt` and find/replace `require("canvas")` with `require("canvas-prebuilt")`).

Actually, you'll have to use prebuilt for this, since it it looks like discord-bot requires gif support, and canvas-prebuilt is the only way to get gif support on Windows right now.

**Comment by ThatOneDeafKid** [comment]
I got it to work. I had to delete package.json and package-lock.json and then do the install and it worked fine. Idk what other steps i took before cause I was just running around but that was the main thing that seem to work.
