### ISSUE TITLE
node-pre-gyp ERR! stack Error: 404 status code

### ISSUE THREAD

**Issue by DDeepu** [Automattic/node-canvas#1274]
> canvas-prebuilt@1.6.11 install C:\Jenkins\workspace\MSL-UI-E2E-Tests\node_modules\canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v64-win32-ia32.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Jenkins\workspace\MSL-UI-E2E-Tests\node_modules\node-pre-gyp\lib\install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Jenkins\workspace\MSL-UI-E2E-Tests\node_modules\request\request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:432:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Jenkins\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\NodeJS10.8\\node.exe" "C:\\Jenkins\\workspace\\MSL-UI-E2E-Tests\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install"
node-pre-gyp ERR! cwd C:\Jenkins\workspace\MSL-UI-E2E-Tests\node_modules\canvas-prebuilt
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v64-win32-ia32.tar.gz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-prebuilt@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2018-10-09T23_31_10_965Z-debug.log
Build step 'Execute Windows batch command' marked build as failure
[Cobertura] Publishing Cobertura coverage report...

Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Finished: FAILURE

## Steps to Reproduce
npm install

## Your Environment
* node 10.8
* Windows 10
* npm 6.4.1

**Comment by zbjornson** [comment]
Are you on 32-bit Windows or just using 32-bit Node.js on 64-bit Windows?

Per https://github.com/node-gfx/node-canvas-prebuilt/issues/27#issuecomment-348037675 it's unlikely that 32-bit prebuilds will be made, so you'll likely need to build from source or switch to 64-bit Node.js instead. The instructions for building from source are here: https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows#install-manually

**Comment by DDeepu** [comment]
switching to 64-bit Node.js worked Thank you
