### ISSUE TITLE
Heroku can't install canvas@2.0.0-alpha.18, but can install canvas@2.0.0-alpha.13?

### ISSUE THREAD

**Issue by ghost** [Automattic/node-canvas#1276]
remote:        > canvas@2.0.0-alpha.18 install /tmp/build_e24cec0e993c4ac7435cec
112b8138dd/node_modules/canvas
remote:        > node-pre-gyp install --fallback-to-build
remote:
remote:        Package pangocairo was not found in the pkg-config search path.
remote:        Perhaps you should add the directory containing `pangocairo.pc'
remote:        to the PKG_CONFIG_PATH environment variable
remote:        No package 'pangocairo' found
remote:        gyp: Call to 'pkg-config pangocairo --libs' returned exit status
1 while in binding.gyp. while trying to load binding.gyp
remote:        gyp ERR! configure error
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_e24cec0e9
93c4ac7435cec112b8138dd/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/
lib/configure.js:345:16)
remote:        gyp ERR! stack     at emitTwo (events.js:126:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (intern
al/child_process.js:198:12)
remote:        gyp ERR! System Linux 4.4.0-1027-aws
remote:        gyp ERR! command "/tmp/build_e24cec0e993c4ac7435cec112b8138dd/.he
roku/node/bin/node" "/tmp/build_e24cec0e993c4ac7435cec112b8138dd/.heroku/node/li
b/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallbac
k-to-build" "--module=/tmp/build_e24cec0e993c4ac7435cec112b8138dd/node_modules/c
anvas/build/Release/canvas-prebuilt.node" "--module_name=canvas-prebuilt" "--mod
ule_path=/tmp/build_e24cec0e993c4ac7435cec112b8138dd/node_modules/canvas/build/R
elease" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--no
de_napi_label=node-v57"
remote:        gyp ERR! cwd /tmp/build_e24cec0e993c4ac7435cec112b8138dd/node_mod
ules/canvas
remote:        gyp ERR! node -v v8.12.0
remote:        gyp ERR! node-gyp -v v3.8.0
remote:        gyp ERR! not ok
remote:        node-pre-gyp ERR! build error
remote:        node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_e24c
ec0e993c4ac7435cec112b8138dd/.heroku/node/bin/node /tmp/build_e24cec0e993c4ac743
5cec112b8138dd/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-
gyp.js configure --fallback-to-build --module=/tmp/build_e24cec0e993c4ac7435cec1
12b8138dd/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=c
anvas-prebuilt --module_path=/tmp/build_e24cec0e993c4ac7435cec112b8138dd/node_mo
dules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_ve
rsion=0 --node_napi_label=node-v57' (1)
remote:        node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/bui
ld_e24cec0e993c4ac7435cec112b8138dd/node_modules/node-pre-gyp/lib/util/compile.j
s:83:29)
remote:        node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
remote:        node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7
)
remote:        node-pre-gyp ERR! stack     at maybeClose (internal/child_process
.js:915:16)
remote:        node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexi
t (internal/child_process.js:209:5)
remote:        node-pre-gyp ERR! System Linux 4.4.0-1027-aws
remote:        node-pre-gyp ERR! command "/tmp/build_e24cec0e993c4ac7435cec112b8
138dd/.heroku/node/bin/node" "/tmp/build_e24cec0e993c4ac7435cec112b8138dd/node_m
odules/.bin/node-pre-gyp" "install" "--fallback-to-build"
remote:        node-pre-gyp ERR! cwd /tmp/build_e24cec0e993c4ac7435cec112b8138dd
/node_modules/canvas
remote:        node-pre-gyp ERR! node -v v8.12.0
remote:        node-pre-gyp ERR! node-pre-gyp -v v0.11.0
remote:        node-pre-gyp ERR! not ok
remote:        Failed to execute '/tmp/build_e24cec0e993c4ac7435cec112b8138dd/.h
eroku/node/bin/node /tmp/build_e24cec0e993c4ac7435cec112b8138dd/.heroku/node/lib
/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-
build --module=/tmp/build_e24cec0e993c4ac7435cec112b8138dd/node_modules/canvas/b
uild/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/t
mp/build_e24cec0e993c4ac7435cec112b8138dd/node_modules/canvas/build/Release --na
pi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-
v57' (1)
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! canvas@2.0.0-alpha.18 install: `node-pre-gyp install --f
allback-to-build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the canvas@2.0.0-alpha.18 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely
 additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.WnsgQ/_logs/2018-10-10T21_10_46_515Z-d
ebug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common is
sues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploy
s
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying
-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...

**Comment by zbjornson** [comment]
There's no prebuild yet for alpha.18. It looks like the latest prebuild is alpha.14 (https://github.com/node-gfx/node-canvas-prebuilt/releases).

There are instructions on the wiki for setting up Heroku to build from source. I haven't tried them personally and there are a few past GitHub issues regarding them, YMMV. If you try them and find a way to improve the build, feel free to edit the wiki. https://github.com/Automattic/node-canvas/wiki/Installation%3A-Heroku

**Comment by Despoinis** [comment]
> 
> 
> There's no prebuild yet for alpha.18. It looks like the latest prebuild is alpha.14 (https://github.com/node-gfx/node-canvas-prebuilt/releases).
> 
> There are instructions on the wiki for setting up Heroku to build from source. I haven't tried them personally and there are a few past GitHub issues regarding them, YMMV. If you try them and find a way to improve the build, feel free to edit the wiki. https://github.com/Automattic/node-canvas/wiki/Installation%3A-Heroku

Alpha.14 can't run locally, I am waiting for prebuild.

Error: The specified procedure could not be found.


\\?\r:\asfasf\node_modules\canvas\build\Release\canvas.node

    at Object.Module._extensions..node (module.js:681:18)

    at Module.load (module.js:565:32)

    at tryModuleLoad (module.js:505:12)

    at Function.Module._load (module.js:497:3)

    at Module.require (module.js:596:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (r:\asfasf\node_modules\canvas\lib\bindings.js:3:18)

    at Module._compile (module.js:652:30)

    at Object.Module._extensions..js (module.js:663:10)

    at Module.load (module.js:565:32)

Waiting for the debugger to disconnect...
