### ISSUE TITLE
Artifacts on image after some time

### ISSUE THREAD

**Issue by k1ker** [Automattic/node-canvas#1277]
I make image from 2 png images. 1 is transparent, another one is avatar. But after some time I get some bugs/glitch/artifacts on images.
After restart:
https://cdn.discordapp.com/attachments/499056312488034305/499445121113260043/top-pubg.png
After some time:
https://cdn.discordapp.com/attachments/499056312488034305/499444795773812757/top-pubg.png
https://cdn.discordapp.com/attachments/499056312488034305/499883624427028480/top-pubg.png

How to fix this? 

canvas 2.0.0-alpha.14 (node 10.3.0 on Debian 9)

**Comment by Hakerh400** [comment]
Repeatedly drawing an image causes semi-transparent edges to become opaque.

**Comment by LinusU** [comment]
Hmm, seems like you have some areas which you don't draw on, which seems to have things that were earlier in the memory on it 🤔 

Short term fix for you: draw a white rectangle covering the entire image when creating a new canvas

Long term fix: make sure that newly allocated memory is properly initialized

**Comment by LinusU** [comment]
Ahhhaaa, maybe I was completely wrong 😬 

Are you using the same canvas over and over? Or are you allocating a new one each time?
