### ISSUE TITLE
Mediarecorder feature

### ISSUE THREAD

**Issue by kamakshidasan** [Automattic/node-canvas#1278]
## Issue or Feature
I'm curious to know how I should record a node-canvas. I would like to use the functionality provided by MSE: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder

**Comment by zbjornson** [comment]
I'm not aware of a MediaRecorder implementation for Node.js. Do you mean to record a canvas in a Web browser instead?

**Comment by Hakerh400** [comment]
> I'm curious to know how I should record a node-canvas

Recording canvas frame-by-frame and exporting to mp4 video can be done in less than 30 lines of code using FFmpeg.

**Comment by kamakshidasan** [comment]
I can record a normal canvas in a browser frame by frame, and then export it to ffmpeg. Here is a simple way to do it: https://github.com/fbsamples/Canvas-Streaming-Example

But that's not the question. The question is if this can be done using a node-canvas, running on a server.

**Comment by Hakerh400** [comment]
You don't need a browser. Spawn FFmpeg, write canvas image data to its stdin and do it in an async loop.

**Comment by kamakshidasan** [comment]
This works. Thanks! 

Closing this.
