### ISSUE TITLE
Install fails on AWS EC2, error: jpeg_mem_dest was not declared in this scope

### ISSUE THREAD

**Issue by carlosveloso** [Automattic/node-canvas#1279]
Hello,
Im trying to update to version 2.0.0-alpha.18, but Im getting this error:

```
  In file included from ../src/Canvas.cc:25:0:
  ../src/JPEGStream.h: In function void write_to_jpeg_buffer(cairo_surface_t*, JpegClosure*, unsigned char**, uint32_t*)Y:
  ../src/JPEGStream.h:168:44: error: jpeg_mem_dest was not declared in this scope
     jpeg_mem_dest(&cinfo, outbuff, &ulOutsize);
                                              ^
  make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
  make: Leaving directory `/tmp/deployment/application/node_modules/can
```

the Packages are already installed:
```
libjpeg-turbo.x86_64                                           1.2.90-5.14.amzn1                                          installed
libjpeg-turbo-devel.x86_64                                     1.2.90-5.14.amzn1                                          @amzn-main
```

Didn't have any (major) issues with 1.6 in the same stack.

## Steps to Reproduce
Try to run v2 in an amazon EC2 instance.

## Your Environment
* Version of node-canvas (e.g. 2.0.0-alpha.18):
* Environment (node v8.11.3, Amazon Linux AMI):

Thanks!

**Comment by zbjornson** [comment]
jpeg_mem_dest was added to libjpeg-turbo in 1.3, and you have 1.2.90. Can you upgrade that?

If you don't need jpeg support, you can uninstall libjpeg-turbo and canvas will build without jpeg support.

**Comment by carlosveloso** [comment]
I can't upgrade libjpeg-turbo at the moment, but removing it did the trick (I don't need jpeg support at the moment).

thanks @zbjornson !
