### ISSUE TITLE
drawImage is extremely slow

### ISSUE THREAD

**Issue by visgotti** [Automattic/node-canvas#1283]
I'm trying to write a program that will render and stream video of the gameplay on my server. So it will be receiving json about game data at about 60 fps and will create the scene from it. 

The problem is that getting anywhere near a tolerable frame rate for a live stream is impossible with the slow rendering speed. The following example takes about 800 ms to draw 500 sprites from the same image.. it doubles for every draw call as well. So if I rendered 250 sprites from image A and 250 from image B it would take 1600 ms

HTML5 does this all < 1 ms so I'm wondering why the difference is so much

```
var Canvas = require('canvas')
    , Image = Canvas.Image
    , loadImage = Canvas.loadImage
    , canvas = new Canvas(200, 200)
    , ctx = canvas.getContext('2d');


var fs = require('fs');
var sys = require('sys');

fs.readFile('bunny.png', function(err, bunny) {
    img = new Image;
    img.src = bunny;

    var timeNow = Date.now();
    for(var i = 0; i < 500; i++) {
        ctx.drawImage(img, 50, 50, 50, 50);
    }

    var timeAfter = Date.now();
    console.log('time:', timeAfter-timeNow)
})

```

**Comment by zbjornson** [comment]
I don't think there's much we can do to improve this; 99% of the work here is done by cairo.

On my laptop, your code reports 32 ms however. What's your environment like? It's possible there have been performance improvements in newer versions of cairo.

> it doubles for every draw call as well

Does your image have transparency? This might be because cairo has to deal with compositing transparent images, in which case you might get a speedup by calling `ctx.clearRect(x, y, w, h)` before `drawImage`. I can't reproduce this doubling to test that theory though.

**Comment by asturur** [comment]
800ms vs 1ms seems unreasonable.

HTML canvas makes abundant use of gpu 2d acceleration, every draw operation happens in the GPU and drawimages are super fast ( chrome and firefox at least ) When you go nodejs you are cpu only, one thread.

**Comment by ggolda** [comment]
Is there a way to improve the `drawImage` performance somehow? It still takes a lot of time to draw images. For example for the sample code below it takes ~110ms on my laptop to draw 1080p image:

```js
import { createCanvas, loadImage } from "canvas";

let canvas = createCanvas(1920, 1080);
let context = canvas.getContext('2d');

let image = await loadImage('test.jpg');

for (let i = 0; i < 100; i++) {
  const start = performance.now();
  context.drawImage(image, 0, 0, 1920, 1080);
  i++;
  const end = performance.now();
  console.log(`draw took ${end - start} ms`);
}

```

**Comment by ggolda** [comment]
It looks like that image resizing is what slows everything down. If image is being drawn with native resolution than it takes <1 ms per call.
