### ISSUE TITLE
Difficulties using the repo on PR

### ISSUE THREAD

**Issue by asturur** [Automattic/node-canvas#1287]
I m having difficulties posting comments on PRs.
What i see is this:

![image](https://user-images.githubusercontent.com/1194048/47289601-cb5a4b00-d5fb-11e8-9ca0-f92acfab62fa.png)

This is happening since yesterday night, and i m not sure if it is my fault or a generic github temporary problem.

I  sorry if my tentatives are creating non sense emails of updates.

**Comment by Hakerh400** [comment]
It's Github's fault.
See https://blog.github.com/2018-10-21-october21-incident-report/
Will be fixed soon.

**Comment by asturur** [comment]
i can close then. Thank you.
