### ISSUE TITLE
Memory leaks in asynchronous image saving methods

### ISSUE THREAD

**Issue by Agamnentzar** [Automattic/node-canvas#1296]
## Issue
Memory leaks appear in asynchronous version of `Canvas.toBuffer` method and `Canvas.createPNGStream` method

- `Canvas.toBuffer` causes large memory leak
- `Canvas.createPNGStream` causes small memory leak

## Steps to Reproduce

```js
const fs = require('fs');
const { createCanvas, Image } = require('canvas');

const image = new Image();
image.src = fs.readFileSync('some_test_image.png');

const canvas = createCanvas(image.width, image.height);
canvas.getContext('2d').drawImage(image, 0, 0);

function saveUsingToBuffer(path, canvas) {
	return new Promise((resolve, reject) => {
		canvas.toBuffer((err, buffer) => {
			if (err) {
				reject(err);
			} else {
				fs.writeFile(path, buffer, err => {
					if (err) {
						reject(err);
					} else {
						resolve();
					}
				});
			}
		});
	});
}

function saveUsingSyncToBuffer(path, canvas) {
	return new Promise((resolve, reject) => {
		const buffer = canvas.toBuffer();
		fs.writeFile(path, buffer, err => {
			if (err) {
				reject(err);
			} else {
				resolve();
			}
		});
	});
}

function saveUsingStream(path, canvas) {
	return new Promise((resolve, reject) => {
		const out = fs.createWriteStream(path);
		const stream = canvas.createPNGStream();
		stream.pipe(out);
		out.on('finish', resolve);
		out.on('error', reject);
	});
}

async function test() {
	while (true) {
		// uncomment one test to run
		// await saveUsingSyncToBuffer('test.png', canvas); // synchronous toBuffer() (no leak)
		await saveUsingToBuffer('test.png', canvas); // asynchronous toBuffer() (large leak)
		// await saveUsingStream('test.png', canvas); // createPNGStream() (small leak)
		gc();
	}
}

test();
```

You need to provide some test png image to load `some_test_image.png`
The script will keep saving `test.png` image in current path
Run with `--expose-gc` flag (or comment out call to `gc()`

## Your Environment
* Version of node-canvas: 2.0.1
* Environment: node 9.11.2 on Windows 10 x64

**Comment by zbjornson** [comment]
Confirmed, thanks for the clear repro.

Started working on it here https://github.com/Automattic/node-canvas/compare/master...zbjornson:zb/1296 but there's some heap corruption going on. Sort of uncovered a mess.

**Comment by Lexxxtentacion** [comment]
Do you know if these issues also effect the asynchronous version of `loadImage`?

**Comment by Agamnentzar** [comment]
@Lexxxtentacion just tested sync and async loading of images and it doesn't seem to be affected by any memory leaks.
