### ISSUE TITLE
Error: node-canvas was built without SVG support

### ISSUE THREAD

**Issue by zicodeng** [Automattic/node-canvas#1297]
## Issue

I thought SVG support was added? The doc has example for it.

## Steps to Reproduce

```js
const image = new Image();
image.onload = () => ctx.drawImage(img, 0, 0);
image.onerror = err => {
  throw err;
};
image.src = './Apollo.svg';

or

loadImage(url) does not work with svg either
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): v10.12.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): macOS 10.14

**Comment by zbjornson** [comment]
I assume you're using prebuilds, which don't have SVG support yet (#1248). The work-around is to follow the full installation instructions near the top of the readme or in the wiki pages (https://github.com/Automattic/node-canvas/wiki) to install the dependencies, and use `npm install canvas --build-from-source`. (Yarn does not work with that flag.)

**Comment by zicodeng** [comment]
@zbjornson Aha, I was using yarn. Thanks, will try it again :)

**Comment by chearon** [comment]
2.1.0 has prebuilt SVG support
