### ISSUE TITLE
Hypesquad icon crashes bot with `Unsupported image type`

### ISSUE THREAD

**Issue by AGuyNamedJens** [Automattic/node-canvas#1299]
Bot crashes when a user joins using a hypesquad icon

## Issue or Feature

`Error: Unsupported image type`
This only happends when people join using those "hypesquad" icons, any idea how to fix this?
## Steps to Reproduce

Let someone with a hypesquad icon join your server when bot is active (for example, this image: https://cdn.discordapp.com/avatars/265791495519338496/004dafe5ae0533fc228106b0109b501d that throws this error)

## Your Environment
* Version of node-canvas : latest
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 9.11.1

**Comment by Hakerh400** [comment]
Unable to reproduce the issue. The image loads properly both from URL and from file system. Can you share the minimal code (without external modules) that reproduces the issue?

**Comment by AGuyNamedJens** [comment]
Well nvm, appearently forcing discord to get the user's avatar via .PNG fixed the issue
