### ISSUE TITLE
Failed at the canvas@1.3.12 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by lamphattai100590** [Automattic/node-canvas#1300]
## Issue
I searched those previous issues related to this kind of error and follow all those steps with unlucky. 

I ran this before:
`brew install pkg-config cairo pango libpng jpeg giflib librsvg`
`xcode-select --install`

The below error:

canvas@1.3.12 install /Users/lamphattai/workspace/middleware/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lamphattai/.nvm/versions/node/v4.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/lamphattai/.nvm/versions/node/v4.3.1/bin/node" "/Users/lamphattai/.nvm/versions/node/v4.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lamphattai/workspace/gdam/adbank-5/gdam-frontend/web-frontend/middleware/node_modules/canvas
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
babylon@5.5.29 /Users/lamphattai/workspace/middleware
└── rc@1.2.7 

npm WARN babylon@5.5.29 No repository field.
npm WARN babylon@5.5.29 No license field.
npm ERR! Darwin 18.2.0
npm ERR! argv "/Users/lamphattai/.nvm/versions/node/v4.3.1/bin/node" "/Users/lamphattai/.nvm/versions/node/v4.3.1/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

## Your Environment
* Version of node-canvas: 1.3.12
* Environment: node 4.3.1, npm 3.7.1 on Mac OS X 10.14.1 Mojave, XCode 10.1

I tried a node 8.9.1 and the same error, just for testing. The project can not be upgraded a new version. My colleague uses the same env 4.3.1 and it works and he has no idea what's wrong on mine.

Any help is appreciated cause I'm struggling since 2 days

**Comment by zbjornson** [comment]
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++

Based on that, I think the solution is here: https://github.com/Automattic/node-canvas/issues/1257#issuecomment-425518507

(You're also using a very old version of Canvas; you should upgrade if you can.)

**Comment by lamphattai100590** [comment]
I got this after followings the comment:

2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc:2195:21: error: no member named 'isnan' in namespace
      'std'
    if (a[i] < 0 || isnan(a[i]) || isinf(a[i])) return;
                    ^~~~~~~~~~~
../src/CanvasRenderingContext2d.cc:33:23: note: expanded from macro 'isnan'
#define isnan(x) std::isnan(x)
                 ~~~~~^
../src/CanvasRenderingContext2d.cc:2195:36: error: no member named 'isinf' in namespace
      'std'
    if (a[i] < 0 || isnan(a[i]) || isinf(a[i])) return;
                                   ^~~~~~~~~~~
../src/CanvasRenderingContext2d.cc:34:23: note: expanded from macro 'isinf'
#define isinf(x) std::isinf(x)
                 ~~~~~^
../src/CanvasRenderingContext2d.cc:2229:7: error: no member named 'isnan' in namespace
      'std'
  if (isnan(offset) || isinf(offset)) return;
      ^~~~~~~~~~~~~
../src/CanvasRenderingContext2d.cc:33:23: note: expanded from macro 'isnan'
#define isnan(x) std::isnan(x)
                 ~~~~~^
../src/CanvasRenderingContext2d.cc:2229:24: error: no member named 'isinf' in namespace
      'std'
  if (isnan(offset) || isinf(offset)) return;
                       ^~~~~~~~~~~~~
../src/CanvasRenderingContext2d.cc:34:23: note: expanded from macro 'isinf'
#define isinf(x) std::isinf(x)
                 ~~~~~^
4 errors generated.
make: *** [Release/obj.target/canvas/src/CanvasRenderingContext2d.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lamphattai/.nvm/versions/node/v4.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/lamphattai/.nvm/versions/node/v4.3.1/bin/node" "/Users/lamphattai/.nvm/versions/node/v4.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lamphattai/workspace/middleware/node_modules/canvas
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
babylon@5.5.29 /Users/lamphattai/workspace/middleware
└── rc@1.2.7 

npm WARN babylon@5.5.29 No repository field.
npm WARN babylon@5.5.29 No license field.
npm ERR! Darwin 18.2.0
npm ERR! argv "/Users/lamphattai/.nvm/versions/node/v4.3.1/bin/node" "/Users/lamphattai/.nvm/versions/node/v4.3.1/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lamphattai/middleware/npm-debug.log

**Comment by zbjornson** [comment]
That was fixed in 1.6.3 (you're on 1.3.12).

**Comment by lamphattai100590** [comment]
Is there any way can work around? I can not upgrade this version.

**Comment by zbjornson** [comment]
Building with GCC instead of Clang might work.

**Comment by lamphattai100590** [comment]
Could you show me how do that?

**Comment by zbjornson** [comment]
Once you've installed GCC (try https://discussions.apple.com/thread/8336714), then you need to run

```
env CC=/path/to/gcc CXX=/path/to/g++ npm install canvas
```

Beyond that, I can't help much with an old version of canvas.
