### ISSUE TITLE
Core dump with animation

### ISSUE THREAD

**Issue by piranna** [Automattic/node-canvas#1302]
## Issue
I've adapted updated the code of https://github.com/Automattic/node-canvas/pull/571, and using a modified version of the `clock` example to use the framebuffer backend and update it at intervals, after a number of frames, a core dump is generated. Seems to be always the same number of frames, a lower framerate makes is to appear later. Probably things are queued somewhere or it's a problems regarding garbage collector or memory leaks (probably related to https://github.com/Automattic/node-canvas/issues/1296).

![whatsapp image 2018-11-19 at 14 52 00](https://user-images.githubusercontent.com/532414/48713589-022e7b80-ec11-11e8-9d35-2b8802becdf4.jpeg)
The times shown in the image are of 1fps, 2fps, 4fps, 8fps, 16fps, 30fps and 60fps respectively. Seems there's an invert relation between the number of the fps and the timelapse the application crashes, that's why I think there's some buffer don't get emptied.

## Steps to Reproduce
1. Pick the fork and compile it with `npm install --build-from-source --has_X11=false`.
2. Do a working code that use the framebuffer and update periodically.
3. After about 50 frames, application crashes and a core dump is generated.

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.1.0 (master, with support for FbDev backend)
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 10.12.0 on Ubuntu 18.10

**Comment by zbjornson** [comment]
The live-clock.js example runs fine for me in master. Do you have a repro that happens in master? Otherwise it seems to be a bug in your fork...

**Comment by piranna** [comment]
`life-clock.js` is generating a single frame server side, and serving it as a image `data:` URL to the frontend. How can be able to replicate a live clock and generate multiple frames? Seems the problems is related to this...

**Comment by piranna** [comment]
Ok, the `http-equiv="refresh"` meta tag does the trick. Let me check if I can be able to replicate it in `master` with that.

**Comment by piranna** [comment]
I have done some other tests, both at 60fps and 1fps. I have done several runs and behaviour is consistent, it crash exactly after drawing 46 frames. When drawing at 60fps sometimes get up to 47 or 48, seems the extra ones are due to drawing them so fast.

**Comment by Agamnentzar** [comment]
@piranna You can try replacing `createPNGStream()` with synchronous `toBuffer()` call, if that solves the problem then it's most likely the same issue as #1296

**Comment by zbjornson** [comment]
@piranna did you figure out the source of this issue?

**Comment by piranna** [comment]
> @piranna did you figure out the source of this issue?

No... but as I told in the [previous comment](https://github.com/Automattic/node-canvas/issues/1302#issuecomment-446899626), by merging my fork with upstream master some commits after it's not happening again, so seems efectively it was related to https://github.com/Automattic/node-canvas/issues/1296. I think we can close it now.
