### ISSUE TITLE
createCanvas: undefined symbol

### ISSUE THREAD

**Issue by SpaceboyRoss01** [Automattic/node-canvas#1305]
## Issue or Feature
```
node: symbol lookup error: /home/spaceboyross/NeroUI/node_modules/canvas/build/Release/canvas.node: undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv
```

## Steps to Reproduce
```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.1.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v8,0.0 on Arch Linux

**Comment by zbjornson** [comment]
See #1252 or #1284 -- there's a bug in some versions of Node.js 8.x. You need to use at least 8.12.0.
