### ISSUE TITLE
NPM 404 Redirect, failed 2.2.0 download link access

### ISSUE THREAD

**Issue by hmmhmmhm** [Automattic/node-canvas#1316]
## Issue or Feature

![2](https://user-images.githubusercontent.com/38493722/49392174-feead200-f770-11e8-8ac6-c612eb098215.png)

![1](https://user-images.githubusercontent.com/38493722/49392061-ad424780-f770-11e8-8a57-5ea911c947fa.png)

![3](https://user-images.githubusercontent.com/38493722/49392255-483b2180-f771-11e8-9d2c-cc369b944e6e.png)

Hello~

Although the canvas module is confirmed to have been updated,
It looks like a the download link does not appear to exist yet.

https://github.com/node-gfx/node-canvas-prebuilt/releases/

If the work is still in progress,
please fix release links, thanks

## Steps to Reproduce

Just create new npm project,
and run npm install canvas command.

## Your Environment
node 11.3 on Windows 10 x64

**Comment by chearon** [comment]
Done

@LinusU any more thoughts on waiting on prebuilds in between tagging and releasing? We could make it build when a tag is pushed automatically too, though usually some manual intervention is needed because something like #1317 always happens, or I haven't yet updated the binding.gyp etc

**Comment by LinusU** [comment]
@chearon sorry, haven't looked any more into that 🙈 

Would love to have something automatic, but before that, I could start holding of pushing to npm?

Maybe we could even publish to a special tag, e.g. `next`, and then when the prebuilds are done we can point `latest` to that version as well?

**Comment by chearon** [comment]
> Would love to have something automatic, but before that, I could start holding of pushing to npm?

Yeah, once the (git) tag is pushed the binaries can be built, and after that you can safely release

> Maybe we could even publish to a special tag, e.g. next, and then when the prebuilds are done we can point latest to that version as well?

Sure that works! That might be a little easier for you since you can just it once with NPM instead of having to do the git tag first
