### ISSUE TITLE
Canvas 2.2.0 install broken

### ISSUE THREAD

**Issue by Bramzor** [Automattic/node-canvas#1319]
## Issue or Feature
Version 2.2.0 upgrade is broken while previous version (2.1.0) works perfectly.

Error:
../src/CanvasRenderingContext2d.cc:1810:12: warning: unused variable ‘iso’ [-Wunused-variable]
   Isolate *iso = Isolate::GetCurrent();
            ^~~
canvas.target.mk:134: recipe for target 'Release/obj.target/canvas/src/CanvasRenderingContext2d.o' failed
make: *** [Release/obj.target/canvas/src/CanvasRenderingContext2d.o] Error 1
make: Leaving directory '/home/nodejs/cvcback-development/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.15.0-1021-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/nodejs/cvcback-development/node_modules/canvas/build/Release/canvas-prebuilt.node" "--module_name=canvas-prebuilt" "--module_path=/home/nodejs/cvcback-development/node_modules/canvas/build/Release" "--node_abi_napi=node-v51" "--napi_build_version=0" "--node_napi_label=node-v51"
gyp ERR! cwd /home/nodejs/cvcback-development/node_modules/canvas
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/nodejs/cvcback-development/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/home/nodejs/cvcback-development/node_modules/canvas/build/Release --node_abi_napi=node-v51 --napi_build_version=0 --node_napi_label=node-v51' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/nodejs/cvcback-development/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.15.0-1021-aws
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/nodejs/cvcback-development/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/nodejs/cvcback-development/node_modules/canvas
node-pre-gyp ERR! node -v v7.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 

## Steps to Reproduce
npm install canvas@2.2.0 on a linux machine (or just npm install canvas as 2.2.0 is now the default value)

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
Works:

npm list canvas
├─┬ awesome-qr@1.2.0
│ └── canvas@1.6.13 
└── canvas@2.1.0

Fails:
npm list canvas
├─┬ awesome-qr@1.2.0
│ └── canvas@1.6.13 
└── canvas@2.2.0

**Comment by LinusU** [comment]
Hmm, I can only see a warning in your output, I wonder what caused it to fail 🤔 

Prebuilt binaries for 2.2.0 should be uploaded by now, you could try those by reinstalling ☺️

**Comment by Bramzor** [comment]
Just tried again. Worked on OSX but failed on Linux with following error:

` node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.2.0/canvas-prebuilt-v2.2.0-node-v51-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.2.0 and node@7.6.0 (node-v51 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/nodejs/cvcback-development/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
  CXX(target) Release/obj.target/canvas/src/Backends.o
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc: In static member function ‘static Nan::NAN_SETTER_RETURN_TYPE Context2d::SetCurrentTransform(v8::Local<v8::String>, v8::Local<v8::Value>, Nan::NAN_SETTER_ARGS_TYPE)’:
../src/CanvasRenderingContext2d.cc:1722:49: error: ‘class v8::Object’ has no member named ‘InstanceOf’
   if (!Nan::To<Object>(value).ToLocalChecked()->InstanceOf(ctx, _DOMMatrix.Get(Isolate::GetCurrent())).ToChecked())
                                                 ^~~~~~~~~~
../src/CanvasRenderingContext2d.cc: In static member function ‘static Nan::NAN_SETTER_RETURN_TYPE Context2d::SetStrokeStyle(v8::Local<v8::String>, v8::Local<v8::Value>, Nan::NAN_SETTER_ARGS_TYPE)’:
../src/CanvasRenderingContext2d.cc:1810:12: warning: unused variable ‘iso’ [-Wunused-variable]
   Isolate *iso = Isolate::GetCurrent();
            ^~~
canvas.target.mk:134: recipe for target 'Release/obj.target/canvas/src/CanvasRenderingContext2d.o' failed
make: *** [Release/obj.target/canvas/src/CanvasRenderingContext2d.o] Error 1
make: Leaving directory '/home/nodejs/cvcback-development/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.15.0-1021-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/nodejs/cvcback-development/node_modules/canvas/build/Release/canvas-prebuilt.node" "--module_name=canvas-prebuilt" "--module_path=/home/nodejs/cvcback-development/node_modules/canvas/build/Release" "--node_abi_napi=node-v51" "--napi_build_version=0" "--node_napi_label=node-v51"
gyp ERR! cwd /home/nodejs/cvcback-development/node_modules/canvas
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/nodejs/cvcback-development/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/home/nodejs/cvcback-development/node_modules/canvas/build/Release --node_abi_napi=node-v51 --napi_build_version=0 --node_napi_label=node-v51' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/nodejs/cvcback-development/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:890:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.15.0-1021-aws
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/nodejs/cvcback-development/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/nodejs/cvcback-development/node_modules/canvas
node-pre-gyp ERR! node -v v7.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
`

Seems the prebuild is not available and it fails while trying to build it itself.

**Comment by chearon** [comment]
That's #1317, 2.2.0 doesn't currently work on node 7, but it will work in the next release

**Comment by Bramzor** [comment]
Problem was indeed the version, thanks!

**Comment by rquimbygh** [comment]
Is it expected to see this error with node version 8.9.4?

**Comment by zbjornson** [comment]
@rquimbygh 8.9.7 (node module version 57) and canvas-prebuilt 2.2.0 should work for Linux, Mac and Win x64. What's your environment and what's the exact console output?

**Comment by rquimbygh** [comment]
My environment is Win 10 x64. Upgrading to 8.9.7, then uninstalling and reinstalling node 8.9.4 fixed the issue for me. Thank you for your response @zbjornson, I only have a screenshot of the error I was seeing.
![npm-i-save-canvas-output](https://user-images.githubusercontent.com/3440392/50043508-57f51880-0043-11e9-9db6-6ea3004596a3.jpg)

**Comment by zbjornson** [comment]
Ah, it looks like you had 32-bit ("ia32") Node.js originally, and perhaps when you uninstalled/reinstalled node, you upgraded to x64. Prebuilds only support x64.

**Comment by goldbalaji13** [comment]
i still have this problem can someone help??

**Comment by Serhioromano** [comment]
```
npm i canvas

> canvas@2.6.1 install /mnt/c/Users/serhi/Sites/st-book/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@10.18.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error There was a fatal problem while downloading/extracting the tarball
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/mnt/c/Users/serhi/Sites/st-book/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/mnt/c/Users/serhi/Sites/st-book/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /mnt/c/Users/serhi/Sites/st-book/node_modules/canvas
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/c/Users/serhi/Sites/st-book/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/mnt/c/Users/serhi/Sites/st-book/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/c/Users/serhi/Sites/st-book/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/mnt/c/Users/serhi/Sites/st-book/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/c/Users/serhi/Sites/st-book/node_modules/canvas
node-pre-gyp ERR! node -v v10.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/c/Users/serhi/Sites/st-book/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/mnt/c/Users/serhi/Sites/st-book/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN markdown-it-toc-done-right@4.1.0 requires a peer of markdown-it@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN structured-text-book@1.31.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sergey/.npm/_logs/2019-12-31T12_00_08_239Z-debug.log
```

Same error

```
node -v
v10.18.0
npm -v
6.13.4
```

**Comment by lrettig** [comment]
For the record I got the same error with node15 just now. Switching to node14 (LTS) instead worked.

```
> python --version
Python 3.8.6
> node -v
v14.15.4
> npm -v
6.14.11
```
