### ISSUE TITLE
SVG support: foreignObject node not visible

### ISSUE THREAD

**Issue by FransBosuil** [Automattic/node-canvas#1325]
## Issue
Running the below test does not create the expected result. The canvas should show a green and red rectangle, but, only the green rectangle is visible. It looks like the _foreignObject_ SVG tag is not taken into account. Can you please indicate what I might be doing wrong? Thank you.

## Steps to Reproduce
```js
import { createCanvas, loadImage } from 'canvas'

describe('SVG Test Suite', function () {

  it('should be drawn on canvas', function (done) {
    var svgString = `
        <svg xmlns="http://www.w3.org/2000/svg" width="256" height="256">
          <foreignObject x="0" y="0" width="200" height="200">
              <div xmlns="http://www.w3.org/1999/xhtml" style="background: red; height:100px"></div>
          </foreignObject>
          <rect x="0" y="0" width="100" height="100" fill="green"></rect>
        </svg>
    `.replace(/\n/g, " ").trim()
    console.log(svgString)

    var svgData = 'data:image/svg+xml;base64,' + btoa(svgString)
    console.log(svgData)

    loadImage(svgData).then((svg) => {
      console.log(svg)
      const canvas = createCanvas(256, 256)
      const context = canvas.getContext('2d')
      context.drawImage(svg, 0, 0)
      console.log(canvas.toDataURL('image/png'))
      done()
    })
  })
})
```

## Your Environment
* Version of node-canvas: prebuilt based on v2.2.0
* Environment : node 8.10.0 - ubuntu - jest 23.6.0

**Comment by chearon** [comment]
I don't think librsvg will ever support rendering HTML and CSS :/ that takes a large piece of a web browser to do properly.

**Comment by zbjornson** [comment]
Agreed with @chearon. You might want to use [puppeteer](https://github.com/GoogleChrome/puppeteer) for that.
