### ISSUE TITLE
shadowBlur for Image not working

### ISSUE THREAD

**Issue by bteitelb** [Automattic/node-canvas#133]
Testing node-canvas with this test script https://gist.github.com/1423054 on a machine with Cairo 1.10.0 installed, I am seeing a Gaussian blur shadow for the squares, but not for the arrangement of leaves.  Specifically, I am seeing this:

 ![shade_test](http://ben.teitelbaum.us/tmp/shade_test.png)

Whereas in Chrome, both render with shadowBlur:

 ![shade_test](http://ben.teitelbaum.us/tmp/shade_test_chrome.png)

**Comment by inssein** [comment]
Did anybody find a solution? @woodcoder mentioned what it would take to fix this, just wondering if there has been any movement.

**Comment by PromInc** [comment]
I haven't pursued this any further my self, but no I haven't heard of any progress.

I had toyed with the idea of a kind of 'ugly' workaround of adding a shape layer directly beneath the image in the same size, thus allowing the shadow to be on the 'hidden' shape and creating the illusion that it's on the image.
