### ISSUE TITLE
Broken jpeg data when using toDataURL image/jpeg on 2.3.0

### ISSUE THREAD

**Issue by pstaffan** [Automattic/node-canvas#1350]
## Issue or Feature

The dataURL generated for image/jpeg seems broken on version 2.3.0. It works well on version 2.2.0.
Example: [brokenjpeg.txt](https://github.com/Automattic/node-canvas/files/2752339/brokenjpeg.txt)

## Steps to Reproduce

```js
const {createCanvas, Image} = require("canvas")
const {writeFileSync, readFileSync} = require("fs")

const canvas = createCanvas(800, 50)
const ctx = canvas.getContext("2d")
ctx.fillStyle = 'white';
ctx.fillRect(0, 0, 800, 50);
ctx.font = '16.5pt sans-serif'
ctx.fillStyle = 'black';
ctx.fillText('A B C D E F G H I J K L M N O P Q R S T U V W X Y Z', 10, 30);
canvas.toDataURL('image/jpeg', function (error, dataUrl) {
    console.log(dataUrl);
});
writeFileSync("out.jpg", canvas.toBuffer())
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
canvas@2.3.0

* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
node v10.15.0 on Ubuntu 18 LTS
build-essential is already the newest version (12.4ubuntu1).
libcairo2-dev is already the newest version (1.15.10-2).
libgif-dev is already the newest version (5.1.4-2).
libjpeg-dev is already the newest version (8c-2ubuntu8).
librsvg2-dev is already the newest version (2.40.20-2).
libpango1.0-dev is already the newest version (1.40.14-1ubuntu0.1).

**Comment by zbjornson** [comment]
Hrm, works on Windows but confirmed broken on Ubuntu. Will look at today, thanks for reporting.

**Comment by zbjornson** [comment]
Fix in #1352. BTW your last line is actually producing a PNG; you need `writeFileSync("out.jpg", canvas.toBuffer("image/jpeg"))`.

**Comment by pstaffan** [comment]
Many thanks!! I've tested the changes in my projects test suit and it looks good here

**Comment by LinusU** [comment]
2.3.1 is being released with a fix for this 👍
