### ISSUE TITLE
Text rendering fails when specific fonts are preregistered

### ISSUE THREAD

**Issue by jhuckaby** [Automattic/node-canvas#1362]
I was testing font rendering using [Google Fonts](https://github.com/google/fonts), specifically their [official downloadable TrueType collection - 300 MB](https://github.com/google/fonts/archive/master.zip), and found that quite a lot of them failed to display correctly.  node-canvas (well, probably Pango) seems to silently fall back to something that looks like Helvetica or Arial (e.g. generic sans-serif).  I am seeing this behavior on both macOS and Linux.

Here is a specific case that is easily reproducible macOS 10.12, 10.14, and Linux CentOS 7 using both pre-compiled and source compiled versions of node-canvas 2.3.1.  The font is [Advent Pro Regular](https://fonts.google.com/specimen/Advent+Pro) and is available for free download from Google (also included in my source link below).  All you need to reproduce the bug is to call `registerFont()` with all 7 Advent Pro styles, then try to render the regular style:

```js
const { registerFont, createCanvas } = require('canvas');

registerFont( 'AdventPro-Bold.ttf', { family: "AdventProBold" } );
registerFont( 'AdventPro-ExtraLight.ttf', { family: "AdventProExtraLight" } );
registerFont( 'AdventPro-Light.ttf', { family: "AdventProLight" } );
registerFont( 'AdventPro-Medium.ttf', { family: "AdventProMedium" } );
registerFont( 'AdventPro-Regular.ttf', { family: "AdventProRegular" } );
registerFont( 'AdventPro-SemiBold.ttf', { family: "AdventProSemiBold" } );
registerFont( 'AdventPro-Thin.ttf', { family: "AdventProThin" } );

var canvas = createCanvas( 600, 100 );
var ctx = canvas.getContext( '2d' );

ctx.fillStyle = '#ffffff';
ctx.fillRect( 0, 0, canvas.width, canvas.height );

ctx.font = "normal normal 30px AdventProRegular";
ctx.fillStyle = '#000000';
ctx.fillText( "Now is the time for all good men.", 10, 50 );

require('fs').writeFileSync( "out.png", canvas.toBuffer('image/png') );
```

The result image looks like this on all my systems:

![out-bad-30px](https://user-images.githubusercontent.com/700765/51566782-63114480-1e4a-11e9-9b61-9c9a197f88a8.png)

(Note: That is **not** what Advent Pro Regular is supposed to look like.)

Now, here is where it gets interesting.  If you simply remove the `registerFont()` calls, except for the one loading the regular style, it renders just fine.  Example:

```js
const { registerFont, createCanvas } = require('canvas');

registerFont( 'AdventPro-Regular.ttf', { family: "AdventProRegular" } );

var canvas = createCanvas( 600, 100 );
var ctx = canvas.getContext( '2d' );

ctx.fillStyle = '#ffffff';
ctx.fillRect( 0, 0, canvas.width, canvas.height );

ctx.font = "normal normal 30px AdventProRegular";
ctx.fillStyle = '#000000';
ctx.fillText( "Now is the time for all good men.", 10, 50 );

require('fs').writeFileSync( "out.png", canvas.toBuffer('image/png') );
```

And the output image from that:

![out-correct-30px](https://user-images.githubusercontent.com/700765/51566797-6c021600-1e4a-11e9-9268-ba08f052cb31.png)

(That is what Advent Pro Regular is actually supposed to look like.)

Now, I completely understand that some fonts may not work correctly with Pango on some systems, and I accept that.  But a few things about this particular situation have me thinking this is probably a bug:

- These are official Google TrueType Fonts, not just some random fonts I found online.  These *should* be pristine examples of properly formatted font files.
- Registering multiple styles of a font should not cause any one style to fail.
- This specific font fails on three different systems across two operating systems.
- The bug seems to be *much* more prevalent on macOS, with many more fonts failing, and I have theory as to why (see below).

My working theory is that Pango's internal font registry is getting corrupted when specific fonts are loaded.  The odds of this happening increase the more fonts you throw at it.  Now, macOS X, being a desktop operating system, naturally has a metric ton of built-in fonts, and I believe Pango is pre-loading all of them on process launch (this may also explain issue [#1358](https://github.com/Automattic/node-canvas/issues/1358)).  I think this is why so many more Google Fonts are "randomly" failing to render on macOS, because Pango's font registry is already in a "compromised" state on launch.  While I can also reproduce this bug on Linux, it is rarer and occurs with far fewer Google Fonts.

If we cannot fix this bug in node-canvas, one possible workaround would be to allow users to "deregister" a font, essentially unload it after use.  We may want to add this API anyway, as it may help with memory usage.  Consider a web service (Node.js daemon) that serves up images on demand over HTTP, and can load potentially "any" font at any time.  Such a service would probably need to "unload" (free up) memory used by fonts.

Here is a link to a tarball containing my test script, and the Google Advent Pro TrueType font files.  These are OFL licensed fonts, and safe to download and use: http://pixlcore.com/bugs/pango-font-bug.tar.gz

## Your Environment

The bug is reproducible on the following environments:

```
Node.js v10.14.1, node-canvas v2.3.1 (Darwin darwin x64 16.7.0, 16384 MB RAM) 
(OS X 10.12 Sierra) -- Precompiled binary for node-canvas v2.3.1.

Node.js v10.14.1, node-canvas v2.3.1 (Darwin darwin x64 18.2.0, 16384 MB RAM) 
(OS X 10.14 Mojave) -- node-canvas was compiled with --build-from-source.

Node.js v10.14.1, node-canvas v2.3.1 (Linux linux x64 3.10.0-862.3.2.el7.x86_64, 1800 MB RAM) 
(AWS CentOS 7.5.1804) -- node-canvas was compiled with --build-from-source.
```

**Comment by chearon** [comment]
I used that same huge font database to build/test `registerFont` 😃

I'm not actually able to reproduce the issue in your first code snippet on macOS. I don't think there's a bug in node-canvas's font selection code, but sometimes it misses.

To give you some background, node-canvas has a two-sided object that it uses to store registered fonts. On one side is what you gave to `registerFont`, and on the other side is a "system" font description that _should_ resolve to the ttf you registered on the operating system. When you set `ctx.font` it checks the first side of all of those objects and if it finds a match, it sends the system description to Pango to do the drawing.

Pango doesn't perfectly describe fonts correctly on macOS, though. [I fixed this myself in Pango and they merged it](https://bugzilla.gnome.org/show_bug.cgi?id=766148), but after that Pietro Gagliardi went way further than I did and posted even more details to the issue, particularly with already-registered fonts.

That'd explain why you're seeing more misses on macOS, there are specific fonts that just don't work. Misses on Linux are pretty rare since it generally just uses the OS/2 table directly.

That said, you seem to be getting more misses than usual, so maybe there is something else like an overloaded font list happening. Do you know if any of these fonts are already registered on your OS?

**Comment by chearon** [comment]
Also good points here

> allow users to "deregister" a font

we should probably add that

**Comment by jhuckaby** [comment]
Hey @chearon!  Hope you are doing well, sir.  I love your node-canvas library :)

I totally agree with everything you said.  And frankly, if this issue was isolated to macOS, I probably wouldn't have even reported it.  It's such a chaotic environment with so many built-in fonts, that things like this are just bound to happen.  [Here is my list of installed fonts by the way](https://pixlcore.com/bugs/all-my-fonts.txt) -- no dupes with any Google Fonts that I was testing with -- but who knows?  Maybe it's some kind of internal ID conflict inside the the font metadata.

My only real concern with this issue was that I was able to get a relatively clean, freshly provisioned Linux server into a "bad state" quite easily.  All I installed was Node.js via RPM, and then your prerequisite RPMs for compiling node-canvas from source.  That was all it took to get the bug reproducible (i.e. generic sans-serif showing in place of Advent Pro Reg).

Something came to mind today, and that was when I typed the `yum` command to install all the prerequisites, the list of packages it installed included `fontconfig` (undoubtedly by way of dependency chain, probably from pango).  Anyway, my point is, I realized this sort of dirtied the waters a bit, tainted my test environment as it were, and I wanted to try this on a *truly* clean system, with *nothing* installed except the base OS, Node.js and node-canvas precompiled.  So I did exactly that, on a fresh new EC2 instance using Amazon's own AWS Linux, latest version, and then typed:

```
rpm -i https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodejs-10.14.1-1nodesource.x86_64.
rpm
warning: /var/tmp/rpm-tmp.tMUlu5: Header V4 RSA/SHA256 Signature, key ID 34fa74dd: NOKEY

node --version
v10.14.1

npm install canvas

> canvas@2.3.1 install /opt/pango-font-bug/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[canvas] Success: "/opt/pango-font-bug/node_modules/canvas/build/Release/canvas.node" is installed via remote

+ canvas@2.3.1
added 68 packages from 36 contributors and audited 97 packages in 3.306s
found 0 vulnerabilities
```

I then installed my script with those same 7 Google Font styles, and the result image is:

![out-ec2-clean](https://user-images.githubusercontent.com/700765/51650849-a816a300-1f3e-11e9-8163-42d40e0a044d.png)

Viola!  It looks perfect.  The bug is **not** reproducible on a pure clean Linux box.  Now, to take the test one step further, I installed just **one** additional RPM, `fontconfig` of course:

```
yum install fontconfig

Running transaction
  Installing : fontpackages-filesystem-1.44-8.amzn2.noarch
  Installing : stix-fonts-1.1.0-5.amzn2.noarch
  Installing : fontconfig-2.10.95-11.amzn2.0.2.x86_64
  Verifying  : fontconfig-2.10.95-11.amzn2.0.2.x86_64
  Verifying  : stix-fonts-1.1.0-5.amzn2.noarch
  Verifying  : fontpackages-filesystem-1.44-8.amzn2.noarch

Installed:
  fontconfig.x86_64 0:2.10.95-11.amzn2.0.2

Dependency Installed:
  fontpackages-filesystem.noarch 0:1.44-8.amzn2
  stix-fonts.noarch 0:1.1.0-5.amzn2                     
```

And re-ran the test script:

![out-ec2-fc](https://user-images.githubusercontent.com/700765/51650808-84535d00-1f3e-11e9-8c79-68c8120eee82.png)

And boom, there you have it, broken image, and this time it's showing as Times New Roman?!?!  🤷‍♂️  So the default `fontconfig` RPM, as installed by `yum`, which also installs a prerequisite called `stix-fonts`, seems to be the catalyst for this bug to occur.

I also noticed that when running the script the second time (after installing `fontconfig`), it outputted a warning:

```
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
```

So I guess my question is, do I even need `fontconfig`?  I didn't know it was optional.  I suppose one thing I could do is just make sure all my servers are devoid of any of the trigger RPMs, especially `fontconfig`.  However, this seems like a strange hack / workaround.

> we should probably add that (edit: after a quick look though, while win32 and CoreText would allow us to do that safely, FontConfig only lets you clear all fonts, so node-canvas's API would have to be deregisterAllFonts)

I would **love** to have a `deregisterAllFonts` function, if you are able to add it easily.  I think that may be an acceptable workaround that removes the problem, if I am unable to avoid `fontconfig` for some reason.

Thank you for your quick replies and attention to this issue!

**Comment by jhuckaby** [comment]
Digging a bit deeper, in my specific case on that AWS Linux instance, when `fontconfig` was installed it brought along the `stix-fonts` package with it (for some reason), and that installs these 4 files:

```
/usr/share/fonts/stix/STIX-Bold.otf
/usr/share/fonts/stix/STIX-BoldItalic.otf
/usr/share/fonts/stix/STIX-Italic.otf
/usr/share/fonts/stix/STIX-Regular.otf
```

Apparently these are the culprit, at least in this one specific case, as moving them out of `/usr/share/fonts` fixes my issue, and my Advent Pro Regular renders properly.

That being said, I found something else out which is pretty bizarre.  The Advent Pro Regular font renders with a different weight (thickness) and slightly different kerning / character spacing depending on if I call `registerFont` with all the 7 styles, or just with the regular style.

Calling `registerFont` on all 7 styles then rendering regular:

![wtf5](https://user-images.githubusercontent.com/700765/51655374-398f1080-1f51-11e9-9df0-8ece531065a6.png)

Calling `registerFont` on *only* the regular style:

![single1](https://user-images.githubusercontent.com/700765/51655377-3d229780-1f51-11e9-9b2f-d3634adfdffb.png)

I have no idea why this would change the weight of the regular style, but just thought I'd mention it.

Fonts are weird, man!

**Comment by chearon** [comment]
> So I guess my question is, do I even need fontconfig? 

You don't. By default `canvas` comes with prebuilt binaries, but if you want to use the operating system's fontconfig you can install with `npm install canvas --build-from-source`.

I would say this is the same issue as #1309 except that your logs didn't end in an error. Still could be similar though, if FontConfig detects warnings in the config, maybe it disables app fonts completely...

> I'm really starting to think we should just implement that deregisterAllFonts function, and I just call it between every single use. What do you think?

I can open a PR for that soon, it should be easy

> those two images should really be identical. FYI, I believe the second image is the correct one. That looks like true regular, whereas the first image looks more like "medium".

I just checked (via https://opentype.js.org/font-inspector.html - very handy) and the "extra light" face and the "thin" face both have the same `usWeightClass` (OS/2 table) of 250, and they all have the `fontSubfamily` (naming table) set to "Regular". Those inconsistencies could be causing the FontConfig to pick a different font than we'd expect. You could try correcting those values in FontForge and saving the font.

Unfortunately unless we do font selection entirely in node-canvas, some fonts are always going to have these problems with `registerFont`.

**Comment by jhuckaby** [comment]
Got it, thank you for the reply!  I will uninstall and run without `fontconfig` from here on in :)  I was planning on using the precompiled node-canvas anyway, as it's so incredibly convenient.

Oh wow, the OpenType.js inspector looks awesome.  Thanks for that, and thank you for troubleshooting that font.  How odd that Google would have messed up the attributes!

> Unfortunately unless we do font selection entirely in node-canvas, some fonts are always going to have these problems with registerFont.

Yup, I understand now.  We're basically delegating to Pango and letting it do the font loading work for us, so we have to play by its rules :)

> I can open a PR for that soon, it should be easy

Thank you very much!  I really appreciate it.  I will go ahead and close this issue now.  I think we can probably close [#1358](https://github.com/Automattic/node-canvas/issues/1358) as well, as I am now fairly certain the delay is caused by Pango preloading all my macOS fonts.

**Comment by CodysseusX** [comment]
I am having a very similar problem. I render text using different fonts in a AWS Lambda environment. When I call the cold Lambda for the first time, it renders the font correctly. The second time with a different font, no problem.  The same with the third. Different font files, names and font families. However, the fourth time it renders the wrong font, one registered and rendered previously. No idea how to solve this.

**Comment by jhondge** [comment]
@chearon thanks for your inspiration
I was found  this issue reason is not just about the usWeightClass is same, and there have a common case is font naming table show the difference with fontFamily and preferredFamily. so the node-canvas `register_font.cc` files will add both `fontFamily` and `preferredFamily` to the list, and then different fontFamily but got the same `preferredFamily`.
so I was changed some logic for my business, it's work fine to me:
```cpp
get_family_name(FT_Face face) {
  FT_SfntName name;
  GList *list = NULL;
  char *utf8name = NULL;
  // add this var avoid preferredFamily override the fontFamily cause registerFont got wrong fonts
  bool hasFontFamily = false;
  for (unsigned i = 0; i < FT_Get_Sfnt_Name_Count(face); ++i) {
    FT_Get_Sfnt_Name(face, i, &name);

    if (name.name_id == TT_NAME_ID_FONT_FAMILY || (!hasFontFamily && name.name_id == TT_NAME_ID_PREFERRED_FAMILY)) {
      char *buf = to_utf8(name.string, name.string_len, name.platform_id, name.encoding_id);

      if (buf) {
        NameDef *d = (NameDef*)malloc(sizeof(NameDef));
        d->buf = (const char*)buf;
        d->rank = GET_NAME_RANK(name);

        list = g_list_insert_sorted(list, (gpointer)d, _name_def_compare);
        if(name.name_id == TT_NAME_ID_FONT_FAMILY) {
          hasFontFamily = true;
        }
      }
    }
  }
}
```

**Comment by chearon** [comment]
@jhondge you might want to see discussion on #1572, which sounds like similar issue. We're waiting on [this PR](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/191) to land in Pango, and then we'll get much more accurate matching on Linux.

**Comment by jhondge** [comment]
> @jhondge you might want to see discussion on #1572, which sounds like similar issue. We're waiting on [this PR](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/191) to land in Pango, and then we'll get much more accurate matching on Linux.
Thanks so much!!!

**Comment by jhondge** [comment]
> @jhondge you might want to see discussion on #1572, which sounds like similar issue. We're waiting on [this PR](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/191) to land in Pango, and then we'll get much more accurate matching on Linux.

@chearon Thanks so much!!!
