### ISSUE TITLE
node-pre-gyp hanging

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [Automattic/node-canvas#1364]
Hello,

I'm trying to install this module on Arch Linux and it hangs there:
 
```
> canvas@2.3.0 install /home/guillaume/weblab/server/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
```

Any idea what should i do ? 
## Your Environment
```
└─┬ text2png@2.1.0
  └── canvas@2.3.0
```

node v11.8.0 on ArchLinux

**Comment by zbjornson** [comment]
This is a hard one to troubleshoot, but could mean a locked file by another process (not too likely on Linux) or that the HTTP request is hanging for some reason. Is there anything unusual about your internet connection (like a proxy)?

**Comment by GuillaumeLeclerc** [comment]
I think there was a bug in my version of `ld`. Should be good now.

Thanks

**Comment by luwuer** [comment]
the same problem i met，and it wasted me almost three hours. 
But after i updated my npm version(v6.9.0 to v6.11.3), it was successful downloaded in a few seconds.

It worked but dont know why.

**Comment by liuxinqiong** [comment]
> the same problem i met，and it wasted me almost three hours.
> But after i updated my npm version(v6.9.0 to v6.11.3), it was successful downloaded in a few seconds.
> 
> It worked but dont know why.

your solution worked in macos, but didn't work in linux, It's interesting.
