### ISSUE TITLE
Canvas as dependency - npm install problem <bits/stdint-intn.h> fatal error

### ISSUE THREAD

**Issue by mikejernil** [Automattic/node-canvas#1365]
Whenever i try to install a package with node canvas as dependency, this problem occurs.
But sometimes rarely, it installs without any issues.
Not sure where to post about this problem i'm facing

![screenshot from 2019-01-30 11-17-42](https://user-images.githubusercontent.com/43872457/51960855-b570e780-2480-11e9-8bfa-1671db7c1ca1.png)

## Steps to Reproduce

npm i node-three-screenshot

## Your Environment
* canvas@2.3.1
* node v11.8.0

**Comment by LinusU** [comment]
Hmm, seems like the error is coming from within your systems `stdint.h`. Could you try to compile just this bare minimum basic C file?

```c
#include <stdint.h>

int main() {
  return 0;
}
```

**Comment by mikejernil** [comment]
I'm getting the same error when i compiled this
```
$ gcc test.c 
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9:0,
                 from test.c:1:
/usr/include/stdint.h:34:10: fatal error: bits/stdint-intn.h: No such file or directory
 #include <bits/stdint-intn.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by mikejernil** [comment]
@LinusU How do i solve this issue?

**Comment by LinusU** [comment]
Something is broken with your compiler/toolchain setup, unfortunately I cannot help you with this 😬 

Maybe try reinstalling gcc? 🤔

**Comment by mikejernil** [comment]
Tried it already.. doesn't work! 😕

**Comment by mikejernil** [comment]
uninstalled libc6-dev and installed everything right back.. worked !
Incomplete C library install was the problem
