### ISSUE TITLE
Installing canvas on RPI

### ISSUE THREAD

**Issue by LegendNed** [Automattic/node-canvas#1369]
I am having a problem with installing a node-canvas on Raspberry Pi. 

Ran`sudo npm i canvas --save` to try to install for discord js project.

This is the console output: https://hastebin.com/ohucelavuk.coffeescript

Can't figure out what the problem is.

**Comment by KyzaGitHub** [comment]
I am also getting this error while trying to install `color-thief` which uses `canvas` as a dependancy.

**Comment by LinusU** [comment]
> user "root" does not have permission to access the dev dir "/root/.node-gyp/8.11.1"

I wouldn't recommend running any `npm` related command as root, not sure how the setup on a raspberrypi works though 🤔

**Comment by buggedcom** [comment]
@LegendNed Did you ever find a solution to this?

**Comment by LegendNed** [comment]
No, closing it as I bought a private server, rPi didn't do much.
