### ISSUE TITLE
 canvas.createPNGStream is not a function

### ISSUE THREAD

**Issue by skeddles** [Automattic/node-canvas#1371]
What is wrong with this? 

```
var canvas = require('canvas');
const stream = canvas.createPNGStream();
```

**Comment by Hakerh400** [comment]
`createPNGStream` is a method of `Canvas.prototype`. Proper usage is

```js
const {Canvas} = require('canvas');
const canvas = new Canvas(100, 100);
const stream = canvas.createPNGStream();
```

**Comment by talhaanees** [comment]
@Hakerh400 using this gives an error saying 'Canvas is not a constructor'. And using createCanvas gives an error that createPNGStream is not a function. Any other ideas?
