### ISSUE TITLE
Canvas fails to load large image (10.7 MB)

### ISSUE THREAD

**Issue by vdalv** [Automattic/node-canvas#1374]
## Issue
When I try to load [this large image](https://storage.googleapis.com/learnjs-data/model-builder/mnist_images.png) into an Image object, I get the following stack trace:

(node:3798) UnhandledPromiseRejectionWarning: Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
    at setSource (/home/vdalv/myApp/node_modules/canvas/lib/image.js:97:13)
    at Image.set (/home/vdalv/myApp/node_modules/canvas/lib/image.js:60:9)
    at Promise (/home/vdalv/myApp/data.js:99:15)
    at new Promise (<anonymous>)
    ...

I've Googled the error, and seen a couple of Cairo-related issues...

## Steps to Reproduce
```js
var Canvas = require('canvas');
var img = new Canvas.Image();
img.onerror = err => { 
	throw err;
}
img.src = 'path/to/mnist_images.png';
```

## Your Environment
* Version of node-canvas: canvas@2.3.1
* Environment: node v8.10.0 on Ubuntu 16.04

Thanks,

-Vlad

**Comment by zbjornson** [comment]
Unfortunately Cairo has a hard-coded limit of ~32,767 pixels for the max width and height of a surface. Could you slice up your image with another application before loading it with node-canvas?

**Comment by vdalv** [comment]
Ah, alright, thanks for the info, I'll have to look into that.
