### ISSUE TITLE
Image load from remote url

### ISSUE THREAD

**Issue by remy** [Automattic/node-canvas#138]
I might be missing something _really_ obvious here, but I can't see that loading images from a url works (data urls work fine).

Example:

```
> var Image = require('canvas').Image;
undefined
> i = new Image();
[Image]
> i.onload = function () { console.log('image loaded'); };
[Function]
> i.src = 'http://remysharp.com/images/remy.jpg';
'http://remysharp.com/images/remy.jpg'
> 
```

Never shows "image loaded".  I've been porting client side canvas code to server side with very little changes, but loading remote images seem to be tripping me up.  I'm happy to mod my code to run a http.request on the url and then pass in the buffer to the `Image` but it seemed like loading images from a url should be there - so figuring I might be doing something wrong?

**Comment by rpominov** [comment]
Hi, I'm new not node, so I was wondering if someone could take a look at image loading code I wrote. Is it ok? Can it be improved/simplified somehow?

```js
var http = require('http')
var Canvas = require('canvas')

module.exports = function(url, cb) {
  http.get(url)
    .on('response', function(res) {

      // http://stackoverflow.com/a/14269536/478603
      var chunks = []
      res.on('data', function(data) {
        chunks.push(data)
      })
      res.on('end', function() {
        var img = new Canvas.Image()
        img.src = Buffer.concat(chunks)
        cb(null, img)
      })

    })
    .on('error', function(err) {
      cb(err)
    })
}
```

**Comment by zbjornson** [comment]
Tracking in #945.

**Comment by DaviesGit** [comment]
@remy  with the same problem
