### ISSUE TITLE
Canvas is no CanvasImageSource (2.4+)

### ISSUE THREAD

**Issue by Devidian** [Automattic/node-canvas#1392]
## Issue or Feature
I just updated from 2.3.0 to 2.4.0 / 2.4.1 and have some issues with the typescript definitions added. My Projects now throw this messages on tsc:

> Argument of type 'Canvas' is not assignable to parameter of type 'CanvasImageSource'

> Argument of type 'Image' is not assignable to parameter of type 'CanvasImageSource'

## Steps to Reproduce

```ts
interface MapTile {
	z: number,
	x: number,
	y: number,
	image: Canvas
}
....
// I have to create a canvas first and fill it with raw data pixel by pixel from a binary source
const C: Canvas = createCanvas(256, 256);
return {
			z: rt.z,
			x: rt.x,
			y: rt.y,
			image: C
		}
...
// Another Canvas is then created in another method
const tCanvas:Canvas = await this.loadTargetTileImage(targetImagePath);
const ctx: CanvasRenderingContext2D = tCanvas.getContext('2d');
const dSize = coords.factor * 256;
// here the first error is thrown as MapTile.image is a Canvas
ctx.drawImage(mt.image, coords.sx * 256, coords.sy * 256, dSize, dSize);
....
public async loadTargetTileImage(sourcePath: string): Promise<Canvas> {

	const Canvas = createCanvas(256, 256);
	try {
		const image = await loadImage(sourcePath);
		const ctx: CanvasRenderingContext2D = Canvas.getContext('2d');
		ctx.drawImage(image, 0, 0); // Second error here image is Image
	} catch (error) {
		// just return empty Canvas
	}
	return Canvas;
}
```

## Your Environment
* canvas@2.4.1
* node v10.15.3
* Debian GNU/Linux 9

## current workaround used:

set type of MapTile.image and image to any

**Comment by LinusU** [comment]
Did you test 2.4.0 as well, and thus are sure that the error is somewhere between 2.3.0 and 2.4.0? Would you mind testing 2.3.1 as well to further pinpoint the exact location of the breakage?

Would also be great with an example that I can copy and paste into the Node.js repl to reproduce the problem.

Thanks!

**Comment by zbjornson** [comment]
@LinusU This is just a typescript declaration error, not a runtime bug.

I think it's a one-line fix but I haven't had time to work on canvas lately.

**Comment by LinusU** [comment]
Ahaaa 😄

**Comment by Devidian** [comment]
As @zbjornson said its just a declaration error but the repo i'm talking about is public https://github.com/Devidian/oz_rw_risingmap_backend so you might test it yourself  ;)

**Comment by zbjornson** [comment]
@Devidian I think the defs are actually correct. You're casting the return values of `canvas.getContext("2d")` from `Canvas.CanvasRenderingContext2D` (node-canvas's class) to `CanvasRenderingContext2D` (the global DOM definition). The changes below should work:

```ts
const ctx: CanvasRenderingContext2D = tCanvas.getContext('2d');
// should be:
const cts: Canvas.CanvasRenderingContext2D = tCanvas.getContext('2d');
// or just
const cts = tCanvas.getContext('2d');
// ...
		// prefix this one too:
		const ctx: Canavs.CanvasRenderingContext2D = Canvas.getContext('2d');
		//                                           ^
		// btw I'd name this something other than Canvas so it doesn't shadow the import
		ctx.drawImage(image, 0, 0); // Second error here image is Image
```

If that doesn't solve it, it'd be helpful if you clone this repository and figure out what lines to add to `types/test.ts` to cause a type violation.

If your module only runs in Node.js, you can also probably remove "dom" from the "libs" array in your tsconfig.json. That might get rid of the ambient `CanvasRenderingContext2D` definition, which would then cause a (useful) error when you try to use it.

**Comment by Devidian** [comment]
yes, i just removed the type from ctx and it's working. Previously getContext returned any, that is why i added the type to ctx, as it is now returning the correct type i don't need to add this.

[solved] Thanks!
