### ISSUE TITLE
How to load the bitmap

### ISSUE THREAD

**Issue by land007** [Automattic/node-canvas#1397]
I have an opencv converted bitmap binary and its width and height, how to load into the canvas, I try to use

···
var u8ca = new Uint8ClampedArray(bmp_img_raw);
const myCanvas = canvas.createCanvas(width, height);
Const myCtx = myCanvas.getContext('2d', {alpha: true, pixelFormat: "RGBA32"});
Const myCtx = myCanvas.getContext('2d', {alpha: false, pixelFormat: "RGB24"});
const myImageData = canvas.createImageData(u8ca, width, height);
myCtx.putImageData(myImageData, 0, 0);
···

In both cases, normal images cannot be obtained.

**Comment by land007** [comment]
![image](https://user-images.githubusercontent.com/574543/55316550-3d836580-54a1-11e9-8ae6-9ec454f8d8c5.png)

**Comment by LinusU** [comment]
`createImageData` expects the data to be `ARGB32` encoded, I think that you have to make sure that your data is in that format before loading it

**Comment by land007** [comment]
![image](https://user-images.githubusercontent.com/574543/55416846-26786c80-55a2-11e9-816d-581b1ad90d8d.png)
I modified the code, the bitmap code, and released a new version of the npm bitmaps, which solved the problem almost, but with a black border at the bottom.
