### ISSUE TITLE
Overlapping Bug :/

### ISSUE THREAD

**Issue by AhmetTR7771** [Automattic/node-canvas#1403]
Hi. When I change the reps variable without restarting the project, the old state and the new state intermingle and it turns out.

My code:
```
db.fetch(`userReps_${user.id}`).then(reps => {
 canvas.fillText('▪Reps+: ${reps}`, 80, 500)

message.channel.send(new Discord.Attachment(canvas.toBuffer())
})
```

You can see the output image.

Output: https://prnt.sc/n89mae

The bug is in the output image :|

**Comment by zbjornson** [comment]
I'm not sure what your intent is, but I'm guessing you mean to create a new canvas/image each time? Can you show more of your code? You might get more input on StackOverflow as well.
