### ISSUE TITLE
[BUG] toBuffer('image/png') is returning SVG Buffer

### ISSUE THREAD

**Issue by ritwickdey** [Automattic/node-canvas#1406]
`.toBuffer('image/png')` is returning `svg`. I tried `toBuffer('application/pdf')`, this is working.

**Comment by ritwickdey** [comment]
One more strange I noticed. Async is not working 
```
const data = canvas.toBuffer((err, data) => {
     //THIS CALLBACK NEVER CALLED
}, 'image/png');

// I checked the type of `data`, it's buffer. 

```

**Comment by ritwickdey** [comment]
I got the issue. If I pass canvas `type` as `svg`,  it's not working. e.g:  `createCanvas(width, height, 'svg')`

```diff
 // This failed to generate toBuffer('image/png') and the callback fn
-createCanvas(width, height, 'svg')

 //This is working 
+createCanvas(width, height, undefined)
```

>createCanvas(width: number, height: number, type?: 'PDF'|'SVG') => Canvas
>`https://github.com/Automattic/node-canvas#createcanvas`

**Comment by zbjornson** [comment]
SVG canvases can only be exported as SVGs, and PDF canvases as PDFs. If you need a PNG, then you have to use the default (undefined) canvas type in `createCanvas(w, h)`.

**Comment by ritwickdey** [comment]
Thank you for clarification. :)
