### ISSUE TITLE
filltext dosen't work on CentOS6.0

### ISSUE THREAD

**Issue by lonevan** [Automattic/node-canvas#141]
ctx.fillText("Awesome!", 50, 100);

the text cannot rendered..

OS: CentOS 6.0
node: 0.6.6
canvas: 0.8.3
==========================
npm rebuild canvas
npm WARN htmlparser@1.7.3 package.json: bugs['web'] should probably be bugs['url']

> canvas@0.8.3 preinstall /usr/local/cc/node_modules/canvas
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for library gif                 : not found 
Checking for library jpeg                : yes 
Checking for cairo                       : yes 
'configure' finished successfully (0.240s)
Waf: Entering directory `/usr/local/cc/node_modules/canvas/build'
Waf: Leaving directory `/usr/local/cc/node_modules/canvas/build'
'build' finished successfully (0.017s)
canvas@0.8.3 /usr/local/cc/node_modules/canvas
==============================
but it works fine on
OS: Ubuntu 11.10
node: 0.6.6
canvas: 0.8.3

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
