### ISSUE TITLE
"Stripes" appearing while drawing gradients at low opacity.

### ISSUE THREAD

**Issue by AntonC9018** [Automattic/node-canvas#1412]
## Overview
I'm drawing shapes with gradients at low opacity with the code below. However, I'm getting these "stripes" (take a look at the images), which is wildly different from what the browser produces (for the way I draw them a kind of a grid appears). Compare with [the pen](https://codepen.io/AntonC9018/pen/mgvNOZ).

I'd like to find a way to mitigate this problem. Possibly some work-around, or some low-level manipulation. I don't know much about the two implementations of the canvas.

Also, do you think this is a bug and should be fixed? 

## My code
This code is just for the first test.

```javascript
const { createCanvas } = require('canvas');
let canvas = createCanvas(500, 500);
let ctx = canvas.getContext('2d');
const fs = require('fs');

render();

async function render() {

  const I = 50;

  for (let i = 0; i < I; i++) {

    // shifts coordinates and rotates
    rotate(250, 150, 1, ctx);

    let color = ctx.createLinearGradient(0, 0, 200, 200);

    color.addColorStop(0, 'rgba(244, 0, 0, 0.05)');
    color.addColorStop(1, 'rgba(9, 200, 0, 0.05)');
    ctx.fillStyle = color;


    ctx.fillRect(0, 0, 200, 200);

    // saves the canvas state as square{i}.png
    await saveFile('square' + i);
  }
}

function rotate(x, y, a, ctx) {
  ctx.resetTransform();
  var cos = Math.cos(a);
  var sin = Math.sin(a);
  ctx.transform(cos, sin, -sin, cos, x, y);
}

function saveFile(fname) {
  return new Promise((resolve, reject) => {
    const out = fs.createWriteStream(__dirname + `/${fname}.png`)
    const stream = canvas.createPNGStream()
    stream.pipe(out)
    out.on('finish', () => {
      console.log('The PNG file was created.')
      resolve(true);
    })
  })  
}
```
## Setup for all tests
All test results are [here](https://drive.google.com/open?id=1YEcFRV-x4Bem3GXpt93LFdr7iymu-1as), at google drive.

**The code for getting all results at once is [here.](https://github.com/AntonC9018/canvas-tests)**

Down below are the adjustments to the initial code you have to make to perform the test.

1 to 3 just increases the opacity to illustrate the "stripe" issue.

1.
```javascript
  const I = 50;

  color.addColorStop(0, 'rgba(244, 0, 0, 0.05)');
  color.addColorStop(1, 'rgba(9, 200, 0, 0.05)');
```
![1](https://user-images.githubusercontent.com/39066090/56854587-9ed41280-6941-11e9-96f8-b27dcf695a43.png)

2.
```javascript
  const I = 50;

  color.addColorStop(0, 'rgba(244, 0, 0, 0.1)');
  color.addColorStop(1, 'rgba(9, 200, 0, 0.1)');
```
![2](https://user-images.githubusercontent.com/39066090/56854594-c3c88580-6941-11e9-863c-6634a65146ee.png)

3.
```javascript
  const I = 10;

  color.addColorStop(0, 'rgba(244, 0, 0, 0.2)');
  color.addColorStop(1, 'rgba(9, 200, 0, 0.2)');
```
![3](https://user-images.githubusercontent.com/39066090/56854597-d04cde00-6941-11e9-8719-a1a2f1e68944.png)

4. Introduces 'globalAlpha' which didn't change anything.
```javascript
  const I = 50;

  for (let i = 0; i < I; i++) {

    // shifts coordinates and rotates
    rotate(250, 150, 1, ctx);

    let color = ctx.createLinearGradient(0, 0, 200, 200);

    ctx.globalAlpha = 0.05;

    color.addColorStop(0, 'rgb(244, 0, 0)');
    color.addColorStop(1, 'rgb(9, 200, 0)');
    ctx.fillStyle = color;


    ctx.fillRect(0, 0, 200, 200);

    // saves the canvas state as square{i}.png
    await saveFile('square' + i);
  }
```
![5](https://user-images.githubusercontent.com/39066090/56854600-de9afa00-6941-11e9-8a3b-b3ef97689839.png)

5. Tried increasing the quality to 'bilinear' and 'best'. The rest is the same as 4. It did nothing.
```javascript
ctx.patternQuality = 'best';
ctx.quality = 'best';
```

6. A moving figure. The rest is the same as 4.
```javascript
const I = 250;

rotate(250 + i * 2, 150, 1, ctx);
```
![6](https://user-images.githubusercontent.com/39066090/56854609-fa9e9b80-6941-11e9-9a7c-dfeff86a4b40.png)

## Comparisons
Compare the results with [this pen's](https://codepen.io/AntonC9018/pen/mgvNOZ) results.
![download (16)](https://user-images.githubusercontent.com/39066090/56854624-42bdbe00-6942-11e9-9adc-53eaa099c6b6.png)
![download (17)](https://user-images.githubusercontent.com/39066090/56854625-44878180-6942-11e9-8e26-b75dc717a63e.png)
These seem a lot smoother. The "stripes" are missing. Also, there's this grid, like little squares all over the image. Would love to know where they come from.

## Environment
* Windows 7
* node-canvas 6.9.0
* node v10.15.0

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/57578263-ece02e80-7488-11e9-9d3e-8d5057cac8e6.png)

created a test case to track fix-improvements

**Comment by asturur** [comment]
look what happen if you let rotate the image (i  removed the resetTransform ):

![image](https://user-images.githubusercontent.com/1194048/57578451-27e46100-748d-11e9-9a85-9f1a9229321e.png)

or look if you remove the 1 radiant angle rotation
![image](https://user-images.githubusercontent.com/1194048/57578471-772a9180-748d-11e9-887a-0de378b2d5c3.png)

the difference disappear.

different quality settings:
FAST
![image](https://user-images.githubusercontent.com/1194048/57578498-ec966200-748d-11e9-95c0-e90e03f876a4.png)

GOOD
![image](https://user-images.githubusercontent.com/1194048/57578500-fa4be780-748d-11e9-9f8e-5d1c2334c17c.png)

**Comment by AntonC9018** [comment]
@asturur Any progress on this?

**Comment by asturur** [comment]
i do not think i can get any progress.
To me looks like that cairo and browser can have different ways of aliasing and we have to take it. The latest screenshot i posted do show that the libs operates enough similarly to the browser when used differently. May be an aliasing or composition native issue

**Comment by asturur** [comment]
also look firefox, a cairo-backed-canvas-browser:

![image](https://user-images.githubusercontent.com/1194048/57737397-dbc33780-76ab-11e9-9426-c11da2c22a00.png)

totally same as node-canvas

**Comment by asturur** [comment]
this is safari, stripes + dithering

![image](https://user-images.githubusercontent.com/1194048/57737446-090fe580-76ac-11e9-8678-f728f45771c3.png)

**Comment by AntonC9018** [comment]
> look what happen if you let rotate the image (i removed the resetTransform ):
> 
> ![image](https://user-images.githubusercontent.com/1194048/57578451-27e46100-748d-11e9-9a85-9f1a9229321e.png)
> 
> or look if you remove the 1 radiant angle rotation
> ![image](https://user-images.githubusercontent.com/1194048/57578471-772a9180-748d-11e9-887a-0de378b2d5c3.png)
> 
> the difference disappear.

Just removed all the rotation and still got the same behavior. How strange.
![square39](https://user-images.githubusercontent.com/39066090/57758243-e5768a80-76ff-11e9-8600-23fd7e8a5918.png)


Whatever angle I choose, I get the same stripes.
`ctx.createLinearGradient(250, 0, 250, 500);`
![square39](https://user-images.githubusercontent.com/39066090/57758314-1060de80-7700-11e9-940b-9c0b5fdf6145.png)


Can you please send me the code you created these images with?

**Comment by AntonC9018** [comment]
Or is it the same is mine? Do you think it's a sheer platform-specific thing?

**Comment by asturur** [comment]
oh now is clear to me.
![image](https://user-images.githubusercontent.com/1194048/57794963-25ac2c00-7745-11e9-82d2-58f9df8521cf.png)

this is the gradient drawn 1 time, perfectly smooth.

you are moving from r 244 to 9 and similar for green from 0 to 200.
Let's take the green case that is easier.

When at opacity 0.05, blended with any color on the background, this green gradient will be 95% background and 5% your green. Being the background a full color that means that your green is moving from 0 to 5% of 200 = 10.

So you have just 10 variation of final color in one sense of the gradient and something like that on the other side ( 11 or 12 )

When adding back 50 copies of the gradient over itself, you go back to the original color but you are adding the faint stripes of green on top of each other, getting back to 10 strong stripes of color.

If you look at your gradient closely you can see 10 stripes overlapped with 12. and this is exactly what i think is happening.

Is just your drawing alghoritm that produces this.

Chrome may be doing this in floats in the gpu and then going back to 2d canvas and numbers between 0 to 255 all at once at the end of operations, so this is why it gets a different output, safari too is applying dithering, letting think that the final conversion to integers is done at the end.

I have no proofs for this, neither i will go and check the original browser source code to understand if this is correct, but i think this may be plausible and we should not investigate further.

**Comment by AntonC9018** [comment]
@asturur oh ok so you think it's like they get less diverse when drawn at a low opacity, that makes sense. This apparently can't be solved within the Cairo library as it lacks that low level control like OpenGL does, for example. Thank you for your attention on this!

**Comment by asturur** [comment]
I think this can't be solved, cairo/firefox output looks correct, chrome/safari output looks artificially improved, agumented.
