### ISSUE TITLE
ctx.measureText() cause memory leak in koa server

### ISSUE THREAD

**Issue by GuanyuChen** [Automattic/node-canvas#1419]
## Issue or Feature

I found that when I call `ctx.measureText()` in a router, it causes an increase in memory.

## Steps to Reproduce

```js
router.get('/test', async ctx => {
    const canvas = Canvas.createCanvas(100, 100);
    const canvasContext = canvas.getContext('2d');
    
    canvasContext.measureText('test');
    console.log('heapUsed: ', process.memoryUsage().heapUsed, ' external: ', process.memoryUsage().external);
 
    ctx.body = { code: 0 }
})
```

When I repeat the request，the `external` num has been growing。

## Environment
canvas@2.5.0
Node v10.15.3 on macOS Mojave 10.14.4

Look forward to your reply ：）

thanks!

**Comment by LinusU** [comment]
Why did you close this? If there is a memory leak here I would love it if we could solve it, or did you find out that there was something in your app causing it? ☺️
