### ISSUE TITLE
registerFont fails to select font on macOS

### ISSUE THREAD

**Issue by askerb** [Automattic/node-canvas#1426]
## registerFont fails to select font on macOS
Using "Roboto Condensed" or "Roboto Condensed Light" on macOS results in a default font being used. Other fonts, such as "Roboto" or "Roboto Mono" works. Same code works fine under Windows.
In the attached image the "Q" clearly shows that the third line is not written using Roboto Condensed.

## Steps to Reproduce
 ```
Canvas.registerFont("resources/fonts/Roboto_Mono/RobotoMono-Regular.ttf", { family: "Roboto Mono" })
Canvas.registerFont("resources/fonts/Roboto/Roboto-Regular.ttf", { family: "Roboto" })
Canvas.registerFont("resources/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf", { family: "Roboto Condensed" })

const cvs = Canvas.createCanvas(500, 500)
const ctx = cvs.getContext("2d")
ctx.fillStyle = "#FFFFFF"
ctx.fillRect(0, 0, 500, 500)
ctx.fillStyle = "#000000"

ctx.font = `62px "Roboto Mono"`
ctx.fillText("ÅÄÖAjgyQGm", 0, 100)

ctx.font = `62px "Roboto"`
ctx.fillText("ÅÄÖAjgyQGm", 0, 200)

ctx.font = `62px "Roboto Condensed"`
ctx.fillText("ÅÄÖAjgyQGm", 0, 300)
```

![fontTest](https://user-images.githubusercontent.com/1169390/57767390-8584e180-7709-11e9-8f59-95bdcbb09bd8.png)

## Environment
canvas@2.4.1
node 11.0.0 on macOS 10.14.4
Works fine when running Windows.

**Comment by chearon** [comment]
See https://github.com/Automattic/node-canvas/issues/1207#issuecomment-414176074

**Comment by chearon** [comment]
This is because on macOS you need to call `createCanvas` before you call `registerFont`. I'm not sure why that is, and it needs to be fixed, but for now the work-around is swapping those calls. I'll use #1747 to track the problem, so closing this.
