### ISSUE TITLE
install in centos 6.1

### ISSUE THREAD

**Issue by axoquen** [Automattic/node-canvas#144]
Hi, i get this message, what can i do?, where i can check?

Checking for program g++ or c++          : /usr/bin/g++
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : ok /usr/local/bin/node
Checking for node prefix                 : ok /usr/local
Checking for library gif                 : yes
Checking for library jpeg                : yes
Checking for cairo                       : yes
'configure' finished successfully (0.354s)
Waf: Entering directory `/root/projects/node_modules/canvas/build'
[1/9] cxx: src/Canvas.cc -> build/Release/src/Canvas_1.o
/usr/local/include/node/uv-private/eio.h: In static member function âstatic v8::Handle<v8::Value> Canvas::ToBuffer(const v8::Arguments&)â:
/usr/local/include/node/uv-private/eio.h:361: error: too few arguments to function âeio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*, eio_channel*)â
../src/Canvas.cc:214: error: at this point in file
Waf: Leaving directory `/root/projects/node_modules/canvas/build'
Build failed:  -> task failed (err #1):
        {task: cxx Canvas.cc -> Canvas_1.o}

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
