### ISSUE TITLE
canvas installation error with Node v12

### ISSUE THREAD

**Issue by KbDinesh87** [Automattic/node-canvas#1441]
## Issue or Feature
Not able to install and rebuild canvas package

## Steps to Reproduce

```js
npm install canvas@latest

```

## Your Environment
npm@6.9.0 C:\Program Files\nodejs\node_modules\npm
`-- fabric@3.1.0
  `-- UNMET OPTIONAL DEPENDENCY canvas@2.5.0

Node Version : v12.3.1
Elcctron : v5.0.2

**Comment by lolwhite23** [comment]
I am having the same problem with node v11.15.0, I will try another version of node to see what happened.

**Comment by lolwhite23** [comment]
Still doesnt work

**Comment by chearon** [comment]
node 12/Windows is not supported yet, see #1420. Hopefully node-gfx/node-canvas-prebuilt#80 will fix this very soon

I don't know why 11 wouldn't work, are you using 64 bit Windows?

**Comment by lolwhite23** [comment]
Yes, and I also tried Linux and I know it should work on linux, ive done it before

**Comment by bozzmob** [comment]
Nodejs 12 is still having installation problems. Any idea when  node-gfx/node-canvas-prebuilt#80  will get merged?

**Comment by Uniphix** [comment]
I am also getting this problem with node v11.15.0 have to revert back to node v10.16.3

**Comment by zbjornson** [comment]
Prebuilds for canvas v2.5.0, v2.6.0 and v2.6.1 for Node.js v12 and v13 have been available for a bit now (thanks to @chearon). If anyone's still having problems, please open a new issue.
