### ISSUE TITLE
Hebrew Fonts breaking with specific fonts Friz-Quadrata with measureText

### ISSUE THREAD

**Issue by fourcolors** [Automattic/node-canvas#1443]
## Issue

I'm using `node-canvas` to convert from some legacy fonts to newer google fonts. I ran across this text in hebrew: `יוסי האפס :)` that will break when I try to render it with a font called `friz-quadrata` in bold [http://fontsgeek.com/fonts/Friz-Quadrata-Bold](url)

## Steps to Reproduce
- Register `friz-quadrata` bold
- set canvas font to the friz-quadrata with this text string `יוסי האפס :)`
- attempt to `ctx.measureText`

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.5.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
`node v10.15.3` `Mac OS X 10.14.5`

Error that gets thrown
```
2019-06-07 12:00:16.310 node[33253:250982] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 34 beyond bounds [0 .. 33]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff538f9cfd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7dfa3a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff53938cf4 -[CFPrefsConfigurationFileSource initWithConfigurationPropertyList:containingPreferences:] + 0
	3   CoreFoundation                      0x00007fff53851919 -[__NSSingleObjectSetI member:] + 0
	4   libpangocairo-1.0.0.dylib           0x0000000106abe3c9 pango_core_text_fontset_get_font_at + 62
	5   libpangocairo-1.0.0.dylib           0x0000000106abe361 pango_core_text_fontset_foreach + 43
	6   libpango-1.0.0.dylib                0x0000000106adb015 get_shaper_and_font + 208
	7   libpango-1.0.0.dylib                0x0000000106ada285 itemize_state_process_run + 963
	8   libpango-1.0.0.dylib                0x0000000106ad9b3e pango_itemize_with_base_dir + 110
	9   libpango-1.0.0.dylib                0x0000000106adf3ca pango_layout_check_lines + 617
	10  libpango-1.0.0.dylib                0x0000000106ae2d7e pango_layout_get_extents_internal + 47
	11  canvas.node                         0x00000001068cbd1a _ZN9Context2d11MeasureTextERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE + 342
	12  canvas.node                         0x00000001068deac2 _ZN3Nan3impL23FunctionCallbackWrapperERKN2v820FunctionCallbackInfoINS1_5ValueEEE + 164
	13  node                                0x000000010023663f _ZN2v88internal25FunctionCallbackArguments4CallEPNS0_15CallHandlerInfoE + 623
	14  node                                0x0000000100235b81 _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE + 689
	15  node                                0x0000000100235220 _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE + 288
	16  ???                                 0x00002f614265be3d 0x0 + 52094772297277
	17  ???                                 0x00002f61426118d5 0x0 + 52094771992789
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

UPDATE:
The issue was solved by updating the fonts I was using with fonts that had correct table contents. `measureText` breaks with international languages with font files that don't have the correct table data.

**Comment by chearon** [comment]
It looks like it's crashing while trying to get the native face from the OS, almost like the font got removed.

I can't repro on macOS 10.14.4, either for prebuilds or natively built, registering through OS or through node-canvas. Does it still happen when you change the text? Does it happen when you change the font it uses?

**Comment by fourcolors** [comment]
@chearon So it's with that text string with `friz-quadra-bold` If i change the font it works fine and if it change the text string to something else it seems to work fine.

**Comment by fourcolors** [comment]
```
registerFont(__dirname + '/fonts/friz-quadrata.ttf', { family: 'FrizQuadrata' })
registerFont(__dirname + '/fonts/friz-quadrata-bold.ttf', { family: 'FrizQuadrata', weight: 'bold' })
```
I'm registering the font like this

**Comment by fourcolors** [comment]
It might be related to this. 
![image](https://user-images.githubusercontent.com/51751/59132694-b6cc8800-892a-11e9-9faf-57e816d560c4.png)
When attempting to install the font, I get these errors

Then a quick google search I found this: https://www.iwebss.com/tech/540-fixing-fonts-with-validation-errors-on-mac

I'll post an update if fixing the font works. Thanks for taking a look at this.

**Comment by fourcolors** [comment]
Solved. I posted an update in the original description.
