### ISSUE TITLE
Release of missing prebuilds

### ISSUE THREAD

**Issue by jamescryer** [Automattic/node-canvas#1445]
## Issue
I'm looking to update Canvas in an opensource library called Resemble.js. I'd like to upgrade because canvas@<2.5.0 doesn't support Node 12 and users who are trying to upgrade their local and CI environments are requesting an update.

It seems though that not all the prebuilds are yet available, I personally use Windows 10.  I'm hesitant to update right now as this may break downstream CI pipelines.

I need to decide whether to release a new major version of Resemble.js, or hang on for a little while and release a minor.  **Can you tell me what the plans and timelines are for the release of new prebuilds?**

## Steps to Reproduce
```
PS C:\{path}\Resemble.js> npm i

> canvas@2.5.0 install C:\{path}\Resemble.js\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.5.0 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND github.com
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.

...

gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
```

## Your Environment
* canvas@2.5.0
* node@12.3.1
* Window 10 Pro

**Comment by LinusU** [comment]
Seems like specifically `v72-win32` is missing from 2.5.0, not sure why ☺️

@chearon you know what's up?

**Comment by LinusU** [comment]
Track status of this here 👉 https://github.com/node-gfx/node-canvas-prebuilt/issues/78

**Comment by jamescryer** [comment]
Thanks for the response.  So to summarise (correct me if I'm wrong), releases of node-canvas are independent of the release of prebuilts, thereby not immediately guaranteeing an upgrade path of minor versions for all dependents. The problem that relates to this ticket is an [issue with Appveyor](https://github.com/appveyor/ci/issues/2921) which means a Windows 10 + Node 12 prebuilt from [node-canvas-prebuilt](https://github.com/node-gfx/node-canvas-prebuilt/issues/78) cannot currently be created and released.

**Comment by LinusU** [comment]
> releases of node-canvas are independent of the release of prebuilts

When I release a new canvas release to npm, I put it under the `next` tag until we have prebuilds available. When those are available, I also tag `latest` to the same version.

So running `npm install canvas` _should_ always give you prebuilds :)

We currently have some issues with all Windows builds though, and 2.6.0 only have Linux/macOS builds ready. https://github.com/node-gfx/node-canvas-prebuilt/releases/tag/v2.6.0
