### ISSUE TITLE
can not install canvas in arm64 (AArch64)  

### ISSUE THREAD

**Issue by hossein-b** [Automattic/node-canvas#1447]
I'av tried to install canvas on arm64 (AArch64) architecture by using this command. 
`sudo npm install canvas`
but it doesn't work and the following is results:

```
> canvas@2.5.0 install /usr/local/lib/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.5.0 and node@10.16.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas/build' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas/build'
gyp ERR! System Linux 4.9.0-xilinx-v2017.3
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/canvas/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/canvas
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.9.0-xilinx-v2017.3
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/canvas
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ngd/.npm/_logs/2019-06-25T23_46_17_319Z-debug.log

```
also, I'av tried to build it by using source but it doesn't work too.
npm install --build-from-source canvas

**Comment by LinusU** [comment]
> EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas/build'

This seems to be an issue with permissions rather than having anything to do with the arch...

**Comment by hossein-b** [comment]
anyway, it doesn't work, finally, I build it by using the source as following:
git clone https://github.com/Automattic/node-canvas.git
npm i -g nan
export NODE_PATH=$(npm root -g)
node-gyp configure
node-gyp build

**Comment by LinusU** [comment]
It probably works building from source since you are doing that in a directory that you own, as supposed to before when trying to install it to `/usr/local/lib/node_modules/canvas`.

Anyways, glad you managed to solve it 👍

**Comment by elohffa** [comment]
> anyway, it doesn't work, finally, I build it by using the source as following:
> git clone https://github.com/Automattic/node-canvas.git
> npm i -g nan
> export NODE_PATH=$(npm root -g)
> node-gyp configure
> node-gyp build

After Build , Should I have to move node-canvas folder to /usr/lib/node_modules ?

**Comment by hossein-b** [comment]
No, during building, it is copied to  /usr/lib/node_modules/canvas.

**Comment by hossein-b** [comment]
> > anyway, it doesn't work, finally, I build it by using the source as following:
> > git clone https://github.com/Automattic/node-canvas.git
> > npm i -g nan
> > export NODE_PATH=$(npm root -g)
> > node-gyp configure
> > node-gyp build
> 
> After Build , Should I have to move all file from node-canvas folder to /usr/lib/node_modules/canvas ?

No, during building, it is copied to /usr/lib/node_modules/canvas.

**Comment by elohffa** [comment]
But on my case in my Pi , after I build , the file doesn't copy to /usr/lib/node_modules/ , so I create the a new as canvas and copy all the folder under node-canvas to the canvas folder , but it is don't work , so can u let me know what can i do ?

**Comment by TSKsmiley** [comment]
> 
> 
> anyway, it doesn't work, finally, I build it by using the source as following:
> git clone https://github.com/Automattic/node-canvas.git
> npm i -g nan
> export NODE_PATH=$(npm root -g)
> node-gyp configure
> node-gyp build

`pi@raspberrypi:~/node-canvas $ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@12.19.0 | linux | arm
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/node-canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/12.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/12.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/12.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/node-canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /home/pi/node-canvas
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok `

**Comment by TSKsmiley** [comment]
> 
> 
> anyway, it doesn't work, finally, I build it by using the source as following:
> git clone https://github.com/Automattic/node-canvas.git
> npm i -g nan
> export NODE_PATH=$(npm root -g)
> node-gyp configure
> node-gyp build

When I try to run node-gyp configure I get this

![image](https://user-images.githubusercontent.com/37146398/96476597-b7bb3c80-1235-11eb-9ef5-8d8db80fa506.png)

**Comment by danyildiabin** [comment]
Might be not related to this repo, but I found solution that worked for me.
[https://stackoverflow.com/questions/64562563/how-can-i-ovecome-this-error-in-npm-install](https://stackoverflow.com/questions/64562563/how-can-i-ovecome-this-error-in-npm-install)

**Comment by carlos-garcia** [comment]
thanks @danyildiabin the answer on that link worked really well

`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

then i can run `npm install canvas` with no issues

**Comment by YousefX8** [comment]
> thanks @danyildiabin the answer on that link worked really well
> 
> `sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`
> 
> then i can run `npm install canvas` with no issues


Aww man thank you that worked out
