### ISSUE TITLE
SVG image loading error in CentOS container

### ISSUE THREAD

**Issue by icfantv** [Automattic/node-canvas#1459]
I've built up a CentOS container (including building node-canvas from source) per this site's instructions and everything appears to be working great with the one exception that we appear to not be able to set the `src` property on an `<image/>` tag to an SVG without getting:

```
Error: Could not load img: "data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iZmlsbDogZGltZ3JleSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTIiIGhlaWdodD0iMTIiIHZpZXdCb3g9IjAgMCAxMiAxMiI+PHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMyw1IEwzLDMuNTc1NjY0OTMgQzMsMi40MTQxNzM0IDQuMzQ2NTE3MTIsMSA2LDEgQzcuNjU2ODU0MjUsMSA5LDIuNDE4MTM1OTggOSwzLjU3NTY2NDkzIEw5LDUgTDkuNDk5NTY0MTcsNSBDOS43NzU5NDcyNSw1IDEwLDUuMjI3ODgwNDggMTAsNS40OTEwMDUxOCBMMTAsMTAuNTA4OTk0OCBDMTAsMTAuNzgwMTY5NSA5Ljc2OTIwMzE5LDExIDkuNDk5NTY0MTcsMTEgTDIuNTAwNDM1ODMsMTEgQzIuMjI0MDUyNzUsMTEgMiwxMC43NzIxMTk1IDIsMTAuNTA4OTk0OCBMMiw1LjQ5MTAwNTE4IEMyLDUuMjE5ODMwNTEgMi4yMzA3OTY4MSw1IDIuNTAwNDM1ODMsNSBMMyw1IFogTTgsMy41NzU2NjQ5MyBDOCwyLjcwODQxODA3IDcuMTA0NTY5NSwyIDYsMiBDNC44OTc2NzgwOCwyIDQsMi43MDU0NDkyMiA0LDMuNTc1NjY0OTMgTDQsNSBMOCw1IEw4LDMuNTc1NjY0OTMgWiBNNSw3IEw1LDkgTDcsOSBMNyw3IEw1LDcgWiIvPjwvc3ZnPg=="
```

We've tried setting the `src` attribute to both a URL (to the Internet) and a base64 encoded PNG and that works great so we were thinking that it might be because we were missing the `librsvg2` library as indicated by the 2.0 release notes but this is not fixing the issue.

I have not tested also installing the `librsvg2-devel` library prior to building node-canvas from source because that RPM is not currently available on our Artifactory server and if it turns out we do need that RPM to make this work, then we have other issues internally we'll need to resolve that are beyond the realm of this project.

## Steps to Reproduce
We're setting the `src` attribute on an HTML image tag to an SVG string.

## Your Environment
* Version of node-canvas:  2.4.1
* Environment:  Centos7 container with Node 10.16.0

**Comment by LinusU** [comment]
I'm afraid that you need to have `librsvg2-devel` available when building node-canvas. That is the library that does the svg decoding & rasterising...

**Comment by icfantv** [comment]
@LinusU I was afraid you were going to say that.  Thanks for getting back to us.  I'll mark this as closed/resolved.

**Comment by icfantv** [comment]
Just to tie this off, adding `librsvg2-devel` solved the issue for us.
