### ISSUE TITLE
Corrupted image

### ISSUE THREAD

**Issue by guiOLVR** [Automattic/node-canvas#1463]
## Issue or Feature

I try to reduce image opacity and put that on other image like watermark, but when i try to do that with SHARP, the code show me an error like: 

`Error: Expected from parameter to be a Buffer, Stream, or a String`

when i try to save that image into home, but when i open that image, i just see nothing, just white image, but in the icon show normal.

## Steps to Reproduce

```js
   const Canvas = require('canvas');
   let canvas = Canvas.createCanvas(220, 215);
    let ctx = canvas.getContext('2d');

    await Canvas.loadImage('logo.png').then((logo) => {
        ctx.globalAlpha = 0.5;
        ctx.drawImage(logo, 10, 10);
    });
    let buff = await canvas.toBuffer();
    
    sharp(image)
            .composite([{ input: buff, gravity: 'northwest' }])//Here give me an error.
            .sharpen()
            .withMetadata()
            .toBuffer()
            .then(function(outputBuffer) {
                buffer = outputBuffer;
            })
            .catch(error => {
                console.log(error);
            });
```

## Your Environment
* Version of node-canvas ("canvas": "^2.5.0"):
* Environment (node 10.15.3 on Windows 10):

**Comment by LinusU** [comment]
I think that you want to pass `buff` to `sharp`, not `image`?

**Comment by guiOLVR** [comment]
> I think that you want to pass `buff` to `sharp`, not `image`?

I just want to pass image data(buffer), but this not work.
I had try to pass a image path like: 'images/watermark.png' but not work to.

```js
   const Canvas = require('canvas');
   let canvas = Canvas.createCanvas(220, 215);
    let ctx = canvas.getContext('2d');

    await Canvas.loadImage('logo.png').then((logo) => {
        ctx.globalAlpha = 0.5;
        ctx.drawImage(logo, 10, 10);
    });
    canvas.createPNGStream().pipe(fs.createWriteStream(path.join('watermark.png')));

   sharp(image)
            .composite([{ input: 'watermark.png', gravity: 'northwest' }])//Here give me an error.
            .sharpen()
            .withMetadata()
            .toBuffer()
            .then(function(outputBuffer) {
                buffer = outputBuffer;
            })
            .catch(error => {
                console.log(error);
            });
```

**Comment by guiOLVR** [comment]
He just work into browser.

**Comment by LinusU** [comment]
You are getting the data from the canvas here:

```js
let buff = await canvas.toBuffer();
```

and storing it in a variable named `buff`.

A few lines down you are trying to load the image from a variable named `image`, which doesn't seem to exists:

```js
sharp(image)
```

You probably want to change that line to read from `buff` instead:

```js
sharp(buff)
```

**Comment by guiOLVR** [comment]
@LinusU
Sharp(image) is other image like background.

I call buff in composite.

```js
sharp(image)//back-ground.
            .composite([{ input: buff, gravity: 'northwest' }])//Here i call buff.
```

**Comment by LinusU** [comment]
Ah, okay 👌 

Does Sharp support passing a buffer as that `input` parameter? You were passing a filename string before it seems 🤔
