### ISSUE TITLE
Loaded image doesn't appear in saved file.

### ISSUE THREAD

**Issue by Hickacou** [Automattic/node-canvas#1464]
## Issue or Feature
I used the `loadImage()` example code to load an image into my canvas. using the `.toDataURL()`, I get what I expect, which is just simply the loaded image. But when I try to save the image into a file, using `toBuffer()`, I just get an empty image.

## Steps to Reproduce

```js
const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext('2d');
const fs = require("fs");
loadImage('test.jpg').then((image) => {
  ctx.drawImage(image, 50, 0, 70, 70)

  console.log('<img src="' + canvas.toDataURL() + '" />')
});
var buf = canvas.toBuffer();
fs.writeFileSync("test.jpg", buf);
```

Here is the image I'm using : 
![b31cef49-1900-4b01-ab11-93e283b585c2](https://user-images.githubusercontent.com/20957865/62886115-cc02d000-bd3a-11e9-9889-31d8153b7abf.png)

I also tried saving into a .png file or loading a .png file as well, but it never worked.
## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
canvas@2.5.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
Node v10.16.0
on Windows 10 1903

**Comment by zbjornson** [comment]
Try moving

```js
var buf = canvas.toBuffer();
fs.writeFileSync("test.jpg", buf);
```

into your `then(() => { ... })` callback. Otherwise you're saving the canvas before the image has loaded.

`toBuffer` also defaults to PNG, but you're saving it with a "jpg" extension, btw.

**Comment by Hickacou** [comment]
Thank you, it fixed my problem !
