### ISSUE TITLE
[question] how to set pixel density

### ISSUE THREAD

**Issue by srikanthbandaru** [Automattic/node-canvas#1465]
Is there any way to set the pixel density for more sharp canvas and images? 
Like: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

**Comment by srikanthbandaru** [comment]
NVM! 
I ended up doing like below to get a sharper image. 

```
var canvas = Canvas.createCanvas(canvasWidth, canvasHeight);
var ctx = canvas.getContext('2d');
canvas.width = 1920 * 4;
canvas.height = 1080 * 4;
ctx.scale(4, 4);
```

Thank you for the awesome library!!!

**Comment by weinixiong** [comment]
> NVM!
> I ended up doing like below to get a sharper image.
> 
> ```
> var canvas = Canvas.createCanvas(canvasWidth, canvasHeight);
> var ctx = canvas.getContext('2d');
> canvas.width = 1920 * 4;
> canvas.height = 1080 * 4;
> ctx.scale(4, 4);
> ```
> 
> Thank you for the awesome library!!!

I tried to use this method to get pictures, but the text layout was too loose. Did you have this problem？
![image](https://user-images.githubusercontent.com/19499927/86097894-eb882000-bae7-11ea-8e2a-2bc35399efa2.png)
