### ISSUE TITLE
i can`t install canvas centos 7 pterodactyl

### ISSUE THREAD

**Issue by superboys2017** [Automattic/node-canvas#1466]
npm install -g canvas

generateActionsToTake npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR! { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR! stack:
npm ERR! 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm ERR! A complete log of this run can be found in:
npm ERR! /home/container/.npm/_logs/2019-08-15T17_44_27_361Z-debug.log

**Comment by zbjornson** [comment]
You're trying to install with the `-g` (global) flag but don't have access to `/usr/local/lib/node_modules`. Generally you shouldn't install node modules with `-g`. If you must for some reason, you probably need to use `sudo` or change folder permissions. (https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92 discusses some reasons to avoid sudo/-g.)
