### ISSUE TITLE
fatal error LNK1104: cannot open file 'C:\libjpeg-turbo\lib\jpeg.lib'

### ISSUE THREAD

**Issue by cfanoulis** [Automattic/node-canvas#1468]
## Issue or Feature
When installing `node-canvas`, I encounter the error `fatal error LNK1104: cannot open file 'C:\libjpeg-turbo\lib\jpeg.lib'`.   However, that folder (fresh install) does not include any `lib` files, only `A` files.

![](https://my-code.is-terrible.com/L8mu6J.png)

## Your Environment
node v12.8.1
node-gyp v5.0.3
canvas v2.4.1
Windows 10 Pro 64bit, build 1903

**Comment by cfanoulis** [comment]
Nevermind... I was installing the GCC version. Make sure you dont download that

**Comment by MukeshKalaga** [comment]
Tq u saved my time
