### ISSUE TITLE
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v64-win32-ia32.tar.gz

### ISSUE THREAD

**Issue by wpitallo** [Automattic/node-canvas#1471]
Hi I am receiving this error when trying to install on Azure functions, an idea's how to solve it?

> canvas-prebuilt@1.6.11 install D:\home\site\wwwroot\avataaars\node_modules\canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v64-win32-ia32.tar.gz
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v64-win32-ia32.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (D:\home\site\wwwroot\avataaars\node_modules\node-pre-gyp\lib\install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (D:\home\site\wwwroot\avataaars\node_modules\request\request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:441:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "D:\\Program Files (x86)\\nodejs\\10.14.1\\node.exe" "D:\\home\\site\\wwwroot\\avataaars\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install"
node-pre-gyp ERR! cwd D:\home\site\wwwroot\avataaars\node_modules\canvas-prebuilt
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
npm WARN api@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
An error has occurred during web site deployment.
npm ERR! canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-prebuilt@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by LinusU** [comment]
You seem to be using an old version of `canvas-prebuilt`, please change to a recent release of `canvas` instead :)

**Comment by NodiraIbrogimova** [comment]
Hi there,
I'm getting the following error when I run `npm install`:

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/nns/Documents/Self Projects/augur_exp/frontend/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:323:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/nns/Documents/Self Projects/augur_exp/frontend/node_modules/request/request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:311:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:476:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:311:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/nns/.nvm/versions/node/v12.16.1/bin/node" "/Users/nns/Documents/Self Projects/augur_exp/frontend/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/nns/Documents/Self Projects/augur_exp/frontend/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
```
I have node version `v12.16.1` and npm version `6.13.4`. I had the same issue on node version `10.x`

Was the issue above fixed? Can somebody suggest any idea to fix the error?

**Comment by zbjornson** [comment]
@NodiraIbrogimova it looks like you're using an old version (1.6.11). You need to use a 2.x version, and install `canvas` instead of `canvas-prebuilt` if you're not doing so already.

**Comment by NodiraIbrogimova** [comment]
@zbjornson I have `"canvas": "^2.6.1"` in my `package.json` and I think I'm doing it right with changes. Correct me if I'm wrong, please.

This is my `dependencies` list:
```
"dependencies": {
    "@types/d3": "^5.7.2",
    "@types/jquery": "^3.3.30",
    "@types/lodash": "^4.14.135",
    "@types/nprogress": "^0.2.0",
    "@vue/cli": "^3.12.1",
    "bootstrap": "^4.3.1",
    "brunch": "^3.0.0",
    "canvas": "^2.6.1",
    "core-js": "^2.6.5",
    "d3": "^5.9.7",
    "jquery": "^3.4.1",
    "lodash": "^4.17.15",
    "nprogress": "^0.2.0",
    "query-string": "^6.8.1",
    "quill": "^1.3.6",
    "shards-vue": "^1.0.4",
    "svgsaver": "^0.9.0",
    "vega": "^5.9.1",
    "vega-embed": "^4.2.1",
    "vega-lite": "^3.4.0",
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.2",
    "vue-multiselect": "^2.1.6",
    "vue-property-decorator": "^8.1.0",
    "vue-router": "^3.0.3",
    "vue-spinners": "^1.0.2",
    "vue-vega": "^1.0.0-alpha.13",
    "vuex": "^3.0.1",
    "vuex-persistedstate": "^2.5.4"
  }
```
> it looks like you're using an old version (1.6.11). You need to use a 2.x version

I didn't find any place in the project where there is mentioned about `canvas-prebuilt`, though I find it after npm install in `package-lock` followed by the installation info of `canvas`. Or it comes by default with the installation of canvas?
Thanks for answer in advance. It 3rd day I'm struggling with this error.

P.S I'm using MacOS version 10.14.6

**Comment by zbjornson** [comment]
@NodiraIbrogimova I'm not sure. Do any of those dependencies possibly depend on an old version of canvas? (search your package-lock for "canvas" maybe)

**Comment by NodiraIbrogimova** [comment]
Yes, I have a canvas in the dependency list in the `package.json` file (provided in my comment above).
However, even though I deleted canvas from dependency list and installed `npm` again (after deleting `node_modules` and `package-lock.json`) I'm still getting the error.
I think `vue-vega` uses `canvas-prebuilt` internally. But, how can I fix it without deleting vue-vega? 
I thought the cause of the error was `node-gyp`, but now I'm hesitating. Hello, dilemma! 😄

**Comment by zbjornson** [comment]
@NodiraIbrogimova your best option is probably to fork vue-vega and update it to use canvas 2.x.

**Comment by NodiraIbrogimova** [comment]
This option sounds more interesting rather than spending time on nonsense trials to fix the issue! Thx

**Comment by prAkash-SVMX** [comment]
@NodiraIbrogimova  i am facing same issue when i am trying to run npm install i am getting :-
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.5-prerelease.1/canvas-prebuilt-v1.6.5-prerelease.1-node-v83-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/prakashnarayan.shukla/Documents/github/fsa-ara-uifw/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:387:35)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/prakashnarayan.shukla/Documents/github/fsa-ara-uifw/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:375:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:375:28)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:290:12)
node-pre-gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:265:9)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/prakashnarayan.shukla/Documents/github/fsa-ara-uifw/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/prakashnarayan.shukla/Documents/github/fsa-ara-uifw/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v14.17.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.5-prerelease.1/canvas-prebuilt-v1.6.5-prerelease.1-node-v83-darwin-x64.tar.gz
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-chai@2.9.0 requires a peer of chai@>=1.9.2 <4 but none is installed. You must install peer dependencies yourself.
npm WARN servicemax_ui_framework@1.0.0 No repository field.
npm WARN servicemax_ui_framework@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.5-prerelease.1 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas-prebuilt@1.6.5-prerelease.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prakashnarayan.shukla/.npm/_logs/2021-09-24T15_45_04_752Z-debug.log



Could  you please help me out here .
