### ISSUE TITLE
Build failure on Windows/libjpeg turbo 2.0.3

### ISSUE THREAD

**Issue by VagrantAI-c** [Automattic/node-canvas#1472]
## Issue
Node-gyp upon rebuild throws error that it cannot open `C:\libjpeg-turbo64\lib\jpeg.lib`
Full log:
```
EDITED\node_modules\canvas>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.12.0 | win32 | x64
gyp info spawn C:\Users\EDITED\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\EDITED\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'EDITED\\node_modules\\canvas\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\EDITED\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\EDITED\\.node-gyp\\10.12.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\EDITED\\.node-gyp\\10.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\EDITED\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\EDITED\\.node-gyp\\10.12.0\\<(target_arch)\\node.lib',
  PdfBackend.cc
  SvgBackend.cc
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  closure.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  register_font.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1181: эх єфрхЄё  юЄъЁ√Є№ тїюфэющ Їрщы "C:\libjpeg-turbo64\lib\jpeg.lib" [EDITED\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `EDITED\Visual Studio Community 2017\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\EDITED\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "EDITED\\NodeVersionManagement\\node\\node.exe" "C:\\Users\\EDITED\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"   
gyp ERR! cwd EDITED\node_modules\canvas
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
Fatal error states in russian with broken encoding that one cannot find stated file (jpeg.lib in my case), and indeed, this folder contains only next files:
```
libjpeg.a
libjpeg.dll.a
libturbojpeg.a
libturbojpeg.dll.a
```

## Steps to Reproduce
1. Follow Windows x64 installation steps
2. Run `node-gyp rebuild` in `/node_modules/canvas` folder
The point is to launch latest fabric in node environment

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
```
+-- canvas@2.6.0 
`-- fabric@3.4.0
  `-- canvas@2.6.0  deduped
```
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Windows 10 x64 Ultimate
* Node v10.12.0
* Libjpeg turbo v2.0.3

**Comment by VagrantAI-c** [comment]
BTW, same error is produced when doing `npm ci --build-from-source`

**Comment by zbjornson** [comment]
It also looks like the files you listed should only appear if GCC is present: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/5db6a6819d0f904e0b58f34ae928fea234adb1a0/release/installer.nsi.in#L60-L64. Which libjpeg-turbo download link did you use? It should be https://sourceforge.net/projects/libjpeg-turbo/files/2.0.3/libjpeg-turbo-2.0.3-vc64.exe/download (assuming 2.x works; I haven't tested anything newer than 1.5.1 myself).

**Comment by VagrantAI-c** [comment]
Yes, I did use this very link. I uninstalled old libjpeg turbo beforehand, then installed 2.0.3 from installer. I'm wondering whether I have gcc.

**Comment by zbjornson** [comment]
Sorry, I sorta botched my comment, should have said "if GCC was present during the build/was used for the build". It looks like you downloaded libjpeg-turbo-2.0.3-gcc64.exe instead of libjpeg-turbo-2.0.3-vc64.exe. Can you double check please? I just checked and 2.0.3-vc64.exe has the correct .lib files.

**Comment by VagrantAI-c** [comment]
Seems like everything builds fine just now. Didn't know there are two versions of same library. Thanks for your help!
