### ISSUE TITLE
Installing the current canvas using npm fails on OSX

### ISSUE THREAD

**Issue by prantlf** [Automattic/node-canvas#1475]
Installing `canvas` in an empty Node.js project fails (the full 2019-09-24T07_04_55_209Z-debug.log is attached below):

```txt
$ cd test
$ npm init -y
$ npm i canvas

> canvas@2.6.0 install ~/test/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/ferdipr/.nvm/versions/node/v10.16.3/bin/node" "~/test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd ~/test/node_modules/canvas
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the canvas@2.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ferdipr/.npm/_logs/2019-09-24T07_04_55_209Z-debug.log
```

My environment:

```txt
$ node --version
v10.16.3
$ npm --version
6.11.3
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
```

Maybe upgrading `node-pre-gyp` would help?

```txt
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
```

[2019-09-24T07_04_55_209Z-debug.log](https://github.com/Automattic/node-canvas/files/3645740/2019-09-24T07_04_55_209Z-debug.log)

**Comment by chearon** [comment]
Maybe try some of the suggestions in mapbox/node-pre-gyp#367? Sounds like it could be caused by a network issue.

**Comment by prantlf** [comment]
Thank you, @chearon, it helped!

I found suspicions, that the command line was `node-pre-gyp install --fallback-to-build`, but I saw no `node-pre-gyp` in `node_modules/.bin`. So I tried to install it locally and re-run `npm i`:

    $ cd ~/test
    $ npm i node-pre-gyp

    + node-pre-gyp@0.13.0
    added 3 packages from 2 contributors, removed 3 packages, updated 3 packages and audited 1136 packages in 3.961s
    found 0 vulnerabilities

    $ npm i

    > canvas@2.6.0 install ~/test/node_modules/canvas
    > node-pre-gyp install --fallback-to-build

    node-pre-gyp WARN Using request for node-pre-gyp https download
    [canvas] Success: "~/test/node_modules/canvas/build/Release/canvas.node" is installed via remote
    added 12 packages from 20 contributors and audited 1250 packages in 107.731s
    found 0 vulnerabilities

Success! After seeing `node-pre-gyp` in your `package.json` I suspected my package lock causing some trouble. I got rid of it and re-run `npm i`:

    $ rm -r node_modules/ package-lock.json
    $ npm i

    npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.

    > canvas@2.6.0 install ~/test/node_modules/canvas
    > node-pre-gyp install --fallback-to-build

    node-pre-gyp WARN Using request for node-pre-gyp https download
    [canvas] Success: "~/test/node_modules/canvas/build/Release/canvas.node" is installed via remote
    npm notice created a lockfile as package-lock.json. You should commit this file.
    added 438 packages from 355 contributors and audited 1250 packages in 124.971s
    found 0 vulnerabilities

Success! In the end, there was some problem in `npm` updating the package lock after I increased a couple of module versions in `package.json` and run `npm i` to take care of the installation. The freshly created package lock works well.
