### ISSUE TITLE
Problem with install on Debian

### ISSUE THREAD

**Issue by dpopek92** [Automattic/node-canvas#1480]
I have a little problem with installing canvas on Debian 9. 

> canvas@2.6.0 install /opt/nodeserver/blow/node_modules/canvas
> node-pre-gyp install --fallback-to-build

>node-pre-gyp WARN Using needle for node-pre-gyp https download
>node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.0 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
>node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/opt/nodeserver/blow/node_modules/canvas/build'
>gyp WARN EACCES user "blow" does not have permission to access the dev dir "/root/.cache/node-gyp/10.16.3"
>gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/nodeserver/blow/node_modules/canvas/.node-gyp"
>gyp WARN install got an error, rolling back install
>gyp WARN install got an error, rolling back install
>gyp ERR! configure error
>gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/nodeserver/blow/node_modules/canvas/.node-gyp'
>gyp ERR! System Linux 4.9.0
>gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node->gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/nodeserver/blow/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/nodeserver/blow/node_modules/canvas/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
>gyp ERR! cwd /opt/nodeserver/blow/node_modules/canvas
>gyp ERR! node -v v10.16.3
>gyp ERR! node-gyp -v v5.0.3
>gyp ERR! not ok
>node-pre-gyp ERR! build error
>node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/nodeserver/blow/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/nodeserver/blow/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
>node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
>node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
>node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
>node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
>node-pre-gyp ERR! System Linux 4.9.0
>node-pre-gyp ERR! command "/usr/bin/node" "/usr/bin/node-pre-gyp" "install" "--fallback-to-build"
>node-pre-gyp ERR! cwd /opt/nodeserver/blow/node_modules/canvas
>node-pre-gyp ERR! node -v v10.16.3
>node-pre-gyp ERR! node-pre-gyp -v v0.13.0
>node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/nodeserver/blow/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/nodeserver/blow/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
>npm WARN ordersmanagement@1.0.0 No repository field.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the canvas@2.6.0 install script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     /root/.npm/_logs/2019-10-07T16_25_33_911Z-debug.log`

* Environment (Debian 9.7, Node 10.16.0, NPM 6.9.0)

**Comment by LinusU** [comment]
> EACCES user "blow" does not have permission to access the dev dir "/root/.cache/node-gyp/10.16.3"

> EACCES: permission denied, mkdir '/opt/nodeserver/blow/node_modules/canvas/.node-gyp'

Seems like the user you are running as doesn't have the appropriate permissions...
