### ISSUE TITLE
Could not work under nodejs 13

### ISSUE THREAD

**Issue by taoqf** [Automattic/node-canvas#1483]
## Issue or Feature

Could not install package.

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):2.6.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):node v13.0.1 on Debian 10

**Comment by DominusVilicus** [comment]
Also not working for me

**Comment by DominusVilicus** [comment]
@taoqf were you able to fix?

**Comment by taoqf** [comment]
It seems could be installed now. @DominusVilicus

**Comment by taoqf** [comment]
I've tried 2.6.0 and 2.6.1, both will do.

**Comment by taoqf** [comment]
Sorry, I was wrong.
Maybe I installed it success full because there was a version was installed already.
I tried again, and removed node_modules before that, it failed again.
