### ISSUE TITLE
Issue while installing canvas

### ISSUE THREAD

**Issue by wizanyx** [Automattic/node-canvas#1487]
## Issue or Feature
When installing canvas on Linux the following error pops up.
`node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v64-linux-musl-x64.tar.gz`

## Steps to Reproduce
Do `npm install canvas` on linux. 

## Your Environment
* Environment: Node v10 on linux

**Comment by zbjornson** [comment]
There's no prebuild available for musl libc (https://github.com/node-gfx/node-canvas-prebuilt/issues/77). Until there is, you'll have to build from source (https://github.com/Automattic/node-canvas#compiling).

**Comment by Weirdo914** [comment]
Which is the latest version available for musl libc

**Comment by zbjornson** [comment]
There's never been a musl prebuild for any version of node-canvas yet.

**Comment by GimpMaster** [comment]
Here are the packages I had to install to get it to install and compile from source on Alpine.

apk add --no-cache make gcc g++ python pkgconfig pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev

**Comment by beingyash** [comment]
Thanks @GimpMaster It worked like a charm.
