### ISSUE TITLE
BMPs made from Super Smash Bros Crusaids don't work

### ISSUE THREAD

**Issue by NightYoshi370** [Automattic/node-canvas#1492]
Images made from the Super Smash Bros Crusaids game render blank when processed through node-canvas

## Issue or Feature
It's an issue

## Steps to Reproduce
Load this image: https://cdn.discordapp.com/attachments/318888570691518465/644651359282528257/resultsbg.bmp
Then create a new canvas of this size, paste this exact image and then export it to a PNG buffer

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): latest, which I think is 6.1.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
Node 10.x on ubuntu

Credits to Lakifume from the Mario Maker Modding community for accidentally finding it out

**Comment by NightYoshi370** [comment]
Hey, can anyone else reproduce this using the image I gave above?
Also, @Hakerh400, since you took care of the last BMP issue, do you mind taking a look at this as well?

**Comment by Hakerh400** [comment]
This should fix the issue

```diff
diff --git a/src/bmp/BMPParser.cc b/src/bmp/BMPParser.cc
index 1dcc48b..d649587 100644
--- a/src/bmp/BMPParser.cc
+++ b/src/bmp/BMPParser.cc
@@ -305,7 +305,12 @@ void Parser::parse(uint8_t *buf, int bufSize, uint8_t *format){
               blue = U1UC();
               green = U1UC();
               red = U1UC();
-              alpha = U1UC();
+              if(infoHeader >= 3){
+                alpha = U1UC();
+              }else{
+                alpha = 255;
+                skip(1);
+              }
               break;
           }
           break;
```
