### ISSUE TITLE
Facing issue when converting image of resolutions 56000x28000

### ISSUE THREAD

**Issue by CodezerosDev** [Automattic/node-canvas#1494]
When I try to convert an image of the resolution mentioned above the node got crashed and it says: 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
[nodemon] app crashed - waiting for file changes before starting...

## Steps to Reproduce
try to converting an image which resolution mentioned above

## Environment
* Version of node-canvas :  canvas@^2.4.1
* Environment :node v10.17.0 on Ubuntu 18.04.3 LTS

**Comment by zbjornson** [comment]
That likely means you don't have enough memory available (~6.7 GB). Besides that though, Cairo can't work with images larger than 32,767 px in either dimension.
