### ISSUE TITLE
How to pack canvas.node by rollup?

### ISSUE THREAD

**Issue by HelloDennis** [Automattic/node-canvas#1504]
**rollup version:** v1.27.14
**node version:** v10.15.3
**npm version:** 6.13.4
**syster:** windows 10

When I pack it, i got this error:

> **[!] Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)**
> node_modules\canvas\build\Release\**canvas.node** (1:2)
> 1: MZ� �� � @ � � �!�L�!This program cannot be run in DOS mode.
> ^
> 2: $ �=�\j��\j��\j��:n��\j��:i��\j��:o�\j�<����\j��4i��\j��4n��\j��\j�u\j��4o��\j��:k��\j��\k�G\j�85c��\j�85j��\j�85���\j�85h��\j�Rich�\j�
> 0� p l P p �. @ .text h3 4 `.rdata �, P . 8 @ @.data
> � @ B
> �%I ���%�H ���%"I ���%�F ���%"G ���%�H ���%�F ���%�G ���%�G ���%�H ���%�F ���%*F ���%�F ���%�H ���%�G ���%"H ���%�F ���%�E ���%G ���%"G ���%G ���
> G ���%jG ���%JG ���%�F ���%�F ���%�F ���%�G ���%G ���%:H ���%rG ���%�E ���%RE ���%�G ���%:G ���%zG ���%�F ���%�G ���%�G ���%RE ���%JG ���%�E ���%F
> ���%�F ���%2E ���%jG ���%�F ���%�E ���%G ���%F ���%�F ���%RG ���%�E ���%"E ���%ZF ���%:E ���%�D ���%�F ���%�D ���%�F ���%�F ���%jG ���%�E ���%�F ��
> �%G ���%�D ���%�E ���%BF ���%�F ���%JE ���%
> 3: F ���%�D ���%�D ���%�E ���%�C ���%*E ���%�D ���%jD ���%�D ���%E ���%�E ���%:D ���%�E ���%�F ���%�C ���%�C ���%*D ���%BE ���%�C ���%�E ���%�C ���%
> rF ���%
> Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

There is a loader for webpack here: https://github.com/Automattic/node-canvas/issues/867.
However, i don't know how to deal with it in rollup.

Is there any plugin which can pack .node files?

Thanks so much!

**Comment by zbjornson** [comment]
I've never used rollup, but I see a native module loader here: https://github.com/danielgindi/rollup-plugin-natives

Note that if you're bundling for use in a Web browser, you don't need this (canvas) module and can use native HTML canvas directly.

**Comment by LinusU** [comment]
If you are bundling for the browser, set the `browser` flag to `true` and it should work automatically: https://github.com/rollup/plugins/tree/master/packages/node-resolve#browser

If you are bundling for Node.js, use the native module loader that **zbjornson** linked.

**Comment by acidjazz** [comment]
use `rollup-igonre-plugin`

```js
rollupConfig: {
  plugins: [ignore(['canvas'])],
},
```
