### ISSUE TITLE
when I install the canvas, I always get this interface

### ISSUE THREAD

**Issue by yaozhongnan** [Automattic/node-canvas#1507]
![微信截图_20200103095023](https://user-images.githubusercontent.com/42015945/71703357-16cad480-2e0f-11ea-9041-98d36beacad1.png)

It's stuck in this interface

I waited an hour, two hours, always

I tried to install other versions, latest, 2.6.0, 2.5.0....，results the same

I installed everything needed for Windows according to the documentation

crying

the environment: node -v 12.13.1, windows 10

**Comment by zbjornson** [comment]
That sounds like your internet connection is stuck or something. You can force it to build from source using `npm i canvas@latest --build-from-source`, since you already did the preparations for Windows.

**Comment by yaozhongnan** [comment]
@zbjornson Thanks for your reply, it works, thanks for helping.
