### ISSUE TITLE
Install on Windows 10 and Node 12

### ISSUE THREAD

**Issue by taviroquai** [Automattic/node-canvas#1510]
## Issue or Feature
Issue. Can't install.

## Steps to Reproduce
$ npm install canvas
canvas@1.6.13 install D:\project\node_modules\canvas
node-gyp rebuild

D:\project\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
d:\project\node_modules\canvas\src\init.cc(37): warning C4996: 'v8::Object::Set': was declared deprecated [D:\project\node_modules\canvas\build\canvas.vcxproj]
  c:\users\mafonso\appdata\local\node-gyp\cache\12.14.0\include\node\v8.h(3402): note: see declaration of 'v8::Object::Set'
d:\project\node_modules\canvas\src\canvaspattern.cc(34): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [D:\project\node_modules\canvas\b 
uild\canvas.vcxproj]

(More 99 errors and eventually...)

d:\project\node_modules\canvas\src\canvasrenderingcontext2d.cc(2111): fatal error C1003: error count exceeds 100; stopping compilation [D:\project\node_modules\canvas\build\ca 
nvas.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\mafonso\cushman\node_modules\canvas
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1

## Your Environment
* Window 10 64bits
* Node v12.14.0

Any ideia would be helpfull. Thanks!

**Comment by tima101** [comment]
I have similar output when I try to install dependencies for project that has `chart.js` and `chartjs-node`.

Ubuntu 18.04.3 LTS
Node 12.4.0

```
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠈ canvas
error /home/tima/apps/async/github/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/tima/apps/async/github/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/tima/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
...
...
canvas.target.mk:139: recipe for target 'Release/obj.target/canvas/src/Canvas.o' failed
make: Leaving directory '/home/tima/apps/async/github/node_modules/canvas/build'
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tima/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-72-generic
gyp ERR! command "/home/tima/.nvm/versions/node/v12.4.0/bin/node" "/home/tima/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tima/apps/async/github/node_modules/canvas
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by zbjornson** [comment]
@taviroquai hm, you're the second person for whom "npm install canvas" has tried to install an old (1.x) version (#1490), and there wasn't enough info to keep troubleshooting the other case. Are you using a private NPM registry or anything else like that that could cause it to fetch an old version instead of 2.x?

**Comment by zbjornson** [comment]
@tima101 there's not enough info in that output to debug, but from that little bit it looks like a different problem, if you'd like to open a separate issue.

**Comment by taviroquai** [comment]
@zbjornson Thanks for the enlighment =D. I'm creating a development environment of an "old" project on a Windows host and indeed the canvas version on package.json was 1.x.

With ```npm install canvas@latest``` no errors! We can close this.

**Comment by sam13591980** [comment]
Hello everyone!
I have the same issue

Could you please check here?
