### ISSUE TITLE
Installation problem with Node.js v12.13.0

### ISSUE THREAD

**Issue by NoTalk-ly** [Automattic/node-canvas#1513]
when I remove the down a repository which use the node-canvas, 
i install by this command:  npm i --repository=https://registry.npmjs.org/
the install hangs on node-pre-gyp WARN Using request for node-pre-gyp https download.

## Issue or Feature

but I install again it succeed. I repeat this case by remove node_module folder and package-lock.json and it will happen.
![image](https://user-images.githubusercontent.com/30374176/72313522-933e9c80-36c6-11ea-92cc-0ace0c31992b.png)

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 12.13.0 centos 7

**Comment by NoTalk-ly** [comment]
![image](https://user-images.githubusercontent.com/30374176/72322775-289b5a00-36e2-11ea-8ec9-88c9ac567a88.png)
It's so strange.  when I `npm i ` first time , the install process hangs on node-pre-gyp WARN Using request for node-pre-gyp https download. At that time I stop the process and `npm i ` again, it worked. although it works by this method, I wonder the problem's reason and to find a more elegant method to fix this problem.

**Comment by zbjornson** [comment]
Any chance something is locking the install or temp directory? Does the same problem happen with yarn?

**Comment by NoTalk-ly** [comment]
@zbjornson I will try your method.  I found another problem: I run `npm install --build-form-source canvas`，the install process is ok. but when I run the code that `loadImage(svgImgUrl)`, throw a error 

> Error: node-canvas was built without SVG support.

**Comment by zbjornson** [comment]
SVG support is optional; try installing librsvg2-devel first and then rebuilding.

If you need SVG support, I think you have to build from source anyway -- I don't think prebuilds have SVG support (I might be wrong though).

**Comment by NoTalk-ly** [comment]
@zbjornson I installed librsvg2, I dont know the differnce from librsvg2-devel and libsvg.
![image](https://user-images.githubusercontent.com/30374176/72325040-3d2e2100-36e7-11ea-8550-698873aef28c.png)
I install the canvas by `npm install --build-from-souce canvas`, in OS X，no problem. but in centOS 7, the mentioned problem happend.

**Comment by NoTalk-ly** [comment]
got it done!
you should do something In CentOS:

`yum install librsvg-devel` librsvg-devel is different from librsvg. I read the package's summary found that librsvg-devel is used to 
> Libraries and include files for developing with librsvg
I think you should add the package to the dependencies in README.MD >  Installation > Compiling > Fedora > Command and https://github.com/Automattic/node-canvas/wiki/Installation%3A-Fedora-and-other-RPM-based-distributions 's installing dependencies. @zbjornson

**Comment by alessiopremoli** [comment]
For anyone coming here building the lib for an alpine distribution, the package should be `librsvg-dev` (https://pkgs.alpinelinux.org/package/edge/community/x86_64/librsvg-dev)

**Comment by irfaan008** [comment]
I came across this error still (Nov 2023) on Mac M1. I am using canvas=2.11.2 and node=20.3.1. What seemed to work for me was:

Uninstalling canvas: `npm uninstall canvas`
Installing librsvg `brew install librsvg`
Rebuilding canvas: `npm rebuild --build-from-source=canvas`
Reinstall canvas: `npm install canvas`
