### ISSUE TITLE
Cario Npm Package

### ISSUE THREAD

**Issue by SliceWire** [Automattic/node-canvas#1519]
Hey Canvas Team! 

I just created a cario package that you can install.

it will make it simpler for windows users. and it works out-of-the-box.

here's the link:  [cario](https://www.npmjs.com/package/cario)

Thank's!

**Comment by NxYs-Developer** [comment]
you only have to install cario once non-globally for all of your packages

**Comment by zbjornson** [comment]
Thanks for the note. That appears to just be the unbuilt cairo source published to npm? Prebuilds address the same goal and are built-in. (There also seems to be no matching source repository for that package...)
