### ISSUE TITLE
addPage not defined

### ISSUE THREAD

**Issue by ikit** [Automattic/node-canvas#1520]
Hi, I'm stuck with a weird error... 
I don't understand, because the addPage() seems to be a well documented method...

## Issue or Feature
Do not compile due to the following error:
```
Property 'addPage' does not exists on type 'NodeCanvasRenderingContext2D'.
```

Note that I try to put the addPage() on the canvas object, then the project compile, but at the runtime, I got the following error:
```
canvas.addPage is not a function
```

## Steps to Reproduce

```js
import { createCanvas } from "canvas";

const canvas = createCanvas(200, 200, "pdf");
const ctx = canvas.getContext('2d');

for (let i=0; i<4; i++) {
    ctx.fillText("test " + i, 5, 40*i);
    ctx.addPage();
}
```

## Your Environment
* canvas 2.6.1 installed from npm
* node 12 on Windows 10
* typscript project

**Comment by zbjornson** [comment]
Hrm, I can't reproduce that.

```
> const {createCanvas} = require("canvas")
> const canvas = createCanvas(200, 200, "pdf");
> const ctx = canvas.getContext("2d")
> ctx.addPage()
> ctx.addPage
[Function: addPage]
```

Since you're using Typescript, note that #1509 corrected an error in the typings: `addPage` was declared on the canvas instance instead of the context.

Can you inspect the properties of your `ctx` instance?

**Comment by ikit** [comment]
ok thanks, it's the same problem that the #1509

**Comment by clayplumridge** [comment]
Just ran into this myself; is there another anticipated release coming any time soon?
