### ISSUE TITLE
Crash on Image::SetSource

### ISSUE THREAD

**Issue by Dramex** [Automattic/node-canvas#1525]
A crash without any proper Error 

## Issue or Feature

```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [node /home/x/bot/bot.js]
 2: 0x11e7fec [node /home/x/bot/bot.js]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node /home/x/bot/bot.js]
 4: Image::SetSource(Nan::FunctionCallbackInfo<v8::Value> const&) [/home/x/bot/node_modules/canvas/build/Release/canvas.node]
 5: 0x7fdbe8d90117 [/home/x/bot/node_modules/canvas/build/Release/canvas.node]
 6: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node /home/x/bot/bot.js]
 7: 0xb7a9ac [node /home/x/bot/bot.js]
 8: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node /home/x/bot/bot.js]
 9: 0x32efca7842fd
```
## Steps to Reproduce

My script running very well, I have an image with text above it. the image provided by the user. Sometimes my script crash with that error. it happens like 10 times a day! or less

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
├── canvas@2.6.0 
└─┬ konva-node@0.11.1
  └── canvas@2.6.0  deduped
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
node v8.11.1 - debian 9

**Comment by zbjornson** [comment]
That often means there's not enough memory. Even if node-canvas threw a proper Error instead, v8 would likely crash immediately after. Alternatively, it's possible some other exception happened, but I can't tell without seeing your script. Can you provide more context about your script?

**Comment by Dramex** [comment]
i have been struggling with this issue and i didn't know it's memory!! Turn out my node.js limit processes at ~1.3 gb, solved after increasing that limit.

Thanks @zbjornson for leading me to that limit. :)

**Comment by alrdebugne** [comment]
Hi, same issue here I believe:
```
[nodemon] starting `node --inspect server/index.js`
Debugger listening on ws://127.0.0.1:9229/d468cec9-f486-4512-acf1-d2c862152f3a
For help, see: https://nodejs.org/en/docs/inspector
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x1012e3d85 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a6239 node::Abort() [/usr/local/bin/node]
 3: 0x1000a639f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001eadd0 v8::V8::ToLocalEmpty() [/usr/local/bin/node]
 5: 0x1053d7a44 Image::SetSource(Nan::FunctionCallbackInfo<v8::Value> const&) [/Users/alrdebugne/projects/slime_soccer_online/node_modules/canvas/build/Release/canvas.node]
 6: 0x1053adced Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/alrdebugne/projects/slime_soccer_online/node_modules/canvas/build/Release/canvas.node]
 7: 0x10025a2d8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 8: 0x10025986c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 9: 0x100258f92 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x100a7a139 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
```

The error happens a few seconds after I start `node`. Increasing memory through `--max-old-space-size=1024` etc. did not help (went up to 8GB).

## More details

The script is a simple Phaser game. I'm running a server to handle the physics, with clients connecting to the server. I'm using `express`, `socket.io` and a Phaser-specific package called `@geckos.io/phaser-on-nodejs`. Let me know which details you require.

## Environment

### Version of node-canvas

└─┬ @geckos.io/phaser-on-nodejs@1.2.3
  └── canvas@2.6.1 

### Environment
macOS Catalina (10.15.7), node v14.15.3

**Comment by alrdebugne** [comment]
Posting as a new issue!

**Comment by zbjornson** [comment]
@alrdebugne without a repro it's hard to troubleshoot this. Closing for now but will reopen if you can provide more info.
