### ISSUE TITLE
How do i load google fonts on the sever side node js

### ISSUE THREAD

**Issue by KashafS98** [Automattic/node-canvas#1527]
## Issue or Feature
I am using node js and canvas to create an API that writes text on a certain image. I successfully created a route such as -> /:sometext/:fontsize/:color/:position-x/:position-y and sends a static image with the text of the given font-size, color, and position on the canvas.

What I am unable to achieve is that I want to send the font family in the route and have that rendered on the screen. Plus, isn't there any other way that I can load at least google fonts without having to download the .ttf file.

What I have tried:

1. GetGoogleFonts npm package (which was a bad idea, since it was stuck at the installation)
2. WebFontLoader (Gives "Window is not defined" error)

## Steps to Reproduce

Currently, I am using a ttf file to load the font

router.get('/thumbnail/:name/:fontsize/:color/:posx/:posy', function (req, res, next) {
  let name = req.params.name;
  let fontsize = req.params.fontsize
  let positionx = req.params.posx 
  let positiony = req.params.posy
  let color = req.params.color

  let myimage = 'static/image1.jpg'

  const canvas = createCanvas(2000, 1000)
  const ctx = canvas.getContext('2d')
  var str = "hi "+name
  registerFont('AvenirNext.ttf', { family: 'Avenir Next' })
  loadImage(myimage).then((image) => {
  ctx.drawImage(image, 0 , 0, 2000, 1000);
  ctx.font = fontsize + "px Avenir Next"
  ctx.fillStyle = color
  ctx.fillText(str, positionx, positiony);

  const out = fs.createWriteStream(__dirname + '/test.jpeg')
  const stream = canvas.createJPEGStream()
  stream.pipe(res)
  out.on('finish', () =>  console.log('The JPEG file was created.'))

})
});

**Comment by zbjornson** [comment]
node-canvas can't fetch remote font files, so you either need to download them manually or have your API function save the required files. For Google Fonts, the easiest way I know of is to download from [the GitHub repo](https://github.com/google/fonts/tree/master/ofl), like `https://github.com/google/fonts/raw/master/ofl/baskervville/Baskervville-Italic.ttf`. Is that what you're asking/is that helpful?

**Comment by KashafS98** [comment]
> [o](https://github.com/google/fonts/tree/master/ofl), like `https://github.com/google/fonts/raw/master/ofl/baskervville/Baskervville-Italic.ttf`. Is that what you're asking/is that helpful

Hey thanks @zbjornson , I'm gonna try this out as soon as I get some time on my hands. I appreciate the help!! :)

**Comment by nicktaras** [comment]
You could try using Google Puppeteer or JSDom to emulate the browser within Node.

**Comment by tatihub** [comment]
Would be nice to have as some of us don't actually have access to the local system (using cloud functions)

**Comment by zbjornson** [comment]
@tatihub there's a local scratch disk with cloud functions.

**Comment by daweichendoctor** [comment]
> @tatihub there's a local scratch disk with cloud functions.

I have the the same question ,  project use cloud save 
I was helpless. @tatihub @zbjornson

**Comment by atumas-bananamilk** [comment]
any update? this is bizarre in 2026..
