### ISSUE TITLE
Canvas.Image is not a constructor

### ISSUE THREAD

**Issue by videetparekh** [Automattic/node-canvas#1528]
## Issue or Feature
I am using `node-canvas` to generate an ImageElement from a Base64 URI. This code seems to be logically correct, but for some reason it keeps generating the following error (note, the code is obfuscated and minified before deploy/test, so the error was manually traced to ):

```
Here 2: TypeError: i.Image is not a constructor

// "i" is presumably the obfuscated Canvas object 
```

## Steps to Reproduce

```js
const Canvas = require('canvas')
// ...
// ...
async function function(base64String) {
  return new Promise((resolve, reject) => {
    let img = null
    try {
      img = new Canvas.Image()
    } catch(e) {
      reject("Here 2: " + e)
    }
    img.onload = () => {
      // create the tensor after the image has loaded
      img.src = base64String;
      img.width = 28;
      img.height =  28;
      resolve(img)
    }
    img.onerror = reject;
  });
}
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.6.1 
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): CloudFlare Worker (running on V8 Engine), with support for npm

Is there an import issue here?

**Comment by zbjornson** [comment]
That means node-canvas isn't installing or loading properly. I haven't used CloudFlare Workers, but looking at their docs, I see a few possible issues:

- There's a 1MB maximum code size. Node-canvas is about 27 MB.
- I can't find any documentation on how CloudFlare handles native Node.js addons like node-canvas, or the execution environment (version of Linux and installed packages).
- It uses webpack by default, so you might need to configure webpack to handle native modules.

Your best bet would probably be to ask CloudFlare support or post in their community forums.

**Comment by LinusU** [comment]
closing for now, happy to reopen if you need more help!

**Comment by jardicc** [comment]
In my case this was caused that I had .node file alone without other .dll files.
