### ISSUE TITLE
Server crashes on starting the node app. Issue related to canvas node.

### ISSUE THREAD

**Issue by naivedeveloper95** [Automattic/node-canvas#1529]
![image](https://user-images.githubusercontent.com/15083393/75136473-d6028400-570a-11ea-8aad-8b24958ba273.png)

**Here is the complete log of the issue.**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Madrobot@0.0.1~prestart: Madrobot@0.0.1
6 info lifecycle Madrobot@0.0.1~start: Madrobot@0.0.1
7 verbose lifecycle Madrobot@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle Madrobot@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Dev\Phable\phable.api.backend.satyam.js\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\HashiCorp\Vagrant\bin;C:\ProgramData\chocolatey\bin;C:\Users\satyam\.windows-build-tools\python27\;C:\Users\satyam\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\satyam\AppData\Local\Programs\Python\Python38-32\;C:\Users\satyam\AppData\Local\Microsoft\WindowsApps;C:\Users\satyam\AppData\Roaming\npm;C:\Users\satyam\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\MongoDB\Server\4.2\bin;C:\MinGW\bin;C:\Program Files (x86)\Java\jre1.8.0_231\bin;C:\Octave\Octave-5.1.0.0\usr\bin;C:\libjpeg-turbo64\bin
9 verbose lifecycle Madrobot@0.0.1~start: CWD: D:\Dev\Phable\phable.api.backend.satyam.js
10 silly lifecycle Madrobot@0.0.1~start: Args: [ '/d /s /c', 'node app' ]
11 silly lifecycle Madrobot@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle Madrobot@0.0.1~start: Failed to exec start script
13 verbose stack Error: Madrobot@0.0.1 start: `node app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid Madrobot@0.0.1
15 verbose cwd D:\Dev\Phable\phable.api.backend.satyam.js
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error Madrobot@0.0.1 start: `node app`
22 error Exit status 1
23 error Failed at the Madrobot@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**It runs fine on linux, but crashes on windows.**

**Comment by bntzio** [comment]
I'm experiencing this issue as well.

**Comment by zbjornson** [comment]
Do you also have sharp.js installed? If so, see https://github.com/Automattic/node-canvas/issues/930.

**Comment by naivedeveloper95** [comment]
Delete package-lock.json, install sharp and also check if windows dev tools (If on Windows) are installed. This worked for me.
