### ISSUE TITLE
behind proxy download path for canvas library.

### ISSUE THREAD

**Issue by khanzzirfan** [Automattic/node-canvas#1530]
Hi Team,
For corporate users who are behind the proxy cannot have access to download anything from github or google storage access.  Is it possible to provide  a download_host for canvas library to download from a self hosted cloud account or alternative download mirror for npm to install the library? Similar to how Puppteer has a download host option.

**Comment by zbjornson** [comment]
I think you can set the `HTTP_PROXY` or `http_proxy` or `npm_config_proxy` environment variable.
