### ISSUE TITLE
Package gobject-2.0 was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by gugvel** [Automattic/node-canvas#1531]
I faced below error while run npm i chartjs-node
I am using MacOs Catalina - v10.15.3

Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gobject-2.0', required by 'cairo', not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gugvel2/Documents/CSD/MP-182/csd/node_modules/canvas
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

![image](https://user-images.githubusercontent.com/45001700/75967882-7cf8d400-5ef2-11ea-96e6-0ef2383c24d7.png)

Any pointers on this error to solve..Please check
Thanks,
Velmurugan

**Comment by tgk1** [comment]
brew install glib

**Comment by zbjornson** [comment]
What @tgk1 said. Also note that chartjs-node uses an ancient version of canvas that won't work with node v12.
