### ISSUE TITLE
When I use node canvas to render the picture, I have some strange problems

### ISSUE THREAD

**Issue by Jhaidi** [Automattic/node-canvas#1532]
## my code

```js
const avatarImg = new Image()
 avatarImg.onload = () => {
     ctx.arc(offsetBottom + avatar/2, canvas.height - avatar - offsetBottom + avatar/2, avatar/2, 0, 2 * Math.PI)
     ctx.clip()
     ctx.drawImage(avatarImg, offsetBottom, canvas.height - avatar - offsetBottom, avatar, avatar)
     canvas.createPNGStream().pipe(fs.createWriteStream(curPath))
  }
  avatarImg.onerror = err => { throw err }
  avatarImg.src = data.headurl
// etc.
```
When the image address is normal, the code will run normally. However, when the address is
`http://thirdwx.qlogo.cn/mmopen/vi'32/q0j4twtgtftih6x1x7bhrnqz31e3vvial0ub2akfvktw1y4xf8wnaepdkohjpdoo6rlwc1356khicxrpo5toicg / 132 `, the rendering will have problems

I can draw the URL when I use the above code on my Mac, but I can't when I'm in docker. I want to know how to solve this problem

## my dockerfile
```dockerfile
FROM node:12-alpine

RUN apk add --update \
  make \
  g++ \
  jpeg-dev \
  cairo-dev \
  giflib-dev \
  pango-dev

RUN npm i canvas --build-from-source
```

**Comment by ShunnyBunny** [comment]
How is it abnormal? the url you posted doesn't work for me. I am guessing you ran into the same problem as me where the legends is just all boxes? If that is the case, you need to install fonts for alpine docker image. Add
```
ttf-freefont \
fontconfig
```
to your apk add

**Comment by Jhaidi** [comment]
thanks, 
I know what causes this problem. It's because of asynchronous rendering. I solved this problem through `Peomise`
