### ISSUE TITLE
Highlight some area on Image using rectangle or circle?

### ISSUE THREAD

**Issue by Tatya-winchu** [Automattic/node-canvas#1548]
I have a background Image and there is a object on that Image which I would like to highlight, I have the information about the coordinates of that object with that Information I would like to draw an rectangle/ or any shape around that object. 

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 10.15.3 on Ubuntu 18.4

**Comment by LinusU** [comment]
This issue tracker is mainly for reporting bugs or issue feature request to the Node.js implementation of Canvas.

It seems like you need help with general canvas usage, could you please open a question at [StackOverflow](https://stackoverflow.com) instead?
