### ISSUE TITLE
Adding Blur 

### ISSUE THREAD

**Issue by GodyFromDiscord** [Automattic/node-canvas#1554]
So I currently have this 

        const background = await Canvas.loadImage(data.song.cover);
        ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
        ctx.filter = "blur(6px)";

This pulls the background from an api but I am trying to apply a blur to the background but I cannot find anything about it other than the ctx.filter but that still does not blur the background is there anything else I am missing out on or not? I am trying to get a blur like this image attached
![Discord_NDyQ39KNMC](https://user-images.githubusercontent.com/60844168/79211221-dfbc8400-7e3d-11ea-91fd-4fa3f25f0fd2.png)

**Comment by zbjornson** [comment]
See #1063 - this library doesn't support the `filter` API yet. (When it does, the 2nd and 3rd lines would be reversed btw.)
