### ISSUE TITLE
How do I keep certain texts in a box? 

### ISSUE THREAD

**Issue by AdibHoque** [Automattic/node-canvas#1556]
Sorry but the documentation & examples aren't much useful to know all the functions.

**Comment by zbjornson** [comment]
node-canvas implements the HTML Canvas API, so almost all documentation and examples for HTML Canvas apply to node-canvas.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText

`ctx.fillText(text, x, y, maxWidth)` -- the last argument lets you specify a maximum width that might achieve what you're looking for.

**Comment by AdibHoque** [comment]
How do make it not change size to adjust with the maxwidth but move to the next line?

**Comment by zbjornson** [comment]
That's a question better suited to StackOverflow (see maybe https://stackoverflow.com/questions/2936112/text-wrap-in-a-canvas-element) since it's about how to use the Canvas API.
