### ISSUE TITLE
Binaries for Node.js v14

### ISSUE THREAD

**Issue by Ky6uk** [Automattic/node-canvas#1557]
It looks like binary files for the latest node release (`v14`) are missed. From sources, it compiles well.

**Comment by flaviocopes** [comment]
Meanwhile, if someone stumbles on this and never compiled from source before, I had to install those 2 packages (using Homebrew on macOS):

```
brew install pkg-config 
brew install pango
```

before `npm install` canvas worked

**Comment by perrin4869** [comment]
Binaries would make enabling `node@14` easier: https://github.com/itgalaxy/favicons/pull/306
I noticed that `node@14` was enabled in master already. Any ideas when a release will be published?

**Comment by zbjornson** [comment]
I just uploaded the binaries for v2.6.1 for Node.js v14. :shipit:

**Comment by perrin4869** [comment]
Thank you!!!
