### ISSUE TITLE
Issues with transformed text and letter spacing

### ISSUE THREAD

**Issue by alpfactory-alex** [Automattic/node-canvas#1559]
## Issue or Feature
It seems that whenever text receives a scalation transform the character spacing itself goes wild.

## Steps to Reproduce
see https://github.com/fabricjs/fabric.js/issues/6292

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 12.11 on Mac OS X 10.15.2

**Comment by asturur** [comment]
duplicate of #1544 ?

**Comment by asturur** [comment]
duplicate of #1506

**Comment by zbjornson** [comment]
Thanks @asturur
