### ISSUE TITLE
png file, color change ?? drawImage

### ISSUE THREAD

**Issue by parkheeyoung** [Automattic/node-canvas#156]
var Canvas = require('canvas')
  , Image = Canvas.Image
  , fs = require('fs');

var img = new Image;

img.onload = function(){
  var w = img.width
    , h = img.height
    , canvas = new Canvas(w, h)
    , ctx = canvas.getContext('2d');

```
ctx.drawImage(img, 0, 0);

canvas .toBuffer(function(err, buf){
    fs.writeFile('test.png', buf, function(){
    });
}); 
```

};

img.src = 'default.png';

png file, color change ??

(Canvas(width , height)  == image.width, image.height)  :  The same size 

original image
<img src="http://s1-01.twitpicproxy.com/photos/full/526864039.png?key=21746" />

.....

After image
<img src="http://s1-05.twitpicproxy.com/photos/full/526863462.png?key=21642" />

(Canvas(width+? or  height+?)  > image.width, image.height)  :  normal
ctx.globalAlpha = '0.99' : normal
ctx.globalAlpha = '1' : color change

24bit, 72dpi -> canvas  -> 32bit, 95dpi change??

drawImage bug???

Help me...

**Comment by zbjornson** [comment]
I'm not sure what the question is here, the before and after images are not available anymore. Happy to re-open if you can provide more info.
