### ISSUE TITLE
Issue with installing node-canvas recently.

### ISSUE THREAD

**Issue by jpbberry** [Automattic/node-canvas#1560]
I keep receiving this error when trying to install canvas.
Never had the issue until today and now it's completely messed up my applications.
```
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::ToBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:415:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (canvas->nBytes() > node::Buffer::kMaxLength) {
         ~~~~~~~~~~~~~~~~~^~~~~~
```
Causing there to be errors in the `vega` library. I was getting the same error before when I opened an issue with vega. But I ended up reinstalling node-canvas, and it began working again perfectly.
I am once again getting the same error, reinstalling only gave me the small error seen above and I've no clue what I could possibly do with it.
Any help is appreciated

## Your Environment
* canvas 2.6.1
* ubuntu

**Comment by zbjornson** [comment]
That's only a warning and will not cause compilation to fail. (It's trivial to fix, I'll open a PR soon.) Are you getting other error messages? Can you include your Node.js version please?

**Comment by jpbberry** [comment]
Im using node 11.15, and that's the only bit I'm getting. Whether it's a warning or an error it must be doing something? When create a canvas the vega library reports that it can't read getContext of null. Like I said I had this issue before and reinstalling canvas fixed it. But once again it's failing. Never got the warning the first time so my best guess is it's the issue.

**Comment by zbjornson** [comment]
#1566 will fix the warning, but that's not the cause of this issue. If you can get to the point of calling `canvas.getContext`, that likely means the build was successful and there's some other error.
