### ISSUE TITLE
Stretched or bolded font in rendered canvas on node js is off by a lot of pixels.

### ISSUE THREAD

**Issue by sanathfp** [Automattic/node-canvas#1565]
I'm sending the canvas data to the node js server and doing a 
`fabric.util.enlivenObjects`
to rerender the canvas. I'm converting the canvas to jpeg/png using the sharp library. But the fonts that are stretched or bolded are always off by a lot of pixels in the rendered image. I can confirm that this works fine when I render the canvas on my client application (AngularJS). 

Also, this is not a problem with sharp. I tried a couple of other libraries, they all gave me the same output.

Reproduction script:
Here, canvasObjects is the canvas state.
```
const renderCanvas  = new fabric.StaticCanvas(null, { width: 550 });
fabric.util.enlivenObjects(canvasObjects, async function(objects) {
    objects.forEach(function(obj) {
    renderCanvas.add(obj)
})
```
After the canvas is rendered, I convert it into a jpeg image with sharp.
```
let svgData = renderCanvas.toSVG()
svgData = await getBufferedSVG(svgData);
const stream = sharp(Buffer.from(svgData)).jpeg();
```

The actual canvas on my client application looks like this: https://ibb.co/G34X2Lz
But the rendered jpeg on the node server looks like this: https://ibb.co/pz5Nrvh

PS: Do not worry about the background. Just notice how the text is off.
More info: This works fine when the text is not bolded or stretched.

Nodejs 8.11.1, Canvas: latest version, Platform: Ubuntu

**Comment by zbjornson** [comment]
Can you post a reproduction script, and the info in the issue template please (Node.js version, Canvas version, platform)?

**Comment by sanathfp** [comment]
> Can you post a reproduction script, and the info in the issue template please (Node.js version, Canvas version, platform)?

Hey, I've updated more details in my question. Please take a look at it and let me know if you need more details!

**Comment by zbjornson** [comment]
Can you post a complete/runnable reproduction using Canvas only please?
