### ISSUE TITLE
Font Problems

### ISSUE THREAD

**Issue by Melocet** [Automattic/node-canvas#1569]
`const Canvas = require("canvas"),
Discord = require("discord.js");
const { resolve } = require("path");
// Register assets fonts
Canvas.registerFont(resolve("./assets/fonts/theboldfont.ttf"), { family: "Bold" });
Canvas.registerFont(resolve("./assets/fonts/SketchMatch.ttf"), { family: "SketchMatch" });

const applyText = (canvas, text, defaultFontSize) => {
    const ctx = canvas.getContext("2d");
    do {
        ctx.font = `${defaultFontSize -= 10}px Bold`;
    } while (ctx.measureText(text).width > 600);
    return ctx.font;
};
its my code and giving 

Could not parse font file` error how its wrong?

**Comment by zbjornson** [comment]
See #1164.
