### ISSUE TITLE
404 errors trying to install

### ISSUE THREAD

**Issue by Karrade** [Automattic/node-canvas#1575]
While attempting to run
`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

all i get is this:
Error log: https://pastebin.com/gvZ8cxjt

is there another way to install this on ubuntu?

**Comment by zbjornson** [comment]
Those IP addresses belong to Canonical. It looks like you don't have a working connection to the apt repositories.

Prebuilds for Node v14/canvas 2.6.1 are available now, so you don't need to install those dependencies if that's the version combo you're using.
