### ISSUE TITLE
Install on raspberry (raspbian buster) 404 error 

### ISSUE THREAD

**Issue by RobinSchapendonk** [Automattic/node-canvas#1578]
I'm getting 404 errors when installing canvas

## Issue or Feature

`node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.gz`
`node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)`

(full error: https://pastebin.com/PeqUNuip)
## Your Environment
* npm: 6.14.4
* nodejs: 12.16.3
* node-gyp: 6.1.0
* raspbian buster (debian 10)

**Comment by zbjornson** [comment]
Hi, please see *If you have an ARM CPU* in #1511

**Comment by RobinSchapendonk** [comment]
Yes thank you, I should have read that, but I just scolled over it.
