### ISSUE TITLE
Wiki is vandalized

### ISSUE THREAD

**Issue by Ricket** [Automattic/node-canvas#1579]
The "Installation Windows" page is nonsense: https://github.com/Automattic/node-canvas/wiki/Installation---Windows

It looks like maybe the last good version was this one: https://github.com/Automattic/node-canvas/wiki/Installation---Windows/64e7c20b487cd568e9fa43a40b7fa2f85376b053

**Comment by zbjornson** [comment]
Thanks. That page isn't supposed to exist (the one with a colon -- ["Installation: Windows"](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows) -- is), but it keeps getting resurrected. Guessing there are links to it somewhere.

Anyway, deleted it. Thanks again.
