### ISSUE TITLE
The resource must be a string, Buffer or a valid file stream.

### ISSUE THREAD

**Issue by RobinSchapendonk** [Automattic/node-canvas#1581]
TypeError [REQ_RESOURCE_TYPE]: The resource must be a string, Buffer or a valid file stream.

## Issue or Feature

When I try to draw a local image (also, a url doesn't work) I get the error that its a wrong type.

## Steps to Reproduce

```js
const img = new Canvas.Image();
img.onload = () => ctx.drawImage(img, 0, 0);
img.src = './coin.png';
```
The dir is correct, because I get another error (no such file / dir) if I make it for example ../coin.png

## Your Environment
* canvas@2.6.1
* node v12.16.3, npm v6.14.5, Arch Linux (DE: deepin)

**Comment by RobinSchapendonk** [comment]
Okay I'm dumb this error comes from discord.js

**Comment by RobinSchapendonk** [comment]
But why this:
```js
	if(!!imageURL) {
		console.log(imageURL); // https://cdn.discordapp.com/attachments/705070324613513257/710745169670176828/coin-200.png
		const img = new Image();
		img.onload = () => ctx.drawImage(img, 0, 0);
		img.src = imageURL;
	}
```
Just ends up being a transparent background?

**Comment by RobinSchapendonk** [comment]
Okay just promsified a function to draw the image, (because if there's no url, it should just draw a black background). But now I get this error:

```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x558299872e81 node::Abort() [node]
 2: 0x5582997ac38b node::FatalError(char const*, char const*) [node]
 3: 0x5582999ef3eb v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0x7f96402cbe16 Image::SetSource(Nan::FunctionCallbackInfo<v8::Value> const&) [/media/Disk/data/bots/official/Earl/node_modules/canvas/build/Release/canvas.node]
 5: 0x7f96402c7368  [/media/Disk/data/bots/official/Earl/node_modules/canvas/build/Release/canvas.node]
 6: 0x558299a53077 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [node]
 7: 0x558299a53441  [node]
 8: 0x558299a53cea  [node]
 9: 0x558299a54606 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x55829a1cc719  [node]
Aborted (core dumped)
```

**Comment by LinusU** [comment]
> Just ends up being a transparent background?

The problem is that `canvas.toBuffer` is running before `ctx.drawImage`. I would recommend using `loadImage` instead of the constructor:

```js
const { createCanvas, loadImage } = require('canvas')

async function test () {
    const canvas = createCanvas(200, 200)
    const ctx = canvas.getContext('2d')
    const img = await loadImage('https://cdn.discordapp.com/attachments/705070324613513257/710745169670176828/coin-200.png')

    ctx.drawImage(img, 0, 0, canvas.width, canvas.height)

    return canvas.toBuffer()
}
```


> How to install the dependencies for Arch Linux?

We only have instructions for DEB and RPM, maybe you can create a page "Installation: Arch and other pacman based distributions"? Should be easy to adapt from one of the existing

e.g. https://github.com/Automattic/node-canvas/wiki/Installation%3A-Fedora-and-other-RPM-based-distributions

**Comment by RobinSchapendonk** [comment]
Okay thanks, only problem that I don't know which dependencies are needed on Arch.
