### ISSUE TITLE
Pre-built binaries not installing on Mac Mojave 10.14.6 with Node 12.16.3

### ISSUE THREAD

**Issue by tonylukasavage** [Automattic/node-canvas#1587]
## Issue

Pre-built binaries not installing on Mac Mojave 10.14.6 with Node 12.16.3

## Steps to Reproduce
```js
npm install --save canvas
```
## Error Output

```
~/development/project master*
❯ node --version
v12.16.3

~/development/project master*
❯ uname -a
Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

~/development/project master*
❯ npm install --save canvas

> canvas@2.6.1 install /Users/tony/development/fever-dream/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.16.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
```

## Environment
* node: 12.16.3
* node-canvas: 2.6.1
* os: Mac Mojave 10.14.6

**Comment by zbjornson** [comment]
Hi, see the top entry in #1511:

## Installation fails with Node.js v12.16.3 and later

This is due to an upstream issue in the module that downloads prebuilds: tomas/needle#312. That issue will hopefully be fixed today, 20-May.

Workarounds:

    Add request to your package.json. node-pre-gyp will automatically use that instead of needle.
    Use an earlier version of Node.js
    Build from source (see readme)

**Comment by tonylukasavage** [comment]
Thanks for the workarounds, that explains why this isn't an issue in another project I have with `node-canvas`. I use `node-fetch` in the project with the problem, but `request` in the project that does NOT have this problem. I'll sit tight and wait for the upstream fix.
