### ISSUE TITLE
Crash occurred when loading malformed jpg/gif image

### ISSUE THREAD

**Issue by nulltask** [Automattic/node-canvas#159]
#### Version
- Node 0.6.13
- node-canvas 0.10.3
- Cairo 1.10.2
- giflib 4.1.6
- libjpeg 8d
#### Code

``` js
var fs = require('fs')
  , Canvas = require('canvas')
  , Image = Canvas.Image;

var imge = new Image();
img.src = fs.readFileSync('/path/to/malformed.jpg');  // crash occurred!
```
#### Sample images
- http://www.libraw.org/sites/libraw.org/files/P1010671.JPG
- https://si0.twimg.com/profile_images/63752576/ee.gif

**Comment by zbjornson** [comment]
The gif URL is dead.

The JPEG returns "Premature end of JPEG file" instead of crashing the process in current master. (Guessing @LinusU fix it in 236e719541158250732f86f9c275c0a0201dfcea.)
