### ISSUE TITLE
loadImage() throws 'Error: out of memory' on a 19KB Image-Buffer in nodejs

### ISSUE THREAD

**Issue by EngelPika32** [Automattic/node-canvas#1591]
I have a buffer holding an image which I want to draw on my canvas-image. 
But the loadImage() function which allows a buffer in node js fails with this Error. 
Buffer-size: 19942 Bytes

## Issue or Feature

Issue (Bug?). I think the loadImage() function shouldn't fail at a 19KB Image-Buffer because of memory. 

## Steps to Reproduce

```js
// outOfMemoryError.js
const {createCanvas, loadImage} = require('canvas');
// Some code grabbing the image, storing it in the object e as e.b.
// and 19942 Bytes, from my test image, would be a lot to write in here :) 
async function test(){
    const canvas = createCanvas(330, 250);
    const ctx = canvas.getContext('2d');

    console.log(e.b);
    if(Buffer.isBuffer(e.b)){
        console.log("It's a buffer!");
        let img = await loadImage(e.b); // Should work with Buffers? - Fails here

        await ctx.drawImage(img, 80, 0, 35, 35); // Never executed
    }else{
        console.log("Not a buffer :/");
    }
}

test().catch(console.error);
```
Console-Output: 
```
<Buffer fd 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 fd 00 00 00 7a 08 06 00 00 00 77 37 5b fd 00 00 51 fd 49 44 41 54 78 fd fd fd 79 fd 5d 57 75 ... 19892 more bytes>
It's a buffer!
Error: out of memory
    at setSource (projectPath/node_modules/canvas/lib/image.js:91:13)
    at Image.set (projectPath/node_modules/canvas/lib/image.js:65:7)
    at projectPath/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (projectPath/node_modules/canvas/index.js:23:10)
    at test (projectPath/outOfMemoryError.js:19549:25)
    at Object.<anonymous> (projectPath/outOfMemoryError.js:19557:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)

Process finished with exit code 0
``` 
// The outOfMemoryError.js test file is over 19k lines long because I copied a buffer as Buffer-array into the file.

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
 canvas@2.6.1 
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
node: v13.5.0
npm: 6.13.4
Linux x64

**Comment by zbjornson** [comment]
That's *almost* the signature of a PNG, but the first byte is wrong. Node-canvas will attempt to load that anyway, but that's sorta suspicious.

Can you upload your image? From the bytes in your post it's a 253 x 122 pixel 8-bit RGBA image, so will take at least 124 kB to decode.

**Comment by EngelPika32** [comment]
Here: https://cdn.discordapp.com/emojis/553303474289246208.png?v=1 
same for https://cdn.discordapp.com/emojis/602442583729373215.png?v=1 

I'm getting the buffer using axios and Buffer.from().

**Comment by zbjornson** [comment]
Both of those images load for me when I download them with curl, but neither have the same bytes shown in your post.

**Comment by EngelPika32** [comment]
Sorry for letting this lay for so long.

The buffer got somehow edited/corrupted. I'm getting another buffer now - which is working _(my project changed a lot, still WIP)_. 
It got parsed wrongly at some point of processing.
But due to so many changes in my project, it's hard to identify the exact cause without going through every commit, and I don't think this is needed here.

I'm not that much into image buffers. So, I'm not sure if corrupted buffers/images can be (easily) detected. I would have expected to receive an image with some weird looking at the end and not an 'out of memory' error if an image gets edited/parsed wrongly.

Anyways, thanks for the fast help, wouldn't have thought of an incorrect buffer here.

PS: For anyone coming through this issue later: Try to write the buffer into an image file. If you can't view the image, then something is _(might be)_ wrong with the buffer. - That's what I did with the saved copy of the incorrect buffer after I saw @zbjornson's comment^ :)
