### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by RubyPiec** [Automattic/node-canvas#1602]
Issue or Feature
The example isn't working

Steps to Reproduce
```
const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext('2d')

// Write "Awesome!"
ctx.font = '30px Impact'
ctx.rotate(0.1)
ctx.fillStyle = 'green'
ctx.fillText('Awesome!', 50, 100)

// Draw line under text
var text = ctx.measureText('Awesome!')
ctx.strokeStyle = 'green'
ctx.beginPath()
ctx.lineTo(50, 102)
ctx.lineTo(50 + text.width, 102)
ctx.stroke()

console.log('<img src="' + canvas.toDataURL() + '" />')
```

Your Environment
* Environment: repl.it

This is the output for me:
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAABmJLR0QA/wD/AP+gvaeTAAAHm0lEQVR4nO3bW4zUVwHH8e9/doBSlFpuOxdKjbEvYjVaq6GNmmBCY/RJTeOD0UfSxDSi0SBN6IGmULwQYnyQJ2M0Jpo+qtH4oD5Y0/igtpV6RSi7O3uR+67A7sz8fTj/Gf7DzgzThbI7+v0kZGdnzpz/mc35zbn8DyBJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiStCMlyN2BgB/goCdOMMMEDTPM4jeVukv73DUdAvsUazjELvAKUgE3ANFADJoBxAk8ACYGPUWCcESZZYIpAc/karmE3HAEJvBX4DYH7s9+LFBmlThV4B3CEwCiBTcAY8CoxSBuBGWCcGKaTBPZwnFVMsouECZrUgGmDpG6Ky92AAVWII0UUqBM7/TiBeWLnhwJlmvyDwHsAOM4qZthCnSoJD5HyJWAPNarAj0j5JzAKbCQwlV2jBrxKYC9HWctldpIwRpOprEx6xz61lt0wBaTW57UYnvSGIO1mgVaQDrKGtCNILxPYAcQg1RgFtgKPAJ8F9jLL20n5ISmngVEC9xKndmPAJPBHAoEjvJkrfJACZxhhmqeYus2fX8tkOAKSUCbNdfxO+YCU6RWk9KZBGgPGCGxo19GkDLxIYBcAgdUUGaXJVpp8BHgMCFzhQeAHNBmjSYnAPcQgnQGmSfgdT3OEwAYSPpAbkaaX/DfRHTEcAbmxQ+fF8LRC0bvcoEHqrOPGqd08sdOf4QDbSHlXrg2/IvDJrNxqoESBKk0+TsqHgSMkPEzK97P2lgisB6aI4ZwirrOOEdgCvBcYYzVT7GOm9x9Hb6ThCAiUSfhb11dSKiS8lP1WIeGvPcrlQzFYkDrD17tc9yC9BrxGYDtxw6DVhp8S+BwQd+cuUco2Gz4F7ACOAR8Cvg3MME+ZwJuIU7rx7OcvCXyHQIWEB0mz5wP/7tFWLdGwBKRfhy6T8ovc41/3qeOl3ONe5crAy0ArfL2Deasj0pNcA04Dpwm8HygArWA+T+DzQGubu5y9/zPA+7IadpFyCDgHVAjcTT5ICT/hab7bo10aQGG5GzCgypK+yW8sl7TrKOceL7W+fB03u+5E+z1L2Wx4kmsEThF4IbtmrCOhDHyPwDuztdNbgJ0U+ApwmZR397iWBjQ8AVnNeI/XqhTbr+UfL64jzZVL+5TLByTp2fHzdQw2ZYMqyYDX7VVfShWyOlKqHe0LXCVwkv38lnj/p1ebNKCVH5DAXcB65tnOMzyQTSNarxWATWxmmnjTcwv1nlusZe5qf3uXiFOR7uWKuZGm2fMbP19HmULPcvl1TJmkz3UHG+Hyr5X6jKz96tCAVv4aZA1rucbzwLM0KAFVQvv+xlngPLtZ4BCbmadOgYd5hkkajBP4DwBfZx1zFNnLxSxw6wicXXStHzPCCTazmUli4EpsGHAqVuwzghQ7On7vcoWBRq7Xv2unJVv5Afkq54FPdzz3HPdwlWq2mF0LQEoR+BlNDkO2oI27SePMcYFWZxmhTIPLBB5lhBrrmOCLXAHgBJuBC+xmITu2MpstpDvFXaUigQtZ4O5mH+cWlYuB29QRuEafb/zGQCPX4Guk3qOLBrTyA9LNXi4CF4ET7eeeogY83lHuMPeyQCW74Rc/a4OUuIP1HA3KXKJC4Cqxo83S2fnmOMijJEzQoJaVa4Wslns8SbcjKH9nC50j3Gy7jrw4wq3KBa7/CFdmilbgek8VHUFug5UdkMAXgMNcPyMVfyZMZN+OExSo0eQ0gdlF74+jz3ngz7k6T9ErSHH3qHVocR74PU2+RuxsZQJzQI1GO1CtHadrXYO0kNu1mu+zg3U115n7BS6OcOc7RrhugcuPcLolKz0gxzjKcS5lU6Yk+xnvO2wnTkUqwDYCRW5vkP5CvHl33SE2Zh29QqE99ZoFTmRB2ko8szWXtWOBzhGpTuARioyznsn29K2RC0+/UwOLp1fdAzfSMV3TLVjZAQGy9cHJ7F9vR1k7QJDuJzDCzYK0llN8mblF19jHWeLGwCvt5/bzJ+ATHeXidCoefixwGYAC52nyL+Ab1KlyjhKBS8QpUpN4RL8VELoGKX9nv9/5tP4h0+uw8gMyqKUH6W1Zh3oIsvXKHPdlI831EMFEtm16PUxlzmQHHTvFs1MzdAbpRboFqU6JJlXIFvkJ06RMA9+kzlbOsaUdpJQC8EL27gpQ5CA7KDBGnalsU6J1yNIR5DYYjv8wtRw6F/iV7Bs7rkVo/7wPbiFIg3qWURbaI1KN/fyBAzxGyhPQPqY/SpwmTgGrgJ8T2LPkawowILdu5QbpDPuzM2VaMgNyp9zOIMVTwvVl+Rz/ZwzISjNYkLYBlzFIbzgDMoziDcNRCll40nZ4bgzSzmy7WpIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSf38F7fAxUOhkHMkAAAAAElFTkSuQmCC

**Comment by zbjornson** [comment]
That appears to be the correct output, with the caveat that repl.it doesn't have the Impact font installed, so you get boxes instead of letters.

**Comment by RubyPiec** [comment]
I see.
