### ISSUE TITLE
Are you on macOS, Linux or Windows? Which version of node-canvas?

### ISSUE THREAD

**Issue by wike2019** [Automattic/node-canvas#1604]
Are you on macOS, Linux or Windows? Which version of node-canvas?

_Originally posted by @chearon in https://github.com/Automattic/node-canvas/issues/1600#issuecomment-639766406_

win and. Lasted. Version. I install. Use npm install  canvas

**Comment by zbjornson** [comment]
(no need for another issue, this can continue in #1600)
