### ISSUE TITLE
Node-Canvas crashes NodeJS on require, on Android Termux (ARM)

### ISSUE THREAD

**Issue by NatsumiUIX** [Automattic/node-canvas#1609]
## Issue or Feature

Everytime that I started a script that include Node-Canvas, NodeJS crashes and give me the error
```
return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "/data/data/com.termux/files/usr/lib/node_modules/canvas/build/Release/canvas.node"...
```

## Steps to Reproduce

```js
var Canvas = require('canvas');
```

## Your Environment
* Version of node-canvas: canvas@2.6.1 (NPM)
* Environment: NodeJS v14.2.0 on Android Termux (ARM)

**Comment by zbjornson** [comment]
Are you comfortable cloning this repo, making changes and building? If so, you might be able to just make this change:

```diff
diff --git a/binding.gyp b/binding.gyp
index 777032c..68d9c88 100644
--- a/binding.gyp
+++ b/binding.gyp
@@ -128,7 +128,8 @@
             '<!@(pkg-config cairo --libs)',
             '<!@(pkg-config libpng --libs)',
             '<!@(pkg-config pangocairo --libs)',
-            '<!@(pkg-config freetype2 --libs)'
+            '<!@(pkg-config freetype2 --libs)',
+            '-latomic'
           ],
           'include_dirs': [
             '<!@(pkg-config cairo --cflags-only-I | sed s/-I//g)',
```

but based on https://github.com/termux/termux-packages/issues/3092, I'm not sure that will work.

**Comment by KitsuneIDK** [comment]
Yes, I will test and see if work

**Comment by KitsuneIDK** [comment]
Thanks, work perfectly! But still without support to JPEG, GIF or SVG

**Comment by zbjornson** [comment]
@KitsuneIDK do you have libjpeg-dev, libgif-dev and librsvg-dev installed? If not, try installing them. If yes, then they might not be findable by the compiler.

**Comment by Gustavo10Destroyer** [comment]
> Are you comfortable cloning this repo, making changes and building? If so, you might be able to just make this change:
> 
> ```diff
> diff --git a/binding.gyp b/binding.gyp
> index 777032c..68d9c88 100644
> --- a/binding.gyp
> +++ b/binding.gyp
> @@ -128,7 +128,8 @@
>              '<!@(pkg-config cairo --libs)',
>              '<!@(pkg-config libpng --libs)',
>              '<!@(pkg-config pangocairo --libs)',
> -            '<!@(pkg-config freetype2 --libs)'
> +            '<!@(pkg-config freetype2 --libs)',
> +            '-latomic'
>            ],
>            'include_dirs': [
>              '<!@(pkg-config cairo --cflags-only-I | sed s/-I//g)',
> ```
> 
> but based on [termux/termux-packages#3092](https://github.com/termux/termux-packages/issues/3092), I'm not sure that will work.

How to do it? I'm newbie with Termux...

**Comment by Gustavo10Destroyer** [comment]
I'm getting the same problem of this issues '-', on require canvas

**Comment by NatsumiUIX** [comment]
Hello @Gustavo10Destroyer, you can solve this problem cloning the repository, before you only need make the edit specified by @zbjornson, use "npm pack" and "npm install <path to tarball generated in pack>"

**Comment by little-evil-thing** [comment]
> I've did what you suggested but it still give me the following error:
> `Error: dlopen failed: cannot locate symbol "FcConfigAppFontAddFile" referenced by "canvas.node" ...`
i've ggot tha same issue by now, i admit it can be the targeted android api version but, i'm not an android dev so i cannot say much more.

it's quite annoying and i'm still trying to fix that, with no clue it'll work

**Comment by DoveBoy** [comment]
@zbjornson I have the same problem, after using `npm install canvas` on Termux, running nodejs fails. How can I solve it?
