### ISSUE TITLE
i can't install canvas

### ISSUE THREAD

**Issue by Haksiu** [Automattic/node-canvas#1610]
Hey, i can't install canvas to my discord bot

```node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.18.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build'
gyp ERR! System Linux 4.19.0-9-cloud-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/rsa-key-20200524/ThunderBot/node_modules/canvas
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/rsa-key-20200524/ThunderBot/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.0-9-cloud-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/home/rsa-key-20200524/ThunderBot/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/rsa-key-20200524/ThunderBot/node_modules/canvas
node-pre-gyp ERR! node -v v12.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN thunderbolt@1.0.3 No description
npm WARN thunderbolt@1.0.3 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-24T11_25_31_384Z-debug.log```

node version: 12.18.0
npm version: 6.14.5

**Comment by inkrot** [comment]
I have the same problem on Ubuntu 18.04.4

**Comment by inkrot** [comment]
> Hey, i can't install canvas to my discord bot
> 
> ```
> node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.18.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
> node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build' 
> gyp ERR! configure error 
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build'
> gyp ERR! System Linux 4.19.0-9-cloud-amd64
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
> gyp ERR! cwd /home/rsa-key-20200524/ThunderBot/node_modules/canvas
> gyp ERR! node -v v12.18.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/rsa-key-20200524/ThunderBot/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> node-pre-gyp ERR! System Linux 4.19.0-9-cloud-amd64
> node-pre-gyp ERR! command "/usr/bin/node" "/home/rsa-key-20200524/ThunderBot/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /home/rsa-key-20200524/ThunderBot/node_modules/canvas
> node-pre-gyp ERR! node -v v12.18.0
> node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> node-pre-gyp ERR! not ok 
> npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
> npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN thunderbolt@1.0.3 No description
> npm WARN thunderbolt@1.0.3 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the canvas@2.6.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-06-24T11_25_31_384Z-debug.log```
> 
> node version: 12.18.0
> npm version: 6.14.5
> ```

Try to execute next: 
```
sudo npm install canvas --unsafe-perm=true --allow-root --save
```
it worked for me

**Comment by Haksiu** [comment]
> > Hey, i can't install canvas to my discord bot
> > ```
> > node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.18.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
> > node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build' 
> > gyp ERR! configure error 
> > gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build'
> > gyp ERR! System Linux 4.19.0-9-cloud-amd64
> > gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
> > gyp ERR! cwd /home/rsa-key-20200524/ThunderBot/node_modules/canvas
> > gyp ERR! node -v v12.18.0
> > gyp ERR! node-gyp -v v5.1.0
> > gyp ERR! not ok 
> > node-pre-gyp ERR! build error 
> > node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/rsa-key-20200524/ThunderBot/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> > node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/rsa-key-20200524/ThunderBot/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> > node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> > node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> > node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> > node-pre-gyp ERR! System Linux 4.19.0-9-cloud-amd64
> > node-pre-gyp ERR! command "/usr/bin/node" "/home/rsa-key-20200524/ThunderBot/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> > node-pre-gyp ERR! cwd /home/rsa-key-20200524/ThunderBot/node_modules/canvas
> > node-pre-gyp ERR! node -v v12.18.0
> > node-pre-gyp ERR! node-pre-gyp -v v0.11.0
> > node-pre-gyp ERR! not ok 
> > npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
> > npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
> > npm WARN thunderbolt@1.0.3 No description
> > npm WARN thunderbolt@1.0.3 No repository field.
> > npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
> > npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> > 
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
> > npm ERR! Exit status 1
> > npm ERR! 
> > npm ERR! Failed at the canvas@2.6.1 install script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /root/.npm/_logs/2020-06-24T11_25_31_384Z-debug.log```
> > 
> > node version: 12.18.0
> > npm version: 6.14.5
> > ```
> 
> Try to execute next:
> 
> ```
> sudo npm install canvas --unsafe-perm=true --allow-root --save
> ```
> 
> it worked for me

thanks! it worked

**Comment by zbjornson** [comment]
There's some guidance on this issue in #1511 copied below. Generally you should not install with `sudo`.


## I get a permissions error (`EACCES`)

Possibly your `node_modules` or an npm or yarn cache or temp directory is owned by a different user. Review the error log to see what folder you don't have permission to access. See #1429 for an example, or [any of these issues](https://github.com/Automattic/node-canvas/issues?utf8=%E2%9C%93&q=is%3Aissue+eacces).

If you were trying to install with `sudo`, try without. (See [issues](https://github.com/Automattic/node-canvas/issues?utf8=%E2%9C%93&q=is%3Aissue+sudo).)
