### ISSUE TITLE
export image is flurry

### ISSUE THREAD

**Issue by weinixiong** [Automattic/node-canvas#1613]
i want to use the node-canvas to create canvas element and then export the image as file to save.
but i got one flurry image.
i use follow code to get more clear image，but i failed. The layout of the text is too loose。
 ctx.setTransform(2, 0, 0, 2, 0, 0);
the   result is:
![image](https://user-images.githubusercontent.com/19499927/86097039-b29b7b80-bae6-11ea-9c04-231511c21ec4.png)
the image is more clear ,but the layout of text is too loose.
 Is there any way to get a clear picture of canvas?

**Comment by zbjornson** [comment]
Please provide the info that was requested in the issue template (code to reproduce the issue, Node.js and Canvas versions, operating system). Does the image look okay if the same code is run in a browser?
