### ISSUE TITLE
Is it possible to load a font from a buffer instead of a file?

### ISSUE THREAD

**Issue by LJNeon** [Automattic/node-canvas#1614]
My current setup has a data folder full of config files, images, fonts, etc. to load into memory for use. However, I can't seem to figure out how to supply a font buffer to canvas. The current workaround I'm using is blacklisting the fonts sub folder and supplying the file paths, but this is a lot messier in comparison.

**Comment by zbjornson** [comment]
It's not possible yet, see #386 for an explanation.
