### ISSUE TITLE
Webpack - Canvas creation

### ISSUE THREAD

**Issue by marpap** [Automattic/node-canvas#1616]
Hi,

I recently converted a project using "webpack" which is new for me.

I have an issue with the creation of a 2D canvas.
I installed canvas with npm and I have imported it as follows:
import {createCanvas} from 'canvas';

I also use it in my code, as:
let canvas = createCanvas(200, 200);
let context = canvas.getContext('2d');
..........
..........
let texture = new THREE.Texture(canvas);
texture.needsUpdate = true;
texture.minFilter = THREE.LinearFilter; 
let material = new THREE.SpriteMaterial({map: texture,
                                                 transparent: false
                                               }); //Here, I construct the material of the sprites

However, the sprites result in having a huge black box (which I think is canvas) around them.
Is there anything wrong with canvas creation?

Thank you in advance!

**Comment by zbjornson** [comment]
Are you running in a browser or Node.js? #730 has some info on using three.js with node-canvas, but it's not a typical combination.
