### ISSUE TITLE
No block text on Windows, but block Text on Linux

### ISSUE THREAD

**Issue by theADAMJR** [Automattic/node-canvas#1618]
# Issue or Feature
![Windows vs Linux](https://user-images.githubusercontent.com/28284250/87017241-a8a10900-c1c7-11ea-9209-a466a5072630.png)

Windows (left) vs Linux (right)

## Steps to Reproduce
```ts
import { createCanvas, loadImage, CanvasRenderingContext2D, Canvas } from 'canvas';
...
const { canvas, ctx } = this.createCanvas(300, 250);
const pos = { x: canvas.width / 4, y: canvas.height / 5 };
...
ctx.font = '32px Arial, sans-serif';
ctx.fillStyle = 'red';
ctx.fillText('testing123', pos.x, pos.y);
```

## Your Environment
**Ubuntu 18.04 (breaks on)**:
"canvas": "^2.6.1"
Node: v14.4.0

**Windows 10**:
"canvas": "^2.6.1"
Node: v13.10.1

**Comment by zbjornson** [comment]
Do you have fonts installed on the Ubuntu machine? (https://askubuntu.com/a/651442/875375) It should fall-back to some sans-serif if Arial isn't found though. Does it work if you use [`registerFont`](https://github.com/Automattic/node-canvas#registerfont)?

**Comment by theADAMJR** [comment]
Fonts weren't installed on Ubuntu for some reason 😂. Installing them fixed the problem.
Thank you.
