### ISSUE TITLE
Is resizing a canvas possible?

### ISSUE THREAD

**Issue by LJNeon** [Automattic/node-canvas#1624]
In browser, you can simply change the `canvas.width` and `canvas.height` properties, is there an equivalent in `node-canvas`?

**Comment by LinusU** [comment]
You should be able to simply change the `canvas.width` and `canvas.height` properties with this library as well :)

**Comment by LJNeon** [comment]
Are there are potential performance problems with doing this extremely often?

**Comment by LJNeon** [comment]
Also, it would be nice if `canvas.width` and `canvas.`height` were documented somewhere. I looked around documentation and the compatibility list in the wiki and saw nothing.

**Comment by zbjornson** [comment]
I think I only added things to the compatibility wiki that MDN has in their compatibility tables, so missed width/height and probably some other basic ones. Just added width and height though.

> Are there are potential performance problems with doing this extremely often?

Yeah, each time you change the width *or* height it resets and reallocates the internal canvas/memory. Ideally changing those both in succession would only cause one reset/reallocation (#63).

**Comment by LJNeon** [comment]
Which would be cheaper in terms of performance, reusing a single canvas and constantly altering the width and height, or creating a new canvas with varying widths and heights each time?

**Comment by zbjornson** [comment]
I'm not sure, would have to benchmark that. The former reallocates Cairo objects twice, the latter creates v8 objects and allocates Cairo objects once.

**Comment by LJNeon** [comment]
Thanks.
