### ISSUE TITLE
Implement what-wg's new TextMetrics Interface

### ISSUE THREAD

**Issue by raweden** [Automattic/node-canvas#163]
What-WG recently update their specifications for the TextMetrics object. In the specification calls to `ctx.measureText()` now returns more detailed information about the text measured which also describes the height of the bounding box as well as measurement that are essential for drawing multi-line text, as it provides information that could be used to compute the vertical distance of the next line to be drawn.

[What-WG's TextMetrics Interface (updated in April 2012)](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#textmetrics)

**Comment by zbjornson** [comment]
This is supported in 2.x 🎉.
