### ISSUE TITLE
code silently stops at canvas.loadImage function

### ISSUE THREAD

**Issue by Teikuwu** [Automattic/node-canvas#1633]
Hello @zbjornson 

I recently started working on another discord.js bot which was not initially made by me. I've used canvas on my old bot and it worked flawlessly. But now on the new one, it doesn't work and just silently aborts the code at "const background = await loadImage('./xfile/yfile')". Sending a simple string message after that line doesn't work either. I'm using canvas version 2.6.1, node version 12.16.1 and discord.js varies between those 2 bots. The working one uses discord.js 11.6.4, the non-working one uses 12.2.0. Before downgrading the discord.js version of a bot initially not made by me for further attempts/examination, is there anything else you could suggest regarding my issue?
I should add that it doesn't work for links nor local images.

Thank you in advance!

**Comment by Teikuwu** [comment]
Downgrading to discord.js 11.6.4 worked.

**Comment by Jannchie** [comment]
I have the same problem.

**Comment by kiwabotgh** [comment]
Hi Jannchie,
I managed to fix my issue by using canvas version 2.5.0, which works fine with discord.js v12.
For some reason canvas 2.6.4 doesn't want to work with discord.js v12.

**Comment by Jannchie** [comment]
> Hi Jannchie,
> I managed to fix my issue by using canvas version 2.5.0, which works fine with discord.js v12.
> For some reason canvas 2.6.4 doesn't want to work with discord.js v12.

Thanks for your reply! I will try to reduce the version.
