### ISSUE TITLE
No package 'pixman-1' found on Centos 7

### ISSUE THREAD

**Issue by ThenMorning** [Automattic/node-canvas#1634]
## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v10.19.0   on  CentOS Linux release 7.6.1810 (Core)

npm install canvas 
node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download

Package pixman-1 was not found in the pkg-config search path.

Perhaps you should add the directory containing `pixman-1.pc'

to the PKG_CONFIG_PATH environment variable

No package 'pixman-1' found

gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack at ChildProcess.onCpExit (/home/sankuai/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)

gyp ERR! stack at ChildProcess.emit (events.js:198:13)

gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

gyp ERR! System Linux 3.10.0-862.mt20190308.130.el7.x86_64

gyp ERR! command "/home/sankuai/.nvm/versions/node/v10.19.0/bin/node" "/home/sankuai/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi

_label=node-v64"

gyp ERR! cwd /docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas

gyp ERR! node -v v10.19.0

gyp ERR! node-gyp -v v5.0.5

gyp ERR! not ok 

node-pre-gyp ERR! build error

node-pre-gyp ERR! stack Error: Failed to execute '/home/sankuai/.nvm/versions/node/v10.19.0/bin/node /home/sankuai/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0

--node_napi_label=node-v64' (1)

node-pre-gyp ERR! stack at ChildProcess. (/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

node-pre-gyp ERR! stack at ChildProcess.emit (events.js:198:13)

node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:982:16)

node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

node-pre-gyp ERR! System Linux 3.10.0-862.mt20190308.130.el7.x86_64

node-pre-gyp ERR! command "/home/sankuai/.nvm/versions/node/v10.19.0/bin/node" "/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"

node-pre-gyp ERR! cwd /docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas

node-pre-gyp ERR! node -v v10.19.0

node-pre-gyp ERR! node-pre-gyp -v v0.11.0

node-pre-gyp ERR! not ok

**Comment by ThenMorning** [comment]
Anybody help?

**Comment by ThenMorning** [comment]
I have install all the dep follow the wiki about Centos 7.
![image](https://user-images.githubusercontent.com/22017926/88910549-3932ac80-d28f-11ea-84a7-0d20b09338c9.png)

**Comment by ThenMorning** [comment]
Another Error！


[egg-scripts] Error: [egg-core] load file: /docker/opt/meituan/www/waimai_mfe_merlin/app/service/waterMask.js, error: The module '/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/build/Release/canvas.node'

[egg-scripts] was compiled against a different Node.js version using

[egg-scripts] NODE_MODULE_VERSION 57. This version of Node.js requires

[egg-scripts] NODE_MODULE_VERSION 64. Please try re-compiling or re-installing

[egg-scripts] the module (for instance, using `npm rebuild` or `npm install`).

[egg-scripts] at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)

[egg-scripts] at Module.load (internal/modules/cjs/loader.js:653:32)

[egg-scripts] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

[egg-scripts] at Function.Module._load (internal/modules/cjs/loader.js:585:3)

[egg-scripts] at Module.require (internal/modules/cjs/loader.js:692:17)

[egg-scripts] at require (internal/modules/cjs/helpers.js:25:18)

[egg-scripts] at Object. (/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/lib/bindings.js:3:18)

[egg-scripts] at Module._compile (internal/modules/cjs/loader.js:778:30)

[egg-scripts] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

[egg-scripts] at Module.load (internal/modules/cjs/loader.js:653:32)

[egg-scripts]

**Comment by ThenMorning** [comment]
I fixed it by upgrading node version from 8 to 10

**Comment by sachinprabhuk** [comment]
Node version is the issue. 
Changing from 16 -> 14 helped for me.

**Comment by SilvaQ** [comment]
not working , same problem

**Comment by SeiwonPark** [comment]
> Node version is the issue. Changing from 16 -> 14 helped for me.

Thanks it helped me :)
