### ISSUE TITLE
Can't load big image file ( > 10MB ) with loadImage function with Node.js on Ubuntu, CentOS

### ISSUE THREAD

**Issue by thobn24h** [Automattic/node-canvas#1635]
## Issue or Feature

Can't load big image file ( > 10MB ) with loadImage function of “node-canvas” with Node.js on Ubuntu, CentOS ( But working normally with MacOS )

## Steps to Reproduce

```js
const { loadImage } = require('canvas')
loadImage('https://cdn.indyfriend.com/test.svg').then((image) => {
    console.log('success full load image')
})
```

Here is my error:
```
(node:4498) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/home/thobn/Desktop/Project/node_modules/canvas/lib/image.js:91:13)
    at /home/thobn/Desktop/Project/node_modules/canvas/lib/image.js:59:11
    at /home/thobn/Desktop/Project/node_modules/simple-get/index.js:89:7
    at PassThrough.<anonymous> (/home/thobn/Desktop/Project/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (events.js:420:28)
    at PassThrough.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

## Your Environment
Ubuntu 20.04 LTS, 
Npm: 6.14.7, 
Node: v14.6.0

**Comment by zbjornson** [comment]
I'm guessing the image download is failing or getting interrupted. Instead of loading from a URL, could you try downloading the SVG file, verifying that it's complete/valid, and then loading that file?

**Comment by FJEagle** [comment]
I meet the same issue: node-canvas failed to load tensorflow train image(>10M).

image file to reproduce: https://storage.googleapis.com/learnjs-data/model-builder/mnist_images.png
I downloaded the above png file and saved in local filesystem.

`
imgPath = "./data/mnist_images.png";
loadImage(imgPath).then((img) => {
    //won't be here, crashed during loading
    console.log("img:", img)
}
`

OS: Ubuntu 18.04 and win 10
node: v12/v14
npm: 6.x
canvas: 2.6.1

error log:
err: [Error:] invalid value (typically too big) for the size of the input (surface, pattern, etc.)
    at setSource (digitrecognitionnodejsrewrite\node_modules\canvas\lib\image.js:91:13)
    at Image.set (digitrecognitionnodejsrewrite\node_modules\canvas\lib\image.js:65:7)
    at fs.readFile (digitrecognitionnodejsrewrite\data.js:107:15)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 00007FF6A7D8F04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF6A7D6A0C6 node::MakeCallback+4518
 3: 00007FF6A7D6AA30 node_module_register+2032
 4: 00007FF6A7FF4CD6 v8::V8::ToLocalEmpty+54
 5: 00007FFE56075B6C Canvas::getHeight+134732
 6: 00007FFE5605436C Backend::getHeight+2476
 7: 00007FF6A856C122 v8::internal::OptimizingCompileDispatcher::Unblock+59890
 8: 00007FF6A856D5AD v8::internal::OptimizingCompileDispatcher::Unblock+65149
 9: 00007FF6A856C606 v8::internal::OptimizingCompileDispatcher::Unblock+61142
10: 00007FF6A856C4EB v8::internal::OptimizingCompileDispatcher::Unblock+60859
11: 000002742DADC5C1

**Comment by FJEagle** [comment]
Should this issue be reopened? @zbjornson

**Comment by thefat32** [comment]
Having this problem any solution?
