### ISSUE TITLE
was compiled against a different Node.js version using   

### ISSUE THREAD

**Issue by ThenMorning** [Automattic/node-canvas#1637]
## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v10.19.0   on  CentOS Linux release 7.6.1810 (Core)

[egg-scripts] Error: [egg-core] load file: /docker/opt/meituan/www/waimai_mfe_merlin/app/service/waterMask.js, error: The module '/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/build/Release/canvas.node'

[egg-scripts] was compiled against a different Node.js version using

[egg-scripts] NODE_MODULE_VERSION 57. This version of Node.js requires

[egg-scripts] NODE_MODULE_VERSION 64. Please try re-compiling or re-installing

[egg-scripts] the module (for instance, using `npm rebuild` or `npm install`).

[egg-scripts] at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)

[egg-scripts] at Module.load (internal/modules/cjs/loader.js:653:32)

[egg-scripts] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

[egg-scripts] at Module.require (internal/modules/cjs/loader.js:692:17)

[egg-scripts] at require (internal/modules/cjs/helpers.js:25:18)

[egg-scripts] at Object. (/docker/opt/meituan/www/waimai_mfe_merlin/node_modules/canvas/lib/bindings.js:3:18)

[egg-scripts] at Module._compile (internal/modules/cjs/loader.js:778:30)

[egg-scripts] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

[egg-scripts] at Module.load (internal/modules/cjs/loader.js:653:32)

[egg-scripts]

**Comment by ThenMorning** [comment]
I fixed it by upgrading node version from 8 to 10

**Comment by hardikpatel043** [comment]
Same error coming with node 14.16.1

**Comment by obihill** [comment]
I had this issue after upgrading Node.js from 10 to 12. I had initially built `canvas` from source so I went through the following steps:

1. Remove/delete `node_modules` directory
2. Re-install: `npm install`
3. Rebuild canvas `npm rebuild --build-from-source canvas`

This fixed the issue.

**Comment by damiangreen** [comment]
@obihill's solution worked for me , except on step 2. i did `yarn` and step 3 wasnt required  (node 16.13.0)
