### ISSUE TITLE
contex.getTransform() is missing

### ISSUE THREAD

**Issue by Pomax** [Automattic/node-canvas#1642]
# Issue or Feature

It looks like the `getTransform` function is missing from the CanvasRenderingContext2d.

## Steps to Reproduce
```js
const canvas = CanvasBuilder.createCanvas(200, 200);
const ctx = canvas.getContext('2d');
console.log(ctx.beginPath);
console.log(ctx.moveTo);
console.log(ctx.arc);
console.log(ctx.getTransform);
console.log(ctx.setTransform);
```

results in:

```bash
[Function: beginPath]
[Function: moveTo]
[Function: arc]
undefined
[Function: setTransform]
```

## Your Environment
* Version of node-canvas: 2.6.1
* Environment: node 14.7 on Win10 x64

## Workaround

I tried shimming this using `ctx.getTransform = () => ctx.currentTransform;` which seems to work?

**Comment by Tirondzo** [comment]
@zbjornson, Looks like this issue can be closed now.
