### ISSUE TITLE
releasing a v2.7.1?

### ISSUE THREAD

**Issue by Pomax** [Automattic/node-canvas#1654]
The DOMMatrix and pango font fixes feel like they would make for a good `v2.7.1`. would it be possible to push out a new version to npm?

(It looks like 2.7.0 already exists, but never got pushed up to the npm registry... not sure if that was intentional, or whether an autopublish hook failed)

**Comment by zbjornson** [comment]
2.7.0 is in limbo (https://github.com/Automattic/node-canvas/issues/1622#issuecomment-667600108) -- I tagged the release in GitHub and tried to make prebuilds, but it's failing for one Node.js version on Linux and all versions on Windows. Once prebuilds are made it can get published to npm.

I might have time to keep troubleshooting it today, and I'll either delete the current 2.7.0 tag and recreate it at the current master commit (not sure if that will cause problems for anyone), or make 2.7.1 at the same time.
