### ISSUE TITLE
I got this error : Could not parse font file.

### ISSUE THREAD

**Issue by TheDaekLord1989** [Automattic/node-canvas#1657]
Hey guys, I am trying to make a message level system on discord, all other functions are great but only the rank command failed, I try to use canvas to send a picture that shows user's level but it just throws me an error: Could Not Parse Font File, how can I fix this error, please?
*I am using Canvas 2.6.1 on Windows 10 64bit.
*Sorry but my English is not good

Here is the file:
[LEVEL.zip](https://github.com/Automattic/node-canvas/files/5146246/LEVEL.zip)

**Comment by zbjornson** [comment]
Please see #1164.
