### ISSUE TITLE
Failed to install canvas, can't find the npm

### ISSUE THREAD

**Issue by Fomundi** [Automattic/node-canvas#1660]
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by zbjornson** [comment]
Closing because there's no info in the issue.
