### ISSUE TITLE
Gif support for windows

### ISSUE THREAD

**Issue by xMaxximum** [Automattic/node-canvas#1664]
## Issue or Feature

I can't find a guide how i can get gif support for Windows.
## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 12.18.2 on Windows 10

**Comment by zbjornson** [comment]
It's unfortunately not supported yet, see #1264.
