### ISSUE TITLE
Wiki can be edited by anyone

### ISSUE THREAD

**Issue by Pomax** [Automattic/node-canvas#1665]
@zbjornson Looking at https://github.com/Automattic/node-canvas/wiki/Installation---Windows/_history, it seems this repo has been compromised...  and some of the bad edits are from your account, suggestion _your account_ has been compromised, too O_o

**Comment by zbjornson** [comment]
For better or for worse, anyone can edit the wiki. (None of the current maintainers have access to the GitHub repo's settings to disable that.) That page keeps coming back to life, and we keep deleting it. 😓 Just deleted it again.

The correct Windows wiki page is https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows.

**Comment by Pomax** [comment]
That's... okay that's insane, surely Automattic has people are org-wide rights. Randomly pinging @tyxla: any way to fix this?

**Comment by zbjornson** [comment]
(Changed the title so it doesn't look so alarming :) )

**Comment by tyxla** [comment]
Thanks for the ping! I've restricted editing to users in teams with push access only. There aren't any other options - guess a good option to make this more flexible for any contributors is to move the wiki to the repo itself.
