### ISSUE TITLE
EXIF Orientation metadata option does not affect when drawing image on canvas.

### ISSUE THREAD

**Issue by cherevichka** [Automattic/node-canvas#1670]
If the JPEG image has orientation metadata, the `drawImage` method draws an unrotated image.

## Steps to Reproduce
1. Download JPG image with orientation metadata:
![red-line-rotated](https://user-images.githubusercontent.com/63286826/94535243-059ddf80-024a-11eb-93b5-1dd45ddaf362.jpg)

2. Load the image with `loadImage` utility.
3. Draw the image on canvas.

```js
const image = await loadImage("image_path");
const canvas = createCanvas(image.width, image.height);
const context = canvas.getContext("2d");

context.drawImage(image, 0, 0);

const result = canvas.toBuffer();

fs.writeFileSync("result_path", result);
```
Expected:
<img width="229" alt="github1" src="https://user-images.githubusercontent.com/63286826/94536142-169b2080-024b-11eb-9b83-88de7e603405.png">

Got:
<img width="431" alt="github2" src="https://user-images.githubusercontent.com/63286826/94536284-40544780-024b-11eb-88ed-578597158473.png">

Tested on MacOS, CentoOS.

Thanks!

**Comment by willemmulder** [comment]
@zbjornson Yes I'm having the same problem on Windows and Linux!

Did you find a workaround by any chance?

**Comment by willemmulder** [comment]
@cherevichka I'm now using the 'jpeg-autorotate' package to fix images before I use canvas.loadImage. It works, but it is not optimal :-)

**Comment by cherevichka** [comment]
@willemmulder I use the [exif-parser](https://www.npmjs.com/package/exif-parser) package to determine the orientation of the image, and then rotate the image when needed. 

> It works, but it is not optimal :-)

**Comment by Saberjsd** [comment]
@cherevichka Hello, would you tell me how to do in code to resolve this problem?

**Comment by nrkn** [comment]
@LinusU yes, it works as expected in browser

**Comment by kartikdutt18** [comment]
Hey, the change looks good, we would also like to have this change part of the new canvas version
