### ISSUE TITLE
TypeError: canvas.createSyncPNGStream is not a function

### ISSUE THREAD

**Issue by gregzanch** [Automattic/node-canvas#1672]
## Issue
`node benchmark/run.js` throws `TypeError: canvas.createSyncPNGStream is not a function`

## Steps to Reproduce
```sh
node benchmark/run.js
```

## Your Environment
* Version of node-canvas
`canvas@2.7.0`

* Environment
`node v13.11.0`
`macOS 10.15.6`

**Comment by 256SHA** [comment]
Things just was not honest about a lot of things not me

**Comment by 256SHA** [comment]
Things just was not honest about a lot of things not me
