### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Unsupported image type

### ISSUE THREAD

**Issue by asraful** [Automattic/node-canvas#1677]
I am trying to loadImage with png extension but ,  facing unsupported imageType .
But, the same piece of code is perfectly working for *.jpeg file type.

## Issue 

 (node:2536) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (********\node_modules\canvas\lib\image.js:91:13)
    at Image.set (********\node_modules\canvas\lib\image.js:62:9)
    at ********\landmark-detection\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (********\node_modules\canvas\index.js:23:10)
    at imageReconstruction (********\landmark-detection\app.js:159:22)
    at ********\app.js:102:36
(node:2536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js 
process with a non-zero exit code.

## Steps to Reproduce

const { createCanvas, loadImage } = require('canvas');
var image = await loadImage("png.png");

## Your Environment
Dependency : 
*canvas > version: 2.6.1
*node   > version: 12.12.62

**Comment by asraful** [comment]
fixed

**Comment by FHGDev** [comment]
can you let us know what you did to fix it?

**Comment by michalscislowski** [comment]
What was the issue?

**Comment by dericlima** [comment]
I'm facing a similar issue. @asraful Could you please tell us how did you fix it?

**Comment by sanidhya711** [comment]
How'd you fix it?? 😪

**Comment by laygir** [comment]
I arrived here suffering from similar situation, though didn't check if jpg was working.
nevertheless, in my case there was a `.DS_Store` file in my folder causing the issue.
`find . -name ".DS_Store" -delete` did the trick for me.

**Comment by asraful** [comment]
Image file was not right : https://stackoverflow.com/questions/64329955/nodejs-canvas-unhandledpromiserejectionwarning-error-unsupported-image-type
