### ISSUE TITLE
Cannot install canvas on Android using Termux, is there any other way

### ISSUE THREAD

**Issue by vegeta65** [Automattic/node-canvas#1687]
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by zbjornson** [comment]
There's no info in this issue, but see #1609.
