### ISSUE TITLE
Missed binaries for Node.js v15

### ISSUE THREAD

**Issue by Ky6uk** [Automattic/node-canvas#1688]
CI task has been failed because of missing binaries and building environment.

```
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz 
```

**Comment by zbjornson** [comment]
Prebuilds for v15 aren't available yet, but I made progress on them last weekend and can hopefully finish the remaining issues this weekend. Until then, you'll need to build from source: https://github.com/Automattic/node-canvas#compiling

**Comment by michaelzangl** [comment]
@zbjornson Can you pin this issue for anyone trying to update to Node 15?

**Comment by ridays2001** [comment]
@zbjornson 
Are there any approximate ETAs or something as to when the binaries will be done?

**Comment by zbjornson** [comment]
Node 15 prebuilds are now available!

**Comment by ridays2001** [comment]
The latest version has not been published to npm yet... Any estimations as to when it will be published?
It's only there on GitHub releases.

**Comment by Ky6uk** [comment]
@ridays2001 new package isn't required. The change here is just the previously missed file [canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz](https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz) now available.

**Comment by colin-reid** [comment]
Any chance of a Mac M1 prebuild? Falling back to build from source doesn't seem to work even after brew installing dependencies according to the docs.

**Comment by LinusU** [comment]
@colin-reid please open a dedicated issue for that, it would be awesome to have 👍
