### ISSUE TITLE
How can I parallelize canvas operations?

### ISSUE THREAD

**Issue by danielyaa5** [Automattic/node-canvas#1694]
Canvas operations can take well over a second when Im rendering images. How can I parallelize rendering multiple since its a synchronous operation?

**Comment by Flicksie** [comment]
`toBuffer()` is a CPU-bound operation so in the single-threaded context of node you probably can't without using something like child-process or workers (though node-canvas does not support workers)

my solution to that was either scrub milliseconds by not compressing the image when converting to buffer (down from 280ms to sub-100ms) in some cases, or off-loading the image generation to a separate sidecar app/API which handles the image processing in the first free thread, so you can make it async and not block the event loop in your original application. 

second is a bit more fiddly but is the most scalable.

**Comment by danielyaa5** [comment]
@Flicksie but shouldn't the c code be using separate threads? So I shouldn't need node workers right?

**Comment by Flicksie** [comment]
The underlying C native code indeed is capable of properly using threads, but remember that while you're converting to buffer you're streaming data from this native code to node.
I don't know for sure the specifics of the implementation in node-canvas itself but i believe it behaves just as if you were reading something with fs. this is technically i/o and that is a blocking operation. 

if you queue 100 toBuffer() operations that take 20ms each, they'll take 2 seconds regardless. even if you wrap them in a Promise.all(), the second one won't start before first one is completed. Canvas itself can probably handle multiple streams simultaneously, but node definitely doesn't.

**Comment by zbjornson** [comment]
@danielyaa5 are you using the callback-form of `toBuffer` (`canvas.toBuffer((err, buf) => { ... })`)? That runs in the thread pool, so can run up to ~`UV_THREADPOOL_SIZE` (the environment variable) operations in parallel.

Tuning the `compressionLevel` and `filters` can have a major impact on performance. You can try tuning those to your specific images.

**Comment by danielyaa5** [comment]
@zbjornson thanks! What is the default value for `UV_THREADPOOL_SIZE`? Ill take a look at my filters as well

**Comment by zbjornson** [comment]
@danielyaa5 it's 4, see https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_uv_threadpool_size_size.
