### ISSUE TITLE
I got this error : Could not parse font file.

### ISSUE THREAD

**Issue by Drelaky** [Automattic/node-canvas#1695]
I install the canvas. Version 2.6.1. There is a module called canvacord. Which is based on the canvas module. I asked them if they could help with this but unfortunately they were directed here I hope you can help. I use Windows 10 64Bit. 

my err: 
![image](https://user-images.githubusercontent.com/53569746/98256638-18a97b00-1f7f-11eb-9d23-c37ae79e9b53.png)

Canvas:
![image](https://user-images.githubusercontent.com/53569746/98256725-324ac280-1f7f-11eb-9295-0f96f7b726d9.png)

canvacord:
![image](https://user-images.githubusercontent.com/53569746/98256830-527a8180-1f7f-11eb-8415-697d035830f5.png)

What could be the problem? Unfortunately I don't understand the canvas module. Please help and educate because I want it to work.

**Comment by Drelaky** [comment]
I install the Manrope Font family

**Comment by Drelaky** [comment]
Can anyone help?

**Comment by Drelaky** [comment]
Video: https://www.youtube.com/watch?v=Qqrp0p_PGaE

**Comment by zbjornson** [comment]
Please see #1164.
