### ISSUE TITLE
Issue installing canvas with node-pre-gyp

### ISSUE THREAD

**Issue by dsbs10** [Automattic/node-canvas#1701]
npm ERR! code 1
npm ERR! path C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node-pre-gyp install --fallback-to-build"
npm ERR! Warning: Missing input files:
npm ERR! C:\GTK\bin\libintl-8.dll
npm ERR! C:\GTK\bin\libpangoft2-1.0-0.dll
npm ERR! C:\GTK\bin\libpangowin32-1.0-0.dll
npm ERR! C:\GTK\bin\libgmodule-2.0-0.dll
npm ERR! C:\GTK\bin\libfreetype-6.dll
npm ERR! C:\GTK\bin\libpangocairo-1.0-0.dll
npm ERR! C:\GTK\bin\zlib1.dll
npm ERR! C:\GTK\bin\libpango-1.0-0.dll
npm ERR! C:\GTK\bin\libgobject-2.0-0.dll
npm ERR! C:\GTK\bin\libcairo-2.dll
npm ERR! C:\GTK\bin\libfontconfig-1.dll
npm ERR! C:\GTK\bin\libexpat-1.dll
npm ERR! C:\GTK\bin\libpng14-14.dll
npm ERR! C:\GTK\bin\libgthread-2.0-0.dll
npm ERR! C:\GTK\bin\libglib-2.0-0.dll
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   Backend.cc
npm ERR! C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Nie mozna otworzyc pliku dolacz: 'cairo.h': No such file or directory [C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\build\canvas.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\CooLo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@15.1.0 | win32 | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@15.1.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.1.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.1.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.0 found at "C:\Python39\python.exe"
npm ERR! gyp info find VS using VS2019 (16.6.30309.148) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python39\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\CooLo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\CooLo\\Desktop\\Fvllen One\\node_modules\\canvas\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\CooLo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\CooLo\\AppData\\Local\\node-gyp\\Cache\\15.1.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\CooLo\\AppData\\Local\\node-gyp\\Cache\\15.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\CooLo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\CooLo\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.1.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\CooLo\\Desktop\\Fvllen One\\node_modules\\canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\CooLo\\Desktop\\Fvllen One\\node_modules\\canvas\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.1.0 | win32 | x64
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\CooLo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\CooLo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\CooLo\\Desktop\\Fvllen One\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\CooLo\\Desktop\\Fvllen One\\node_modules\\canvas\\build\\Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
npm ERR! gyp ERR! cwd C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas
npm ERR! gyp ERR! node -v v15.1.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\CooLo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1055:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19041
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\CooLo\\Desktop\\Fvllen One\\node_modules\\canvas\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\CooLo\Desktop\Fvllen One\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v15.1.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

**Comment by Icarus1337** [comment]
same error here i cant find a solution

**Comment by Metuuu** [comment]
Same here

**Comment by kryptorado** [comment]
same here

**Comment by MaximKing1** [comment]
same here, been trying to use this but always have this error?

**Comment by relative** [comment]
Follow the compiling instructions in the [README](https://github.com/Automattic/node-canvas#compiling), if you're on windows also look at [the wiki](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows)

**Comment by pubkey** [comment]
I got this problem when updating to node 15. Maybe a downgrade can help temporary.

**Comment by zbjornson** [comment]
Prebuilds for Windows (and MacOS) for Node.js v15 are available now. Sorry for the delay.
Linux users still need to build from source from now using the info in the readme that <span>@</span>relative linked to above, or use Node.js v14.

**Comment by ztolley** [comment]
Is there any way to load the binaries off a local mirror? I have an app on a private network and when I try to install it can't download the binary and it fails to compile a binary, with no clue as to why even though I've installed the required packages (Using Ubuntu)

**Comment by ShunnyBunny** [comment]
> Is there any way to load the binaries off a local mirror? I have an app on a private network and when I try to install it can't download the binary and it fails to compile a binary, with no clue as to why even though I've installed the required packages (Using Ubuntu)

@ztolley Did you end up figuring out if this is possible?

**Comment by ztolley** [comment]
No, I ended up writing my own mock. I'm running in a walled network on a restricted OS so I can't install the canvas dependencies.

**Comment by sztepen** [comment]
I am having the same issue on node v14.15.5; npm 7.5.4, win 10 intel core i9
earlier it worked

**Comment by infacto** [comment]
Sometime it works, sometimes not. Never installed GTK. (Windows 10, Node 14.16.0). Cleared cache. Why is this random?

**Comment by infacto** [comment]
Sometime it works, sometimes not. Never installed GTK. (Windows 10, Node 14.16.0). Cleared cache. Why is this random?

```text
canvas@2.7.0 install C:\project-path\node_modules\canvas
node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.7.0 and node@14.16.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error There was a fatal problem while downloading/extracting the tarball 
Warning: Missing input files:
C:\GTK\bin\libpangoft2-1.0-0.dll
etc.
```

**Comment by beforecode** [comment]
got the same problem here

**Comment by GustavoLent** [comment]
I had errors trying to run on Node version 18+
Downgraded to v14.20.0 with NVM and it ran successfully!

**Comment by manonon** [comment]
i downgraded node.js to 16.16.0 it work! finally....

**Comment by A7DC** [comment]
Downgrading to node 16 isn't a solution for me as Vercel stop supporting 16 in March 2024

**Comment by DanKaplanSES** [comment]
I'm not sure if this library is responsible, but why is it specifically looking for .dll's in `C:\GTK\bin\`? Shouldn't it be searching the `path` environment variable instead?
