### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by Unpurge** [Automattic/node-canvas#1706]
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by zbjornson** [comment]
Closing because there's no info in the description, but the error in the title means the build/install did not succeed. Please see the installation and compilation section of the readme;  https://github.com/Automattic/node-canvas#installation
