### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Ult1m1** [Automattic/node-canvas#1707]
Can you help me?

ERR:

(node:11284) UnhandledPromiseRejectionWarning: Error: Could not parse font file
    at Object.registerFont (E:\Soubory\Discord\BOT\Psychárna\PsychoVoidV4\node_modules\canvas\index.js:48:17)
    at Function.registerFonts (E:\Soubory\Discord\BOT\Psychárna\PsychoVoidV4\node_modules\canvacord\src\Canvacord.js:381:20)
(node:11284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm trying to load a font in canvas, but I can't
CODE: https://sourceb.in/i1640GMe7A

djs v12  -  "canvas": "^2.6.1",

**Comment by zbjornson** [comment]
Please see #1164.
