### ISSUE TITLE
Issues with generated image filesize in Azure

### ISSUE THREAD

**Issue by dupuis2387** [Automattic/node-canvas#1708]
So, I'm not sure if this is a library/code issue or an Azure issue, but my current scenario, is that with NodeJs, Restify and node-canvas, I have an endpoint that returns back a dynamically generated image, every time it's invoked. It's actually taking tabular data, from a db query, and drawing it as a table, onto a canvas object. 

What I've noticed, is that if the resulting image size is too large, it has weird loading problems. 

In Chrome, when the image was like 1.7MB, it loaded fine in the main window, but then in developer tools, looking at that image request, in the preview tab, it shows chrome's typical "broken image" image place holder.

Now, when the table data is smaller, and the generated output image is like 27KB, there's no problem.

I guess relevant code would be

```
const canvas = createCanvas(WIDTH, HEIGHT);
const ctx = canvas.getContext("2d");
//do some calls to ctx.drawText() and what have you....
const pngData = canvas.toBuffer('image/png', {compressionLevel: 0});
res.setHeader("Content-Type", "image/png");
res.sendRaw(pngData);

```
I tested by actually messing with the compressionLevel parameter, and when it got more compressed, and resulted in a smaller filesize, it worked 100% ok.

Also, I never see any sort of error anywhere, code wise nor inside Azure.

**Comment by zbjornson** [comment]
It's not clear to me that this is a node-canvas issue if the image loads fine in the document and only fails in the dev tools. Are you able to provide a reproduction script that uses only node-canvas?
