### ISSUE TITLE
Text Problem

### ISSUE THREAD

**Issue by RahulPlays** [Automattic/node-canvas#1712]
Text coming as undefined character (like box) even i tried copying ur example code

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by zbjornson** [comment]
Please provide the information requested in the issue template so that we can help. You might not have fonts installed or registered.
