### ISSUE TITLE
Error: Could not parse font file

### ISSUE THREAD

**Issue by croxywastaken** [Automattic/node-canvas#1713]
Hello. I'm gettin' every time 'Error: Could not parse font file' error. I've tried so much font (more than 10) and always it gave me this error.

version: 2.6.1
code:
```js
Canvas.registerFont("ttf/Bebas.ttf", {
        family: "Bebas",
        weight: "bold",
        style: "normal"
});```

**Comment by NANO-ck** [comment]
How did you fix it?
