### ISSUE TITLE
Squares instead of letters

### ISSUE THREAD

**Issue by CursedMun** [Automattic/node-canvas#1714]
For some reason, if I input a not normal letter it just transforms it into a square
## Issue or Feature

Image with node-canvas
![image](https://user-images.githubusercontent.com/46638125/100492236-49b24100-3122-11eb-9be5-1b90afc5664d.png)
Image on browser
![image](https://user-images.githubusercontent.com/46638125/100492335-e83ea200-3122-11eb-9b5f-45809e125390.png)

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
ctx.fillText("𝔖", 100,100)
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Debian 4.19.98-1):

**Comment by ms10398** [comment]
👍 @CursedMun having same issue did you find any fix?

**Comment by CursedMun** [comment]
> 👍 @CursedMun having the same issue did you find any fix?
> 
> Another thing which is happening is that it is happening on an ec2 machine but on my personal machine it seems to work

Yes, try installing this fonts [ImbPlex](https://github.com/IBM/plex) (didn't but it seems to work).
My way I found all the fonts I need here just by writing the text https://www.fontspace.com/category/symbols
