### ISSUE TITLE
ssr + dompurify  error

### ISSUE THREAD

**Issue by crazyair** [Automattic/node-canvas#1715]
https://github.com/jsdom/jsdom/issues/3042

**Comment by zbjornson** [comment]
Not sure what the error is, but looks like you might be trying to load node-canvas with webpack, whereas this module is for use server-side. Please post full info if you need assistance.

**Comment by crazyair** [comment]
install canval


 ERROR  Failed to compile with 1 errors                                                                                                                                              10:08:39 AM

 error  in ./node_modules/canvas/build/Release/canvas.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
demo:https://github.com/crazyair/umi-dompurify-demo

**Comment by ajay92x** [comment]
Hello @crazyair 
Have you find the solution for this issue.
