### ISSUE TITLE
Issue when trying to install canvas on termux

### ISSUE THREAD

**Issue by little-evil-thing** [Automattic/node-canvas#1717]
## Description of the issue
* so, hey everyone. I'm trying to install canvas on mobile, using termux for my discord bot. I do "npm install canvas" and everything run perfectly, untill the end where error message appears and stop the process... I've made search and it's seems that no one talk about it, and the only 2 post on GitHub about this error have no description. Anyway, I'm asking your help to understand what going wrong or what I do wrong :/ thanks in advance:

## Issue or Feature
 here some of error log:
* <npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user>:

* <errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink'>:

So, the file I'm actually trying to install the package on is located on /storage/emulated/0/*my file*
Of course, termux have the perm to write one my storage

## Your Environment
* Version of node - nodejs-lts 12.13.02:
* Environment - android 5.1.1, samsung. Non root device:

**Comment by agiltriono** [comment]
You cannot install package fron storage, because the permission limit is it because the natural linux environment limit on android doesn't support creating symbolic link
