### ISSUE TITLE
Color difference exists when the original image is exported directly after loading

### ISSUE THREAD

**Issue by madaOmada** [Automattic/node-canvas#1719]
As the title

## Issue or Feature

![copy222](https://user-images.githubusercontent.com/34056346/101451814-ba016380-3967-11eb-973a-668cce9aded0.jpg)
![clone](https://user-images.githubusercontent.com/34056346/101451828-be2d8100-3967-11eb-98d6-8a7903069551.jpg)

## Steps to Reproduce

```js
const config = require('./config.js')
const fs = require('fs')
const path = require('path')
const {
    createCanvas,
    Image
} = require('canvas');

const imgPath = path.join(config.TEMP_DIR, 'copy222.jpg');
const imgToPath = path.join(config.TEMP_DIR, 'clone.jpg');
const img = new Image()
img.onload = () => {
    const canvas = createCanvas(img.width, img.height);
    const ctx = canvas.getContext('2d')
    ctx.drawImage(img, 0, 0)
    canvas.createJPEGStream({
        quality: 1,
    }).pipe(fs.createWriteStream(imgToPath))
}
fs.readFile(imgPath, (err, buffer) => {
    img.src = buffer
})
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 8.10.0 on windows10

**Comment by zbjornson** [comment]
Can you read through #1621 (and #1651) please and see if that sounds like the same issue? Does your JPEG specify an ICC color space?

**Comment by zbjornson** [comment]
Assuming the above is correct (that this is a duplicate).
