### ISSUE TITLE
Can't  figure out invalid ELF headers error

### ISSUE THREAD

**Issue by linareyne** [Automattic/node-canvas#1720]
## Issue or Feature
Issue

## Steps to Reproduce
Canvas was installed as a dependency for the pdf-img-convert module, and is throwing an ELF header error that's preventing my docker container from spinning up. Here's a related issue I made in the pdf-img-convert repo https://github.com/olliet88/pdf-img-convert.js/issues/7

I've got `node_modules` in my .dockerignore and have tried things mentioned elsewhere like removing the contents of `node_modules` and reinstalling - no dice. I haven't ran into this issue with any other modules in this environment.

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 13.6 in a docker container

**Comment by zbjornson** [comment]
That most likely means that the MacOS or Win canvas build is being used on Linux. I don't have much experience with Docker to provide any guidance on how to fix it, but one way or another the `npm install` step needs to run on Linux so the correct build is downloaded.

**Comment by gagangoku** [comment]
In my case I had to add node_modules to the .dockerignore file
