### ISSUE TITLE
shadowColor drawn by browser is inconsistent with that drawn by server.

### ISSUE THREAD

**Issue by yangyuqing123** [Automattic/node-canvas#1730]
When shadow color and fillStyle are used at the same time, the color drawn by browser is inconsistent with that drawn by server.
``` javascript
ctx.fillStyle = "rgba(117,244,84,0.07)"
ctx.shadowColor = "rgba(189,24,24,0.96)";
ctx.shadowOffsetY = 10;
ctx.shadowOffsetX = 10;
ctx.fillRect(10, 10, 100, 100);
```

##  Environment
 "canvas": "^2.6.1",
  node v12.18.2 on Mac OS X 10.15.7

**Comment by LinusU** [comment]
Could you post a picture of what node-canvas does, and a picture of the browser?

**Comment by yangyuqing123** [comment]
> Could you post a picture of what node-canvas does, and a picture of the browser?

![](https://p3.koolearn.com/c357ecc0.png)
![](https://p3.koolearn.com/b42b6d71.png)

**Comment by yangyuqing123** [comment]
> Could you post a picture of what node-canvas does, and a picture of the browser?

[by browser](https://p3.koolearn.com/c357ecc0.png)
[by server](https://p3.koolearn.com/b42b6d71.png)

**Comment by WilliamEddy** [comment]
I have seen this issue as well, and it affects images with an alpha layer in a pretty nasty way. The browser appears to apply the opacity of the parent to the shadow resulting in a much more natural and softer shadow, while the server, node-canvas, does not take the parent opacity into consideration and only applies the desired `shadowColor`. When applied to an image with an alpha layer the browser will draw a shadow around the image content and ignore transparent areas, while node-canvas draws the shadow as a full rectangle with no consideration what areas have content and what areas do not.

I wish I had an answer to your issue, but the least I can do is add additional context in hopes that somebody else can pick this up and help find a resolution.
