### ISSUE TITLE
node-pre-gyp has been deprecated

### ISSUE THREAD

**Issue by yugangtan** [Automattic/node-canvas#1745]
This package depends on node-pre-gyp, but node-pre-gyp has been deprecated.
## Issue or Feature

Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):  
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by Sozialarchiv** [comment]
I can confirm this issue.
