### ISSUE TITLE
drawline bug report

### ISSUE THREAD

**Issue by nxg916** [Automattic/node-canvas#1746]
line1 context.setLineDash() make line2 (solid line) to dash
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(400, 400);
var context = canvas.getContext('2d');

// line1
context.beginPath();
context.setLineDash([ 2, 6 ]);
context.moveTo(0, 100);
context.lineTo(200, 100);
context.stroke();

// line2
context.beginPath();
context.moveTo(0, 200);
context.lineTo(200, 300);
context.strokeStyle = `black`;
context.stroke();
```

## Your Environment
* Version of node-canvas   "^2.6.1"
* node 14.5.1 on Mac OS X :

**Comment by TomFevrier** [comment]
This is not a bug, [this is how `context.setLineDash()` is supposed to work](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash).

You can either call `context.setLineDash([])` with an empty array to reset the dash, or wrap your code into `context.save()`and `context.restore()`instructions.
