### ISSUE TITLE
Issue with installation on CentOS 7

### ISSUE THREAD

**Issue by JeffreyArts** [Automattic/node-canvas#1753]
**I have followed the steps (aka, copy past a one-liner) for installing all of the required packages for CentOS. This got installed with success.**

```
sudo yum install gcc-c++ cairo-devel libjpeg-turbo-devel pango-devel giflib-devel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.nl.datapacket.com
 * epel: mirrors.ukfast.co.uk
 * extras: centos.mirror.transip.nl
 * remi-php73: mirrors.ukfast.co.uk
 * remi-safe: mirrors.ukfast.co.uk
 * updates: mirror.ams1.nl.leaseweb.net
Package gcc-c++-4.8.5-44.el7.x86_64 already installed and latest version
Package cairo-devel-1.15.12-4.el7.x86_64 already installed and latest version
Package libjpeg-turbo-devel-1.2.90-8.el7.x86_64 already installed and latest version
Package pango-devel-1.42.4-4.el7_7.x86_64 already installed and latest version
Package giflib-devel-4.1.6-9.el7.x86_64 already installed and latest version
```

**But when I am trying to run it, it throws me the following error:**

> internal/modules/cjs/loader.js:1122
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> 
> Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by (...)/node_modules/canvas/build/Release/canvas.node)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> ((...)/node_modules/canvas/lib/bindings.js:3:18)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> ((...)/node_modules/canvas/lib/canvas.js:9:18)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> ((...)/node_modules/canvas/index.js:1:16)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

## Environment details
back-end@0.0.1 
├── canvas@2.7.0
└─┬ svg2img@0.9.1
  └── canvas@2.7.0  deduped
NodeJS: v14.16.0
CentOS Linux release 7.7.1908 (Core)

What step would you suggest me to take a look at, in order to resolve this issue?

**Comment by JeffreyArts** [comment]
I have no idea what section actually resolved this problem. But it is fixed by resolving a version conflict of the repo I had.

**Comment by padys** [comment]
In my case (either CentOS 7) there is problem with too old version of `libstdc++` library:
```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/server/node_modules/canvas/build/Release/canvas.node)
```
There is no easy way to upgrade (`yum update` or something)...

I use https://github.com/SeanSobey/ChartjsNodeCanvas which depends on `canvas@^2.6.1`. I had to freeze that library in my private repository and force dependency to constant `canvas@2.6.1`. It is weak but works.

**Comment by stringang** [comment]
CXXABI_1.3.9 is associated with gcc version 5.1. CentOS 7 has gcc 4.8.5.

release: CentOS Linux release 7.8.2003 (Core)

```
$ strings /lib64/libstdc++.so.6 | grep CXXABI

CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
```

> In my case (either CentOS 7) there is problem with too old version of `libstdc++` library:
> 
> ```
> Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/server/node_modules/canvas/build/Release/canvas.node)
> ```
> 
> There is no easy way to upgrade (`yum update` or something)...
> 
> I use https://github.com/SeanSobey/ChartjsNodeCanvas which depends on `canvas@^2.6.1`. I had to freeze that library in my private repository and force dependency to constant `canvas@2.6.1`. It is weak but works.
