### ISSUE TITLE
Issue with node-canvas latest build ?

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [Automattic/node-canvas#1754]
During installation getting 404. Is there some issue with latest builds 2.7.0 ?

**Comment by Kingbultsea** [comment]
node-pre-gyp http 404 status code downloading tarball
https://cdn.npm.taobao.org/dist/node-canvas-prebuilt/v2.7.0/canvas-v2.7.0-node-v72-win32-unknown-x64.tar.gz

**Comment by Kingbultsea** [comment]
now it work... 
get 200

**Comment by zbjornson** [comment]
Please provide more info, including the info in the issue template, and check out the troubleshooting guide in #1511. https://github.com/Automattic/node-canvas/releases/tag/v2.7.0 has the list of all available 2.7.0 prebuilds.
