### ISSUE TITLE
Add Support gif format

### ISSUE THREAD

**Issue by Ult1m1** [Automattic/node-canvas#1755]
Hi, please add gif support.
 
(node:10692) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (E:\Soubory\Discord\BOT\Psychárna\PsychoVoidV4\node_modules\canvas\lib\image.js:91:13)
    at E:\Soubory\Discord\BOT\Psychárna\PsychoVoidV4\node_modules\canvas\lib\image.js:59:11
    at E:\Soubory\Discord\BOT\Psychárna\PsychoVoidV4\node_modules\simple-get\index.js:89:7
    at PassThrough.<anonymous> (E:\Soubory\Discord\BOT\Psychárna\PsychoVoidV4\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (events.js:291:20)
    at PassThrough.emit (events.js:203:13)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:10692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LinusU** [comment]
Make sure that you have the required libraries installed and you should get gif support:

https://github.com/Automattic/node-canvas#compiling

Happy to reopen if you have more troubles :relaxed:

**Comment by thepeanutgalleryandco** [comment]
@LinusU do you perhaps have a sample code snippet for me how I can take a GIF and PNG files (both having transparent backgrounds) and then adding them on top of one another to create a new GIF file? I have looked all over and I can't find quality examples anywhere.
