### ISSUE TITLE
ERROR in ./node_modules/canvas/build/Release/canvas.node 1:0 Module parse failed: Unexpected character '' (1:0)

### ISSUE THREAD

**Issue by raphael10-collab** [Automattic/node-canvas#1761]
In my Electron-React-Typescript-Webpack app I installed node-canvas and pdfs-dist : 

    sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev Reading package lists... 
    Done
    Building dependency tree       
    Reading state information... Done
    build-essential is already the newest version (12.4ubuntu1).
    libjpeg-dev is already the newest version (8c-2ubuntu8).
    libcairo2-dev is already the newest version (1.15.10-2ubuntu0.1).
    libgif-dev is already the newest version (5.1.4-2ubuntu0.1).
    libpango1.0-dev is already the newest version (1.40.14-1ubuntu0.1).
    librsvg2-dev is already the newest version (2.40.20-2ubuntu0.2).
    The following package was automatically installed and is no longer required:
      libpng12-0
    Use 'sudo apt autoremove' to remove it.
    0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

    (base) marco@pc01:~/webMatters/electronMatters/Raphy-Template$ yarn add canvas
    yarn add v1.22.5
    [1/4] Resolving packages...
    warning canvas > node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package 
    is deprecated and only the @mapbox scoped package will recieve updates in the future
    [2/4] Fetching packages...
    info fsevents@2.3.2: The platform "linux" is incompatible with this module.
    info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    info dmg-license@1.0.8: The platform "linux" is incompatible with this module.
    info "dmg-license@1.0.8" is an optional dependency and failed compatibility check. Excluding it from installation.
    info iconv-corefoundation@1.1.5: The platform "linux" is incompatible with this module.
    info "iconv-corefoundation@1.1.5" is an optional dependency and failed compatibility check. Excluding it from installation.
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 4 new dependencies.
    info Direct dependencies
    └─ canvas@2.7.0
    info All dependencies
    ├─ canvas@2.7.0
    ├─ node-pre-gyp@0.15.0
    ├─ simple-concat@1.0.1
    └─ simple-get@3.1.0
    $ yarn electron-rebuild
    yarn run v1.22.5
    $ /home/marco/webMatters/electronMatters/Raphy-Template/node_modules/.bin/electron-rebuild
    ⠇ Building module: canvas, Completed: 0gyp info find Python using Python version 3.7.4 found at "/home/marco/anaconda3
    /bin/python"
    ⠏ Building module: canvas, Completed: 0gyp info spawn /home/marco/anaconda3/bin/python
    gyp info spawn args [
    gyp info spawn args   '/home/marco/webMatters/electronMatters/Raphy-Template/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/marco/webMatters/electronMatters/Raphy-Template/node_modules/canvas/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/marco/webMatters/electronMatters/Raphy-Template/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/marco/.electron-gyp/12.0.0/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/marco/.electron-gyp/12.0.0',
    gyp info spawn args   '-Dnode_gyp_dir=/home/marco/webMatters/electronMatters/Raphy-Template/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/marco/.electron-gyp/12.0.0/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/home/marco/webMatters/electronMatters/Raphy-Template/node_modules/canvas',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    ⠹ Building module: canvas, Completed: 0gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    make: Entering directory '/home/marco/webMatters/electronMatters/Raphy-Template/node_modules/canvas/build'
      SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
      COPY Release/canvas-postbuild.node
      CXX(target) Release/obj.target/canvas/src/backend/Backend.o
    ⠴ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/backend/Backend.cc:1:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class    
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is    
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠏ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
    ⠹ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/backend/ImageBackend.h:3,
                     from ../src/backend/ImageBackend.cc:1:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class    
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is   
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠦ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o    
    ⠏ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/backend/PdfBackend.h:3,
                     from ../src/backend/PdfBackend.cc:1:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class   
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is  
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠸ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
    ⠧ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/backend/SvgBackend.h:3,
                     from ../src/backend/SvgBackend.cc:1:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class    
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is   
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠙ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o 
    ⠇ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/Backends.o
    ⠙ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/Backends.h:3,
                     from ../src/Backends.cc:1:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class   
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is    
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
     /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠼ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/Canvas.o
    ⠇ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/Canvas.h:5,
                     from ../src/Canvas.cc:3:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class    
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is 
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠴ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
    ⠇ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/CanvasGradient.h:5,
                     from ../src/CanvasGradient.cc:3:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class  
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is de
    precated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠸ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
    ⠦ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/CanvasPattern.h:6,
                     from ../src/CanvasPattern.cc:3:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class 
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is    
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
           |         ^~~~~~~~~~~~~~~
    ⠋ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o 
    ⠼ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/Canvas.h:5,
                     from ../src/CanvasRenderingContext2d.h:6,
                     from ../src/CanvasRenderingContext2d.cc:3:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class 
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is  
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠧ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/closure.o
    ⠋ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/Canvas.h:5,
                     from ../src/closure.h:5,
                     from ../src/closure.cc:1:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class   
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is  
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠼ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/color.o
    ⠙ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/Image.o
    ⠼ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/Image.h:8,
                     from ../src/Image.cc:3:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class    
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is 
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠼ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/ImageData.o
    ⠧ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/ImageData.h:5,
                     from ../src/ImageData.cc:3:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class 
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is  
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
     1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠹ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/init.o
    ⠴ Building module: canvas, Completed: 0In file included from /home/marco/.electron-gyp/12.0.0/include/node/node.h:67,
                     from ../../nan/nan.h:56,
                     from ../src/backend/Backend.h:6,
                     from ../src/Backends.h:3,
                     from ../src/init.cc:17:
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1650:79: warning: ‘using ResolveCallback = class    
    v8::MaybeLocal<v8::Module> (*)(class v8::Local<v8::Context>, class v8::Local<v8::String>, class v8::Local<v8::Module>)’ is 
    deprecated: Use ResolveModuleCallback [-Wdeprecated-declarations]
         1650 |                                                       ResolveCallback callback);
          |                                                                               ^
    /home/marco/.electron-gyp/12.0.0/include/node/v8.h:1632:9: note: declared here
     1632 |   using ResolveCallback V8_DEPRECATE_SOON("Use ResolveModuleCallback") =
          |         ^~~~~~~~~~~~~~~
    ⠇ Building module: canvas, Completed: 0  CXX(target) Release/obj.target/canvas/src/register_font.o
    ⠋ Building module: canvas, Completed: 0  SOLINK_MODULE(target) Release/obj.target/canvas.node
    ⠙ Building module: canvas, Completed: 0  COPY Release/canvas.node 
    make: Leaving directory '/home/marco/webMatters/electronMatters/Raphy-Template/node_modules/canvas/build'
    ✔ Rebuild Complete
    Done in 13.21s.
    Done in 24.35s.
    (base) marco@pc01:~/webMatters/electronMatters/Raphy-Template$ 

Once I put in main.ts : 

    let PDFJS = import('pdfjs-dist/build/pdf');

I get this error:

    yarn start
    yarn run v1.22.5
    $ yarn run build && electron ./dist/main/main.js
    $ npx webpack --config ./webpack.config.js
    asset main.js 8.23 MiB [emitted] (name: main)
    runtime modules 1.06 KiB 6 modules
    javascript modules 7.16 MiB
      modules by path ./node_modules/ 7.15 MiB 1255 modules
      modules by path ./src/main/ 9.64 KiB
        ./src/main/main.ts 7.15 KiB [built] [code generated]
        ./src/main/menu/menuTemplate_A.js 2.5 KiB [built] [code generated]
      28 modules
    json modules 394 KiB
      modules by path ./node_modules/har-schema/lib/*.json 6.93 KiB 18 modules
      modules by path ./node_modules/encoding/node_modules/iconv-lite/encodings/tables/*.json 86.7 KiB 8 modules
      modules by path ./node_modules/ajv/lib/refs/*.json 5.58 KiB
        ./node_modules/ajv/lib/refs/json-schema-draft-06.json 2.46 KiB [built] [code generated]
        ./node_modules/ajv/lib/refs/json-schema-draft-07.json 2.72 KiB [built] [code generated]
        ./node_modules/ajv/lib/refs/data.json 409 bytes [built] [code generated]
      8 modules

    ERROR in ./node_modules/canvas/build/Release/canvas.node 1:0
    Module parse failed: Unexpected character '' (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See     
    https://webpack.js.org/concepts#loaders
    (Source code omitted for this binary file)
     @ ./node_modules/canvas/lib/bindings.js 3:0-56
     @ ./node_modules/canvas/index.js 6:17-42
     @ ./node_modules/pdfjs-dist/build/pdf.js 4370:21-38
     @ ./src/main/main.ts 30:54-85

    webpack 5.24.3 compiled with 1 error in 9339 ms

    assets by path lib/pdfjs-dist/web/ 4.51 MiB 331 assets
    assets by path lib/pdfjs-dist/build/ 6.3 MiB
      assets by path lib/pdfjs-dist/build/*.map 4 MiB 3 assets
      assets by path lib/pdfjs-dist/build/*.js 2.3 MiB 3 assets
    assets by path *.js 2.17 MiB
      asset app_A.js 1.05 MiB [compared for emit] (name: app_A)
      asset app.js 1.03 MiB [compared for emit] (name: app)
      asset style_A.js 37 KiB [compared for emit] (name: style_A)
      asset style.js 37 KiB [compared for emit] (name: style)
      asset app_B.js 21.5 KiB [compared for emit] (name: app_B)
      assets by path *.html 1.4 KiB
      asset index_A.html 803 bytes [compared for emit]
      asset index.html 630 bytes [compared for emit]
     asset lib/pdfjs-dist/LICENSE 9.94 KiB [compared for emit] [from: src/lib/pdfjs-dist/LICENSE] [copied]
     runtime modules 3.66 KiB 16 modules
     cacheable modules 1.05 MiB
      modules by path ./node_modules/ 1000 KiB 8 modules
      modules by path ./src/ 68.6 KiB
        modules by path ./src/app_A/ 41.7 KiB 5 modules
        modules by path ./src/app/ 24.8 KiB 4 modules
        ./src/app_B/index_B.tsx 2.12 KiB [built] [code generated]
        external "path" 42 bytes [built] [code generated]
    external "events" 42 bytes [built] [code generated]
    external "child_process" 42 bytes [built] [code generated]
    external "os" 42 bytes [built] [code generated]
    external "fs" 42 bytes [built] [code generated]
    external "util" 42 bytes [built] [code generated]
    webpack 5.24.3 compiled successfully in 6761 ms
     error Command failed with exit code 1.

    devDependencies:
      "electron": "^12.0.0",
      "electron-rebuild": "^2.3.5",
      "webpack": "^5.23.0",
      "typescript": "^4.1.5",
      "react": "^17.0.1",

    dependencies:
       "canvas": "^2.7.0"

- node : v14.5.0
- O.S.: Ubuntu 18.04.4 Desktop

How to solve the problem?

**Comment by sujiewen** [comment]
I also encountered this problem, how to do it？
node v14.15.1 
element 11.3.0
