### ISSUE TITLE
Feature Request: deregisterAllFonts

### ISSUE THREAD

**Issue by jhuckaby** [Automattic/node-canvas#1762]
Hello @chearon, and congratulations on the node-canvas 2.7.0 release!  I really appreciate your work on this important project.  I am still having issues loading certain fonts, even on the latest version (see #1362).

I don't want to re-open that old issue, but I am rather writing to ask about the `deregisterAllFonts()` method that we talked about back in 2019:

> > I'm really starting to think we should just implement that deregisterAllFonts function, and I just call it between every single use. What do you think?

> I can open a PR for that soon, it should be easy

Would it be possible to get this back on the TODO list?  I am just about dying for it now.  Currently I'm forking 32 parallel child processes, all loading separate isolated node-canvases, and then I am assigning children tasks based on the font path.  It's a mess, requires tons of memory, and it barely works (and I'm still hitting edge cases where it doesn't).  What I *really* need is a way to unload fonts.

Do you still think adding `deregisterAllFonts` would be relatively easy?

**Comment by chearon** [comment]
Yes, very easy, it just has to call `FcConfigAppFontClear`.

I think the problem you had in #1362 will be fixed by the new Pango API that got merged recently. I already have most of the work on that done, but a lot of things were waiting on prebuilds which we just finished. Stay tuned...

**Comment by jhuckaby** [comment]
I apologize for nagging, @chearon, but I haven't seen any activity on this for a month or so.  If the new Pango API isn't coming in soon, would it be possible to just toss in a simple API that calls `FcConfigAppFontClear`?

Being an open source developer myself, I hate it when people "ping" me on open issues to see if they will be solved soon.  So I feel terrible doing this, but since you said this would be very easy, I figured I would ask.

I will not nag you again on this 😊
