### ISSUE TITLE
librsvg-2.so.2 Increased File Size

### ISSUE THREAD

**Issue by JeffersonSchuler** [Automattic/node-canvas#1765]
I currently use Canvas in a AWS Lambda environment where executable size is limited.  I noticed with v2.7.0 the file size of librsvg-2.so.2 is now at 102.5 MB.  In Canvas v2.6.1 the file size is 47.1 MB.  

Was this build done without stripping off symbols or some other unneeded data?  

I believe we may have run into this issue a year ago as well.

Thank you.

**Comment by chearon** [comment]
[COMPILING.md](https://github.com/GNOME/librsvg/blob/master/COMPILING.md#debug-or-release-builds) makes it sound like debug build should be off by default as you would expect. Rust binaries always seem to be big. If you or anyone reading this figures out a way to make it smaller, I'll update the docker image. I couldn't find any obvious answers after a quick look.

**Comment by JeffersonSchuler** [comment]
I was able to do the deploy with the current size of the file.
