### ISSUE TITLE
Canvas doesn't work with certain hosting services.

### ISSUE THREAD

**Issue by TRNST-Dev** [Automattic/node-canvas#1766]
## Issue or Feature
Canvas doesn't seem to work using FalixNodes [https://falixnodes.net]

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by zbjornson** [comment]
I'm not at all familiar with FalixNodes. Most likely they don't support native Node.js addons. I'd try contacting their support with the error message you're encountering.
