### ISSUE TITLE
added a loadFromDataBuffer method to Image

### ISSUE THREAD

**Issue by victusfate** [Automattic/node-canvas#177]
Heyo TJ, in my fork I added another load method because for the life of me I couldn't figure out how to create an Image from a raw buffer with the existing source (width*height*4 bytes of rgb data goodness).

Here's the code, if you have a chance please let me know if it's not kosher

```c
cairo_status_t
Image::loadFromDataBuffer(unsigned char *buf, int width, int height) {
  clearData();
  int stride = cairo_format_stride_for_width (CAIRO_FORMAT_ARGB32, width); // 4*width + ?
  _surface = cairo_image_surface_create_for_data(buf,CAIRO_FORMAT_ARGB32,width,height,stride);
  loaded();
  return cairo_surface_status(_surface);
}
```

https://github.com/victusfate/node-canvas/commit/817a750cc571f9edf43a4b3e6a90c0e26586a8ef

**Comment by LinusU** [comment]
Please place a comment if this is still relevant and I'll reopen, I believe that we have made quite a few changes to the relevant parts of the code though...
