### ISSUE TITLE
I dont know what to call this but this is my error

### ISSUE THREAD

**Issue by lordfrijoles** [Automattic/node-canvas#1775]
Referenced from: /Users/lucaqueiroz/Desktop/Astaa/node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/lucaqueiroz/Desktop/Astaa/node_modules/canvas/build/Release/libpixman-1.0.40.0.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by zbjornson** [comment]
Please see #1626 - there's an explanation and workaround in the second comment.
