### ISSUE TITLE
canvas.createPDFStream() makes a 3300 x 2550 pdf canvas into a 13750 x 10625 pdf. 

### ISSUE THREAD

**Issue by hmahmoud3** [Automattic/node-canvas#1777]
## Issue or Feature
I am drawing an image of  3300 x 2550 onto a canvas of 3300 x 2550  (8.5" x 11" Letter) with type pdf, drawing on it, then sending it using `canvas.createPDFStream().pipe(res)`. The final image has a resolution of 13750 x 10625, or 45" x 35". 

## Steps to Reproduce

```js
const { createCanvas, loadImage } = require('canvas');
const canv = createCanvas(3300, 2550, 'pdf');
const ctx = canv.getContext('2d');
let img = await loadImage(layoutImgUrl); 
img.src = layoutImgUrl; // image is a 3300 x 2550 px png 

const drawImage = async () => {
    // do stuff like ctx.fillText;
   return { data : img }
}

await drawImage;

const stream = canv.createPDFStream().pipe(res);
return await new Promise((resolve, reject) => {
stream.on('finish', resolve);
stream.on('error', reject);
    });
```

## My Environment
* Version of node-canvas): canvas@2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 12 on node express server on firebase cloud functions

**Comment by Saberjsd** [comment]
Any update on this issue?

**Comment by zbjornson** [comment]
The PDF format uses points, and there are 72 points per inch, so 3300 / 72 = 45.83 inches. To make an 8.5x11 PDF, you need to use `createCanvas(8.5*72, 11*72)`.

**Comment by Saberjsd** [comment]
But the 3300 x 2550 px png image on this PDF size maybe not clear？
How to resolve this problem?
