### ISSUE TITLE
(node:13925) UnhandledPromiseRejectionWarning: Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by sallamadim** [Automattic/node-canvas#1778]
When I want to use canvas it gives me that error;
![fjnv](https://user-images.githubusercontent.com/70215242/113402326-82eb0e00-93ad-11eb-9f8d-c61487a33a02.png)

**Comment by zbjornson** [comment]
Please see the installation troubleshooting guide here: https://github.com/Automattic/node-canvas/issues/1511. If you're still having troubles after that, please provide the info requested in the issue template.
