### ISSUE TITLE
Does canvas support opacity?

### ISSUE THREAD

**Issue by 3061LRTAGSPKJMORMRT** [Automattic/node-canvas#1786]
Hi, i read the documentation and can't seem to find to adjust the opacity. Is it even possible? If yes, do reply

**Comment by zbjornson** [comment]
Yes, the standard Canvas APIs that take transparency values work in node-canvas:
- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalAlpha
- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle
- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeStyle
