### ISSUE TITLE
Add prebuilt binaries for Apple silicon

### ISSUE THREAD

**Issue by davidanthoff** [Automattic/node-canvas#1794]
I think with the rapid adoption of Apple silicon in Macs this would be really great. Node 16 has added support for Apple Silicon as well, so I think that end of the story should be ready.

**Comment by chearon** [comment]
Prebuilds are working for macOS/Arm since #2354 was merged!

`npm install canvas@next` to get 3.0.0-rc3. I'm going to wait a few days before releasing 3.0.
