### ISSUE TITLE
Canvas adds a space after a single parentheses when using Noto Sans SC font.

### ISSUE THREAD

**Issue by ZEUSGMJ** [Automattic/node-canvas#1795]
## Issue

When using `Noto Sans SC` font, a weird space is added next to `'`. Sometimes it works properly and other times, A space is inserted next to it.
## Steps to Reproduce

```js
const { createCanvas, loadImage, registerFont } = require('canvas');

registerFont('./assets/font/NotoSansSC-Regular.otf', {
	family: 'Noto'
});
// From line 182 of my code.

while (ctx.measureText(trackName.trim()).width > 115)
	trackName = `${trackName.slice(0, -4)}...`;
while (ctx.measureText(`${Artist.trim()}`).width > 160)
	Artist = `${Artist.slice(0, -4)}...`;
while (ctx.measureText(`${albumName.trim()}`).width > 160)
	albumName = `${albumName.slice(0, -4)}...`;
while (ctx.measureText(`• ${username.trim()}`).width > 130)
	username = `${username.slice(0, -4)}...`;

ctx.fillStyle = textColor;
ctx.font = '600 76px Noto Sans SC';
ctx.fillText(`${trackName}`, 45, 165);

ctx.font = '56px Noto Sans SC';
ctx.fillText(`${Artist}`, 45, 230);

ctx.font = '600 56px Noto Sans SC';
ctx.fillText(`${albumName}`, 45, 295);

ctx.font = '600 42px Noto Sans SC';
ctx.fillText(`• ${targetMember.user.username.trim()}`, 100, 75);
```

## Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): **`canvas@2.7.0`**
* Node: **`v15.6.0`**
* OS: **`Windows 10 x64`**
## Attachment
![Spotify](https://user-images.githubusercontent.com/42777277/116907847-c4e2ca80-ac5f-11eb-810e-251efe4b7384.png)

**Comment by zbjornson** [comment]
Can you provide an example of the strings (`trackName`, `Artist`, `albumName`, `username`) to reproduce the issue please?

**Comment by ZEUSGMJ** [comment]
> Can you provide an example of the strings (`trackName`, `Artist`, `albumName`, `username`) to reproduce the issue please?

Yes.

#### Before slicing
- `trackName`: Alfred’s Theme
- `Artist`: Eminem
- `albumName`: Music To Be Murdered By - Side B (Deluxe Edition)
- `username`: ZEUSGMJ
---
#### After slicing
- `trackName`: Alfred’s Theme
- `Artist`: Eminem
- `albumName`: Music To Be Murdered By - Side ...
- `username`: ZEUSGMJ

**Comment by charoitel** [comment]
@ZEUSGMJ , it looks is due to different characters are used in the track names.

For `Alfred’s Theme`, used `’`, ASCII output: 226 128 153

For `I Don't Wanna Dance`, used `'`, ASCII output: 039

Please note I just copied the characters from your examples, didn't typed it. Hope this may help.

**Comment by ZEUSGMJ** [comment]
> @ZEUSGMJ , it looks is due to different characters are used in the track names.
> 
> For `Alfred’s Theme`, used `’`, ASCII output: 226 128 153
> 
> For `I Don't Wanna Dance`, used `'`, ASCII output: 039
> 
> Please note I just copied the characters from your examples, didn't typed it. Hope this may help.
> 

Ah, Well I've changed the font and now use `Arial Unicode MS`. No issues with it till now.
Thanks for the help😁
