### ISSUE TITLE
The source code of the 2.7.0 npm package does not contain the changes in the repository.

### ISSUE THREAD

**Issue by bigbigDreamer** [Automattic/node-canvas#1798]
## Issue or Feature

The source code of the 2.7.0 npm package does not contain the changes in the repository.

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/39019913/117769122-da5e8280-b265-11eb-9dc4-b4fa43f6f4bc.png)
![image](https://user-images.githubusercontent.com/39019913/117769193-f530f700-b265-11eb-80ad-6aa5189e2981.png)

## Your Environment
* Version of node-canvas: 2.7.0
* Environment : node 15.4.0 on Mac OS Big Sur 13.3

**Comment by LinusU** [comment]
You are comparing with `master` and not `v2.7.0`, there has simply been some commits to master since we cut the 2.7.0 release...

https://github.com/Automattic/node-canvas/blob/v2.7.0/package.json
