### ISSUE TITLE
Getting an error "TypeError: ImageData expected" when trying to use putImageData

### ISSUE THREAD

**Issue by ua834** [Automattic/node-canvas#1799]
Trying to use putImageData with a png file, but getting the error "TypeError: ImageData expected" 
## Issue or Feature

Using node 12.18.1 and Ubuntu 20.04

## Steps to Reproduce
```js
const { get, getSync } = require('@andreekeberg/imagedata')
const { createCanvas, loadImage } = require('canvas')
const PNG = require('pngjs').PNG;
const fs = require('fs');

const img1 = PNG.sync.read(fs.readFileSync("./f1.png"));
const img3 = getSync("./f1.png")
c1 = createCanvas(img1.width, img1.height);
context1 = c1.getContext("2d");
try{
	context1.putImageData(img1, 0, 0);
}catch(err1){
	console.log("err1: ",err1);
}
try{
	context1.putImageData(img3, 0, 0);
}catch(err2){
	console.log("err2: ",err2);
}
try{
	context1.putImageData(img1.data, 0, 0);
}catch(err3){
	console.log("err1: ",err3);
}
try{
	context1.putImageData(img3.data, 0, 0);
}catch(err4){
	console.log("err2: ",err4);
}

```

## Your Environment
* Version of node-canvas 2.7.0:
* Environment node 12.18.1 on Ubuntu20.04

Image to use in script:

![f1](https://user-images.githubusercontent.com/81559621/117817951-f7bb2e80-b21c-11eb-828d-896b2272b2d9.png)

**Comment by LinusU** [comment]
Instead of using `PNG.sync.read` or `getSync`, could you use the builtin `loadImage` method from `canvas`?

**Comment by LinusU** [comment]
@willlahr this only happens when you are trying to use something other than the `ImageData` from node-canvas. Be sure to use `const { ImageData } = require('canvas')` to import ImageData.
