### ISSUE TITLE
v2.8.0

### ISSUE THREAD

**Issue by zbjornson** [Automattic/node-canvas#1803]
v2.8.0 is ready to publish to npm @LinusU !

This is the first time that prebuilds run with GitHub Actions have Just Worked. 🎉

**Comment by LinusU** [comment]
My first transfer was (possibly?) interrupted and now I get this error from npm:

> npm ERR! code E403
> npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/canvas - You cannot publish over the previously published versions: 2.8.0.

But the site shows 2.7.0 as the latest:

https://www.npmjs.com/package/canvas

Will test again later today to see if the situation has changed...

**Comment by LinusU** [comment]
It's live now! 🚀
