### ISSUE TITLE
Auttomatic canvas 404 error

### ISSUE THREAD

**Issue by akhil-quarantine** [Automattic/node-canvas#1804]
<img width="1279" alt="Screen Shot 2021-05-17 at 11 51 12 AM" src="https://user-images.githubusercontent.com/44531958/118543956-d4571e80-b709-11eb-9e5b-496957787d2f.png">

I notice this 404 error starting today and it seems there was a release done yesterday?

**Comment by lgc** [comment]
![image](https://user-images.githubusercontent.com/18029469/118589152-69254f00-b7d2-11eb-81e7-a0a4dccff12a.png)

same error

**Comment by pnutmath** [comment]
Same error here too

**Comment by vishu3011** [comment]
'node-pre-gyp WARN Tried to download(404): https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v72-linux-musl-x64.tar.gz \n'

getting this error
having node version 12.19.1

**Comment by pnutmath** [comment]
Same issue with me menthined by @vishu3011

**Comment by chen2009277025** [comment]
same issue, how to fix it??

**Comment by vproce** [comment]
node-pre-gyp http GET https://npm.alibaba-inc.com/mirrors/node-canvas-prebuilt/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-x64.tar.gz

tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: gzip decompression failed
tar: Error exit delayed from previous errors.

node-pre-gyp ERR! install zlib: invalid code lengths set


Unable to install after yesterday's update

**Comment by lgc** [comment]
> same issue, how to fix it??

Temporary modification

"dependencies": {
    "canvas": "2.7.0"
}

**Comment by vishu3011** [comment]
The issue can be solved by upgrading the node version to 14.16.1

**Comment by Kertic** [comment]
Also having the same issue. Working around it with changing the dependency as "^2.7.0" and forcing it to "2.7.0" is getting further. As per @lgc 's suggestion.

**Comment by PrasathHari** [comment]
Getting the same issue. Forcing npm to install "2.7.0" instead of "^2.7.0" worked for me as per @lgc 's suggestion. Is upgrading node to 14.16.1 necessary or is it a bug from the plugin which will be fixed?

**Comment by zbjornson** [comment]
Node.js v10 is end of life, so I didn't make prebuilds for it.

@vishu3011 your issue is different, see the section in https://github.com/Automattic/node-canvas/issues/1511 about musl.

**Comment by zbjornson** [comment]
I just made prebuilds for older versions of Node. (Note however that odd-numbered releases and <12 are not supported by Node.js anymore, https://nodejs.org/en/about/releases/.)
