### ISSUE TITLE
Getting Invalid path for zip while Installing canvas package

### ISSUE THREAD

**Issue by amitsaxen** [Automattic/node-canvas#1806]
I am trying to install canvas using jenkins which executes command
canvas@2.8.0 install /var/www/myapp/node_modules/canvas

I gives me an error saying:

[91mnode-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v64-linux-glibc-x64.tar.gz 
[0m[91mnode-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v64-linux-glibc-x64.tar.gz 

Actually the installation path is not valid anymore.

**Comment by apank** [comment]
Was able to fix the issue temporally by the following updates to my package.json

"dependencies": {
    "canvas": "2.7.0",
}

"resolutions": {
    "chartjs-node-canvas/canvas": "2.7.0",
    "canvas": "2.7.0"
  }

**Comment by zbjornson** [comment]
You're using Node.js v10, which I didn't make prebuilds for because it is end of life. Are you able to upgrade?

**Comment by apank** [comment]
I was getting the error for - node@13.14.0

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v79-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@13.14.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v79-linux-glibc-x64.tar.gz

**Comment by zbjornson** [comment]
I only made prebuilds for versions of Node.js that are currently supported (https://nodejs.org/en/about/releases/): 12, 14, 15, 16. Are you able to use a supported version?

**Comment by thomasaustin** [comment]
I'm also getting this error with Node 14.17.0

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-darwin-unknown-arm64.tar.gz

**Comment by amitsaxen** [comment]
> I only made prebuilds for versions of Node.js that are currently supported (https://nodejs.org/en/about/releases/): 12, 14, 15, 16. Are you able to use a supported version?

It was working fine with same version 2 days back...Suddenly it started failing.. Any specific reason for this?? Because nothing has been from our side in that duration

**Comment by amitsaxen** [comment]
> > I only made prebuilds for versions of Node.js that are currently supported (https://nodejs.org/en/about/releases/): 12, 14, 15, 16. Are you able to use a supported version?
> 
> It was working fine with same version 2 days back...Suddenly it started failing.. Any specific reason for this?? Because nothing has been from our side in that duration

Can we have a fix for this as it is causing trouble to most of the users?

**Comment by zbjornson** [comment]
A new release was published two days ago, so if you're just installing canvas without specifying a version, you're picking up the new release. You can install 2.7.0 or use a supported version of node.

@thomasaustin your issue is different, we've never had arm prebuilds (see #1511).

**Comment by zbjornson** [comment]
I just made prebuilds for more versions of node (8 through 16).
