### ISSUE TITLE
Ability to preload images

### ISSUE THREAD

**Issue by Chromus-dev** [Automattic/node-canvas#1813]
I made a packages that replaces the pixels of images but I have to load the image for each pixel. Is there any way I can load all the images before I go through all the pixels?

You can find the package [here](https://github.com/chromus-dev/blockify)

**Comment by zbjornson** [comment]
This doesn't look like a node-canvas question, but more of an HTML question that would be better asked on StackOverflow. If it's specific to node-canvas, please clarify the question.
