### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by xuaugameplays** [Automattic/node-canvas#1825]
I was trying to install the node canvas and happened a error

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm.tar.gz

Help me pls

**Comment by zbjornson** [comment]
Please see #1511: prebuilds aren't available for ARM CPUs, so you need to build from source (https://github.com/Automattic/node-canvas/wiki#installation-guides).

**Comment by josephEncheckal** [comment]
> Please see #1511: prebuilds aren't available for ARM CPUs, so you need to build from source (https://github.com/Automattic/node-canvas/wiki#installation-guides).

worked in ubuntu (AWS ec2)

**Comment by hasan-retrace** [comment]
Thanks @josephEncheckal , that worked.

**Comment by omergulen** [comment]
> Please see #1511: prebuilds aren't available for ARM CPUs, so you need to build from source (https://github.com/Automattic/node-canvas/wiki#installation-guides).

Using Apple M1 here, installing the dependencies with `brew` from the link you've given solved the issue I was getting on `npm install` on another project.

 Thanks! 🎉

**Comment by davidecarpini** [comment]
> > Please see #1511: prebuilds aren't available for ARM CPUs, so you need to build from source (https://github.com/Automattic/node-canvas/wiki#installation-guides).
> 
> Using Apple M1 here, installing the dependencies with `brew` from the link you've given solved the issue I was getting on `npm install` on another project.
> 
> Thanks! 🎉

```
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```

fixed it

**Comment by pnutmath** [comment]
How this work with alpine images? getting similar issue while using pdfjs-dist:  

`Cannot find module 'canvas'\nRequire stack:\n- /srv/node_modules/pdfjs-dist/legacy/build/pdf.js`

**Comment by wisetc** [comment]
```
^CWarning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
Warning: cairo 1.16.0_5 is already installed and up-to-date.
To reinstall 1.16.0_5, run:
  brew reinstall cairo
Warning: libpng 1.6.39 is already installed and up-to-date.
To reinstall 1.6.39, run:
  brew reinstall libpng
Warning: giflib 5.2.1 is already installed and up-to-date.
To reinstall 5.2.1, run:
  brew reinstall giflib
```

M2 apple silicon

**Comment by katerlloyd** [comment]
Running `brew install pkg-config cairo pango libpng jpeg giflib librsvg` fixed it on my M2 Apple Silicon.

**Comment by yanxiangzhou** [comment]
Using Apple M2 here, installing the dependencies with brew as the following, from the link you've given solved the issue for me, which I was getting on npm install on another project.

`arch -arm64 brew install pkg-config cairo pango libpng jpeg giflib librsvg`

**Comment by mycharoka** [comment]
> I was trying to install the node canvas and happened a error
> 
> node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-android-unknown-arm.tar.gz
> 
> Help me pls

I think I just find a way out of it, so I notice my log said
npm ERR!   File "/Users/muhammadvidi/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/muhammadvidi/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/muhammadvidi/.nvm/versions/node/v18.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'

and so I tried to change my node version into v16.20.2 (i'm using nvm btw) and I change my python version that's being use globally. So on my mac I have python v3.12.2 installed from brew and then I installed `pyenv` and I installed `pyenv install 3.10.4` (or maybe tried to install any 3.10 version maybe) and I hit `npm i` and voila it runs perfectly.
the idea to using python v3.10 is from this stackoverflow article [solution](https://stackoverflow.com/questions/70098133/npm-error-cant-find-python-executable-in-macos-big-sur)

goodluck guys!

**Comment by MeirP-3** [comment]
MacOS Sonoma 14.5 failed `npm install canvas`.

After digging in the error log, root cause were errors similar to `error <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.`.

Solution was:
```bash
export SDKROOT=$(xcrun --show-sdk-path)
npm install canvas
```

**Comment by weiyang001** [comment]
If the above methods don't work on Mac OS, try restarting your computer. This solved my problem, thanks very much! 🙏
