### ISSUE TITLE
Nothing happens on windows

### ISSUE THREAD

**Issue by ErAz7** [Automattic/node-canvas#1827]
Hi

just wanted to try this on windows. so I did all steps to install on windows, installed canvas successfully but when I run this:

```js
const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext('2d')

// Write "Awesome!"
ctx.font = '30px Impact'
ctx.rotate(0.1)
ctx.fillText('Awesome!', 50, 100)

// Draw line under text
var text = ctx.measureText('Awesome!')
ctx.strokeStyle = 'rgba(0,0,0,0.5)'
ctx.beginPath()
ctx.lineTo(50, 102)
ctx.lineTo(50 + text.width, 102)
ctx.stroke()
```

nothing happens and node process ends :

![2021-06-10_2-04-43](https://user-images.githubusercontent.com/46329768/121432757-51d02080-c990-11eb-8176-8f973a96501c.gif)

## Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.8.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):  node 14.16.1 on Windows 10

**Comment by zbjornson** [comment]
That's likely working as expected. To see the canvas, you need to use one of the output APIs like [`toBuffer()`](https://github.com/Automattic/node-canvas#canvastobuffer).
