### ISSUE TITLE
Big error

### ISSUE THREAD

**Issue by kajg2008NL** [Automattic/node-canvas#1830]
Hello i have tried everything but nothing works for me.

Node version: 14.17.1 LTS

Things i did.

https://www.youtube.com/watch?v=SletQOmrhcM
deleted package-lock.json and node modules and reinstall
And sooooo much other tuturials.

this is my error. And yes i also tried it with yarn.

> canvas@2.8.0 install C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-win32-unknown-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-win32-unknown-ia32.tar.gz 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Backend.cc
  ImageBackend.cc
  PdfBackend.cc
  SvgBackend.cc
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
c:\users\kaj\desktop\bots\suppamc\node_modules\canvas\src\bmp\bmpparser.cc(186): warning C4018: '>': signed/unsigned mismatch [C:\Users\Kaj\Desktop\bots\Supp
aMC\node_modules\canvas\build\canvas.vcxproj]
c:\users\kaj\desktop\bots\suppamc\node_modules\canvas\src\bmp\bmpparser.cc(201): warning C4018: '>': signed/unsigned mismatch [C:\Users\Kaj\Desktop\bots\Supp
aMC\node_modules\canvas\build\canvas.vcxproj]
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  closure.cc
  color.cc
  Image.cc
c:\users\kaj\desktop\bots\suppamc\node_modules\canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compiling source file ..\src\CanvasRe
nderingContext2d.cc) [C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\build\canvas.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\map(20): note: see declaration of 'std' (compiling source  
  file ..\src\CanvasRenderingContext2d.cc)
  ImageData.cc
  init.cc
  register_font.cc
c:\users\kaj\desktop\bots\suppamc\node_modules\canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compiling source file ..\src\Image.cc
) [C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\build\canvas.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\queue(451): note: see declaration of 'std' (compiling sour 
  ce file ..\src\Image.cc)
  win_delay_load_hook.cc
c:\users\kaj\desktop\bots\suppamc\node_modules\canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compiling source file ..\src\ImageDat
a.cc) [C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\build\canvas.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\queue(451): note: see declaration of 'std' (compiling sour
  ce file ..\src\ImageData.cc)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Kaj\\Desktop\\bots\\SuppaMC\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Kaj\\Desktop\\bots\\SuppaMC\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Kaj\\Desktop\\bots\\SuppaMC\\node_modules\\canvas\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas
node-pre-gyp ERR! node -v v14.17.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Kaj\Desktop\bots\SuppaMC\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN discord.js@11.6.4 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN suppamc@1.0.0 No description
npm WARN suppamc@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kaj\AppData\Roaming\npm-cache\_logs\2021-06-17T19_01_35_153Z-debug.log`

**Comment by abdulahkam** [comment]
> 

> c:\users\kaj\desktop\bots\suppamc\node_modules\canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compiling source file ..\src\CanvasRe

For me, that is the error that make me failed to install node-canvas. What I do is change the  
> node_modules\canvas\src\util.h

based on this pull request #1394

**Comment by zbjornson** [comment]
Node-canvas doesn't readily support 32-bit Node.js. See #1511 for more info.
