### ISSUE TITLE
node.js Canvas.toBuffer return undefined with image/jpeg

### ISSUE THREAD

**Issue by mike667** [Automattic/node-canvas#1833]
Hello. I used macos 11.4 (apple m1), node 15.14, fabric 4.2.0, canvas 2.6.

In browser canvas and jpeg works well. On node.js (fastify route) has issue:

const fabricCanvas = new fabric.StaticCanvas(null, { 700, 500 });
fabricCanvas.toDataURL({
    format: "jpeg",
    quality: 100,
    multiplier: exportRatio,
});

I have exception on toDataURL line.

Canvas.toDataURL with mime type image/jpeg, inside Canvas.toBuffer return undefined. (canvas/lib/canvas.js line 111).

Stack:
TypeError: Cannot read property 'toString' of undefined\n at Canvas.toDataURL (node_modules/canvas/lib/canvas.js:111:60)\n at HTMLCanvasElementImpl.toDataURL (node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:52:31)\n at HTMLCanvasElement.toDataURL (node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:67:23)\n at Object.toDataURL (node_modules/fabric/dist/fabric.js:1212:23)\n at klass.toDataURL (/node_modules/fabric/dist/fabric.js:13680:26)\n at src/layout/routes.ts:46:38\n at Generator.next ()\n at fulfilled (src/layout/routes.ts:5:58)\n at processTicksAndRejections (node:internal/process/task_queues:94:5)"},"msg":"Cannot read property 'toString' of undefined

Issue is:
- only in node.js fastify server (in browser works well)
- Canvas.toBuffer return undefined with image/jpeg (with image/png works well)

**Comment by mike667** [comment]
Here is code example:

```js
const serverFastify = require("fastify")({ logger: true });
const fabric = require("fabric").fabric;

serverFastify.get("/", async (request, reply) => {
  const fabricCanvas = new fabric.StaticCanvas(null, {
    width: 700,
    height: 500,
  });

  const imageBase64 = fabricCanvas.toDataURL({
    format: "jpeg",
    quality: 100,
    multiplier: 2,
  });

  fabricCanvas.dispose();
  reply.send(imageBase64);
});

const start = async () => {
  try {
    await serverFastify.listen(3000);
  } catch (err) {
    serverFastify.log.error(err);
    process.exit(1);
  }
};
start();
```

**Comment by LinusU** [comment]
Would you be able to provide a minimal reproducible example that uses `canvas` directly instead of `fabric`? It's hard to tell if this is a bug in Fabric or Canvas with the posted example...

**Comment by mike667** [comment]
> Would you be able to provide a minimal reproducible example that uses `canvas` directly instead of `fabric`? It's hard to tell if this is a bug in Fabric or Canvas with the posted example...

But Canvas.toBuffer return undefined, with 'image/jpeg'.

**Comment by diogoviannaaraujo** [comment]
Apple M1 processors are not installing with JPEG support, been struggling in how to enable it.

**Comment by waitkafuka** [comment]
> 
You inspired me.
`brew install jpeg`
and then set these env:
`export LDFLAGS="-L/opt/homebrew/opt/jpeg/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/jpeg/include"
export PATH="/opt/homebrew/opt/jpeg/bin:$PATH"
export PKG_CONFIG_PATH="/opt/homebrew/opt/jpeg/lib/pkgconfig"`
this works for me. It enable the JPEG support.
@mike667

**Comment by waitkafuka** [comment]
You inspired me.
brew install jpeg
and then set these env:
export LDFLAGS="-L/opt/homebrew/opt/jpeg/lib" export CPPFLAGS="-I/opt/homebrew/opt/jpeg/include" export PATH="/opt/homebrew/opt/jpeg/bin:$PATH" export PKG_CONFIG_PATH="/opt/homebrew/opt/jpeg/lib/pkgconfig"
this works for me. It enable the JPEG support.
@mike667

**Comment by waitkafuka** [comment]
> Apple M1 processors are not installing with JPEG support, been struggling looking how to enable it.
You inspired me.
brew install jpeg
and then set these env:
export LDFLAGS="-L/opt/homebrew/opt/jpeg/lib" export CPPFLAGS="-I/opt/homebrew/opt/jpeg/include" export PATH="/opt/homebrew/opt/jpeg/bin:$PATH" export PKG_CONFIG_PATH="/opt/homebrew/opt/jpeg/lib/pkgconfig"
this works for me. It enable the JPEG support.
@mike667

**Comment by mike667** [comment]
@waitkafuka The latest release works fine without any modifications on the M1. This bug was fixed maybe half a year ago, I don't remember exactly in which release.
