### ISSUE TITLE
canvas.createPNGStream() interesting behavior

### ISSUE THREAD

**Issue by EvgeniyGorbachev** [Automattic/node-canvas#1838]
Hi.
I try to generate video from canvas and thats why I use createPNGStream() method.
When I was rendered for example 50 images I saw thats all of them the same.

but I'm sure that they should be different - I use other method to save and I get the correct result - all images are different(my function addToCanvasSomeChanges() works fine), but when i use createPNGStream() - all images are the same.

Could someone help me - what is my mistake and how can I use the createPNGStream() correctly so that all the images are correctly drawn and saved (or sent to stream)

```

const i = 0;
const chunks = [1, 2, 3 ...... 50];
const streamsForGenerateVideo = [];
for (const chunk of chunks) { 
  addToCanvasSomeChanges(chunk);
  canvas.renderAll();
  const canvasStream = canvas.createPNGStream();
 
  //streamsForGenerateVideo.push(canvasStream);

 // try to check what stream data return;
  const out = fs.createWriteStream(`${i}.png`);
  canvasStream.on('data', function(chunk){
      out.write(chunk);
  });
  ++i;
}
```

I can solve it by add small delay 50ms before row and change stream type

```
await delay(50);
const canvasStream = canvas.createPNGStream();
 const stream = Readable.from(canvasStream);
streamsForGenerateVideo.push(stream);
```

 but I am not sure thats is good fix.

**Comment by EvgeniyGorbachev** [comment]
I have solved it:

    ```
       const canvasStream = canvas.createPNGStream();
            const stream = Readable.from(canvasStream);
            streamsForGenerateVideo.push(stream);
```

I covered createPNGStream stream type by origin nodejs stream.

**Comment by zbjornson** [comment]
You need to wait for the stream to finish before moving on to the next frame. An easy way to do this is using the [`events.once()`](https://nodejs.org/api/events.html#events_events_once_emitter_name_options) function.
