### ISSUE TITLE
Support for exporting PDFs with embedded text in browser implementation

### ISSUE THREAD

**Issue by paramsiddharth** [Automattic/node-canvas#1851]
Support for exporting PDFs with embedded text in browser implementation

## Issue or Feature
Although `node-canvas` does have a browser implementation, there are not many
reasons to do this with the browser Canvas API already in place. The PDF support
for canvases is not available in the browser implementation, and glyph-mode
text-drawing will be an amazing addition.

## Steps to Reproduce
Here's how I would want to go about it:
1. Use an existing PDF solution for the front-end (e. g. PDF.js) to recreate the PDF implementation
   instead of rebuilding a solution in WebAssembly.
2. Store the text positions and style configurations and manually embed text drawn in glyph drawing
   mode when rendering as PDF (upon a `toBuffer` or `toDataURL` call).
```js
const { createCanvas } = require('canvas');
const can = createCanvas(200, 200);
const ctx = can.getContext('2d');

ctx.fillStyle = 'purple';
ctx.fillRect(0, 0, can.width, can.height);

// Add embeddable text
ctx.textDrawingMode = 'glyph';
ctx.font = '30px Impact';
ctx.fillStyle = 'white';
ctx.rotate(0.1);
ctx.fillText('Awesome!', 50, 100);

const buf = can.toBuffer('application/pdf', { ... }); // The magic happens here
const dataURI = can.toDataURL(); // And here too
```

## Your Environment
* node-canvas v2.8.0.
* Node.js v15.6.0 on Ubuntu (WSL) 20.04.2 LTS.

**Comment by zbjornson** [comment]
Not a bad idea, but I think this is out of scope of this module. To do this, we'd have to completely replace all of the browser Canvas implementation, whereas the "browser" part of this module is intended to provide just enough of a compatibility layer so that you can use the standard Canvas APIs in both environments.

**Comment by paramsiddharth** [comment]
> Not a bad idea, but I think this is out of scope of this module. To do this, we'd have to completely replace all of the browser Canvas implementation, whereas the "browser" part of this module is intended to provide just enough of a compatibility layer so that you can use the standard Canvas APIs in both environments.

I see! I agree with you. That would also unnecessarily make the module bulky. Maybe creating a new front-end JavaScript module would be the way to go for that.
