### ISSUE TITLE
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v72-linux-musl-arm64.tar.gz 

### ISSUE THREAD

**Issue by ehudg** [Automattic/node-canvas#1864]
Hi, I'm attempting to run an app with canvas in AWS CodeBuild.

buildspec.yml:

version: 0.2
env:
  shell: /bin/sh
phases:
  
  install:      
    runtime-versions:
      nodejs: 12
      python: 3.x
      python: 2.x  
  
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g npm@7.20.0
  
  build:
    commands:     
      - docker-compose -f docker-compose.dev.yml up --build -d        
  
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
  
  

The relevant line in package.json:

"canvas": "^2.8.0"

The error I'm getting in CodeBuild log:

> canvas@2.8.0 install /app/node_modules/canvas
--
482 | > node-pre-gyp install --fallback-to-build
483 |  
484 | node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v72-linux-musl-arm64.tar.gz
485 | node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@12.22.3 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
486 | node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v72-linux-musl-arm64.tar.gz

The npm page says that 2.8.0 is the latest version, but it cannot find it.

thanks

**Comment by zbjornson** [comment]
Please see #1511:

> ## Installation fails with a 404 in the log
> #### If you're on Alpine Linux or another distro using [musl-libc](https://www.musl-libc.org/)
> 
> The log may look like
> 
> ```
> node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v64-linux-musl-x64.tar.gz
> ```
> 
> Prebuilds are only available for glibc, not musl-libc. See [node-gfx/node-canvas-prebuilt#77](https://github.com/node-gfx/node-canvas-prebuilt/issues/77), which includes information on building from source.
