### ISSUE TITLE
Error In Node.js 14.9.0 (Ubuntu)

### ISSUE THREAD

**Issue by zmkq** [Automattic/node-canvas#1869]
When I Node A Project It Gives Me AN Error :
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Note : I Tried To Install/Uninstall The Package And Rebuild
## Your Environment
* Version of node-canvas : 2.8.0
* Environment : Node.js 14.9.0 On Ubuntu 20.4

**Comment by zmkq** [comment]
solved the problem thanks!

**Comment by mahapo** [comment]
@zmkq  I have the same issue. What was the solution?
