### ISSUE TITLE
Cant install node-canvas on arm

### ISSUE THREAD

**Issue by Bobby99as** [Automattic/node-canvas#1876]
## Issue or Feature
when trying to install on arm you get ```node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v72-linux-glibc-arm64.tar.gz```

## Steps to Reproduce
be on arm
try to install node-canvas

## Your Environment
Linux Ubuntu arm 20.04LTS
i tried from node 12 to node 16

**Comment by zbjornson** [comment]
Please see #1511:

> #### If you have an ARM CPU
> 
> Prebuilds aren't available for ARM. Please see the [wiki](https://github.com/Automattic/node-canvas/wiki#installation-guides) for guides on building from source. See also [node-gfx/node-canvas-prebuilt#69](https://github.com/node-gfx/node-canvas-prebuilt/issues/69).
