### ISSUE TITLE
response status 404

### ISSUE THREAD

**Issue by LMS5413** [Automattic/node-canvas#1877]
When I try to install canvas it throws the following errors 
![imagem_2021-08-12_133716](https://user-images.githubusercontent.com/58144443/129234540-02263c6e-3d98-47e6-8468-4b7f539e3610.png)

**Comment by zbjornson** [comment]
See #1511:

> ## Installation fails with a 404 in the log
> #### If you're on Alpine Linux or another distro using [musl-libc](https://www.musl-libc.org/)
> 
> The log may look like
> 
> ```
> node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v64-linux-musl-x64.tar.gz
> ```
> 
> Prebuilds are only available for glibc, not musl-libc. See [node-gfx/node-canvas-prebuilt#77](https://github.com/node-gfx/node-canvas-prebuilt/issues/77), which includes information on building from source.
