### ISSUE TITLE
Installation issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by chris-cooper** [Automattic/node-canvas#1881]
## Issue or Feature
I'm having trouble using node-canvas on Ubuntu 20.04

### Try 1
- install dependencies ```sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev```
- set up a new project
- npm add canvas
- run the sample code

```
Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /lib/x86_64-linux-gnu/libuuid.so.1)
```

### Try 2
- as above, but with `npm install --build-from-source`

```
Error: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /lib/x86_64-linux-gnu/libcairo.so.2)
 ```

## Your Environment
* Version of node-canvas: ` canvas@2.8.0`
* Environment:
```
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
Node: v12.22.5

**Comment by paramsiddharth** [comment]
Could you try the same using Node.js 15.6.0? I use Ubuntu 20.04.2 LTS inside WSL2 too, it worked fine for me.

**Comment by chris-cooper** [comment]
Ah interesting suggestion thanks @paramsiddharth .  I was assuming the problem would be independent to node version.  Just tried with the following configuration and it worked!

```
node: 14.17.5
canvas: 2.8.0
```

**Comment by paramsiddharth** [comment]
> Ah interesting suggestion thanks @paramsiddharth . I was assuming the problem would be independent to node version. Just tried with the following configuration and it worked!
> 
> ```
> node: 14.17.5
> canvas: 2.8.0
> ```

I'm glad I could help! :) Happy development!
