### ISSUE TITLE
Support for docker - node:alpine

### ISSUE THREAD

**Issue by vdemcak** [Automattic/node-canvas#1886]
## Issue or Feature
Hey, I'm unable to install canvas 2.8.0 on my docker container which is running **node:alpine**. Every time npm wants to install this package I get node-gyp error. Could someone help me out with this? Thanks. 
## Steps to Reproduce
Try to install node-canvas on docker container running **node:alpine** image

## Your Environment
* Version of node-canvas : 2.8.0
* Environment: latest Node

**Comment by FoxxMD** [comment]
@vdemcak how did you resolve this?

**Comment by vdemcak** [comment]
I used [this](https://github.com/joshmarinacci/node-pureimage). Works like a charm while being tiny.

**Comment by FoxxMD** [comment]
Woah that is excellent! I'll be suggesting that to resemblejs team as a drop-in replacement...

In the meantime though I found my own solution. For posterity:

https://github.com/node-gfx/node-canvas-prebuilt/issues/77#issuecomment-884365161

Modify Dockerfile to include these lines somewhere before `npm install --build-from-source`

```
RUN apk add --no-cache build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev

RUN apk add --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing libmount ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family fontconfig
```

**Comment by vdemcak** [comment]
Yeah, I got it working somewhat like that too but it increased the container size dramatically.

**Comment by vandeace** [comment]
> Woah that is excellent! I'll be suggesting that to resemblejs team as a drop-in replacement...
> 
> In the meantime though I found my own solution. For posterity:
> 
> [node-gfx/node-canvas-prebuilt#77 (comment)](https://github.com/node-gfx/node-canvas-prebuilt/issues/77#issuecomment-884365161)
> 
> Modify Dockerfile to include these lines somewhere before `npm install --build-from-source`
> 
> ```
> RUN apk add --no-cache build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev
> 
> RUN apk add --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing libmount ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family fontconfig
> ```

mine error like this #6 466.6 (125/125) Installing pango-dev (1.48.2-r0)
#6 466.7 Executing busybox-1.32.1-r6.trigger
#6 466.7 Executing glib-2.66.8-r0.trigger
#6 466.7 No schema files found: doing nothing.
#6 466.7 1 error; 294 MiB in 140 packages
------
executor failed running [/bin/sh -c apk add --no-cache build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev]: exit code: 1
