### ISSUE TITLE
invalid ELF header on Heroku

### ISSUE THREAD

**Issue by git-tayze** [Automattic/node-canvas#1890]
## Environment

* Node v16.6.1 on Windows OS Build: 19043.1165
* Hosting site: _**[Heroku](https://heroku.com/)**_
* canvacord@5.2.3
  └── canvas@2.8.0

## Issue
* 2021-08-28T12:29:08.870584+00:00 app[Worker.1]: Error: /app/node_modules/canvas/build/Release/canvas.node: invalid ELF header
* #1000 

## Code
```
const Discord = require('discord.js')
const canvacord = require('canvacord')

const rank = new canvacord.Rank()
.setAvatar(member.displayAvatarURL({ dynamic: false, format: 'png' }))
.setCurrentXP(user.xp)
.setLevel(user.level)
.setRequiredXP(neededXp)
.setStatus(target.presence.status)
.setBackground("IMAGE", "Private img lin")
.setProgressBar("#00FF00", "COLOR")
.setUsername(member.username)
.setDiscriminator(member.discriminator);
rank.build()
.then(data => {
const attachment = new Discord.MessageAttachment(data, "RankCard.png");
message.channel.send({ files: [attachment] }) });
```

**Comment by git-tayze** [comment]
Turned out I needed to add node_modules to the .gitignore file.

**Comment by gagangoku** [comment]
In my case I had to add node_modules to the .dockerignore file
