### ISSUE TITLE
Bug: Unable to read pdf stream

### ISSUE THREAD

**Issue by joshpetit** [Automattic/node-canvas#1897]
Hey! Thanks for continually working on this great library it's a big help :)

## Issue or Feature
I've been working on writing tests for an API that [generates colors](https://github.com/petit-development/colors) and I've had problems validating the output of `canvas.createPdfStream`. the PNG and JPEG streams can be validated perfectly with the [file-type](https://github.com/sindresorhus/file-type) library, but it cannot read from the pdf stream created, this error is thrown:

```
End-Of-Stream

      at ReadStreamTokenizer.readBuffer (node_modules/strtok3/lib/ReadStreamTokenizer.js:41:19)
      at ReadStreamTokenizer.ignore (node_modules/strtok3/lib/ReadStreamTokenizer.js:89:31)
      at _fromTokenizer (node_modules/file-type/core.js:589:3)
      at Object.fromStream (node_modules/file-type/core.js:16:10)
      at Object.<anonymous> (lib/colors.test.ts:39:15)
```

## Steps to Reproduce

You can clone [this](https://github.com/Petit-Development/Colors) repo, then run `yarn test` in the `be/api` branch and look at the test that fails

or

```sh
yarn add file-type
```
Within a ts file:
```ts
import { createCanvas } from 'canvas'

var canvas = createCanvas(200, 200, 'pdf');
var ctx = canvas.getContext('2d');
ctx.fillStyle = '#000000';
ctx.fillRect(0, 0, canvas.width, canvas.height);
const fileStream = canvas.createPDFStream();
const ret = await FileType.fromStream(fileStream);
console.log(ret!.mime);
```

## Your Environment
* node-canvas v2.8.0
* Node v16.8.0 on Arch Linux

I'm not sure if this is an issue with how canvas handles the pdf stream or with how `file-type` reads streams.

**Comment by zbjornson** [comment]
This looks like a bug in the file-type module. It's calling `tokenizer.ignore(1350)`, which throws an end-of-stream error if that many bytes are not available. This small example PDF stream is only 904 bytes.

**Comment by joshpetit** [comment]
> This looks like a bug in the file-type module. It's calling `tokenizer.ignore(1350)`, which throws an end-of-stream error if that many bytes are not available. This small example PDF stream is only 904 bytes.

Ah ok thank you! I'll bring up the issue in the library's repo. I appreciate it a lot!
