### ISSUE TITLE
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing

### ISSUE THREAD

**Issue by liSong5713** [Automattic/node-canvas#1901]
## Issue 
[1] NODE_MODULE_VERSION 83. This version of Node.js requires
[1] NODE_MODULE_VERSION 89. Please try re-compiling or re-installing

node-canvas is rebuild error in electron . but  version 89 is not exist in https://github.com/Automattic/node-canvas/releases

## Environment
 - node : v14.17.5
 - electron:13.4.0

**Comment by LinusU** [comment]
You are trying to use a binary compiled for a different version of Node/V8/Electron.

`npx electron-rebuild` or `npm rebuild` should fix this.

**Comment by liSong5713** [comment]
> You are trying to use a binary compiled for a different version of Node/V8/Electron.
> 
> `npx electron-rebuild` or `npm rebuild` should fix this.

I've tried .electron-rebuild(@3.2.3)   to rebuild all addons fail  includes node-canvas  
`
node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:109:19
`

and i debug electron-rebuild  found runtime error in  `node-gyp configure`  info list :


`
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.17.5 | darwin | x64
gyp info find Python using Python version 3.9.7 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/lisong/.nvm/versions/node/v14.17.5/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lisong/practice/electron-app/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lisong/.nvm/versions/node/v14.17.5/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lisong/Library/Caches/node-gyp/14.17.5/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lisong/Library/Caches/node-gyp/14.17.5',
gyp info spawn args   '-Dnode_gyp_dir=/Users/lisong/.nvm/versions/node/v14.17.5/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/lisong/Library/Caches/node-gyp/14.17.5/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/lisong/practice/electron-app/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Debugger listening on ws://127.0.0.1:58861/008cbd5c-25e3-4501-b0a6-b777c3bcdb10
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
gyp: Call to 'node ./util/has_lib.js jpeg' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
`

**Comment by liSong5713** [comment]
![截屏2021-09-16 下午5 12 20](https://user-images.githubusercontent.com/19524010/133585121-e15a04df-d7c8-4e32-929e-601d6f11f322.png)

**Comment by liSong5713** [comment]
> You are trying to use a binary compiled for a different version of Node/V8/Electron.
> 
> `npx electron-rebuild` or `npm rebuild` should fix this.

it works  not  in vscode terminal
