### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by el2zay** [Automattic/node-canvas#1903]
Hi,
I have a problem with canvas for a while, every time I try to start my JS code I get this error...

![image](https://user-images.githubusercontent.com/79168733/134465530-a6b09db3-181a-4b3f-8f9e-84816326423f.png)

node version: 
v16.9.1

npm: 
7.21.1

OS: Ubuntu 20.04.3 LTS aarch64

**Comment by el2zay** [comment]
So?

**Comment by LinusU** [comment]
It seems like the library is compiled for another platform. Try running `npm rebuild`

**Comment by el2zay** [comment]
![image](https://user-images.githubusercontent.com/79168733/134939638-4b17583a-db4d-453d-a309-8a6d5f28f10e.png)

That not work
