### ISSUE TITLE
What is the right canvas version for node 14.18.0

### ISSUE THREAD

**Issue by NoobCoderJJ** [Automattic/node-canvas#1905]
I had been facing this issue in heroku while hosting my discord bot
![07258FD8-A4A7-45E6-A57D-F24AC0B8FC0C](https://user-images.githubusercontent.com/90484960/135733692-52a0d9b0-e0b2-409e-bd74-4a95d33369ba.jpeg)

**Comment by LinusU** [comment]
I'm not sure how Heroku builds your dependencies, if it just copies them from your machine you need to deploy from the same environment as you are going to run in.

Since the top of the error message you provided is missing it's hard to tell exactly what the problem is...

**Comment by mn4367** [comment]
@NoobCoderJJ, I think the correct native modules are picked up by canvas it self during `npm i`, depending on the underlying Node.js version. Node.js 14 and 16 are both running fine with canvas 2.8.0 here. Maybe you are running into the same problem as in #1914, you'll find a possible [fix](https://github.com/Automattic/node-canvas/issues/1914#issuecomment-956898031) there.

**Comment by LingleDev** [comment]
Is the solution here just to run a lesser version of canvas?
