### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by aastefian** [Automattic/node-canvas#1908]
## Issue or Feature

Hello guys,

I was following for a while now a feature request to add a method to deregister fonts, and i see that now a PR (https://github.com/Automattic/node-canvas/pull/1811) has been approved and merged to master adding that functionality, but no release is available to use that feature. That feature is very useful when registering a lot of fonts on a server, and also when having conflicts overriding fonts with same family, style, weight.

Do you think it would be possible do a small release of master ?

**Comment by alexboboc** [comment]
I followed the exact same path as this gentleman and got here as well. +1 to the release request.

**Comment by LinusU** [comment]
2.9.0 have been released 🚀
