### ISSUE TITLE
Windows 7 x64. Compiled from sources. Can't load.

### ISSUE THREAD

**Issue by vatula** [Automattic/node-canvas#191]
I have this weird issue. I downloaded Windows 7 SDK, then GTK+ x86, then installed node-gyp, then took node-canvas sources, then compiled. Got this small warning:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(99
1,5): warning MSB8012: TargetExt(.dll) does not match the Linker's OutputFile p
roperty value (.node). This may cause your project to build incorrectly. To cor
rect this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) prop
erty values match the value specified in %(Link.OutputFile). [D:\Development\Ho
me\Projects\Js\shelf\node_modules\canvas\build\canvas.vcxproj]

But I guess that can be ignored. Then tried to run an example from README.md. Because of try/catch block canvas said it can't load module from “default” folder. I commented out try/catch and got this:

module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: The specified module could not be found.
D:\Development\Home\Projects\Js\shelf\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (D:\Development\Home\Projects\Js\shelf\node_modules\canvas\lib\bindings.js:5:20)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by PawandeepKaur** [comment]
I have a same problem. Windows 8 64bit.  with depends.exe I  am getting the following error

API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL

I have path set for GTK bin, I have downloaded 64bit GTK version. I have had copied all dll from GTK/bin. I have already found first 3 and dont know how can I get last 2. any suggestions

**Comment by PaulBGD** [comment]
Same issue here @PawandeepKaur, did you ever solve it?

**Comment by Mrnikbobjeff** [comment]
@PaulBGD I have the same issue, it is related to Windows 8.1. Apparently Microsoft changed the design of Windows, effectively breaking the compability with older dlls or exe files. http://answers.microsoft.com/en-us/windows/forum/windows8_1-performance/32-bit-application-fails-to-start-after-81-upgrade/b825723e-e2a2-4c8f-bd1f-10446a5d7059?auth=1

**Comment by PawandeepKaur** [comment]
@PaulBGD  it was so trouble for me to that in windows, thus I switches to linux and it installed  and run very well..

**Comment by brettz9** [comment]
Following the helpful information at https://github.com/Automattic/node-canvas/issues/191#issuecomment-7681555 (and also https://github.com/nodejs/node-gyp/issues/94#issuecomment-278587021 and of course https://github.com/Automattic/node-canvas/wiki/Installation---Windows), I made a node file that could be added to `postinstall` or such as it detects Windows and copies the files in the expected directories if present: https://github.com/brettz9/typeson-registry/blob/master/windows-install.js
