### ISSUE TITLE
Add Arch Linux installation instructions in Wiki

### ISSUE THREAD

**Issue by ma1ted** [Automattic/node-canvas#1911]
I have created a fork of this repository and added instructions for installation on Arch-based Linux distributions. See the link for the added page. 
https://github.com/ma1ted/node-canvas/wiki/Installation%3A-Arch-based-distributions
Also updated is `Home.md` to include the new page.
All the packages are from the official Arch repository; none are from the AUR.

**Comment by LinusU** [comment]
Sorry for the delay, these should be added now! Thanks ❤️
