### ISSUE TITLE
Vulnerable dependencies

### ISSUE THREAD

**Issue by guillaumearnx** [Automattic/node-canvas#1916]
Hello.
Some users reported me that theres vulnerable dependencies on this package.

Canvas version : **^2.8.0**

![image](https://user-images.githubusercontent.com/37373941/139508642-a7f3be0d-a757-4310-91fa-707453340910.png)

*Please note that `npm audit fix` doesn't resolve the issue on my computer*

Environment
Canvas 2.8.0
NodeJS 16.8.0
NPM 8.1.1

Best regards,
ARNOUX Guillaume

**Comment by imranbarbhuiya** [comment]
same issue

**Comment by mn4367** [comment]
I 'fixed' this with https://stackoverflow.com/a/69642492 although this feels more like a temporary hack to me.

**Comment by LinusU** [comment]
This seems to be a problem with the `@mapbox/node-pre-gyp` dependency. Could someone report this [upstream](https://github.com/mapbox/node-pre-gyp/issues)?

**Comment by guillaumearnx** [comment]
I think a fix was pushed [here](https://github.com/mapbox/node-pre-gyp/commit/ef8f171c0f745da6c607b88f91425b2c28c387e9)

**Comment by LinusU** [comment]
This should be fixed now, run `npm audit fix` or do a fresh install of canvas and it should be good 👍
