### ISSUE TITLE
default x,y values to 0 if not given to drawImage

### ISSUE THREAD

**Issue by kennedybaird** [Automattic/node-canvas#1917]
## Issue or Feature
Feature request.

If no `x` or `y` passed into `drawImage()` default to `0,0`.

I'm doing a rather large project juggling sometimes hundreds of canvases, and feel like this could be a good feature for code simplicity.

**Comment by zbjornson** [comment]
Reasonable suggestion, but the Canvas spec doesn't allow that syntax, and node-canvas follows the spec as closely as possible. (Firefox throws `CanvasRenderingContext2D.drawImage: 1 is not a valid argument count for any overload` for example.)
