### ISSUE TITLE
Non-Public API: Please help for my this problem when upload app to Mac Store.

### ISSUE THREAD

**Issue by Xing1P** [Automattic/node-canvas#1924]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Your app uses or references the following non-public APIs:

Info
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_set_quality
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_destroy_decompress
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_finish_decompress
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_CreateCompress
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_std_error
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_destroy_compress
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_finish_compress
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_CreateDecompress
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_read_header
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_set_defaults
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_abort_decompress
• Contents/Resources/app.asar.unpacked/node_modules/canvas/build/Release/canvas.node/_jpeg_simple_progression

The use of non-public APIs is not permitted on the App Store, because it can lead to a poor user experience should these APIs change.
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas 
`tui-image-editor@3.15.2
  └─┬ fabric@4.5.1
    ├── canvas@2.8.0
    └─┬ jsdom@15.2.1
      └── canvas@2.8.0`
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
Node:v16.13.0
NPM:7.9.0

**Comment by leanghorn** [comment]
I got the same issue in Mac Store.

**Comment by zbjornson** [comment]
Those look like a false-positives, they're all public methods. Someone else has encountered this: https://stackoverflow.com/questions/68155591/how-to-locate-source-of-private-apis-in-my-app-to-pass-apple-review
