### ISSUE TITLE
pls restore branch M1

### ISSUE THREAD

**Issue by dangtinh97** [Automattic/node-canvas#1927]
i run npm install but has_lib is
var SYSTEM_PATHS = [
  '/lib',
  '/usr/lib',
  '/usr/lib64',
  '/usr/local/lib',
  '/opt/local/lib',
  '/usr/lib/x86_64-linux-gnu',
  '/usr/lib/i386-linux-gnu',
  '/usr/lib/arm-linux-gnueabihf',
  '/usr/lib/arm-linux-gnueabi',
  '/usr/lib/aarch64-linux-gnu'
]

**Comment by dangtinh97** [comment]
Error: node-canvas was built without JPEG support
on M1 with branch master

**Comment by LinusU** [comment]
The `m1` branch is merged into `master` now, could you use that one?

**Comment by dangtinh97** [comment]
but i run npm install canvas no have '/opt/homebrew/lib' in file has_lib.js
