### ISSUE TITLE
New version of node-canvas?

### ISSUE THREAD

**Issue by daddy88** [Automattic/node-canvas#1935]
Hi guys,

Firstly a huge thanks for making and maintaining node-canvas!

I was wondering what the plans are for making a new 2.8.1 release? Theres been a lot of fixes and new features since May 16, and IMO there would be a lot of people that could benefit from these features being available through NPM etc.

Hope you will consider making a new release with all these new features/fixes.

**Comment by thornjad** [comment]
I would really love to get those M1 fixes released!

**Comment by zbjornson** [comment]
@LinusU I just made the prebuilds for v2.9.0. Can you publish to NPM sometime please?

**Comment by LinusU** [comment]
So sorry for totally missing this, published 🚀 

(@zbjornson we should make sure that you can publish to Npm as well, what is your username there?)

**Comment by zbjornson** [comment]
Yay!

npm access would be great, I'm zbjornson on there. Would be great to get @chearon as well (calebhearon on npm).

**Comment by LinusU** [comment]
Added you both!
