### ISSUE TITLE
Context save/restore does not handle textBaseline

### ISSUE THREAD

**Issue by JacobNorlin** [Automattic/node-canvas#1936]
## Issue

The context.textBaseline property doesn't seem to be part of the drawing state and is unaffected by save/restore calls.
https://html.spec.whatwg.org/multipage/canvas.html#the-canvas-state
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/save#drawing_state

## Steps to Reproduce

```js
const {createCanvas} = require('canvas');

const canvas = createCanvas(100, 100);
const context = canvas.getContext('2d');

context.textBaseline = 'top';
console.log('top', context.textBaseline);
context.save();
context.textBaseline = 'middle';
console.log('middle', context.textBaseline);
context.restore();
console.log('top', context.textBaseline);
```

*Expected output*
top top
middle middle
top top

*Actual output*
top top
middle middle
top middle

## Your Environment
* 2.8.0
* Node 12.16.2, Windows 10 (21H2)

Also tested with canvas 2.6.1 and node 8.17.0, issue there as well.

**Comment by JacobNorlin** [comment]
Did a check for all properties listed in the spec and this also affects the imageSmoothingQuality property

**Comment by zbjornson** [comment]
> Did a check for all properties listed in the spec and this also affects the imageSmoothingQuality property

Thanks for doing that. `imageSmoothingQuality` isn't saved/restored because that prop isn't implemented at all, it looks like.

Fixes for `textBaseline` and a few others coming up.
