### ISSUE TITLE
Why this file is not available any more? 

### ISSUE THREAD

**Issue by beshoo** [Automattic/node-canvas#1937]
Hi.

I have a library whuch use thus canvas addon, by calling this url

https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-linux-musl-x64.tar.gz

But it seems url removed from  the releases. Whuch broken the install process. 

Please how can we reuse the same url again? 

Regard

**Comment by zbjornson** [comment]
Please see #1511 from the issue template:

> If you're on Alpine Linux or another distro using musl-libc
>
> The log may look like
>
> node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v64-linux-musl-x64.tar.gz
>
> Prebuilds are only available for glibc, not musl-libc. See node-gfx/node-canvas-prebuilt#77, which includes information on building from source.
