### ISSUE TITLE
Azure Function v4 - Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Acantidian** [Automattic/node-canvas#1941]
Hi,
Has anyone found a way to use node-canvas within an azure function?
I've implemented locally with visual studio code (azure function tool 4.x) and everything works but after the publishing the function always return http status code 500, from the log i'm able to retrieve the following error:

`Result: Failure Exception: Worker was unable to load function ********: 'Error: A dynamic link library (DLL) initialization routine failed. \\?\C:\home\site\wwwroot\node_modules\canvas\build\Release\canvas.node' Stack: Error: A dynamic link library (DLL) initialization routine failed. \\?\C:\home\site\wwwroot\node_modules\canvas\build\Release\canvas.node at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Module.require (internal/modules/cjs/loader.js:952:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (C:\home\site\wwwroot\node_modules\canvas\lib\bindings.js:3:18) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Error`

There is some procedure to be carried out for the deployment?

### Enviroment
Cloud Platform : Azure
Resource : Azure Function
OS : Windows x64
Canvas : ^2.8.0
Runtime : node 14

**Comment by zbjornson** [comment]
Sorry this got no response. There's not enough info here to troubleshoot. Please open a new issue if you still need help. #1970 might be useful.
