### ISSUE TITLE
CanvasRenderingContext2d.restore() does not restore font weight

### ISSUE THREAD

**Issue by HackbrettXXX** [Automattic/node-canvas#1946]
## Issue
CanvasRenderingContext2d.restore() does not restore font weight.

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');

ctx.font = 'normal 16px sans-serif';
ctx.save():
ctx.font = 'bold 16px sans-serif';
ctx.restore();
ctx.font === 'bold 16px sans-serif' // should be 'normal 16px sans-serif' now
```

## Your Environment
* canvas@2.8.0
* node@16.4.2 on Windows 10

**Comment by LinusU** [comment]
I'm not able to reproduce this is in the browser. In fact, it seems like "bold" is always stripped 🤔 

```js
var canvas = document.createElement('canvas')
var ctx = canvas.getContext('2d')

ctx.font = '16px sans-serif'
console.log(ctx.font, 'should be "16px sans-serif"')
ctx.save()
ctx.font = 'bold 16px sans-serif'
console.log(ctx.font, 'should be "bold 16px sans-serif"')
ctx.restore()
console.log(ctx.font, 'should be "16px sans-serif"')
```

<img width="412" alt="Screenshot 2021-12-11 at 12 25 58" src="https://user-images.githubusercontent.com/189580/145674703-49abfd6e-250a-4a44-a341-31718119fc1c.png">

**Comment by HackbrettXXX** [comment]
In Chrome, this is logged (bold is returned):
![image](https://user-images.githubusercontent.com/16103654/145792871-e69a5f53-6b06-4379-8b57-10acea439b6d.png)
