### ISSUE TITLE
gyp not building with jpeg/gif support

### ISSUE THREAD

**Issue by logicalparadox** [Automattic/node-canvas#195]
It looks like `with_jpeg/gif` is hardcoded as false in the `binding.gyp` file. Given the bugfixes already applied to work with node 0.8.x,'s version of v8, it would be great if this integrated with the configure file that you started so we could use the full functionality of this module. Any idea on when this will be available?

I don't know enough about gyp to be able to open a pull request for this. If you don't have time enough to implement or could point me to a project or docs that implement this type of configuration, or provide more specifics on what it is you were in the process of doing, I would be more than happy to give it a go.

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
