### ISSUE TITLE
 Cannot find module 'canvas'

### ISSUE THREAD

**Issue by a6965921** [Automattic/node-canvas#1978]
![image](https://user-images.githubusercontent.com/1198840/151944276-9020cf64-da3c-4198-bfb2-edd67d5995e8.png)
`const { createCanvas, loadImage } = require('canvas')
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext('2d')

// Write "Awesome!"
ctx.font = '30px Impact'
ctx.rotate(0.1)
ctx.fillText('Awesome!', 50, 100)

// Draw line under text
var text = ctx.measureText('Awesome!')
ctx.strokeStyle = 'rgba(0,0,0,0.5)'
ctx.beginPath()
ctx.lineTo(50, 102)
ctx.lineTo(50 + text.width, 102)
ctx.stroke()

// Draw cat with lime helmet
loadImage('examples/images/lime-cat.jpg').then((image) => {
  ctx.drawImage(image, 50, 0, 70, 70)

  console.log('<img src="' + canvas.toDataURL() + '" />')
})`

**Comment by zbjornson** [comment]
You installed canvas with `-g` but are trying to load it in a module. Try without `-g`.
