### ISSUE TITLE
Graphical glitch

### ISSUE THREAD

**Issue by Droutin** [Automattic/node-canvas#1988]
## Issue
When FloodFilling individual seats in for loop and replacing that seat on the same coords, it glitches.
![image](https://user-images.githubusercontent.com/17362753/153441851-22ea9de6-efc6-493c-9ec0-b95865d550e4.png)

## Steps to Reproduce
Working demo [https://codesandbox.io/s/node-js-forked-485ud?file=/src/index.js](https://codesandbox.io/s/node-js-forked-485ud?file=/src/index.js)

## Your Environment
canvas@2.9.0
Node v16.13.2 on Windows 11 64bit tested also on MacOS 12.2 with same result

**Comment by zbjornson** [comment]
I see the same glitch when that codesandbox is run in Chrome, so this doesn't appear to be an issue with node-canvas. Happy to reopen if I'm mistaken.
