### ISSUE TITLE
Installation problem in ubuntu

### ISSUE THREAD

**Issue by jfromaniello** [Automattic/node-canvas#200]
after following the instructions on the [ubuntu page](https://github.com/LearnBoost/node-canvas/wiki/Installation---Ubuntu)
I get this error when trying to install the canvas:

```
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
```

I have already installed libcairo2-dev and libjpeg8-dev

**Comment by miguelmota** [comment]
Had same issue as OP in Ubuntu 14.04, installing `libpango1.0-dev` and `libjpeg-dev` fixed the problem.

**Comment by sungwoncho** [comment]
I am seeing the same issue. I followed the instruction in [the wiki](https://github.com/Automattic/node-canvas/wiki/Installation---Ubuntu-and-other-Debian-based-systems#installing-dependencies). I installed `libjpeg-dev` as per @miguelmota's solution, but still have the same error. Any suggestions?

**Comment by sungwoncho** [comment]
It was Dokku issue. I had to inject dependencies into the container. https://github.com/Automattic/node-canvas/issues/483
