### ISSUE TITLE
Not compatible with TypeScript 4.6

### ISSUE THREAD

**Issue by SimenB** [Automattic/node-canvas#2000]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce
https://github.com/SimenB/canvas-ts

```
node_modules/canvas/types/index.d.ts:170:2 - error TS2416: Property 'globalCompositeOperation' in type 'NodeCanvasRenderingContext2D' is not assignable to the same property in base type 'CanvasRenderingContext2D'.
  Type '"clear" | "color" | "color-burn" | "color-dodge" | "copy" | "darken" | "destination-atop" | "destination-in" | "destination-out" | "destination-over" | "difference" | "exclusion" | ... 16 more ... | "destination"' is not assignable to type 'GlobalCompositeOperation'.
    Type '"clear"' is not assignable to type 'GlobalCompositeOperation'.

170  globalCompositeOperation: 'saturate' | 'clear' | 'copy' | 'destination' | 'source-over' | 'destination-over' |
     ~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/canvas/types/index.d.ts:170
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.9.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 16.14.0 on macOS 12.2.1 (TypeScript 4.6)

**Comment by Caesarovich** [comment]
Experiencing the same issue here

**Comment by Apolofx** [comment]
Same issue here too, found this while [comparing Typescript new release v4.6.2 with v4.5.5](https://github.com/microsoft/TypeScript/compare/v4.5.5...v4.6.2#diff-dc0eab937d15e62545da3ed7b4f40ad6b24f15dd88fbc6ceda2bfb4ed8356eb0R3281)
![image](https://user-images.githubusercontent.com/26746547/156202425-8fc18ce9-df10-4d3e-9a4c-9b357b3c7c8d.png)
Not sure if the issue should be here or in Typescript repo

**Comment by zbjornson** [comment]
I think we need to finally redo all of the types from scratch instead of trying to extend the native HTML Canvas types. I'll try to do this this week.

**Comment by zbjornson** [comment]
#1986 broke support for our non-standard "saturate" operator, but otherwise yes.

**Comment by chearon** [comment]
I didn't see a way not to break that, as long as we were trying to be assignable to the DOM type.

**Comment by nathantokarz** [comment]
Is there a way to work around this but downgrading to a different type-script version? unable to run any builds due to this error

**Comment by Apolofx** [comment]
> Is there a way to work around this by downgrading to a different type-script version? unable to run any builds due to this error

I locked Typescript version to 4.5.5 in my `package.json` and that did the job

**Comment by nathantokarz** [comment]
changing my typescript version to 4.5.5 worked for me as well! Thanks

**Comment by LinusU** [comment]
> https://github.com/Automattic/node-canvas/pull/1986 broke support for our non-standard "saturate" operator, but otherwise yes.

> I didn't see a way not to break that, as long as we were trying to be assignable to the DOM type.

Maybe we should deprecate `"saturate"` with a link to an issue for anyone to chime in with use cases. My _guess_ is that it was just thrown in because it exists in Cairo, but it might not actually be widely used.

**Comment by Rush** [comment]
You can upgrade to my "temporary release" of node-canvas 2.9.0 with just the typings fix. Just change your `package.json` manually to:
```
 "canvas": "Rush/node-canvas#v2.9.0-patched",
```
The typings fix is here: https://github.com/Rush/node-canvas/blob/636e4dbc0a18a5861d77620b3658b944f778691e/types/index.d.ts#L170

**Comment by zbjornson** [comment]
v2.9.1 is now published.
