### ISSUE TITLE
`document` is not defined

### ISSUE THREAD

**Issue by Atulin** [Automattic/node-canvas#2001]
## Steps to Reproduce

```ts
import { createCanvas } from "canvas";

export default (name: string, width: number = 200, height: number = 200): Buffer => {
    const initials = name.split(/[\s,-_|]/).map(s => s[0]).join('');

    const canvas = createCanvas(width, height); // error occurs here
    const ctx = canvas.getContext('2d');
    // ...
}
```
[Full file in my repo](https://github.com/Genfic/Avatar-Generator/blob/master/src/generators/image-generator.ts#L6)

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): **2.9.0**
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node **17.0.1** on **Windows 10**

## Investigation results

The generated file after `yarn dev` seems to contain references to `document` which is probably the issue:

```js
    var ne = d(b => {
        // ...
        b.createCanvas = function (s, e) {
            return Object.assign(document.createElement("canvas"), {width: s, height: e})
        };
       // ...
        b.loadImage = function (s, e) {
            return new Promise(function (t, r) {
                let n = Object.assign(document.createElement("img"), e);
                // ...
            })
        }
    });
```
[Full generated file here](https://gist.github.com/Atulin/aa94efbfec4378332d23f8d1671de822#file-index-js-L464-L480)

**Comment by LinusU** [comment]
You are bundling for the browser, read this to make a bundle for Node:

https://esbuild.github.io/getting-started/#bundling-for-node

**Comment by Atulin** [comment]
```
$ esbuild --bundle --sourcemap --minify --outdir=dist ./src/index.ts --platform=node --target=node17.0
X [ERROR] No loader is configured for ".node" files: node_modules/canvas/build/Release/canvas.node

    node_modules/canvas/lib/bindings.js:3:25:
      3 │ module.exports = require('../build/Release/canvas.node')
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Seems like ESBuild doesn't support `.node` files... The only option seems to be, for some godforsaken reason, writing a [custom plugin](https://github.com/evanw/esbuild/issues/1051)...

**Comment by Atulin** [comment]
Well, build succeeds now, but... the bundle doesn't run...
```
ReferenceError: require is not defined
    at G:\WebstormProjects\ServerlessAvatars\node_modules\canvas\lib\DOMMatrix.js:3:14
    at G:\WebstormProjects\ServerlessAvatars\dist\index.js:1:285
    at G:\WebstormProjects\ServerlessAvatars\node_modules\canvas\lib\context2d.js:11:23
    at G:\WebstormProjects\ServerlessAvatars\dist\index.js:1:285
    at G:\WebstormProjects\ServerlessAvatars\node_modules\canvas\lib\canvas.js:11:19
    at G:\WebstormProjects\ServerlessAvatars\dist\index.js:1:285
    at G:\WebstormProjects\ServerlessAvatars\node_modules\canvas\index.js:1:16
    at G:\WebstormProjects\ServerlessAvatars\dist\index.js:1:285
    at G:\WebstormProjects\ServerlessAvatars\src\generators\image-generator.ts:1:30
    at Script.runInContext (node:vm:139:12)
```

**Comment by Atulin** [comment]
Ah, it seems I got to the root of the issue. I wanted to use this package with Cloudflare Workers, and they run on V8, not Node. That's probably why the starter project didn't have bundling for Node set up.

Any idea if Node-Canvas can work on V8, @LinusU?

**Comment by DavidVaness** [comment]
@Atulin 
so im having this issue in nodejs, did you end up fixing it with the external plugin approach?

**Comment by supersuryaansh** [comment]
@Atulin I am also trying to run node-canvas on Cloudflare workers, did you get them or any other image manipulation working?

**Comment by t2vee** [comment]
@supersuryaansh
Unfortunately Cloudflare Workers uses a custom runtime called [workerd](https://github.com/cloudflare/workerd/) instead of the aforementioned V8 so node-canvas or any other node modules not listed in the [node compatibility for workers docs](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) will not run. 

There has been conversation about getting support for image processing ([here](https://github.com/cloudflare/workerd/issues/54) and [here](https://github.com/cloudflare/workerd/discussions/212)) but as far as I can tell no progress has been made yet.
