### ISSUE TITLE
Can this package be used to avoid `ReferenceError: ImageData is not defined`?

### ISSUE THREAD

**Issue by lindapaiste** [Automattic/node-canvas#2003]
## Issue or Feature
I am trying to run Jest tests on a code where the code itself (not the test) uses an `if (variable instanceof ImageData)` check.   I included `setupFiles: ["canvas"]` in my `jest.config.js` file.  When running tests, I get an error:
```
ReferenceError: ImageData is not defined
```
I know that this is because `ImageData` is a DOM construct and doesn't exist in the Node.js environment.

The `canvas` package includes its own implementation of `ImageData` and I'm wondering if that can be used as a polyfill.  I don't get errors when using `instanceof` checks on `HTMLCanvasElement` and other DOM elements.  Is my setup wrong, or is what I'm trying to do just not possible?  And if it's not possible, is there a better way to check whether or not a variable is an `ImageData` object?

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
```
+-- canvas@2.9.0
`-- jest@27.5.1
  `-- @jest/core@27.5.1
    `-- jest-config@27.5.1
      `-- jest-environment-jsdom@27.5.1
        `-- jsdom@16.7.0
          `-- canvas@2.9.0 deduped
```

* Environment
node v16.13.0 on Windows 10

**Comment by LinusU** [comment]
I would recommend this package:

https://github.com/node-gfx/image-data

My goal is to use this in node-canvas in the future, it has a lot of tests to make sure that it works exactly the same as in the browser.

Something like this should do:

```js
global.ImageData = require('@canvas/image-data')
```

**Comment by atsikov** [comment]
Solution from [this comment](https://github.com/Automattic/node-canvas/issues/2003#issuecomment-1069293463) didn't work me as `putImageData` threw likely because of a mismatching class.
However turned out everything could be fixed simply adding `ImageData` from `canvas` package into global scope
```js
const canvas = require('canvas')

global.ImageData = canvas.ImageData
```

**Comment by DisasterMan78** [comment]
> However turned out everything could be fixed simply adding `ImageData` from `canvas` package into global scope

ES6 `import` style:
```javascript
import { ImageData } from 'canvas';
```
