### ISSUE TITLE
[wiki] Download link for GTK 2 does not work

### ISSUE THREAD

**Issue by raychanks** [Automattic/node-canvas#2005]
This issue should be the same as #1951 but unresolved.

In the wiki page for windows: `https://github.com/Automattic/node-canvas/wiki/Installation:-Windows`. When I click the download link for GTK 2, nothing will be downloaded in chrome browser. In edge browser, an error `<file> can't be downloaded securely` is shown in the download queue.

I found that if I open a new tab and type in the address `http://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip` directly, the file can be downloaded without errors.

I suspect this issue is caused by a protocol downgrade from `https` in github to `http` in ftp.gnome.org.

I saw the request will ultimately be redirected to the `https` counterpart, so I think modifying the hyperlink in the wiki page from `http` to `https` will fix the issue. Or else, maybe we can add a sentence describing the workaround of opening a new tab manually in case someone else counters the same issue.

**Comment by zbjornson** [comment]
Odd, works in Firefox but doesn't work in Chrome. I just changed the links to https: and they work in Chrome now. Thanks!
