### ISSUE TITLE
npm ERR! path errors when installing canvas on macOS Monterey

### ISSUE THREAD

**Issue by The0n1y5pace4ce** [Automattic/node-canvas#2018]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

When trying to install canvas using npm i canvas, a lot of errors show up in the terminal, the same thing happens for any package using canvas. errors: https://srcb.in/AMpNVpDI7X

## Steps to Reproduce

```js
install canvas on macOS Monterey using npm i canvas
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
   latest
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
  node 17.6.0, macOS Monterey

**Comment by zbjornson** [comment]
This is covered in the troubleshooting guide: 

> #### If you have an ARM CPU
> 
> Prebuilds aren't available for ARM. Please see the [wiki](https://github.com/Automattic/node-canvas/wiki#installation-guides) for guides on building from source. See also [node-gfx/node-canvas-prebuilt#69](https://github.com/node-gfx/node-canvas-prebuilt/issues/69).
