### ISSUE TITLE
Python issues when installing from source

### ISSUE THREAD

**Issue by zdnk** [Automattic/node-canvas#2021]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Getting following error when running: `PYTHON=/opt/homebrew/bin/python3 yarn` after adding canvas
```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/homebrew/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)
gyp ERR! stack     at Socket.emit (node:events:527:28)
gyp ERR! stack     at Pipe.<anonymous> (node:net:709:12)
```

## Your Environment
Macbook Pro M1
macOS 12.3 Beta (21E5227a)
```
npm -v
8.5.5
---
node -v
v17.8.0
---
python3 --version                    
Python 3.9.12
```

**Comment by jatinderbhola** [comment]
@zdnk did you find a solution? I am facing the same issue!

**Comment by zbjornson** [comment]
Somewhere there's Python 2 code (uses the `print` statement, no parens) that is being executed with Python 3. I don't know where that is. Maybe try updating npm and node-gyp, or as a last resort, use Python 2?
