### ISSUE TITLE
text added to the image appears in boxes

### ISSUE THREAD

**Issue by neekodevil** [Automattic/node-canvas#2022]
Because when i want to add a simple text on an image it appears in the form of boxes, i have tried in many ways but it always appears like this.
Capture as seen in the image
![imagen_2022-04-14_194522420](https://user-images.githubusercontent.com/94580500/163499175-43fa0a58-6c1b-414b-a970-d0ec9908922f.png)

```js
const { createCanvas, loadImage } = require('canvas')
const Discord = require("discord.js");
const canvas = createCanvas(399, 188)
const ctx = canvas.getContext('2d');
const number = Math.floor(Math.random() * 101)
const background = await loadImage("my background url")

ctx.drawImage(background, 0 , 0, canvas.width, canvas.height)

const y= 100, radio= 45, x=canvas.width/2-radio

ctx.fillStyle = '#A9A3A3';
 
ctx.font = '23px Verdana'

ctx.fillText(number + "%", 175, 75) 

const attach = new Discord.MessageAttachment(canvas.toBuffer(), 'ship.png')
const embed = new Discord.MessageEmbed()
  .setColor("RANDOM")
  .setImage("attachment://ship.png")
return message.channel.send({embeds: [embed], files: [attach]})
```
> Canvas v2.9.1
> Node.js v16.14.2

**Comment by chearon** [comment]
That usually means there are no fonts installed. Is there a warning printed on the console? If that's the issue, you could use `registerFont` or install fonts to the OS.

**Comment by neekodevil** [comment]
> 

i already solved it, thanks
