### ISSUE TITLE
canvas.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by OssieFromDK** [Automattic/node-canvas#2023]
```
return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\Administrator\Folder\node_modules\canvas\build\Release\canvas.node is not a valid Win32 application.
```

I've read thru some other issues and tried both NodeJS x32 & x64, still the same error. Im using canvas version 2.9.1
Any ideas?

**Comment by zbjornson** [comment]
Can you post the output from the steps in https://github.com/Automattic/node-canvas/issues/1533#issuecomment-619580233 to help troubleshoot, please?

**Comment by gsteri1** [comment]
I too am having the same issue:
node_modules\canvas\build\Release\canvas.node is not a valid Win32 application.
x64
8664 

Are the results of both tests. I looked at #1533 and cannot figure out what the other poster did to get this to work. Any hints? Thank you!

**Comment by gsteri1** [comment]
One follow up. Perhaps this might help. npm rebuild canvas --update-binary seems to make things happy. Not sure if this durable.
