### ISSUE TITLE
A png image causes Segmentation fault on windows and out of memory on Linux

### ISSUE THREAD

**Issue by smbape** [Automattic/node-canvas#2027]
## Issue or Feature
Unable to load a png.
There is no issue when loaded in a Firefox or Chrome.

## Steps to Reproduce

```js
const Canvas = require("canvas");
const src = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAABfCAIAAAAoKXMlAAAABElEQVQAAAABnSTXkQAAAABJRU5ErkJggg==";
const data = Buffer.from(src.slice("data:image/png;base64,".length), "base64");
const image = new Canvas.Image();

image.onerror = function(err) {
    console.log(err);
};

image.src = data;
console.log([image.width, image.height]);
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.9.1
* Environment: node v16.14.0 (Windows 10 and Ubuntu 20.04)

**Comment by zbjornson** [comment]
That image doesn't appear to be valid. I don't know what these bytes highlighted on the left are supposed to be (starting at `()s%` up to `IHDR`):
![image](https://user-images.githubusercontent.com/469365/181379136-0379dc9d-772f-4f2d-99a5-2ed588c45915.png)
One guess is that was supposed to be `%s` in a format string but was typo'ed as `s%`.

The crash is in cairo but libpng complains also.

**Comment by smbape** [comment]
Thank you for the clarification.
Closing since it is on the cairo side.
