### ISSUE TITLE
Catching absurdly large canvas sizes

### ISSUE THREAD

**Issue by michaellitherland** [Automattic/node-canvas#2028]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

node-canvas is being used by PDF.js to render PDFs to HTML. I don't have control over the PDFs and some of them come with fun things in them like images that are 2 px wide and 65,538 px high, and even one that's 14 px high and 4.192 million pixels wide. node-canvas is understandably not happy about rendering something like this. 

The corrective steps I use below to get the PDFs to render aren't ideal as they just code in arbitrary limits, but I wonder if node-canvas should have some additional checks and reporting. This condition is very hard to work around without modifying this library.

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```
Here's a sample file that fails if you use PDF.js with node-canvas to render a PDF.

[TallImage.pdf](https://github.com/Automattic/node-canvas/files/8549766/TallImage.pdf)

Maybe a counter example of getting it to work as follows makes sense:

```
function createCanvas (width, height, type) {
  // if (height > 10000 || width > 10000) {
  //   return new Canvas(1024, 1024, type)
  // }
  return new Canvas(width, height, type)
}
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

```
bb-pdf@ /home/nule/Workspace/bb-pdf
└── canvas@2.9.1
```
This is Node 14 on a variety of platforms. WSL2 in windows 10 for development, and various Linux containers in dev/prod.

**Comment by LinusU** [comment]
Do you know if browsers has any limits on this?
