### ISSUE TITLE
Not able to load font

### ISSUE THREAD

**Issue by AryaAnish121** [Automattic/node-canvas#2030]
Hi, I am trying to use `Fira` font but for some reason I am not able to do it.

```
registerFont('./fira.ttf', { family: 'Fira', weight: 700 });
ctx.font = '50px "Fira"';
```

This gives:
```
(process:14880): Pango-WARNING **: 20:25:33.039: couldn't load font "Fira Code Light Not-Rotated 50px", falling back to "Sans Light Not-Rotated 50px", 
expect ugly output.

(process:14880): Pango-WARNING **: 20:25:33.043: couldn't load font "Fira Code Light 50px", falling back to "Sans Light 50px", expect ugly output.
```
and with:
```
registerFont('./fira.ttf', { family: 'Fira', weight: 700 });
ctx.font = '50px';
```
I think it gives the right font but it's too small

**Comment by AryaAnish121** [comment]
It work on 400 weight fonts only idk. I am closing this issue anyways

**Comment by hassannaftabb** [comment]
> Hi, I am trying to use `Fira` font but for some reason I am not able to do it.
> 
> ```
> registerFont('./fira.ttf', { family: 'Fira', weight: 700 });
> ctx.font = '50px "Fira"';
> ```
> 
> This gives:
> 
> ```
> (process:14880): Pango-WARNING **: 20:25:33.039: couldn't load font "Fira Code Light Not-Rotated 50px", falling back to "Sans Light Not-Rotated 50px", 
> expect ugly output.
> 
> (process:14880): Pango-WARNING **: 20:25:33.043: couldn't load font "Fira Code Light 50px", falling back to "Sans Light 50px", expect ugly output.
> ```
> 
> and with:
> 
> ```
> registerFont('./fira.ttf', { family: 'Fira', weight: 700 });
> ctx.font = '50px';
> ```
> 
> I think it gives the right font but it's too small

Hi brother, how were you able to resolve this? actually i can't even load fonts, on my system, kindly please have a look on this issue: https://github.com/Automattic/node-canvas/issues/2285 , and plz help if u can , thanks
