### ISSUE TITLE
Not able to install on Linux server 

### ISSUE THREAD

**Issue by vinayvemu** [Automattic/node-canvas#2032]
## Issue or Feature
this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce

```js
yarn add canvas
```

## Your Environment
* trying to install Version of node-canvas 2.9.1
*linux-musl-x64

Getting following error
node-pre-gyp info check checked for "/var/lib/swis-api/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v93-linux-musl-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v93-linux-musl-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@16.7.0 (node-v93 ABI, musl) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v93-linux-musl-x64.tar.gz 
<img width="1623" alt="Screenshot 2022-05-05 at 7 30 10 PM" src="https://user-images.githubusercontent.com/40784199/166940932-3ece56d1-7a76-40af-bad2-8c0ed456c837.png">

**Comment by Youritch** [comment]
i cann't too

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this.
