### ISSUE TITLE
Question: how to convert from  RGBA32

### ISSUE THREAD

**Issue by natcl** [Automattic/node-canvas#2033]
Hello,
I have a regular canvas that I would like to convert to an RGB16_565 canvas so I can write it to a frame buffer, how can I convert one context to the other ?

Thanks !

**Comment by zbjornson** [comment]
The simplest way is to convert the first canvas to an image (`.toBuffer()` to create a PNG), then use `ctx.drawImage(otherImage, x, y)`. I think this will work, but there are very possibly some gaps in 16_565 format support.

Alternatively, you could use `getImageData()` and manually convert that pixel data before calling `putImageData()`. Here's the 16_565 -> 8888 code (reverse of what you need):
https://github.com/Automattic/node-canvas/blob/9d8da5bf1a272ee3e14637feeef545b622822a03/src/PNG.h#L63-L83

**Comment by natcl** [comment]
Thanks !
