### ISSUE TITLE
Error: The specified module could not be found. node_modules\canvas\build\Release\canvas.node

### ISSUE THREAD

**Issue by amrit-2006** [Automattic/node-canvas#2035]

**Comment by prabhakaran8737** [comment]
Any updates on this? I come across this issue when using [pkg](https://www.npmjs.com/package/pkg)

**Comment by eminoda** [comment]
我这边也遇到这个错：The specified module could not be found. 

如果你也是 windows 平台，或许下面的解决方式可以参考：

1. canvas 的安装前置需要：libjpeg-turbo 和 GTK，请确保按照官方流程安装。
2. 我安装的 nvm，切换在 32 位的 nodejs 版本，所以安装了一套 32 位的 libjpeg-turbo 和 GTK。但发现安装 canvas 时，发现2个 dll 找不到，导致如上错误。现在临时将 32 位切换到 64 位，安装匹配的 64 图形库解决的（libjpeg-turbo-2.0.0-vc64.exe）。

**Comment by mn4367** [comment]
`pkg` tries to resolve the *JS* dependencies by looking into your JS files. Detecting native modules isn't possible/supported, as far as I know, so you have to tell `pkg` what needs to be packaged additionally. This is a sample of what is working here with canvas 2.8.0, Node v16.13.0 on macOS BigSur 11.6.5. I'm also able to bundle `canvas` with `pkg` on the Mac for `win-x64`, `linux-x64` and `darwin-x64` targets with a little additional scripting.

**`pkg.json`**

```
{
  "name": "some-name",
  "version": "1.0.0",
  "description": "Some description",
  "author": "Me",
  "license": "UNLICENSED",
  "private": true,
  "pkg": {
    "assets": [
      "./node_modules/canvas/build/Release/**/*"
    ]
  }
}
```

And then:

```
npm run pkg --output <outputFile> -c pkg.json <input.js>
```
