### ISSUE TITLE
Error in canvas

### ISSUE THREAD

**Issue by MichaelScripter** [Automattic/node-canvas#2037]
## Issue or Feature
The issuse with an module

## Steps to Reproduce
(process:9396): GLib-GIO-WARNING **: 20:47:18.082: Unexpectedly, UWP app `Icons8LLC.Lunacy_8.4.1.0_x64__7g68zyg4rddyp' (AUMId `Icons8LLC.Lunacy_7g68zyg4rddyp!App') supports 1 extensions but has no verbs

## Your Environment
* Version of node-canvas 2.9.1:
* Environment (e.g. node 4.2.0 on Widnows 10, Pro):

**Comment by zbjornson** [comment]
Check out https://stackoverflow.com/questions/67607643/what-does-this-warning-mean-it-happens-every-time-i-restart-the-node-process for a solution that has worked for others. I've never been able to reproduce this issue myself, so can't provide any further advice.
