### ISSUE TITLE
2.9.1 fails to load the correct weights in the same font family

### ISSUE THREAD

**Issue by soren121** [Automattic/node-canvas#2041]
## Issue or Feature
When loading multiple font weights in the same font family, node-canvas 2.9.1 fails to render the correct font weight. This issue did not occur in 2.9.0.

I'm loading four styles of the free "Open Sans" font family: Light (300), Regular (400), Bold (700), and Extra Bold (800). When trying to render text in Regular and Extra Bold as follows, 2.9.1 seems to instead render in Light and Regular, respectively:

```
const defaultFontFamily = '"Open Sans"';
ctx.fillStyle = "#fff";

ctx.font = `400 40px ${defaultFontFamily}`;
ctx.fillText("REGULAR", 40, canvas.height / 2 - 50);

ctx.font = `800 40px ${defaultFontFamily}`;
ctx.fillText("EXTRABOLD", 40, canvas.height / 2);
```

## Steps to Reproduce

I've created a barebones reproducible project, adapted from my actual project.

Running `node index.js` will generate an image named "canvas.png" in the same directory.

Project attached here: [repro.zip](https://github.com/Automattic/node-canvas/files/8734043/repro.zip)

### The following is how 2.9.1 incorrectly renders the example: 

![canvas](https://user-images.githubusercontent.com/295939/169399256-9ec515f0-1f62-47ba-bb57-d01fa68f523f.png)

### And how 2.9.0 correctly renders the example:

![expected-2 9 0](https://user-images.githubusercontent.com/295939/169399263-bf5a369a-fb60-43b9-886f-0b3d43afbde4.png)

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.9.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 14.18.2 on Debian 11 (via WSL2)

**Comment by mjgerace** [comment]
I can confirm this is occurring for me too, as well as font family in registerFont not working.
