### ISSUE TITLE
Please help me I can't install canvas

### ISSUE THREAD

**Issue by slefgameRz** [Automattic/node-canvas#2042]
This is log
npm ERR! code 126
npm ERR! path /home/container/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! sh: 1: node-pre-gyp: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2022-05-22T02_43_05_278Z-debug-0.log
npm ERR! code 126
npm ERR! path /home/container/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! sh: 1: node-pre-gyp: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2022-05-22T02_43_08_150Z-debug-0.log
npm ERR! code 126
npm ERR! path /home/container/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! sh: 1: node-pre-gyp: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2022-05-22T02_43_11_057Z-debug-0.log

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 16.15 on Linux peterpdactyl):

**Comment by zbjornson** [comment]
Two possible solutions to try: https://github.com/jansmolders86/mediacenterjs/issues/191#issuecomment-202340822
https://github.com/jansmolders86/mediacenterjs/issues/191#issuecomment-317437604
