### ISSUE TITLE
Canvas 2.9.1: Context.createLinearGradient not working

### ISSUE THREAD

**Issue by anhnh12** [Automattic/node-canvas#2043]
## Issue or Feature
- [x] Context.createLinearGradient() working no more after upgrading to `2.9.1` from `2.8.0`. The background just fell back to `black`. Gradient background still working fine with `2.9.0`

## Your Environment
* Version of node-canvas: 2.9.1
* Environment: node v16.15.0 on MacOS Monterey 12.2

**Comment by zbjornson** [comment]
Can you provide a complete, reproducible example please?

**Comment by anhnh12** [comment]
@zbjornson this following single block of code produces two different result with 2 different version (check 2 attachments).

```
const gradientFrom = "rgba(53,83,192,0.9)"
const gradientTo = "rgba(58,69,110,0.5)"
const canvas = Canvas.createCanvas(width, height)
const ctx = canvas.getContext("2d")
const gradient = ctx.createLinearGradient(0, 0, 0, 400)
gradient.addColorStop(0, gradientFrom)
gradient.addColorStop(1, gradientTo)
```
### Canvas 2.9.1
![image](https://user-images.githubusercontent.com/34529672/172893107-49d8a27d-936f-4dba-908b-80602af5ebc7.png)

### Canvas 2.9.0
![image](https://user-images.githubusercontent.com/34529672/172893007-e5896618-f777-45cb-87b6-92b15907d43a.png)

**Comment by zbjornson** [comment]
I'm getting the correct (gradient, not solid black) behavior in 2.8.0, and 2.9.1. I also don't see any changes that would be likely to have caused this. This is the code I used:

```js
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext("2d");
const gradientFrom = "rgba(53,83,192,0.9)"
const gradientTo = "rgba(58,69,110,0.5)"
const gradient = ctx.createLinearGradient(0, 0, 0, 400)
gradient.addColorStop(0, gradientFrom)
gradient.addColorStop(1, gradientTo)
ctx.fillStyle = gradient;
ctx.fillRect(0, 0, 200, 200);
```
![image](https://user-images.githubusercontent.com/469365/188295581-307bd625-c858-4d59-ae41-393e000c6851.png)

Are you still encountering this issue?

**Comment by zbjornson** [comment]
Closing without more info, but will reopen if you're still encountering this.
