### ISSUE TITLE
Installation Stuck

### ISSUE THREAD

**Issue by Neotastisch** [Automattic/node-canvas#2046]
## Issue

Installation Stuck:
![image](https://user-images.githubusercontent.com/54811660/171442389-8ef1db4b-82a1-4d27-a852-ba4dd92f10ee.png)

## Steps to Reproduce

```js
npm install canva
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): None
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Latest version on ubuntu 10

**Comment by zbjornson** [comment]
There's not enough info here to troubleshoot. If the issue is still happening, can you include the `--verbose` flag?
