### ISSUE TITLE
createPattern always uses "repeat"

### ISSUE THREAD

**Issue by calvinsomething** [Automattic/node-canvas#2049]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

`ctx.createPattern` always uses "repeat" repetition value. It is easy to get around this just by filling to the width/height of a single image impression, but I imagine there are cases where it could be useful to have the proper repetition behaviour. Or at least update the function to reflect that limitation.

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
ctx.fillStyle = ctx.createPattern(someImage, "repeat-x"); // or "repeat-y"
ctx.fillRect(0, 0, canvas.width, canvas.height);
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas 2.9.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v16.11.1 on 5.10.16.3-microsoft-standard-WSL2

**Comment by LinusU** [comment]
ref: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createPattern

**Comment by calvinsomething** [comment]
I can take this issue if that's okay.

**Comment by calvinsomething** [comment]
I traced the repeat options back to [here](https://github.com/freedesktop/pixman/blob/d93ec5713821106df6d57952dcf169308c7c4f0e/pixman/pixman-image.c#L675-L685). Looks like whatever solution there is to this issue, it won't be consistent with the other pattern creations.

Here's what the failing test looks like anyway.
![image](https://user-images.githubusercontent.com/73667022/174462063-0349c60e-8092-4bb4-be2f-bb330b2f0f1a.png)
