### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by FlloooDev** [Automattic/node-canvas#2050]
Hey, i've noticed a documentation error for https://github.com/Automattic/node-canvas/wiki/Installation:-Windows. The upper download for Cairo win64 works, but the bottom one doesn't.

**Comment by LinusU** [comment]
Both links works for me, but the bottom one was using `http` instead of `https`. It might have been a temporary SSL error, or it's something with your computer. Is your date/clock set correctly?

I've updated the entire page to only link to `https` sites now
