### ISSUE TITLE
Not able to install via NPM

### ISSUE THREAD

**Issue by eliezercazares** [Automattic/node-canvas#2052]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

When running "npm install canvas" it is not installed and errors are printed to console.

eliezer.cazares@Eliezers-PW-MacBook-Pro socketio-loadtesting % npm install canvas
npm ERR! code 1
npm ERR! path /Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/Cellar/node/18.2.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.2.0 | darwin | x64
npm ERR! node-pre-gyp info check checked for "/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@18.2.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.2.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.2.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/eliezer.cazares/Library/Caches/node-gyp/18.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/eliezer.cazares/Library/Caches/node-gyp/18.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/eliezer.cazares/Library/Caches/node-gyp/18.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/18.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas
npm ERR! gyp ERR! node -v v18.2.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/18.2.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/Cellar/node/18.2.0/bin/node" "/Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/eliezer.cazares/Desktop/load-testing-convos/socketio-loadtesting/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v18.2.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eliezer.cazares/.npm/_logs/2022-06-14T20_50_44_950Z-debug-0.log
eliezer.cazares@Eliezers-PW-MacBook-Pro socketio-loadtesting % 

## Steps to Reproduce

run "npm install canvas"

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
node v18.2 MacOS 11.6.3

I am ok going through the manual compile myself, but it does not seem like a fix.

**Comment by jensechu** [comment]
Same issue.
* macOS Big Sur `11.6.1 (20G224)`

```
# This file contains the result of Yarn building a package (canvas@npm:2.9.1)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@18.3.0 | darwin | x64
node-pre-gyp info check checked for "/Users/jensen/repos/bangya/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@18.3.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz ```

**Comment by eliezercazares** [comment]
> Same issue.
> 
> * macOS Big Sur `11.6.1 (20G224)`
> 
> ```
> # This file contains the result of Yarn building a package (canvas@npm:2.9.1)
> # Script name: install
> 
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@1.0.9
> node-pre-gyp info using node@18.3.0 | darwin | x64
> node-pre-gyp info check checked for "/Users/jensen/repos/bangya/node_modules/canvas/build/Release/canvas.node" (not found)
> node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz
> node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz 
> node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@18.3.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
> node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-darwin-unknown-x64.tar.gz ```
> ```

I've tried compiling manually as per the guide, but didn't work for me. I will have to look for another dependency it seems.

**Comment by glend1** [comment]
same. windows 11 here.

**Comment by bgoblirsch** [comment]
Same error while installing
macOS Monterey version 12.0.1 (21A559)

**Comment by zbjornson** [comment]
We don't have prebuilds available yet for Node 18, and unfortunately a lot has to happen to make them, see #2025. Until then, this module has to be built from source following https://github.com/Automattic/node-canvas#compiling. If you have troubles compiling, please open a separate issue.

**Comment by ljs19923** [comment]
> We don't have prebuilds available yet for Node 18, and unfortunately a lot has to happen to make them, see #2025. Until then, this module has to be built from source following https://github.com/Automattic/node-canvas#compiling. If you have troubles compiling, please open a separate issue.

Did you find a solution?

**Comment by TaslimOseni** [comment]
Co-ask.
