### ISSUE TITLE
Big text to go on next line.

### ISSUE THREAD

**Issue by Technology-King** [Automattic/node-canvas#2059]
Have a look at the image
![Music-Image](https://user-images.githubusercontent.com/106079266/174783267-0d380aef-4798-48cc-9c9b-922f603e68f2.png)

In the image, you can see that the text (Music Name) has many characters which is making the text to go out of the canvas, I want big name to break and go on next line. Please help me how to do it.

```js
// All the comments given below is for your information.

const Canvas = require("canvas");
Canvas.registerFont('./American Captain.ttf', { family: 'American Captain' });

const canvas = Canvas.createCanvas(700, 250);
const context = canvas.getContext("2d");

const background = await Canvas.loadImage("./Now-Playing.jpg");
const img = await Canvas.loadImage(track.thumbnail); // This is defined

context.drawImage(background, 0, 0, canvas.width, canvas.height);


context.font = '35px "American Captain"';

context.fillStyle = "#ffffff";

context.fillText(`${track.title}  [${millisToDuration(track.duration)}]`, canvas.width, 75, canvas.width); // This is also defined
context.fillText(client.user.tag, 27, 250); // This is also defined

context.drawImage(img, 25, 25, 200, 200);
```

* Version of node-canvas is latest i.e. 2.9.1
* Environment node.js v16.14.2 using Replit for Discord Bot.

**Comment by zbjornson** [comment]
See #1077 - this module mirrors the HTML5 Canvas API, and text wrapping isn't part of that unfortunately. There are some other approaches, like the ones in https://stackoverflow.com/questions/2936112/text-wrap-in-a-canvas-element.
