### ISSUE TITLE
Backstage installation on mac cpu-features node-gyp

### ISSUE THREAD

**Issue by lalit774** [Automattic/node-canvas#2060]
## Issue or Feature
Try to install backstage on Mac with npx @backstage/create-app.

Bug:

Error: Could not execute command yarn install

It seems that something went wrong when creating the app 🤔

🔥  Failed to create app!

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/225961/174893899-df24dd2e-490a-41d5-bde5-eda9e1ee3335.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/225961/174893943-f654cc37-f234-4894-b9d7-4258c7e460ef.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/225961/174893987-1e0deb77-671e-48ff-8bf2-92ab522ba472.png">

## Steps to Reproduce
In terminal 
npx @backstage/create-app

## Your Environment
Node Version: v16.13.0
Yarn Version: 1.22.17
NPM Version: 8.1.4
OS: MacBook Pro (13-inch, M1, 2020)

**Comment by zbjornson** [comment]
This repository is for node-canvas. Please open this in the backstage/create-app repo instead.
