### ISSUE TITLE
drawImage not working

### ISSUE THREAD

**Issue by ThanoFish** [Automattic/node-canvas#2068]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

ctx.drawImage does nothing. I tried filling the canvas and that works, so it's not an issue with the entire package only with drawImage

## Steps to Reproduce

```js
const { createCanvas, loadImage } = require("canvas");

const canvas = createCanvas(480, 60);
const ctx = canvas.getContext('2d');
    
loadImage('./abfeb3afcb784aaf9966e64d59fb6035.jpg').then(image => {
ctx.drawImage(image, 0, 0, 480, 60);
    });
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.9.3
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v16.13.2 on Ubuntu 20.04.2 LTS x86_64

**Comment by zbjornson** [comment]
If you run `node -p "require('canvas')"`, is there a value for `jpegVersion`? Your version might not have been built with libjpeg, in which case it will be `undefined`. If it is defined, can you provide the image?

**Comment by zbjornson** [comment]
If you're using `img.src="..."`, make sure to add an `img.onerror` handler, and if you're using `loadImage(src)`, make sure you're catching promise rejections.

If those don't elucidate the issue, can you share the image that isn't loading along with your exact code please?

**Comment by DatGamerAgainYT** [comment]
```js
const fs = require('fs');
const { createCanvas, loadImage } = require('canvas');

const canvas = createCanvas(1000, 750);
const ctx = canvas.getContext('2d');

loadImage('objectbubble.jpg').then((image) => {
  ctx.drawImage(image, 0, 0, 1000, 750)
})

const out = fs.createWriteStream(__dirname + '/TMP.png');
const stream = canvas.createPNGStream();
stream.pipe(out);
```

**Comment by zbjornson** [comment]
The last three lines need to be in the `.then()` also, otherwise they're not waiting for the image to be loaded.

**Comment by DatGamerAgainYT** [comment]
It's PNG counterpart also does not work. (Yes, these are both in my project's folder.
![objectbubble](https://user-images.githubusercontent.com/43687968/178805314-7459f385-a0c8-4359-b65a-3af3e2577ccf.png)
)

**Comment by DatGamerAgainYT** [comment]
> The last three lines need to be in the `.then()` also, otherwise they're not waiting for the image to be loaded.
I feel stupid for not noticing this. It works now.

**Comment by ThanoFish** [comment]
I figured it out (finally). At least in my case, the issue was fixed by changing
```js
loadImage('./abfeb3afcb784aaf9966e64d59fb6035.jpg').then(image => {
ctx.drawImage(image, 0, 0, 480, 60);
    });
```
to
```js
const image = await loadImage('./abfeb3afcb784aaf9966e64d59fb6035.jpg')
ctx.drawImage(image, 0, 0, 480, 60);
```

I don't really understand why this happened, as I never had such issue (even when using `.then()`) in other projects. But it works now so I'm not complaining.
