### ISSUE TITLE
toDataURL "error while writing to output stream" when width = 0 and height = 0

### ISSUE THREAD

**Issue by katspaugh** [Automattic/node-canvas#207]
Hi!

When you create a canvas with the width of 0 and height of 0, you get the following error later when calling `toBuffer`,  `toDataURL` and other exporting methods:

```
/usr/local/lib/node_modules/canvas/lib/canvas.js:190
    return prefix + this.toBuffer().toString('base64');
                     ^
Error: error while writing to output stream
    at Canvas.toDataURL (/usr/local/lib/node_modules/canvas/lib/canvas.js:190:26)
```

How to reproduce:

```
$ brew install cairo
$ npm install -g canvas    

var Canvas = require('canvas');
var canvas = new Canvas(0, 0); // this is the culprit
canvas.toDataURL();
```

Versions:

node v0.8.4
node-canvas v0.13.1

**Comment by pawlufelice** [comment]
I get roughly the same error because I don't draw anything on the canvas. I believe the `toBuffer()` might be returning `undefined`. That's what happening in my case anyway
