### ISSUE TITLE
drawImage is not shown on canvas

### ISSUE THREAD

**Issue by neronim1141** [Automattic/node-canvas#2086]
## Issue
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Im trying to combine 4 100x100px tiles into one, by scaling each of them down to 50x50px
the problem i noticed is that even though i get correct image data from loadImage , it is not drawed on canvas, and i get buffer with empty image; 

## Steps to Reproduce
```js
const canvas = createCanvas(100, 100);
const ctx = canvas.getContext("2d");

const img = await loadImage("data:image/png;base64," + getTileBase64());
ctx.drawImage(img, x * 50, y * 50, 50, 50);
console.log(canvas.toBuffer().toString("base64"))
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):2.9.3
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v16.13.1 on Windows 11

**Comment by zbjornson** [comment]
Can you provide an example of what `getTileBase64()` returns so I can try to reproduce this?

**Comment by neronim1141** [comment]
I was using fs.promise.readFile to get file buffer and i was saving it into my database as base64,
so getTileBase64 was just getting the string from database
unfortunatelly i lost that code so i cant provide you exactly was was there
in the end im saving the buffer directly in database
and after using sharp to resize it im creating imageData and finnaly used ` ctx.putImageData`  instead
