### ISSUE TITLE
Build canvas-v2.9.3-node-v72-linux-glibc-arm.tar.gz is missing

### ISSUE THREAD

**Issue by fumil** [Automattic/node-canvas#2093]
Build canvas-v2.9.3-node-v72-linux-glibc-arm.tar.gz  is missing from release library while npm tries to use it:

> canvas@2.9.3 install /home/pi/.node-red/node_modules/canvas
2022-08-14T19:15:58.271Z [out] > node-pre-gyp install --fallback-to-build --update-binary
2022-08-14T19:15:58.271Z [out] 
2022-08-14T19:15:59.159Z [err] node-pre-gyp
2022-08-14T19:15:59.160Z [err]  ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v72-linux-glibc-arm.tar.gz 

Tried to install node-red-contrib-chart-image 1.1.0 on NodeRed v2.2.2 on Raspbian OS

**Comment by tachun** [comment]
I got the same issue here.
```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@16.17.0 | darwin | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v93-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v93-darwin-unknown-arm64.tar.gz 
```
## Environment
macOS 12.5.1
node -v v16.17.0
npm -v 8.18.0
"canvas": "^2.9.3"

**Comment by Stanzilla** [comment]
> npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v108-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v108-linux-glibc-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.3 and node@18.7.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v108-linux-glibc-x64.tar.gz

**Comment by GICodeWarrior** [comment]
Hi @fumil, @tachun, per the [Troubleshooting Guide](https://github.com/Automattic/node-canvas/issues/1511) (linked in the new issue template), "Prebuilds aren't available for ARM".  Please read the troubleshooting guide for more information.

@Stanzilla, your error doesn't appear to be ARM related (like the other two above), but still, the troubleshooting guide is the best place to start.

**Comment by fumil** [comment]
@GICodeWarrior, thanks so much. I apologize for wasting your time.
