### ISSUE TITLE
Image data is corrupted when reusing canvas

### ISSUE THREAD

**Issue by GICodeWarrior** [Automattic/node-canvas#2098]
## Issue

Image data is corrupted when reusing a canvas.

## Steps to reproduce

1. Fill a canvas with black.
2. Draw an image with transparency.
3. Output the canvas to PNG.
4. Repeat the above multiple times.

Script:
```
$ git clone https://github.com/GICodeWarrior/node-canvas-test.git
$ cd node-canvas-test
$ node.exe test.js
```

### Expected

Each PNG should represent a single image on a black background.

<img width="320" alt="Expected results" src="https://user-images.githubusercontent.com/19803/185767046-d908ebb3-56f6-4b2c-b64a-9ed18d631550.png">

### Actual

Each PNG is the combination of all previous images combined and on a black background.

<img width="330" alt="Actual results" src="https://user-images.githubusercontent.com/19803/185767043-e8323de5-c2de-491d-be60-0c9e729055d9.png">

## My Environment

```
$ npm ls | grep canvas@
└── canvas@2.9.3
```

```
$ node.exe --version
v16.16.0
```

```
$ systeminfo | grep -E '^OS [NV]'
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
```

Also reproduced on Ubuntu 20.04 with canvas@2.9.3 and node v10.19.0.

**Comment by GeekaholicLin** [comment]
I have met the same issue, and I found out the reason.

```js
const reuseCanvas = createCanvas(ICON_SIZE, ICON_SIZE);
for (let id = 0; id < 4; ++id) {
  hashIcon(reuseCanvas, `actual-${id}`, `${id}.png`);
}

for (let id = 0; id < 4; ++id) {
  const uniqueCanvas = createCanvas(ICON_SIZE, ICON_SIZE);
  hashIcon(uniqueCanvas, `expected-${id}`, `${id}.png`);
}
```

Because you use the same canvas instance, it will draw all the images in the same context.

Only creating new canvas each time (the second usage of your example) is correct

**Comment by LinusU** [comment]
This is indeed working as intended. You can create a new Canvas, or simply clear the one you have:

```js
context.clearRect(0, 0, canvas.width, canvas.height)
```

ref: https://stackoverflow.com/a/2142549/148072

**Comment by GeekaholicLin** [comment]
I'm so sorry about the misleading expain above. [This example](https://github.com/GICodeWarrior/node-canvas-test/blob/main/test.js) is a little different, and I have ignore the code `context.fillRect(0, 0, ICON_SIZE, ICON_SIZE)`, which will 'reset' the canvas context like `context.clearRect`.

Actually, in this example, you can use the same context and just add `await` to ensure the order of execution. For example:

```js
async function run() {
  const reuseCanvas = createCanvas(ICON_SIZE, ICON_SIZE);
  for (let id = 0; id < 4; ++id) {
    await hashIcon(reuseCanvas, `actual-${id}`, `${id}.png`);
  }
}

run();
```

There is no problem with using multiple different canvas instances, because all the canvas context are independent and there is no execution order problem

**Comment by LinusU** [comment]
Aha, I think I understand now. Is the problem basically that the following code can output a red png file?

```js
const { createCanvas } = require('canvas')

const canvas = createCanvas(100, 100)
const ctx = canvas.getContext('2d')

ctx.fillStyle = 'green'
ctx.fillRect(0, 0, 100, 100)

const out = fs.createWriteStream('test.png')
const png = canvas.createPNGStream()
png.pipe(out)

ctx.fillStyle = 'red'
ctx.fillRect(0, 0, 100, 100)
```

**Comment by GeekaholicLin** [comment]
> 

Yes, it is. Because `writePNG` is asynchronous, and it will read the latest canvas context when outputing the image. 

So we need to pay attention to the usage of the same canvas context for asynchronous operations

**Comment by GICodeWarrior** [comment]
Your suggestion fixes it @GeekaholicLin.  Thanks for taking a look.

https://github.com/GICodeWarrior/node-canvas-test/compare/main...fix?diff=split
