### ISSUE TITLE
Incompatible with AWS Lambda

### ISSUE THREAD

**Issue by iiLearner** [Automattic/node-canvas#2101]
## Issue or Feature
- [X] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Hi, I'm using image-merge package which uses node-canvas as a dependency for nodejs, while all this works just fine on my local windows machine, however uploading the same code onto my lambda function (using serverless framework) it does not, i have searched around and it seems to be build issue meaning the build i have on my windows machine gets uploaded by serverless and it is not compatible with the Amazon linux 2 machine used for the lambda.

So, obviously I had to create my own build for Amazon linux 2 and I did, following the guide [this guide](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Fedora-and-other-RPM-based-distributions), once i had my canvas folder created inside node_modules from the build, I copied the folder, and downloaded it onto my windows machine. Went into my project's node modules folder and deleted the canvas folder and replaced with the one i got from my linux machine and uploaded the function with serverless deploy command, that unfortunately does not seem to help either as i get the same error, am i missing something? thank you.

## Your Environment
* Version of node-canvas 2.9.3
* Environment AWS Lambda, node 14

**Comment by Torone** [comment]
Exactly the same problem here, the error Serverless returns is the following: `canvas.node: Module did not self-register`

**Comment by iiLearner** [comment]
The solution to my problem was compiling the binaries with the same node version as my lambda version.

**Comment by NicoHinderling** [comment]
@iiLearner what exactly did you run? I'm still bumping into this issue and I've made sure:
1. I'm running the same version of node as indicated in my serverless.yml
2. I ran `npm rebuild canvas --update-binary` and similarly tried wiping out and recreating my node_modules files a few times to no avail
