### ISSUE TITLE
Canvas can be used, but when using webpack to package canvas, an error of bindings.CanvasRenderingContext2dInit is not a function will be reported at runtime.

### ISSUE THREAD

**Issue by hys-c** [Automattic/node-canvas#2103]
## Issue or Feature
Canvas can be used, but when using webpack to package canvas, an error of bindings.CanvasRenderingContext2dInit is not a function will be reported at runtime.
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* canvas 2.7.0
* node v14.19.3

**Comment by ShaMan123** [comment]
Are you using webpack for a non web app?
Are you using `node-canvas` in the web?

I am confused.
Web has a native implementation. It makes no sense IMO using this one which is a solution for environments without a native implementation.
