### ISSUE TITLE
Module did not self-register: '...\node_modules\canvas\build\Release\canvas.node'

### ISSUE THREAD

**Issue by hys-c** [Automattic/node-canvas#2105]
## Issue or Feature
I want to pack node-canvas by webpack and no error when packing. But when I use the build product to run, the error Module did not self-register: '/home/byteide/workspace/bear-web-x/node_modules/canvas/build/Release/canvas.node' is reported.I tried to use node-loader, but to no avail。

## Steps to Reproduce

```js
// webpack config
config = {
// ...
    target: 'node',
    node: {
    __filename: false,
    __dirname: false,
  },
     externals: [nodeExternals({ allowlist: ["lodash-es"] }), 'canvas'],
}
// etc.
```

## Your Environment
canvas: 2.8.0
node 14.19.3
npm 6.14
python 2.7

**Comment by zbjornson** [comment]
It's unusual to use webpack for code run with Node.js. If you really want to do that, I think you have to use https://webpack.js.org/loaders/node-loader/.
