### ISSUE TITLE
this api don't have "filter"?

### ISSUE THREAD

**Issue by Lman-TW** [Automattic/node-canvas#2106]
## Issue or Feature

I'm using this API to make a simple game engine, but I can't seem to use the filter. I just saw a few reports. It seems that this API does not support the filter relationship. Will this function be added to node-canva in the future? ?

## Steps to Reproduce
```js
ctx.filter = 'blur(5px)'
ctx.drawImage(image)
```

## Your Environment
node-canvas: 2.9.3
node: v16.13.2
macOS: 10.15.7

**Comment by zbjornson** [comment]
Unfortunately we don't have that implemented, see #1063. It's not trivial to implement with cairo.
