### ISSUE TITLE
Issue installing Canvas on Windows 10 , node.js 16.14.2

### ISSUE THREAD

**Issue by SonaliBhatia** [Automattic/node-canvas#2107]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

pm ERR! code 1
npm ERR! path C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=C:\Program Files\Python310\python.exe --msvs_version=2017' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@16.14.2 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://btaps-graphviz-dev.wellsfargo.net/apmt_to_eagc_csvs/v2.9.1/canvas-v2.9.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://btaps-graphviz-dev.wellsfargo.net/apmt_to_eagc_csvs/v2.9.1/canvas-v2.9.1-node-v93-win32-unknown-x64.tar.gz failed, reason: unable to get local issuer certificate
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error request to https://btaps-graphviz-dev.wellsfargo.net/apmt_to_eagc_csvs/v2.9.1/canvas-v2.9.1-node-v93-win32-unknown-x64.tar.gz failed, reason: unable to get local issuer certificate
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.5 found at "C:\Program Files\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz failed, reason: write EPROTO 11344:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:110:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:538:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\U596718\\Documents\\linkurious-windows-v3.1.2\\linkurious-windows\\data\\plugins\\pngExportPOCNew.lke\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\U596718\\Documents\\linkurious-windows-v3.1.2\\linkurious-windows\\data\\plugins\\pngExportPOCNew.lke\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93" "--python=C:\\Program Files\\Python310\\python.exe" "--msvs_version=2017"
npm ERR! gyp ERR! cwd C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=C:\Program Files\Python310\python.exe --msvs_version=2017' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\U596718\\Documents\\linkurious-windows-v3.1.2\\linkurious-windows\\data\\plugins\\pngExportPOCNew.lke\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\U596718\Documents\linkurious-windows-v3.1.2\linkurious-windows\data\plugins\pngExportPOCNew.lke\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v16.14.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\U596718\AppData\Local\npm-cache\_logs\2022-09-01T19_35_24_808Z-debug-0.log

## Steps to Reproduce
<!npm install ca>nvas
```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): Canvas 2.9.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Windows 10

**Comment by zbjornson** [comment]
> `node-pre-gyp http GET https://btaps-graphviz-dev.wellsfargo.net/apmt_to_eagc_csvs/v2.9.1/canvas-v2.9.1-node-v93-win32-unknown-x64.tar.gz`

You appear to be behind a proxy. That should be a github.com URL. I don't have experience with proxies and npm, but hopefully that points you in the right direction.

**Comment by SonaliBhatia** [comment]
Could you please delete the issue 2107 completely from your github please, it contains information regarding my company and I have been identified as policy violator. Please delete issue 2107 ASAP and let me know.
Thanks,-Sonali Bhatia

    On Sunday, October 30, 2022 at 12:07:03 AM EDT, Zach Bjornson ***@***.***> wrote:  
 
 


Closed #2107 as completed.

**Comment by SonaliBhatia** [comment]
> 
> You appear to be behind a proxy. That should be a github.com URL. I don't have experience with proxies and npm, but hopefully that points you in the right direction.

**Comment by zbjornson** [comment]
@SonaliBhatia anyone can see edit history in GitHub issues, so editing it hasn't removed the information you want to delete.

I'm not an admin so I can't delete this issue. You could try reporting your top post and see if GitHub will delete it.

**Comment by SonaliBhatia** [comment]
@zbjornson thanks for quick turn around.

**Comment by SonaliBhatia** [comment]
@zbjornson I am unable to report issue since it is my issue. Could you please report it and ask Admins to delete it by letting them know it contains sensitive information. Thanks for your help!!
