### ISSUE TITLE
Canvas Module didn't register

### ISSUE THREAD

**Issue by parasop** [Automattic/node-canvas#2108]
![image](https://user-images.githubusercontent.com/63485824/188262962-e1bb42b1-fb16-4106-948b-79e010313cc1.png)

when i am lauching my node code in multiple process i am getting this error

**Comment by zbjornson** [comment]
This is probably #1394. Multiple processes should be fine (e.g. the `node:cluster` module), but multiple threads (e.g. node workers) aren't possible right now.
