### ISSUE TITLE
context.imageSmoothingEnabled isn't implemented

### ISSUE THREAD

**Issue by buschtoens** [Automattic/node-canvas#211]
``` javascript
var resolution = 100;

var img = new Image();
img.src = someBuffer;

var canvas = new Canvas(resolution, resolution),
    ctx = canvas.getContext("2d");

ctx.imageSmoothingEnabled = false;
ctx.drawImage(img, 8, 8, 8, 8, 0, 0, resolution, resolution);
```

This code crops and scales up the image `img` to 100px x 100px. The resulting image should not be antialiased, since `ctx.imageSmoothingEnabled = false`. But sadly it's aliased. [`context.imageSmoothingEnabled`](http://dev.w3.org/html5/2dcontext/#image-smoothing) is part of the spec. Chrome and Firefox already adapted with a vendorized version.

Please implement this property, since I don't know how. Porbably [this line](https://github.com/LearnBoost/node-canvas/blob/master/src/CanvasRenderingContext2d.cc#L670) has to be slightly altered and the accessor needs to be added [somewhere here](https://github.com/LearnBoost/node-canvas/blob/master/src/CanvasRenderingContext2d.cc#L135).

**Comment by asturur** [comment]
I do think `imageSmoothingEnabled` should be implemented and i would like to work on it.
any thoughts?

**Comment by zbjornson** [comment]
Yes, it should work like browsers do. PRs welcome!

**Comment by asturur** [comment]
i think we should close this

**Comment by zbjornson** [comment]
Since #1233, thanks @asturur!
