### ISSUE TITLE
v2.9.0 `addColorStop` with opacity 0

### ISSUE THREAD

**Issue by ShaMan123** [Automattic/node-canvas#2111]
## Issue or Feature
Issue, might be related to #2043

## Steps to Reproduce

Add a color stop with opacity 0,
The opacity is ignored and treated as 1

```js
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext("2d");
const gradientFrom = "rgba(53,83,192,0.9)"
const gradientTo = "rgba(58,69,110,0)" // opacity 0
const gradient = ctx.createLinearGradient(0, 0, 0, 400)
gradient.addColorStop(0, gradientFrom)
gradient.addColorStop(1, gradientTo)
ctx.fillStyle = gradient;
ctx.fillRect(0, 0, 200, 200);
// etc.
```
[![Edit heuristic-sea-kfk9w0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-sea-kfk9w0?fontsize=14&hidenavigation=1&theme=dark)

see output for corresponding opacity
![image](https://user-images.githubusercontent.com/34343793/188936422-2463c24c-c0cb-4e0c-a421-81c3c5cfa78e.png)

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.9.0+
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):  node v16.14.2 on Windows 10 64bit

**Comment by ShaMan123** [comment]
Tested on v2.8.0 and it works as expected

**Comment by H3r3zy** [comment]
Will be corrected in 2.10.1 https://github.com/Automattic/node-canvas/pull/2110

**Comment by zbjornson** [comment]
v2.10.1 is out, thanks for the fix @H3r3zy

**Comment by ShaMan123** [comment]
Thanks guys!
