### ISSUE TITLE
No loader is configured for ".node" files: node_modules/canvas/build/Release/canvas.node

### ISSUE THREAD

**Issue by Aarbel** [Automattic/node-canvas#2112]
Hi canvas team, 
I've got this error in my since around ~24 hours.
How can i fix it ? 

Thanks a lot

`No loader is configured for ".node" files: node_modules/canvas/build/Release/canvas.node`

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/25119847/188988626-c30279d7-5d75-4e67-8d31-780b046627a4.png">

**Comment by PoMkaNik** [comment]
Any updates?

**Comment by zbjornson** [comment]
I think this is an esbuild thing, see https://github.com/evanw/esbuild/issues/1051 for recommendations.

**Comment by Aarbel** [comment]
Cf https://github.com/evanw/esbuild/issues/1051

**Comment by Aarbel** [comment]
problem was coming from native dependencies not well copied on lambdas and node modules.

I put an internal commit fix link here for maintance: https://github.com/Clovis-team/clovis-app/pull/2743/commits/5870451d94d8b1b8a6e981bbc37e211e26430a0c

**Comment by Aarbel** [comment]
Indeed the fix was with cdk

using `--loader:.node=file` solved but was hard to configurate

<img width="568" alt="image" src="https://user-images.githubusercontent.com/25119847/233170209-214a27d6-51d6-4b6e-9e01-dad5bc4c2968.png">

**Comment by giladrom** [comment]
Got this error when using `esbuild` to compile typescript code when deploying to AWS Lambda. Adding `--loader:.node=file` solved the issue for me.
