### ISSUE TITLE
Issue installing 2.10.1 on macOS with current stable node (18.9.1)

### ISSUE THREAD

**Issue by zaun** [Automattic/node-canvas#2122]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Can't download the pre-build binary.
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v108-darwin-unknown-x64.tar.gz

## Steps to Reproduce

```
npm install
```

## Your Environment
canvas: 2.10.1
node: v18.9.1
npm: 8.19.1
macOS: 12.5 (intel)

**Comment by CelesteCC** [comment]
**I had the same problem**
`node-pre-gyp ERR! install request to https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v83-darwin-unknown-x64.tar.gz failed, reason: connect ETIMEDOUT 52.69.186.44:443 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.10.1 and node@14.8.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error request to https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v83-darwin-unknown-x64.tar.gz failed, reason: connect ETIMEDOUT 52.69.186.44:443 
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp`

**Your Environment**
canvas: 2.10.1
node: v14.8.0
npm: 6.14.7
macOS: 12.5 (M1)

**Comment by Rohin-Chopra** [comment]
I had the same problem as well

`85 error command failed
386 error command sh -c node-pre-gyp install --fallback-to-build --update-binary
387 error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/rohinchopra/playground/nodejs-cloudword/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/rohinchopra/playground/nodejs-cloudword/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
388 error node-pre-gyp info it worked if it ends with ok
388 error node-pre-gyp info using node-pre-gyp@1.0.10
388 error node-pre-gyp info using node@16.13.1 | darwin | arm64
388 error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v93-darwin-unknown-arm64.tar.gz
388 error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v93-darwin-unknown-arm64.tar.gz
388 error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.10.1 and node@16.13.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
388 error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v93-darwin-unknown-arm64.tar.gz`

Your Environment
canvas: latest
node: v16.13.1
npm: 8.1.2
macOS: 12.5 (M1)

**Comment by zaun** [comment]
I am able to install node-canvas, if I also include node its:

`"dependencies": {
    "canvas": "^2.10.1",
    "node": "lts"
  }`

**Comment by LinusU** [comment]
We don't currently provide prebuilds for Node.js 18, see #2025 for status.

When it's falling back to building, the error tells you what's wrong:

> pkg-config: command not found gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp.

You need to follow the instructions here to install `pkg-config` and the required libraries:

https://github.com/Automattic/node-canvas#compiling
