### ISSUE TITLE
Vitest using JSDOM crashes on PhaserJS unit test

### ISSUE THREAD

**Issue by zewa666** [Automattic/node-canvas#2123]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

I'm using node-canvas through JSDOM in a Vitest where I'm trying to setup a PhaserJS game. The initial execution works perfectly but on a test-watcher rerun the execution crashes or, even worse, the terminal keeps hanging, on Ubuntu. On Windows it merely crashses all the time.

```bash
(process:16044): GLib-GObject-WARNING **: 19:29:39.729: cannot register existing type 'PangoFontMap'

(process:16044): GLib-GObject-WARNING **: 19:29:39.729: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(process:16044): GLib-GObject-CRITICAL **: 19:29:39.729: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:16044): GLib-CRITICAL **: 19:29:39.729: g_once_init_leave: assertion 'result != 0' failed

(process:16044): GLib-GObject-CRITICAL **: 19:29:39.729: g_type_register_static: assertion 'parent_type > 0' failed

(process:16044): GLib-GObject-WARNING **: 19:29:39.729: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(process:16044): GLib-GObject-CRITICAL **: 19:29:39.729: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:16044): GLib-CRITICAL **: 19:29:39.729: g_once_init_leave: assertion 'result != 0' failed

(process:16044): GLib-GObject-CRITICAL **: 19:29:39.729: g_type_register_static: assertion 'parent_type > 0' failed

(process:16044): GLib-GObject-WARNING **: 19:29:39.729: cannot register existing type 'PangoCairoFontMap'

```

## Steps to Reproduce
Here's a repro with instructions in the readme
https://github.com/zewa666/phaser-vitest-bug

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
2.10.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
node 16.17.0, Ubuntu 20_04
node 18.x Win 10

**Comment by zewa666** [comment]
when setting `isolate: false` it starts to work though this is more of a workaround. anyways, since I'm tbh not sure whether its Vitest, Phaser or Canvas causing the root issue I'll close this one.

**Comment by shuji-koike** [comment]
I came across the same problem using node-canvas with pdfjs-dist

sadly `isolate: false` did not work for me...
but, I kept reading the vitest document and found this!

> https://vitest.dev/config/#pool-1-0-0
> Some libraries written in native languages, such as Prisma, bcrypt and canvas, have problems when running in multiple threads and run into segfaults. In these cases it is advised to use forks pool instead.

and setting `pool: 'forks'` worked like a charm!

Anyways thanks for pointing out, saved my day!
