### ISSUE TITLE
 buildpack heroku/procfile@2.0.0 does not support stack heroku-18

### ISSUE THREAD

**Issue by Dhina-test** [Automattic/node-canvas#2125]
Hi  , In order build image we are creating pipeline in aws by official aws cloudformation template
 https://github.com/aws-containers/codepipeline-codebuild-buildpacks-example
 
 Upto last week worked fine , but today while we try to create image by buildpacks getting below error , can u help please,
 
![image](https://user-images.githubusercontent.com/78138014/192718357-a7497eea-0bf0-4b25-b258-54c1fad6b4ee.png)

**Comment by rwarbelow** [comment]
Hi @Dhina-test, I'm not sure what version of `pack` that you're using, but upgrading to 0.27.0 (https://github.com/buildpacks/pack/releases/download/v0.27.0/pack-v0.27.0-linux.tgz) worked for us.

**Comment by Dhina-test** [comment]
Thanks , working
