### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by wanggang1997** [Automattic/node-canvas#2136]
ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz

**Comment by Livijn** [comment]
I get the same error: 
> npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v93-darwin-unknown-arm64.tar.gz

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this. We don't have ARM prebuilds, so it has to be built from source.

**Comment by Livijn** [comment]
For me, running `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman` fixed it!

**Comment by memoev** [comment]
> For me, running `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman` fixed it!

@Livijn How did you come to this solution?
