### ISSUE TITLE
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v108-linux-glibc-x64.tar.gz

### ISSUE THREAD

**Issue by bdklahn** [Automattic/node-canvas#2139]
## Issue or Feature
- [X ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce

```bash
# in a Docker file, bootstrapping 
RUN npm install -g vega-lite vega-cli canvas
```

## Your Environment
[OpenSUSE Tumbleweed](https://hub.docker.com/r/opensuse/tumbleweed) bootstrapped via GH Docker build.

Can I assume this might simply be an issue with the latest Releases not being built against the/a newer version of nodejs ("node-v108")?
If so, when might that happen?

I can probably deduce/patch together the zypper package names I need for compile dependencies, by looking at the CentOS and maybe Ubuntu ones. I just thought I'd check here first, if there's a simpler way or pending update which could help.

**Comment by kwent** [comment]
Seeing same thing

**Comment by rivaslive** [comment]
The same here

**Comment by mpeltomaa** [comment]
Same here, this is annoying problem when deploying to Heroku etc.

**Comment by mpeltomaa** [comment]
Same here

**Comment by filipduch** [comment]
same here, while building on heroku node18

**Comment by imbkz** [comment]
Same here

**Comment by mattvb91** [comment]
Our builds started failing due to this package with no changes to our package or lock file. We have pinned versions of all our packages. This dep seems to come in from `jsdom` which in turn comes in from `jest-environment-jsdom`. Does anyone have any idea whats going on with this? Doesnt look like a new release was put out here

**Comment by zbjornson** [comment]
node-canvas v2.10.2 is now published with support for Node 18.
