### ISSUE TITLE
c1xx : fatal  error C1083: Cannot open source file: '..\src\backend\Backend.cc': No such file or directory

### ISSUE THREAD

**Issue by erqewee** [Automattic/node-canvas#2141]
Progress: resolved 277, reused 263, downloaded 12, added 273, done
node_modules/.pnpm/canvas@2.10.1/node_modules/canvas: Running install script, failed in 19.3s
.../canvas@2.10.1/node_modules/canvas install$ node-pre-gyp install --fallback-to-build --update-binary
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@1.0.10
│ node-pre-gyp info using node@20.0.0-nightly20221020b4efac4820 | win32 | x64
│ node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v111-win32-unknown-x64.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v111-win32-unknown-x64.tar.gz 
│ node-pre-gyp WARN Pre-built binaries not installable for canvas@2.10.1 and node@20.0.0-nightly20221020b4efac4820 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v111-win32-unknown-x64.tar.gz 
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.1.0
│ gyp info using node@20.0.0-nightly20221020b4efac4820 | win32 | x64
│ gyp info ok 
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.1.0
│ gyp info using node@20.0.0-nightly20221020b4efac4820 | win32 | x64
│ gyp info find Python using Python version 3.10.8 found at "C:\Python310\python.exe"
│ gyp info find VS using VS2022 (17.3.32825.248) found at:
│ gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
│ gyp info find VS run with --verbose for detailed information
│ gyp info spawn C:\Python310\python.exe
│ gyp info spawn args [
│ gyp info spawn args   'C:\\Users\\ceyhu\\AppData\\Local\\pnpm\\global\\5\\.pnpm\\pnpm@7.12.2\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'msvs',
│ gyp info spawn args   '-I',
│ gyp info spawn args   'H:\\Masaüstü\\Projelerim\\TypeScript\\Jris (Beta)\\node_modules\\.pnpm\\canvas@2.10.1\\node_modules\\canvas\\build\\config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   'C:\\Users\\ceyhu\\AppData\\Local\\pnpm\\global\\5\\.pnpm\\pnpm@7.12.2\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   'C:\\Users\\ceyhu\\AppData\\Local\\node-gyp\\Cache\\20.0.0-nightly20221020b4efac4820\\include\\node\\common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ceyhu\\AppData\\Local\\node-gyp\\Cache\\20.0.0-nightly20221020b4efac4820',
│ gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\ceyhu\\AppData\\Local\\pnpm\\global\\5\\.pnpm\\pnpm@7.12.2\\node_modules\\pnpm\\dist\\node_modules\\node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\ceyhu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.0.0-nightly20221020b4efac4820\\\\<(target_arch)\\\\node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=H:\\Masaüstü\\Projelerim\\TypeScript\\Jris (Beta)\\node_modules\\.pnpm\\canvas@2.10.1\\node_modules\\canvas',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'H:\\Masaüstü\\Projelerim\\TypeScript\\Jris (Beta)\\node_modules\\.pnpm\\canvas@2.10.1\\node_modules\\canvas\\build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info ok 
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.1.0
│ gyp info using node@20.0.0-nightly20221020b4efac4820 | win32 | x64
│ gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
│ gyp info spawn args [
│ gyp info spawn args   'build/binding.sln',
│ gyp info spawn args   '/clp:Verbosity=minimal',
│ gyp info spawn args   '/nologo',
│ gyp info spawn args   '/p:Configuration=Release;Platform=x64'
│ gyp info spawn args ]
│ Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
│   Copying C:/libjpeg-turbo64/bin/jpeg62.dll to H:\Masa�st�\Projelerim\TypeScript\Jris (Beta)\node_modules\.pnpm\canvas@2.10.1\node_modules\canvas\build\Release\
│           1 file(s) copied.
│   Backend.cc
│ c1xx : fatal  error C1083: Cannot open source file: '..\src\backend\Backend.cc': No such file or directory [H:\Masa�st�\Projelerim\TypeScript\Jris (Beta)\node_modules\.pnpm\canvas@2.10.1\node_modules\canvas\buil
│ gyp ERR! build error
│ gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onExit (C:\Users\ceyhu\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.12.2\node_modules\pnpm\dist\node_modules\node-gyp\lib\build.js:201:23)
│ gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
│ gyp ERR! System Windows_NT 10.0.25217
│ gyp ERR! command "C:\\Program Files\\NodeJS\\node.exe" "C:\\Users\\ceyhu\\AppData\\Local\\pnpm\\global\\5\\.pnpm\\pnpm@7.12.2\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
│ gyp ERR! cwd H:\Masaüstü\Projelerim\TypeScript\Jris (Beta)\node_modules\.pnpm\canvas@2.10.1\node_modules\canvas
│ gyp ERR! node -v v20.0.0-nightly20221020b4efac4820
│ gyp ERR! node-gyp -v v9.1.0
│ gyp ERR! not ok
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\NodeJS\node.exe C:\Users\ceyhu\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.12.2\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js build
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (H:\Masaüstü\Projelerim\TypeScript\Jris (Beta)\node_modules\.pnpm\@mapbox+node-pre-gyp@1.0.10\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
│ node-pre-gyp ERR! System Windows_NT 10.0.25217
│ node-pre-gyp ERR! command "C:\\Program Files\\NodeJS\\node.exe" "H:\\Masaüstü\\Projelerim\\TypeScript\\Jris (Beta)\\node_modules\\.pnpm\\@mapbox+node-pre-gyp@1.0.10\\node_modules\\@mapbox\\node-pre-gyp\\bin\\nod
│ node-pre-gyp ERR! cwd H:\Masaüstü\Projelerim\TypeScript\Jris (Beta)\node_modules\.pnpm\canvas@2.10.1\node_modules\canvas
│ node-pre-gyp ERR! node -v v20.0.0-nightly20221020b4efac4820
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.10
│ node-pre-gyp ERR! not ok
│ Failed to execute 'C:\Program Files\NodeJS\node.exe C:\Users\ceyhu\AppData\Local\pnpm\global\5\.pnpm\pnpm@7.12.2\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --update-bi
└─ Failed in 19.3s
 ELIFECYCLE  Command failed with exit code 1.

|----------------
> pnpm -v
- 7.12.2

> node -v
- v20.0.0-nightly20221020b4efac4820

**Comment by zbjornson** [comment]
node-canvas v2.10.2 is now published with support for Node 18 and 19.
