### ISSUE TITLE
canvas@2.7.0 still depend on `GLIBC_2.18`

### ISSUE THREAD

**Issue by fxxjdedd** [Automattic/node-canvas#2142]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Hi, I have read several issues, including [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511), but under centos7 and node16, `librsvg-2.so.2` in the prebuild used still depends on `GLIBC2.18`.

prebuild:
```
node-pre-gyp http GET https://cdn.npmmirror.com/binaries/canvas/v2.7.0/canvas-v2.7.0-node-v93-linux-glibc-x64.tar.gz
node-pre-gyp http 200 https://cdn.npmmirror.com/binaries/canvas/v2.7.0/canvas-v2.7.0-node-v93-linux-glibc-x64.tar.gz
```
error:
```
error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/admin/xxx/node_modules/_canvas@2.7.0@canvas/build/Release/librsvg-2.so.2)
```

## Steps to Reproduce

```js
var Canvas = require('canvas');
// etc.
```

## Your Environment
* Version of node-canvas (v2.7.0)
* Environment (node 16.17.1 & centos7)

**Comment by zbjornson** [comment]
It would take a lot of time to change the prebuild to use an older version of glibc, and Node 18+ doesn't support CentOS7, so the benefits wouldn't last for long. Best option is to build from source, sorry. https://github.com/Automattic/node-canvas#compiling
