### ISSUE TITLE
Canvas version 2.10.1 installs are trying to load an asset that isn't available

### ISSUE THREAD

**Issue by nels388** [Automattic/node-canvas#2147]
Hi All, when you get a chance, please take a look at this:

not found link used in the build of version 2.10.1 (node-v108-linux):

https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v108-linux-glibc-x64.tar.gz

the current working link (node-v102-linux):

https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v102-linux-glibc-x64.tar.gz

## Your Environment
* Version of node-canvas: 2.10.1
* Environment:   node v15.0.0

Additional Note: this build worked fine yesterday.

**Comment by zbjornson** [comment]
If it's trying to download v108, that's for Node 18. v102 is for Node 17. (If you're using nvm, make sure you're actually using the version you think you are.)

node-canvas v2.10.2 is now published with support for Node 18.

**Comment by nels388** [comment]
Great, Thanks for the help, Much Appreciated.
