### ISSUE TITLE
having issue when installing canvas on latest LTS (v18.12.0)

### ISSUE THREAD

**Issue by Idris1401** [Automattic/node-canvas#2148]
## Issue
- https://sourceb.in/s2MLedXE1i

## Steps to Reproduce

```sh
npm i canvas@latest
```

## Your Environment
* None
* Environment : Node.js v18.12.0 on Debian 11

**Comment by LinusU** [comment]
> /bin/sh: 1: pkg-config: not found

Did you install [the prerequisites for your os](https://github.com/Automattic/node-canvas#compiling)?

**Comment by Idris1401** [comment]
> > /bin/sh: 1: pkg-config: not found
> 
> Did you install [the prerequisites for your os](https://github.com/Automattic/node-canvas#compiling)?

that was the issue. thanks!
