### ISSUE TITLE
Using with Node v18.12.1 and Electron v21.0.1 getting the Error: Compiled against a different Node.js version using NODE_MODULE_VERSION 108. The version of Node.js requires NODE_MODULE_VERSION 109.

### ISSUE THREAD

**Issue by GitMurf** [Automattic/node-canvas#2156]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

As the title says, I am getting the error: `Compiled against a different Node.js version using NODE_MODULE_VERSION 108. The version of Node.js requires NODE_MODULE_VERSION 109.`

I know this has been discussed many times in the past but I have tried all the suggested solutions and have read all of the applicable GitHub Issues, installation guides etc. and no luck.

![image](https://user-images.githubusercontent.com/64155612/200407767-f54c7857-df79-4fdb-a717-24ad0273ba0a.png)

## Steps to Reproduce

In my hello world Electron app I simply have the following at the top and it gives the error.

```js
const { createCanvas, loadImage } = require('canvas');
```

## Your Environment
* Version of node-canvas: `2.10.2`
* Environment: `Node 18.12.1 + Electron 21.0.1 + Windows 11`

I am simply using the current LTS version of Node (18.12.1) as well as the current Stable version of Electron (21.0.1).

**Comment by LinusU** [comment]
`NODE_MODULE_VERSION` 108 is Node.js 18.x, and Node.js 19.x is 111.

Which version are you using? 🤔 

ref: https://nodejs.org/en/download/releases/

**Comment by GitMurf** [comment]
1. Also @LinusU is it odd that Electron is using NODE_MODULE_VERSION 109 when it isn't even listed in node.js releases?
2. Because node-canvas doesn't have a prebuilt for 109 does that make it virtually impossible for us to make it compatible with Electron at this point?

**Comment by GitMurf** [comment]
> edit: just saw in the title that you are using electron, this is not something that we support right now, but if there are instructions on how to make it work we'd be happy to add it

@LinusU after further troubleshooting I was finally able to get node-canvas to work with Electron with some workarounds. But after deep diving into several different issues along the way, and now finally running into a crash using node-canvas getting the error `[7088:1111/085132.471:ERROR:crashpad_client_win.cc(844)]` I have been led to believe that there are several issues with node-canvas relying on `nan`. Below are some of the key issues / explanations I have gathered from elsewhere.

https://github.com/cmake-js/cmake-js/issues/222#issuecomment-722275887
https://github.com/Automattic/node-canvas/issues/1868#issuecomment-963274832
https://github.com/nodejs/nan/issues/922#issuecomment-947721784
https://github.com/electron/electron/issues/29893
https://github.com/Automattic/node-canvas/issues/1868#issuecomment-997719275

Is this something you have looked into / thought about? (switching away from usage of `nan`)
Any advice?

Thanks!

**Comment by GitMurf** [comment]
@LinusU here is another good explanation of the issue. It seems the issue is using `nan` instead of `node-api` (napi). Is this something you all would consider? This is a huge problem because of how popular Electron is getting and because so many packages / libraries depend on node-canvas (like pdf.js). https://github.com/nodejs/nan/issues/892#issuecomment-876966930

Thanks in advance! I have been trying to figure out a workaround for weeks now and no luck and I see a bunch of chatter from others with same issues.

**Comment by GitMurf** [comment]
Also see here: https://github.com/nodejs/nan/issues/922#issuecomment-974779085

**Comment by DarkSynx** [comment]
do not neglect : npx electron-builder install-app-deps
a different version may be compiled without your consent
