### ISSUE TITLE
执行命令 brew install pkg-config cairo pango libpng jpeg giflib librsvg 出现不支持macOS 13

### ISSUE THREAD

**Issue by BILLFuYiWei** [Automattic/node-canvas#2157]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/67575144/200517466-aedb4a9a-17ec-41aa-976d-33407bd11469.png">

brew install pkg-config cairo pango libpng jpeg giflib librsvg

You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

**Comment by LinusU** [comment]
This warning is emitted by Brew, not Canvas. I'm not sure what you want us to do?

**Comment by LinusU** [comment]
> I saw in the documentation that installing canvas needs to install these packages. Do you need these packages to use canvas? If so, is there any other way to install canvas on macOS?

Depending on your platform and Node.js version, there might be pre-builds available. E.g. if you are running macOS and Node.js 16.x I think we should have prebuilds available.

Otherwise you do need those packages.
