### ISSUE TITLE
Can't Install.

### ISSUE THREAD

**Issue by reggi** [Automattic/node-canvas#217]
I am having a hard time installing canvas.

	thomas@workstation:~/Desktop/holstground$ sudo npm install canvas
	Password:
	npm info it worked if it ends with ok
	npm info using npm@1.1.61
	npm info using node@v0.8.6
	npm WARN invalid config registry=""
	npm WARN invalid config Must be a full url with 'http://'
	npm info trying registry request attempt 1 at 02:19:29
	npm http GET https://registry.npmjs.org/canvas
	npm http 304 https://registry.npmjs.org/canvas
	npm info install canvas@0.13.1 into /Users/thomas/Desktop/holstground
	npm info installOne canvas@0.13.1
	npm info /Users/thomas/Desktop/holstground/node_modules/canvas unbuild
	npm info preinstall canvas@0.13.1
	npm info build /Users/thomas/Desktop/holstground/node_modules/canvas
	npm info linkStuff canvas@0.13.1
	npm info install canvas@0.13.1
	
	> canvas@0.13.1 install /Users/thomas/Desktop/holstground/node_modules/canvas
	> node-gyp rebuild
	
	gyp info it worked if it ends with ok
	gyp info using node-gyp@0.6.8
	gyp info using node@0.8.6 | darwin | x64
	gyp info spawn python
	gyp info spawn args [ '/Users/thomas/.node-gyp/0.8.6/tools/gyp/gyp',
	gyp info spawn args   'binding.gyp',
	gyp info spawn args   '-f',
	gyp info spawn args   'make',
	gyp info spawn args   '-I',
	gyp info spawn args   '/Users/thomas/Desktop/holstground/node_modules/canvas/build/config.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/Users/thomas/.node-gyp/0.8.6/common.gypi',
	gyp info spawn args   '-Dlibrary=shared_library',
	gyp info spawn args   '-Dvisibility=default',
	gyp info spawn args   '-Dnode_root_dir=/Users/thomas/.node-gyp/0.8.6',
	gyp info spawn args   '-Dmodule_root_dir=/Users/thomas/Desktop/holstground/node_modules/canvas',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn make
	gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
	  CXX(target) Release/obj.target/canvas/src/Canvas.o
	In file included from ../src/Canvas.cc:8:
	../src/Canvas.h:19:25: warning: cairo/cairo.h: No such file or directory
	../src/Canvas.cc:15:29: warning: cairo/cairo-pdf.h: No such file or directory
	In file included from ../src/Canvas.cc:8:
	../src/Canvas.h:63: error: ‘cairo_status_t’ has not been declared
	../src/Canvas.h:79: error: ISO C++ forbids declaration of ‘cairo_surface_t’ with no type
	../src/Canvas.h:79: error: ‘cairo_surface_t’ declared as an ‘inline’ field
	../src/Canvas.h:79: error: expected ‘;’ before ‘*’ token
	../src/Canvas.h:80: error: expected `;' before ‘inline’
	../src/Canvas.h:88: error: ISO C++ forbids declaration of ‘cairo_surface_t’ with no type
	../src/Canvas.h:88: error: expected ‘;’ before ‘*’ token
	../src/Canvas.h: In member function ‘uint8_t* Canvas::data()’:
	../src/Canvas.h:81: error: ‘_surface’ was not declared in this scope
	../src/Canvas.h:81: error: ‘cairo_image_surface_get_data’ was not declared in this scope
	../src/Canvas.h: In member function ‘int Canvas::stride()’:
	../src/Canvas.h:82: error: ‘_surface’ was not declared in this scope
	../src/Canvas.h:82: error: ‘cairo_image_surface_get_stride’ was not declared in this scope
	In file included from ../src/CanvasRenderingContext2d.h:13,
	                 from ../src/Canvas.cc:9:
	../src/CanvasGradient.h: At global scope:
	../src/CanvasGradient.h:21: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type
	../src/CanvasGradient.h:21: error: ‘cairo_pattern_t’ declared as an ‘inline’ field
	../src/CanvasGradient.h:21: error: expected ‘;’ before ‘*’ token
	../src/CanvasGradient.h:23: error: expected `;' before ‘private’
	../src/CanvasGradient.h:26: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type
	../src/CanvasGradient.h:26: error: expected ‘;’ before ‘*’ token
	In file included from ../src/Canvas.cc:9:
	../src/CanvasRenderingContext2d.h:30: error: ‘cairo_filter_t’ does not name a type
	../src/CanvasRenderingContext2d.h:31: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type
	../src/CanvasRenderingContext2d.h:31: error: expected ‘;’ before ‘*’ token
	../src/CanvasRenderingContext2d.h:32: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type
	../src/CanvasRenderingContext2d.h:32: error: expected ‘;’ before ‘*’ token
	../src/CanvasRenderingContext2d.h:33: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type
	../src/CanvasRenderingContext2d.h:33: error: expected ‘;’ before ‘*’ token
	../src/CanvasRenderingContext2d.h:34: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type
	../src/CanvasRenderingContext2d.h:34: error: expected ‘;’ before ‘*’ token
	../src/CanvasRenderingContext2d.h:130: error: ‘cairo_t’ has not been declared
	../src/CanvasRenderingContext2d.h:131: error: ISO C++ forbids declaration of ‘cairo_t’ with no type
	../src/CanvasRenderingContext2d.h:131: error: ‘cairo_t’ declared as an ‘inline’ field
	../src/CanvasRenderingContext2d.h:131: error: expected ‘;’ before ‘*’ token
	../src/CanvasRenderingContext2d.h:132: error: expected `;' before ‘inline’
	../src/CanvasRenderingContext2d.h:136: error: ‘cairo_surface_t’ has not been declared
	../src/CanvasRenderingContext2d.h:137: error: expected ‘,’ or ‘...’ before ‘(’ token
	../src/CanvasRenderingContext2d.h:137: error: ‘fn’ has incomplete type
	../src/CanvasRenderingContext2d.h:137: error: invalid use of ‘void’
	../src/CanvasRenderingContext2d.h:157: error: ISO C++ forbids declaration of ‘cairo_t’ with no type
	../src/CanvasRenderingContext2d.h:157: error: expected ‘;’ before ‘*’ token
	../src/CanvasRenderingContext2d.h:158: error: ISO C++ forbids declaration of ‘cairo_path_t’ with no type
	../src/CanvasRenderingContext2d.h:158: error: expected ‘;’ before ‘*’ token
	../src/CanvasRenderingContext2d.h: In member function ‘void Context2d::setContext(int*)’:
	../src/CanvasRenderingContext2d.h:130: error: ‘_context’ was not declared in this scope
	In file included from ../src/Canvas.cc:16:
	../src/closure.h: At global scope:
	../src/closure.h:22: error: ‘cairo_status_t’ does not name a type
	../src/closure.h:29: error: ‘cairo_status_t’ does not name a type
	In file included from ../src/Canvas.cc:19:
	../src/JPEGStream.h:100: error: variable or field ‘write_to_jpeg_stream’ declared void
	../src/JPEGStream.h:100: error: ‘cairo_surface_t’ was not declared in this scope
	../src/JPEGStream.h:100: error: ‘surface’ was not declared in this scope
	../src/JPEGStream.h:100: error: expected primary-expression before ‘int’
	../src/JPEGStream.h:100: error: expected primary-expression before ‘int’
	../src/JPEGStream.h:100: error: expected primary-expression before ‘*’ token
	../src/JPEGStream.h:100: error: ‘closure’ was not declared in this scope
	make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
	gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
	gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
	gyp ERR! System Darwin 11.4.2
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /Users/thomas/Desktop/holstground/node_modules/canvas
	gyp ERR! node -v v0.8.6
	gyp ERR! node-gyp -v v0.6.8
	gyp ERR! not ok 
	npm info canvas@0.13.1 Failed to exec install script
	npm info /Users/thomas/Desktop/holstground/node_modules/canvas unbuild
	npm info preuninstall canvas@0.13.1
	npm info uninstall canvas@0.13.1
	npm info postuninstall canvas@0.13.1
	npm ERR! canvas@0.13.1 install: `node-gyp rebuild`
	npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
	npm ERR! 
	npm ERR! Failed at the canvas@0.13.1 install script.
	npm ERR! This is most likely a problem with the canvas package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls canvas
	npm ERR! There is likely additional logging output above.
	
	npm ERR! System Darwin 11.4.2
	npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
	npm ERR! cwd /Users/thomas/Desktop/holstground
	npm ERR! node -v v0.8.6
	npm ERR! npm -v 1.1.61
	npm ERR! code ELIFECYCLE
	npm ERR! 
	npm ERR! Additional logging details can be found in:
	npm ERR!     /Users/thomas/Desktop/holstground/npm-debug.log
	npm ERR! not ok code 0		thomas@workstation:~/Desktop/holstground$ sudo npm install canvas		Password:		npm info it worked if it ends with ok		npm info using npm@1.1.61		npm info using node@v0.8.6		npm WARN invalid config registry=""		npm WARN invalid config Must be a full url with 'http://'		npm info trying registry request attempt 1 at 02:19:29		npm http GET https://registry.npmjs.org/canvas		npm http 304 https://registry.npmjs.org/canvas		npm info install canvas@0.13.1 into /Users/thomas/Desktop/holstground		npm info installOne canvas@0.13.1		npm info /Users/thomas/Desktop/holstground/node_modules/canvas unbuild		npm info preinstall canvas@0.13.1		npm info build /Users/thomas/Desktop/holstground/node_modules/canvas		npm info linkStuff canvas@0.13.1		npm info install canvas@0.13.1				> canvas@0.13.1 install /Users/thomas/Desktop/holstground/node_modules/canvas		> node-gyp rebuild				gyp info it worked if it ends with ok		gyp info using node-gyp@0.6.8		gyp info using node@0.8.6 | darwin | x64		gyp info spawn python		gyp info spawn args [ '/Users/thomas/.node-gyp/0.8.6/tools/gyp/gyp',		gyp info spawn args   'binding.gyp',		gyp info spawn args   '-f',		gyp info spawn args   'make',		gyp info spawn args   '-I',		gyp info spawn args   '/Users/thomas/Desktop/holstground/node_modules/canvas/build/config.gypi',		gyp info spawn args   '-I',		gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',		gyp info spawn args   '-I',		gyp info spawn args   '/Users/thomas/.node-gyp/0.8.6/common.gypi',		gyp info spawn args   '-Dlibrary=shared_library',		gyp info spawn args   '-Dvisibility=default',		gyp info spawn args   '-Dnode_root_dir=/Users/thomas/.node-gyp/0.8.6',		gyp info spawn args   '-Dmodule_root_dir=/Users/thomas/Desktop/holstground/node_modules/canvas',		gyp info spawn args   '--depth=.',		gyp info spawn args   '--generator-output',		gyp info spawn args   'build',		gyp info spawn args   '-Goutput_dir=.' ]		gyp info spawn make		gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]		CXX(target) Release/obj.target/canvas/src/Canvas.o		In file included from ../src/Canvas.cc:8:		../src/Canvas.h:19:25: warning: cairo/cairo.h: No such file or directory		../src/Canvas.cc:15:29: warning: cairo/cairo-pdf.h: No such file or directory		In file included from ../src/Canvas.cc:8:		../src/Canvas.h:63: error: ‘cairo_status_t’ has not been declared		../src/Canvas.h:79: error: ISO C++ forbids declaration of ‘cairo_surface_t’ with no type		../src/Canvas.h:79: error: ‘cairo_surface_t’ declared as an ‘inline’ field		../src/Canvas.h:79: error: expected ‘;’ before ‘*’ token		../src/Canvas.h:80: error: expected `;' before ‘inline’		../src/Canvas.h:88: error: ISO C++ forbids declaration of ‘cairo_surface_t’ with no type		../src/Canvas.h:88: error: expected ‘;’ before ‘*’ token		../src/Canvas.h: In member function ‘uint8_t* Canvas::data()’:		../src/Canvas.h:81: error: ‘_surface’ was not declared in this scope		../src/Canvas.h:81: error: ‘cairo_image_surface_get_data’ was not declared in this scope		../src/Canvas.h: In member function ‘int Canvas::stride()’:		../src/Canvas.h:82: error: ‘_surface’ was not declared in this scope		../src/Canvas.h:82: error: ‘cairo_image_surface_get_stride’ was not declared in this scope		In file included from ../src/CanvasRenderingContext2d.h:13,		               from ../src/Canvas.cc:9:		../src/CanvasGradient.h: At global scope:		../src/CanvasGradient.h:21: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type		../src/CanvasGradient.h:21: error: ‘cairo_pattern_t’ declared as an ‘inline’ field		../src/CanvasGradient.h:21: error: expected ‘;’ before ‘*’ token		../src/CanvasGradient.h:23: error: expected `;' before ‘private’		../src/CanvasGradient.h:26: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type		../src/CanvasGradient.h:26: error: expected ‘;’ before ‘*’ token		In file included from ../src/Canvas.cc:9:		../src/CanvasRenderingContext2d.h:30: error: ‘cairo_filter_t’ does not name a type		../src/CanvasRenderingContext2d.h:31: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type		../src/CanvasRenderingContext2d.h:31: error: expected ‘;’ before ‘*’ token		../src/CanvasRenderingContext2d.h:32: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type		../src/CanvasRenderingContext2d.h:32: error: expected ‘;’ before ‘*’ token		../src/CanvasRenderingContext2d.h:33: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type		../src/CanvasRenderingContext2d.h:33: error: expected ‘;’ before ‘*’ token		../src/CanvasRenderingContext2d.h:34: error: ISO C++ forbids declaration of ‘cairo_pattern_t’ with no type		../src/CanvasRenderingContext2d.h:34: error: expected ‘;’ before ‘*’ token		../src/CanvasRenderingContext2d.h:130: error: ‘cairo_t’ has not been declared		../src/CanvasRenderingContext2d.h:131: error: ISO C++ forbids declaration of ‘cairo_t’ with no type		../src/CanvasRenderingContext2d.h:131: error: ‘cairo_t’ declared as an ‘inline’ field		../src/CanvasRenderingContext2d.h:131: error: expected ‘;’ before ‘*’ token		../src/CanvasRenderingContext2d.h:132: error: expected `;' before ‘inline’		../src/CanvasRenderingContext2d.h:136: error: ‘cairo_surface_t’ has not been declared		../src/CanvasRenderingContext2d.h:137: error: expected ‘,’ or ‘...’ before ‘(’ token		../src/CanvasRenderingContext2d.h:137: error: ‘fn’ has incomplete type		../src/CanvasRenderingContext2d.h:137: error: invalid use of ‘void’		../src/CanvasRenderingContext2d.h:157: error: ISO C++ forbids declaration of ‘cairo_t’ with no type		../src/CanvasRenderingContext2d.h:157: error: expected ‘;’ before ‘*’ token		../src/CanvasRenderingContext2d.h:158: error: ISO C++ forbids declaration of ‘cairo_path_t’ with no type		../src/CanvasRenderingContext2d.h:158: error: expected ‘;’ before ‘*’ token		../src/CanvasRenderingContext2d.h: In member function ‘void Context2d::setContext(int*)’:		../src/CanvasRenderingContext2d.h:130: error: ‘_context’ was not declared in this scope		In file included from ../src/Canvas.cc:16:		../src/closure.h: At global scope:		../src/closure.h:22: error: ‘cairo_status_t’ does not name a type		../src/closure.h:29: error: ‘cairo_status_t’ does not name a type		In file included from ../src/Canvas.cc:19:		../src/JPEGStream.h:100: error: variable or field ‘write_to_jpeg_stream’ declared void		../src/JPEGStream.h:100: error: ‘cairo_surface_t’ was not declared in this scope		../src/JPEGStream.h:100: error: ‘surface’ was not declared in this scope		../src/JPEGStream.h:100: error: expected primary-expression before ‘int’		../src/JPEGStream.h:100: error: expected primary-expression before ‘int’		../src/JPEGStream.h:100: error: expected primary-expression before ‘*’ token		../src/JPEGStream.h:100: error: ‘closure’ was not declared in this scope		make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1		gyp ERR! build error 		gyp ERR! stack Error: `make` failed with exit code: 2		gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)		gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)		gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)		gyp ERR! System Darwin 11.4.2		gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"		gyp ERR! cwd /Users/thomas/Desktop/holstground/node_modules/canvas		gyp ERR! node -v v0.8.6		gyp ERR! node-gyp -v v0.6.8		gyp ERR! not ok 		npm info canvas@0.13.1 Failed to exec install script		npm info /Users/thomas/Desktop/holstground/node_modules/canvas unbuild		npm info preuninstall canvas@0.13.1		npm info uninstall canvas@0.13.1		npm info postuninstall canvas@0.13.1		npm ERR! canvas@0.13.1 install: `node-gyp rebuild`		npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1		npm ERR! 		npm ERR! Failed at the canvas@0.13.1 install script.		npm ERR! This is most likely a problem with the canvas package,		npm ERR! not with npm itself.		npm ERR! Tell the author that this fails on your system:		npm ERR!     node-gyp rebuild		npm ERR! You can get their info via:		npm ERR!     npm owner ls canvas		npm ERR! There is likely additional logging output above.				npm ERR! System Darwin 11.4.2		npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"		npm ERR! cwd /Users/thomas/Desktop/holstground		npm ERR! node -v v0.8.6		npm ERR! npm -v 1.1.61		npm ERR! code ELIFECYCLE		npm ERR! 		npm ERR! Additional logging details can be found in:		npm ERR!     /Users/thomas/Desktop/holstground/npm-debug.log		npm ERR! not ok code 0]

**Comment by wonderdogone** [comment]
I built this (node-gyp rebuild) and then included in my node V12.6 project and can confirm canvas now working back as normal. Thanks for this.

**Comment by LinusU** [comment]
Fixed by #574
