### ISSUE TITLE
Doesn't play nice with macpors (where files are in /opt/local/include)

### ISSUE THREAD

**Issue by Zugwalt** [Automattic/node-canvas#218]
Used macports to install cairo and that worked fine until 0.8.

Now when I go to install/update canvas I get error cannot find cairo.h

Went through steps your provided that installed versions of cairo and pixman to /usr/local/include but then install would die on not being able to find lib_gif.h. Tried both linking to version in /opt/local/include and downloading giflib source and installing in /usr/local/include but with no luck.

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
