### ISSUE TITLE
issue when installing and launching with node

### ISSUE THREAD

**Issue by Youritch** [Automattic/node-canvas#2183]
The install was completed with no issue but when launching my js code it's didn't work.

It's seam that is not a arm64 version that has been install.

## Steps to Reproduce
```
brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman
```
Error : 
```
node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/youri/node_modules/canvas/build/Release/canvas.node, 0x0001): tried: '/Users/youri/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/youri/node_modules/canvas/build/Release/canvas.node' (no such file), '/Users/youri/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/youri/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

## Your Environment
* node : 18.12.1
* MAC M1 (13.0.1)

**Comment by flohall** [comment]
Have you just upgraded to node 18? Then try npm rebuild. Or try deleting all node_modules and run npm i --build-from-source.

Or make sure your node has actually the correct architecture. I for example had a similar error some days ago, where I used my nvm installed node (arm) to install canvas, but used Intellijs node (amd64) to run the code. After starting my code from console the issue went away.

**Comment by Youritch** [comment]
I think I don't have the right architecture but how I choose the one I want ?
or where ?
i juste installe as it mark in the readme.dm

**Comment by flohall** [comment]
How do you run your code? With like `node index.js` or something? In this case the following command should give you the architecture of the node you use for your runtime. Which will be probably 'arm64' in your case.

`node -p "process.arch"` this should tell the version

Try to use the same node (if you have multiple ones installed to run `npm i`). I am not sure how you switch between node version, but lets say you use nvm (node version managers). Then set a node version with `nvm use` in your current console. Reinstall all your node dependencies. Then run your code in the same console.

It seemed that my issues was the opposite of yours:
```
Error: dlopen(/Users/flohall.xx/workspaces/vm-rendering-backend/node_modules/canvas/build/Release/canvas.node, 0x0001): tried: '/Users/flohall.xx/workspaces/vm-rendering-backend/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/florian.hallay/workspaces/vm-rendering-backend/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

```

In my case I can see it like this:

I run

    nvm use v14.17.6
    node -p "process.arch"
    
    >> x64
    
Then I run:

    nvm use v14.18.1
    node -p "process.arch"
    
    >> arm64

**Comment by Youritch** [comment]
I run with ```node index.js```. and yes I have an arm64,.
Do i install nvm ? because I don't use it, use npm ?
may I uninstall all canvas stuff (how?, already try ```npm uninstall canvas```

**Comment by flohall** [comment]
nvm is a tool to install/switch between different node versions. For people that develop in many different repositories at the same time.
If you wanna use it you could for example deinstall node and npm. Install nvm instead. Then use nvm to install a node version (or multiple ones you like). Every node version in nvm has also npm in a specific version attached.

So in my case I can use:
```
nvm use v14.18.1
npm install --build-from-source
node index.js
```

Nvm will switch to a specific node version and a specific version of npm. The install script must be executed with same architecture as the runtime script.

Thing is M1 CPUs support two architectures for many applications (also for node as it seems) and it seems you can install node in a way (that is supports either amd64 or arm64).

**Comment by Youritch** [comment]
ok, i had uninstall node and npm, install nvm, re-build from source
but same error.
So i uninstall canvas with brew and re-insatll canvas with brew.
But I have the same error....

**Comment by flohall** [comment]
why do you install canvas via brew? do you mean canvas itself or just the canvas dependencies - I just installed the dependencies via brew. I install canvas via npm. `npm i canvas --build-from-source`

**Comment by Youritch** [comment]
i installe dependencies with brew because it that was write in the readme file.
```npm i canvas --build-from-source``` work, thanks for all.
