### ISSUE TITLE
node-pre-gyp http 404 https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v111-darwin-unknown-x64.tar.gz

### ISSUE THREAD

**Issue by SymbolStar** [Automattic/node-canvas#2188]
Hello,
I've a problem with  canvas.

When installing the dependencies (yarn install),
node-pre-gyp try to download your Pre-built binaries, but failed due to a file that not exist (404).
## Issue or Feature
```
[5/5] 🔨  Building fresh packages...
[-/12] ⠠ waiting...
[10/12] ⠠ canvas
[12/12] ⠠ fsevents
[11/12] ⠠ electron-typings
error /Users/symbolstar/Microsoft/client_skypex_skype4life/clients/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/symbolstar/Microsoft/client_skypex_skype4life/clients/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@19.4.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/Users/symbolstar/Microsoft/client_skypex_skype4life/clients/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v111-darwin-unknown-x64.tar.gz
node-pre-gyp http 404 https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v111-darwin-unknown-x64.tar.gz
```

## Steps to Reproduce

```js
package.json -> "canvas": "2.7.0",
yarn install
```

## Your Environment
* Version of node-canvas @2.7.0
* Environment (e.g. node 19.4.0 on Mac OS X 13.1):

**Comment by anyu** [comment]
Hit the same on MacOS 13.1 Ventura, but `node-canvas 2.9.0` + `node 19.13.0` + `npm 9.2.0`.

The solution from the [docs](https://github.com/Automattic/node-canvas#compiling) that seemed to work for [others](https://github.com/Automattic/node-canvas/issues/2025#issuecomment-1321135561) (`brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`) didn't work for me while still on `node v19`.

However, both of these worked for me:

a) downgrading to `node v18` with the above packages OR 
b) downgrading to `node v14` (specifically `node 14.19.3`, `npm 8.10`) without needing those extra packages

**Comment by thepian** [comment]
Thank you for the node downgrade suggestion

**Comment by zbjornson** [comment]
v2.11.2 was the first version of node-canvas to support node 19+.
