### ISSUE TITLE
symbol not found in flat namespace '_cairo_fill' M1 chip

### ISSUE THREAD

**Issue by cynosureabu** [Automattic/node-canvas#2192]
## Issue or Feature
cannot start server 
node v18.13.0
npm 8.19.3
MacOS 13.0 

Already installed Cairo separately (brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman)
npm i canvas succeeded, but when start server, it throws error:

node:internal/modules/cjs/loader:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(canvas/build/Release/canvas.node, 0x0001): symbol not found in flat namespace '_cairo_fill'
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1302:18)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (node_modules/canvas/index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/utils.js:160:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js:463:14)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (node_modules/pirates/lib/index.js:136:24) {
  code: 'ERR_DLOPEN_FAILED'
}

This is log for install:
> canvas@2.11.0 install boiler/node_modules/canvas
> node-pre-gyp install --fallback-to-build --update-binary

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-darwin-unknown-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.0 and node@18.13.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-darwin-unknown-arm64.tar.gz
(node:84975) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
In file included from ../src/backend/Backend.cc:1:
../src/backend/Backend.h:60:14: warning: private field 'backend' is not used [-Wunused-private-field]
    Backend* backend;
             ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
  CXX(target) Release/obj.target/canvas/src/Backends.o
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc:2494:11: warning: enumeration values 'TEXT_ALIGNMENT_START' and 'TEXT_ALIGNMENT_LEFT' not handled in switch [-Wswitch]
  switch (state->textAlignment) {
          ^~~~~~~~~~~~~~~~~~~~
../src/CanvasRenderingContext2d.cc:2494:11: note: add missing switch cases
  switch (state->textAlignment) {
          ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/closure.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
../src/Image.cc:1196:3: warning: 'rsvg_handle_get_dimensions' is deprecated: Use 'rsvg_handle_get_intrinsic_size_in_pixels' instead [-Wdeprecated-declarations]
  rsvg_handle_get_dimensions(_rsvg, dims);
  ^
/usr/local/Cellar/librsvg/2.55.1/include/librsvg-2.0/librsvg/rsvg.h:705:1: note: 'rsvg_handle_get_dimensions' has been explicitly marked deprecated here
RSVG_DEPRECATED_FOR(rsvg_handle_get_intrinsic_size_in_pixels)
^
/usr/local/Cellar/librsvg/2.55.1/include/librsvg-2.0/librsvg/rsvg.h:50:32: note: expanded from macro 'RSVG_DEPRECATED_FOR'
#define RSVG_DEPRECATED_FOR(f) G_DEPRECATED_FOR(f) RSVG_API
                               ^
/usr/local/Cellar/glib/2.74.5/include/glib-2.0/glib/gmacros.h:1211:44: note: expanded from macro 'G_DEPRECATED_FOR'
#define G_DEPRECATED_FOR(f) __attribute__((__deprecated__("Use '" #f "' instead")))
                                           ^
../src/Image.cc:1235:24: warning: 'rsvg_handle_render_cairo' is deprecated: Use 'rsvg_handle_render_document' instead [-Wdeprecated-declarations]
  gboolean render_ok = rsvg_handle_render_cairo(_rsvg, cr);
                       ^
/usr/local/Cellar/librsvg/2.55.1/include/librsvg-2.0/librsvg/rsvg-cairo.h:87:1: note: 'rsvg_handle_render_cairo' has been explicitly marked deprecated here
RSVG_DEPRECATED_FOR(rsvg_handle_render_document)
^
/usr/local/Cellar/librsvg/2.55.1/include/librsvg-2.0/librsvg/rsvg.h:50:32: note: expanded from macro 'RSVG_DEPRECATED_FOR'
#define RSVG_DEPRECATED_FOR(f) G_DEPRECATED_FOR(f) RSVG_API
                               ^
/usr/local/Cellar/glib/2.74.5/include/glib-2.0/glib/gmacros.h:1211:44: note: expanded from macro 'G_DEPRECATED_FOR'
#define G_DEPRECATED_FOR(f) __attribute__((__deprecated__("Use '" #f "' instead")))
                                           ^
2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/register_font.o
  SOLINK_MODULE(target) Release/canvas.node
ld: warning: directory not found for option '-L/opt/homebrew/lib'
ld: warning: ignoring file /usr/local/Cellar/cairo/1.16.0_5/lib/libcairo.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/libpng/1.6.39/lib/libpng16.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/pango/1.50.12/lib/libpangocairo-1.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/pango/1.50.12/lib/libpango-1.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/pixman/0.42.2/lib/libpixman-1.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/glib/2.74.5/lib/libglib-2.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/glib/2.74.5/lib/libgobject-2.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/librsvg/2.55.1/lib/librsvg-2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/opt/freetype/lib/libfreetype.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/libgif.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/opt/gettext/lib/libintl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/glib/2.74.5/lib/libgio-2.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/harfbuzz/6.0.0_1/lib/libharfbuzz.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/jpeg-turbo/2.1.4/lib/libjpeg.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/gdk-pixbuf/2.42.10/lib/libgdk_pixbuf-2.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):─ canvas@2.11.0
* Environment: MacOS 13.0 M1 node18

**Comment by jtw-r** [comment]
Having the same issue on an M2 chip

**Comment by jtw-r** [comment]
*sigh*

After about a week of troubleshooting, I've resolved the issue for myself.

For me personally, it was multiple small problems all cascading into one. I recently just upgraded my Macbook from an Intel x64 chip to Apple's arm64--probably like many of you. I restored my new computer from a backup, which I'm suspecting "incorrectly" copied over my NVM and Homebrew setup.

The first thing I did was uninstall the x64 node version I had previously and install a clean copy of Node v.18.6 with arm64 support.
Ensured it was built for arm64 by running: `file $(which node)`. You should see "NODE PATH: **Mach-O 64-bit executable arm64**"

Then, I installed Homebrew in the correct `/opt/homebrew` folder. Added this folder to my zsh path too

Then I ran `arch -arm64 brew install pkg-config cairo pango libpng jpeg giflib librsvg`, and exported all of the path variables it brought up during the install.

In my repo I uninstalled canvas via NPM, deleted the `node_modules/` directory at the root of my project, then **restarted my computer**, and finally ran `npm i -D canvas`.

All errors went away! I'm hoping this helps someone else

**Comment by victor141516** [comment]
@jtw-r I did what you said and sadly it didn't work. I also removed arm64 Homebrew and installed again. Also didn't work.

Can you attach your compiled `canvas.node`? So that I can at least work 😅

**Comment by nabati** [comment]
I'll just add what resolved this issue for me as well: 

Similar to what others have said, likely my issues have been due to restoring a backup of my computer when transitioning to an M1. 

In my case, what ended up happening was that I had two versions of Brew installed, one for x86 and one for arm64, and it's not clear what was being installed where when I was running the installation commands. 

What eventually solved this for me was: 
1. Run the brew uninstaller multiple times, install all brew instances and their packages. Check website for command.
2. Reinstall brew. 
3. Remove node_modules and run `yarn cache clean`. 
4. Reinstall dependencies (`yarn`)

**Comment by billkabanga** [comment]
Phew After a couple of hours troubleshooting the same issue, [This ](https://github.com/Automattic/node-canvas/issues/2192#issuecomment-1499520296) got me unblocked. Thanks @jtw-r .

**Comment by aokrushk** [comment]
I removed and reinstalled nvm, node, npm packages, brew and its packages - pretty much all I could. What I was missing was this recommendation:

> and exported all of the path variables it brought up during the install.

https://github.com/Automattic/node-canvas/issues/2192#issuecomment-1499520296

Thanks @jtw-r !

**Comment by rahuljustbaat** [comment]
> `arch -arm64 brew install pkg-config cairo pango libpng jpeg giflib librsvg`, and exported all of the path variables it brought up during the install.



> @jtw-r I did what you said and sadly it didn't work. I also removed arm64 Homebrew and installed again. Also didn't work.
> 
> Can you attach your compiled `canvas.node`? So that I can at least work 😅
> 
> Edit: A co-worker sent me his working `canvas.node` and it worked! I attach it for anyone having the same problem. I also attach the one that my computer build just in case it helps to debug this issue. (Rename any of them to `canvas.node` to make it work)
> 
> [canvas.node.bad.txt](https://github.com/Automattic/node-canvas/files/11934567/canvas.node.bad.txt) [canvas.node.good.txt](https://github.com/Automattic/node-canvas/files/11934568/canvas.node.good.txt)

which file to use?
Also I am getting more errors if I use the good.txt one
 node:internal/modules/cjs/loader:1460
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/rahulkathuria/Documents/justbaat/layerhub-renderer/node_modules/.pnpm/canvas@2.11.2_encoding@0.1.13/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: /opt/homebrew/opt/pixman/lib/libpixman-1.0.dylib
  Referenced from: <C9FBC6F7-DD7F-3588-B0AD-732589B6DABB> /Users/rahulkathuria/Documents/justbaat/layerhub-renderer/node_modules/.pnpm/canvas@2.11.2_encoding@0.1.13/node_modules/canvas/build/Release/canvas.node
  Reason: tried: '/opt/homebrew/opt/pixman/lib/libpixman-1.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/pixman/lib/libpixman-1.0.dylib' (no such file), '/opt/homebrew/opt/pixman/lib/libpixman-1.0.dylib' (no such file), '/usr/local/lib/libpixman-1.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/usr/lib/libpixman-1.0.dylib' (no such file, not in dyld cache)
    at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/rahulkathuria/Documents/justbaat/layerhub-renderer/node_modules/.pnpm/canvas@2.11.2_encoding@0.1.13/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by yuri-scarbaci-lenio** [comment]
Proposed solution above didn't work per se BUT `jtw-r` was spot on on the root analysis

I already had
```
arch -arm64 brew install pkg-config cairo pango libpng jpeg giflib librsvg
```
as well as 
```
arch -arm64 brew install python-setuptools
```
(which is required too)

BUT the issues in my scenarios where mainly 2:
 - I never ran `arch -arm64 zsh` which ensures all the commands I run in my zsh terminal are properly communicated the architecture my computer should favour
 - I used `pnpm env` to install and manage my node versions, but because I failed to set my desired architecture pre-installation, pnpm env installed x86_x64 of node
 
 hence
 ```
 file $(which node)
 ```
 was saying x86_x64
 
 
 
### My solution (given I use `pnpm env` and `pnpm .sh` way to install pnpm) was:
1 - `rm -rf $PNPM_HOME` to complete remove any pnpm from my machine
2 - `arch -arm64 zsh` to operate in arm64 mode from now on
3 - `curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=9.7.1 sh -` to install pnpm `9.7.1` (you can change the version if you need another one)
4 - `pnpm env use --global 22` (I use node 22, but you can change it as fit per your scenario)

if everything went correctly 
 ```
 file $(which node)
 ```
 should now properly say `executable arm64`
 
 
 From this point forward you should be able to complete any dev flow by doing a clean install of the project ( keep package-lock, remove node_modules, run `pnpm i`/`npm i` )


If you use `nvm` or other node version manager, the key to find a solution here is making sure
 ```
 file $(which node)
 ```
says `executable arm64` (given you already have all the build tools in you machine properly installed and part of your PATH )

**Comment by imtns** [comment]
> _sigh_
> 
> After about a week of troubleshooting, I've resolved the issue for myself.
> 
> For me personally, it was multiple small problems all cascading into one. I recently just upgraded my Macbook from an Intel x64 chip to Apple's arm64--probably like many of you. I restored my new computer from a backup, which I'm suspecting "incorrectly" copied over my NVM and Homebrew setup.
> 
> The first thing I did was uninstall the x64 node version I had previously and install a clean copy of Node v.18.6 with arm64 support. Ensured it was built for arm64 by running: `file $(which node)`. You should see "NODE PATH: **Mach-O 64-bit executable arm64**"
> 
> Then, I installed Homebrew in the correct `/opt/homebrew` folder. Added this folder to my zsh path too
> 
> Then I ran `arch -arm64 brew install pkg-config cairo pango libpng jpeg giflib librsvg`, and exported all of the path variables it brought up during the install.
> 
> In my repo I uninstalled canvas via NPM, deleted the `node_modules/` directory at the root of my project, then **restarted my computer**, and finally ran `npm i -D canvas`.
> 
> All errors went away! I'm hoping this helps someone else

You're truly my lifesaver! I've already wasted 5-6 hours on this issue... Thank you so much!

**Comment by jamesandres** [comment]
Note for anyone else who didn't catch it on the first pass. In @jtw-r's comment above:

> Then, I installed Homebrew in the correct /opt/homebrew folder.

That means completely uninstall and reinstall homebrew. The reason is your homebrew is likely configured to use Rosetta and `x86_64`.
