### ISSUE TITLE
Get Canvas from Context

### ISSUE THREAD

**Issue by DARK-ECNELIS** [Automattic/node-canvas#2198]
Yep

I would like to know how I can retrieve the canvas from the context given that `context.canvas` no longer exists?

**Comment by zbjornson** [comment]
It should still work:
```
> c = createCanvas(1,1)
[Canvas 1x1]
> ctx = c.getContext('2d')
CanvasRenderingContext2D { canvas: [Canvas 1x1] }
> ctx.canvas
[Canvas 1x1]
```

**Comment by DARK-ECNELIS** [comment]
Hummm, well there is no `canvas` property in `CanvasRenderingContext2D` type. This is probably not a problem for Js but for Ts we don't have access to it

**Comment by SZOKOZ** [comment]
I concur. The type definition in this repository is not up to date and I have it frequently conflicting with the one typescript provides.
`TS2740: Type 'CanvasRenderingContext2D' is missing the following properties from type 'CanvasRenderingContext2D': canvas, getContextAttributes, isPointInStroke, createConicGradient, and 5 more.`

**Comment by ZeLonewolf** [comment]
I am also running into this issue.

**Comment by ZeLonewolf** [comment]
I've been using this fairly ugly hack to get around the error for now:
```typescript
  createGraphics(bounds: Bounds): CanvasRenderingContext2D {
    let canvas = createCanvas(bounds.width, bounds.height, this._type);
    let ctx = canvas.getContext("2d");
    (ctx as any).canvas = canvas;
    return ctx as any as CanvasRenderingContext2D;
  }
```
However, this seems to _sometimes_ be producing weird side effects where canvas tries to create a browser-based canvas rather than a headless one.

**Comment by zbjornson** [comment]
This is fixed in master, we just need to make a release.
@ZeLonewolf there's no need to assign `ctx.canvas`; it exists already, it's just missing from the Typescript types.

**Comment by zymotik** [comment]
Hey @zbjornson , when is the next release scheduled please? Thanks

**Comment by zbjornson** [comment]
v2.11.2 is out with this fix. The other missing properties are not supported by node-canvas.

**Comment by ljttl3q04t** [comment]
@nvhuy5  You save my day sir 🚀🚀🚀

**Comment by omkrk** [comment]
Faced similar issue for canvas-2.11.2. For typescript the workaround is as below -

`encoder.addFrame(ctx as any);`
