### ISSUE TITLE
Release new version including fonts fixes from January

### ISSUE THREAD

**Issue by flohall** [Automattic/node-canvas#2206]
## Request for release
Could you please provide a release version including the last fonts fixes from January.

Please include commits:
fdf709a7b08abae33a93c510b96f71df6c13c7b0
4c276e07f570ee6a727f88dcc67251823895c671

Background:
We have just switched our container from Amazon Linux 2 to Debian 12 to fix some issues with librsvg. But not only librsvg, but also pango and all other dependencies have been upgraded. We build canvas from source and have now some little issues with letter spacing for custom fonts. We would like to try those fixes to see if they help.

**Comment by chearon** [comment]
Finally done. Sorry for the wait, prebuilds are always a pain.
