### ISSUE TITLE
Can we get a buffer from an Image ?

### ISSUE THREAD

**Issue by mahnehsilla** [Automattic/node-canvas#2207]
## Issue

Implement a way to get a buffer from the decoded image

```typescript
  import { loadImage } from "canvas";
  
const image = await loadImage(imagePath)
const raw = image.toBuffer(image)
```
Is this possible or the only way is creating a canvas from the image first?

**Comment by zbjornson** [comment]
The only way is to draw it to a canvas unfortunately.
