### ISSUE TITLE
Select / Find text in a pdf Created Using Node-Canvas

### ISSUE THREAD

**Issue by kaushik-utkarsh** [Automattic/node-canvas#2209]
## Issue
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Bug: I have created some text containing PDF's using node-canvas but i can not find or select the text, can anyone please help me out with this.

**Comment by zbjornson** [comment]
Set `context.textDrawingMode = "glyph"`. See https://github.com/Automattic/node-canvas#canvasrenderingcontext2dtextdrawingmode

> `glyph` will embed text instead of paths into the PDF. This is faster to encode, faster to open with PDF viewers, yields a smaller file size and makes the text selectable. The subset of the font needed to render the glyphs will be embedded in the PDF. This is usually the mode you want to use with PDF canvases.
