### ISSUE TITLE
Unable to install node-canvas in node 18.16.0.

### ISSUE THREAD

**Issue by sharma-shray** [Automattic/node-canvas#2233]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

unable to install canvas for node version 18.16.0
![image](https://user-images.githubusercontent.com/48922607/233076075-f1410819-b7b3-41dd-989b-3457f144af17.png)

## Your Environment
* Environment (e.g. node 18.16.0 on windows):

**Comment by sharma-shray** [comment]
When can I expect the support for node 18.16.0?

**Comment by zbjornson** [comment]
Can you use canvas v2.11.0 or later? That's the first version with prebuilds for Node.js v18.

**Comment by sharma-shray** [comment]
thank you for the clarification that should fix it. thanks

**Comment by Gnud-NA** [comment]
> thank you for the clarification that should fix it. thanks

What Nodejs version do you use, Sir?

**Comment by Gnud-NA** [comment]
I have a problem with canvas ver 2.11.0. When I open merge request, ci/cd on github caught error about node-canvas and its say say using node@20.0.0. Who can explain what reason and how to fix it. Thanks.
