### ISSUE TITLE
Can't install in alpine

### ISSUE THREAD

**Issue by rimifon** [Automattic/node-canvas#2239]
ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v111-linux-musl-x64.tar.gz

command:
apk add npm python3 build-base pango-dev
npm i canvas

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this.

**Comment by rimifon** [comment]
If node-canvas does not support Alpine containers, why can I install it normally in an Alpine container under my local WSL environment? I just need to run "apk add npm python3 build-base pango-dev" and then "npm i canvas".

**Comment by rimifon** [comment]
In the alpine container newly launched in my local WSL2 docker, only need to install these packages with "apk add npm pango-dev g++ make jpeg-dev giflib-dev librsvg-dev", and then run "npm i canvas", it can be installed normally.

**Comment by rimifon** [comment]
The problem has been solved. First, I configured the same environment in the local WSL2 Alpine docker system, and then installed the canvas module with "npm i canvas". After successfully installing it, I packaged the entire directory and transferred it to the server environment. After unpacking it on the server, it can be used normally.

**Comment by hrithik01** [comment]
Just add below command to your docker file and it will run.
`RUN apk update && apk add build-base g++ cairo-dev pango-dev giflib-dev`

**Comment by duylddev** [comment]
Thanks @hrithik01 
you saved my day
