### ISSUE TITLE
the module was compiled against a different Node.js version 

### ISSUE THREAD

**Issue by shifoc** [Automattic/node-canvas#2242]
## Issue or Feature
- [x ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).
I tried npm rebuild and npm install nothing fixed it

## Steps to Reproduce

```
Error: The module '/home/ubuntu/wa/node_modules/canvas/build/Release/canvas.node'
0|index  | was compiled against a different Node.js version using
0|index  | NODE_MODULE_VERSION 108. This version of Node.js requires
0|index  | NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
0|index  | the module (for instance, using `npm rebuild` or `npm install`).
0|index  |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
0|index  |     at Module.load (node:internal/modules/cjs/loader:1033:32)
0|index  |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
0|index  |     at Module.require (node:internal/modules/cjs/loader:1057:19)
0|index  |     at Module.Hook._require.Module.require (/home/ubuntu/.nvm/versions/node/v18.12.1/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
0|index  |     at require (node:internal/modules/cjs/helpers:103:18)
0|index  |     at Object.<anonymous> (/home/ubuntu/wa/node_modules/canvas/lib/bindings.js:3:18)
0|index  |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
0|index  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
0|index  |     at Module.load (node:internal/modules/cjs/loader:1033:32)
0|index  |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
0|index  |     at Module.require (node:internal/modules/cjs/loader:1057:19)
0|index  |     at Module.Hook._require.Module.require (/home/ubuntu/.nvm/versions/node/v18.12.1/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
0|index  |     at require (node:internal/modules/cjs/helpers:103:18)
0|index  |     at Object.<anonymous> (/home/ubuntu/wa/node_modules/canvas/lib/canvas.js:9:18)
0|index  |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
0|index  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
0|index  |     at Module.load (node:internal/modules/cjs/loader:1033:32)
0|index  |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
0|index  |     at Module.require (node:internal/modules/cjs/loader:1057:19)
0|index  |     at Module.Hook._require.Module.require (/home/ubuntu/.nvm/versions/node/v18.12.1/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
0|index  |     at require (node:internal/modules/cjs/helpers:103:18) {
0|index  |   code: 'ERR_DLOPEN_FAILED'
0|index  | }
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 10.2.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): 18.2.0 on ubuntu

**Comment by Yann-Chapuis** [comment]
Same thing for me 

node v20.1.0 (docker node:20.1.0)
npm v9.6.4
canvas v2.11.2
Ubuntu

**Comment by svk-man** [comment]
![image](https://github.com/Automattic/node-canvas/assets/17108861/b92a629d-9d06-42b6-84fb-88a738a8323f)

**Comment by svk-man** [comment]
What am I doing wrong?

![image](https://github.com/Automattic/node-canvas/assets/17108861/a3817476-fef7-4906-b7c1-d418582d2996)

**Comment by svk-man** [comment]
114 is not found: https://nodejs.org/en/download/releases#ref-1

**Comment by svk-man** [comment]
> @svk-man you're using Electron, which has its own set of NODE_MODULE_VERSIONs.

@zbjornson Thank you very much!

I installed [@electron/rebuild](https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules#installing-modules-and-rebuilding-for-electron) package and when I try to rebuild I get an error:

![image](https://github.com/Automattic/node-canvas/assets/17108861/fed5396c-2e95-495a-add4-c7243f5f3c37)

What caused this error?

node: v20.1.0
npm: 9.6.6

my dependencies:
```
    "@electron/rebuild": "^3.2.13",
    "body-parser": "^1.20.2",
    "express": "^4.18.2",
    "ffmpeg": "^0.0.4",
    "multer": "^1.4.5-lts.1",
		"@tensorflow/tfjs-node-gpu": "^4.5.0",
    "canvas": "^2.11.2",
    "electron": "^24.3.0"
```

**Comment by Orange-001** [comment]
Have you tried removing `node-modules` and `package-lock.json` and then running `npm install`. I recommend you to check out this solution: [https://stackoverflow.com/questions/63712163/node-was-compiled-against-a-different-node-js-version-using-node-module-versio/63712386#63712386](url)

**Comment by colining** [comment]
> Same issue for me :(
> 
> Windows 10 Pro, x64 Node v20.3.0 (NODE_MODULE_VERSION 115 according to https://nodejs.org/en/download/releases#ref-1) npm v9.7.1 canvas v2.11.2. electron v24.3.1
> 
> After hours of rebuilding and reinstalling I tried the canvas package from https://www.npmjs.com/package/@napi-rs/canvas and it works! No problem with running canvas in my electron project

save my life, thanks a lot

**Comment by jphawk** [comment]
> Same issue for me :(
> 
> Windows 10 Pro, x64 Node v20.3.0 (NODE_MODULE_VERSION 115 according to https://nodejs.org/en/download/releases#ref-1) npm v9.7.1 canvas v2.11.2. electron v24.3.1
> 
> After hours of rebuilding and reinstalling I tried the canvas package from https://www.npmjs.com/package/@napi-rs/canvas and it works! No problem with running canvas in my electron project

Thank you @RootDev4, it really did work! 🚀 
I had an issue after switching to `node v20.8.1` and `npm 10.2.1` on MacOS 13.6, but removing `canvas` and installing [@napi-rs/canvas](https://www.npmjs.com/package/@napi-rs/canvas) did the trick.

**Comment by AlirezaDadrass** [comment]
hi
I have this issue too but I cant use any alternative package because it used in another package "jscanify".

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/alireza/Projects/FinProjects/CheckScanner/CheckScanner/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 119. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2238)
    at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2238)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/alireza/Projects/FinProjects/CheckScanner/CheckScanner/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)`
    
can you help please?

**Comment by RootDev4** [comment]
> hi I have this issue too but I cant use any alternative package because it used in another package "jscanify".
> 
> `A JavaScript error occurred in the main process Uncaught Exception: Error: The module '/home/alireza/Projects/FinProjects/CheckScanner/CheckScanner/node_modules/canvas/build/Release/canvas.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 115. This version of Node.js requires NODE_MODULE_VERSION 119. Please try re-compiling or re-installing the module (for instance, using `npm rebuild`or`npm install`). at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2238) at Module._extensions..node (node:internal/modules/cjs/loader:1356:18) at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2238) at Module.load (node:internal/modules/cjs/loader:1126:32) at Module._load (node:internal/modules/cjs/loader:967:12) at l._load (node:electron/js2c/asar_bundle:2:13642) at Module.require (node:internal/modules/cjs/loader:1150:19) at require (node:internal/modules/cjs/helpers:119:18) at Object.<anonymous> (/home/alireza/Projects/FinProjects/CheckScanner/CheckScanner/node_modules/canvas/lib/bindings.js:3:18) at Module._compile (node:internal/modules/cjs/loader:1271:14)`
> 
> can you help please?

Hi AlirezaDadrass,
maybe this works: install @napi-rs/canvas. Than, inside your project folder, go to node_modules/jscanify and open jscanify-node.js. Update `const { Canvas, createCanvas, Image, ImageData } = require("canvas");` in line 3 to `const { Canvas, createCanvas, Image, ImageData } = require("@napi-rs/canvas");`

**Comment by kschobiz** [comment]
> 114 is not found: https://nodejs.org/en/download/releases#ref-1
> 
> ![image](https://private-user-images.githubusercontent.com/17108861/238663475-24356438-aebc-4285-96d2-6b72b7d4c591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODAxNjcsIm5iZiI6MTcwOTg3OTg2NywicGF0aCI6Ii8xNzEwODg2MS8yMzg2NjM0NzUtMjQzNTY0MzgtYWViYy00Mjg1LTk2ZDItNmI3MmI3ZDRjNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA2Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZDYzYjBlZTM4YjYyNTNiYjFhOTU5YjdiZGIwNDE2Y2ZlMTk4Njg3YjhlMGNkMjRiZjA3MzRiMGM4MjQ4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FvcWarGZ0_4kUoo63pbwkLOYJPWPHHGM8SpzNbsc_3o)

Good~

**Comment by kschobiz** [comment]
Good

**Comment by kane-mason** [comment]
I ran into this issue and for me the problem was somehow with nvm.

I had two versions of nvm installed (20 and 16), even though 20 was the default and active version of node, the binaries were being compiled with node 16.

Solved by removing node 16 from nvm

(i also had to delete and re-add my pm2 tasks so possible problem was pm2 all along using wrong node)
