### ISSUE TITLE
where is arm64 builds ;(

### ISSUE THREAD

**Issue by pompushko** [Automattic/node-canvas#2247]
Hello
Cant find arm64 builds for M1/M2 cpu ;(

Thank you

**Comment by MattyBalaam** [comment]
This would certainly help my issue: https://github.com/mozilla/pdf.js/issues/16463

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this.
