### ISSUE TITLE
problem with cairo when npm install canvas

### ISSUE THREAD

**Issue by johholl** [Automattic/node-canvas#225]
i installed pixman, cairo and now want to install canvas via npm.

an error occurs (and makes me sick :-)

 CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:8:
../src/Canvas.h:19:10: fatal error: 'cairo/cairo.h' file not found
# include <cairo/cairo.h>

1 error generated.
make: **\* [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 12.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Johannes/node_modules/canvas
gyp ERR! node -v v0.8.11
gyp ERR! node-gyp -v v0.6.11
gyp ERR! not ok 
npm ERR! canvas@0.13.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the canvas@0.13.1 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /Users/Johannes
npm ERR! node -v v0.8.11
npm ERR! npm -v 1.1.62
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Johannes/npm-debug.log
npm ERR! not ok code 0

Can someone help me please ...

**Comment by tomdanvers** [comment]
Hi I'm getting this error too. I've followed this guide (https://github.com/Automattic/node-canvas/wiki/Installation---OSX) to the letter but get the following:

> canvas@1.2.0 install /Users/tomdanvers/Documents/_workspace/samsung-aof-prototype/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  SOLINK_MODULE(target) Release/canvas-postbuild.node: Finished
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:7:
../src/Canvas.h:19:10: fatal error: 'cairo/cairo.h' file not found
#include <cairo/cairo.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tomdanvers/Documents/_workspace/samsung-aof-prototype/node_modules/canvas
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! canvas@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.0 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /Users/tomdanvers/Documents/_workspace/samsung-aof-prototype
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
jemima:samsung-aof-prototype tomdanvers$ 


This is driving me nuts, any help would be much appreciated!

**Comment by mltucker** [comment]
What do you see when you do:

```
pkg-config --cflags-only-I cairo
```

?

**Comment by tomdanvers** [comment]
Hi @mltucker thanks for the response. I see this:

-I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/include/libpng15 

Thanks

**Comment by mltucker** [comment]
Hi @tomdanvers .  That looks good.  What does this give you:

```
find /usr/local/include/cairo -type f
```

?

**Comment by tomdanvers** [comment]
This @mltucker:

/usr/local/include/cairo/cairo-deprecated.h
/usr/local/include/cairo/cairo-features.h
/usr/local/include/cairo/cairo-ft.h
/usr/local/include/cairo/cairo-pdf.h
/usr/local/include/cairo/cairo-ps.h
/usr/local/include/cairo/cairo-quartz.h
/usr/local/include/cairo/cairo-script-interpreter.h
/usr/local/include/cairo/cairo-script.h
/usr/local/include/cairo/cairo-svg.h
/usr/local/include/cairo/cairo-version.h
/usr/local/include/cairo/cairo-xlib-xrender.h
/usr/local/include/cairo/cairo-xlib.h
/usr/local/include/cairo/cairo.h

**Comment by mltucker** [comment]
@tomdanvers 

It's not exactly a proper solution, but I'm guessing you could fix this problem by doing:

```
sudo ln -s . /usr/local/include/cairo/cairo
```

**Comment by tomdanvers** [comment]
Thanks @mltucker I really appreciate the help. Could explain what that bash command does if you have a moment? It has got me past the initial error (yay) but is immediately followed by another error (boo - jpeglib.h' file not found). 

I feel its my limited knowledge of bash that is causing my problems :D

**Comment by mltucker** [comment]
@tomdanvers No problem.  It's definitely not your bash skills causing the issues!  It should just install when you do `npm install canvas`.  What the command does is make a symbolic link  `/usr/local/include/cairo/cairo` pointing to `/usr/local/include/cairo`.  Since pkg-config is telling node-gyp to look in /usr/local/include/cairo, and src/Canvas.cc is including <cairo/cairo-XX.h>, (and since no one is telling the compiler to look in /usr/local/include), the compiler looks for /usr/local/include/cairo/cairo/cairo-XX.h.  The command I gave you makes that the same as /usr/local/include/cairo/cairo-XX.h.  I hope that makes sense.

Can you post the entire error?

**Comment by tomdanvers** [comment]
Ah I understand! So the error I now get is similar but a different library this time I think...

../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tomdanvers/Documents/_workspace/samsung-aof-prototype/node_modules/canvas
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! canvas@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.0 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /Users/tomdanvers/Documents/_workspace/samsung-aof-prototype
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by mltucker** [comment]
@tomdanvers Once again a problem of /usr/local/include not being included... 

First of all, make sure this file exists:

```ls /usr/local/include/jpeglib.h```

If so, then try this (I'm not sure if node-gyp takes environment variables like this, but hopefully it does):

```CFLAGS=-I/usr/local/include npm install canvas```

If that doesn't work, try the same thing with OTHER_CFLAGS:

```OTHER_CFLAGS=-I/usr/local/include npm install canvas```

**Comment by tomdanvers** [comment]
Thank @mltucker! Still no joy I'm afraid.

There is a bit on npm environment variables here (https://docs.npmjs.com/misc/config) but I've tried various combinations with no luck.

E.g. 
npm install canvas --npm_config_cflags  -I/usr/local/include

**Comment by wehtta** [comment]
Totally the same problem with you。
I think it is because node gyp rebuild can not include /usr/local/include ， but do not how to solve

**Comment by mltucker** [comment]
@wehtta Which include files are not being found for you?  What OS are you on?
@tomdanvers Did you find a solution?

Both: have you installed libjpeg?  What does `pkg-config --cflags-only-I libjpeg` give?

**Comment by wehtta** [comment]
@mltucker 
I run install.sh in this module and then npm install canvas@1.1.1 . This works

**Comment by LinusU** [comment]
@mltucker Thank you so much! The symlink trick fixes it for me. 

I think that the correct thing to do would be to remove the `cairo/` part in the include? I guess that the only reason that works on Linux is because gcc already looks in `/usr/local/include`. That means that it dosen't use whatever `pkg-config` gives it anyway.

It would be great if someone on linux could test this out.

**Comment by LeeDr** [comment]
@peytra did you get your Windows system working?  I have the same problem.  How can I get cairo installed on Windows?

```
c:\git\kibana>npm install canvas
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported

> canvas@1.2.9 install c:\git\kibana\node_modules\canvas
> node-gyp rebuild


c:\git\kibana\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\Lee\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
c:\git\kibana\node_modules\canvas\src\color.h(12): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
c:\git\kibana\node_modules\canvas\src\color.h(12): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
c:\git\kibana\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
c:\git\kibana\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
c:\git\kibana\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
c:\git\kibana\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
c:\git\kibana\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
c:\git\kibana\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [c:\git\kibana\node_modules\canvas\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Lee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Lee\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\git\kibana\node_modules\canvas
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Lee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\git\kibana\npm-debug.log
```

**Comment by mathiasbynens** [comment]
```
$ npm install canvas
[snip]
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
[snip]

$ pkg-config --cflags-only-I libjpeg
Package libjpeg was not found in the pkg-config search path.
Perhaps you should add the directory containing `libjpeg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libjpeg' found

$ echo $PKG_CONFIG_PATH
/usr/local/include

$ ls /usr/local/include/jpeglib.h
/usr/local/include/jpeglib.h
```

Any other ideas?

**Comment by LinusU** [comment]
@mathiasbynens `xcode-select --install`

I assume that you have upgraded to El Capitan which causes this strange error. The bug is not in canvas, but rather with the compiler tools since it won't work for any c/c++ file. The command I posted will magically fix it.

**Comment by kangax** [comment]
@LinusU should we add this to README?

**Comment by LinusU** [comment]
Hmm, yeah probably, at least temporary since it seems like a lot of people are having trouble with this...

**Comment by mathiasbynens** [comment]
@LinusU Thanks; I can confirm this fixed the problem.

**Comment by josephmilla** [comment]
Also, encountered this issue. I hope it gets fixed soon

**Comment by LinusU** [comment]
@josephmilla did you read the conversation? The problem is not in node-canvas and a workaround have been added to the readme

**Comment by portwatcher** [comment]
`xcode-select --install` saved my whole night! Finally I can leave company with peace now....

**Comment by LinusU** [comment]
Glad to hear it :beers:

**Comment by xw65** [comment]
I fix the problem for jpeglib.h but got the following problem:

$ npm install canvas

> canvas@1.3.12 install /Users/xiaohangwang/Desktop/superApp/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xiaohangwang/Desktop/superApp/node_modules/canvas
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN TalkingEditor@1.0.0 No repository field.
npm WARN TalkingEditor@1.0.0 license should be a valid SPDX license expression
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE


Any ideas?

**Comment by LinusU** [comment]
@xw65 could you try running `xcode-select --install` and then try again

**Comment by xw65** [comment]
@LinusU , yeh i already installed that, now it returns me:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates.

And the ERR i mentioned before still exists...

**Comment by LinusU** [comment]
Have you tried using "Software Update" to install updates?

**Comment by xw65** [comment]
@LinusU Yes, that doesnt work for me.

**Comment by rqzheng2015** [comment]
also met this problem like @xw65 ,even after i had run "xcode-select --install", plz help

**Comment by moeiscool** [comment]
@jonsrepo is the saviour!

**Comment by buildAll** [comment]
JUST DO xcode-select --install, then re install the package. It works perfect!

**Comment by zhoushulin168** [comment]
D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5>npm install canvas

> canvas@1.6.6 install D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas
> node-gyp rebuild


D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
d:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\src\Canvas.h(19): f
atal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.
cc) [D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\build\canvas.v
cxproj]
d:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\src\Canvas.h(19): f
atal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasP
attern.cc) [D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\build\c
anvas.vcxproj]
d:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\src\Canvas.h(19): f
atal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasG
radient.cc) [D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\build\
canvas.vcxproj]
  color.cc
  Image.cc
  ImageData.cc
  init.cc
d:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\src\Canvas.h(19): f
atal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasR
enderingContext2d.cc) [D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\can
vas\build\canvas.vcxproj]
d:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\src\Canvas.h(19): f
atal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Image.c
c) [D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\build\canvas.vc
xproj]
d:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\src\Canvas.h(19): f
atal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\ImageDa
ta.cc) [D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\build\canva
s.vcxproj]
d:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\src\Canvas.h(19): f
atal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\init.cc
) [D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas\build\canvas.vcx
proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\node_modules\canvas
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN dashboard@1.0.0 No description
npm WARN dashboard@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node-project\dsashboard-2.0-master-167183959700012e8f268cdddb5166ec76575cd5\npm-debug.log

**Comment by cr0wg4n** [comment]
Instead move to  [chartjs node canvas](https://www.npmjs.com/package/chartjs-node-canvas)

**Comment by dsouzamanish** [comment]
This did the trick for me. If anyone facing same issue on macbook m1.

$ nvm uninstall 14
$ arch -x86_64 zsh 
$ nvm install 14
$ nvm alias default 14
