### ISSUE TITLE
Can't upload  canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz 

### ISSUE THREAD

**Issue by dmZhan** [Automattic/node-canvas#2251]
--Hey, guys! I also had the same issue. Maybe you can try creating a .npmrc file under the project root path, specifying the mirror address of the canvas, like this: `canvas_binary_host_mirror=https://registry.npmmirror.com/-/binary/canvas`
It worked for me and I hope it helps you.

--_Originally posted by @Orange-001 in https://github.com/Automattic/node-canvas/issues/2186#issuecomment-1562146083_
            
I have a new problem. I did it the way you did it. It doesn't work because  `https://registry.npmmirror.com/-/binary/canvas/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz` doesn't exist. And my device is a Mac with M2.

**Comment by bengyles** [comment]
Same issue here on an M1 Macbook

**Comment by arcticShadow** [comment]
Seems like canvas does not have prebuilt binaries for arm64 (Mac M1/M2's)

See the binaries that they provide here: 
https://github.com/Automattic/node-canvas/releases

(I'm also searching for a solution at the moment)

**Comment by bengyles** [comment]
indeed the arm64 versions are not prebuilt, node gyp is installing them from source and giving this error: 

```
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

**Comment by bengyles** [comment]
fixed it by adding `export PATH="/opt/homebrew/bin:$PATH"` to `~/.zshrc`. I think I have 2 installs of pkg-config and now the correct one is being used. Hope this fixes the issue for others as well

**Comment by Arkomus** [comment]
> > export PATH="/opt/homebrew/bin:$PATH"
> 
> ne fonctionne pas pour moi😢, a essayé de supprimer yarn.lock et node_modules avant aussi.

i have found the response after two days,
after this
https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md

hoping it work for you

**Comment by fuchunhui** [comment]
when I successfully installed it, I smiled.

**Comment by fuchunhui** [comment]
1. read this.
> https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md

We need to start by knowing your version of npm:
```npm --version```

If your npm is version 7 or 8, do:
```
npm explore npm/node_modules/@npmcli/run-script -g -- npm_config_global=false npm install node-gyp@latest
```

2.

**Comment by EricLiuZero** [comment]
I got the same issue.
my machine is MacBook Pro M1 2020.
trying @fuchunhui 's solution.
after executing `brew install pkg-config cairo pango libpng jpeg giflib librsvg`
I got the following message and try to install `xcode-select`
![image](https://github.com/Automattic/node-canvas/assets/3775020/72f7e747-b538-4429-89ef-289ec9dffa86)
re-open vscode and run `pnpm i`
![image](https://github.com/Automattic/node-canvas/assets/3775020/addcb5b2-f102-4b27-a2d9-fe386688ef3c)

eventually, `canvas@2.11.2` was installed successfully.

**Comment by zbjornson** [comment]
As most of you figured out, there are no prebuilds for ARM. There's info on building from source in the troubleshooting guide (#1511).

> #### If you have an ARM CPU
> 
> Prebuilds aren't available for ARM. Please see the [wiki](https://github.com/Automattic/node-canvas/wiki#installation-guides) for guides on building from source. See also [node-gfx/node-canvas-prebuilt#69](https://github.com/node-gfx/node-canvas-prebuilt/issues/69).

**Comment by sadewa25** [comment]
> brew install pkg-config cairo pango libpng jpeg giflib librsvg

thanks for your solutions, this work for me

**Comment by cunneen** [comment]
I also had to install `python-setuptools` i.e.:

`brew install pkg-config cairo pango libpng jpeg giflib librsvg python-setuptools`

**Comment by 7zf001** [comment]
> I also had to install `python-setuptools` i.e.:
> 
> `brew install pkg-config cairo pango libpng jpeg giflib librsvg python-setuptools`

Thank you for providing the solution, it resolved my issue, I had to install python-setuptools. 
Mine is a 2021 M1, Version: 13.6.9
