### ISSUE TITLE
Update simple-get version to 4.0.1

### ISSUE THREAD

**Issue by guptaashwanee** [Automattic/node-canvas#2252]
I have no Idea about it, but docker says this is High Vulnerabilities.
 
Exposure of Sensitive Information to an Unauthorized Actor in NPM simple-get prior to 4.0.1.
--
CVSS Score: | 7.5
CVSS Vector: | CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
Affected range: | <4.0.1
Fix version: | 4.0.1
Publish date: | 2022-01-26

**Comment by LinusU** [comment]
Our usage of simple-get is not vulnerable. We cannot upgrade without a breaking change, so this will be fixed in the next major.

More info: https://github.com/Automattic/node-canvas/pull/2223#issuecomment-1496177541
