### ISSUE TITLE
problem canvas in using Any pdf modeule

### ISSUE THREAD

**Issue by woxman** [Automattic/node-canvas#2259]
i cant run my software  and see this problem.
when I see this problem , when use any module pdf convert to png
canvas version 2.0.22
nodejs version 18.16.0

Please help me.................

![image](https://github.com/Automattic/node-canvas/assets/42204644/d95bbc3a-4d0f-4210-9667-95e012fb662a)

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this. There's not enough info here to troubleshoot.
