### ISSUE TITLE
Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)

### ISSUE THREAD

**Issue by mbxuexing** [Automattic/node-canvas#2262]
<img width="722" alt="image" src="https://github.com/Automattic/node-canvas/assets/45852421/fa353638-cdfd-4734-8710-996ae159b3ba">loadImage 文件过大 提示Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)

**Comment by zbjornson** [comment]
Can you provide a minimal reproducible example please? That error can happen if the size is negative or greater than Canvas's limit (32,767).
