### ISSUE TITLE
 Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by tt-abetemadi** [Automattic/node-canvas#2273]
## Cannot find module '../build/Release/canvas.node'
When using the canvas library, the following error is encountered: "Cannot find module '../build/Release/canvas.node'".

## Steps to Reproduce

```js
    const canvas = createCanvas(200, 200);
// etc.
```
<img width="343" alt="image" src="https://github.com/Automattic/node-canvas/assets/93504194/962dbd70-c60b-4284-aa0f-cd027dba2a52">

After removing the "node_modules" directory and reinstalling the packages, the error persists.

## Your Environment
* Version of node-canvas : v1.22.19
* Environment : node v16.20.1 on Windows

**Comment by dodomui** [comment]
Me too facing the issue. it happens exactly after reinstall.
No matter how many time I tried to reinstall or downgrade it wouldn't works

**Comment by AdrianBonpin** [comment]
Facing this same issue especially when i package using pkg or nexe

Hopefully a fix comes out soon

**Comment by zbjornson** [comment]
Please refer to the troubleshooting guide (#1511) and look through older issues. There's not enough info here to troubleshoot.

**Comment by alessandrocapra** [comment]
I can add some more context. When you install, there will be a build error with the following contents:

```
# This file contains the result of Yarn building a package (canvas@npm:2.11.2)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.19.0 | darwin | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.19.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok

```
