### ISSUE TITLE
[Issue] Problem to Preparing a build for Windows on Linux

### ISSUE THREAD

**Issue by ohanedan** [Automattic/node-canvas#2276]
## Issue Description

Hello,

I'm trying to prepare a build for Windows using a Linux Docker image in CI/CD. When I run 'npm install', I faced the following error in my service:
```
canvas.node is not a valid Win32 application.
```

For this reason, I thought I needed to build for Windows and started researching. In my research, I discovered the 'target_arch' and 'target_platform' parameters of node-gyp.

After found these, I executed the "npm install" command with these parameters in CI/CD:
```
npm install --target_arch=x64 --target_platform=win32
```
Now, I'm facing the following error during the installation:
```
  npm ERR! node-pre-gyp info check checked for "/myservice/node_modules/canvas/build/Release/canvas.node" (not found)
  npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v93-win32-glibc-x64.tar.gz
  npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v93-win32-glibc-x64.tar.gz
  npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.0 and node@16.20.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
  npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v93-win32-glibc-x64.tar.gz
```

How can I resolve this issue? If it can't be resolved, how can I prepare a build for Windows from Linux? Thanks.

## Steps to Reproduce
- use or create any project which uses this package
- run "npm install --target_arch=x64 --target_platform=win32" on Linux

## Your Environment
- canvas: 2.9.0
- npm: 8.19.4
- node: v16.20.0
- OS: Debian GNU/Linux 11 (bullseye) (docker container, actually)

**Comment by zbjornson** [comment]
Try adding `--target_libc=unknown` so it doesn't try to use glibc on Windows. Not sure if you'll hit downstream issues though.

**Comment by ohanedan** [comment]
> Try adding `--target_libc=unknown` so it doesn't try to use glibc on Windows. Not sure if you'll hit downstream issues though.

It works, I didn't faced any new problems in my first tests. Thanks
