### ISSUE TITLE
What is the registerFont behavior?

### ISSUE THREAD

**Issue by dala00** [Automattic/node-canvas#2280]
## Issue
What is the registerFont behavior? I'm using on server. When registerFont is called on each server request, memory usage increases forever? deregisterAllFonts should be called at the end of each request?

Then I thought following request pattern works well?

1. RequestA: registerFont called
2. RequestB: registerFont called
3. RequestA: deregisterAllFonts called
4. ReqeustB: use canvas (with no font?)

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.11.2
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node18, Next.js13 API Routes

**Comment by zbjornson** [comment]
You only need to call it once for the lifetime of the process/canvas module. Assuming you're reusing the same fonts across requests, there's no need to unregister and re-register fonts in each request.

**Comment by dala00** [comment]
Thanks. But by default, Next.js API Routes has no initialize method. So I wanted font loading duplication check method or unload method.

But I try other server. Thanks.
