### ISSUE TITLE
canvas not working on node version 19. 

### ISSUE THREAD

**Issue by Proxtx** [Automattic/node-canvas#2281]
## Issue
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

this error occours when importing canvas: 
```
node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\E:\<Project-Path>\node_modules\canvas\build\Release\canvas.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (<Project-Path>\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v19.0.1
```
I am on winows and have tried rebuilding canvas with node-gyp: 
```
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 1 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen. <Code generation is finished>
  canvas-postbuild.vcxproj -> <Project-Path>\node_modules\canvas\build\Release\\canvas-postbuild.node
gyp info ok 
```

I have tried running node as admin.

## Your Environment
<Project>@1.0.0 <Project-Path>
└── canvas@2.11.2
* Windows - Node v19.0.1

**Comment by Batimius** [comment]
I did some research and some testing. It looks like the issue is because of incapability with Sharp. You can solve this by either uninstalling Sharp (which might not be possible because it might be used as a dependency for another necessary library), or by requiring canvas first (it seems like this is a 50/50 from what I've read, it works for me though). Test it out and see what works and what doesn't.

**Comment by andre5s** [comment]
If anyone still needs this, I managed to make it work with:
- Canvas: `v2.11.2`
- Sharp: `v0.32.3`   _(this was the main issue for me, because it is not working with newer versions)_
- Node.js: `v20.6.1`

To be sure, I also used `"overrides"` property in **package.json**

**Comment by Proxtx** [comment]
I didn't test @andre5s solution but @Batimius also mentioned issues with sharp. So this is probably the solution.
I'm closing this issue now.
