### ISSUE TITLE
strndup is not supported in mac os x's c compiler

### ISSUE THREAD

**Issue by dreamind** [Automattic/node-canvas#229]
CanvasRenderingContext2d.cc uses strndup, which is not available on mac os x (10.6.8) and gcc i686-apple-darwin10-gcc-4.2.1.

http://stackoverflow.com/questions/6062822/whats-wrong-with-strndup

**Comment by LinusU** [comment]
Apple dropped support for OS X 10.6 as of February 25, 2014. Because of that I'm closing this bug, if this is affecting you please comment and we can consider reopening.
