### ISSUE TITLE
Python error on MacOS

### ISSUE THREAD

**Issue by oneVcard** [Automattic/node-canvas#2290]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

When performing npm install trough DockerFile this error occures:
#15 34.57 npm ERR! code 1
#15 34.57 npm ERR! path /usr/src/app/node_modules/canvas
#15 34.57 npm ERR! command failed
#15 34.57 npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
#15 34.57 npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/src/app/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#15 34.57 npm ERR! node-pre-gyp info it worked if it ends with ok
#15 34.57 npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
#15 34.57 npm ERR! node-pre-gyp info using node@16.20.2 | linux | arm64
#15 34.57 npm ERR! node-pre-gyp info check checked for "/usr/src/app/node_modules/canvas/build/Release/canvas.node" (not found)
#15 34.57 npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v93-linux-glibc-arm64.tar.gz
#15 34.57 npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v93-linux-glibc-arm64.tar.gz 
#15 34.57 npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@16.20.2 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
#15 34.57 npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v93-linux-glibc-arm64.tar.gz 
#15 34.57 npm ERR! gyp info it worked if it ends with ok
#15 34.57 npm ERR! gyp info using node-gyp@9.1.0
#15 34.57 npm ERR! gyp info using node@16.20.2 | linux | arm64
#15 34.57 npm ERR! gyp info ok 
#15 34.57 npm ERR! gyp info it worked if it ends with ok
#15 34.57 npm ERR! gyp info using node-gyp@9.1.0
#15 34.57 npm ERR! gyp info using node@16.20.2 | linux | arm64
#15 34.57 npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
#15 34.57 npm ERR! gyp http GET https://nodejs.org/download/release/v16.20.2/node-v16.20.2-headers.tar.gz
#15 34.57 npm ERR! gyp http 200 https://nodejs.org/download/release/v16.20.2/node-v16.20.2-headers.tar.gz
#15 34.57 npm ERR! gyp http GET https://nodejs.org/download/release/v16.20.2/SHASUMS256.txt
#15 34.57 npm ERR! gyp http 200 https://nodejs.org/download/release/v16.20.2/SHASUMS256.txt
#15 34.57 npm ERR! gyp info spawn /usr/bin/python3
#15 34.57 npm ERR! gyp info spawn args [
#15 34.57 npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#15 34.57 npm ERR! gyp info spawn args   'binding.gyp',
#15 34.57 npm ERR! gyp info spawn args   '-f',
#15 34.57 npm ERR! gyp info spawn args   'make',
#15 34.57 npm ERR! gyp info spawn args   '-I',
#15 34.57 npm ERR! gyp info spawn args   '/usr/src/app/node_modules/canvas/build/config.gypi',
#15 34.57 npm ERR! gyp info spawn args   '-I',
#15 34.57 npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#15 34.57 npm ERR! gyp info spawn args   '-I',
#15 34.57 npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.20.2/include/node/common.gypi',
#15 34.57 npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
#15 34.57 npm ERR! gyp info spawn args   '-Dvisibility=default',
#15 34.57 npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.20.2',
#15 34.57 npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
#15 34.57 npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.20.2/<(target_arch)/node.lib',
#15 34.57 npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/src/app/node_modules/canvas',
#15 34.57 npm ERR! gyp info spawn args   '-Dnode_engine=v8',
#15 34.57 npm ERR! gyp info spawn args   '--depth=.',
#15 34.57 npm ERR! gyp info spawn args   '--no-parallel',
#15 34.57 npm ERR! gyp info spawn args   '--generator-output',
#15 34.57 npm ERR! gyp info spawn args   'build',
#15 34.57 npm ERR! gyp info spawn args   '-Goutput_dir=.'
#15 34.57 npm ERR! gyp info spawn args ]
#15 34.57 npm ERR! Package pangocairo was not found in the pkg-config search path.
#15 34.57 npm ERR! Perhaps you should add the directory containing `pangocairo.pc'
#15 34.57 npm ERR! to the PKG_CONFIG_PATH environment variable
#15 34.57 npm ERR! No package 'pangocairo' found
#15 34.57 npm ERR! gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
#15 34.57 npm ERR! gyp ERR! configure error 
#15 34.57 npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
#15 34.57 npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
#15 34.57 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#15 34.57 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
#15 34.57 npm ERR! gyp ERR! System Linux 5.15.49-linuxkit
#15 34.57 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/src/app/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
#15 34.57 npm ERR! gyp ERR! cwd /usr/src/app/node_modules/canvas
#15 34.57 npm ERR! gyp ERR! node -v v16.20.2
#15 34.57 npm ERR! gyp ERR! node-gyp -v v9.1.0
#15 34.57 npm ERR! gyp ERR! not ok 
#15 34.57 npm ERR! node-pre-gyp ERR! build error 
#15 34.57 npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/src/app/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
#15 34.57 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#15 34.57 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#15 34.57 npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
#15 34.57 npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
#15 34.57 npm ERR! node-pre-gyp ERR! System Linux 5.15.49-linuxkit
#15 34.57 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#15 34.57 npm ERR! node-pre-gyp ERR! cwd /usr/src/app/node_modules/canvas
#15 34.57 npm ERR! node-pre-gyp ERR! node -v v16.20.2
#15 34.57 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
#15 34.57 npm ERR! node-pre-gyp ERR! not ok
#15 34.57 
#15 34.57 npm ERR! A complete log of this run can be found in:
#15 34.57 npm ERR!     /root/.npm/_logs/2023-09-20T11_24_22_875Z-debug-0.log

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
─┬ easyqrcodejs-nodejs@4.4.5
│ ├── canvas@2.9.1
│ └─┬ jsdom@19.0.0
│   └── canvas@2.9.1 deduped
└─┬ react-scripts@5.0.1
  └─┬ jest@27.5.1
    └─┬ @jest/core@27.5.1
      └─┬ jest-config@27.5.1
        └─┬ jest-environment-jsdom@27.5.1
          └─┬ jsdom@16.7.0
            └── canvas@2.9.1 deduped
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
M2 MacOS Ventura 13.4.1
Python 3.10.11
Node: v18.18.0

**Comment by zbjornson** [comment]
Prebuilds aren't available for ARM. Please see the [wiki](https://github.com/Automattic/node-canvas/wiki#installation-guides) for guides on building from source. See also https://github.com/node-gfx/node-canvas-prebuilt/issues/69.

**Comment by wrs-coder** [comment]
How soon can release the arm architecture package for mac？
