### ISSUE TITLE
Creating build/Release very slow

### ISSUE THREAD

**Issue by GABuryan** [Automattic/node-canvas#2294]
## Issue or Feature
I run the command to build the project - npm ci --loglevel verbose
if I do it before 10am or at night, , I see it in the logs

3696 info run canvas@2.11.2 install { code: 0, signal: null }
3697 timing build:run:install:node_modules/canvas Completed in 6037ms

If I run at another time 

3689 info run canvas@2.11.2 install { code: 0, signal: null }
3690 timing build:run:install:node_modules/canvas Completed in 2066781ms

Folder build/Release in the first variant, it appears from two to 10 seconds. Processor -70%
In second variant - it appears from 10 to 40 minutes. Processor 2% . You can see how slowly the dll files appear in the folder.

Restarting the pc does not help. What could be the reason for this behavior? It started around the end of September. The project itself has not changed and the package versions have not changed either

**Comment by zbjornson** [comment]
I can't think of any reason this would be due to node-canvas itself. The build is fast on my computer and on GitHub Actions runners. Best guess might be a failing disk.
