### ISSUE TITLE
Generate Node 21 Prebuilds

### ISSUE THREAD

**Issue by dan-mcdonald** [Automattic/node-canvas#2295]
Node 21 was released a couple days ago. 

```
$ npm install
...
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@21.0.0 (node-v120 ABI, glibc) (falling back to source compile with node-gyp) 
...
```

**Comment by KaiSchwarz-cnic** [comment]
```
npm ERR! code 1
npm ERR! path /usr/share/<project>/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/usr/share/<project>/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/share/<project>/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
```

**Comment by ZsoltiHUB** [comment]
**npm ERR! code 1
npm ERR! path /home/ubuntu/Discord-MusicBot/djs-bot/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/ubuntu/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/ubuntu/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@21.0.0 | linux | x64
npm ERR! (node:33170) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@21.0.0 (node-v120 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz**

**Comment by ZsoltiHUB** [comment]
`npm ERR! code 1
npm ERR! path /home/ubuntu/Discord-MusicBot/djs-bot/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/ubuntu/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/ubuntu/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@21.0.0 | linux | x64
npm ERR! (node:33170) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@21.0.0 (node-v120 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-linux-glibc-x64.tar.gz`

**Comment by zbjornson** [comment]
Prebuilds are up for MacOS and Linux. Windows failed and needs some work to investigate it. 😩

**Comment by schuerg** [comment]
> Prebuilds are up for MacOS and Linux. Windows failed and needs some work to investigate it. 😩

Thanks!

Also thank you a lot for maintaining this library in general!

**Comment by olivierbelzile** [comment]
Any update on Windows prebuilds?

**Comment by ridays2001** [comment]
Is anyone facing issues while building this on Windows with node 21? I am unable to even build the package.

**Comment by luanon404** [comment]
Still waiting for node 21🫠🫠

**Comment by jmynes** [comment]
Any changes coming for this?

**Comment by zbjornson** [comment]
Prebuilds for Windows, Node.js v21, node-canvas v2.11.2 are up. The build was failing because of a regression in Node.js: https://github.com/nodejs/node/issues/48673.
