### ISSUE TITLE
Leading and trailing whitespace invalidates CSS colors

### ISSUE THREAD

**Issue by haykam821** [Automattic/node-canvas#2301]
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Building off of #2300, having whitespace at the start or end of the CSS color used to set a fill style, for example, invalidates the color, which is inconsistent with browser behavior and [the specification](https://drafts.csswg.org/css-values-4/#component-whitespace). (This specification also allows comments to appear, which are also incorrectly parsed here.)

## Steps to Reproduce

Compare the results of running the following snippet in a browser and in Node.js with `canvas`:

```js
const canvas = "document" in globalThis ? document.createElement("canvas") : require("canvas").createCanvas();
const context = canvas.getContext("2d");

const entries = [
	"red",
	" red",
	" red ",
	"#ff0000",
	" #ff0000",
	"#ff0000 "
];

for (const entry of entries) {
	context.fillStyle = entry;
	console.log(context.fillStyle);
}
```

## Environment

* `canvas` 2.11.2
* macOS Sonoma 14.1

**Comment by zbjornson** [comment]
Fixed in https://github.com/Automattic/node-canvas/pull/2384, will be in the next 3.0.0-rc and final v3.0.0.
