### ISSUE TITLE
Support bun runtime

### ISSUE THREAD

**Issue by cwtuan** [Automattic/node-canvas#2302]
## Feature
Support bun runtime

## Steps to Reproduce
Run the [example](https://github.com/Automattic/node-canvas#quick-example) in [bun](https://bunjs.run/) runtime caused error:
```bash
 dlopen(/xxxx/node_modules/canvas/build/Release/canvas.node, 0x0001): tried: '/Users/tony/workspace/github/cwtuan/fe-tool/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
      at internalRequire (:1:20)
      at /xxxx/node_modules/canvas/lib/bindings.js:3:6
      at globalThis (/xxxx/node_modules/canvas/lib/bindings.js:12:8)
      at overridableRequire (:1:20)
      at /xxxx/node_modules/canvas/lib/canvas.js:9:6
      at globalThis (/xxxx/node_modules/canvas/lib/canvas.js:111:77)
      at overridableRequire (:1:20)
```

## Your Environment
* Version of node-canvas: canvas@2.11.2 
* Environment:  bun 1.0.9 on Mac OS X 12.3

**Comment by 7f8ddd** [comment]
It builds and works fine on Bun, the maintainers just haven't released a version since they migrated to NAPI. If you use the .git link in "bun i git+githere" then it'll successfully build it and work, given you have the dependencies.

**Comment by chuckstock** [comment]
+1

**Comment by chearon** [comment]
It does work with Bun: `npm install canvas@next`. 3.0.0 is still an RC because I just want to wait a few more days to make sure nobody has issues with the new Arm images, but I will release it very soon.
