### ISSUE TITLE
Loss of color information when rendering small images

### ISSUE THREAD

**Issue by kennethpHN** [Automattic/node-canvas#2307]
## Issue
I am encountering a problem when generatating images. The goal is to create a 2x2 image with specific colors, such as red, green, blue, and black. The image data is manually created as a Uint8ClampedArray, and the colors seem correct when inspected.

However, when attempting to render the image using the putImageData method on the canvas context, the resulting image appears to lose color information and is displayed in grayscale. This issue persists even when creating a simple completely green 2x2 image.

It is worth mentioning that rendering images of larger sizes, for example 128x128, does not present any problem.

## Steps to Reproduce

```javascript
import { createCanvas, createImageData} from 'canvas';
import fs from "fs";

//Uint8ClampedArray for a 2x2 image with red, green, blue, and black colors
const dataArrayColorful = new Uint8ClampedArray([
    255, 0, 0, 255,   // Red
    0, 255, 0, 255,   // Green
    0, 0, 255, 255,   // Blue
    0, 0, 0, 255      // Black
]);
// Uint8ClampedArray for a 2x2 completely green image
const dataArrayGreen = new Uint8ClampedArray([
    0, 255, 0, 255,   // Green
    0, 255, 0, 255,   // Green
    0, 255, 0, 255,   // Green
    0, 255, 0, 255    // Green
]);
// canvas and a context
const canvas = createCanvas(2, 2);
const context = canvas.getContext('2d');

// ImageData object for the colorful image
const imgDataColorful = context.createImageData(new Uint8ClampedArray(dataArrayColorful), 2, 2);

// colorful image onto the canvas context
context.putImageData(imgDataColorful, 0, 0);

// Save the colorful image as a PNG
fs.writeFileSync('./output_colorful.png', canvas.toBuffer('image/png'));

// ImageData object for the completely green image
const imgDataGreen = context.createImageData(new Uint8ClampedArray(dataArrayGreen), 2, 2);

// green image onto the canvas context
context.putImageData(imgDataGreen, 0, 0);

// Save the green image as a PNG
fs.writeFileSync('./output_green.png', canvas.toBuffer('image/png'));
```

## Your Environment
* canvas@2.11.2
* node v16.16.0
* OS: Windows 10 22H2

**Comment by zbjornson** [comment]
> ```js
> const imgDataColorful = context.createImageData(new Uint8ClampedArray(dataArrayColorful), 2, 2)
> // ...
> const imgDataGreen = context.createImageData(new Uint8ClampedArray(dataArrayGreen), 2, 2);
> ```

Those lines should be `createImageData` without `context.` -- the function exported by node-canvas, not the Context2d property. With that fix, it seems to work:
![image](https://github.com/Automattic/node-canvas/assets/469365/a402bf62-16b1-45d5-a03d-a713b0895912)
