### ISSUE TITLE
Issue nan while rebuilding the module for electron using electron-rebuilder.

### ISSUE THREAD

**Issue by DomainFlag** [Automattic/node-canvas#2315]
## Issue
<code>Creating library x\app\node_modules\canvas\build\Release\canvas.lib and object x\app\node_modules\canvas\build\Release\canvas.exp
Canvas.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) referenced in function "void __cdecl parsePNGArgs(class v8::Local<class v8::Value>,struct PngClosure &)" (?parsePNGArgs@@YAXV?$Local@VValue@v8@@@v8@@AEAUPngClosure@@@Z) [x\app\node_modules\canvas\build\canvas.vcxproj]
</code>

I see that the issue is related to `nan`, and also saw that the PR was merged for moving to N-API. It it safe to use the master branch, or what are the recommendations, when is the next release?

## Your Environment
* Version of node-canvas: 2.11.2
* Environment (e.g. node 16.20.2, win64 - 11 / Version	10.0.22621 Build 22621):
* Electron - v24.8.8

**Comment by zbjornson** [comment]
Yes, try using the master branch. Prebuilds are the only thing holding up the v3 release, and prebuilds aren't usable with electron anyway.
