### ISSUE TITLE
[TypeError: Object #<PNGStream> has no method 'destroy']

### ISSUE THREAD

**Issue by kilianc** [Automattic/node-canvas#232]
Stream interface not fully implemented.

**Comment by zbjornson** [comment]
From the [docs](https://nodejs.org/dist/latest-v4.x/docs/api/stream.html) and [discussion on SO](http://stackoverflow.com/questions/19277094/how-to-close-a-readable-stream-before-end) it seems like streams don't actually provide a `.destroy` method, although `fs.readStream` happens to.

See more notes in #740.

**Comment by zbjornson** [comment]
Fixed in 8b5dc056b3045ffe6665c38c732dc7b37ce7c454 I think. (Definitely fixed, but not positive it was that commit.)

```js
> canvas.createPNGStream().destroy
[Function: destroy]
```
