### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by Edwin-Luijten** [Automattic/node-canvas#2323]
This is happening when a pre-compiled build is used (npm install canvas)

I see this error: `Cannot read properties of undefined (reading 'prototype')`  
`at ../../node_modules/canvas/lib/bindings.js (file:///var/task/ad/src/handlers/render.mjs:29076:24)"`.  

Which points to this:
```
'use strict'

const bindings = require('../build/Release/canvas.node')

module.exports = bindings

bindings.ImageData.prototype.toString = function () {
	return '[object ImageData]'
}

bindings.CanvasGradient.prototype.toString = function () {
	return '[object CanvasGradient]'
}
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):  
2.11.2
* Environment (e.g. node 20.9.0 on macOS 14.1.1):  
Node 18

**Comment by Edwin-Luijten** [comment]
`node build` seemed to fix it.

**Comment by buenaSopa** [comment]
run into the same issue but npm rebuild doesnt seems to fix it. same version of node canvas but I am using tru Fabric.js
