### ISSUE TITLE
npm pack ignoring build/ directory

### ISSUE THREAD

**Issue by deyceg** [Automattic/node-canvas#233]
Hey,

I have a dependency on Canvas, but I am unable to run npm install on my deployment server. My build is run on a CI server using npm pack to create distributable tarball ready for execution. However, I've noticed the build directory is in the .npmignore so my tarball will not run.

As I said, running npm install on the server is not an option. However, my development/CI/deployment platforms are identical, so packaging the build/ directory will work.

I had hoped to leverage npm as much as possible, but at the moment my only solution is to implement a workaround in my build script, or use some other method of packaging instead of npm.

I was wondering if you had a better solution?

Thanks

**Comment by LinusU** [comment]
Hmm, I don't actually think that this is the use case of `npm pack`. It is used for making the packages that go up to npm and if we made it include the build folder we would publish prebuilt binaries from whichever person published that release which wouldn't be good at all.

I'm afraid that you'll have to go with the workaround...
