### ISSUE TITLE
Custom Font Loaded Only Once (On restarting the node.js server only)

### ISSUE THREAD

**Issue by vivrkerror404** [Automattic/node-canvas#2337]
## Steps to Reproduce
```
const customFonts = {  
"Tangerine Regular": "Tangerine-Regular.ttf",
  "Updock Regular": "Updock-Regular.ttf",
};
    const fontName = customFonts [req.query?.fontName];
    const fontPath = fontName
      ? `./public/assets/fonts/${fontName}` 
      : "./public/assets/fonts/SpaceMono-Italic.ttf";// custom fonts .ttf files are inside assets/fonts folder
    const dataUri = await textToImage.generate(text, {
      textColor: "black",
      bgColor: "cyan",
      fontPath: fontPath,
      fontFamily: req.query?.fontName,
    });
```

I am using above code to create text images with custom fonts depending upon what parameter passed in query
It is working fine for the 1st time but next time I tried changing the fontName dynamically using query params, then it is loading image with the old font only but when I restarted my server it again worked fine

## Your Environment
* Version of node-canvas ("canvas": "^2.6.0"):
* Environment ( AWS EC2 ubuntu):
* Web server: ![Screenshot 2024-01-07 143114](https://github.com/Automattic/node-canvas/assets/45729693/8852edee-0d8e-45d0-879b-7ee90c1148ca)

**Comment by klavsbuss** [comment]
i think i have same issue. one day it works fine, the other it uses one font no matter what i pass as font parameter. seems that it uses some kind of 'catched' font. @vivrkerror404 did you found fix for this?

**Comment by vivrkerror404** [comment]
@klavsbuss I found the workaround for this , I simply deregister the font before loading new one in this file (**node_modules/text-to-image/dist/textToImage.js**) as show below:

```
canvas_1.Canvas._deregisterAllFonts();  // this extra line I have added
(0, canvas_1.registerFont)(fontPath, { family: fontFamily });
```
Here is a live working demo for the same:
https://apihut.in/Digital%20Signature%20App/live-demo

There is an addon, since the changes are inside node_modules I used patch-package to persist them even after npm install

Hope it might helps you

**Comment by klavsbuss** [comment]
@vivrkerror404 i wonder if i could run it on my firebase nodejs cloud environment too :/
