### ISSUE TITLE
 error C2039: “toupper”

### ISSUE THREAD

**Issue by abcln** [Automattic/node-canvas#2341]
d:\webserver\weixin\node\test\canvas-2.8\package\src\Util.h(17): warning C4996: 'Nan::SetAccessor': 被声明为已否决 (编译源文件 ..\src\ImageData.cc) [D:\webServe
r\weixin\node\test\canvas-2.8\package\build\canvas.vcxproj]
  D:\webServer\weixin\node\test\canvas-2.8\package\node_modules\nan\nan.h(2514): note: 参见“Nan::SetAccessor”的声明 (编译源文件 ..\src\ImageData.cc) 
d:\webserver\weixin\node\test\canvas-2.8\package\src\Util.h(31): error C2039: “toupper”: 不是“std”的成员 (编译源文件 ..\src\ImageData.cc) [D:\webServer\weixin
\node\test\canvas-2.8\package\build\canvas.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\queue(452): note: 参见“std”的声明 (编译源文件 ..\src\ImageData.cc)
d:\webserver\weixin\node\test\canvas-2.8\package\src\Util.h(17): warning C4996: 'Nan::SetAccessor': 被声明为已否决 (编译源文件 ..\src\CanvasRenderingContext2d.c
c) [D:\webServer\weixin\node\test\canvas-2.8\package\build\canvas.vcxproj]
  D:\webServer\weixin\node\test\canvas-2.8\package\node_modules\nan\nan.h(2514): note: 参见“Nan::SetAccessor”的声明 (编译源文件 ..\src\CanvasRenderingContext2
  d.cc)
d:\webserver\weixin\node\test\canvas-2.8\package\src\Util.h(31): error C2039: “toupper”: 不是“std”的成员 (编译源文件 ..\src\CanvasRenderingContext2d.cc) [D:\w
ebServer\weixin\node\test\canvas-2.8\package\build\canvas.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\map(15): note: 参见“std”的声明 (编译源文件 ..\src\CanvasRenderingContext2d.cc)      
d:\webserver\weixin\node\test\canvas-2.8\package\src\Util.h(17): warning C4996: 'Nan::SetAccessor': 被声明为已否决 (编译源文件 ..\src\Image.cc) [D:\webServer\we
ixin\node\test\canvas-2.8\package\build\canvas.vcxproj]
  D:\webServer\weixin\node\test\canvas-2.8\package\node_modules\nan\nan.h(2514): note: 参见“Nan::SetAccessor”的声明 (编译源文件 ..\src\Image.cc)     
d:\webserver\weixin\node\test\canvas-2.8\package\src\Util.h(31): error C2039: “toupper”: 不是“std”的成员 (编译源文件 ..\src\Image.cc) [D:\webServer\weixin\nod
e\test\canvas-2.8\package\build\canvas.vcxproj]

PS C:\Users\Administrator> node -v
v16.20.2
PS C:\Users\Administrator> npm -v
8.19.4
问一下为什么。我在 2.8.3是可以编辑的

**Comment by abcln** [comment]
PS C:\Users\Administrator> node -v
v16.20.2
PS C:\Users\Administrator> npm -v
8.19.4
问一下为什么。我在 2.8.3是可以编辑的

**Comment by zbjornson** [comment]
This issue was fixed in Canvas v2.9.1. Canvas 2.8 was released in 2021 and doesn't support Node 16 as well.
