### ISSUE TITLE
React 18+ Support?

### ISSUE THREAD

**Issue by enze-li-whatnot** [Automattic/node-canvas#2342]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Hi team, I am having trouble with using it on React 18+, this seems due to one package that we are using - @artsey/fresnel@3.5.0 that requires React < 18. I checked out artsey/fresnel's website and it seems they offer React 18+ support now https://github.com/artsy/fresnel. Was wondering if we can support React 18+? Thank you!

<img width="571" alt="image" src="https://github.com/Automattic/node-canvas/assets/102544906/d8f03eae-737d-4b7e-9093-0db489b6158f">

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment: 
"engines": {
    "node": ">=20.0.0",
    "npm": ">=6.14.15"
  },

**Comment by LinusU** [comment]
`canvas` doesn't depend on `@artsey/fresnel`, which can be verified by installing canvas to a clean project and running `npm ls @artsey/fresnel`.

It seems like there is some other package that you are having problem with...
