### ISSUE TITLE
v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz was not found for my mac m1

### ISSUE THREAD

**Issue by ghulamrasuldev** [Automattic/node-canvas#2351]
Use M1 Mac and try installing library: chartjs-node-canvas. 
It also depends on your library, which gives the following error: 

node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz 

That means build for canvas library for arm64 is missing.

**Comment by minega25** [comment]
facing similar issue

**Comment by coderfin** [comment]
I'm not associated with this project or https://github.com/Brooooooklyn/canvas but I found that https://www.npmjs.com/package/@napi-rs/canvas is a great replacement for node-canvas. `@napi-rs/canvas` supports Intel and Arm (M Chip) Macs with no system dependencies.  It supports all the same features that I needed.  It also supports `webp` which was a welcome bonus and is MIT license.

Instead of `registerFont` use `GlobalFonts.registerFromPath`; `createCanvas` and `loadImage` remain the same.

**Comment by fhigher** [comment]
facing similar issue

**Comment by adeelibr** [comment]
this issue is still valid

**Comment by mn4367** [comment]
Maybe [this](https://github.com/Automattic/node-canvas/issues/2353#issuecomment-1989229688) and the following comment helps.

**Comment by adeelibr** [comment]
I shared the solution here https://github.com/Automattic/node-canvas/issues/1511#issuecomment-2007391298 for apple m1 chip

**Comment by mn4367** [comment]
Just for the record, I didn't install node-gyp nor did I export CXXFLAGS. Having installed Xcode, brew and the dependencies mentioned in the README should be sufficient for installing canvas on Node **_20_** (as I mentioned, installing on Node **_21_** didn't work).

Can you can confirm that your procedure works on Node **_21_**?

**Comment by adeelibr** [comment]
I can confirm the solution worked for me on Node version 20

**Comment by mn4367** [comment]
So not on Node 21?

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this. 

> ### If you have an ARM CPU, including an Apple M1 or M2
> 
> Prebuilds aren't available for ARM. Please see the [wiki](https://github.com/Automattic/node-canvas/wiki#installation-guides) for guides on building from source. See also https://github.com/node-gfx/node-canvas-prebuilt/issues/69.

**Comment by ESW1234** [comment]
Following steps worked for me
`brew install pkg-config cairo pango libpng jpeg giflib librsvg`
`npm i chartjs-node-canvas`
`npm install`
