### ISSUE TITLE
Inflight - Missing Release of Resource after Effective Lifetime

### ISSUE THREAD

**Issue by Luen** [Automattic/node-canvas#2360]
This package depends on inflight, and it is vulnerable - [SNYK-JS-INFLIGHT-6095116](https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116) and [CWE-772: Missing Release of Resource after Effective Lifetime](https://cwe.mitre.org/data/definitions/772.html).

Introduced through: `canvas@2.11.2 › @mapbox/node-pre-gyp@1.0.11 › rimraf@3.0.2 › glob@7.2.3 › inflight@1.0.6` 

GitHub issues:
- [mapbox/node-pre-gyp#707](https://github.com/mapbox/node-pre-gyp/pull/707)
- [mapbox/node-pre-gyp#705](https://github.com/mapbox/node-pre-gyp/issues/705)
- [isaacs/node-glob#435](https://github.com/isaacs/node-glob/issues/435)
- [isaacs/node-glob#573](https://github.com/isaacs/node-glob/issues/573)
- [isaacs/inflight#5](https://github.com/isaacs/inflight/issues/5)
- [isaacs/inflight#19](https://github.com/isaacs/inflight/issues/19)

**Comment by zbjornson** [comment]
v3.0.0 drops node-pre-gyp as a dependency.
