### ISSUE TITLE
How to use prebuild for AWS lambda?

### ISSUE THREAD

**Issue by GeorgeTailor** [Automattic/node-canvas#2376]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

I am not sure how is this supposed to work, AWS lambda suggests to put external dependencies into separate zip with the following structure:
```
xray-sdk.zip
└ nodejs/node_modules/aws-xray-sdk
```

in case of canvas I would expect something like:

```
canvas.zip
└ nodejs/node_modules/canvas
```

however releases page includes confusing info:
1. the name of the release includes node_modules_version instead of node version
2. the downloaded zip contains nothing that is expected by the lambda as per docs

## Steps to Reproduce
-

## Your Environment
* Version of node-canvas [v2.11.2](https://github.com/Automattic/node-canvas/releases/tag/v2.11.2)
* Environment node 20 on AWS Lambda x86_64 – 64-bit x86 architecture, for x86-based processors.

**Comment by arcovaa** [comment]
simply copying the module from a non-Linux system won't work. You need to either compile the module directly on an Amazon Linux environment or use a Docker container that mimics Lambda's environment.

**Comment by zbjornson** [comment]
I recommend using a docker container on Lambda. The node-canvas prebuild is 30 MB and Lambda's ZIP limit is only 50 MB, so you're likely to hit that limit if you have many other dependencies. Using a docker container also makes it much easier to get the right prebuild installed.

https://docs.aws.amazon.com/lambda/latest/dg/nodejs-image.html#nodejs-image-instructions

---

I'm trying to close out as many of the dozens of installation issues as possible. If the above doesn't work and I miss a ping here to reopen this issue, please don't hesitate to open a new one.
