### ISSUE TITLE
loadImage function is not allowing use of await keyword

### ISSUE THREAD

**Issue by mgroovyank** [Automattic/node-canvas#2379]
## Issue or Feature
I'm trying to use loadImage function by using await keyword.

## Steps to Reproduce

```js
const { createCanvas, loadImage } = require("canvas");
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext('2d');
const myimg = await loadImage('./assets/image.png');

```
Here is the error:
> const myImg = await loadImage("./assets/image.jpg");
              ^^^^^
SyntaxError: await is only valid in async functions and the top level bodies of modules

## Your Environment
* Version of node-canvas: 2.11.2
* Environment: Node.js v20.12.2

**Comment by semohr** [comment]
The error message is clearly explaining the problem to you :) You can not use `await` in the top level of a module. There are a number of ways to fix that tho.

Set `"type": "module"` in the package.json or rename your file from `.js` to `.mjs`. Alternatively move the await from top level e.g.
```javascript
const { createCanvas, loadImage } = require("canvas");
const canvas = createCanvas(200, 200);
const ctx = canvas.getContext('2d');

let myImage;
async function load(){
    myImage = await loadImage('./assets/image.png');
}
load()
```

This is not an error in the canvas implementation!
