### ISSUE TITLE
Canvas fails to import after install

### ISSUE THREAD

**Issue by sojs-coder** [Automattic/node-canvas#2380]
## Issue or Feature

Node canvas fails to run, none of the issues listed in the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) helped me at all.

A simple `require` statement throws the error.

## Steps to Reproduce

```js
var Canvas = require('canvas');
```

One line... that is all.

Installed with 

```bash
npm i canvas
```

Did not build, everything seemed to install fine, no errors.

Here is what happens when I run the code....
![image](https://github.com/Automattic/node-canvas/assets/77751154/bc17a4b3-a75a-49fd-9eee-948fd2cf1765)

## Your Environment
* Version of node-canvas:
![image](https://github.com/Automattic/node-canvas/assets/77751154/222cc429-5255-4b53-94b0-8eb9ec6c17c1)

* Environment: node v20.11.1, Linux 22.04.1-Ubuntu x86_64 GNU/Linux, running in a REPL on repl.it

**Comment by namnguyenthanhwork** [comment]
Are you install on mac?

**Comment by sojs-coder** [comment]
no, this is on ubuntu @namnguyenthanhwork

**Comment by zbjornson** [comment]
I had to install libuuid (System Dependencies > search for "util-linux" and install "libuuid@2.38.1"), but then `npm install canvas@next` to install [v3.0.0-rc2](https://github.com/Automattic/node-canvas/releases/tag/v3.0.0-rc2) worked on repl.it.

---

I'm trying to close out as many of the dozens of installation issues as possible. If the above doesn't  work and I miss a ping here to reopen this issue, please don't hesitate to open a new one.
