### ISSUE TITLE
gyp: Undefined variable android_ndk_path in binding.gyp while trying to load binding.gyps

### ISSUE THREAD

**Issue by spz2020** [Automattic/node-canvas#2385]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

[install.txt](https://github.com/Automattic/node-canvas/files/15377899/install.txt)

## Steps to Reproduce

```js
npm install canvas --build-from-source
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): none
* Environment (e.g. node 20.9.0 on macOS 14.1.1): node v21.6.2 on Android (termux)

**Comment by StarSky919** [comment]
try this
```
mkdir ~/.gyp && echo "{'variables':{'android_ndk_path':''}}" > ~/.gyp/include.gypi
```

**Comment by zbjornson** [comment]
There are also some other issues with guidance about using canvas in termux: https://github.com/Automattic/node-canvas/issues?q=is%3Aissue+termux+ - in particular #1756 and #1609.

**Comment by edwardbeckett** [comment]
> try this
> 
> ```
> mkdir ~/.gyp && echo "{'variables':{'android_ndk_path':''}}" > ~/.gyp/include.gypi
> ```

You Rock...

**Comment by meverss** [comment]
> try this
> 
> ```
> mkdir ~/.gyp && echo "{'variables':{'android_ndk_path':''}}" > ~/.gyp/include.gypi
> ```

Finally it worked...!! Massive thanks...!! 👍🏾👍🏾

**Comment by ditt0132** [comment]
You Rock!!! I have this and almost trashed my toy project because of Fxxxking GYP error
thank you so much!!

**Comment by solemaire** [comment]
e.gypi
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
