### ISSUE TITLE
Compile Errors on XP with Visual Studio 2005 - Solved

### ISSUE THREAD

**Issue by hobberwickey** [Automattic/node-canvas#239]
I've spent the better part of today trying to get this to compile, and finally did so I thought I share what I did (not sure if this is the right place, they seem like errors in node-gyp). 

The first error was

"missing ";" before identifier "srwlock_" in C:\Documents and Settings\<user-name>\.node-gyp\0.8.16\deps\uv\include\uv-private\uv-win.h on line 187

To fix it I just comment out line 187, the problem is that SWRLOCK is not a valid in Windows XP (I think)

The next error was

LINK: fatal error LNK1181: cannot open file 'C:Documents.obj'...

The problem here was that the compiler was choking on the spaces in the pathname, so I downloaded the source, and ran

node-gyp configure

Then in I opened the project file in ../node-canvas/build and in 

project->canvas Properties->Configuration Properties->Linker ->Input->Additional Dependencies

I put quotes around "Documents and Settings" and took out the variable in the pathname (I forget what it was) and replaced it with the actual directory node.lib was in. After that it compiled, and canvas.node was in the Debug directory. 

Not easy but it worked. Hope this helps someone.

**Comment by Mugu-FG** [comment]
@hobberwickey I have the same problem when I try to install the node-oracledb. 

LINK: fatal error LNK1181: cannot open file 'C:Documents.obj'

So Can you let me know how to fix the file path issue.

Thanks

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
