### ISSUE TITLE
canvas@2.11.2 install: `node-pre-gyp install --fallback-to-build --update-binary`

### ISSUE THREAD

**Issue by shijorabi** [Automattic/node-canvas#2396]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

I getting this error when am  npm install

error:
canvas@2.11.2 install: `node-pre-gyp install --fallback-to-build --update-binary`

## Steps to Reproduce

npm install canvas

## Your Environment
* Version of node-canvas (2.11.2 ):
* Environment (node: 14.19.0, windows: 10)

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this.
