### ISSUE TITLE
Can't install node-canvas properly - Win7 x64

### ISSUE THREAD

**Issue by Krb686** [Automattic/node-canvas#242]
I've followed all of the instructions for installing node-canvas on windows and run into the exact same error that this person did.

https://github.com/LearnBoost/node-canvas/issues/226

But I don't understand what to do because nobody seemed to post a good solution on that page.  So any help?

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Please see the posted solution, or the updated wiki-page...
