### ISSUE TITLE
Create `v2.x` branch

### ISSUE THREAD

**Issue by diefbell-grabcad** [Automattic/node-canvas#2455]
In order to ensure v2 can still be supported with bug fixes etc, could we please have a `v2.x` branch, similar to how we have a `v1.x` branch. I assume branched from the `v2.11.2` commit.

**Comment by chearon** [comment]
Are you sure you can't use 3.0? It supports all supported versions of Node, and all v2 to v3 did was drop old Node versions. So I'm not sure I see the point in maintaining 2.x since we didn't break any APIs.

**Comment by chearon** [comment]
Feel free to reopen if there's a good counterargument
