### ISSUE TITLE
Package fontconfig was not found in the pkg-config search path

### ISSUE THREAD

**Issue by Qard** [Automattic/node-canvas#246]
Just tried installing canvas 1.0.0 from npm and I'm getting this error;

    > canvas@1.0.0 install /Users/stephenbelanger/Documents/Work/BlackcombGames/stats/node/node_modules/canvas
    > node-gyp rebuild

    Package fontconfig was not found in the pkg-config search path.
    Perhaps you should add the directory containing `fontconfig.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'fontconfig', required by 'cairo', not found
    Traceback (most recent call last):
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/gyp", line 18, in <module>
        sys.exit(gyp.main(sys.argv[1:]))
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/__init__.py", line 511, in main
        return gyp_main(args)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/__init__.py", line 494, in gyp_main
        options.circular_check)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/__init__.py", line 133, in Load
        depth, generator_input_info, check, circular_check)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/input.py", line 2378, in Load
        depth, check)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/input.py", line 384, in LoadTargetBuildFile
        build_file_data, PHASE_EARLY, variables, build_file_path)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/input.py", line 1027, in ProcessVariablesAndConditionsInDict
        ProcessConditionsInDict(the_dict, phase, variables, build_file)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/input.py", line 904, in ProcessConditionsInDict
        variables, build_file)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/input.py", line 975, in ProcessVariablesAndConditionsInDict
        variables, build_file, 'variables')
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/input.py", line 982, in ProcessVariablesAndConditionsInDict
        expanded = ExpandVariables(value, phase, variables, build_file)
      File "/Users/stephenbelanger/.node-gyp/0.8.15/tools/gyp/pylib/gyp/input.py", line 714, in ExpandVariables
        (contents, p.returncode))
    Exception: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/0.8.15/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:350:16)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
    gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
    gyp ERR! System Darwin 11.4.2
    gyp ERR! command "node" "/usr/local/Cellar/node/0.8.15/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/stephenbelanger/Documents/Work/BlackcombGames/stats/node/node_modules/canvas
    gyp ERR! node -v v0.8.15
    gyp ERR! node-gyp -v v0.7.1
    gyp ERR! not ok 
    npm ERR! canvas@1.0.0 install: `node-gyp rebuild`
    npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
    npm ERR! 
    npm ERR! Failed at the canvas@1.0.0 install script.
    npm ERR! This is most likely a problem with the canvas package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls canvas
    npm ERR! There is likely additional logging output above.

    npm ERR! System Darwin 11.4.2
    npm ERR! command "/usr/local/Cellar/node/0.8.15/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! cwd /Users/stephenbelanger/Documents/Work/BlackcombGames/stats/node
    npm ERR! node -v v0.8.15
    npm ERR! npm -v 1.1.66
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /Users/stephenbelanger/Documents/Work/BlackcombGames/stats/node/npm-debug.log
    npm ERR! not ok code 0

**Comment by dt1973** [comment]
Having the same problem on FreeBSD 10.1. `cairo-1.12.18_1,2` is installed. I've tried `export PKG_CONFIG_PATH=/usr/local/libdata/pkgconfig` to no avail:

```
# uname -a
FreeBSD test 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014
# npm install canvas
/
> canvas@1.1.6 install /usr/home/www/myapp/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System FreeBSD 10.1-RELEASE
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/www/myapp/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! FreeBSD 10.1-RELEASE
npm ERR! argv "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/www/myapp/npm-debug.log
```

**Comment by mltucker** [comment]
@dt1973 looks like pkg-config executable is not in your PATH?

**Comment by dt1973** [comment]
Indeed. Turns out I had to do `pkg install pkgconf`.

Thanks!

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...

**Comment by hasnainshafqatmlt** [comment]
seems like it's worked, waoO

`PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig/ npm install canvas `

**Comment by maple-leaf** [comment]
Add a note for installing for mac on macOS 10.13.2 using `brew`:
1. brew install pkg-config cairo libpng jpeg giflib fontconfig
2. export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
3. so far, `fontconfig.pc` and `libpng.pc` may not exist on `PKG_CONFIG_PATH,` so you need copy them into `PKG_CONFIG_PATH`

```
cp /usr/local/Cellar/libpng/1.6.34/lib/pkgconfig/libpng.pc /usr/local/lib/pkgconfig
cp /usr/local/Cellar/libpng/1.6.34/lib/pkgconfig /usr/local/lib/pkgconfig
```

4. now you should install `node-canvas` without any deps problem

**Comment by tomasdev** [comment]
```
brew install pkg-config cairo pango libpng jpeg giflib
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export PATH="/usr/local/opt/icu4c/bin:$PATH
export PATH="/usr/local/opt/icu4c/sbin:$PATH
cp /usr/local/Cellar/libpng/1.6.34/lib/pkgconfig/libpng.pc /usr/local/lib/pkgconfig
cp /usr/local/Cellar/fontconfig/2.12.6/lib/pkgconfig/fontconfig.pc /usr/local/lib/pkgconfig
npm i canvas
```

These are all the steps I had to do in my Mac, thanks @maple-leaf for 99% of that

**Comment by tigercosmos** [comment]
@toddwilkens  works well

**Comment by halfbeep** [comment]
on ubuntu 18* try:-

sudo apt-get install libfontconfig-dev

**Comment by talgalili** [comment]
Using `sudo apt install pkgconf` on linux mint worked for me. :)
