### ISSUE TITLE
Not working with Node version 22.11.0

### ISSUE THREAD

**Issue by umeshramya** [Automattic/node-canvas#2461]
Not working with Node version 22.11.0

**Comment by alumni** [comment]
Hey, you should provide a description of what's not working. Also, it's a good idea to check any existing open and closed issues.

Very likely it's a duplicate of https://github.com/Automattic/node-canvas/issues/2448.

**Comment by umeshramya** [comment]
I am unable to build my Next.js application written in TypeScript due to an issue that seems to be related to the `punycode` module. 

I am using the `canvas` Node module in my application. The build works with Node.js version 20.18.1, but it fails with version 22.11.0, which is the default Node.js version on GCP.

**Comment by birkskyum** [comment]
I see this too

**Comment by chearon** [comment]
Duplicate of #2448. (Try `npm install canvas@next`. We have to wait a few more days to get that version to be the default install).
