### ISSUE TITLE
Cannot find

### ISSUE THREAD

**Issue by WaveCloudx** [Automattic/node-canvas#2467]
Error: Cannot find module '../build/Release/canvas.node'

**Comment by WaveCloudx** [comment]
Error: Cannot find module '../build/Release/canvas.node'

**Comment by trikaladesignstudio** [comment]
can anyone help, what is going on with this issue, because i am still getting this issue in v3.0.0

 ⨯ Error: could not resolve "../build/Release/canvas.node" into a module
