### ISSUE TITLE
can't install canvas

### ISSUE THREAD

**Issue by frsanna** [Automattic/node-canvas#249]
when i try to install canvas i get this message:

[root@dev1 node.js](release/3.1 *)# npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas

> canvas@1.0.0 install /var/www/node.js/node_modules/canvas
> node-gyp rebuild

info it worked if it ends with ok 
spawn python [ '/root/.node-gyp/0.6.18/tools/gyp_addon',
  'binding.gyp',
  '-I/var/www/node.js/node_modules/canvas/build/config.gypi',
  '-f',
  'make' ]
spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/var/www/node.js/node_modules/canvas/build'
  CXX(target) Release/obj.target/canvas/src/Canvas.o
make: g++: Command not found
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 127
make: Leaving directory`/var/www/node.js/node_modules/canvas/build'
ERR! Error: `make` failed with exit code: 2
    at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:362:16)
    at Process.onexit (child_process.js:398:5)
ERR! not ok

npm ERR! canvas@1.0.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the canvas@1.0.0 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.2.34-55.46.amzn1.x86_64
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /var/www/node.js
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.21
npm ERR! code ELIFECYCLE
npm ERR! message canvas@1.0.0 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/node.js/npm-debug.log
npm not ok

what i can do??

**Comment by tiendunghaui** [comment]
Thanks BigSmurf  :+1:
