### ISSUE TITLE
Async version of toBuffer doesn't work with pdfs

### ISSUE THREAD

**Issue by nik9000** [Automattic/node-canvas#252]
The async version of toBuffer isn't working for me with pdfs.  I modified smallpdf.js to reproduce it.

Because the sync version of toBuffer works I doubt my cairo installation caused a problem but this is how I installed cairo:
sudo port install libpixman-devel cairo-devel libpng pango-devel +pdf

``` js

var Canvas = require('canvas')
  , canvas = new Canvas(400, 200, 'pdf')
  , ctx = canvas.getContext('2d')
  , fs = require('fs');

var y = 80
  , x = 50;

ctx.font = '22px Helvetica';
ctx.fillText('node-canvas pdf', x, y);

ctx.font = '10px Arial';
ctx.fillText('Just a quick example of PDFs with node-canvas', x, y += 20);

ctx.globalAlpha = .5;
ctx.fillRect(x, y += 20, 10, 10);
ctx.fillRect(x += 20, y, 10, 10);
ctx.fillRect(x += 20, y, 10, 10);

canvas.toBuffer(function (err, buf) {
  if (err) return console.log(err.stack);
  fs.writeFileSync('out.pdf', buf);
  console.log('created out.pdf');
});
```

**Comment by zbjornson** [comment]
`toBuffer(callback)` for PDF: no support yet, tracking in #821.

The issue in the second comment appears unrelated and is likely fixed.
