### ISSUE TITLE
Cannot render more than one "default" font on Centos 6.2

### ISSUE THREAD

**Issue by adyzah** [Automattic/node-canvas#253]
Hi,

I've installed the node-canvas module on a Centos 6.2, all went ok. The problem i have is that no matter which font i set, it always outputs as just one font.

node : 0.8.18
cairo: 1.10.2
pixman : 0.22.0
canvas module : 1.0.0

This bit for example:

```javascript
var Canvas = require('canvas')
  , canvas = new Canvas(200,200)
  , ctx = canvas.getContext('2d');

ctx.font = '30px Arial';
ctx.fillText("Awesome!", 0, 25);

ctx.font = '30px Courier';
ctx.fillText("Awesome!", 0, 75);

ctx.font = '30px Helvetica';
ctx.fillText("Awesome!", 0, 125);

ctx.font = '30px Verdana';
ctx.fillText("Awesome!", 0, 175);
```

will look like:

![text](https://f.cloud.github.com/assets/1619308/112858/a3d8af20-6b2d-11e2-963c-a53d3dd017ff.png)

I tried more fonts, taken from the fc-list output, same result :(

I had a similar issue on a RedHat, i *think* i fixed the issue there by installing every font package i could find but when i did same thing on Centos it did not work...

Any idea?

Thanks in advance

**Comment by LinusU** [comment]
Closing this since it's an old thread, please report back if you still have problems...
