### ISSUE TITLE
Images anti-antialias doesn't seem to work

### ISSUE THREAD

**Issue by iMoses** [Automattic/node-canvas#256]
I'm trying to produce animation file using node.js and the node-canvas package, extracting frame by frame. Part of the animation includes scaling and moving images. My problem is that no anti-aliasing seems to be happening although according to the manual anti-aliasing should be done by default and can be controlled using `ctx.antialias = 'gray';` (e.g.) but it doesn't seem to do anything either. If there's any more details I can provide that may help please let me know. Is there any way, using node-canvas or even cairo directly, to add anti-aliasing to image transformations?

**Comment by zbjornson** [comment]
Closing as a dupe of #263, which has a lot of discussion.
