### ISSUE TITLE
Inspecting canvas object in node-inspector crashes node

### ISSUE THREAD

**Issue by hura** [Automattic/node-canvas#258]
If I hook up node-inspector I can step through the code fine but as soon as I 'inspect' a canvas object it'll crash:

    .node-gyp/0.8.6/src/node_object_wrap.h:52: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = Canvas]: Assertion `handle->InternalFieldCount() > 0' failed.

Minimal working example should be a simple:

    var Canvas = require('canvas')
    var canvas = new Canvas(w,h)

**Comment by chylvina** [comment]
+1

**Comment by dfoody** [comment]
+1 on io.js 2.3.4 with canvas 1.2.3

**Comment by hometlt** [comment]
+1

**Comment by LinusU** [comment]
Duplicate of #76

**Comment by DaviesGit** [comment]
+1

**Comment by LinusU** [comment]
@DaviesGit this was fixed by #808
