### ISSUE TITLE
Install error with gyp package gobject-2.0 

### ISSUE THREAD

**Issue by johholl** [Automattic/node-canvas#272]
Everything was running propper on my mac.
That it happend out of nowhere ... 
BAM... Canvas didn't work.

I tried to reinstall it - here is the error message:

package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gobject-2.0', required by 'cairo', not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:415:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 12.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
 
Can someone please help - i am not a genius is this stuff :-)

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...

**Comment by jniac** [comment]
An old issue ? 2013, indeed... but i have that same problem today:
macOS High Sierra 10.13.3 (17D47)  
first i run (according to the instructions) :
```shell
brew install pkg-config cairo pango libpng jpeg giflib
```
then for each package i got that warning
`xxxx is installed but not linked
You can use `brew link giflib` to link this version.`

so i linked everything but when i run `npm add canvas`
i got the same error as the one above : 

```> canvas@1.6.9 install /Users/joseph/Documents/WIP.local/me/export-image/node_modules/canvas
> node-gyp rebuild

Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gobject-2.0', required by 'cairo', not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
....```

**Comment by FIVELONG** [comment]
> An old issue ? 2013, indeed... but i have that same problem today:
> macOS High Sierra 10.13.3 (17D47)
> first i run (according to the instructions) :
> 
> ```shell
> brew install pkg-config cairo pango libpng jpeg giflib
> ```
> 
> then for each package i got that warning
> 
> ```
> xxxx is installed but not linked  
> You can use 'brew link xxxx' to link this version.
> ```
> so i linked everything but when i run `npm add canvas`
> i got the same error as the one above :
> 
> ```shell
> > canvas@1.6.9 install /Users/joseph/Documents/WIP.local/me/export-image/node_modules/canvas
> > node-gyp rebuild
> 
> Package gobject-2.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `gobject-2.0.pc'
> to the PKG_CONFIG_PATH environment variable
> Package 'gobject-2.0', required by 'cairo', not found
> gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
> ... 
> ```

same question,did u handle it?
