### ISSUE TITLE
ctx#arc must have six parameters?

### ISSUE THREAD

**Issue by fundon** [Automattic/node-canvas#274]
In browser, draw a full circle, we can use

``` js
// First.
ctx.arc(0, 0, 50, 0, Math.PI * 2, false)
// Or
// Second.
ctx.arc(0, 0, 50, Math.PI * 2, false)
```

Can I use second in the node-canvas?

**Comment by winstonewert** [comment]
It's not the last argument that's elided. The standard canvas api lets you skip the fourth argument, defaulting it to zero. That doesn't seem to work in this implementation.

**Comment by LinusU** [comment]
Yeah, we should fix this, pull request welcome :+1:

**Comment by winstonewert** [comment]
Looking again, it appears that, I was simply using the api wrong, but I get away with it in chrome (perhaps other browsers) but not in node-canvas.

ctx.arc(0, 0, 50, Math.PI * 2, false)

Gets interpreted as:

ctx.arc(x=0, y=0, radius=50, startAngle=Math.PI * 2, endAngle=false)

Where the endAngle gets interpreted as 0, thus accidently doing what I wanted.

It looks like node-canvas simply ignores calls to arc which don't have the correct types. Is this simply a more general problem of not coercing arguments the way that javascript would?
