### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas'

### ISSUE THREAD

**Issue by DrMiaow** [Automattic/node-canvas#284]
Getting this issue under Debian.

checked out this repository and ran make

Tried to run the example, but no joy.

root@linuxlab:/home/tw-nodejs/lab/node-canvas/examples# node clock.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/canvas'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/tw-nodejs/lab/node-canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by sungwoncho** [comment]
I am experiencing the same issue. @benmorris44's solution throws:

    gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp

Any update on this one?

**Comment by gleerman** [comment]
@sungwoncho 's suggestion did it for me. I got the error after doing an `npm update`, but doing `npm install` separately afterwards fixed the issue

**Comment by pbadger** [comment]
@DrMiaow Did you solve this?

I'm seeing

`> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:10:
../src/CanvasPattern.h:23:9: warning: private field '_width' is not used [-Wunused-private-field]
    int _width, _height;
        ^
../src/CanvasPattern.h:23:17: warning: private field '_height' is not used [-Wunused-private-field]
    int _width, _height;
                ^
2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
In file included from ../src/FontFace.cc:7:
../src/FontFace.h:27:15: warning: private field '_ftFace' is not used [-Wunused-private-field]
    FT_Face   _ftFace;
              ^
1 warning generated.
  SOLINK_MODULE(target) Release/canvas.node`

but then when I try to run browserify with babel (browserify -t babelify -o "outfile.js"), I get 

`Error: Cannot find module '../build/Release/canvas' from '/Users/pbadger/Desktop/gigster/Seizin/node_modules/canvas/lib'`

@gleerman What is the contents of your build/Release folder? I have
 
`canvas-postbuild.node           canvas.node           obj.target (directory)` - does the canvas.node file mean this isn't an issue with canvas?

**Comment by LinusU** [comment]
@pbadger You won't be able to use this module in the browser since it's built in C++ together with other compiled libraries.

There have been discussions of adding a `browser` field to the package.json with a small shim though, I think that there is another package that wraps this with that currently...

**Comment by mathisonian** [comment]
@LinusU do you or anyone else have a link to this package?

> There have been discussions of adding a browser field to the package.json with a small shim though, I think that there is another package that wraps this with that currently...

**Comment by seajean** [comment]
still have this problem,and my canvas version is 1.6.1

**Comment by incism** [comment]
Still have this problem-- my canvas version is 1.6.2

Error: Cannot find module '../build/Release/canvas' from '/home/mine/app/node_modules/canvas/lib'

**Comment by astw** [comment]
Still have this problem on version 1.7.3

**Comment by marcelkalveram** [comment]
Having the same issue here. Works on my MacBook's local environment, but fails on Heroku.

**Comment by marcelkalveram** [comment]
The problem in my case was that Heroku was using `yarn` to install dependencies. I removed the `yarn.lock` file, so `npm` took over and ran the install script for node-canvas (which for some reason got omitted with yarn). That created the missing `build` folder for me, and my app is running fine now.

**Comment by mini-eggs** [comment]
@ marcelkalveram It wasn't necessarily Yarn causing issues, but that Heroku's Yarn cache wasn't snagging node_modules/canvas/Release/. That may have been why you seen it fail with Yarn.

To fix this up I've added the following to my package.json scripts
```
"postinstall": "cd node_modules/canvas && node-gyp rebuild"
```

You'll need canvas and node-gyp in your dependencies for this to work.

**Comment by moeiscool** [comment]
```
Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/Shinobi/plugins/calebtaylor-alpr/node_modules$
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

canvas 1.6

Install looked ok like every other machine i installed it on. Just this one it keeps doing this when i start my script. Please fix this.

**Comment by timbowhite** [comment]
Just ran into this really fun experience with node v10.16.3/Centos 8/canvas@. Adding the following to my package.json scripts fixed it:
```
  "scripts":{
    "postinstall" : "cd node_modules/canvas && /usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild"
  }
```
Then run:
```
npm install
npm run postinstall
```

**Comment by Saad-Abbasi** [comment]
@timbowhite i am getting this error `The system cannot find the path specified.`

**Comment by wilmaribg** [comment]
Ubuntu:
$ sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
$ npm install node-gyp
$ npm install --build-from-source
