### ISSUE TITLE
Image given has not completed loading

### ISSUE THREAD

**Issue by tarunkurapati** [Automattic/node-canvas#289]
Error:
      Error: Image given has not completed loading
    at /home/f-user/passport-facebook/examples/login/app.js:315:17
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15) 

Code:

var canvas = new Canvas(650, 650)
                               , ctx = canvas.getContext('2d');
fs.readFile(__dirname + '/public/resimg/1.jpg', function(err, squid){
      if (err) throw err;
        img = new Canvas.Image;
          img.src = squid;
          img.onload = function(){
              console.log("ian here in onload");
            ctx.drawImage(img, 0, 0, img.width / 4, img.height / 4);
          }
});

I have seen similar issues here, they mentioned to use "img.onload" in case we get this error "Image given has not completed loading"

But img.onload is not getting fired in my case.
May i know how to fix for this issue.
Thanks

**Comment by redspider** [comment]
For everybody on this ticket and for all those who will arrive in the future, please note that this error message MAY occur because you are attempting to load an image type that canvas does not support - probably due to a limited cairo build. You can verify this by trying to load a PNG instead which is typically supported.

**Comment by dosapati** [comment]
Having the same issue to load jpg images. Tried installing libjpeg through brew still no luck. Works for PNG images and not for JPG images

**Comment by noam3127** [comment]
I was having this same problem, and the solution given by **yhostc** discussed in [this issue](https://github.com/Automattic/node-canvas/issues/348) ended up solving it:
brew update
brew doctor
xcode-select --install
brew install cairo gobject-introspection pixman

**Comment by tomerb15** [comment]
@redspider How can we add JPEG support for node-canvas?

**Comment by redspider** [comment]
@tomerb15 node-canvas doesn't care about image types, if I recall correctly it is cairo that cares (cairo is a dependency). You have to make sure your cairo build has JPEG enabled. I can't help you with that though.

**Comment by coolfeature** [comment]
I was having the issue every time when I tried to render the PNG image below onto the canvas.  

![withinkscapechunk](https://cloud.githubusercontent.com/assets/6413939/13752268/df832f32-ea05-11e5-99ac-628fd9df2917.png)

I noticed that the rendering worked fine for other PNG images. So I used a hex editor (http://entropymine.com/jason/tweakpng/) to see what is different about the file. 

The obvious difference was the header:
 
![hex](https://cloud.githubusercontent.com/assets/6413939/13752490/cd25261e-ea06-11e5-9f53-0706e8d9cee9.png)

I removed the ancillary tEXt chunk, saved the file and re-rendered without any errors.

This fixed the issue for me. There might me other chunks that confuse canvas when rendering. It would be really nice to have some basic data cleansing there to save us fiddling around with binary formats.

**Comment by jshin49** [comment]
I'm having the same problem even when I use readFileSync.

My OS is Windows 10, and I've installed node-canvas as guided, and somehow it always fails with
drawImage function.

**Comment by HaoCherHong** [comment]
@redspider the reason of getting this error message is that when we try to use(draw) the image, it's actually not completed loaded yet. If you add a handler on img.onerror you will see this error instead:  "Error: error while reading from input stream". And we should stop processing right there.

**Comment by yeldarby** [comment]
I was getting this as well which was weird because I was sure the image was loaded before setting the data. But as mentioned above setting an `onerror` handler gave me a (weird) error.

It said "Out of memory" but it clearly wasn't. The issue ended up being a sRGB color profile that libpng didn't like. Stripping that fixed my issue. (in case anyone is ending up here from a google search like I did)

In my case it was `IEC619966-2.1` that was the problem. Other pngs with other profiles worked fine.

**Comment by endquote** [comment]
I'm running into this on two Windows 7 machines and a Windows 10 machine. The image files are normal JPGs, and the same code with the same images works great on macOS.

**Comment by endquote** [comment]
As others have found, it looks like when following the install instructions for Windows (installing libjpgturbo), Cairo gets built without JPG support. The same code works fine if you work with PNGs.

So... maybe it's just a documentation issue?

**Comment by zbjornson** [comment]
There are a few different issues in this thread.

@endquote and @jshin49 JPEG support for Windows is PR #841 and isn't merged yet (but is functional if you want to use his fork). I'm not sure exactly what you're doing without more context, but that is likely what you're hitting.

@yeldarby That's interesting and I think merits a new issue. The only other issue I see for color profiles is #725, which isn't what you've described.

A lot of the other reports I think are from building node-canvas without libjpeg support (at least three different posters). For debian/ubuntu this means having libjpeg-dev (or a variant), for MacOS see the wiki instructions https://github.com/Automattic/node-canvas/wiki/Installation---OSX#having-trouble-with-gif-or-jpegs. For windows, as above, that means using the fork in #841 or waiting for that to be merged.

Finally, a lot of this is better described in #486 ("not completed loading" is misleading) -- this error message occurs in a variety of situations unrelated to image loading: in addition to having a build without JPEG support, it apparently happens specifically for some color profiles (https://github.com/Automattic/node-canvas/issues/289#issuecomment-283699138) and unhandled PNG header chunks (https://github.com/Automattic/node-canvas/issues/289#issuecomment-196415998).

**Comment by zbjornson** [comment]
Closing per above.
