### ISSUE TITLE
Can't install on AWS EC2

### ISSUE THREAD

**Issue by aleiby** [Automattic/node-canvas#291]
I followed the instructions here:
https://github.com/LearnBoost/node-canvas/wiki/Installation---Amazon-Linux-AMI-(EC2)

However, I grabbed the latest stable versions of everything:
cairo-1.12.14
freetype-2.4.12
jpeg-9
libpng-1.6.2
pixman-0.30.0

$PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

Here's the error output:

$ npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas

> canvas@1.0.3 install /home/ec2-user/server/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/home/ec2-user/server/node_modules/canvas/build'
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:18:
../src/JPEGStream.h: In function ‘boolean empty_closure_output_buffer(jpeg_compress_struct*)’:
../src/JPEGStream.h:43: error: cannot convert ‘bool’ to ‘boolean’ in return
../src/JPEGStream.h: In function ‘void write_to_jpeg_stream(cairo_surface_t*, int, int, closure_t*)’:
../src/JPEGStream.h:114: error: invalid conversion from ‘int’ to ‘boolean’
../src/JPEGStream.h:114: error:   initializing argument 3 of ‘void jpeg_set_quality(jpeg_compress_struct*, int, boolean)’
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory`/home/ec2-user/server/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.4.43-43.43.amzn1.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/server/node_modules/canvas
gyp ERR! node -v v0.10.10
gyp ERR! node-gyp -v v0.9.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by erhhung** [comment]
These are the latest lib versions with which I've successfully compiled canvas:

http://sourceforge.net/projects/libpng/files/libpng16/1.6.21/libpng-1.6.21.tar.xz (_latest_)
http://www.ijg.org/files/jpegsrc.v8d.tar.gz (**do not use v9 or above**)
http://www.cairographics.org/releases/pixman-0.34.0.tar.gz (_latest_)
http://download.savannah.gnu.org/releases/freetype/freetype-2.6.tar.gz (_latest_)
http://cairographics.org/releases/cairo-1.14.6.tar.xz (_latest_)
