### ISSUE TITLE
Forgetting 'new' keyword causes node to crash

### ISSUE THREAD

**Issue by tjlahr** [Automattic/node-canvas#294]
The following code causes my node repl to crash. While it's up to the developer to remember the 'new' keyword, it would be nice if the library threw a more intelligible error.

```
var Canvas = require('canvas');
var cvs = Canvas(100, 200);
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file ../src/node_object_wrap.h, line 71.
Abort trap: 6
```

**Comment by LinusU** [comment]
Haha, this is still a problem, I'll fix it now :laughing:
