### ISSUE TITLE
segfault in canvas.streamJPEGSync

### ISSUE THREAD

**Issue by stroncium** [Automattic/node-canvas#297]
Calling streamJPEGSync with bufSize = 0 sometimes causes Segmentation Fault.

Cairo version: 1.12.12
JPEG version: 8
(reported by node-canvas)
nodejs version: v0.11.3-pre (git head one week old or so)

I've also encountered cases when it was throwing something like "corrupted double-linked list" error, but I can't reproduce it now and logs are out of history.

**Comment by zbjornson** [comment]
@Hakerh400 says they can't repro in https://github.com/Automattic/node-canvas/pull/1245#issue-214139919, so closing.
