### ISSUE TITLE
Fonts Problem

### ISSUE THREAD

**Issue by BigSmurf** [Automattic/node-canvas#298]
Hi...

I created a code to create an image from a text but if i try to use a different font the generated image still remain the same.

Any idea?

I reload my old working code:

// Recreate canvas with right txt size
  canvas = new Canvas(width, height);
  ctx = canvas.getContext('2d');
  ctx.font = font;

  console.debug(ctx.font); // TODO to remove

  // Rotate text
  if(config.orientation == 'right'){
    wheel = -Math.PI/2;
    ctx.translate(width/2 - config.font_size/4, height/2);
  }
  else if(config.orientation == 'left'){
    wheel = Math.PI/2;
    ctx.translate(width/2 + config.font_size/4, height/2);
  }  

  ctx.rotate(wheel);

  ctx.fillStyle = config.text_color;
  ctx.fillText(config.text, -x, y);
  var stream = canvas.createPNGStream();

  stream.on('data', function(chunk){
    out.write(chunk);
  }); 

and using fc-list all the font are installed.

Please I need a solution.

**Comment by LinusU** [comment]
I'm guessing that this is fixed in 2.x, happy to reopen otherwise...
