### ISSUE TITLE
A way to determine if canvas was compiled with necessary features at runtime

### ISSUE THREAD

**Issue by mitar** [Automattic/node-canvas#299]
I would request a way to test if canvas was compiled necessary features at runtime. Something like `canvas.features.JPEG` or `canvas.features.FREETYPE`. Because canvas can compile successfully even without some features it would be useful to be able to check for them and complain if they are required by the app.

**Comment by LinusU** [comment]
@mitar Coming right up :+1:

**Comment by mitar** [comment]
+1
