### ISSUE TITLE
Install on Centos (Following ec2 instructions)

### ISSUE THREAD

**Issue by craigwinstanley** [Automattic/node-canvas#303]
Everything perfect bar the following, i dont know if you want to test and correct me if im wrong.

libpng file thats listened on the instructions no longer exists;
FIX: i downloaded the following and managed to continue as instructed: http://sourceforge.net/projects/libpng/files/libpng15/1.5.17/libpng-1.5.17.tar.gz/download

I also needed to download zlib from the same repo and precompile that the exact same way as installing everything else

freetype file no longer exists;
FIX: downloaded the following and managed to continue; http://download.savannah.gnu.org/releases-redirect/freetype/freetype-2.4.11.tar.gz

Much appreciated and love node-canvas keep up the awesome work

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
