### ISSUE TITLE
Add data uri jpeg support

### ISSUE THREAD

**Issue by tj** [Automattic/node-canvas#31]
currently only supports image/png

**Comment by superRaytin** [comment]
is there any news?

**Comment by zbjornson** [comment]
You can do this manually following what's in [the test suite](https://github.com/Automattic/node-canvas/blob/master/test/server.js#L86-L100).

```
var stream = canvas.jpegStream();
var buffers = [];
var result;
stream.on('data', function (chunk) {
    buffers.push(chunk);
});
stream.on('end', function() {
    result = 'data:image/jpeg;base64,' + Buffer.concat(buffers).toString('base64');
});
// result is a jpeg data URI
```

Making a pull request now to fix this...

**Comment by LinusU** [comment]
@zbjornson maybe it would be a good idea to use a streaming base64 encoder? That way we don't have to encode the entire buffer in one go on the "main thread"

**Comment by zbjornson** [comment]
Hm, perhaps -- but `jpegStream` is sync always, so I'm not sure it would make a difference for that case?

**Comment by superRaytin** [comment]
@zbjornson that's awesome, thx a ton!
