### ISSUE TITLE
Passing flags to MSVS

### ISSUE THREAD

**Issue by ngryman** [Automattic/node-canvas#322]
Hi,

I'm currently developing a `node` addon, and faced the same issue: you can't pass `cflags` to `msvs` with `node-gyp`.

After some search, you can use the `msvs_settings` key to pass arguments to the `VCCLCompilerTool`, which basically allows you to set flags.

For example, this is how I disable a specific warning:
```json
"msvs_settings": {
  "VCCLCompilerTool": {
    "DisableSpecificWarnings": [ "4267" ]
  }
}
```

Here is a complete list of the flags you can pass: https://code.google.com/p/gyp/source/browse/trunk/pylib/gyp/MSVSSettings.py?r=904#451.

Hope this can help.

**Comment by LinusU** [comment]
I believe that we indeed do use this now :)
