### ISSUE TITLE
Any possible way to compress PNG or use indexed RGB on node-canvas?

### ISSUE THREAD

**Issue by hunt** [Automattic/node-canvas#332]
I'm not sure is it possible or not? by node-canvas api after we use "createPNGStream" image will be in indexed rgb format or PNG-8

Thank you!

**Comment by mathiasbynens** [comment]
@kkoopa Could you clarify how #306 enables saving an indexed PNG8 file? It doesn’t seem like [any of the filters](https://github.com/Automattic/node-canvas/issues/306#issuecomment-22070405) map to that directly.

The only PNG8 example I see is [using node-mapnik](https://github.com/Automattic/node-canvas/issues/306#issuecomment-37083195).

**Comment by kkoopa** [comment]
It does not enable indexed PNG8, just setting zlib compression level and filters.

**Comment by mathiasbynens** [comment]
Thanks for clarifying, @kkoopa!

I guess this issue could be reopened and repurposed/renamed as “Make it possible to use PNG8 palette”, then.

**Comment by zbjornson** [comment]
@mathiasbynens FWIW, I've been starting to use this library with indexed PNG encoding by using one of the RGBA channels (e.g. A) as our palette indices, calling `toBuffer("raw")`, extracting and packing every 4th byte, and then using a different PNG encoding function to write the indexed PNG (we made our own; you can bind to libpng or lodepng for example).

I was toying with what an API in node-canvas could look like, e.g.

```js
var c = new Canvas(w, h, "palette8" /* or "alpha8" or "png8" or ... */);
c.pngStream({palette: /* a Uint8ClampedArray of RGBA values */});
```

which seems all and well until you get to `getImageData` and `putImageData` -- if the returned pixel array is just one channel, it's compact and easy to work with but doesn't follow the Canvas specification; if it is unpacked and returns all four channels, it's bigger and harder to work with but follows the Canvas spec.

**Comment by zbjornson** [comment]
Actually, I just discovered PR #678, which lets you set any of Cairo's native formats (including alpha8). @mathiasbynens that would be a good place to discuss this further.

**Comment by LinusU** [comment]
Reopening this until we can get it resolved :)
