### ISSUE TITLE
Error installing canvas on RHEL

### ISSUE THREAD

**Issue by stefanocog** [Automattic/node-canvas#334]
Hi, tryng to install canvas on RHEL, by following this guide https://github.com/LearnBoost/node-canvas/wiki/Installation---Amazon-Linux-AMI-%28EC2%29 , i get this error:

npm install --nodedir=/var/tmp/node-master canvas

npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas

> canvas@1.1.0 install /root/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/root/node_modules/canvas/build'
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.h:22,
                 from ../src/Canvas.cc:7:
../src/nan.h:440: error: â€˜uv_work_tâ€™ does not name a type
../src/nan.h: In constructor â€˜NanAsyncWorker::NanAsyncWorker(NanCallback*)â€™:
../src/nan.h:416: error: â€˜requestâ€™ was not declared in this scope
../src/nan.h: At global scope:
../src/nan.h:473: error: variable or field â€˜NanAsyncExecuteâ€™ declared void
../src/nan.h:473: error: â€˜uv_work_tâ€™ was not declared in this scope
../src/nan.h:473: error: â€˜reqâ€™ was not declared in this scope
../src/nan.h:478: error: variable or field â€˜NanAsyncExecuteCompleteâ€™ declared void
../src/nan.h:478: error: â€˜uv_work_tâ€™ was not declared in this scope
../src/nan.h:478: error: â€˜reqâ€™ was not declared in this scope
../src/nan.h: In function â€˜void NanAsyncQueueWorker(NanAsyncWorker*)â€™:
../src/nan.h:486: error: â€˜uv_default_loopâ€™ was not declared in this scope
../src/nan.h:487: error: â€˜class NanAsyncWorkerâ€™ has no member named â€˜requestâ€™
../src/nan.h:488: error: â€˜NanAsyncExecuteâ€™ was not declared in this scope
../src/nan.h:489: error: â€˜uv_after_work_cbâ€™ was not declared in this scope
../src/nan.h:490: error: â€˜uv_queue_workâ€™ was not declared in this scope
In file included from ../src/Canvas.cc:7:
../src/Canvas.h: At global scope:
../src/Canvas.h:67: error: â€˜uv_work_tâ€™ has not been declared
../src/Canvas.h:68: error: â€˜uv_work_tâ€™ has not been declared
../src/Canvas.cc:168: error: variable or field â€˜ToBufferAsyncâ€™ declared void
../src/Canvas.cc:168: error: â€˜uv_work_tâ€™ was not declared in this scope
../src/Canvas.cc:168: error: â€˜reqâ€™ was not declared in this scope

any ideas?

thanks
Stefano

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
