### ISSUE TITLE
Installation On Windows 8 x64 

### ISSUE THREAD

**Issue by ZeroHackeR** [Automattic/node-canvas#335]
Using
- node v0.10.15 x64
- python 2.7.3
- gtk 2.22
- VS 2012 Ultimate
- node-gyp 0.10.10

They were individually tested and working.

And canvas installation failed... 
![2013-10-08_0942](https://f.cloud.github.com/assets/3157700/1286181/98854692-2fc7-11e3-8a0e-93a029b1899d.png)

where can I find this common.gypi ?

**Comment by Agamnentzar** [comment]
Setting default visual studio version and fixing include paths (#589) fixed the issue for me.
```
npm config set msvs_version 2013 --global
```

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
