### ISSUE TITLE
Context2d#drawImage() throws 'TypeError: Image or Canvas expected' when called with Image

### ISSUE THREAD

**Issue by nooga** [Automattic/node-canvas#338]
I don't know if it's a node-canvas issue but everything else looks good to me.

I load the image like this:

``` javascript
var Image = require('canvas').Image;
//...
fs.readFile(obj.bigsrc, function(err, imgbuf){
        that.overlayImage = new Image();
        that.overlayImage.src = imgbuf;
});
```

And then, after some time, when the promise for preloading images is fulfilled:

``` javascript
      var ctx = this.canvas_api.nodeCanvas.getContext('2d'); //via fabric
      console.log(this.overlayImage);
      ctx.drawImage(this.overlayImage, 0, 0, this.w, this.h);
```

`console.log` outputs `[Image:1920x1080 complete]` but `drawImage` throws the following exception:

```
TypeError: Image or Canvas expected
```

This `[Image:1920x1080 complete]` is not very descriptive but suggests that the image is loaded properly and ready to be displayed. It also suggests that the type of passed object is `Image`.

I don't have any idea what's wrong and how to debug this problem.

Edit: node v0.10.18, node-canvas v1.1.0

**Comment by typpo** [comment]
A note for future travelers who are troubleshooting this error caused by multiple versions of the `canvas` dependency: you can force a version of the `canvas` library in `package.json` by specifying [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in npm >= 8 or [`resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it) in yarn >= 1

**Comment by ggolda** [comment]
@typpo could you please explain how exactly you overrode canvas dependencies :smile: 
I tried this and it didn't change anything:

```
"overrides": {
  "fabric": {
    "canvas": "^2.11."
  }
}
```

**Comment by GrayedFox** [comment]
@ggolda you've probably figured it out but you would in this case overwrite the canvas version number directly instead of nesting it under a parent module, like so:

```json
{
  "overrides": {
    "canvas": "3.0.0-rc2"
  }
}
```

Note that major version differences usually indicate breaking changes if the module follows semantic versioning.
