### ISSUE TITLE
The surface type is not appropriate for the operation

### ISSUE THREAD

**Issue by Rinkoo** [Automattic/node-canvas#344]
My code (running on NodeJS 0.10.13, VS 2012, Windows 8.1 x64) constantly received 'Error: the surface type is not appropriate for the operation' message after invoked canvas.toBuffer() method. I was trying to reinstall any components used by node-canvas and compiled canvas.node as x86 and X64 versions, but still got no luck... 

Any help or tips would be appreciate.

---

Typically this type of error is from your code rather than a bug exists in library.

**Comment by ankitjaininfo** [comment]
{{parseInt}} worked like a charm. BTW, the error message is so cryptic.

**Comment by DustinWoods** [comment]
Had the same issue - turned out my width/height values for `new Canvas()` were NaN.

**Comment by adiusz** [comment]
Yep, I can confirm that createCanvas and fillRect have some problem with passing variables as a parameters. 
I had to pass variables like that `createCanvas(Number(width), Number(height))`
`parseInt` was not working for me.

**Comment by Leavoh** [comment]
Thank yall! For me the width and height values were also null!

**Comment by fermiverse** [comment]
This error also seems to occur for zero width/height values.
