### ISSUE TITLE
Install Problem: 'jpeglib.h' file not found

### ISSUE THREAD

**Issue by georgecoltart** [Automattic/node-canvas#348]
I've been going round the bend trying to solve this. 
When I attempt to install I get: 

```
npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> canvas@1.1.1 install /Users/georgecoltart/Sites/tilestitch/node_modules/canvas
> node-gyp rebuild

  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:19:
../src/JPEGStream.h:11:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/georgecoltart/Sites/tilestitch/node_modules/canvas
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

```

Having done a search, the jpeglib.h file is in /usr/include/jpeglib.h
I'm pretty sure I installed it correctly, but it must be a broken reference. 

Can someone tell me where this jpeg lib is expected to be located for the canvas install to find it?

Thanks a lot.

**Comment by dosapati** [comment]
Had the same issue, yhostc's solution solved it, thank you

**Comment by theyaserfox** [comment]
No one of these solutions helped in my case, but this helped fix it :
https://gist.github.com/darul75/9125097

**Comment by piranna** [comment]
I think node-canvas should download the dependencies and compile them statically to prevent this problems...

**Comment by Drjacky** [comment]
What about in ubuntu?!

**Comment by piranna** [comment]
My fork download all dependencies and compike them statically inside the canvas.node binary, so these problems are not happening anymore. I did a pull-request sometime ago.

**Comment by dbkaplun** [comment]
+1

**Comment by lizhanhui** [comment]
For Ubuntu users, please install the package: libjpeg-dev
It works for Wily(15.04 64bit).

**Comment by 0326** [comment]
$ xcode-select --install  works for mac!

**Comment by tomerb15** [comment]
I did a lot of the things writen here for my mac OSX but non seam to work.

Finally i uninstalled node-canvas from my node_modules library and reinstall it and now i can work with jpegs!

I feel like i have won a gold medal at the Olympics

**Comment by whxaxes** [comment]
great !!!!!!!!!  xcode-select --install works

thanks a lot

**Comment by LinusU** [comment]
Please try `xcode-select --install` :)

**Comment by piranna** [comment]
As I said before, by compiling statically this problem gets fixed. My [pull-request](https://github.com/Automattic/node-canvas/pull/571) is waiting...

**Comment by zhaotai** [comment]
My solution is the same with @LinusU.
Just `xcode-select --install`.

**Comment by javadba** [comment]
xcode-select --install works for me.
