### ISSUE TITLE
Not support custom font?

### ISSUE THREAD

**Issue by ondev** [Automattic/node-canvas#350]
I have success install canvas, and use canvas to crop image.
Today I use it to draw custom font text to canvas, and not success.
I use font.js in sample to test.
var Font = Canvas.Font;
if(!Font) {
      console.log("not support font customize");
}

will go in to if, and log:not support font customize

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...

**Comment by mitar** [comment]
There are quite some custom font tickets around.
