### ISSUE TITLE
Error on Amazon Linux AMI (EC2) Installation

### ISSUE THREAD

**Issue by jannae** [Automattic/node-canvas#355]
Hi, I'm experiencing an error on the install on an Amazon EC2. I have followed all the steps in order on the [wiki](https://github.com/LearnBoost/node-canvas/wiki/Installation---Amazon-Linux-AMI-\(EC2\))

This is my amazon info: 

> Amazon Linux AMI release 2013.09
> Kernel \r on an \m
> Linux x86_64 x86_64 x86_64 GNU/Linux

Here's the log from running `npm install canvas`

	npm WARN package.json solarplay@0.0.1 No description
	npm WARN package.json solarplay@0.0.1 No repository field.
	npm WARN package.json solarplay@0.0.1 No README data
	npm http GET https://registry.npmjs.org/canvas
	npm http 304 https://registry.npmjs.org/canvas
	npm http GET https://registry.npmjs.org/nan
	npm http 304 https://registry.npmjs.org/nan
	
	> canvas@1.1.2 install /home/ec2-user/fabric/node_modules/canvas
	> node-gyp rebuild
	
	make: Entering directory `/home/ec2-user/fabric/node_modules/canvas/build'
	  CXX(target) Release/obj.target/canvas/src/Canvas.o
	  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
	  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
	In file included from ../src/CanvasPattern.cc:9:0:
	../src/Image.h:20:21: fatal error: gif_lib.h: No such file or directory
	compilation terminated.
	make: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1
	make: Leaving directory `/home/ec2-user/fabric/node_modules/canvas/build'
	gyp ERR! build error
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
	gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
	gyp ERR! System Linux 3.4.57-48.42.amzn1.x86_64
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/ec2-user/fabric/node_modules/canvas
	gyp ERR! node -v v0.10.21
	gyp ERR! node-gyp -v v0.10.10
	gyp ERR! not ok
	npm ERR! weird error 1
	npm ERR! not ok code 0

Thanks for your help with this!

**Comment by LinusU** [comment]
`libgif-dev` should be what you want

Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
