### ISSUE TITLE
Implement resetClip

### ISSUE THREAD

**Issue by mitar** [Automattic/node-canvas#358]
Implement resetClip:
- http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#dom-context-2d-resetclip
- http://wiki.whatwg.org/wiki/Canvas#Misc_other_proposals
- https://www.w3.org/Bugs/Public/show_bug.cgi?id=14499

**Comment by zbjornson** [comment]
This is still in the WHATWG spec, but no browsers implemented it or intend to as far as I can see:

* webkit wontfix: https://bugs.webkit.org/show_bug.cgi?id=82801
* chromium wontfix: https://bugs.chromium.org/p/chromium/issues/detail?id=284600
* discussion remove from the spec: https://lists.w3.org/Archives/Public/public-canvas-api/2013JanMar/0017.html

I've submitted a PR to remove it from the spec finally... let's see where that goes. https://github.com/whatwg/html/pull/3796
