### ISSUE TITLE
Issue with resizing

### ISSUE THREAD

**Issue by dariusc93** [Automattic/node-canvas#359]
Hello,

I have a issue with resizing with node-canvas. The following code can be located https://gist.github.com/dariusc93/7656098 but the error I receive is "the surface type is not appropriate for the operation".

Any idea what could be causing this error?

EDIT:

After experimenting with everything i found that node-canvas has issue with accepting integers from req.params.

**Comment by lildogi** [comment]
Hey, having the same problem can you tell me how exactly you solved it ?
