### ISSUE TITLE
Error: error while reading from input stream (Image given has not completed loading)

### ISSUE THREAD

**Issue by bimusiek** [Automattic/node-canvas#364]
```
    var bufferImage = new Buffer(data.image, 'base64');
    var canvasImage = new Image;
    var generate = function(img) {
    }
    canvasImage.onload = function() {
        generate(canvasImage);
    }
    canvasImage.onerror = function(error) {
        debug.error('Failed loading image. '+error);
        generate();
    }
    canvasImage.src = bufferImage;
```

When I am trying to use JPEG with Canvas.Image it is triggering error event with message: "Error: error while reading from input stream". 

I tried 

```
apt-get install libcairo2-dev libjpeg8-dev
```

and 

```
apt-get install libjpeg62-dev
```

But this does not work :/ However on my local machine (MacOS) everything is working correctly. Funny thing is that with pngs everything is ok, only jpegs have problems.

strace: http://pastebin.com/6m8ZLa21

**Comment by roygwsidev** [comment]
I have install jpeg from  http://gnuwin32.sourceforge.net/packages/jpeg.htm. and also reinstalled node-canvas but still no luck

**Comment by khanhankkhan** [comment]
for me, I assigned the base64 string and was missing the prepended

     "data:image/png;base64,"

**Comment by MLiranG** [comment]
I have the same prob on windows node.js
code:
![image](https://user-images.githubusercontent.com/30736093/41235336-440de25a-6d97-11e8-9e8d-56e5b27989db.png)
err:
https://cdn.discordapp.com/attachments/404569720583618560/455727041031962625/unknown.png

**Comment by zbjornson** [comment]
@MLiranG if you're still having problems, please post a minimal repro case to a new issue.

Closing since the rest of this is from 2014 and there's not quite enough info to try to troubleshoot it. Sounds like it might have been fixed in a change to has_lib.sh/js.

**Comment by bobbigmac** [comment]
I was getting this on a remote server, after using `mkdirp` to generate the directories my files were being stored in. Turned out I was just dumb and hadn't set the correct folder permissions when it created them, so canvas couldn't read the images at all. Figured I'd post just in case anyone else lands here. Check your folder permissions :)
