### ISSUE TITLE
Nodejs exits with code=null when doing two drawImage or fillText operations

### ISSUE THREAD

**Issue by nvd-ai** [Automattic/node-canvas#371]
Here is the problem: I need to resize multiple images for which I have to resize the canvas according to a given size. Right after resizing the canvas, the call to drawImage or fillText causes nodejs to exit with code=null.

I have tried to create multiple canvases and contexts, one for each image resize, and again nodejs breaks.

I also have tried changing the width and height of canvas by doing canvas.width=w, canvas.height=h, and the same thing happens.

The common thing in all the cases is that the first call to fillText/drawImage works just fine, but nodejs exits right on the second call to fillText/drawImage. 

The OS is MacOSX Mavericks.

**Comment by LinusU** [comment]
I can't reproduce this. Please test with the latest version and reopen if problem persists :+1:
