### ISSUE TITLE
Custom Font .width & .height not accurate

### ISSUE THREAD

**Issue by PvanHengel** [Automattic/node-canvas#375]
Hi, we are using custom fonts on node.js, it seems that when using custom fonts the width returned by textItem.width and textItem.height do not match what is actually rendered.  It works fine with the default font.

**Comment by LinusU** [comment]
This comment (https://github.com/Automattic/node-canvas/issues/331#issuecomment-429590355) leads me to think that this is fixed, happy to reopen if otherwise...
