### ISSUE TITLE
Symbol not found in binary canvas.node

### ISSUE THREAD

**Issue by dzsodzso63** [Automattic/node-canvas#377]
When I require resemble package, I got this:

`...node_modules/canvas/build/Release/canvas.node, 1): Symbol not found: __Z22jpeg_resync_to_restartP22jpeg_decompress_structi`

`node-gyp` rebuild did not help

**Comment by ArdentKid** [comment]
I'm running on Meteor 1.3.4.1 and getting a similar error. Mine says:

`Unable to resolve some modules: "../build/Release/canvas" in /node_modules/canvas/lib/bindings.js (web.browser)`

I looked at the bindings.js file, and if I change it to "../build/Release/canvas.**node**" where it says `module.exports = require('../build/Release/canvas');` then it works. But that won't fly when it installs my npm dependencies automatically.

**Comment by zbjornson** [comment]
(See #930 -- if there's a conflicting version of libcairo this method may be missing.)

**Comment by zbjornson** [comment]
The .node extension was added in #933 (1.6.6) and #939 (2.x), which fixes the 3rd comment. See #930 for the other potential cause.
