### ISSUE TITLE
Typed Array and Chunked image decode

### ISSUE THREAD

**Issue by m5p3nc3r** [Automattic/node-canvas#378]
Hi Guys

I am currently working on a node binding to OpenGL ES2, and want to add a shim on top of this to give WebGL bindings.  I would like to be able to use the node-canvas project to give me Canvas 2D and png/jpeg capability for GLES textures, but from looking at the currently exposed API's, there does not seem to be a suitable way to do this.

I am happy to attempt to do the work for you, but wanted to gauge how likely to be accepted upstream these modifications would be

In order of my personal priority:

1 - Modify Image to allow output to a typed array - this would allow efficient transfer of the decoded image into the GLES bindings
2 - Modify Image to allow for chunked decoding - this would allow me to create a http loader for the images that has the same API as a DOM Image.
3 - Modify Canvas to allow output to a typed array - to be uses as a texture source in the GLES bindings.

Kind regards

Matt

**Comment by piranna** [comment]
@m5p3nc3r, are you still working on this issue? I'm interested on having WebGL support for NodeOS.

**Comment by LinusU** [comment]
This is cool!

I think that point 3 is addressed by #604 which I want to merge next week, we just need to give some time for the other maintainers to look on it if they want to.

It then makes sense to have a similar api for `Image` which is your point 1.

Point 2 would also be very cool, that would allow us to do async loading of `Image`s, right?

**Comment by zbjornson** [comment]
I'm not sure I understand (2) -- 2.x supports `img.src = <url>`. That's not "chunked" but it is an http loader that matches browsers. Is that what you mean?

**Comment by LinusU** [comment]
Seems like this is supported now:

1. `getBuffer('raw')`
2. `img.src = <url>`
3. #604 which is merged

Happy to reopen if we are missing something...
