### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by asherbitton** [Automattic/node-canvas#380]
Hi,

I've installed on windows however when using the exmaple provided (with the model1.jpg) file it gets an error ("Your image is long to be loaded - ..."), same example using a png file works fine.
Trying to use "npm install -g canvas --with-jpeg --with-gif" (per old threads) I get an error on Cannot open include file: 'jpeglib.h'..
Right now I'm stuck, will be happy to know how to get out of this and get jpeg files supported in canvas on windows.
Btw, to get the build to work I had to put gtk on c:\gtk (thanks to old threads), not nice, but working.

**Comment by stiv-yakovenko** [comment]
I've run into the same problems. Here is my question on stackoverflow: http://stackoverflow.com/questions/30953683/how-to-enable-jpeg-support-in-node-canvas-on-x64-windows-with-msvc10-compiler

I will surely find some sort of solution, but if you vote for my question, this would happen faster :)

**Comment by zbjornson** [comment]
Windows JPEG support was added in 2.x. 🎉
