### ISSUE TITLE
Windows build fails with syntax errors

### ISSUE THREAD

**Issue by farzher** [Automattic/node-canvas#388]
Z:\a\node_modules\canvas>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
	Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
	  CanvasRenderingContext2d.cc
	  CanvasPattern.cc
	  color.cc
	  PixelArray.cc
	  ImageData.cc
	  Canvas.cc
	  init.cc
	  Image.cc
	..\src\color.cc(353): warning C4305: 'initializing' : truncation from 'double' to 'float' [Z:\a\node_modules\canvas\build\canvas.vcxproj]
	..\src\color.cc(356): warning C4305: '*=' : truncation from 'double' to 'float' [Z:\a\node_modules\canvas\build\canvas.vcxproj]
	  CanvasGradient.cc
	C:\Users\Farzher\.node-gyp\0.11.8\src\node.h(176): error C2146: syntax error : missing ';' before identifier 'DecodeBytes' [Z:\a\node_modules\canvas\build\canvas.vcxproj]

I followed all the steps on the Windows install guide. And re-installed everything multiple times. Any idea how a syntax error is even possible?

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
> No, because devs don't give a fuck.

Ouch :(

Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
