### ISSUE TITLE
Symbol lookup error on 0.11.12: canvas.node: undefined symbol: MakeCallback

### ISSUE THREAD

**Issue by modulesio** [Automattic/node-canvas#394]
Latest git canvas, 0.11.12 built from source. Getting MakeCallback undefined at runtime. The exact symbol is:

 _ZN4node12MakeCallbackEN2v86HandleINS0_6ObjectEEENS1_INS0_8FunctionEEEiPNS1_INS0_5Value
EEE

Tried newer nan (0.8.0), since that's what's abstracting this call; didn't work.

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
