### ISSUE TITLE
Can use node-gyp to compile

### ISSUE THREAD

**Issue by m0ose** [Automattic/node-canvas#396]
I am using mac os 10.9

I tried running through the installation instructions, and got to some error looking for jpeglib.h . A search shows that I have like 5 or 6 copies of that file on my computer. 
So I downloaded the node-canvas code and ran
```
npm install
```
It Fails for the same reason.
But then I ran the command
```
node-gyp clean configure build
```
It compiled Successfully. 
All of the tests and benchmark ran fine. 

Still running 'npm install' fails for the same reason, missing jpeglib.h.
Is there some kind of path problem?

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
