### ISSUE TITLE
ImageData.data should return a Uint8ClampedArray instead of a CanvasPixelArray

### ISSUE THREAD

**Issue by zbjornson** [Automattic/node-canvas#403]
`CanvasPixelArray` is deprecated per https://www.w3.org/Bugs/Public/show_bug.cgi?id=12586.

I don't care, except `CanvasPixelArray` doesn't have a `set` method that typed arrays have.

Also encountered here by another user: http://stackoverflow.com/questions/21435027/node-js-canvas-implementation-with-uint8clampedarray

(Seeing if I understand this library well enough to submit a pull request...)

**Comment by LinusU** [comment]
Fixed by #604
