### ISSUE TITLE
Install with npm it fails but from source it works?

### ISSUE THREAD

**Issue by reggi** [Automattic/node-canvas#404]
Any idea why when I install canvas with npm it fails but from source it works?

```
npm install canvas --save
```
https://gist.github.com/reggi/10810791#file-from-npm-txt

vs

```
git clone https://github.com/LearnBoost/node-canvas.git && cd node-canvas && npm install
```
https://gist.github.com/reggi/10810791#file-from-source-txt

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
