### ISSUE TITLE
Opening more than 242 streams cause error

### ISSUE THREAD

**Issue by paragshar** [Automattic/node-canvas#405]
The code below which captures the canvas image in a loop works fine if the frame count is less than 242. However if the frames increase beyond 242, the code is not able to open more output streams for me to write on to it.

     var fs = require('fs');
     for(var frameIndex=0; frameIndex<500; frameIndex++){
          var out = fs.createWriteStream(__dirname + '/frames/'+frameIndex+'.png');
          var stream = anivid.canvas.createPNGStream();

          stream.on('data', function(chunk) {
            out.write(chunk);
          });

     }

The error I get is 
Error: EMFILE,

Any way this could be resolved?

**Comment by LinusU** [comment]
@ti2m If you do `stream.pipe(out)` that will automatically wire up both `data` and `end`.

@paragshar Use `.pipe()` instead of `.on('data')`, also `EMFILE` is not a problem in canvas, you're simply opening too many files. See the answer that @zbjornson provided...
