### ISSUE TITLE
Error npm installing canvas@1.1.3 on Windows (GTK does not come with libpng.lib)

### ISSUE THREAD

**Issue by Darthfett** [Automattic/node-canvas#412]
After following the [Windows Installation Instructions](https://github.com/LearnBoost/node-canvas/wiki/Installation---Windows) to set up the necessary dependencies, I got an error when I attempted to `npm install canvas`:

```
LINK : fatal error LNK1181: cannot open input file 'C:\GTK\lib\libpng.lib' [c:\
Users\_____\Scripts\test\node_modules\canvas\build\canvas.vcxproj]
```

After getting the same error on a friend's fork ([ref](https://github.com/andrewrk/chem-cli/issues/5)), I was able to solve this issue by changing this line in binding.gyp:

```
             '-l<(GTK_Root)/lib/libpng.lib'
```

To:

```
            '-l<(GTK_Root)/lib/libpng.dll.a'
```

The current binary of GTK given in the installation instructions does not come with a `libpng.lib`, but rather a `libpng.dll.a`.

**Comment by andig** [comment]
> Yes, that's the case if you use GTK 3.x. In the GTK 2.x bundle there is indeed a libpng.lib.

It would make sense then to update the install instructions to specifically download the all-in-one bundle for GTK2 which is not obvious. Just stumbled upon the same issue.

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Please see the posted solution, or the updated wiki-page...
