### ISSUE TITLE
Bug with Global Composite Operations

### ISSUE THREAD

**Issue by bchevalier** [Automattic/node-canvas#416]
The result obtained is different from standard canvas when using the global composite operation 'destination-in' as follow:

```
context.drawImage(imageA, x, y);
context.globalCompositeOperation = 'destination-in';
context.save();
context.translate(imageB.width / 2, imageA.height / 2);
context.rotate(Math.PI / 4);
context.scale(0.5);
context.translate(-imageB.width / 2, -imageA.height / 2);
context.drawImage(imageB, x, y);
context.restore();
```

The global composition 'destination-in' should let ImageA be masked with imageB. But if the bounding box of imageB after transformation is smaller than imageA, then every pixel of imageA outside of this bounding box is displayed, although it should not. But inside this bounding box, the behaviour is correct and imageA is displayed correctly.

It looks like, at least for this global composite operation, the surface that is being considered is the bounding box of the image being drawn although it should be the entire canvas.

**Comment by janslifka** [comment]
Is there any progress or workaround for this issue?

**Comment by bchevalier** [comment]
I guess the workaround would be to make sure that when imageB is drawn its bounding box completely covers imageA by artificially increasing the dimension of imageB (may be render imageB in a proxy canvas of higher dimension?).

**Comment by udipl** [comment]
I've run into a similar problem with the `'source-in'` composite operation. I'm getting destination pixels where I'm expecting transparent pixels.
