### ISSUE TITLE
I follow the wiki installed, but still has an error

### ISSUE THREAD

**Issue by cxh80301983** [Automattic/node-canvas#421]
yum install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * extras: mirrors.163.com
 * updates: mirrors.163.com
Setting up Install Process
No package libcairo2-dev available.
No package libjpeg8-dev available.
No package libpango1.0-dev available.
No package libgif-dev available.
No package build-essential available.
No package g++ available.
Error: Nothing to do

and  npm install canvas 

canvas@1.1.3 install /alidata1/wwwroot/teams/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/alidata1/wwwroot/teams/node_modules/canvas/build'
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:8:
../src/PNG.h: In function ‘cairo_status_t canvas_write_png(cairo_surface_t*, void (*)(png_struct*, png_byte*, png_size_t), void*)’:
../src/PNG.h:165: 警告：case 标号值比该类型的最小值还要小
In file included from ../src/Canvas.cc:19:
../src/JPEGStream.h: In function ‘boolean empty_closure_output_buffer(jpeg_compress_struct*)’:
../src/JPEGStream.h:44: 错误：不能将‘bool’转换为‘boolean’，在 return 中
../src/JPEGStream.h: In function ‘void write_to_jpeg_stream(cairo_surface_t*, int, int, bool, closure_t*)’:
../src/JPEGStream.h:127: 错误：从类型‘int’到类型‘boolean’的转换无效
../src/JPEGStream.h:127: 错误：  初始化‘void jpeg_set_quality(jpeg_compress_struct*, int, boolean)’的实参 3
make: *** [Release/obj.target/canvas/src/Canvas.o] 错误 1
make: Leaving directory `/alidata1/wwwroot/teams/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 2.6.32-358.6.2.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /alidata1/wwwroot/teams/node_modules/canvas
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! canvas@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.1.3 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /alidata1/wwwroot/teams
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /alidata1/wwwroot/teams/npm-debug.log
npm ERR! not ok code 0

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
