### ISSUE TITLE
CMYK JPEG images are not properly painted

### ISSUE THREAD

**Issue by bimusiek** [Automattic/node-canvas#425]
So here is example of CMYK Jpeg that we try just to draw on canvas in nodejs.
![logo-neu-fl-01-unsharp](https://cloud.githubusercontent.com/assets/1025588/3039104/ae8761ac-e0d7-11e3-8c58-67b747acbf19.jpg)

And here is an result of it.
![screenshot 2014-05-21 13 04 50](https://cloud.githubusercontent.com/assets/1025588/3039108/c25a2a2a-e0d7-11e3-83bf-20ad143b6705.jpg)

Code that I am using:

```
        this.context.drawImage(this.imageObj, imageX, imageY, imageWidth, imageHeight);
```

I would suggest to return exception that JPEG CMYK is not supported.

**Comment by imjared** [comment]
Did either of you find a way around this? This is looking like a pain point for my application.

**Comment by bimusiek** [comment]
We changed our backend to convert CMYK to RGB before sending it to NodeJS.

**Comment by jakeg** [comment]
I also experience this problem but we have very few customers using CMYK images so it's not a priority for us at the moment.

**Comment by vasili-zolotov** [comment]
**+1** Just spent the day tracing the issues through the processing pipeline and all signs point to this as the root cause.

**Comment by jakeg** [comment]
Happy to offer a bounty for anyone who wants to add support for CMYK jpgs.

**Comment by bruceCzK** [comment]
I'm facing the same issue, and I just use gm to convert images to RGB colorspace using following function. Make sure gm installed first.
```
const gm = require('gm')

function convertToRGB(file) {
  return new Promise((resolve, reject) => {
    gm(file).colorspace('RGB').toBuffer((err, buffer) => {
      if (err) {
        return reject(err)
      }
      resolve(buffer)
    });
  });
}
```

**Comment by bhouston** [comment]
This is also affecting YCCK images.  Add this so that this thread appears in searches for the YCCK keyword.

**Comment by vlad-dudu** [comment]
Has anyone managed to find a solution for this issue besides converting the image to RGB prior to sending it to node canvas?

**Comment by pravdomil** [comment]
Does anybody tried to embed CMYK JPG into PDF?

```js
const canvas = createCanvas(100, 100, "pdf")
const ctx = canvas.getContext("2d")

const image = new Image()
image.dataMode = Image.MODE_MIME
image.src = require("fs").readFileSync(filepath)
ctx.drawImage(image, 0, 0)

canvas.toBuffer()
```
