### ISSUE TITLE
New version giflib.

### ISSUE THREAD

**Issue by mynoheart** [Automattic/node-canvas#440]
The new version of giflib changed signature function `int DGifCloseFile(GifFileType * GifFile, int *ErrorCode)`.
giflib v5.1.0.
Sorry, my english very bad.

**Comment by mathieujobin** [comment]
`DGifOpenFileHandle` too, if you are trying to build Imlib 1.9.5 under Ubuntu 20.04, which ship with `giflib` 5.1.x, you will need to add the NULL param as described above.

thank you guys
