### ISSUE TITLE
Automatic external dependency installation

### ISSUE THREAD

**Issue by buschtoens** [Automattic/node-canvas#450]
How about detecting and trying to install the external dependencies before attemting to build node-canvas? If the installation fails (no root rights, wrong system, etc.), we could output some useful information and how to fix this, e.g. "run `apt-get ...` with root rights".

I'd be delighted to code this installation hook, if wanted.

**Comment by zbjornson** [comment]
@chearon setup node-pre-gyp/prebuilds 🎉 , which generally makes this moot.
