### ISSUE TITLE
Failed to install on Windows 8.1 x64

### ISSUE THREAD

**Issue by Mathyn** [Automattic/node-canvas#451]
I have tried the solutions posted in other issues found here. So far none of them helped. When installing node-canvas using 

npm install canvas

it fails with the following errors:

C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsServer\XXX_wmt
s_server>npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> canvas@1.1.5 install C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsServer\XXX_wmts_server\node_modules\canvas
> node-gyp rebuild

C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsServer\XXX_wmt
s_server\node_modules\canvas>node "D:\IT\NodeJS\node_modules\npm\bin\node-gyp-bi
n\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:998:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "D:\\IT\\NodeJS\\node_modules\\npm\\node_modules\\node-g
yp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsSer
ver\XXX_wmts_server\node_modules\canvas
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! canvas@1.1.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.5 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\IT\\NodeJS\\\\node.exe" "D:\\IT\\NodeJS\\node_modules\\npm
\\bin\\npm-cli.js" "install" "canvas"
npm ERR! cwd C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsSer
ver\XXX_wmts_server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsSer
ver\XXX_wmts_server\npm-debug.log
npm ERR! not ok code 0

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\IT\\NodeJS\\\\node.exe" "D:\\IT\\NodeJS\\node_modules\\npm
\\bin\\npm-cli.js" "install" "canvas"
npm ERR! cwd C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsSer
ver\movin_wmts_server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Mathyn\My Documents\Aptana Studio 3 Workspace\XXXMapsSer
ver\movin_wmts_server\npm-debug.log
npm ERR! not ok code 0

I am using Windows 8.1 x64. My NodeJS version is v0.10.28. I installed GTK 2.22 64 bit to C:\GTK and I set the Path variable to C:\GTK\Bin;

Does anyone know of any possible solutions?

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Please see the posted solution, or the updated wiki-page...
