### ISSUE TITLE
 OS X  Error: Image given has not completed loaded

### ISSUE THREAD

**Issue by xwartz** [Automattic/node-canvas#453]
https://github.com/Automattic/node-canvas/wiki/Installation---OSX

I did brew install giflib , then recompile node-canvas. 

But it didn't work!  why?

**Comment by mltucker** [comment]
Can you post some code that's not working?  Are you setting `img.src` to a Buffer or to a URL or what?  If you are getting that error message, then it doesn't sound like an installation issue.
