### ISSUE TITLE
LibPng fails even with installed binaries

### ISSUE THREAD

**Issue by smks** [Automattic/node-canvas#454]
If libpng fails and you get the error "error: recommended PNG functions feature could not be enabled", try installing this binary and re-running the configure step.

I have installed binaries, yet the errorstill occurs. 
http://stackoverflow.com/questions/24829078/installing-cairo-on-mac-could-not-find-libpng-in-the-pkg-config-search-path

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
