### ISSUE TITLE
Node-canvas on AWS elasticbeanstalk (.ebextensions)

### ISSUE THREAD

**Issue by jasonfutch** [Automattic/node-canvas#455]
Having issue getting this setup for AWS easticbeanstalk, which is a great quick way of launching node instances. They require the config to be defined in .ebextensions but with my limited knowledge of cairo I'm sure what needs to be defined.

The reason I ask is because I see you already have directions for AWS EC2, but would be great to have the ebextensions defined for it as well.

**Comment by LinusU** [comment]
Seems like this is resolved then :)

**Comment by dtturcotte** [comment]
@hampelm where do I add that packages thing? Is it /.ebextentions/config.config?

**Comment by hampelm** [comment]
@dtturcotte We aren't using elasticbeanstalk in production, so alas I'm not sure what the current setup looks like. If I remember correctly, the config goes in a file called `.config` -- the elasticbeanstalk docs should have more information on where to specify packages. There's a fair chance it's changed in the last two years.
