### ISSUE TITLE
Save canvas as png using toBuffer

### ISSUE THREAD

**Issue by Mathyn** [Automattic/node-canvas#462]
I am trying to save the result of a canvas as a png using the toBuffer function.

I have the below code

var canvasBuffer = canvas.toBuffer();
var bytesWritten = FS.writeSync("images/test.png", canvasBuffer, canvasBuffer.length, 0);

However no file is created and nothing is stored (bytesWritten = 0). I am still rather new to NodeJS and node-canvas so I probably just missed a step, can someone point me in the right direction?

**Comment by mltucker** [comment]
How are you creating the canvas?  The following works for me:

    var fs = require("fs");
    var Canvas = require("canvas");

    var canvas = new Canvas(200, 200, "png");
    var g = canvas.getContext("2d");
    g.fillStyle = "black";
    g.fillRect(0, 0, 100, 100);

    var buf = canvas.toBuffer();
    fs.writeFileSync("test.png", buf);

**Comment by LinusU** [comment]
The problem is that you're using `writeSync` instead of `writeFileSync`...
