### ISSUE TITLE
possible issue with node-canvas or giflib

### ISSUE THREAD

**Issue by danschumann** [Automattic/node-canvas#463]
can anyone resize this img using node canvas and giflib?

http://postimg.org/image/frc5x5lo9/

On mine, it works, but it seems seems to have weird issues with the transparency.  It will cut off the top, and then after the image done it prints random pixels as if it's x, y offsets are getting scrambled.

afterwards its looks like this

http://postimg.org/image/69h0aupdl/

at first I thought this was a resizing algorithm I wrote ( which btw you might want in node-canvas ), its `limby-resize`.  It's a little slower but it resizes down very nicely while preserving all color data.

Anyway, it scrambles it whether I manipulate image data myself or just call `drawImage`

**Comment by zbjornson** [comment]
Closing because those image links are dead now -- no way to troubleshoot.
