### ISSUE TITLE
Problem with displaying TTF font (icomoon)

### ISSUE THREAD

**Issue by gen4sp** [Automattic/node-canvas#464]
i try to render glyths on canvas, but nothing happens.
other font is render well (roboto by googleFont)

this is my code:

```
var grabaword = new Font('grabaword',__dirname + '/public/fonts/grabaword.ttf');
ctx.font = '50px grabaword';
ctx.fillStyle = grayColor;
ctx.fillText(String.fromCharCode(parseInt('002A', 16)), 100, 100);
ctx.fillText('*-', 200, 100);
ctx.fillText('\u002a', 300, 100);
ctx.fillText('\u002A', 400, 100);
```

this is font-file (i use ttf)
https://drive.google.com/file/d/0B55bVrO2NLRvRGpxejkyS2lyN3M/edit?usp=sharing

**Comment by LinusU** [comment]
The font backend has been reworked a lot in 2.0, please reopen if the issue is still there ☺️
