### ISSUE TITLE
Cairo Installation : LibPng package url has to be fixed

### ISSUE THREAD

**Issue by G33kLabs** [Automattic/node-canvas#466]
Hi,

I recently installed node-canvas : thanks for the work ! 
But I want to inform you that libpng has been updated, and in facts compilation failed.

```
$ wget https://raw.githubusercontent.com/LearnBoost/node-canvas/master/install -O - | sh
``` 

So you can replace 
```
LIBPNG="http://downloads.sourceforge.net/project/libpng/libpng16/1.6.10/libpng-1.6.10.tar.gz"
```

By 

```
LIBPNG="http://downloads.sourceforge.net/project/libpng/libpng16/1.6.13/libpng-1.6.13.tar.gz"
```

And compilation works fine for me now !

**Comment by LinusU** [comment]
The installation script has now been retired :)
