### ISSUE TITLE
ShadowBlur on text

### ISSUE THREAD

**Issue by Mathyn** [Automattic/node-canvas#467]
Is ShadowBlur on text supported? I tried the following:

context.shadowColor = "red";
context.shadowOffsetX = 10;
context.shadowOffsetY = 10;
context.shadowBlur = 25;

context.fillText("Hello World", 100, 100);

And all I saw was the shadow placed at an offset of 10, 10 but with no blur effect applied. Can anyone verify if it should or should not work? On a related note: is there a list of all supported and unsupported canvas features working with node-canvas somewhere?

**Comment by woodcoder** [comment]
This should work fine when using image-based output.  It won't work with vector based output currently (e.g. PDF).  The pull request referenced above adds support for that.

**Comment by zbjornson** [comment]
Fixed in #505 🎉
