### ISSUE TITLE
Incompatible library version: libfontconfig.1.dylib requires version 18.0.0 or later, but libfreetype.6.dylib provides version 16.0.0

### ISSUE THREAD

**Issue by lowiebenoot** [Automattic/node-canvas#471]
I installed cairo and its dependencies (on Mac OS X 10.9.3) via the oneliner.  
When i run the following script (index.js):

	var Canvas = require('canvas');
	
I get this error:

    $ node index.js

    module.js:356
      Module._extensions[extension](this, filename);
                                   ^
    Error: dlopen(/Users/lowiebenoot/Projects/node-canvas-test/node_modules/canvas/build/Release/canvas.node, 1): Library not loaded: /usr/local/lib/libfreetype.6.dylib
      Referenced from: /usr/local/lib/libfontconfig.1.dylib
      Reason: Incompatible library version: libfontconfig.1.dylib requires version 18.0.0 or later, but libfreetype.6.dylib provides version 16.0.0
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/Users/lowiebenoot/Projects/node-canvas-test/node_modules/canvas/lib/bindings.js:2:18)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)

**Comment by bogdancloud** [comment]
Same issue in here on Mac Os X with node v0.10.32

**Comment by mltucker** [comment]
@bogdancloud Did you do this?

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
```

(and is X installed in `/opt/X11`?)

How did you install freetype?

**Comment by bogdancloud** [comment]
How to fix the issue on Mac Os X 10.10.2 with node v0.10.32

Find your libfreetype library:
```
sudo find / -name libfreetype.6.dylib
```

check the version of the libraries
```
otool -L /usr/local/lib/libfreetype.6.dylib
otool -L /opt/X11/lib/libfreetype.6.dylib
```

and update the library with the correct version
```
 cp /opt/X11/lib/libfreetype.6.dylib /usr/local/lib/libfreetype.6.dylib
```

**Comment by talkol** [comment]
I tried all the solutions in this thread and none worked because all versions of my libfreetype.6.dylib were 16.0.0 so I couldn't copy one over the other. After some research the answer was to install a fresh new copy of libfreetype, which I did with brew:

    brew install freetype
    brew link --overwrite freetype

**Comment by kerngven** [comment]
install fontconfig-2.11.93.tar.gz 
http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.93.tar.gz

**Comment by sungwoncho** [comment]
@talkol's  solution worked for me. OSX Yosemite 10.10.3 and node v0.12.7.

**Comment by holographix** [comment]
@talkol's solution played out well even for me! :+1:

**Comment by cperryk** [comment]
@talkol's worked for me too. El Capitan 10.11 Beta, Node 4.0.0. :+1:

**Comment by tim-dandb** [comment]
I had two versions of libfreetype installed:

    $ locate libfreetype.6.dylib
    /usr/X11/lib/libfreetype.6.dylib
    /usr/local/Cellar/freetype/2.5.4/lib/libfreetype.6.dylib
    /usr/local/Cellar/freetype/2.6_1/lib/libfreetype.6.dylib

Manually creating a symlink to the newer version in /usr/local/lib/libfreetype.6.dylib worked for me.

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...

**Comment by suniliphone** [comment]
is there any one knows how to generate libfontconfig.a file for ios ?

**Comment by kamathhrishi** [comment]
For me reinstalling it with the command 

`conda install --channel https://conda.anaconda.org/menpo opencv3` 

worked fine.
