### ISSUE TITLE
measureText resulting integer in CentOS 6

### ISSUE THREAD

**Issue by i2joseph** [Automattic/node-canvas#472]
Hi,
The measureText method is resulting integer in CentOS 6. Is there a way to solve this problem? THANKS.

Here is the comparison result between CentOS and Mac OS X 10.8

Result from CentOS:
{ width: 25,
  actualBoundingBoxLeft: 1,
  actualBoundingBoxRight: 24,
  actualBoundingBoxAscent: 8,
  actualBoundingBoxDescent: 0,
  emHeightAscent: 11,
  emHeightDescent: 3,
  alphabeticBaseline: 0 }

Result from Mac OS X 10.8:
{ width: 24.005859375,
  actualBoundingBoxLeft: 0.017578125,
  actualBoundingBoxRight: 23.162109375,
  actualBoundingBoxAscent: 8.58984375,
  actualBoundingBoxDescent: 0.140625,
  emHeightAscent: 10.86328125,
  emHeightDescent: 2.54296875,
  alphabeticBaseline: 0 }

**Comment by jakeg** [comment]
Tried this:
```
// We use get_extents not get_pixel_extents because the latter rounds (we want more precision)
  // pango_layout_get_pixel_extents(layout, &ink_rect, &logical_rect); // will round, which we don't want
  pango_layout_get_extents(layout, &ink_rect, &logical_rect); // pango_layout_get_pixel_extents will round which we don't want
  double precision_width = (double) logical_rect.width/PANGO_UNITS; // PANGO_UNITS is 1024
```
... but even when using get_extents instead of get_pixel_extents the logical_rect.width is still divisible by PANGO_UNITS (which is 1024).

**Comment by zbjornson** [comment]
Should be fixed in 2.x since Pango is required (and in 2bbfec5)?
