### ISSUE TITLE
32-bit image 300dpi striped error

### ISSUE THREAD

**Issue by danschumann** [Automattic/node-canvas#473]
Hello,

As you can see, for some strange reason, my image gets weird.

All I am doing is opening it and calling drawImage.

original
![cr_undefined_logo_vtx-vip_white-green-31999-1un8khw-original](https://cloud.githubusercontent.com/assets/1516973/4424351/3dce210e-459e-11e4-910b-2b74241dcd5a.jpg)

`drawImage(..., 1000, 1000);`
![cr_199_cr_undefined_logo_vtx-vip_white-green-31999-1un8khw-original-17341-1biap4d-avatar](https://cloud.githubusercontent.com/assets/1516973/4424361/625f1fa0-459e-11e4-842d-e84c925765fa.jpg)

This should be GREEN.. all green!  These are some of the green pixels where y=50

```
102 212 255 255
209 102 212 255
255 209 102 255
212 255 209 255
102 212 255 255
209 102 212 255
255 209 102 255
212 255 209 255
102 212 255 255
209 102 212 255
255 209 102 255
212 255 209 255
102 212 255 255
209 102 212 255
255 209 102 255
212 255 209 255
102 212 255 255
209 102 212 255
255 209 102 255
212 255 209 255
102 212 255 255
209 102 212 255
255 209 102 255
212 255 209 255
102 212 255 255
209 102 212 255
255 209 102 255
212 255 209 255
102 212 255 255
209 102 212 255
255 209 102 255
213 255 208 255
102 212 255 255
209 101 214 255
255 212 112 255
247 255 247 255
228 255 255 255
```

It seems like its analyzing pixels wrong, thus stretching it across the x axis
300dpi 32bit depth

**Comment by pravdomil** [comment]
https://github.com/Automattic/node-canvas/issues/425
