### ISSUE TITLE
Question: How expansive is it to create the canvas object?

### ISSUE THREAD

**Issue by roundrobin** [Automattic/node-canvas#482]
I am currently using **node-canvas** in the context of an Express.js application, which basically generates an image every time a certain endpoint gets called. 

After using it for a while and doing multiple load tests, I noticed that creating a canvas and drawing stuff on it, is very expansive and causes the CPU to easily jump to 100% consumption.

Do you have any tips how to us the library in a web server context? 
Or avoid these CPU usage peaks?

One of my ideas was to have a canvas object pool or only instantiating only one canvas, not sure if this is doable or would help.

Any feedback is welcome
Thanks roundrobin

**Comment by LinusU** [comment]
I would recommend having a pool of a few canvas that you can reuse, should work pretty good. I believe the async library has some helper methods for this...
