### ISSUE TITLE
'Image given has not completed loading' is misleading.

### ISSUE THREAD

**Issue by mbostock** [Automattic/node-canvas#486]
If you try to load an invalid image file, node-canvas reports the misleading error 'Image given has not completed loading', rather than reporting that the image file is invalid.

To reproduce, first create an invalid image:

``` bash
echo 'File not found.' > test.png
```

Then try this script:

``` js
var fs = require("fs"),
    Canvas = require("canvas"),
    Image = Canvas.Image;

var image = new Image;
image.src = fs.readFileSync("test.png");

var canvas = new Canvas(256, 256),
    context = canvas.getContext("2d");
context.drawImage(image, 0, 0); // Error: Image given has not completed loading
```

It’d be even better if the error were reported when `image.src` is assigned, rather than deferring it until context.drawImage.

**Comment by topherhunt** [comment]
+1 on this. It seems to be related to some pretty confusing errors in tools like ResembleJS, see http://stackoverflow.com/questions/24944987/node-canvas-resemble-js-error-image-given-has-not-completed-loading-at-load
