### ISSUE TITLE
Could not load font file: Register Serif BTN SC.ttf

### ISSUE THREAD

**Issue by luffyyu** [Automattic/node-canvas#492]
Hi, guys:

I have a issue when load the custom file, the code is simple, see below:
var path    = require('path');
var font = "Register Serif BTN SC.ttf";
var font_name = path.basename(font, ".ttf");
var fontObj = new Canvas.Font(font_name, '/data/files/fonts/' + font);

A error occured:
Error: Could not load font file
at Font.addFace (/opt/node-v0.10.30-linux-x64/lib/node_modules/canvas/lib/canvas.js:80:16)
at new Font (/opt/node-v0.10.30-linux-x64/lib/node_modules/canvas/lib/canvas.js:73:10)

I checked the font file already exists on local, but It can be loaded by PHP GD. I don't know why.

This is the font file:
https://s3.amazonaws.com/common_contents/Register%20Serif%20BTN%20SC.ttf

Someone can help me? Thank you so much!

**Comment by LinusU** [comment]
Please test this with 2.x and reopen if it still doesn't work, thanks ☺️
