### ISSUE TITLE
long text cut off when using glyph textDrawingMode in PDF

### ISSUE THREAD

**Issue by mltucker** [Automattic/node-canvas#495]
I'm using the latest node-canvas and glyph textDrawingMode in my PDF generation so that text can be selected.  I noticed that long strings in g.fillText are being cut off in a strange way (only the middle remains).  This behavior can be reproduced with the following code:

```
var Canvas = require("canvas");
var fs = require("fs");

var pageWidth = 595.276;
var pageHeight = 841.890;

var canvas = new Canvas(pageWidth, pageHeight, "pdf");
var g = canvas.getContext("2d");

var text = "Text gets cut off when using textDrawingMode glyph, but not when using path.  But only after a certain length.";
var words = text.split(" ");

g.fillStyle = "black";
g.font = "11px Arial";

g.textDrawingMode = "path";

g.fillText("g.textDrawingMode='path' OK", 20, 20);

for (var i = words.length; i > 0; i--) {
    g.fillText(words.slice(0, i).join(" "), 20, 50 + (words.length - i)*16);
}

g.textDrawingMode = "glyph";

g.fillText("g.textDrawingMode='glyph' broken", 20, pageHeight/2 + 20);

for (var i = words.length; i > 0; i--) {
    g.fillText(words.slice(0, i).join(" "), 20, pageHeight/2 + 50 + (words.length - i)*16);
}

var buf = canvas.toBuffer();
fs.writeFileSync("test.pdf", buf);
```

**Comment by zbjornson** [comment]
@mltucker both modes look the same for me on Windows in the current master branch, current v1.x branch and a commit from Nov 2015 (oldest I can easily compile).

![image](https://user-images.githubusercontent.com/469365/45920741-bb651500-be5d-11e8-84dd-596323dde82f.png)

Can you please check if this got fixed or if it's still happening, and post a screenshot of what it looks like?
