### ISSUE TITLE
install failed in mac-10.9.5 and node-0.10.36,have installed all the dependeces

### ISSUE THREAD

**Issue by lin-hun** [Automattic/node-canvas#508]
![qq20150201-1](https://cloud.githubusercontent.com/assets/7136386/5990949/006ffc82-aa08-11e4-8032-b79a88afd647.png)

**Comment by mltucker** [comment]
Is there any more text below or above?

**Comment by lin-hun** [comment]
nothing
uh,have solved by port to install.
closed
