### ISSUE TITLE
doesn't build on OS X with cairo installed with homebrew without command line clang

### ISSUE THREAD

**Issue by sma** [Automattic/node-canvas#514]
We noticed a problem which might be a bug. When trying to install 1.2.0 on OS X it worked on one machine but not on another one. Very frustrating. After 2h of digging, I noticed a subtile difference: I had installed the Xcode development tools via `xcode-select --install`, my colleague never did that but used the tools that came with Xcode. What was different?

We both installed Cairo 1.14.0 via `brew install cairo`. This did copy the library's include files to `/usr/local/include/cairo` as well as `/usr/local/Cellar/cairo/1.14.0/include/cairo/`. A call to `npm install node-canvas` does a lot of magic to build the native library. Frankly, I don't understand that. However, the configuration process adds a lot of include paths for the compiler, including the second one I mentioned above. Then, the source code tries to load .h files using `#include <cairo/cairo.h>`. This cannot work, because this would try to open `/usr/local/Cellar/cairo/1.14.0/include/cairo/cairo/cairo.h` (notice the double `cairo`) I think. On my system, the compiler also added `/usr/local/include` by default so I got the file in question from `/usr/local/include/cairo/cairo.h`. On the other machine, that default include was missing. Probably because that clang wasn't installed as command line tools.

When I removed the useless explicit cairo include to just relay on the default path, I noticed that one .cc file (which I forget, sorry), used `include <name.h>` instead of `include <cairo/name.>` which I'd consider an error that never got noticed because of the second search path added.

Unfortunately, I don't know how to work with gyp or whatever but perhaps this report is still useful for other who have the same strange problem.

**Comment by amchang** [comment]
https://github.com/Homebrew/homebrew/issues/14123,

This patch will fix it.

**Comment by LinusU** [comment]
Should be fixed by #574
