### ISSUE TITLE
Documentation mistakenly claims need to add --enable-pdf=yes to Cairo install to support PDFs

### ISSUE THREAD

**Issue by tdingman** [Automattic/node-canvas#519]
I kept getting an error about the command not being recognized when I tried to add that flag to the `apt-get` command to install all the packages on Ubuntu. I added it on the `node-canvas` install command, but I have no idea if that was necessary.

**Comment by mltucker** [comment]
The `--enable-pdf` flag is needed when building cairo binaries.  You are installing binaries that someone else built.  Are you using ubuntu?  If you want to see what flags your packagers used, go to [launchpad](https://launchpad.net/ubuntu/+source/cairo), then select a package depending on your ubuntu version (I clicked 1.14.0-2.1ubuntu1 under The Vivid Vervet).  Then scroll down to where it says Builds and choose amd64 (or your platform).  Then click on the buildlog link ([here](https://launchpadlibrarian.net/194092106/buildlog_ubuntu-vivid-amd64.cairo_1.14.0-2.1ubuntu1_UPLOADING.txt.gz)).  When you search for `--enable-pdf`, you'll see that they included that flag when they built cairo for you.

**Comment by tdingman** [comment]
I am indeed using Ubuntu. I've never built any binaries, so when I read "Make sure to install cairo with `--enable-pdf=yes` for the PDF backend," I assumed that was an apt-get flag. I'll close the issue, but it may save some other users from heartache if you specified in the documentation.

**Comment by mltucker** [comment]
@tdingman I see why this caused an issue for you!
