### ISSUE TITLE
use sh instead of bash for util scripts

### ISSUE THREAD

**Issue by danyocom** [Automattic/node-canvas#527]
Some lighter weight/embedded linux distros do not have bash installed (only sh). However the scripts in the /util directory specify bash as the shell to use to run the script. The scripts do not use any bash specific syntax, and changing from bash to sh, would make the scripts compatible with more systems.

**Comment by TooTallNate** [comment]
PR would be accepted!

**Comment by LinusU** [comment]
I believe we use bash-specific syntax at the moment, is this still an issue in 2016?
