### ISSUE TITLE
node-gyp rebuild fails during npm install canvas

### ISSUE THREAD

**Issue by hayesmaker** [Automattic/node-canvas#528]
I get this when trying to install via $npm install canvas

npm ERR! canvas@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.1 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by kanzelm3** [comment]
+1

I'm having this issue too, seems that latest build is missing a required file for FontFace (fontconfig.h), stack trace below:

> canvas@1.2.1 install /Users/jkanzelmeyer/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  SOLINK_MODULE(target) Release/canvas-postbuild.node: Finished
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:10:
../src/CanvasPattern.h:23:9: warning: private field '_width' is not used [-Wunused-private-field]
    int _width, _height;
        ^
../src/CanvasPattern.h:23:17: warning: private field '_height' is not used [-Wunused-private-field]
    int _width, _height;
                ^
2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc:374:22: warning: unused variable 'surface' [-Wunused-variable]
    cairo_surface_t *surface = cairo_get_group_target(_context);
                     ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/PixelArray.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
../src/FontFace.cc:9:10: fatal error: 'fontconfig/fontconfig.h' file not found
#include <fontconfig/fontconfig.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/FontFace.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jkanzelmeyer/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! canvas@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.1 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /Users/jkanzelmeyer/pkg-config-0.28/pixman-0.22.0/cairo-1.12.8/wget-1.15
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by mltucker** [comment]
@hayesmaker what's the rest of the error message?

@kanzelm3 Did you follow the [installation instructions](https://github.com/Automattic/node-canvas/wiki/Installation---OSX)?

**Comment by kanzelm3** [comment]
Yes, I followed them to a T.

**Comment by hayesmaker** [comment]
I didn't want to install cairo, but after I installed macports, then cairo, then canvas, the install script runs ok.

hayesmaker@andy-mac:~/Workspace/contracts/high5/online/client_code/HTML5/kingkong/Trunk$(master)$ npm install canvas --save-dev
-
> canvas@1.2.1 install /Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/kingkong/Trunk/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  SOLINK_MODULE(target) Release/canvas-postbuild.node: Finished
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:10:
../src/CanvasPattern.h:23:9: warning: private field '_width' is not used [-Wunused-private-field]
    int _width, _height;
        ^
../src/CanvasPattern.h:23:17: warning: private field '_height' is not used [-Wunused-private-field]
    int _width, _height;
                ^
2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc:374:22: warning: unused variable 'surface' [-Wunused-variable]
    cairo_surface_t *surface = cairo_get_group_target(_context);
                     ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/PixelArray.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
In file included from ../src/FontFace.cc:7:
../src/FontFace.h:27:15: warning: private field '_ftFace' is not used [-Wunused-private-field]
    FT_Face   _ftFace;
              ^
1 warning generated.
  SOLINK_MODULE(target) Release/canvas.node
  SOLINK_MODULE(target) Release/canvas.node: Finished
canvas@1.2.1 node_modules/canvas
└── nan@1.5.3

**Comment by mltucker** [comment]
@kanzelm3 What's the result of this:

```
find /opt/X11 -name fontconfig.h
```

Alternatively, do you have X installed somewhere else?  What version of OS X are you running?

**Comment by kanzelm3** [comment]
I am running OS X Mavericks and the result of that script is:
```
find: /opt/X11: No such file or directory
```

**Comment by mltucker** [comment]
That's the problem.  You need to install X11: http://support.apple.com/en-us/HT201341

After that make sure that it gets added to your PKG_CONFIG_PATH:

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
```

**Comment by kanzelm3** [comment]
@mltucker that didn't fix the issue. Still have the same error:
```
../src/FontFace.cc:9:10: fatal error: 'fontconfig/fontconfig.h' file not found
```

**Comment by kanzelm3** [comment]
Just got it to work by doing the following:
```
PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig/ npm install canvas
```
Not exactly sure why that worked but it did!

**Comment by lynndylanhurley** [comment]
Thx @mltucker - this worked for me:

~~~bash
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
npm install canvas
~~~

**Comment by wesbarichak** [comment]
I'm getting this same error while installing on Windows 7. Any suggestions that aren't OS X-specific? :)

**Comment by wesbarichak** [comment]
Switching to the 32 bit version solved the issue for me.

**Comment by mltucker** [comment]
@wesbarichak That's good that you could fix it.  What error message did you have (for future issue searchers).  It wasn't exactly what kanzelm3 had, was it?

```
./src/FontFace.cc:9:10: fatal error: 'fontconfig/fontconfig.h' file not found
#include 
^
1 error generated.
make: ** [Release/obj.target/canvas/src/FontFace.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: make failed with exit code: 2
```

**Comment by wesbarichak** [comment]
Sorry, I can't find the original log, but it wasn't the fontface error. It was the same error as from the original post.

**Comment by tolmasky** [comment]
I am getting the fontconfig error. I have tried installing all the necessary components in multiple ways (wgetting cairo, sudo port installing it, etc etc), nothing seems to work.

**Comment by tolmasky** [comment]
(if I use the pkg-config trick, it stops being able to find libjpeg)

**Comment by mltucker** [comment]
@molmasky Where is libjpeg installed?

**Comment by ericandrewlewis** [comment]
That was a fun hour. I'm on Mac OS X Yosemite (10.10.3).

To get it working, [I installed X11](https://github.com/Automattic/node-canvas/issues/528#issuecomment-75580155) and then followed the [manual install instructions for OS X](https://github.com/Automattic/node-canvas/wiki/Installation---OSX).

**Comment by piranna** [comment]
I have the same problem when compiling statically for NodeOS (for the case, a barebones Linux with raw Node.js on top and no libraries nor graphic interface). Why is this needed? Is it only needed the headers, or the full fontconfig and binaries? Could be changed someway so it's not mandatory? Can it be disabled someway?

**Comment by piranna** [comment]
I have just put the fontconfig/fontconfig.h file in place and it compiked correctly, so seems it's only used to get some constants or structures and could be changed. What do you think?

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...

**Comment by andela-ooladayo** [comment]
@LinusU I am facing this same issue
`gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.5.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/oladayo/Documents/source/PayVer/node-canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/oladayo/.node-gyp/4.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/oladayo/.node-gyp/4.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/oladayo/Documents/source/PayVer/node-canvas',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:10:
../src/CanvasPattern.h:23:9: warning: private field '_width' is not used [-Wunused-private-field]
    int _width, _height;
        ^
../src/CanvasPattern.h:23:17: warning: private field '_height' is not used [-Wunused-private-field]
    int _width, _height;
                ^
2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
../src/FontFace.cc:9:10: fatal error: 'fontconfig/fontconfig.h' file not found
#include <fontconfig/fontconfig.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/FontFace.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/oladayo/Documents/source/PayVer/node-canvas
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok`

**Comment by LinusU** [comment]
Have you tried the solutions outlined in the thread? Installing X11 and setting the pkg-config path?

**Comment by freddneos** [comment]
Works for m1 on M1 Pro Monterey.

`arch -arm64 brew install pkg-config cairo pango jpeg giflib librsvg`

**Comment by adeelabbas409** [comment]
@freddneos solution worked for me on M1 . Thanks mate

**Comment by KJYoung** [comment]
@freddneos solution saved my life. Thanks!

**Comment by Ruobin521** [comment]
@freddneos solution worked for me on M2 Max . Thanks mate

**Comment by lynda0214** [comment]
@freddneos worked for me on M2 Macbook Air. Big Thanks!
