### ISSUE TITLE
Install node-oracledb in Windows XP (32 bit)

### ISSUE THREAD

**Issue by Mugu-FG** [Automattic/node-canvas#530]
I am trying to install node-oracledb in Windows XP (32 bit ) machine.

I followed the installation guideline.
1. Installed Python 2.7 and setup environment variable
2. Microsoft Visual Studio C++ 2008
3. Installed instantclient basic and sdk
4. Clone the project and run "npm install -g"

I am getting the following error. Can you someone help me to overcome this issue.

D:\NodeJs\node-oracledb>npm install -g

> oracledb@0.3.1 install C:\Documents and Settings\mgky\Application Data\npm\node_modules\oracledb
> node-gyp rebuild

C:\Documents and Settings\mgky\Application Data\npm\node_modules\oracledb>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
C:\Documents and Settings\mgky\.node-gyp\0.10.0\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Pers
istent<T>::New(v8::Handle<T>)'
C:\Documents and Settings\mgky\.node-gyp\0.10.0\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Pers
istent<T>::New(v8::Handle<T>)'
C:\Documents and Settings\mgky\.node-gyp\0.10.0\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Pers
istent<T>::New(v8::Handle<T>)'
C:\Documents and Settings\mgky\.node-gyp\0.10.0\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Pers
istent<T>::New(v8::Handle<T>)'
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc
..\src\njs\src\njsConnection.cpp(563): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data
..\src\njs\src\njsConnection.cpp(568): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data
..\src\njs\src\njsConnection.cpp(624): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data
..\src\njs\src\njsConnection.cpp(836): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data
..\src\njs\src\njsConnection.cpp(842): warning C4244: 'argument' : conversion from 'sb8' to 'size_t', possible loss of data
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\vector(46): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<
T>::New(v8::Handle<T>)'
C:\Program Files\Microsoft Visual Studio 9.0\vc\include\vector(46): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<
T>::New(v8::Handle<T>)'
LINK : fatal error LNK1181: cannot open input file 'C:\Documents.obj'
Project : warning PRJ0018: The following environment variables were not found:
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v3.5\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Documents and Settings\mgky\Application Data\npm\node_modules\oracledb
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok
npm ERR! oracledb@0.3.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the oracledb@0.3.1 install script.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! cwd D:\NodeJs\node-oracledb
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\NodeJs\node-oracledb\npm-debug.log
npm ERR! not ok code 0

**Comment by LinusU** [comment]
This is the node-canvas repo...
