### ISSUE TITLE
The function ‘CGFontGetGlyphPath’ is obsolete and will be removed in an upcoming update.

### ISSUE THREAD

**Issue by imjared** [Automattic/node-canvas#531]
When running `examples/text.js`, I get this output. Seems to be the case any time I try to use `strokeText` or `fillText` and I imagine any of the other text-related goodies. I'm on Yosemite 10.10.2.

This seems to be an issue upstream with Cairo [http://lists.cairographics.org/archives/cairo/2014-July/025348.html](http://lists.cairographics.org/archives/cairo/2014-July/025348.html) that's waiting on a fix but I wanted to flag it here since a) this was where I came looking initially and it might help someone find info about the issue and b) if anyone has a solution or workaround, I'd love to hear it.

**Comment by jmsaavedra** [comment]
I'm getting this same issue. OSX 10.10.2. Seems like just a warning for the moment, everything working well.  Testing on Ubuntu shortly, will report back. Any info would be helpful !

Full debug:

```
<Error>: The function ‘CGFontGetGlyphPath’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.
```

**Comment by bingomanatee** [comment]
+1 -- this is a pretty old bug!

**Comment by sungwoncho** [comment]
+1

**Comment by praneybehl** [comment]
+1

**Comment by lionkeng** [comment]
+1

**Comment by jleppert** [comment]
+1

**Comment by LinusU** [comment]
Please report this problem upstream to cairo. As said, a patch was floated but it seems that it wasn't applied, the problem lies in their code.

**Comment by jleppert** [comment]
Where would be the best place to make a report? All I see is a mailing list.

**Comment by LinusU** [comment]
> If you've found a bug in cairo, you can discuss it on the [cairo@cairographics.org](mailto:cairo@cairographics.org) mailing list, (you will need to [subscribe](http://cairographics.org/cgi-bin/mailman/listinfo/cairo) before the list will accept your mail). Or, if you prefer a web-based interface that lets you check back on the status of the bug, then enter a bug report against the cairo product at [http://bugs.freedesktop.org](http://bugs.freedesktop.org/).

**Comment by LinusU** [comment]
This is probably fixed, happy to reopen otherwise ☺️
