### ISSUE TITLE
QRCode.toPNGStream is failing due to callback undefined function

### ISSUE THREAD

**Issue by dosapati** [Automattic/node-canvas#532]
/node_modules/qrcode/node_modules/canvas/lib/pngstream.js:43
    canvas[method](function(err, chunk, len){
                  ^
TypeError: undefined is not a function
    at /node_modules/qrcode/node_modules/canvas/lib/pngstream.js:43:19
    at process._tickDomainCallback (node.js:463:13)

**Comment by zbjornson** [comment]
That means that canvas wasn't successfully built. If by chance you still need help, the installation should be easier now that prebuilds work.
