### ISSUE TITLE
Allow to define globally the default output type

### ISSUE THREAD

**Issue by piranna** [Automattic/node-canvas#534]
As proposed on https://github.com/Automattic/node-canvas/issues/533#issuecomment-77778158, add an environment and/or a config variable to set what output type is used by default instead of image.

**Comment by zbjornson** [comment]
I'm not sure what that linked comment is referring to (now maybe the `pixelFormat` for the context?), but having a change in behavior based on the build config doesn't seem ideal, when the alternative is to just explicitly specify the desired behavior at runtime with the existing API...
