### ISSUE TITLE
Install canvas failed node-canvas

### ISSUE THREAD

**Issue by ccqpein** [Automattic/node-canvas#536]
I install canvas for gitbook-plugin, but error again and again.

I have done this url, but its not work.
https://github.com/Automattic/node-canvas/wiki/installation---osx

Here is error log: 

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/canvas
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "canvas" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ccQ/npm-debug.log

**Comment by matthewlynch** [comment]
I think I have the same issue as above. 

I followed the instructions from [the wiki] and also tried the wget command in the read me. Everything seems to install okay.

Here is the output from the console: 

```
> canvas@1.2.1 install /Users/matthewlynch/some/path
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  SOLINK_MODULE(target) Release/canvas-postbuild.node: Finished
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:10:
../src/CanvasPattern.h:23:9: warning: private field '_width' is not used [-Wunused-private-field]
    int _width, _height;
        ^
../src/CanvasPattern.h:23:17: warning: private field '_height' is not used [-Wunused-private-field]
    int _width, _height;
                ^
2 warnings generated.
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc:374:22: warning: unused variable 'surface' [-Wunused-variable]
    cairo_surface_t *surface = cairo_get_group_target(_context);
                     ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/PixelArray.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
../src/FontFace.cc:9:10: fatal error: 'fontconfig/fontconfig.h' file not found
#include <fontconfig/fontconfig.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/FontFace.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/matthewlynch/some/path
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matthewlynch/some/path

```

Node v: 0.12.0
NPM v: 2.5.1

[the wiki]:https://github.com/Automattic/node-canvas/wiki/Installation---OSX

**Comment by ykan** [comment]
same problem.
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/0.10.22/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:106:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.22/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ykan/Documents/gitlab/icon-magic-server/node_modules/canvas
gyp ERR! node -v v0.11.8
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok
npm ERR! canvas@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by zbjornson** [comment]
Not looking too closely at your errors, but I see you're all using v0.11 or 0.12. I couldn't get node-canvas to work with a version later than 0.10. (https://github.com/Automattic/node-canvas/issues/535)

**Comment by xoorath** [comment]
node v0.12.2 worked fine for me on windows 7 32bit using the 32bit gtk package. Failed on windows 7 64bit using the 64bit gtk package.

**Comment by arb** [comment]
Same error here on OSX using Node 0.10.38. I followed the install instructions by hand and have the same problem with the `[Release/obj.target/canvas/src/FontFace.o] Error 1`

**Comment by z3t0** [comment]
I also have this problem on 64 bit windows 8 when trying to use three.js on node. Any suggestions?

**Comment by zbjornson** [comment]
@xoorath was that with 32-bit node? (e.g. 32-bit everything)

**Comment by xoorath** [comment]
@zbjornson 32-bit everything worked as expected. 64-bit everything didn't. The 64-bit setup was fixed by switching GTK to 32-bit, while leaving everything else 64.

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Please see the posted solution, or the updated wiki-page for windows.

For OS X please try the updated installation instructions.

Thanks
