### ISSUE TITLE
Installation on Windows - Add note on Wiki about installing with different VS version

### ISSUE THREAD

**Issue by rhengles** [Automattic/node-canvas#537]
Hello!

I was installing node-canvas on Windows, and the wiki page[1] says to install Visual Studio 2010. But I had Visual Studio 2013 installed, and I found out[2] that one can override the version directly from NPM with the flag "--msvs_version=2013". It worked for me, and it would be very helpful if this was mentioned on the page.

[1] https://github.com/Automattic/node-canvas/wiki/Installation---Windows
[2] http://kevgriffin.com/specifying-visual-studio-version-in-npm-installs/

**Comment by vweevers** [comment]
[Done](https://github.com/Automattic/node-canvas/wiki/Installation---Windows).
