### ISSUE TITLE
"Error: no error" when requiring in NodejS

### ISSUE THREAD

**Issue by MathynMovin** [Automattic/node-canvas#538]
So I just installed node-canvas on a Windows 8.1 x64 machine. I followed the Windows installation guide and I then installed the module using "npm install canvas". It looks like the installation went ok, there are no errors as far as I could see (see at the bottom of my post for the install log).

Next I write a very simple NodeJS application which only does:

var Canvas = require("canvas");

It crashes with the following error:

module.js:355
  Module._extensions\[extension\](this, filename);
                               ^
Error: no errorD:\IT\canvas-test\node_modules\canvas\build\Release\canvas.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\IT\canvas-test\node_modules\canvas\lib\bindings.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

What does this mean? What can I do to solve this problem? Anyone got any pointers?

-----------------INSTALL LOG--------------------------
> canvas@1.1.6 install D:\IT\canvas-test\node_modules\canvas
> node-gyp rebuild

D:\IT\canvas-test\node_modules\canvas {git}
{lamb} node "D:\IT\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
..\src\CanvasRenderingContext2d.cc(1256): warning C4344: behavior change: use of explicit template arguments result s in call to 'v8::Local<T> NanNew<v8::String,char*>(char *)' [D:\IT\canvas-test\node_modules\canvas\b uild\canvas.vcxproj]
          with
          [
              T=v8::String
          ]
          but the regular function 'v8::Local<T> NanNew(const char *,int)' is a better match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *,int)' to be called then you need to make it an explicit s
  pecialization
          with
          [
              T=v8::String
          ]
..\src\CanvasRenderingContext2d.cc(1285): warning C4344: behavior change: use of explicit template arguments result s in call to 'v8::Local<T> NanNew<v8::String,char*>(char *)' [D:\IT\canvas-test\node_modules\canvas\b uild\canvas.vcxproj]
          with
          [
              T=v8::String
          ]
          but the regular function 'v8::Local<T> NanNew(const char *,int)' is a better match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *,int)' to be called then you need to make it an explicit s
  pecialization
          with
          [
              T=v8::String
          ]
..\src\CanvasRenderingContext2d.cc(1314): warning C4344: behavior change: use of explicit template arguments result s in call to 'v8::Local<T> NanNew<v8::String,char*>(char *)' [D:\IT\canvas-test\node_modules\canvas\b uild\canvas.vcxproj]
          with
          [
              T=v8::String
          ]
          but the regular function 'v8::Local<T> NanNew(const char *,int)' is a better match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *,int)' to be called then you need to make it an explicit s
  pecialization
          with
          [
              T=v8::String
          ]
  color.cc
  Image.cc
  ImageData.cc
  init.cc
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
  PixelArray.cc
C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5216): warning C4512: 'v8::ExtensionConfiguration' : assig nment operator could not be generated [D:\IT\canvas-test\node_modules\canvas\build\canvas.vcxproj]
          C:\Users\mathy_000\.node-gyp\0.12.0\deps\v8\include\v8.h(5204) : see declaration of 'v8::ExtensionConfigu
  ration'
     Creating library D:\IT\canvas-test\node_modules\canvas\build\Release\canvas.lib and object D:\IT
  \canvas-test\node_modules\canvas\build\Release\canvas.exp
  Generating code
  Finished generating code
  canvas.vcxproj -> D:\IT\canvas-test\node_modules\canvas\build\Release\\canvas.node
  Copying C:/GTK/bin/libcairo-2.dll to D:\IT\canvas-test\node_modules\canvas\build\Release\\libcairo-
  2.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libfontconfig-1.dll to D:\IT\canvas-test\node_modules\canvas\build\Release\\libf
  ontconfig-1.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libexpat-1.dll to D:\IT\canvas-test\node_modules\canvas\build\Release\\libexpat-
  1.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libfreetype-6.dll to D:\IT\canvas-test\node_modules\canvas\build\Release\\libfre
  etype-6.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libpng14-14.dll to D:\IT\canvas-test\node_modules\canvas\build\Release\\libpng14
  -14.dll
          1 file(s) copied.
  Copying C:/GTK/bin/zlib1.dll to D:\IT\canvas-test\node_modules\canvas\build\Release\\zlib1.dll
          1 file(s) copied.
canvas@1.1.6 node_modules\canvas
└── nan@1.2.0

**Comment by MathynMovin** [comment]
Just to let everyone know: the other day the problem was solved. Most likely I just needed to restart my computer. I can now use canvas rendering on Windows :)

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Glad to hear it, thank you for taking the time to come back and report :+1:
