### ISSUE TITLE
Please do a release with the new io.js patches

### ISSUE THREAD

**Issue by domenic** [Automattic/node-canvas#542]
jsdom needs a new release!!

**Comment by robertjustjones** [comment]
+1

**Comment by marcello3d** [comment]
+1 using the git tagged version has been working for me, but a proper release would be better

**Comment by kangax** [comment]
Someone please send PR and I'll merge+publish (swamped with other stuff at the moment)

**Comment by domenic** [comment]
It's already merged, just needs to be published!

**Comment by kangax** [comment]
Still need package.json and changelog (like in https://github.com/Automattic/node-canvas/commit/d40f649a5458f78dde04fe95a729fd55e52ce9f4) which we didn't update yet from what i remember

**Comment by kangax** [comment]
@domenic we should just give you access to the repo. I'm sure @TooTallNate and @rvagg wouldn't mind? (I no longer seem to be able to access "Settings" here on github so gotta ask someone who can)

**Comment by TooTallNate** [comment]
@kangax Do you even have push access anymore? I'm trying to figure out these confusing GH permissions settings…

**Comment by kangax** [comment]
@TooTallNate push I still have, I think (tagged last release on feb 10, was all good — https://github.com/Automattic/node-canvas/commit/d40f649a5458f78dde04fe95a729fd55e52ce9f4)

**Comment by TooTallNate** [comment]
Ok, figured it out. We've added @domenic to have push access! :beers:

**Comment by jakeg** [comment]
Brilliant :)

**Comment by domenic** [comment]
w00t! Will try to do a release tonight.

**Comment by kangax** [comment]
Awesome, finally another pair of eyes to observe an infinite stream of all-too-dear node-canvas installation dependencies issues :D

**Comment by domenic** [comment]
Released!

**Comment by marcello3d** [comment]
@domenic hate to bug you on a friday night, but I `npm install canvas@latest` still gives me 1.2.1 (and I don't see it listed on `npm info canvas` or https://www.npmjs.com/package/canvas)

**Comment by domenic** [comment]
Hmm yes I do seem to have forgotten to look at my console output:

```
$ npm publish
npm ERR! publish Failed PUT 404
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v1.7.1
npm ERR! npm  v2.7.6
npm ERR! code E404

npm ERR! 404 Not found : canvas
npm ERR! 404
npm ERR! 404 'canvas' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Domenic\Dropbox\GitHub\Automattic\node-canvas\npm-debug.log
```

unsure why. Maybe this is the error you get when you don't have npm publish permissions? I do indeed not show up on the collaborators list on https://www.npmjs.com/package/canvas
