### ISSUE TITLE
Terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by huttarichard** [Automattic/node-canvas#545]
Guys, really nice job with node-canvas.
Since I actually decide to not use node-canvas at all, I still feel a need to report na issue.

Im using CamanJS to do some stuff with images and from some unknown reason I still get an segment fault error. I little bit dive in to find out whats going on and I found that this line https://github.com/meltingice/CamanJS/blob/master/src/core/caman.coffee#L497 is reason of this error (maybe #383 - don't know).

The example is tested on vanilla ubuntu 14.04 and (not vanilla) osx yos.
Ubuntu has installed node v0.12.2, canvas@1.2.x, caman@4.1.2, latest libcairo2-dev and pixman, same on osx.

```
#!/usr/bin/env node

var Caman = require('caman').Caman;
Caman.DEBUG = true;

Caman("./file.png", function () {
  this.brightness(50);
  this.render(function () {
    this.save("./output.png", true);
  });
});
```

Don't take me wrong, the job is done, it will successfuly generate an image. But end up with segment fault error.

**Comment by zbjornson** [comment]
I haven't found a way to repro this. If you can post more info, I'll reopen it, but it's also possible this got fixed in the last three years.
