### ISSUE TITLE
Image given has not completed loading

### ISSUE THREAD

**Issue by jun-lu** [Automattic/node-canvas#546]
````

fs.readFile('./images/'+name, function(err, squid){
	  if (err) throw err;

	  var canvas = new Canvas(width+20, height+20);
	  var ctx = canvas.getContext("2d");

	  img = new Image;
	  img.src = squid;


	  ctx.drawImage(img, 10, 10, width, height);
          //  Image given has not completed loading

````

程序读取`jpg`文件报错 `Image given has not completed loading`;

已安装 `libjpeg ` 

````
$ brew install libjpeg
Warning: jpeg-8d already installed

````

是其他什么问题吗？

**Comment by jun-lu** [comment]
已

**Comment by Mirror2Tina** [comment]
windows下，先开打开binding.gyp文件，对将jpeg的支持设置为true（'with_jpeg%': 'true',），添加libjpeg-turbo的引用（在include_dirs下也就是 '<(GTK_Root)/include/cairo',  下加一行'<(jpeg_root)/include',）
重新编译时传递参数（ 给jpeg_root设置你安装的libjpeg-turbo地址：node-gyp rebuild --jpeg_root=C:\libjpeg-turbo64）
