### ISSUE TITLE
What's the story with Canvas.Font on Windows?

### ISSUE THREAD

**Issue by ghost** [Automattic/node-canvas#547]
Hi,

I am trying get support for Canvas.Font on Windows, but I don't get far. From what I see, currently both with_pango and with_freetype are disabled so the Canvas object does not even have a Font property.
When I try to compile with either one of them, then I get into a myriad of dependency issues with sources of various libs - glib, cairo-ft, etc...

Do you perhaps have an easy setup of compiling with either pango or freetype on windows?

**Comment by chearon** [comment]
Closed via #715
