### ISSUE TITLE
SpiderMonkey bug affecting tests

### ISSUE THREAD

**Issue by donpark** [Automattic/node-canvas#55]
In `rotation() 2` visual test, I was consistently getting black dots instead of color dots in node-canvas version of image when visual test is invoked from Firefox.

Upon closer inspection, I found that SpiderMonkey's `fn.toString()` was serializing expression

`'rgb(' + 51 * i + ',' + 255 - 51 * i + ',255)`

to

`rgb(' + 51 * i + ',' + 255 - 51 * i + ',255)`

essentially stripping parentheses erroneously, which caused fillStyle to be set to

`NaN,255)`

Changing the problematic expression to

`['rgb(', 51*i, ',', 255 - 51 * i, ',255).join('')`

fixed the problem but, just in case there other similar bug in SpiderMonkey javascript serializer, I think test harness needs to be changed so original textual version of each test function is sent to server.

But faster but somewhat twisted fix might be to also use stingified-then-evaled test code for client-side canvas rendering.

**Comment by LinusU** [comment]
Please reopen if this is still relevant...
