### ISSUE TITLE
Cannot build 1.2.2 on Win64

### ISSUE THREAD

**Issue by andig** [Automattic/node-canvas#554]
Tools and Cairo are installed. These are the hard errors:

	..\src\CanvasRenderingContext2d.cc(536): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(536): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(537): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(537): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(551): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(551): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(552): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(552): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]

This is the full log:

	c:\vz\node_modules\node-canvas-linedash-visual-c>node-gyp rebuild
	gyp info it worked if it ends with ok
	gyp info using node-gyp@1.0.3
	gyp info using node@0.12.2 | win32 | x64
	gyp info spawn python
	gyp info spawn args [ 'C:\\Users\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
	gyp info spawn args   'binding.gyp',
	gyp info spawn args   '-f',
	gyp info spawn args   'msvs',
	gyp info spawn args   '-G',
	gyp info spawn args   'msvs_version=auto',
	gyp info spawn args   '-I',
	gyp info spawn args   'c:\\andi\\htdocs\\vz\\node_modules\\node-canvas-linedash-visual-c\\build\\config.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   'C:\\Users\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   'C:\\Users\\.node-gyp\\0.12.2\\common.gypi',
	gyp info spawn args   '-Dlibrary=shared_library',
	gyp info spawn args   '-Dvisibility=default',
	gyp info spawn args   '-Dnode_root_dir=C:\\Users\\.node-gyp\\0.12.2',
	gyp info spawn args   '-Dmodule_root_dir=c:\\andi\\htdocs\\vz\\node_modules\\node-canvas-linedash-visual-c',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'c:\\andi\\htdocs\\vz\\node_modules\\node-canvas-linedash-visual-c\\build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
	gyp info spawn args [ 'build/binding.sln',
	gyp info spawn args   '/clp:Verbosity=minimal',
	gyp info spawn args   '/nologo',
	gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
	Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
	  Canvas.cc
	  CanvasGradient.cc
	  CanvasPattern.cc
	  CanvasRenderingContext2d.cc
	c:\vz\node_modules\node-canvas-linedash-visual-c\src\PNG.h(205): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data (..\src\Canvas.cc) [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	  color.cc
	  Image.cc
	..\src\color.cc(353): warning C4305: 'initializing' : truncation from 'double' to 'float' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\color.cc(356): warning C4305: '*=' : truncation from 'double' to 'float' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	  ImageData.cc
	..\src\CanvasRenderingContext2d.cc(536): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(536): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(537): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(537): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(551): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(551): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(552): error C2039: 'min' : is not a member of 'std' [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(552): error C3861: 'min': identifier not found [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(647): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(648): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(649): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(650): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(651): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(652): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(653): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(654): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(658): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(659): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(660): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(661): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(665): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(666): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(687): warning C4244: '/=' : conversion from 'float' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(688): warning C4244: '/=' : conversion from 'float' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(719): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(938): warning C4244: 'initializing' : conversion from 'double' to 'int', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2246): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2249): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2252): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2254): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2279): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2284): warning C4244: 'initializing' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2301): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	..\src\CanvasRenderingContext2d.cc(2311): warning C4244: '=' : conversion from 'double' to 'float', possible loss of data [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	  init.cc
	  PixelArray.cc
	..\src\Image.cc(185): warning C4267: 'initializing' : conversion from 'size_t' to 'unsigned int', possible loss of data
	 [c:\vz\node_modules\node-canvas-linedash-visual-c\build\canvas.vcxproj]
	gyp ERR! build error
	gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onExit (C:\Users\a25058\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:269:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
	gyp ERR! System Windows_NT 6.1.7601
	gyp ERR! command "node" "C:\\Users\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
	gyp ERR! cwd c:\vz\node_modules\node-canvas-linedash-visual-c
	gyp ERR! node -v v0.12.2
	gyp ERR! node-gyp -v v1.0.3
	gyp ERR! not ok

**Comment by andig** [comment]
According to https://social.msdn.microsoft.com/Forums/vstudio/en-US/f5915ad0-a9d1-49f3-8643-ffd623f72b93/error-c2039-max-is-not-a-member-of-std?forum=vcgeneral an

  include <algorithm>

is requried for VisualC. This does indeed take care of the min/max errors.

**Comment by kkoopa** [comment]
Whatever version you're building, it is **not** 1.2.2. The line numbers do not add up. The necessary headers are [included in version 1.2.2](https://github.com/Automattic/node-canvas/blob/1.2.2/src/CanvasRenderingContext2d.cc#L12)

**Comment by LinusU** [comment]
This should be fixed in the latest version, please reopen if you still have problems.
