### ISSUE TITLE
node-canvas heroku fork does not exist anymore

### ISSUE THREAD

**Issue by austinpray** [Automattic/node-canvas#555]
Hey guys,

Over at: https://github.com/Automattic/node-canvas/wiki/Installation-on-Heroku#using-a-fork-of-node-canvas references are made to: https://github.com/elspoono/node-canvas-heroku

That repo doesn't exist anymore. Is there an updated repo I can't find or should I just remove that section?

**Comment by derekbreden** [comment]
I vote let's remove that section. I was the previous owner of that elspoono account and I definitely don't remember what that was or have backups of it.

**Comment by LinusU** [comment]
@derekbreden Sounds good for me :+1:

**Comment by marcsyp** [comment]
@derekbreden  unfortunately I don't really have the skill to pull off the "instructions" that you have linked.  Is there any other way to get this up and running on heroku?

Thanks,
Marc

**Comment by zbjornson** [comment]
Per above, the fork isn't necessary anymore. I just successfully installed canvas 2.0.0-alpha.12 and 1.6.11 on the vanilla heroku-16 stack. Both just worked thanks to prebuilds. If anyone has a need to make a from-source build work, I can look into it.
