### ISSUE TITLE
Fail to build on linux iojs 2.x

### ISSUE THREAD

**Issue by puzrin** [Automattic/node-canvas#556]
You already have report in travis:

https://travis-ci.org/Automattic/node-canvas/jobs/62086858

**Comment by wavded** [comment]
This has been fixed in master (my tests work out), @TooTallNate care to make a release?

**Comment by puzrin** [comment]
@wavded thanks, version from master now works.

@TooTallNate please publish it.

**Comment by TooTallNate** [comment]
1.2.3 tagged and published.

**Comment by puzrin** [comment]
:+1:
