### ISSUE TITLE
Tried to upgrade from 1.1.6 to 1.2.3, font sizes are broken.

### ISSUE THREAD

**Issue by dufia** [Automattic/node-canvas#561]
Part of my code:

```
var openSansRegular = new Font('openSansRegular', 'data/fonts/Open_Sans/OpenSans-Regular.ttf');

function renderFooter (c, canvasHeight) {
  c.fillStyle = "#545454";
  c.font = "normal 11px openSansRegular";
  c.fillText('MMARocks.pl SINCE 2007  -  typermma.pl', 5, canvasHeight - 6);
  return false;
}
```

I then save it like this:

```
   var out = fs.createWriteStream(__dirname + '/../../data/bet-pictures/'+ filename);
    var stream = canvas.jpegStream({
        bufsize: 4096 // output buffer size in bytes, default: 4096
      , quality: 100 // JPEG quality (0-100) default: 75
      , progressive: false // true for progressive compression, default: false
    });

    stream.on('data', function(chunk){
      out.write(chunk);
      return false;
    });
```

Changing "11px" has literally no effect at all, size seems to default to 10px(or smth) at all times...

Also checked, its broken since 1.2.0.

Regards,
Konrad

**Comment by bmv437** [comment]
I've noticed this as well. It might be have something to do with the use of an external font. 

If you try `c.font = "18px Arial";` font size will work. It looks like if it fails to parse any part of the font string (such as font-family), it discards the entire action of setting weight, size, and font-family.

Can anyone else confirm?

**Comment by Caged** [comment]
I'm getting a different behavior running font.js.  I'm also getting odd behavior running text.js where the letters all overlap.  It looks like [cairo was updated in March](http://cairographics.org/news/cairo-1.14.2), so I'm wondering if that has anything to do with the font issues. 

![text](https://cloud.githubusercontent.com/assets/25/8246830/ddd18110-15f9-11e5-85df-4d046ce78bc5.png)

![font](https://cloud.githubusercontent.com/assets/25/8246824/c09fc2aa-15f9-11e5-9770-2bb1e2e958d5.png)

**Comment by dunn** [comment]
I'm having the same problem, or a very similar one.  With cairo 1.14.2, and node 0.12.4 (both installed with Homebrew) on 10.10.3, I get this for `text.js`:
![text](https://cloud.githubusercontent.com/assets/985416/8269462/f66d1c7e-175d-11e5-8e90-7aa25c4f8d1c.png)

and this for `font.js`:
![font](https://cloud.githubusercontent.com/assets/985416/8269465/fe5cdb72-175d-11e5-9273-063cdc3d16e1.png)

**Comment by LinusU** [comment]
The text backend has been reworked in 2.x, could you please try with that version and reopen if the issue persists, thanks ☺️
