### ISSUE TITLE
the property font is not compatiable with HTML5 canvas font 

### ISSUE THREAD

**Issue by zwzw911** [Automattic/node-canvas#566]
HTML5 canvas font accept: font-style/font-variant/font-weight/font-size/font-family, for example, context.font="italic small-caps bold 12px arial", but node-canvas only accept  font-style/font-size/font-family, it set font-variant or font-weight, the property font change to default value "10px sans-serfi"

**Comment by keverw** [comment]
Interesting. I posted about this here https://github.com/Automattic/node-canvas/issues/53#issuecomment-151760247

but noticed bold isn't working in my case. I guess it's not supported yet?

**Comment by kaivi** [comment]
Yep, all options other than font-size and font-family are being ignored by node-canvas. When one specifies both font-style and font-variant, context.font gets reset to a default one:

## Chrome 48.0.2564.116 on OS X
![chrome-osx](https://cloud.githubusercontent.com/assets/3091192/13350427/4858a70a-dc80-11e5-9c4a-5913e4a9684d.png)

## canvas v1.3.10 on OS X
![node-canvas-osx](https://cloud.githubusercontent.com/assets/3091192/13350426/48566364-dc80-11e5-9fb9-fc294ffd40ac.png)

Here is [an in-browser JSFiddle](https://jsfiddle.net/rggzfyzf/3/), this code attempts to auto-fit font size to fill a rectangle.

**Comment by yever** [comment]
@zwzw911, the issue with not parsing the font style correctly (especially when it includes the variant) was fixed in #891. In the meantime, I can't get `pango` to actually render small-caps. Most fonts don't support it and I'm not sure that `pango` is capable of using this feature when it does exist.  I opened an issue for this: #894.

I think that the "font reset" problem is fixed, so should this issue be closed now?

**Comment by jleclanche** [comment]
I'm not sure if [line-height](https://developer.mozilla.org/en/docs/Web/CSS/line-height) (`16px/1em`) is being taken into account right now, I don't think it is, but it doesn't error anymore in the 2.0 alpha, so yay. :)

**Comment by chearon** [comment]
There is no line height on canvas since there's no layout functionality in the font APIs, it just draws one line of text. It might parse OK but would be ignored.

**Comment by zbjornson** [comment]
I think since #944 landed, this is as good as we can get. Please comment if you find any other discrepancies.
