### ISSUE TITLE
Couldn't able to install canvas in Windows 8

### ISSUE THREAD

**Issue by ravimmrk** [Automattic/node-canvas#579]
Please can you help in installing the canvas in windows8. Below given is the error log. Thanks in advance for your needful help. 

Already tried installing microsoft .net frame work it didn't help.
Thanks,
Ravi Kumar

Jul 3, 05:19

Please can you help in installing the canvas in windows8. Below given is the error log. Thanks in advance for your needful help.

E:\>npm install canvas
\
> canvas@1.2.3 install E:\node_modules\canvas
> node-gyp rebuild

E:\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (rebuild)
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'canvas.vcxproj' is invalid. Platform='x64'. You may be seeing
this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [E:\node_modules\canvas\build\canvas.vcx
proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack at ChildProcess.emit (events.js:110:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\node_modules\canvas
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
npm ERR! node v0.12.3
npm ERR! npm v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! E:\npm-debug.log

**Comment by eppsilon** [comment]
Were you following the [Windows installation guide](https://github.com/Automattic/node-canvas/wiki/Installation---Windows)? If GTK is not in C:\GTK, you can specify the path using --GTK_Root, like so:

```npm install canvas --GTK_Root=/path/to/gtk```

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Please see the posted solution, or the updated wiki-page...

**Comment by michaelscheurer** [comment]
The [Windows installation guide](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows) has been moved to a new place: [](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows)
