### ISSUE TITLE
Threading Question

### ISSUE THREAD

**Issue by timkendall** [Automattic/node-canvas#581]
How does node-canvas work exactly? I know it makes calls to the Cairo C++ library but does this happen in  a separate thread?

**Comment by TooTallNate** [comment]
Only the "async" calls happen on the thread pool, i.e. [`Canvas#toBuffer(callback)`](https://github.com/Automattic/node-canvas#canvastobuffer-async). Everything synchronous happens on the same JS thread that Node.js is running on.

Hope that helps!

**Comment by timkendall** [comment]
Thanks!
