### ISSUE TITLE
Convert Hexadecimal To PNG/JPEG

### ISSUE THREAD

**Issue by wpp2014** [Automattic/node-canvas#587]
I get the imformation of a picture, but the format is hexadecimal. How convert it to png or jpeg .....
```
{ width: 128,
  height: 128,
  data: <Buffer 80 00 00 00 80 00 00 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ff 00 ff ff ... > }
```
this is my format, I want to convert it to flow format:
```
<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 96 00 00 00 96 08 06 00 00 00 3c 01 71 e2 00 00 00 06 62 4b 47 44 00 ff 00 ff 00 ff a0 bd a7 ... >
```

**Comment by LinusU** [comment]
Actually that indicates that it the data lives in a buffer, not that it's in hexadecimal.

Do you think that the data is just raw pixels? It's kind of hard to tell but it looks like it.

**Comment by wpp2014** [comment]
This is an array of possible icons for the client. This specification does not stipulate what size these icons should be, but individual desktop environments or toolkits may do so. The Window Manager MAY scale any of these icons to an appropriate size.

This is an array of 32bit packed CARDINAL ARGB with high byte being A, low byte being B. The first two cardinals are width, height. Data is in rows, left to right and top to bottom.

**Comment by LinusU** [comment]
This isn't really the right forum for this. I would recommend opening a post on [StackOverflow](http://stackoverflow.com) instead.

`canvas` is a library for drawing images which can then be exported to jpeg/png. It could possibly be implemented by utilizing this library but that implementation would be out of the scope for us to do for you.
