### ISSUE TITLE
No package 'cairo' found

### ISSUE THREAD

**Issue by Zander1983** [Automattic/node-canvas#595]
Im trying to install npm canvas. I got lots of errors when running:

sudo npm install canvas
So I downloaded the package from git and ran:

make
But i end up with an error regarding Cairo:

> canvas@1.2.4 install /home/mark/Programming/node-canvas-master
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mark/Programming/node-canvas-master
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! canvas@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mark/Programming/node-canvas-master/npm-debug.log
make: *** [build/Release/canvas.node] Error 1
I have already run:

sudo apt-get install libcairo2-dev
and:

 sudo apt-get install libjpeg-dev
And these have installed. But still I get this error. Any ideas what I can do?

**Comment by LinusU** [comment]
What does the following command output for you?

```sh
dpkg-query -S cairo.pc
```

This is my output, and I can compile just fine:

```text
/usr/lib/i386-linux-gnu/pkgconfig/cairo.pc
```

**Comment by equiet** [comment]
Same issue here.

Here's my output to `dpkg-query -S cairo.pc` (running on Heroku):
```
libcairo2-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/cairo.pc
```

**Comment by LinusU** [comment]
@equiet What is the output of `pkg-config --cflags cairo`?

**Comment by equiet** [comment]
@LinusU `-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12`

**Comment by LinusU** [comment]
@equiet Are you sure that you are getting the exact same error? I don't think so since it complains that "Package cairo was not found in the pkg-config search path."

**Comment by equiet** [comment]
@LinusU Sorry, probably not the same error. At first sight they seemed related. Here's what I see:

```
remote:        > canvas@1.2.4 install /tmp/build_8e7d47039f66a696c657cbb579c67ad1/node_modules/canvas
remote:        > node-gyp rebuild
remote:
remote:        Package pangocairo was not found in the pkg-config search path.
remote:        Perhaps you should add the directory containing `pangocairo.pc'
remote:        to the PKG_CONFIG_PATH environment variable
remote:        No package 'pangocairo' found
remote:        gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1. while trying to load binding.gyp
remote:        gyp ERR! configure error
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
remote:        gyp ERR! System Linux 3.13.0-57-generic
remote:        gyp ERR! command "node" "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_8e7d47039f66a696c657cbb579c67ad1/node_modules/canvas
remote:        gyp ERR! node -v v0.12.7
remote:        gyp ERR! node-gyp -v v2.0.1
remote:        gyp ERR! not ok
remote:        npm ERR! Linux 3.13.0-57-generic
remote:        npm ERR! argv "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/bin/node" "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.npmrc"
remote:        npm ERR! node v0.12.7
remote:        npm ERR! npm  v2.11.3
remote:        npm ERR! code ELIFECYCLE
remote:
remote:        npm ERR! canvas@1.2.4 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the canvas@1.2.4 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the canvas package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls canvas
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_8e7d47039f66a696c657cbb579c67ad1/npm-debug.log
```

**Comment by LinusU** [comment]
@equiet Your's is a separate issue, could you please open a new issue and move the output to that one?

**Comment by equiet** [comment]
@LinusU Yes, here it is: #599.

**Comment by Zander1983** [comment]
It's working for me now with previous version of canvas(1.2.23)

**Comment by LinusU** [comment]
@Zander1983 Could you please try with `1.2.7`? :+1: thank you!
