### ISSUE TITLE
Can't compile Cairo for 32 bits

### ISSUE THREAD

**Issue by piranna** [Automattic/node-canvas#597]
When trying to compile node-canvas for i686 using musl as libc and I get errors on Cairo regarding to undefined __uint128_t and __int128_t symbols. These are extensions of GCC that seems are only available for 64 systems but Cairo shouldn't be trying to use them on 32 bits systems, or at least it should have check for them. Is it a Cairo bug or I'm doing something wrong?

**Comment by piranna** [comment]
Any update on this? Anyone knows what could be happening here?

**Comment by LinusU** [comment]
Have you tried building vanilla Cairo and see if that works?

**Comment by LinusU** [comment]
Any updates? Please feel free to reopen if you have any more information...
