### ISSUE TITLE
Node Canvas 1.2.7 fails to be installed in CentOS release 5.8

### ISSUE THREAD

**Issue by stuartZhang** [Automattic/node-canvas#613]
Hello specialist,

I run across a failure of the installation of <Node-Canvas 1.2.7> over the <CentOS release 5.8> platform.

(1) The full version of the Linux OS

LSB Version:    :core-4.0-ia32:core-4.0-noarch:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 5.8 (Final)
Release:        5.8
Codename:       Final

(2) The referenced installation instruction is https://github.com/Automattic/node-canvas/wiki/Installation---Amazon-Linux-AMI-(EC2) and https://github.com/Automattic/node-canvas/wiki/installation---osx

(3) The OS GUI library (e.g. Xorg-x11) has been installed by the following command:

   sudo yum groupinstall "X Window System" 

However, when I run the command "npm install canvas@1.2.7", the below error is still thrown to me:

> canvas@1.2.7 install /usr/local/home/stzhang/var/programs/node_modules/canvas
> node-gyp rebuild
make: Entering directory `/usr/local/home/stzhang/var/programs/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
../src/Canvas.cc: In static member function âstatic void Canvas::StreamJPEGSync(const v8::FunctionCallbackInfo<v8::Value>&)â:
../src/Canvas.cc:460: warning: passing âdoubleâ for argument 2 to âvoid write_to_jpeg_stream(cairo_surface_t*, int, int, bool, closure_t*)â
../src/Canvas.cc:460: warning: passing âdoubleâ for argument 3 to âvoid write_to_jpeg_stream(cairo_surface_t*, int, int, bool, closure_t*)â
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc: In member function âvoid Context2d::shadow(void (*)(cairo_t*))â:
../src/CanvasRenderingContext2d.cc:383: warning: passing âdoubleâ for argument 2 to âcairo_surface_t* cairo_image_surface_create(cairo_format_t, int, int)â
../src/CanvasRenderingContext2d.cc:383: warning: passing âdoubleâ for argument 3 to âcairo_surface_t* cairo_image_surface_create(cairo_format_t, int, int)â
../src/CanvasRenderingContext2d.cc:379: warning: unused variable âsurfaceâ
../src/CanvasRenderingContext2d.cc: In member function âvoid Context2d::blur(cairo_surface_t*, int)â:
../src/CanvasRenderingContext2d.cc:475: warning: converting to âintâ from âfloatâ
../src/CanvasRenderingContext2d.cc: In static member function âstatic void Context2d::SetShadowBlur(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)â:
../src/CanvasRenderingContext2d.cc:1014: warning: converting to âintâ from âdoubleâ
../src/CanvasRenderingContext2d.cc: In static member function âstatic void Context2d::SetFont(const v8::FunctionCallbackInfo<v8::Value>&)â:
../src/CanvasRenderingContext2d.cc:1888: error: âPANGO_WEIGHT_MEDIUMâ was not declared in this scope
make: *** [Release/obj.target/canvas/src/CanvasRenderingContext2d.o] Error 1
make: Leaving directory `/usr/local/home/stzhang/var/programs/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/home/stzhang/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.18-308.11.1.el5PAE
gyp ERR! command "node" "/usr/local/home/stzhang/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/home/stzhang/var/programs/node_modules/canvas
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 2.6.18-308.11.1.el5PAE
npm ERR! argv "/home/stzhang/usr/bin/node" "/home/stzhang/usr/bin/npm" "install" "canvas"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! canvas@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/home/stzhang/var/programs/npm-debug.log

In my view, the vital error is "../src/CanvasRenderingContext2d.cc:1888: error: âPANGO_WEIGHT_MEDIUMâ was not declared in this scope".

Could you please give me a bit of help for fixing the issue?

**Comment by stuartZhang** [comment]
By the way, it's worth saying that node-canvas@1.1.6 can be successfully installed in the same Linux host.

**Comment by LinusU** [comment]
Could be that you have an outdated version of pango installed...

Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
