### ISSUE TITLE
Cannot use custom font

### ISSUE THREAD

**Issue by sungwoncho** [Automattic/node-canvas#624]
I am following the `example/font.js` to use a custom font, but the font does not show up.

Here is what I have so far:

```javascript
var Canvas = require('canvas')
    , Image = Canvas.Image
    , Font = Canvas.Font
    , path = require('path');

var gubblebum = new Font('gubblebum', fontFile('GUBBLO___.ttf'));

function fontFile(name) {
  return path.join(__dirname, '../fonts', name);
}

function draw() {
  var canvas = new Canvas(100, 100)
    , ctx = canvas.getContext('2d');

  ctx.addFont(gubblebum);
  ctx.font = 'bold 40 gubblebum';
  ctx.fillText('test', 25, 45);

  return canvas;
}

module.exports = draw;
```

When rendered in a browser, the font is left unchanged from the default, as well as the size.

Interestingly, when I do `ctx.font = 'bold 40 someGibberish';` the font size is applied correctly.

**Comment by chearon** [comment]
is this happening on OS X? I'm trying to narrow down on the issue (see #628)

**Comment by sungwoncho** [comment]
Yes it happened on OSX Yosemite.
