### ISSUE TITLE
jpegStream causes segfault

### ISSUE THREAD

**Issue by targos** [Automattic/node-canvas#629]
On Node v4.0.0.
There is no crash with 0.12 but the resulting file is not a valid jpeg.

```js
var fs = require('fs');
var Canvas = require('canvas');

var canvas = new Canvas(640, 480);
var out = fs.createWriteStream('./test.jpg');
var stream = canvas.jpegStream();
stream.pipe(out);
```

http://pastebin.com/raw.php?i=qpi1Dzfv

**Comment by ashaposhni** [comment]
The same issue on Node 4.1.0 / canvas 1.2.9

**Comment by inssein** [comment]
Confirmed. Newer deployment of my fabric.js based apps no longer work as the version dependency is set to 1.2*. 1.2.8 works fine, where as 1.2.9 does not.

**Comment by LinusU** [comment]
Hmm, that's unfortunate. Than it's because of the switch to Nan 2.x, we must have missed something.

@zbjornson any ideas?

**Comment by zbjornson** [comment]
Fixed, sorry about that.

(Something seems to be suppressing the output of the unit tests in the travis logs, but I added a test for this.)
