### ISSUE TITLE
Receiving error when using CanvasContext#drawImage 

### ISSUE THREAD

**Issue by henrytseng** [Automattic/node-canvas#632]
```
node(2013,0x7fff773e8300) malloc: *** error for object 0x102831800: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
>> application exited with signal SIGABRT
```

Receiving error the following error when using the context#drawImage method.

**Comment by zbjornson** [comment]
Does this happen for you in 1.2.8? `drawImage` has some [other long-standing open issues](https://github.com/Automattic/node-canvas/search?q=drawimage&type=Issues&utf8=%E2%9C%93) already. Would be good to know if this came from the nan 2 update.

**Comment by LinusU** [comment]
@henrytseng Please provide more info...
