### ISSUE TITLE
alternate renderers.

### ISSUE THREAD

**Issue by carlsonsolutiondesign** [Automattic/node-canvas#633]
Have you considered alternate renderers besides cairo, such as gnuplot's term libraries? I'm looking for a 3d printing solution to 2d visualization that I don't need a cad tool for. I want to be able to produce an STL or PLY file from canvas.

Thanks!

**Comment by zbjornson** [comment]
I think this would be out of scope for this lib, which aims to stick closely to HTML Canvas spec. However, I know there are utilities to convert SVG files to STL (in the form of extrusions), like this: https://github.com/rcalme/svg-to-stl, and you can create SVG images with canvas already.
