### ISSUE TITLE
Strange error from travis build

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#636]
It might be related to #635 

```text
$ node --version
v1.8.4
$ npm --version
2.9.0
$ nvm --version
0.23.3
```

```text
$ npm test
> canvas@1.2.9 test /home/travis/build/Automattic/node-canvas
> make test
   canvas: 1.2.9
   cairo: 1.10.2
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․*** glibc detected *** /home/travis/.nvm/versions/io.js/v1.8.4/bin/iojs: corrupted double-linked list: 0x0000000002be7dd0 ***
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Link to job: https://travis-ci.org/Automattic/node-canvas/jobs/83060391

**Comment by zbjornson** [comment]
Fixed by #635

**Comment by LinusU** [comment]
Are you sure, I found it during that build? Or am I missing something?

**Comment by zbjornson** [comment]
I don't see it in the latest build:
https://travis-ci.org/Automattic/node-canvas/jobs/84989570
Am I missing it?
(Although for some reason the stdout from `make test` didn't print either. Seen that behavior transiently in this repo, not sure why.)

**Comment by LinusU** [comment]
I was just thinking that it was a rare race condition, but you might be right, it could be gone now.

Okay I just tried running the tests with that version of iojs a very large number of times, no errors what so ever. Closing this...
