### ISSUE TITLE
Can we use Nan::TypedArrayContents

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#637]
@zbjornson I think that this can help some of your ifdefs, it will be released with Nan 2.1

nodejs/nan#486

**Comment by zbjornson** [comment]
Looks like it will help with at least some cases. Creating new typed arrays might still need directives. Will play with it when it's in release.

**Comment by LinusU** [comment]
It's already in release ;)

**Comment by LinusU** [comment]
Tried it out myself, it's super easy to use :)

`encode.cc`
https://github.com/LinusU/node-lodepng/commit/f5b68e12c1d54eb72e8a98ffce1addbc0461f570

**Comment by zbjornson** [comment]
See also https://github.com/nodejs/nan/issues/521
