### ISSUE TITLE
namespace for node-canvas API extensions

### ISSUE THREAD

**Issue by RandomEtc** [Automattic/node-canvas#65]
Nice to see you're experimenting with the canvas API with things like pattern quality. I've been thinking about a few other extensions I'd like to try (setting path from an array, stroke dash array, line patterns, text on a path). Rather than cluttering the canvas spec namespace with unofficial extensions, perhaps a prefix 'node' would help?

This would be like the vendor-specific CSS extensions (webkit- moz- etc), and Mozilla does this for some of their text operations so there's a precedent for canvas too: https://developer.mozilla.org/en/drawing_text_using_a_canvas

**Comment by LinusU** [comment]
Please reopen if still relevant...
