### ISSUE TITLE
Replace `port` command with `brew` command in README

### ISSUE THREAD

**Issue by dbkaplun** [Automattic/node-canvas#651]
port's barely used anymore compared to brew. The README should use homebrew instead of port.

**Comment by LinusU** [comment]
Couldn't agree more :+1: 

Pull request welcome :)

**Comment by LinusU** [comment]
Maybe we could have a quick start table?

OS | Command
----- | -----
OS X | `brew install ...`
Ubuntu | `sudo apt-get install ...`
Fedora | `sudo yum install ...`
Windows | [Link](http://example.com/)

**Comment by kangax** [comment]
Yep, good idea!

**Comment by LinusU** [comment]
Submitted a PR! @dbkaplun do you like it?
