### ISSUE TITLE
node-canvas fails on require('canvas')

### ISSUE THREAD

**Issue by HendrixString** [Automattic/node-canvas#654]
Hi.

please help me if you can

I am reporting an issue with the following scenario:
1) I compiled node-canvas on a windows 7 machine, with io.js, Python 2.7
and visual studio 2013 and GTK. all versions are 64 bit. Everything went smoothly,
and 'canvas.node' was created inside the Release folder.
2) I copied the node-canvas folder into another machine with windows 8.1, where I am using github-electron. I embedded node-canvas folder inside the 'node_modules' folder, and also changed the
main package.json file to add node-canvas as a dev-dependency.
3) I wrote a test script that only used require('canvas').
4) I ran the software and got an error without any message. only that require has failed.

additional info:
- 'canvas.node' is present

**Comment by LinusU** [comment]
I don't think that electron can use binaries compiled for io.js, please recompile it with the tools provided by electron.

Also, electron has the canvas from WebKit built in, do you really need this library?

**Comment by tonbz** [comment]
Did you test it working or not on windows 7? And I think you need to build it in windows 8.1 again for current environment.

**Comment by mreshetHaifa** [comment]
worked like a charm on windows 10
