### ISSUE TITLE
Undefined symbol while trying to get Canvas data

### ISSUE THREAD

**Issue by varunsaravagi** [Automattic/node-canvas#657]
I am trying to write the image in Canvas to a file. I get this error:
<code>symbol lookup error: /home/mpc/MPCProject/server/node_modules/canvas/build/Release/canvas.node: undefined symbol: _ZN4node6Buffer3NewEPKcm </code>

I tried using Canvas.toBuffer(), Canvas.toDataURL(), and Canvas.jpegStream() and get the same error.
My versions are:

Node: 0.10.25
Canvas: 1.3.0

**Comment by zbjornson** [comment]
That sounds like a bad build or like it was built for one version of node and invoked with another... How did you build?

**Comment by varunsaravagi** [comment]
I installed using the commands given in Readme. First I installed cairo dependencies and then used npm to install canvas.

**Comment by LinusU** [comment]
Hmm, this is indeed very strange. I just tried it myself on Node 0.10 and it work for me.

It seems like the function `node::Buffer::New` can't be found...

**Comment by zbjornson** [comment]
Definitely no messages during the build? You're building for the same version of node that you're trying to use it with? What's `node-gyp -v` for you?

**Comment by varunsaravagi** [comment]
<code>node-gyv -v</code> gives me v0.10.10
I got some messages during build, have attached the screenshot:

![npmcanvas](https://cloud.githubusercontent.com/assets/725323/11315096/d1a2231e-8fba-11e5-92ea-fc39c8efcc3f.png)

**Comment by zbjornson** [comment]
Can you try upgrading to the current version of node-gyp (3.1.0) and rebuilding?

**Comment by varunsaravagi** [comment]
I updated to the said version and did a re-build. The message still comes.

**Comment by zbjornson** [comment]
The warning in the image you patsed (comparison between signed and unsigned) you can ignore. You still get the symbol lookup error when running your cod?

**Comment by varunsaravagi** [comment]
No. It is gone now.
Thanks a lot for your help.
