### ISSUE TITLE
Support for CanvasRenderingContext2D.currentTransform

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#658]
I think it would be nice to support this feature, it allows you to either set, or read back the current transformation that is being applied to the canvas.

More info at MDN: [CanvasRenderingContext2D.currentTransform](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/currentTransform)

**Comment by zbjornson** [comment]
~80% done: https://github.com/Automattic/node-canvas/compare/master...zbjornson:current-tform.
