### ISSUE TITLE
Shadow on images is incorrect if the image is scaled

### ISSUE THREAD

**Issue by inssein** [Automattic/node-canvas#668]
Can't believe I didn't see this before, but shadow position is wrong if the image is scaled. Will try fixing this tomorrow, and hopefully include a test as well.

**Comment by inssein** [comment]
Also, the Y position of the shadow and glow is wrong as well, there was a mistake in the PR which I will be rectifying tomorrow.

**Comment by LinusU** [comment]
Nice catch, thanks for the help! I'll be ready to review :+1:

**Comment by denkan** [comment]
Sorry for hi-jacking an old issue.

I'm having trouble with shadow when using scale() on context; shouldn't the shadowBlur value increase accordingly to scale as well? 

My tests seems to be leaving the blur untouched, making the blur/shadow effect barely visible when scaling up. 

Am I doing something wrong or do we have a valid issue here? :)

**Comment by LinusU** [comment]
Seems like a valid issue to me, could you try it out in a web browser?

**Comment by denkan** [comment]
@LinusU, actually didn't try out in browser. 
As far as I can see, the browser doesn't scale the blur value either. 

See fiddle:
https://jsfiddle.net/5aajvm3u/

A bit odd that shadowBlur is the only value that needs manually handling, if you ask me. But node-canvas is doing good (Y) :)
