### ISSUE TITLE
error installing keystonejs 

### ISSUE THREAD

**Issue by Procode-Egypt** [Automattic/node-canvas#673]
while trying to install the keystone app i had an error

my steps was : 
root@company:~/website/keystone/instaaltion# npm install -g generator-keystone

the coming errors was : 
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "node" "/root/.nvm/v0.11.13/bin/npm" "install" "-g" "generator-keystone"
npm ERR! node v0.11.13
npm ERR! npm  v3.3.9
npm ERR! code ENOMEM
npm ERR! errno ENOMEM
npm ERR! syscall spawn

npm ERR! spawn ENOMEM
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/website/keystone/instaaltion/npm-debug.log
  what should i do to setup app ?

**Comment by LinusU** [comment]
I think that you have posted this to the wrong repo, this is the repository for node-canvas.
