### ISSUE TITLE
jpegstream is broken since 1.2.6

### ISSUE THREAD

**Issue by mnill** [Automattic/node-canvas#674]
After 1.2.6 jpeg stream makes for me really big files with some trash. Tested on mac and linux.

**Comment by mnill** [comment]
Really big - 10 mb for file 300kb

**Comment by zbjornson** [comment]
Can you provide your test code please?

**Comment by mnill** [comment]
@zbjornson 

Sure:

```javascript
var canvas = require('canvas');

var c = new canvas(2048, 1536);

c.context = c.getContext('2d');
for (i=0; i<2048*1536; i++) {
    c.context.fillStyle = "rgb("+ i%255 +","+i%255+","+i%255+")";
    c.context.fillRect(i%2048, parseInt(i/2048), 1, 1);
}

var stream = c.jpegStream({
    bufsize: 1024*1024*10 // output buffer size in bytes, default: 4096
    , quality: 75 // JPEG quality (0-100) default: 75
    , progressive: false // true for progressive compression, default: false
});
var bufs = [];
stream.on('data', function(d){ bufs.push(d); });
stream.on('end', function() {
    var buf = Buffer.concat(bufs);
    require('fs').writeFileSync(require('path').join(__dirname, '/test.jpg'), buf);
    console.log('all done', buf.length);
});
```

With latest version i have: 'all done 10485760'
With 1.2.9 i have 'all done 571936'
I found it has been broken in 1.2.10
On 1.2.9 it is worked correctly.

**Comment by targos** [comment]
The `bufsize` option seems important here. If I remove it I get `all done 573440`

**Comment by mnill** [comment]
Hm, really missed that 10485760 = 1024*1024*10.  Maybe it is not issue.  Thanks.

**Comment by zbjornson** [comment]
We should probably clamp the length of the returned buffer though so this
can't happen...

**Comment by LinusU** [comment]
This still feels like a bug to me

**Comment by LinusU** [comment]
Another thing that I discovered just now is that the stream isn't a spec-compliant `Readable` stream. Namely there isn't a function `.read([n])`.

**Comment by LinusU** [comment]
Okay, here is some very short code demonstrating the issue:

```javascript
const assert = require('assert')
const Canvas = require('canvas')
const SIZE = 10 * 1024 * 1024

let c = new Canvas(10, 10)
let s = c.jpegStream({ bufsize: SIZE })

s.on('data', function (chunk) {
  assert(chunk.length < SIZE)
})
```
