### ISSUE TITLE
Draw operations are not guaranteed to complete before converting to PNG?

### ISSUE THREAD

**Issue by atomizer** [Automattic/node-canvas#683]
node 5.1.1, node-canvas 1.3.4, Windows 7 x64

What I do:

1. Render frames of an animation to `Canvas` instances
2. Save them to PNG files or buffers. Tried all of the following: `toDataURL()`, `toBuffer()` and `pngStream()` - same results with all of them

What happens is that sometimes a partially-rendered image is saved. For example, here is the same frame when it gets cut on the left, and when saved correctly on the right:
![](https://i.imgur.com/FpUUT1T.png) ![](https://i.imgur.com/IKwMr2S.png)
You can see I added borders to every piece and a green square as the last operation on the canvas to indicate completeness.

I tried to write a simple example/test for this but I am unable to reproduce it in a sterile environment. What I can say is that:
  - everything always completes without throwing
  - most likely not a problem with my program or input data, because the effect is random (which frames get cut and in what way seems to depend on amount of frames drawn total)

Am I doing something wrong? How do I even begin to debug this? Is it possible that canvas somehow enters a weird state when it doesn't update itself and silently eats all draw calls?

[This](https://github.com/Automattic/node-canvas/blob/eb97ef838658ee7a9cafb44bb20f3253e044e42b/src/PNG.h#L23) looks suspicious (but who am I to say, I have no idea of how this actually works).

**Comment by automata** [comment]
Interesting, I do not know if it's related but I'm writing a canvas to a stream (tried with both `pngStream` and `jpegStream`) and then I'm reading it back in a child process.

```coffeescript
  out = fs.createWriteStream tmpFile.path
  stream = canvas.pngStream()
  stream.on 'data', (chunk) ->
    out.write(chunk)
  stream.on 'end', () ->
    try
      # Delay it a bit to avoid premature stream ending, it helps but not always
      setTimeout () ->
        onEnd tmpFile, cascade, callback
      , 100
    catch e
      callback e
      tmpFile.unlink()
```

Sometimes, randomly, I get a `libpng error: Read Error` on the child process (called by `onEnd` in the listing above). I investigated it a bit and nothing was throw by the stream writer, however it seems the writer didn't finished writing the file properly, and then the child process gets an unfinished/corrupted file.

Any ideas?

**Comment by atomizer** [comment]
Most likely not related - I don't have any problems with the PNGs themselves. My problem is on a higher level than streaming (I get same results with both streaming and synchronous `toDataURL()`).

Related to the issue, if anyone encounters this - I worked around it by drawing each frame in a separate process. It's a crutch, it's **super slow**, but it works.

**Comment by atomizer** [comment]
I was completely wrong; the actual issue here is #702
