### ISSUE TITLE
Error: libjpeg.so.8: cannot open shared object file: No such file or directory in centos 6.6

### ISSUE THREAD

**Issue by rohit-chaubey** [Automattic/node-canvas#684]
I've installed all the dependencies via yum installer given in the readme page. But i'm still getting this error.

**Comment by rohit-chaubey** [comment]
Ok. Problem solved. Just rebuild the canvas module with node-gyp.
STEPS :
1) npm install node-gyp
2) goto node_modules/canvas
3) node-gyp rebuild

**Comment by jonathanborges** [comment]
Install node-gyp global and rebuild. Works fine! Thanks.
