### ISSUE TITLE
context.restore makes canvas not able to draw anything

### ISSUE THREAD

**Issue by fuzhenn** [Automattic/node-canvas#691]
A bug we encountered here.

My environment:
Windows 7 Pro 64-bit.
Node 5.1.0
node-canvas 1.3.5
GTK 2.22.1

If you invoke context.restore() before any other operations, then the canvas will be always blank.

for example, in examples/image-src.js

![image](https://cloud.githubusercontent.com/assets/13678919/11805835/050d7d28-a34a-11e5-9eeb-be50b5b021b4.png)

**Comment by atomizer** [comment]
Side note, this broken state looks exactly like in #702. Would be great if it would at least crash instead of blackholing everything.

**Comment by zbjornson** [comment]
This was fixed in 8ef00a4db19b647dd124f18a525a2fb069f099ff!
