### ISSUE TITLE
Canvas.Image : data access

### ISSUE THREAD

**Issue by whatisor** [Automattic/node-canvas#693]
Hello,
To access pixel data of original DOM Image, we have Image.data.
However, I have no way to access pixel data of Canvas.Image.
Thank you

**Comment by LinusU** [comment]
I have never seen `Image.data` and it doesn't seem to be available in Safari. Do you have a link to any specification or documentation?

**Comment by whatisor** [comment]
Sorry, it is my mis-understand.
