### ISSUE TITLE
Problem with npm install canvas

### ISSUE THREAD

**Issue by kronsi** [Automattic/node-canvas#697]
Hi I get the following error if I try to install the canvas modul.

165 error Darwin 15.2.0
166 error argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install"
167 error node v5.3.0
168 error npm  v3.3.12
169 error code ELIFECYCLE
170 error canvas@1.3.5 install: `node-gyp rebuild`
170 error Exit status 1
171 error Failed at the canvas@1.3.5 install script 'node-gyp rebuild'.
171 error Make sure you have the latest version of node.js and npm installed.
171 error If you do, this is most likely a problem with the canvas package,
171 error not with npm itself.
171 error Tell the author that this fails on your system:
171 error     node-gyp rebuild
171 error You can get their info via:
171 error     npm owner ls canvas
171 error There is likely additional logging output above.
172 verbose exit [ 1, true ]

**Comment by oozywaters** [comment]
Same error here.

**Comment by Zeng83** [comment]
same here

**Comment by amitmotgi** [comment]
same here

**Comment by kellyjandrews** [comment]
+1

**Comment by LinusU** [comment]
Please try again with the 1.3.8.

Also, please mention OS and other relevant info
