### ISSUE TITLE
npm install failed in OSX 10.11.1 EI Capitain

### ISSUE THREAD

**Issue by licanbluesea** [Automattic/node-canvas#703]
I have ran 
```shell
 brew uninstall jpeg && brew install jpeg.
```
while I ran  
```shell
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/X11/lib/pkgconfig npm install canvas --save
```
 , but I got following error message:

 canvas@1.3.6 install /Users/xxx/Development/website/wwww/xxx/node_modules/canvas
 node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas.node
ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/Development/website/wwww/html/project/xfecodes/xoyo/website201512/node_modules/canvas
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/ject/xfecodes/xoyo/website201512/npm-debug.log

**Comment by leftstick** [comment]
Have you try following:

![snip20160115_1](https://cloud.githubusercontent.com/assets/1059956/12348266/a003280a-bba0-11e5-9247-09f247117a71.png)

**Comment by LinusU** [comment]
As @leftstick said, please try to run `xcode-select --install`. If that doesn't work, feel free to reopen the issue.
