### ISSUE TITLE
Benchmarks takes a majority of the time on travis

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#707]
The benchmarks currently takes a majority of the time on travis. It seems like the actual tests are done within the minute, but the build time is still 2-3 minutes because the benchmark is still running.

Surely it's not needed to run the benchmark on all versions of node?

Is there a way to tell travis to report the build as successful before the benchmark starts? postbuild script?

**Comment by kangax** [comment]
Do benchmarks actually influence test results (meaning that there's some threshold that shouldn't be crossed)? It seems unnecessary to include benchmarks in CI in the first place.

**Comment by zbjornson** [comment]
I had added them to CI but don't care if they're removed.

The only performance bug currently captured by benchmarks is this one: https://github.com/Automattic/node-canvas/issues/626.

There is no mechanism by which performance regressions are reported as test failures right now.

**Comment by LinusU** [comment]
Since I don't believe anyone is looking at them, and since it doesn't affect the test result, I say we remove them for now.

**Comment by kangax** [comment]
+1
