### ISSUE TITLE
toBuffer returns SlowBuffer

### ISSUE THREAD

**Issue by Vanuan** [Automattic/node-canvas#711]
It appears that canvas#toBuffer return SlowBuffer instead of Buffer.
While it has same interface, it's difficult to verify object's class.

**Comment by LinusU** [comment]
Two things. 1) This should be fixed here, but 2) you should always use `Buffer.isBuffer` to check if something is a buffer

**Comment by Vanuan** [comment]
Aha, didn't know about isBuffer. Thanks

**Comment by zbjornson** [comment]
I don't actually see how SlowBuffer is returned from that code. @Vanuan how are you seeing that? It's possible that's an implementation detail of how larger node Buffers are allocated.

**Comment by Vanuan** [comment]
> how are you seeing that?

    canvas.toBuffer().constructor.name

**Comment by zbjornson** [comment]
Roger, thanks! :)

**Comment by zbjornson** [comment]
I can't reproduce this (node 6 and canvas 2) with tiny or huge canvases, and I don't see any way in the code for this to be happening. Please comment if you have a way to reproduce it still. :)
