### ISSUE TITLE
OSX Installation fails: no attribute 'mkstemp'

### ISSUE THREAD

**Issue by mDomingues** [Automattic/node-canvas#714]
Hi guys,

I can't get this done, after hours of searching everywhere for this error. 
Before you ask, I got all dependencies installed and XCode updated.

Even cloning this repo and installing by it, I get the same error.

![image](https://cloud.githubusercontent.com/assets/11029958/12964504/67ebb556-d048-11e5-8be5-14f564171999.png)

![image](https://cloud.githubusercontent.com/assets/11029958/12964524/8ac6bdfa-d048-11e5-82a3-9abd9fae0641.png)

System info:

![image](https://cloud.githubusercontent.com/assets/11029958/12964541/9c628f44-d048-11e5-8061-f508a3144daf.png)

Thanks for your help

**Comment by LinusU** [comment]
Wow, this is an interesting one. Seems like your Python installation is broken. Could you try opening Python and typing something like this?

```py
import tempfile
tempfile.mkstemp
```

**Comment by mDomingues** [comment]
Yeah, something's wrong with python.

![image](https://cloud.githubusercontent.com/assets/11029958/12971952/a5ed108e-d098-11e5-9235-36db990e22a7.png)

**Comment by LinusU** [comment]
Cam you try running this in your python repl?

```py
import tempfile
tempfile.mkstemp
```
