### ISSUE TITLE
canvas how to reset?  it is overlap!

### ISSUE THREAD

**Issue by V-Tom** [Automattic/node-canvas#726]
here are my code on Node.js

```
const Canvas = require('canvas'),
  canvas = new Canvas(1000, 200),
  ctx = canvas.getContext('2d');
class App {
  constructor(length) {
    this.verifyCodeLength = length || 8;
    this._init();
  };

  _init() {
  };

  _getRandomCode() {
    var key = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPRSTUVWXYZ1234567890'.split('');
    var code = '', i, length = key.length;
    for (i = 0; i < this.verifyCodeLength; i++) {
      code += key[Math.round(Math.random() * (length - 1))];
    }
    return code;
  };

  _setCodeStyle(code) {
   ctx.font = '30px';
    ctx.rotate(.1);
    for (var i = 0; i < this.verifyCodeLength; i++) {
      ctx.fillText(code[i], 65 * i, 100);
    }
    var te = ctx.measureText(code);
    ctx.strokeStyle = 'rgba(0,0,0,0.5)';
    ctx.beginPath();
    ctx.lineTo(50, 102);
    ctx.lineTo(50 + te.width, 102);
    ctx.stroke();
  };

  getCodeBase64() {
    var code = this._getRandomCode();
    this._setCodeStyle(code);
    return {
      canvas: canvas,
      code: code
    };
  }
}
module.exports = App;
```

I use it to generate a verification code, and then return to the external call out on a canvas base64 and images overlap, how can I eliminate  the overlap portion?

`canvas.clear()`
 `ctx. clearRect()` 
both does not work.

I hope you can help me.
thanks.

**Comment by V-Tom** [comment]
![demo](https://cloud.githubusercontent.com/assets/8033489/13380603/44f67dcc-de82-11e5-9dab-310eccca3039.png)

**Comment by LinusU** [comment]
`ctx.clearRect(0, 0, canvas.width, canvas.height)`

**Comment by V-Tom** [comment]
ok,Thanks
my english it not very well.

And i also maybe find a bug in `lib/canvas.js`
line 233
`
      } else if ('number' === typeof a2) {
        opts = {quality: Math.min(0, Math.max(1, a2)) * 100};
      }
`
The opts always is `{quality:0}`
Also maybe i am wrong.
Thanks after all~

**Comment by zbjornson** [comment]
My mistake, min and max are switched there. PR coming soon. Thanks.

**Comment by LinusU** [comment]
@zbjornson Awesome :+1:

**Comment by V-Tom** [comment]
@zbjornson  Awesome :+1:
