### ISSUE TITLE
"out of memory" error when trying to load a PNG with a dubious gAMA chunk

### ISSUE THREAD

**Issue by papandreou** [Automattic/node-canvas#73]
I had some trouble loading a specific PNG, which other viewers were able to display just fine. The image's onerror handler fires with an "out of memory" error.

However pngcrush does provide a hint about what's wrong:

```
   Total length of data found in IDAT chunks    =      912
libpng warning: Ignoring gAMA chunk with gamma=0
```

With that chunk gone, node-canvas is happy again.

I put the original image here: http://gofish.dk/zero-gAMA.png

Of course it's the image that's broken, but I'm reporting it anyway because "out of memory" is a weird symptom :)

**Comment by zbjornson** [comment]
This works with Cairo 1.16.0. 🎉
