### ISSUE TITLE
Can't install in CentOs 6.3 by you wiki, and miss the same problom.

### ISSUE THREAD

**Issue by eidonjoe** [Automattic/node-canvas#731]
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error:`gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Linux 2.6.32-358.6.2.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/tmp/canvas/node_modules/canvas
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas" "--save"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/tmp/canvas/npm-debug.log

**Comment by LinusU** [comment]
> Package cairo was not found in the pkg-config search path.

Is cairo-dev installed?

**Comment by petermikitsh** [comment]
@LinusU To install on CentOS 7.x, I followed the instructions for Fedora, but also needed the `gcc-c++` package, e.g., `sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel gcc-c++`

Then `npm i -g canvas@1.6.2` worked for me. It might be nice to include that in the docs. However, it was pretty easy to debug:

```
> canvas@1.6.2 install /usr/lib/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
make: g++: Command not found
```

**Comment by zbjornson** [comment]
Thanks, I've updated the [wiki](https://github.com/Automattic/node-canvas/wiki/Installation---Fedora-(and-other-RPM-based-distributions)) and tested 2.x on CentOS 7.
