### ISSUE TITLE
JPEG streams seem not to be really synchronous 

### ISSUE THREAD

**Issue by Etsitpab** [Automattic/node-canvas#732]
When I try to save many image, the files are only written at the end of the script.
@LinusU Here is the shortest script I could write to reproduce the problem I observed :

```
#!/usr/bin/env node

var fs = require('fs'),
    Canvas = require('canvas'),
    Image = Canvas.Image;

(function () {
    "use strict";
    var out, stream;
    out = fs.createWriteStream("test1.jpg");
    stream = new Canvas(500, 500).syncJPEGStream();
    stream.on('data', function (chunk) {
        console.log("Write chunk for", "test1.jpg")
        out.write(chunk);
    });
    stream.on('end', function () {
        console.log("End stream for", "test1.jpg")
    });
    out = fs.createWriteStream("test2.jpg");
    stream = new Canvas(500, 500).syncJPEGStream();
    stream.on('data', function (chunk) {
        console.log("Write chunk for", "test2.jpg")
        out.write(chunk);
    });
    stream.on('end', function () {
        console.log("End stream for", "test2.jpg")
    });
})();
```

And here, the corresponding output:

```
Write chunk for test1.jpg
Write chunk for test2.jpg
Write chunk for test2.jpg
End stream for test2.jpg
Write chunk for test1.jpg
End stream for test1.jpg
```

Where I was expecting something like that:

```
Write chunk for test1.jpg
Write chunk for test1.jpg
End stream for test1.jpg
Write chunk for test2.jpg
Write chunk for test2.jpg
End stream for test2.jpg
```

I'm very interested to know whether you are able to reproduce this behavioror have any hint on what i could do wrong. Thank you for your time and for the great work you're doing, this module is really cool !

**Comment by zbjornson** [comment]
I've been poking at this area of code today and think you're right that it's not technically sync. The c++ code pushes chunks of data, and does so whenever it wants to. One of the original creators might be able to explain why it's considered sync?

**Comment by zbjornson** [comment]
This is as-designed, and the `sync___stream` methods were fully removed in 2.x.
