### ISSUE TITLE
OSX install error

### ISSUE THREAD

**Issue by scanlonjts** [Automattic/node-canvas#737]
npm install
npm WARN engine palette@0.0.1: wanted: {"node":"0.6.x"} (current: {"node":"4.4.0","npm":"2.14.20"})
 
> canvas@1.3.12 install /Users/xxx/Documents/git/photosearch/indexer/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jscanlon/Documents/git/photosearch/indexer/node_modules/canvas
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jscanlon/Documents/git/photosearch/indexer/npm-debug.log
xxx ~/Documents/git/photosearch/indexer$ node-gyp rebuild

**Comment by zbjornson** [comment]
Looks like you're installing canvas as a dependency of palette? Palette's [package.json](https://github.com/tj/palette) specs a very old canvas version. Try setting that to a recent version.

**Comment by LinusU** [comment]
You need pkg-config installed, from the readme:

```sh
brew install pkg-config cairo libpng jpeg giflib
```

**Comment by vicary** [comment]
As of 2022 August, Apple M1 needs `pango` for `pangocairo`.

```diff
brew install pkg-config cairo libpng jpeg giflib
```

**Comment by vicary** [comment]
As of 2022 August, Apple M1 needs `pango` for `pangocairo`.

```diff
- brew install pkg-config cairo libpng jpeg giflib
+ brew install pkg-config cairo libpng jpeg giflib pango
```
