### ISSUE TITLE
Installation on Heroku needs updating

### ISSUE THREAD

**Issue by chico** [Automattic/node-canvas#741]
I followed https://github.com/Automattic/node-canvas/wiki/Installation-on-Heroku but it's now out of date. Heroku now supports multiple buildpacks out of the box.

The simplest way to get node-canvas working is to add the cairo buildpack using the following heroku command:

```
heroku buildpacks:add --index 1 https://github.com/mojodna/heroku-buildpack-cairo.git
```

**Comment by mini-eggs** [comment]
Thanks you @chico

**Comment by mapmeld** [comment]
note that *this* workaround is no longer working, as it hasn't been updated for heroku-16 stack, and cedar-14 is no longer available:

https://github.com/mojodna/heroku-buildpack-cairo/issues/16

**Comment by rista404** [comment]
I just tested this with version `2.0.0-alpha.12`, and got it working with this buildpack: https://github.com/rista404/heroku-buildpack-cairo

Just add it before nodejs buildpack and it should be working.

**Comment by eko24ive** [comment]
@rista404 I was able to get `node-canvas` running on Heroku without any issues (see: https://github.com/Automattic/node-canvas/issues/843#issuecomment-386801470)
Although it looks like you are using `cedar-14` stack, while I'm using `heroku-16` - maybe that's the difference

**Comment by zbjornson** [comment]
In addition to the other solutions commented above... I just successfully installed canvas 2.0.0-alpha.12 and 1.6.11 on the vanilla heroku-16 stack. Both just worked thanks to prebuilds. If anyone has a need to make a from-source build work, I can look into it.
