### ISSUE TITLE
I have install everything but still can't install canvas

### ISSUE THREAD

**Issue by elvischan** [Automattic/node-canvas#745]
![image](https://cloud.githubusercontent.com/assets/12570430/14166515/c76755b0-f746-11e5-88fe-8afe3223de45.png)
what's the problem with that？

**Comment by LinusU** [comment]
Could you try running `xcode-select --install`

**Comment by freetomik** [comment]
I have same problem on Linux Mint 17.

**Comment by freetomik** [comment]
I was installing node-canvas as a dependency of another project, and I haven't read readme before.
Solved by installing dependencies:
```
sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
```

**Comment by ronnerock** [comment]
The process I did, in case it's helpful to anyone, is below:

1) uninstall all instances of cocopods (just to be safe and keep things clean) sudo gem uninstall cocoapods
2) sudo gem install -n /usr/local/bin cocoapods
3) sudo chmod +rx /usr/local/bin/
