### ISSUE TITLE
Can this be use to combine two images?

### ISSUE THREAD

**Issue by astewes** [Automattic/node-canvas#748]
I'm looking to add functionality to a splash page where:

1) User uploads a profile picture
2) A second image - an preset image overlay that will always be the same - is then placed on top of the uploaded profile pic and saved as one image
3) User can then share the final image on Facebook, Twitter, and Instagram (this step isn't related to my question, but I included it to provide context)

Is this possible with node-canvas?

**Comment by LinusU** [comment]
Yes, that's absolutely possible. Search the web for canvas tutorials, you should be able to find something that can help you...
