### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by badhaloninja** [Automattic/node-canvas#752]
I need help installing canvas on **win10** I've **installed everything** _**else**_ but it just wont "rebuild"
:sob:
![No Image? Click meh for CMD window!](http://puu.sh/oeTaP/8ad357564c.PNG)

**Comment by zbjornson** [comment]
It looks like you're trying to `node-gyp rebuild` in a directory that doesn't contain canvas. Do you mean to be in a different directory?

**Comment by badhaloninja** [comment]
no i followed the instructions exactly it just wont work

**Comment by zbjornson** [comment]
What does `ls` (or `dir`) output?
