### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by astewes** [Automattic/node-canvas#753]
Brand-spanking-new to node-canvas, and I'm getting an "**Uncaught ReferenceError: require is not defined**" in my console.

What I've done:

1. installed node-canvas (v3.8.6) and its dependencies on OS X El Capitan following these instructions: https://github.com/Automattic/node-canvas/wiki/Installation---OSX -- it's worth noting that I didn't notice any errors during the installation
2. copied the example code into my JS to see what would happen:

        var Canvas = require('canvas'),
            Image = canvas.Image,
            canvas = new Canvas(200, 200),
            ctx = canvas.getContext('2d');

        ctx.font = '30px Impact';
        ctx.rotate(.1);
        ctx.fillText("Awesome!", 50, 100);

        var te = ctx.measureText('Awesome!');
        ctx.strokeStyle = 'rgba(0,0,0,0.5)';
        ctx.beginPath();
        ctx.lineTo(50, 102);
        ctx.lineTo(50 + te.width, 102);
        ctx.stroke();

        console.log('<img src="' + canvas.toDataURL() + '" />');

Am I missing a step or a piece that's key to understanding how node-canvas works?

**Comment by LinusU** [comment]
> into my JS

This is for usage with [Node.js](https://nodejs.org/en/), is that what you are using?

**Comment by astewes** [comment]
Argh, I'm using it on my WordPress site, which is integrated with npm. Is there any way to accomplish this? If not with node-canvas, any other packages you're aware of?

**Comment by LinusU** [comment]
If your doing this in the web browser, you already have canvas. It's part of html5
