### ISSUE TITLE
 canvas@1.3.12 install failed  (script 'node-gyp rebuild')

### ISSUE THREAD

**Issue by kwnovi** [Automattic/node-canvas#755]
Trying to install node-canvas through `npm install canvas --save` after installing the dependencies (`brew install pkg-config cairo libpng jpeg giflib`) but getting an error from `node-gyp rebuild`

```
209 error Darwin 14.0.0
210 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
211 error node v4.4.1
212 error npm  v3.8.6
213 error code ELIFECYCLE
214 error canvas@1.3.12 install: `node-gyp rebuild`
214 error Exit status 1
215 error Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
215 error Make sure you have the latest version of node.js and npm installed.
215 error If you do, this is most likely a problem with the canvas package,
215 error not with npm itself.
215 error Tell the author that this fails on your system:
215 error     node-gyp rebuild
215 error You can get information on how to open an issue for this project with:
215 error     npm bugs canvas
215 error Or if that isn't available, you can get their info via:
215 error     npm owner ls canvas
215 error There is likely additional logging output above.
216 verbose exit [ 1, true ]

```

When running `npm install canvas@1.3.12`

```
`canvas@1.3.12 install /Users/kwnovi/Desktop/toska/test/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
`
```

Edit : I tried 

```
brew uninstall jpeg && brew install jpeg
brew uninstall cairo
xcode-select --install
brew install cairo

PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/X11/lib/pkgconfig sudo npm install canvas

```

But got an different error : 

```
canvas@1.3.12 install /Users/kwnovi/Desktop/toska/test/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kwnovi/Desktop/toska/test/node_modules/canvas
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
```

**Comment by qwemaze** [comment]
same problem here's [npm-debug.log](http://pastebin.com/NfygCpT0)

**Comment by jeremypeters** [comment]
Yep, same issue here as well.

**Comment by jeremypeters** [comment]
Running `xcode-select --install` fixed the issue, as suggested [here](https://github.com/Automattic/node-canvas/issues/722) :)

**Comment by sukhmeet2390** [comment]
@jeremypeters for me it didn't

`xcode-select --install`
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

` npm install canvas@latest

> canvas@1.3.14 install /Users/sukhi/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sukhi/node_modules/canvas
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/Users/sukhi
└── node-gyp@3.3.1

npm WARN enoent ENOENT: no such file or directory, open '/Users/sukhi/package.json'
npm WARN sukhi No description
npm WARN sukhi No repository field.
npm WARN sukhi No README data
npm WARN sukhi No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas@latest"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sukhi/npm-debug.log `

**Comment by LinusU** [comment]
@sukhmeet2390 read the error message, you don't have pkg-confit installed. Please follow the installation instructions in the readme...

**Comment by zhuyingda** [comment]
I had the same problem, I fixed the problem by brew install some packages such as cairo. 
Now I can use node-canvas and it runs well.

**Comment by laispace** [comment]
@jeremypeters It works, thank you!

**Comment by kurisubrooks** [comment]
Just run into this error on Ubuntu 16.04, never had it before. All dependencies are met, but I still get this error with no stack trace. 

NPM Log
```
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kurisu/sherlock/node_modules/canvas
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "canvas"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
```

**Comment by kurisubrooks** [comment]
Found this in the resulting `npm-debug.log`

```
311 silly lifecycle canvas@1.4.0~install: Args: [ '-c', 'node-gyp rebuild' ]
312 silly lifecycle canvas@1.4.0~install: Returned: code: 1  signal: null
313 info lifecycle canvas@1.4.0~install: Failed to exec install script
```

Permissions error? Does it need sudo?

**Comment by goliatone** [comment]
Similar issue:

```
SOLINK_MODULE(target) Release/canvas-postbuild.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
```

Had cairo, jpge, pkg-config, etc already installed.

Solved with following instructions:
```
brew uninstall jpeg && brew install jpeg
brew uninstall cairo
xcode-select --install
brew install cairo
```

**Comment by kopickik** [comment]
`brew upgrade cairo`
