### ISSUE TITLE
Node.js v6: `v8::ObjectTemplate::Set() with non-primitive values is deprecated`

### ISSUE THREAD

**Issue by mathiasbynens** [Automattic/node-canvas#758]
```
$ node --version
v6.0.0

$ node -e 'require("canvas")'
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x4d535bc9fa9 <JS Object>#0#
    [stack trace omitted]
=====================


==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: Canvas::Initialize(v8::Local<v8::Object>)
 3: init(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 8: 0x187971b0961b
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

[super-long list of JS + C stack traces omitted]
```

Ref. https://github.com/nodejs/node/issues/6216 and https://github.com/nodejs/node/pull/6228 — starting with Node.js v6, setting non-primitive values on `FunctionTemplate` and `ObjectTemplate` instances is discouraged (and triggers a stack trace). v7 will downright disallow it.

**Comment by mathiasbynens** [comment]
cc @bnoordhuis

**Comment by chearon** [comment]
we just have to update the minimum version of NAN, it was fixed in 2.3.1: https://github.com/nodejs/nan/commit/a90951e9ea70fa1b3836af4b925322919159100e

**Comment by mathiasbynens** [comment]
Pull request: https://github.com/Automattic/node-canvas/pull/759

**Comment by LinusU** [comment]
Released as `1.3.13`

**Comment by jitendravyas** [comment]
i'm also getting this error

```
➜  posthtml gulp posthtml
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x12d40f0c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x686806f33a4] (this=0x11b21f1ec031 <an Object with deprecated map 0x177080a17be1>#1#,module=0x1132a1bb9 <a Module with map 0x177080a181b9>#2#,filename=0x1132a1b91 <String[97]: /Users/jitendravyas/my-projects/posthtml/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    2: load [module.js:~447] [pc=0x686806f9776] (this=0x1132a1bb9 <a Module with map 0x177080a181b9>#2#,filename=0x1132a1b91 <String[97]: /Users/jitendravyas/my-projects/posthtml/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x6868053899d] (this=0x12d40f004189 <undefined>,module=0x1132a1bb9 <a Module with map 0x177080a181b9>#2#,filename=0x1132a1b91 <String[97]: /Users/jitendravyas/my-projects/posthtml/node_modules/node-sass/vendor/darwin-x64-48/binding.node>)
    4: _load [module.js:407] [pc=0x686805345e2] (this=0x11b21f1ebfe9 <JS Function Module (SharedFunctionInfo 0x11b21f1286b9)>#3#,request=0x1132a08d9 <String[97]: /Users/jitendravyas/my-projects/posthtml/node_modules/node-sass/vendor/darwin-x64-48/binding.node>,parent=0x113288c79 <a Module with map 0x177080a181b9>#4#,isMain=0x12d40f004299 <false>)
ion require (SharedFunctionInfo 0x11b21f1584c1)>#6#,module=0x113288c79 <a Module with map 0x177080a181b9>#4#,__filename=0x113288c51 <String[76]: /Users/jitendravyas/my-projects/posthtml/node_modules/node-sass/lib/index.js>,__dirname=0x11328f981 <String[67]: /Users/jitendravyas/my-projects/posthtml/node_modules/node-sass/lib>)
80725200] (this=0x11321ded9 <an Object with map 0x37de61007b71>#9#,exports=0x11321ded9 <an Object with map 0x37de61007b71>#9#,require=0x113221799 <JS Function require (SharedFunctionInfo 0x11b21f1584c1)>#10#,module=0x11321de89 <a Module with map 0x177080a181b9>#8#,__filename=0x11321de61 <String[72]: /Users/jitendravyas/my-projects/posthtml/node_modules/gulp-sass/index.js>,__dirname=0x113221731 <String[63]: /Users/jitendravyas/my-projects/posthtml/node_modules/gulp-sass>)
79 <String[9]: gulp-sass>)
dule with map 0x177080a181b9>#12#,filename=0x113008b29 <String[52]: /Users/jitendravyas/my-projects/posthtml/gulpfile.js>)
x2c77ca50e019 <JS Array[3]>#22#,execute=0x26427f1e1e1 <JS BoundFunction bound  (BoundTargetFunction 0x26427f1e161)>#23#)

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: SassTypes::Number::initPrototype(v8::Local<v8::FunctionTemplate>)
 3: SassTypes::SassValueWrapper<SassTypes::Number>::get_constructor_template()
 4: SassTypes::SassValueWrapper<SassTypes::Number>::get_constructor()
 5: SassTypes::Factory::initExports(v8::Local<v8::Object>)
 6: RegisterModule(v8::Local<v8::Object>)
 7: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 8: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 9: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
10: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
11: 0x6868040961b
[1]    31169 segmentation fault  gulp posthtml
```

**Comment by LinusU** [comment]
@jitendravyas Have you made sure that your version of canvas is updated to 1.3.13?

**Comment by richardgong1987** [comment]
i am also getting this error



(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0xc9537cc9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x1b22fec36744] (this=0x39e06f6dc9b1 <an Object with map 0x15de13c17e49>#1#,module=0x29d6e0b59321 <a Module with map 0x15de13c18421>#2#,filename=0x29d6e0b592f9 <String[115]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:~447] [pc=0x1b22fec3ccd6] (this=0x29d6e0b59321 <a Module with map 0x15de13c18421>#2#,filename=0x29d6e0b592f9 <String[115]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/fsevents/build/Release/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1b22fe838c7d] (this=0xc9537c04189 <undefined>,module=0x29d6e0b59321 <a Module with map 0x15de13c18421>#2#,filename=0x29d6e0b592f9 <String[115]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/fsevents/build/Release/fse.node>)
name=0x29d6e0b54c39 <String[104]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/fsevents/fsevents.js>,__dirname=0x29d6e0b57501 <String[92]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/fsevents>)
sers/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/chokidar/lib/fsevents-handler.js:7] [pc=0x1b22fee88c52] (this=0x29d6e0b4cb29 <an Object with map 0x216cc6b07ac1>#9#,exports=0x29d6e0b4cb29 <an Object with map 0x216cc6b07ac1>#9#,require=0x29d6e0b4fb31 <JS Function require (SharedFunctionInfo 0x39e06f653c41)>#10#,module=0x29d6e0b4cad9 <a Module with map 0x15de13c18421>#8#,__filename=0x29d6e0b4cab1 <String[116]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/chokidar/lib/fsevents-handler.js>,__dirname=0x29d6e0b4fac9 <String[96]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/node_modules/chokidar/lib>)
9e06f622dd1)>#3#,request=0x49126b979b1 <String[18]: ./fsevents-handler>,parent=0x29d6e0afaa49 <a Module with map 0x15de13c18421>#12#,isMain=0xc9537c04299 <false>)
/chokidar/lib/index.js>)
String[90]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/src/node-loaders.js>)
defined' || window !== this) {\n    module.exports = require('./node-loaders');\n}\nelse {\n    module.exports = require('./web-loaders');\n}\n>,filename=0x29d6e0aeccc9 <String[85]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/src/loaders.js>)
0x15de13c18421>#23#,__filename=0x29d6e0a793c9 <String[89]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/src/environment.js>,__dirname=0x29d6e0a7eae1 <String[74]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/src>)
ace/alphabets/node_modules/nunjucks/index.js:3] [pc=0x1b22fee67cc1] (this=0x29d6e0a711f1 <an Object with map 0x216cc6b07ac1>#28#,exports=0x29d6e0a711f1 <an Object with map 0x216cc6b07ac1>#28#,require=0x29d6e0a72939 <JS Function require (SharedFunctionInfo 0x39e06f653c41)>#29#,module=0x29d6e0a711a1 <a Module with map 0x15de13c18421>#27#,__filename=0x29d6e0a71179 <String[79]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks/index.js>,__dirname=0x29d6e0a728d1 <String[70]: /Users/richardgong/Documents/workspace/alphabets/node_modules/nunjucks>)
6526a1 <String[8]: nunjucks>)
runMain [module.js:575] [pc=0x1b22fe83438a] (this=0x39e06f6dc969 <JS Function Module (SharedFunctionInfo 0x39e06f622dd1)>#3#)

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x1b22fe70961b
 8: 0x1b22fec36744

**Comment by LinusU** [comment]
@richardgong1987 Have you made sure that your version of canvas is updated to 1.3.13?

**Comment by seanlarge** [comment]
I am also running into this error:

`node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x3cf280bc9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x2dfcb132de24] (this=0x32e1901def41 <an Object with map 0x17e20ab17be1>#1#,module=0x10f52e781 <a Module with map 0x17e20ab181b9>#2#,filename=0x10f52e759 <String[101]: /Users/sea2574595/dev/Haystack/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node>)
    2: load [module.js:456] [pc=0x2dfcb1138e72] (this=0x10f52e781 <a Module with map 0x17e20ab181b9>#2#,filename=0x10f52e759 <String[101]: /Users/sea2574595/dev/Haystack/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x2dfcb113899d] (this=0x3cf280b04189 <undefined>,module=0x10f52e781 <a Module with map 0x17e20ab181b9>#2#,filename=0x10f52e759 <String[101]: /Users/sea2574595/dev/Haystack/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node>)
    4: _load [module.js:407] [pc=0x2dfcb11345e2] (this=0x32e1901deef9 <JS Function Module (SharedFunctionInfo 0x32e1901286b9)>#3#,request=0x10f5279a1 <String[101]: /Users/sea2574595/dev/Haystack/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node>,parent=0x10f323589 <a Module with map 0x17e20ab181b9>#4#,isMain=0x3cf280b04299 <false>)
89 <JS Function require (SharedFunctionInfo 0x32e190158b79)>#6#,module=0x10f323589 <a Module with map 0x17e20ab181b9>#4#,__filename=0x10f323551 <String[66]: /Users/sea2574595/dev/Haystack/node_modules/sqlite3/lib/sqlite3.js>,__dirname=0x10f327421 <String[55]: /Users/sea2574595/dev/Haystack/node_modules/sqlite3/lib>)
ject>#9#,dialect=0x10f3195d9 <JS Object>#10#,sequelize=0x10f228f49 <JS Object>#11#)
modelName]) {\n        db[modelName].associate(db);\n    }\n});\n\nsequelize.sync();\n\ndb.sequelize = sequelize;\ndb.Sequelize = Sequelize;\n\nmodule.exports = db;>,filename=0x26d6ec17a031 <String[46]: /Users/sea2574595/dev/Haystack/models/index.js>)
outes>)
42506] (this=0x3cf280b04189 <undefined>,path=0x32e19015bde1 <String[14]: ./routes/users>)
7f29 <String[6]: ../app>)
 <null>,process=0x3cf280be5b91 <a process with map 0x17e20ab5f2d9>#27#)

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: node_sqlite3::Database::Init(v8::Local<v8::Object>)
 3: (anonymous namespace)::RegisterModule(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 8: 0x2dfcb100961b
Segmentation fault: 11`

**Comment by LinusU** [comment]
@seanlarge Have you made sure that your version of canvas is updated to 1.3.13?

**Comment by seanlarge** [comment]
@LinusU  yes, it is updated. but after googling further I found that this issue was related to sqlit3 and nodev6 so we can disregard my comment. 

see [here](https://github.com/mapbox/node-sqlite3/issues/634#issuecomment-219261269)
