### ISSUE TITLE
.prototype segfaults

### ISSUE THREAD

**Issue by substack** [Automattic/node-canvas#76]
I like to inspect prototype attributes to get a feel for what methods objects support, but this causes segfaults on most objects, like this one:

```
$ node
> require('canvas').prototype

rlwrap: warning: node killed by signal 11 - rlwrap will now kill itself with the same signal
Segmentation fault
```

This is on node v0.2.5 and it seems that most everything else works.

**Comment by LinusU** [comment]
This is still a problem with version `1.2.3` on node `0.12.4`.

**Comment by LinusU** [comment]
This is still a problem with version `1.3.10` on node `5.5.0`.

**Comment by basvanmeurs** [comment]
This is still a problem in Node 6.8 and 7.2.

**Comment by zbjornson** [comment]
@basvanmeurs #808 (not merged) hopefully fixes this but the VS Code debugger seems to be doing something unique that exacerbates the problem. What's your environment like - any debuggers?
