### ISSUE TITLE
Installation with Etherdraw fails

### ISSUE THREAD

**Issue by rugk** [Automattic/node-canvas#764]
I am trying to install Etherdraw on bananian and canvas fails to build.

`Failed at the canvas@1.2.1 install script 'node-gyp rebuild'.`
All details: https://github.com/JohnMcLear/draw/issues/233

Probably related to: 
https://github.com/Automattic/node-canvas/issues/755

**Comment by rugk** [comment]
The new jpeg package is installed:

```
Package libjpeg8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg62-turbo-dev

E: Package 'libjpeg8-dev' has no installation candidate
```

And this package is already installed: `libjpeg62-turbo-dev is already the newest version`

**Comment by JohnMcLear** [comment]
Fixed by targeting latest canvas.

**Comment by LinusU** [comment]
Awesome 🙌
