### ISSUE TITLE
Pango Crashing

### ISSUE THREAD

**Issue by davidlimjh** [Automattic/node-canvas#767]
We've been using the latest version of node-canvas that supports custom fonts on windows. Not sure whats up but we occasionally we run into crashes such as these: 

```
(node.exe:1300): Pango-CRITICAL **: pango_win32_font_map_get_font_cache: assertion `font_map != NULL' failed
**
Pango:ERROR:pangowin32.c:831:pango_win32_font_finalize: assertion failed: (win32font->fontmap != NULL)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.```

**Comment by chearon** [comment]
That's interesting... it looks more like a problem inside Pango than in canvas itself, since it's crashing in pangowin32.c and I've not seen it do that on other platforms.

**Comment by davidlimjh** [comment]
I'll leave a bug report on their Bugzilla page in that case.
