### ISSUE TITLE
Cent OS node-gyp failed

### ISSUE THREAD

**Issue by spAnser** [Automattic/node-canvas#768]
OK So after reading the log myself I found out that the nan dependency was giving off a warning saying I had to use a C++11 Compiler.

I used [this guide](http://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/)

I already had the required installed items they just weren't enabled. This should probably be part of the wiki on how to install.

**Comment by rokyed** [comment]
try installing the required libs https://github.com/Automattic/node-canvas#installation

**Comment by spAnser** [comment]
I think you missed what I said. I succeded in installing just saying the method outline on the wiki is not perfect.

**Comment by rokyed** [comment]
sorry, my bad and you are definitely right.
