### ISSUE TITLE
Can't install on OS X

### ISSUE THREAD

**Issue by ArmyArmyCz** [Automattic/node-canvas#771]
Hello,
I'm trying to use Pho devstack for my project structure, when i generate the structure everything goes fine, then it fails during "npm install" when building canvas.

[canvas-err.txt](https://github.com/Automattic/node-canvas/files/284372/canvas-err.txt) terminal output

I've tried several thing, I have installed the xcode command line tools, installed/reinstalled missing packages but still no results.

OS: OS X El Capitan v10.11.5
Node: v6.2.0
Npm: 3.8.9

**Comment by tjwebb** [comment]
Also cannot install on OSX with node 6.2

**Comment by tjwebb** [comment]
I got it to build properly if I go all the way back to the node 0.12 series, but I need to use node > 4

**Comment by zazk** [comment]
Install without problems.
OS: OS X El Capitan v10.11.3
Node: v6.2.2
Npm: 3.9.6
