### ISSUE TITLE
Segfault in getImageData when using SVG canvas

### ISSUE THREAD

**Issue by PAFsec** [Automattic/node-canvas#772]
Hello,

I was playing with the SVG canvas, and I got a segfault:

```
var Canvas = require('canvas');`
var c = new Canvas(600, 600, 'svg');`
var ctx = c.getContext("2d");`
var data = ctx.getImageData(0, 0, 600, 600);`
```

> Program received signal SIGSEGV, Segmentation fault.
> 
> 0x00007ffff41d34af in Context2d::GetImageData(Nan::FunctionCallbackInfov8::Value const&) () from /node_modules/canvas/build/Release/canvas.node

I am using:

|--canvas@1.3.15
   |--nan@2.3.3

Thanks

**Comment by PAFsec** [comment]
Soooo,

After digging a little bit into that bug, I found out that the pointer that points to the canvas data (after using the function **canvas->data()** is the null pointer, and no verification is done against it : 

```
CanvasRenderingContext2d.cc#L736     int srcStride = canvas->stride();
CanvasRenderingContext2d.cc#L737     int dstStride = sw * 4;
CanvasRenderingContext2d.cc#L739     uint8_t *src = canvas->data();
...
CanvasRenderingContext2d.cc#L757            uint32_t *row = (uint32_t *)(src + srcStride * (y + sy));
...
CanvasRenderingContext2d.cc#L769            uint32_t *pixel = row + x + sx;
CanvasRenderingContext2d.cc#L770            uint8_t a = *pixel >> 24;
```

When dereferencing the variable _pixel_ that holds a pointer on a specific pixel that is retrieved by manipulating the pointer of the _row_ (that contains a pointer null):
`CanvasRenderingContext2d.cc#L757            uint32_t *row = (uint32_t *)(src + srcStride * (y + sy));`


It will obviously trigger a segfault, as the null pointer will be derefenced: 
`CanvasRenderingContext2d.cc#L770            uint8_t a = *pixel >> 24;`


Maybe **getImageData** should not be used in 'SVG' mode? If so, that could be added to the documentation or handled programmaticaly.

Thanks

**Comment by LinusU** [comment]
Thanks for your extensive research, I'll try to have a look at it soon to see how we can fix this

**Comment by cammanderson** [comment]
Just checking to see if this issue has been resolved?

**Comment by PAFsec** [comment]
Hi,

I can confirme that this issue has not been resolved yet.
Any plan to do it in the (near) future ?

Regards,

**Comment by zbjornson** [comment]
We need to fix the segfault, but because SVG is not a raster format, I think the only fixes here are to either (a) make `getImageData` a no-op or (b) rasterize the SVG canvas. Likewise, `putImageData` I think has to be a no-op.

**Comment by zbjornson** [comment]
As of 2.9.1 this will throw an error instead of segfault.
