### ISSUE TITLE
can not install on mac

### ISSUE THREAD

**Issue by jinhuang3115** [Automattic/node-canvas#779]
error output

> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
In file included from ../src/JPEGStream.h:10:
In file included from /usr/local/include/jpeglib.h:27:
/usr/local/include/jmorecfg.h:263:27: error: expected identifier
typedef enum { FLASE = 0, TRUE = 1 } boolean;
                          ^
/usr/include/mach/boolean.h:81:14: note: expanded from macro 'TRUE'
# define TRUE    1

```
            ^
```

In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:47:10: error: cannot initialize return object of type 'boolean' with an rvalue of type 'bool'
  return true;
         ^~~~
../src/JPEGStream.h:118:3: error: no matching function for call to 'jpeg_set_quality'
  jpeg_set_quality(&cinfo, quality, (quality<25)?0:1);
  ^~~~~~~~~~~~~~~~
/usr/local/include/jpeglib.h:984:14: note: candidate function not viable: no known conversion from 'int' to 'boolean' for 3rd argument
EXTERN(void) jpeg_set_quality JPP((j_compress_ptr cinfo, int quality,
             ^
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:121:3: error: no matching function for call to 'jpeg_start_compress'
  jpeg_start_compress(&cinfo, TRUE);
  ^~~~~~~~~~~~~~~~~~~
/usr/local/include/jpeglib.h:1003:14: note: candidate function not viable: no known conversion from 'int' to 'boolean' for 2nd argument
EXTERN(void) jpeg_start_compress JPP((j_compress_ptr cinfo,
             ^
4 errors generated.
make: **\* [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jin/webstorm-project/scoreweb-node/node_modules/canvas
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPACKAGEJSON scoreweb-node@1.0.0 No description
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas@latest"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.16 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

**Comment by rereed92** [comment]
I have the same issue

**Comment by developeron29** [comment]
+1

**Comment by LinusU** [comment]
@developeron29 you need to install pkg-config, have you followed the instructions in the readme?

**Comment by developeron29** [comment]
@LinusU Thanks!
But After doing brew install and rerunning npm install canvas, I'm getting the following error:
```
> canvas@1.3.16 install /usr/local/lib/node_modules/canvas
> node-gyp rebuild

SOLINK_MODULE(target) Release/canvas-postbuild.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
```

**Comment by LinusU** [comment]
@developeron29 can you try it with the latest version of canvas? 1.4.0

**Comment by developeron29** [comment]
Getting this error

> `
npm ERR! No compatible version found: canvas@1.4.0
npm ERR! Valid install targets:
npm ERR! 1.3.16, 1.3.15, 1.3.14, 1.3.13, 1.3.12, 1.3.11, 1.3.10, 1.3.9, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.11, 1.2.10, 1.2.9, 1.2.8, 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.13.1, 0.13.0, 0.12.1, 0.12.0, 0.11.3, 0.11.2, 0.11.1, 0.11.0, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.0, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.0, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.0, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR! 
`
