### ISSUE TITLE
Please make custom fonts work

### ISSUE THREAD

**Issue by jingsam** [Automattic/node-canvas#783]
I have waste two days to trying get custom fonts work. The font api is not documented. I can just find some clues in `example/font.js`. Ironically, even this example is not working. After some searching, it seems that the example will not work with pango support.

I am very depressed now. So please get it works and saving the precious time of people's life!

**Comment by yy1107** [comment]
/ font.js

**Comment by LinusU** [comment]
#715 would probably interest you. You can also try building without pango, that should work...

> So please get it works and saving the precious time of people's life!

No one is getting paid to work on canvas and we are all donating our precious time to making it work at all. Feel free to fix this yourself and send us a pull request...

**Comment by chearon** [comment]
Closed via #715
