### ISSUE TITLE
getImageData not working for loaded image

### ISSUE THREAD

**Issue by badjano** [Automattic/node-canvas#787]
var Canvas = require('canvas')
var Image = Canvas.Image;
var fs = require('fs');

fs.readFile(__dirname + '/img/image.png', function(err, data){
  if (err) throw err;
  var img = new Image();
  img.onload = function(){
    var canvas = new Canvas(img.width, img.height);
    var ctx = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0, img.width, img.height);
    var imageData = ctx.getImageData();
  }
  img.src = data;
});

// LOG BELOW

var imageData = ctx.getImageData();
                    ^

Error: IndexSizeError: The source width is 0.
at Error (native)
at img.onload (/MyProject/test.js:12:25)
at Image.src (/MyProject/node_modules/canvas/lib/image.js:30:17)
at /MyProject/index.js:40:11
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

**Comment by zbjornson** [comment]
`getImageData` takes four parameters: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData. You probably want `getImageData(0, 0, img.width, img.height)`.

**Comment by badjano** [comment]
I'm sorry, thank you!
