### ISSUE TITLE
can not install on mac(fatal error: 'jpeglib.h' file not found)

### ISSUE THREAD

**Issue by rainer800hao** [Automattic/node-canvas#789]
error msg:

> canvas@1.3.16 install /Users/rainer800/SinaWork/#Lab/phantomjs/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rainer800/SinaWork/#Lab/phantomjs/node_modules/canvas
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas@1.3.16"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.16 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rainer800/SinaWork/#Lab/phantomjs/npm-debug.log

**Comment by LinusU** [comment]
Have you followed the instructions at the top of the readme?

```sh
xcode-select --install
brew install pkg-config cairo libpng jpeg giflib
```

Feel free to reopen if problems persists...

**Comment by chearon** [comment]
@LinusU i bet we could save days and days of your time if there was a good way to distribute recompiled binaries

**Comment by LinusU** [comment]
Yes! I would love to get that going :)

**Comment by zbjornson** [comment]
Meanwhile, might be worth while to make an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) that says something like "before submitting an issue, have you read the installation guide? -link-"

**Comment by LinusU** [comment]
Great idea! Pull requests welcome :)

**Comment by rainer800hao** [comment]
@LinusU,  I had installed dependencies successfully.

And, try to install xCode command line tools.

➜  phantomjs xcode-select --install
xcode-select: note: install requested for command line developer tools
➜  phantomjs brew install pkg-config cairo libpng jpeg giflib
Warning: pkg-config-0.29.1 already installed
Warning: cairo-1.14.6_1 already installed
Warning: libpng-1.6.23 already installed
Warning: jpeg-8d already installed
Warning: giflib-4.2.3 already installed
➜  phantomjs

But, installed error

npm install canvas@1.3.16
\
> canvas@1.3.16 install /Users/rainer800/SinaWork/#Lab/phantomjs/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rainer800/SinaWork/#Lab/phantomjs/node_modules/canvas
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas@1.3.16"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.16 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

**Comment by LinusU** [comment]
```text
➜ phantomjs xcode-select --install
xcode-select: note: install requested for command line developer tools
```

During this phase, did you get any GUI that prompted you to install the xcode cil tools?

**Comment by rainer800hao** [comment]
Yes, I got it!

**Comment by LinusU** [comment]
Did you install it? Did it solve the problem?

**Comment by rainer800hao** [comment]
Installed successfully, but problem persists.

**Comment by LinusU** [comment]
Hmm, after some googling it seems like you must install xcode as well as the xcode command line tools. It's available via the app store.

https://github.com/nodejs/node-gyp/issues/734

**Comment by goliatone** [comment]
Just FYI, the wiki page for macOS does not mention `xcode-select --install` which will cause this error on install.
