### ISSUE TITLE
I don't understand this install error

### ISSUE THREAD

**Issue by RobinCodeX** [Automattic/node-canvas#792]
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:873:11)
gyp ERR! stack     at TLSWrap.onread (net.js:557:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\daimajun\node_modules\canvas
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "F:\\nodejs\\node.exe" "F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\daimajun\npm-debug.log
```

**Comment by RobinCodeX** [comment]
OK,this is a problem with my network

**Comment by huyangoo** [comment]
Hi,how do you solve the problem of network,i have the same problem


26173 error Windows_NT 6.1.7601
26174 error argv "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
26175 error node v6.10.1
26176 error npm  v3.10.10
26177 error code ELIFECYCLE
26178 error canvas@1.6.0 install: `node-gyp rebuild`
26178 error Exit status 1
26179 error Failed at the canvas@1.6.0 install script 'node-gyp rebuild'.
26179 error Make sure you have the latest version of node.js and npm installed.
26179 error If you do, this is most likely a problem with the canvas package,
26179 error not with npm itself.
26179 error Tell the author that this fails on your system:
26179 error     node-gyp rebuild
26179 error You can get information on how to open an issue for this project with:
26179 error     npm bugs canvas
26179 error Or if that isn't available, you can get their info via:
26179 error     npm owner ls canvas
26179 error There is likely additional logging output above.
26180 verbose exit [ 1, true ]

**Comment by RobinCodeX** [comment]
@huyangoo Do you have run in Visual Studio 2012/2013/2015 Command Line?
