### ISSUE TITLE
text/html buffer to image.src

### ISSUE THREAD

**Issue by khanhankkhan** [Automattic/node-canvas#798]
Looks like images of type text/html

when downloaded and stored as a buffer don't load when assigned to Image.src.

example end-point below

```
app.get('/api/test', function(req,res)
  {
    var type    = '';
    var img_buf   = Buffer('');
    var request = require('request');
    request.get("http://images.bergdorfgoodman.com/ca/2/product_assets/Y/2/S/N/K/BGY2SNK_mu.jpg").
    on('data', function(data)
    {
      img_buf = Buffer.concat([img_buf,data]); 
    }).
    on('end',function(w)
    {
      var Canvas = require('canvas');
      var Image  = Canvas.Image;
      var img = new Image;
      console.log(type);
      console.log('img_buffer done downloading...');
      img.onload = function()
      {
        console.log('i loaded');
        res.send('done');
      };
      img.onerror = function(e)
      {
        console.log('error:'+e);
      }
      img.src = img_buf;
    }).
    on('response', function(response) 
    {
      type = response.headers['content-type'];
    }).
    on('error',function(error)
    {
      console.log('error: '+error+' with:'+image_urls[index]);
    });

  });

```

**Comment by LinusU** [comment]
What do you mean with images of type "text/html"? There are no images of that type, image types starts with "image/", e.g. "Image/jpeg" or "image/gif".

It seems like your url should download a jpeg image, are you sure that your endpoint sets the correct headers?

**Comment by khanhankkhan** [comment]
yes
if i run the above code, on that specific url i see the content-type of the image is text/html. i too am a bit perplexed

`response.headers['content-type'];`

**Comment by khanhankkhan** [comment]
might be an issue with the request-npm... idk i opened a ticket there

https://github.com/request/request/issues/2336

**Comment by khanhankkhan** [comment]
The server hosting the image matters - if you assign the img.src to the url (instead of buffer data), then draw to a canvas and try to get the image data, you get a 'tainted canvas'

example url:
http://images.bergdorfgoodman.com/ca/1/product_assets/J/9/1/5/5/BGJ9155_mu.jpg

javascript console logs:

Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by LinusU** [comment]
Tainted canvases should only exist in the browser, not in node-canvas?

**Comment by zbjornson** [comment]
@khanhankkhan that URL first sends a `301 Moved Permanently` with `Content-Type: text/html`. If you follow the redirect then it correctly has `Content-Type: image/jpeg`.
