### ISSUE TITLE
clear

### ISSUE THREAD

**Issue by fantazer** [Automattic/node-canvas#799]
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = new Canvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by LinusU** [comment]
Closing due to no info being provided...
