### ISSUE TITLE
Problem Installing Color-Wander with Node-Canvas

### ISSUE THREAD

**Issue by NaturalFigurehead** [Automattic/node-canvas#800]
## Issue or Feature
I have installed node-canvas and am able to build it. However when I am trying to do `npm install` for this project, [color-wander](https://github.com/mattdesl/color-wander), I seem to be having problems with node-canvas that I am unsure how to solve.

## Steps to Reproduce

If node-canvas is installed follow the installation directions for color-wander. When you do `npm install` you may end up with something like this:

C:\Users\Oliver\Documents\GitHub\color-wander>npm install
\
> canvas@1.4.0 install C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\canvas
> node-gyp rebuild

C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
..\src\Canvas.cc(144): warning C4457: declaration of 'data' hides function parameter [C:\Users\Oliver\Documents\GitHub\
color-wander\node_modules\canvas\build\canvas.vcxproj]
  ..\src\Canvas.cc(140): note: see declaration of 'data'
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(31): warning C4055: 'type cast
': from data pointer 'HMODULE' to function pointer 'FARPROC' [C:\Users\Oliver\Documents\GitHub\color-wander\node_module
s\canvas\build\canvas.vcxproj]
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot
ifyHook2': redefinition; different type modifiers [C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\canvas\bu
ild\canvas.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\canvas
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Oliver\Documents\GitHub\color-wander\npm-debug.log

Not sure where to go from here. Here's the debug file:
[npm-debug.txt](https://github.com/Automattic/node-canvas/files/425690/npm-debug.txt)

## Your Environment
* Version of node-canvas (1.4.0):
* Environment (node 4.4.7 on win32 x64):

**Comment by zbjornson** [comment]
Try upgrading node-gyp to 2.15.9 or later. (`npm install -g node-gyp`  and `node-gyp -v` to test the version installed)

**Comment by NaturalFigurehead** [comment]
I guess you meant upgrade npm? I did that and it seemed to work! Thanks!

**Comment by zbjornson** [comment]
Actually meant node-gyp, but perhaps upgrading npm upgraded node-gyp as well. :)
