### ISSUE TITLE
pngStream End Before File is writen

### ISSUE THREAD

**Issue by pyromanci** [Automattic/node-canvas#802]
## Issue or Feature
I'm currently working on a script that takes the output from a roll20 API wrote and merge the map data down to a single image. This was due to the fact that a couple of my maps are so big that a few of my maps were so large with so many different elements it was crashing a few of my players.

So i wrote this to rebuild the map in a canvas and save it off as a single PNG. The problem is when i do this. I seem to get the 'saved png' message far before the actually file is finished being written. 

The Final PNG size in my tests was almost 300MB in size.

## Steps to Reproduce
var fs = require('fs')
  , out = fs.createWriteStream(__dirname + '/text.png')
  , stream = canvas.pngStream();
 
stream.on('data', function(chunk){
  out.write(chunk);
});
 
stream.on('end', function(){
  console.log('saved png');
});

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 1.4.0
* Environment: Centos 6 Linux 3.10.101-1.el6.elrepo.x86_64 #1 SMP Wed Mar 16 20:55:27 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LinusU** [comment]
This is expected, `end` only mean that the data has ended from the stream. If you want to know when the file is written, you'll have to listen to the `finish` event on the file writer.

```js
out.on('finish', () => console.log('saved png'))
```

**Comment by mathiasbynens** [comment]
@LinusU In that case, we may want to update this README example: https://github.com/Automattic/node-canvas#canvaspngstreamoptions

**Comment by LinusU** [comment]
Great catch! I’m on mobile now so can’t do it myself, PR welcome or I’ll fix it after the weekend :)
