### ISSUE TITLE
Issue: Wrong behavior when draw stroke text

### ISSUE THREAD

**Issue by Jack-Works** [Automattic/node-canvas#804]
![image](https://cloud.githubusercontent.com/assets/5390719/18052065/de4be768-6e2a-11e6-82c9-f87308c67e93.png)
You can see the strange thorn there. When draw with the font 'Microsoft Yahei'
```js
'use strict'
var path = require('path')
var fs = require('fs')
var bufferToImage = (buffer) => {
    var img = new Image()
    img.src = buffer
    return img
}
var imageToCanvas = (img) => {
    var canvas = new Canvas(img.width, img.height)
    var ctx = canvas.getContext('2d')
    ctx.drawImage(img, 0, 0, img.width, img.height)
    return {canvas, context: ctx}
}
var Canvas = require('canvas')
var Image = Canvas.Image

var src = './test.png'
var canvasAndContext = imageToCanvas(bufferToImage(fs.readFileSync(src)))

var ctx = canvasAndContext.context

let x = 200, y = 200, text = "1   2   3   4   5   6   7    8   9   0"
ctx.font = "32px 'Microsoft Yahei'"
ctx.lineWidth = 15
ctx.strokeStyle = "rgba(71, 153, 216, 0.8)"
ctx.strokeText(text, x, y)

ctx.lineWidth = 10
ctx.fillStyle = 'white'
ctx.fillText(text, x, y)

fs.writeFileSync('./final.png', canvasAndContext.canvas.toBuffer())
```

Node-canvas 1.4.0 on NodeJS 5.12.0 on Windows 10 (1607)

**Comment by LinusU** [comment]
Could you try this an a recent web browser and post how it looks there as well? Thanks :)

**Comment by Jack-Works** [comment]
Interesting, I found it behavior like this in Chrome and Edge, and I'm using sans the default font instead of Microsoft Yahei. And the problem occur again.
Is it a defined behavior of canvas?

![image](https://cloud.githubusercontent.com/assets/5390719/18073772/fc12a320-6e9a-11e6-9389-12cadd0f742b.png)

**Comment by Jack-Works** [comment]
```JS
ctx.lineJoin = "round"
```
will fix this problem, thanks

**Comment by LinusU** [comment]
No problem 👌
