### ISSUE TITLE
Build Fails on macOS Sierra

### ISSUE THREAD

**Issue by kurisubrooks** [Automattic/node-canvas#814]
Installing Canvas 1.5.0 on macOS Sierra yields the following error:

```
  SOLINK_MODULE(target) Release/canvas-postbuild.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
```

All macOS build dependencies **are met**. I did a clean reinstall of them to see if that would fix this error, but it did not.

## Steps to Reproduce
Upgraded from OS X El Capitan to macOS Sierra last night, tried to install Canvas into a new project this morning, and i'm met with the above build error. 

## Your Environment
* Version of node-canvas: 1.5.0
* Environment: Node 6.3.1 on macOS Sierra (10.12)

**Comment by LinusU** [comment]
Can you try `xcode-select --install` :)

**Comment by kurisubrooks** [comment]
Ah darnit. I feel stupid now! I assumed I could skip this step as I opened Xcode manually after updating to Xcode 8, accepted the terms via the GUI, etc etc. Thanks for the response!
