### ISSUE TITLE
"./util/has_lib.sh freetype" returned exit status 0 in Canvas 1.6.0

### ISSUE THREAD

**Issue by kurisubrooks** [Automattic/node-canvas#822]
After updating to 1.6.0 on Ubuntu 16.04, i'm now recieving the following error:

```
$ npm i canvas

> canvas@1.6.0 install /home/kurisu/sherlock/node_modules/canvas
> node-gyp rebuild

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

I previously had Canvas 1.5.0 installed, all the dependencies (through apt) are met, but after trying to install 1.6.0, now I can't even return to 1.5.0.

#### Environment:
Ubuntu 16.04 LTS Server
Canvas 1.6.0
Node 6.5.0

**Comment by zbjornson** [comment]
It sounds like one or more of your dependencies got borked. Might try re-running the install bit (`sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`)... If that doesn't do it, there are a [handful of issues in this repo](https://github.com/Automattic/node-canvas/issues?utf8=%E2%9C%93&q=is%3Aissue%20has_lib.sh) with the same or similar error that might have useful things to try.

**Comment by kurisubrooks** [comment]
Just reinstalled all apt dependencies, unfortunately still the same error. Might go through your link now and see what I can find.

**Comment by kurisubrooks** [comment]
Ironically found my _own_ answer in #755. How unexpected... Totally forgot!

![image](https://cloud.githubusercontent.com/assets/6291467/19574641/f4da8be2-9756-11e6-8763-732bac8c651d.png)

Successfully built.

Maybe we should tell the maintainers to add something in the README to run under sudo on 16.04+

**Comment by LinusU** [comment]
I think that the actual problem was that you had `GREP_OPTIONS` set. `sudo` shouldn't be a requirement and I would not recommend building with `sudo`.

The only reason it started working with `sudo` is that it clears the environment.

This could be fixed by converting `has_lib.sh` from sh to javascript.

**Comment by micky2be** [comment]
Getting same error on CircleCI for my projects (using Ubuntu 14.04).
This is pretty annoying.

**Comment by AvraamMavridis** [comment]
Is this solved somehow?

**Comment by kurisubrooks** [comment]
@AvraamMavridis Not solved, but you can work around this by running `npm i` with `sudo`

**Comment by zbjornson** [comment]
@kurisubrooks as LinusU pointed out this shouldn't be a sudo problem and that is a less safe solution.

@AvraamMavridis and @micky2be is `GREP_OPTIONS` set in your env also?

**Comment by adamjcsmith** [comment]
Fixed on my machine (OSX) with:

```
npm install -g node-gyp
brew install pkg-config cairo libpng jpeg giflib
```

**Comment by capaj** [comment]
@zbjornson I had this on my ubuntu 16.10 and your apt-get command helped, thanks!

**Comment by jodacame** [comment]
@zbjornson worked for me (Ubuntu Server) Thanks!

**Comment by geodyne** [comment]
@adamjcsmith This works for OSX. Thanks!

**Comment by louiemontes** [comment]
@adamjcsmith Seconding, thanks! Fixed problem for MacOS High Sierra (10.13.3) from error when trying to run "npm install color" (for colors.js).

**Comment by kty1965** [comment]
@adamjcsmith Thanks!

**Comment by adimittal** [comment]
npm install -g node-gyp
brew install pkg-config
brew link pkg-config

**Comment by danieltroger** [comment]
> Fixed on my machine (OSX) with:

I also had to `brew install pango`
