### ISSUE TITLE
Can't load canvas module

### ISSUE THREAD

**Issue by ruttydm** [Automattic/node-canvas#823]
I am trying to get the example working but it doesn't work for me.
## Issue or Feature

module.js:328
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ruttydm/Dropbox/CODING/nodecanvas/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

## Steps to Reproduce

var Canvas = require('canvas');
var Image = Canvas.Image;
var canvas = new Canvas(1920, 1080);
var ctx = canvas.getContext('2d');
var fs = require('fs');
var out = fs.createWriteStream(__dirname + '/text.png');
var stream = canvas.pngStream();

ctx.font = '30px Impact';
ctx.rotate(.1);
ctx.fillText("Awesome!", 50, 100);

var te = ctx.measureText('Awesome!');
ctx.strokeStyle = 'rgba(0,0,0,0.5)';
ctx.beginPath();
ctx.lineTo(50, 102);
ctx.lineTo(50 + te.width, 102);
ctx.stroke();

console.log(canvas.toDataURL());
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): latest
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Latest node version on ubuntu

**Comment by chearon** [comment]
try re-running `npm install canvas`, it looks like it hasn't been built. if there are errors when you do that post that here too

**Comment by ruttydm** [comment]
I tried but i just get two warnings about my package.json

**Comment by chearon** [comment]
weird, what does `ls /home/ruttydm/Dropbox/CODING/nodecanvas/node_modules/canvas/build` output? are you calling `require` from the same directory that you did `npm install canvas` in?

**Comment by ruttydm** [comment]
There is no build folder, it can't build for some reason i think. But it gives no errors.

**Comment by chearon** [comment]
hmmm, try:

`npm install -g node-gyp`
`cd /home/ruttydm/Dropbox/CODING/nodecanvas/node_modules/canvas`
`node-gyp rebuild`

maybe the `install` isn't triggering gyp for some reason

**Comment by ruttydm** [comment]
Thanks, this works. Really weird

**Comment by LinusU** [comment]
Thanks for the help @chearon, closing this :)

**Comment by MeaningOfLights** [comment]
I got this error too and this page has the best troubleshooting steps.

My problem was this command `npm install canvas` actually failed. 

What I did to get it installed and working was install it without considering the dependencies:

`npm install canvas --legacy-peer-deps`
