### ISSUE TITLE
 this “drawImage ” API is different from HTML5 Canvas “drawImage”

### ISSUE THREAD

**Issue by match08** [Automattic/node-canvas#827]
var Canvas = require('canvas');
var canvas = new Canvas(200, 200);
var ctx = canvas.getContext('2d');
ctx.drawImgae(image,10,10,1000,100); 

 this “drawImgae ” api different  h5 Canvas “drawImgae”

**Comment by LinusU** [comment]
How do they differ?

**Comment by match08** [comment]
"sx "and "sy" is crop image start  point   ,  "swidth " and "sheight  " is  scale image.
"x" and "y" is  canvas start  point, "width and "height" is  scale image

**Comment by paramaggarwal** [comment]
@match08 That changes based on the number of arguments passed to the function. Please see Mozilla docs.

**Comment by zbjornson** [comment]
I think this is working as intended for all three overloads

```
void ctx.drawImage(image, dx, dy);
void ctx.drawImage(image, dx, dy, dWidth, dHeight);
void ctx.drawImage(image, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight);
```

There's test coverage for all of those. @match08 please let us know if you've found a difference.
