### ISSUE TITLE
"TypeError: Canvas.registerFont is not a function"

### ISSUE THREAD

**Issue by ImSanctuary** [Automattic/node-canvas#828]
Updated all the dependencies, updated canvas, updated node and npm, all in order to try to get custom fonts working (since I couldn't before `Canvas.registerFont` became a thing), but now I get an error saying `Canvas.registerFont` is not a function.

Using basically the same code from the /examples/ folder:
```js
var fs = require('fs');
var path = require('path');
var Canvas = require('canvas');

function fontFile (name) {
    return path.join(__dirname, '/pfennigFont/', name);
}

Canvas.registerFont(fontFile('Pfennig.ttf'), {family: 'pfennigFont'});
Canvas.registerFont(fontFile('PfennigBold.ttf'), {family: 'pfennigFont', weight: 'bold'});
Canvas.registerFont(fontFile('PfennigItalic.ttf'), {family: 'pfennigFont', style: 'italic'});
Canvas.registerFont(fontFile('PfennigBoldItalic.ttf'), {family: 'pfennigFont', weight: 'bold', style: 'italic'});

var canvas = new Canvas(320, 320);
var ctx = canvas.getContext('2d');

ctx.font = 'normal normal 50px Helvetica';

ctx.fillText('Quo Vaids?', 0, 70);

ctx.font = 'bold 50px pfennigFont';
ctx.fillText('Quo Vaids?', 0, 140);
```

All the fonts are in the appropriate folder and etc.
Removing the `Canvas.registerFont` lines and trying to use it then works perfectly fine.

* Using canvas v1.6.1, node v7.0.0 (also tested on 6.5, didn't work there either), npm v3.10.3, fs v0.0.1-security, path 0.12.7
* Ubuntu 16.04.1 x64 VPS

**Comment by LinusU** [comment]
`registerFont` is part of Canvas 2.x which is currently unreleased. I would recommend pinning to a commit right now if you want to try it out, but keep in mind that this is untested and unstable...

```json
  "canvas": "Automattic/node-canvas#a19f790"
```
