### ISSUE TITLE
failed custom font

### ISSUE THREAD

**Issue by weity** [Automattic/node-canvas#840]
## Issue
I have install all thins as wiki said in [this page](https://github.com/Automattic/node-canvas/wiki/Installation---Windows).But when i config binding.gyp to make it support jpeg and custom font.There's something wrong when rebuild it.

## Steps to Reproduce
```
'conditions': [
    ['OS=="win"', {
      'variables': {
        'GTK_Root%': 'C:/GTK', # Set the location of GTK all-in-one bundle
        'with_jpeg%': 'true',
        'with_gif%': 'false',
        'with_pango%': 'true',
        'with_freetype%': 'false'
      }
    }....
```
only set 'with_jpeg' and 'with_pango' variable true.when i rebuild canvas,hint errors:
```
d:\gaga\node_modules\canvas\src\Canvas.h(17): fatal error C108
3: 无法打开包括文件: “pango/pangocairo.h”: No such file or directory (编译源文
件 ..\src\CanvasGradient.cc) [D:\gaga\node_modules\canvas\build\canvas.vcxpr
oj]
  color.cc
d:\gaga\node_modules\canvas\src\Canvas.h(17): fatal error C108
3: 无法打开包括文件: “pango/pangocairo.h”: No such file or directory (编译源文
件 ..\src\Canv
as.cc) [D:\gaga\node_modules\canvas\build\canvas.vcxproj]
d:\gaga\node_modules\canvas\src\Canvas.h(17): fatal error C108
3: 无法打开包括文件: “pango/pangocairo.h”: No such file or directory (编译源文
件 ..\src\Canv
asPattern.cc) [D:\gaga\node_modules\canvas\build\canvas.vcxpro
j]
```
acturally.I have no idea about pango.But I find libs about pango in GTK,like pagnowin32-1.0.lib etc
how can i do?
## Your Environment
* Version of node-canvas (e.g. 1.4.0):1.6.2
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):node v6.2.0 on window10

**Comment by zbjornson** [comment]
Pango wasn't really working on Windows until 2.x, and 2.x also has prebuilds so you don't need to deal with compiling. If you still have this problem with 2.x, let us know!
