### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by DevinThePancake** [Automattic/node-canvas#842]
it wont install because of node-gyp rebuild it says and ive tried everything to fix it :/

**Comment by LinusU** [comment]
Can you post some more information, like the error output?

**Comment by DevinThePancake** [comment]
canvas@1.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Chicken Wings\npm-debug.log

**Comment by DevinThePancake** [comment]
[npm-debug.txt](https://github.com/Automattic/node-canvas/files/585545/npm-debug.txt)

**Comment by DevinThePancake** [comment]
what version am i supposed to have for node?

**Comment by DevinThePancake** [comment]
ok found it out.. it doesnt support python 3.5.2

**Comment by LinusU** [comment]
Glad you managed to solve it :)
