### ISSUE TITLE
Cannot open include file: 'cairo.h': No such file or directory

### ISSUE THREAD

**Issue by DevinThePancake** [Automattic/node-canvas#843]
says it in the title..

**Comment by LinusU** [comment]
Have you followed the installation instructions?

https://github.com/Automattic/node-canvas#installation

**Comment by apexearth** [comment]
Following the ["Install with Chocolatey"](https://github.com/Automattic/node-canvas/wiki/Installation---Windows#install-with-chocolatey) instructions for windows led me to this problem.
Following the ["Install Manually"](https://github.com/Automattic/node-canvas/wiki/Installation---Windows#install-manually) instructions fixed the problem. (downloading GTK 2 and placing it in `C:\GTK`)

The choco install seemed to be lacking the sources.

**Comment by megamindbrian** [comment]
unzipping GTK to C:\GTK worked, it is missing from the to automatic instructions you still have to download GTK separately.

**Comment by eko24ive** [comment]
I can confirm that using manual install solve this issue.
Does anyone from contributors/owner of this repo would like me to create PR to update wiki ?

**Comment by LinusU** [comment]
> Does anyone from contributors/owner of this repo would like me to create PR to update wiki ?

Yes please ☺️

**Comment by zbjornson** [comment]
@eko24ive anyone can edit the wiki without a PR, so if you find a way to improve it, go ahead. That's how the Chocolatey instructions ended up there. There have been [a few issues](https://github.com/Automattic/node-canvas/search?q=chocolatey&type=Issues) with those instructions, so we might want to just remove them if they can't be made more reliable.

**Comment by eko24ive** [comment]
@zbjornson @LinusU 
I've updated the wiki. It was my first time with wikis, so I was expected PR-like procedure or something 😂 
I decided to add a warning for Chocolatey instruction for now, since we don't know if it doesn't work for people at all. Also, I've added an anchor link to "Install Manually" section in the warning message.Please review it and let me know if something not right.

**Comment by zbjornson** [comment]
Thanks @eko24ive. If I have time I'll see if I can come up with a better version of the Chocolatey instructions sometime.

**Comment by eko24ive** [comment]
@zbjornson no problem.

Also, I saw "Installation on Heroku" article on the wiki, and I was wondering why it is even there.
You see, I have my dyno on Heroku running at `heroku-16` stack, and in my project I'm using [chartjs-node](https://github.com/vmpowerio/chartjs-node) which is depended on `node-canvas` and I was able to get it up and running right out of the box without using any buildpacks.
Probably that wiki article must be revised as well, what do you think ?

**Comment by eko24ive** [comment]
I'm just saying that I was sort of able to get `node-canvas` up and running without using any custom buildpacks - right out of the box. Do you have anyone on the collaborators team to check it by chance?

**Comment by chearon** [comment]
I don't think any of the collaborators use Heroku but if you're sure it worked with zero config, I say go ahead and remove the wiki or add a note saying your setup didn't need any changes.

**Comment by eko24ive** [comment]
Ok, I'll double check it then and if it's so - I'll add a note to the article.

**Comment by karlhorky** [comment]
@zbjornson maybe `python2` can be switched to `python` and `microsoft-build-tools` switched to `visualstudio2017-workload-vctools`?

https://github.com/felixrieseberg/windows-build-tools/issues/172#issuecomment-824916268

Why is GTK needed? Can it be installed using Chocolatey too?

We're going to try the Chocolatey instructions with some bootcamp students (with the Python / Build Tools changes proposed above): https://github.com/upleveled/next-starter-peacock#getting-started

**Comment by zhangguanzhang** [comment]
```
sudo apt-get install libcairo2-dev
```
