### ISSUE TITLE
Font size is not correct

### ISSUE THREAD

**Issue by gormat** [Automattic/node-canvas#844]
## Issue
Font size is not correct.

#### Painter.js
    import Canvas from 'canvas';
    import fs from 'fs';
    import path from 'path';
    import config from '../config/config';
    
    export default class Painter {
        constructor () {
            this.canvas = new Canvas(config.painter.width, 1000);
            this.fileName = Date.now().toString();
        }
    
        drawTable () {
            const ctx = this.canvas.getContext('2d');
            ctx.font = '30px Arial';
            ctx.fillText('Hello World', 10, 50);
        }
    
        save (cb) {
            const filePath = path.join(config.exportPath, `${this.fileName}.png`);
            const out = fs.createWriteStream(filePath);
            const stream = this.canvas.pngStream();
    
            stream.on('data', (chunk) => {
                out.write(chunk);
            });
    
            stream.on('end', () => cb(filePath));
        }
    }
    

#### Test.js
    import Painter from '../painter/Painter';
    const painter = new Painter();
    painter.drawTable();
    painter.save((path) => {
        console.log(path);
    });

## Result
When running test.js
[![1479065337470.png](https://s18.postimg.org/jwpr4xy3d/1479065337470.png)](https://postimg.org/image/6fssm2nrp/)

## Environment
* Version of node-canvas 1.6.2:
* Environment ( node v6.8.0 on Mac OS X 10.12.1):

**Comment by chearon** [comment]
looks like a lot more than just font size is wrong! do you know if you have Pango? if you're not sure, what does `pkg-config --libs pango` say? I would look at making sure you have the most up-to-date versions of Pango and Cairo

**Comment by gormat** [comment]
Hi @chearon 
`pkg-config --libs pango` says `-L/usr/local/Cellar/pango/1.38.0/lib -L/usr/local/Cellar/glib/2.46.0/lib -L/usr/local/opt/gettext/lib -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl`

**Comment by chearon** [comment]
I believe they're on 1.40.3. Try `brew update` && `brew upgrade pango`

**Comment by gormat** [comment]
@chearon 
update works. Thank you very much.
