### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by abellee** [Automattic/node-canvas#845]
i can install canvas.
but after i require it and launch my app
it shows me "Error: Module version mismatch. Expected 50, got 51."

my os is mac os x 10.12.1 and nodejs is v.7.1.0
also i have tried to submodule your rep and rebuild it,
all of that is success, but when i launched.

**Comment by LinusU** [comment]
It looks like you are building with Node 6 and launching to Node 7.

Could you try running `npm rebuild`?

**Comment by abellee** [comment]
@LinusU where to run?

**Comment by abellee** [comment]
@LinusU I have tried to run *npm rebuild* under both my app dir and submodule of ur repo, also show my this error

**Comment by LinusU** [comment]
Hmm, strange, are you sure that you don't have mutliple binaries of node installed at the same time somehow?

**Comment by abellee** [comment]
@LinusU i tried to run `node -v`
it only shows me `v7.1.0`
and i tried to run `npm -v`
then shows me `4.0.2`

**Comment by abellee** [comment]
@LinusU I have tried to reinstall the nodejs v6.9.1 LTS
also not working

**Comment by abellee** [comment]
it's also not working even though I have reinstalled the nodejs

**Comment by Jack-Works** [comment]
Just remove the node_modules and npm install it again

**Comment by abellee** [comment]
@Jack-Works I have tried. even tried to reinstall the nodejs. still not working.
