### ISSUE TITLE
Difference between Data URI on server/client

### ISSUE THREAD

**Issue by ryan-codingintrigue** [Automattic/node-canvas#853]
I have a small piece of code which draws to a canvas and returns the resulting data URI - this code runs on both the server & client, so I need the result to be identical - however using the exact same code produces different data URIs even though the resulting images are identical

## Issue or Feature
Potential issue? Not sure if Data URIs are supposed to be unique across environments.

## Steps to Reproduce
On Server: 
```js
function render(c1, c2, size) {
    const ServerCanvas = require('canvas');
    const canvasSize = size * 2;
    const canvas = new ServerCanvas(canvasSize, canvasSize);
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = c1;
    ctx.fillRect(0, 0, canvasSize, canvasSize);
    ctx.fillStyle = c2;
    ctx.fillRect(0, 0, size, size);
    ctx.translate(size, size);
    ctx.fillRect(0, 0, size, size);
    return canvas.toDataURL();
}

console.log(render("transparent", "rgba(0,0,0,0.8)", 8));
// data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAAK0lEQVQ4jWNkYGA4w4AfmOCTZCKgmSAYNWAwGMBIhBq86WTgvTBqABUMAADKgwHrfdT4mAAAAABJRU5ErkJggg==
```

On Client:
```js
function render(c1, c2, size) {
    const canvasSize = size * 2;
    const canvas = document.createElement("canvas");
    canvas.width = canvas.height = canvasSize;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = c1;
    ctx.fillRect(0, 0, canvasSize, canvasSize);
    ctx.fillStyle = c2;
    ctx.fillRect(0, 0, size, size);
    ctx.translate(size, size);
    ctx.fillRect(0, 0, size, size);
    return canvas.toDataURL();
}

console.log(render("transparent", "rgba(0,0,0,0.8)", 8));
// data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMUlEQVQ4T2NkYGA4w4AfmOCTZhw1gGGYhAGBZIA/nYDCgBDAm9BGDWAAJyRCgLaBCACbmQ5xVDZNzgAAAABJRU5ErkJggg==
```

Resulting diff:
![image](https://cloud.githubusercontent.com/assets/9048902/20786768/ca1e1f9a-b79f-11e6-9d34-9004f503e1d7.png)

## Your Environment
* Version of node-canvas: 1.6.2
* Environment: Node 6.2.2 on Mac OS X 10.12.1

**Comment by LinusU** [comment]
This would probably be different between browsers as well, PNG is a form of compression and there is no guarantees on the stability of the output...

**Comment by ryan-codingintrigue** [comment]
@LinusU Ahh, OK - that makes sense. Thanks for the clarification.
