### ISSUE TITLE
node-gyp rebuild errror

### ISSUE THREAD

**Issue by qly612525** [Automattic/node-canvas#854]
```
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory `/vagrant/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/node_modules/canvas
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "canvas"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
vagrant@precise64:/vagrant$ make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1^C
```

## Issue or Feature

make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory `/vagrant/node_modules/canvas/build'

**I think there are some error in the Canvas.o. But I don't know how to solve it**

## Your Environment
* Version of node-canvas (e.g. 1.4.0):  1.6.2
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):  Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kodie** [comment]
+1 same issue

**Comment by jsharonk** [comment]
also having the same issue

**Comment by chearon** [comment]
I don't know anything about vagrant and I'm not sure if any of the contributors here do, but one thing you can try is using the unofficial `canvas-prebuilt` NPM module.

if you wanna solve the build problem you'd have to:

```
npm ERR! Please include the following file with any support request:
npm ERR! /vagrant/npm-debug.log
```

**Comment by dikeert** [comment]
I'm having same issue:

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/aermolenko/.nvm/versions/node/v7.2.0/bin/node" "/usr/local/bin/npm" "install" "canvas" "--save"
npm ERR! node v7.2.0
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE
```

**Comment by jsharonk** [comment]
hello, thanks very much for your response. here's the full error i get
below:

npm ERR! Failed at the canvas@1.6.2 install script 'node-gyp rebuild'.

npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the canvas package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     node-gyp rebuild

npm ERR! You can get information on how to open an issue for this project
with:

npm ERR!     npm bugs canvas

npm ERR! Or if that isn't available, you can get their info via:

npm ERR!     npm owner ls canvas

npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:

npm ERR!     /Users/jsk/Desktop/whatifmaybe/panic-diary/npm-debug.log

**Comment by jonbronson** [comment]
I'm also running into this same issue.

**Comment by pwichmann** [comment]
Same here. Any solution?

```
root@XXX-nodejs-512mb:/var/www/XXX# npm install canvas -g

> canvas@1.6.2 install /usr/lib/node_modules/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/canvas/.node-gyp"
make: Entering directory '/usr/lib/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:9:0:
../src/Image.h:19:21: fatal error: gif_lib.h: No such file or directory
compilation terminated.
canvas.target.mk:120: recipe for target 'Release/obj.target/canvas/src/CanvasPattern.o' failed
make: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1
make: Leaving directory '/usr/lib/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/canvas
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "canvas" "-g"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by pwichmann** [comment]
Same here. Any solution?

**Comment by TnkC** [comment]
Hey, finally found the solution! I was having this error as well, what you have to do is download the dependencies first.
`sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`
After you finish that you would proceed with installing using `npm install canvas`

**Comment by batjko** [comment]
Apparently canvas, for some reason, depends on native modules.
So @TnkC 's suggestion will work (on Linux). Node-gyp is for compiling native modules and npm needs some native build tools to do just that.

On Windows you might have to install Visual Studio for Desktop, which includes all the build tools node-gyp needs.

**Comment by BigMoose530** [comment]
I'm also having this problem on Windows.  Running the latest NodeJS (6.9.5).  I have Visual Studio Pro 2013 installed and licensed.  I do not currently have the GNU compiler tools installed on this machine.  The suggestion about using "sudo" seems aimed at Linux not Windows.  Any ideas?

**Comment by zbjornson** [comment]
@BigMoose530 do you have GTK installed? See https://github.com/Automattic/node-canvas/wiki/Installation---Windows

**Comment by BigMoose530** [comment]
I have GTK2 installed in C:\GTK.  I have libjpeg-turbo installed in
C:\libjpeg-turbo-gcc.  I have Visual Studio 2013.  I've tried:

npm install canvas
npm install canvas --msvs_version=2013

Python is installed and appears to be working.

I've run:
    npm install -g node-gyp
and this appears to execute successfully

Anything else I might have missed? Here is the latest error message:

******

C:\Windows\system32\node_modules\canvas>if not defined npm_config_node_gyp
(node
 "C:\Program
Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: binding.gyp not found (cwd: C:\Windows\system32\node_modules\canvas)
while
trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program
Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open
'C:\Windows\system32\pac
kage.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by zbjornson** [comment]
@BigMoose530 looks like something's weird with your working directory/path:

> C:\Windows\system32\package.json
> binding.gyp not found (cwd: C:\Windows\system32\node_modules\canvas)

Are you actually trying to use C:\Windows\system32 as your development directory or did gyp try to go where it shouldn't, somehow?

**Comment by BigMoose530** [comment]
This could certainly be the problem.  What directory should I be in?
    -- bruce musicus

**Comment by zbjornson** [comment]
@BigMoose530 wherever the node.js project that you're working on is located. This installs like a normal NPM module (aside from the native dependencies).

**Comment by BigMoose530** [comment]
This idea is almost surely the solution.  Thanks!  (I had assumed that this
was a global install of some sort.)
    -- bruce musicus

**Comment by metaColin** [comment]
Same trouble here on Fedora 24. The Fedora dependency list from the wiki was not sufficient.

It might be overkill but this is what worked for me:
`RUN dnf install -y cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel make automake gcc gcc-c++ kernel-devel`

**Comment by CrizzzSombiii** [comment]
Same error on windows 10...

**Comment by zbjornson** [comment]
Closing because there are no specific errors in this issue, the suggestions in the comments are now in the readme and prebuilds exist.
