### ISSUE TITLE
[Error: error while reading from input stream]

### ISSUE THREAD

**Issue by hanagejet** [Automattic/node-canvas#856]
## Issue

I have this error: `[Error: error while reading from input stream]`
Can I resolve this??

## Steps to Reproduce

my test js
```js
// some imports and variables...

test('run setImage', t => {
  fs.readFile(dummyImg, 'base64', (err, data) => {
    if (err) throw error;
    const img = new Image;
    img.src = data;

    return setImage(img, data)
    .then(result =>
      t.is(result, img)
    );
  });
});
// etc.
```

this is setImage method
```js
  static setImage(img, src) {
    return new Promise((resolve, reject) => {
      img.onload = () => resolve(img);
      img.onerror = error => reject(error);
      img.src = src;
    });
  }
```

## Your Environment
* Version of node-canvas (e.g. 1.6.2):
* Environment (e.g. node 5.0.0 on Mac OS X 10.12.1):

**Comment by mohamedmansour** [comment]
According to this https://github.com/Automattic/node-canvas/wiki/Installation---Windows, JPEG support is only available for libjpeg #841 (which is pending)

The error you are having (since I ran into the same issue) is basically because in `lib/Image.js` it is setting:

```
Image.prototype.__defineSetter__('src', function(val){
  console.log('MO', '"'+ val +  '"');
  if ('string' == typeof val && 0 == val.indexOf('data:')) {
    val = val.slice(val.indexOf(',') + 1);
    this.source = Buffer.from(val, 'base64');
  } else {
    this.source = val;
  }
});
```

this.source is failing in native code (according to your stack trace),  

```
cairo_status_t
Image::loadFromBuffer(uint8_t *buf, unsigned len) {
  uint8_t data[4] = {0};
  memcpy(data, buf, (len < 4 ? len : 4) * sizeof(uint8_t));

  if (isPNG(data)) return loadPNGFromBuffer(buf);
#ifdef HAVE_GIF
  if (isGIF(data)) return loadGIFFromBuffer(buf, len);
#endif
#ifdef HAVE_JPEG
#if CAIRO_VERSION_MINOR < 10
  if (isJPEG(data)) return loadJPEGFromBuffer(buf, len);
#else
  if (isJPEG(data)) {
    if (DATA_IMAGE == data_mode) return loadJPEGFromBuffer(buf, len);
    if (DATA_MIME == data_mode) return decodeJPEGBufferIntoMimeSurface(buf, len);
    if ((DATA_IMAGE | DATA_MIME) == data_mode) {
      cairo_status_t status;
      status = loadJPEGFromBuffer(buf, len);
      if (status) return status;
      return assignDataAsMime(buf, len, CAIRO_MIME_TYPE_JPEG);
    }
  }
#endif
#endif
  return CAIRO_STATUS_READ_ERROR;
}
```

And you are hitting the "CAIRO_STATUS_READ_ERROR"  because in binding.gyp, everything is false:

```
 'conditions': [
    ['OS=="win"', {
      'variables': {
        'GTK_Root%': 'C:/GTK', # Set the location of GTK all-in-one bundle
        'with_jpeg%': 'false',
        'with_gif%': 'false',
        'with_pango%': 'false',
        'with_freetype%': 'false'
      }
    },
```

So you have to set "--with_jpeg=true" when rebuilding with gyp. But this is broken because GTK (that was provided in the wiki) doesn't get bundled with jpeg:
```

        ['with_jpeg=="true"', {
          'defines': [
            'HAVE_JPEG'
          ],
          'conditions': [
            ['OS=="win"', {
              'libraries': [
                '-l<(GTK_Root)/lib/jpeg.lib'
              ]
            }, {
              'libraries': [
                '-ljpeg'
              ]
            }]
          ]
        }],
```

So yea, it isn't supported in Windows yet it got regressed.

**Comment by zbjornson** [comment]
Thanks @mohamedmansour for picking up that this was on Windows and troubleshooting. In that case, it's the same as #738.

**Comment by hanagejet** [comment]
@mohamedmansour @zbjornson Thanks a lot!! Good information :)

**Comment by awingit** [comment]
So based on what @mohamedmansour, there is no solution for windows? I am unable to resolve this very issue. Is there no manual way to get libjpeg working with GTK?

**Comment by zbjornson** [comment]
@awingit the fork in https://github.com/Automattic/node-canvas/pull/841 provides JPEG support on Windows but hasn't been merged yet. You could install that fork directly if needed.

**Comment by awingit** [comment]
Thanks @zbjornson , How exactly do I install a specific version? Can this be done with node? Or would I need to use git for this? Would you be willing to give me an idea of how I would use the working version in my project?

**Comment by mohamedmansour** [comment]
@awingit it is a branch (pr) checkout that branch and build.  

@zbjornson it works great, should be merged in :) I tried it 3 months ago

**Comment by awingit** [comment]
Thanks @mohamedmansour, I think I am exposing my limited skills understanding of git. I know some basics of cloning, pulling, committing and  pushing, but I am not yet clued up with branches. Would I be pushing my luck to ask for an example to be able to install the correct version? Specifically [#841](https://github.com/Automattic/node-canvas/pull/841) . Your help is really appreciated.

**Comment by awingit** [comment]
@mohamedmansour and @zbjornson , I have downloaded the branch mentioned and manually copied it over. I then did a rebuild from the canvas folder: 
node-gyp rebuild --with_jpeg=true --jpeg_root=C:\libjpeg-turbo64
The build completes without any errors.
However, I still get an error:
"error while reading from input stream"

**Comment by awingit** [comment]
Sorry guys, I do not want to waste anyones time. I am wondering if the issue is my environment. I seem to be getting an issue even for PNG files.

Perhaps this is not related to node-canvas or its dependencies.

Here is the error I get:

> Error: error while reading from input stream
>     at Error (native)
>     at Image.src (C:\wamp\www\localhost\test\webgl\maps\node_modules\canvas\lib\image.js:30:17)
>     at loadImage (C:\wamp\www\localhost\test\webgl\maps\node_modules\load-img\index.js:34:10)
>     at C:\wamp\www\localhost\test\webgl\maps\node_modules\async-image-loader\index.js:24:7
>     at C:\wamp\www\localhost\test\webgl\maps\node_modules\async-each\index.js:16:7
>     at Array.forEach (native)
>     at each (C:\wamp\www\localhost\test\webgl\maps\node_modules\async-each\index.js:15:11)
>     at load (C:\wamp\www\localhost\test\webgl\maps\node_modules\async-image-loader\index.js:22:5)
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by mohamedmansour** [comment]
@awingit  I do not think you did not checkout the correct branch for the PR. 

This is how you usually do it in GitHub:

```
git fetch origin pull/841/head:winjpeg
git checkout winjpg
node-gyp rebuild --GTK_Root=C:\Tools\GTK --jpeg_root=C:\Tools\libjpeg-turbo64  --with_jpeg
```

I just verified it still works.

**Comment by zbjornson** [comment]
(The `--with_jpeg` flag shouldn't be necessary anymore. It was needed in the older PR #815 only.)

**Comment by marcsyp** [comment]
@awingit -- did you solve this for your PNG files?  I am getting the same error with PNG files as well.

**Comment by marcsyp** [comment]
Incidentally, I found a workaround by including some legacy code from another thread. Instead of using loadImage, I'm using:

from: https://github.com/Automattic/node-canvas/issues/959
```
const http = require('http');
function loadImage (url) {
    return new Promise((resolve, reject) => {
        const img = new Canvas.Image();
        img.onload = () => resolve(img);
        img.onerror = () => reject(new Error('Failed to load image'));
        http.get(url, (res) => {
            let buf = '';
            res.setEncoding('binary');
            res.on('data', function(chunk){ buf += chunk; });
            res.on('end', function(){
                let canvas = new Canvas();
                img.src = new Buffer(buf, 'binary');
            });
        })
    })
}
```

Works well -- but I'm wondering what is wrong with the loadImage method....
