### ISSUE TITLE
node-gyp running in canvas directory cannot find C++ compiler

### ISSUE THREAD

**Issue by iankevinmcdonald** [Automattic/node-canvas#858]
## Issue or Feature

Am attempting to install canvas on a Linux Mint box. It fails to install after failing to detect the C++ compilers (or finding that they do not meet dependencies).

## Steps to Reproduce
Install nodejs and npm as per these instructions:
https://github.com/nypublicradio/audiogram/blob/master/INSTALL.md

After issues, I chose low memory troubleshooting options 2 and 3 below; using clang and separating out the canvas install. As per its package.json file, I ran:

npm install git+https://github.com/chearon/node-canvas.git#12971f64a66b

As this hadn't occurred with other runs of "npm install", I assume it's an issue with canvas.

## Your Environment
* Version of node-canvas (e.g. 1.4.0):
Not yet installed.

* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
uname -a yields:
Linux orwell 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:41:14 UTC 2012 i686 i686 i386 GNU/Linux

ian@orwell ~/audiogram $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
ian@orwell ~/audiogram $ clang -v
Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: i386-pc-linux-gnu
Thread model: posix

Installation logging output (from two different runs):
[npm-debug.log.txt](https://github.com/Automattic/node-canvas/files/655231/npm-debug.log.txt)

The mention of a requirement for "C++11" is in the standard error, which I captured in this file:
[npm-error2.log.txt](https://github.com/Automattic/node-canvas/files/655232/npm-error2.log.txt)

**Comment by LinusU** [comment]
> GCC 4.8.1 was the first feature-complete implementation of the 2011 C++ standard

You seem to have GCC 4.6.3 which I guess is to old, try updating to at least 4.8.1
