### ISSUE TITLE
gyp ERR! build error  while npm install freshbooks package

### ISSUE THREAD

**Issue by Ameer3060** [Automattic/node-canvas#859]
Spends hours trying every solution. It works perfectly on my local environment but when I try to put on my server ( CentOS ) I am not able to install following is the error log. Thanks in advance :)

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-042stab113.11
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/freshbooks/node_modules/libxmljs
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN ameer@1.0.0 No repository field.
npm ERR! Linux 2.6.32-042stab113.11
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "freshbooks"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/freshbooks/npm-debug.log

**Comment by gevorg15** [comment]
I'm running into the same exact issue

**Comment by zbjornson** [comment]
>  Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.

This doesn't look like a node-canvas problem...

**Comment by Ameer3060** [comment]
It is a general node issue. if you can help that would be great

**Comment by Ameer3060** [comment]
@gevorg15 were you able to solve it?

**Comment by LinusU** [comment]
This should be reported to libxmljs, not here...
