### ISSUE TITLE
drawImage support not working with cairo 1.10.2 from Homebrew

### ISSUE THREAD

**Issue by nielsm** [Automattic/node-canvas#86]
brew info cairo
cairo 1.10.2
http://cairographics.org/
Depends on: pkg-config, pixman
/usr/local/Cellar/cairo/1.10.2 (91 files, 6.5M)

When trying to use drawImage, I get this error in console:

Error: drawImage() needs cairo >= 1.10.0

This seems similar to https://github.com/LearnBoost/node-canvas/issues/4, but in this case, Homebrew has the latest version.

Thoughts?

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
