### ISSUE TITLE
fatal error: 'jpeglib.h' file not found

### ISSUE THREAD

**Issue by appbanana** [Automattic/node-canvas#860]
1.brew install pkg-config cairo pango libpng jpeg giflib
2.npm install canvas
The problem of "../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
"  appear after two steps . How I can solve this problem?

## Your Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (e.g. node v7.2.0 npm 4.0.5  node-gyp -v v3.4.0 on macOS  10.12.2):

**Comment by LinusU** [comment]
Can you try running `xcode-select --install`?

More info: http://stackoverflow.com/a/32929012/148072

**Comment by mohamedmansour** [comment]
@LinusU this is an issue with GTK2 for Windows too, I explained my findings here #856

**Comment by ilfrich** [comment]
@LinusU `xcode-select --install` solved the problem for me!

**Comment by LinusU** [comment]
Closing this since `xcode-select --install` seems to fix it on macOS and since #856 tracks the error on windows
