### ISSUE TITLE
ISSUE:  show nothing in 'node-gyp rebuild' when installing canvas@1.6.2

### ISSUE THREAD

**Issue by jiangzihao** [Automattic/node-canvas#871]
When I'm installing canvas@1.6.2

```
> canvas@1.6.2 install /home/jiangzihao/Projects/szupu-fa/server/node_modules/canvas
> node-gyp rebuild
```

Then the terminal show nothing?
Just stuck in there?
What I can do just waiting...

I'm using node@7.4.0 & npm@4.0.5 on Ubuntu 16.04
Network Environment: Chinese mainland(Maybe GFW cause this problem?)

**Comment by francescostella** [comment]
Same error here in macOS 10.12.3
Node: v6.9.5
NPM: 3.10.10

**Comment by francescostella** [comment]
@jiangzihao On Linux you might find a solution here: https://github.com/Automattic/node-canvas/issues/854#issuecomment-272637456

**Comment by francescostella** [comment]
For macOS users: I skipped the run of `xcode-select --install`. This solves the issue.

**Note:** don't forget to run first of all
`brew install pkg-config cairo pango libpng jpeg giflib`
