### ISSUE TITLE
What is the maximum value of width/height of canvas ? 

### ISSUE THREAD

**Issue by jd1378** [Automattic/node-canvas#875]
i need to create a very large canvas (4000 x 36000) , i wanted to know if its possible or not.

**Comment by zbjornson** [comment]
A lot of methods stop working for canvases with >32,767 px (max signed int16) in either width or height (including `toBuffer` and `getImageData`). This is a limitation of Cairo's maximum surface dimensions, as far as I know. You could theoretically make a 32767 x 32767 (~1 gigapixel) canvas though.

At 32,767 px, you might also start hitting some issues with node memory usage in general. `getImageData(0,0,4000,32767)` will require at least 524,272,000 bytes. The streaming methods will hopefully work. Worth a try.

**Comment by jd1378** [comment]
Thanks for the answer , 
is it possible to append some images using streaming methods ? how can i do that ?

**Comment by zbjornson** [comment]
Not quite sure what you mean.  You want to stream an image onto the canvas? [`ctx.drawImage`](https://github.com/Automattic/node-canvas#imagesrcbuffer) is sync but you can put it in the callback of an async data load.

**Comment by jd1378** [comment]
thank you so much
i got what i needed

**Comment by tests1** [comment]
Hi jd,
Can you please let me know how you got resolved to achieve larger dimension canvas:

greater than 36000
