### ISSUE TITLE
add raw data access

### ISSUE THREAD

**Issue by dunkfordyce** [Automattic/node-canvas#88]
I would like a way to grab the raw RGBA data straight from cairo without it being made into a PNG first. 

For some applications you dont want a PNG and the PNG creation process is actually rather slow. I already have code for such a method because Im turning the data into YUV format but Im interested if this functionality would be welcome.  

As for API, something like Canvas.toRAWBuffer() or .toRGBABuffer() would be fine imo.

**Comment by LinusU** [comment]
`ctx.getImageData` should cover that use case :+1:
