### ISSUE TITLE
Slight font rendering difference on Windows and Linux

### ISSUE THREAD

**Issue by zefie** [Automattic/node-canvas#880]
## Issue or Feature
Font generation seems to be slightly different on Linux and Windows.
The code, font files, etc are the same on both platforms. I was testing on Windows and literally uploaded the entire folder to Linux, and did npm rebuild to obviously get linux binaries rather than windows binaries of node-canvas.

The difference is subtle, a little hard to notice on this test example, but very easy to notice on my actual application. You should see that, despite being the same exact code, that the Windows version is a bit more... "bolder". This is the correct version, as this is what you would get if you used the Ubuntu font in an actual browser canvas.

See here: http://i.imgur.com/CxVIo1A.png

## Steps to Reproduce
Code is a bit too big to post here, So I pastebin'd it: http://pastebin.com/nHvTFvXt

```
command output:

windows:
S:\sites\nepgen_nodejs>node test.js
loaded: Ubuntu (S:\sites\nepgen_nodejs\resources\fonts\Ubuntu\Ubuntu-Regular.ttf)
loaded: Ubuntu (S:\sites\nepgen_nodejs\resources\fonts\Ubuntu\Ubuntu-Italic.ttf)
loaded: Ubuntu (S:\sites\nepgen_nodejs\resources\fonts\Ubuntu\Ubuntu-Bold.ttf)
loaded: Ubuntu (S:\sites\nepgen_nodejs\resources\fonts\Ubuntu\Ubuntu-BoldItalic.ttf)

linux:
zefie@nodejs:~/node_apps/nepgen_nodejs$ node test.js
loaded: Ubuntu (/home/zefie/node_apps/nepgen_nodejs/resources/fonts/Ubuntu/Ubuntu-Regular.ttf)
loaded: Ubuntu (/home/zefie/node_apps/nepgen_nodejs/resources/fonts/Ubuntu/Ubuntu-Italic.ttf)
loaded: Ubuntu (/home/zefie/node_apps/nepgen_nodejs/resources/fonts/Ubuntu/Ubuntu-Bold.ttf)
loaded: Ubuntu (/home/zefie/node_apps/nepgen_nodejs/resources/fonts/Ubuntu/Ubuntu-BoldItalic.ttf)
```

## Your Environment
* node-canvas version git-5702c47
* Windows (x64) Node Version: v6.9.5
* Debian Jessie Linux (x64) Node Version: v6.10.0
* Linux pango version: 1.36.8-3
* Windows pango version: (whatever is in the GTK zip provided on your wiki for Windows installation)

**Comment by zefie** [comment]
Small update, by applying a stroke of 0.2 to only the linux render, I am able to _nearly_ simulate the Windows "bolder" effect, but another issue I just noticed stands out, and that is the render height seems to be different. Take this video for example, where I switch between test_win32.png and test_linux.png very fast.

https://www.planeptune.org/2017-02-28_node-canvas_font.webm

Specifically, notice the letter "e", and how the top portion appears "squished" in the linux render. Also note that the "jumping" is not bad editing on my part, it is part of the render issue. (I'm just displaying the two generated images back to back in Windows Photo Viewer, and what you see is a cropped screen capture)

(For reference, here are the changes I made to the above sample code to generate the stroke only on linux):

Between the ctx.font definition and ctx.fillText function, add:
```js
if (os.platform() == "linux") {
	ctx.strokeStyle = ctx.fillStyle;
	ctx.lineWidth = 0.2;
	ctx.lineJoin = 'round';
	ctx.strokeText("testing font rendering: "+os.platform(),10,50);
}
```

**Comment by chearon** [comment]
Each OS has different ways of rasterizing fonts... there's many techniques and tricks that they all choose to do differently, and you generally can't expect fonts to render the same across platforms. I would avoid expecting anything to be consistent except for general metrics. See the comment at the end of #782 too

**Comment by Maxim-Mazurok** [comment]
Ran into this issue when using vega to generate charts.
Might switch to SVG, but then I'll lose the ability to view a nice diff in VS Code to see what changed on the chart (I update them weekly to track finances).
So instead, I'm considering using Docker to do the rendering.
I usually use my windows PC, but sometimes use my MacOS laptop, so it's quite annoying that all charts are showing up in git diff when I switch from one machine to another.
