### ISSUE TITLE
Windows 10 installation failed

### ISSUE THREAD

**Issue by fstn** [Automattic/node-canvas#881]
Hi, I was unable to install node-canvas. I have done all step of windows installation guide, I don't know what to do

> :\Users\stephen\AppData\Roaming\npm\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\stephen\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
> \node-gyp.js" rebuild )  else (node "" rebuild )
> Warning: Missing input files:
> C:\GTK\bin\libfreetype-6.dll
> Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
>   Canvas.cc
>   CanvasGradient.cc
>   CanvasPattern.cc
>   CanvasRenderingContext2d.cc
>   color.cc
>   Image.cc
>   ImageData.cc
>   init.cc
>   win_delay_load_hook.cc
> ..\src\CanvasRenderingContext2d.cc(801): warning C4458: la déclaration de 'constructor' masque le membre de classe [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
>   c:\users\stephen\appdata\roaming\npm\node_modules\canvas\src\CanvasRenderingContext2d.h(72): note: voir la déclaration de 'Context2d::constructor' (compilation du fichier source ..\src\CanvasRenderin
>   gContext2d.cc)
> ..\src\Canvas.cc(154): warning C4457: la déclaration de 'data' masque le paramètre de fonction [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
>   ..\src\Canvas.cc(150): note: voir la déclaration de 'data'
>      CrÚation de la bibliothÞque C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\Release\canvas.lib et de l'objet C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\Release\c
>   anvas.exp
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_destroy_write_struct [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_bKGD [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_write_user_transform_fn [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_surface_destroy [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_longjmp_fn [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_get_stride [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_get_format [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_destroy [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_get_io_ptr [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_surface_finish [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_get_data [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pdf_surface_set_size [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_write_info [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_packswap [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_write_image [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_get_error_ptr [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_get_height [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pdf_surface_create_for_stream [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_create [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_status_to_string [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_filter [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_surface_flush [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_svg_surface_create_for_stream [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_compression_level [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_surface_status [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_IHDR [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_write_fn [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_create_info_struct [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_set_filler [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_write_end [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_get_width [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_error [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_create [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Canvas.obj : error LNK2001: symbole externe non rÚsolu png_create_write_struct_2 [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasGradient.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_add_color_stop_rgba [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasGradient.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_create_radial [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasGradient.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_create_linear [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasGradient.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_destroy [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasPattern.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_create_for_surface [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_path_destroy [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_in_fill [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_select_font_face [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_operator [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_surface_mark_dirty_rectangle [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_save [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_matrix [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_arc_negative [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_stroke_preserve [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_rectangle [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_line_join [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_get_filter [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_source_surface [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_fill [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_line_cap [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_source [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_mask_surface [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_set_filter [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_fill_extents [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_show_page [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_restore [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_font_extents [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_line_to [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_fill_rule [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_paint [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_push_group [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_stroke [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_move_to [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_line_cap [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pattern_set_extend [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_operator [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_text_path [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_clip [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_antialias [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_source_rgba [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_copy_path_flat [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_source [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_scale [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_user_to_device_distance [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_show_text [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_surface_mark_dirty [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_font_size [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_fill_preserve [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_rotate [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_stroke_extents [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_matrix_init [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_text_extents [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_pop_group_to_source [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_dash [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_miter_limit [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_append_path [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_new_path [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_identity_matrix [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_line_join [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_in_stroke [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_paint_with_alpha [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_antialias [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_dash_count [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_dash [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_transform [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_close_path [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_arc [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_line_width [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_clip_preserve [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_line_width [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_set_miter_limit [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_get_current_point [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_translate [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> CanvasRenderingContext2d.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_curve_to [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Image.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_create_from_png [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> Image.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_image_surface_create_from_png_stream [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> init.obj : error LNK2001: symbole externe non rÚsolu __imp_cairo_version_string [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
> C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\Release\canvas.node : fatal error LNK1120: 111 externes non rÚsolus [C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas\build\canvas
> .vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\stephen\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 10.0.14393
> gyp ERR! command "E:\\DevTools\\node.exe" "C:\\Users\\stephen\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\stephen\AppData\Roaming\npm\node_modules\canvas
> gyp ERR! node -v v6.9.4
> gyp ERR! node-gyp -v v3.5.0
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! canvas@1.6.4 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the canvas@1.6.4 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the canvas package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs canvas
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls canvas
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\stephen\AppData\Roaming\npm-cache\_logs\2017-02-28T06_56_06_548Z-debug.log

## Your Environment
* Version of node-canvas 1.6.4
* Environment 👍 
    npm: 4.4.0
   visual studio 2015
   GTK: 2.24.10 
   Windows 10 64bit

> C:\DevTools\Git\peter>set
PROMPT=$P$G
USERDOMAIN_ROAMINGPROFILE=FSTN
PROCESSOR_LEVEL=6
FP_NO_HOST_CHECK=NO
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
SESSIONNAME=Console
ALLUSERSPROFILE=C:\ProgramData
PROCESSOR_ARCHITECTURE=AMD64
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
SystemDrive=C:
SSH_AGENT_PID=6532
MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
USERNAME=stephen
ProgramFiles(x86)=C:\Program Files (x86)
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY
HerokuPath=C:\Program Files (x86)\Heroku
ProgramData=C:\ProgramData
ProgramW6432=C:\Program Files
HOMEPATH=\Users\stephen
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 70 Stepping 1, GenuineIntel
ProgramFiles=C:\Program Files
PUBLIC=C:\Users\Public
NODE_ENV=DEV
windir=C:\WINDOWS
LOCALAPPDATA=C:\Users\stephen\AppData\Local
USERDOMAIN=FSTN
LOGONSERVER=\\FSTN
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_45
VS120COMNTOOLS=E:\DevTools\Common7\Tools\
asl.log=Destination=file
OneDrive=C:\Users\stephen\SkyDrive
APPDATA=C:\Users\stephen\AppData\Roaming
CYGWIN=mintty
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
CommonProgramFiles=C:\Program Files\Common Files
Path=C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\ImageMagick-6.8.3-Q16;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\
WindowsPowerShell\v1.0\;E:\DevTools\play-2.0.3\play-2.0.3;C:\Program Files\Java\jdk1.7.0_07\bin;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files
\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tool
s\Binn\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\ImageMagick-6.8.3-Q16\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\
git\cmd;C:\Program Files (x86)\MySQL\MySQL Utilities 1.3.6\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\8.1\Windows Perfo;C:\Program Files (x86)\NVIDIA Corpor
ation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C
:\Program Files (x86)\Skype\Phone\;C:\Program Files\OpenSSH\bin;C:\Program Files\Amazon\AWSCLI\;E:\DevTools\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\WINDOWS\system32\con
fig\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Users\stephen\AppData\Loc
al\Programs\Python\Python35-32\Scripts\;C:\Users\stephen\AppData\Local\Programs\Python\Python35-32\;E:\DevTools\gradle-2.2\bin;E:\DevTools\viking-shell\bin;E:\DevTools\node_modules\npm\bin;E:\DevTools\
nodejs;E:\DevTools\apache-maven\bin;E:\DevTools\python;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\apache-maven\apache-maven-3.3.9\bin;C:\DevTools\gradle-2.10\bin;C:\Users\stephen\App
Data\Local\atom\bin;C:\Users\stephen\AppData\Local\Microsoft\WindowsApps;C:\DevTools\PostgreSQL\9.5\bin;C:\Users\stephen\AppData\Roaming\npm;C:\GTK\bin
OS=Windows_NT
PROCESSOR_REVISION=4601
CommonProgramW6432=C:\Program Files\Common Files
ComSpec=C:\WINDOWS\system32\cmd.exe
SSH_AUTH_SOCK=/tmp/ssh-YAYjDC5996/agent.5996
SystemRoot=C:\WINDOWS
TEMP=C:\Users\stephen\AppData\Local\Temp
HOMEDRIVE=C:
TMP=C:\Users\stephen\AppData\Local\Temp
VS110COMNTOOLS=E:\DevTools\C#\Common7\Tools\
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
NUMBER_OF_PROCESSORS=8

**Comment by zefie** [comment]
The error starts with
**Warning: Missing input files:**
**C:\GTK\bin\libfreetype-6.dll**

Did you extract the GTK zip on the wiki to C:\GTK? If you extracted it elsewhere you would have to manually update binding.gyp to set GTK_Root to the correct path, being sure to replace the backslash ("\") with a forward slash ("/"). 

An example, if you extracted it to your Downloads folder:
'GTK_Root%': 'C:/Users/stephen/Downloads/GTK',

**Comment by fstn** [comment]
ok  Sorry for that, I took Win32 GTK package instead of win64 one
