### ISSUE TITLE
Cannot install dependencies (Ubuntu)

### ISSUE THREAD

**Issue by WernerderChamp** [Automattic/node-canvas#883]
I tried to install the dependencies as described in the install guide, but I'm getting strange errors. On my other linux VM where I installed canvas a few weeks ago I did not got any errors.

Console Output:
`sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`

`The following packages have unmet dependencies:`
 `build-essential : Depends: libc6-dev but it is not going to be installed or`
 `                           libc-dev`
` g++ : Depends: g++-5 (>= 5.3.1-3~) but it is not going to be installed`
` libcairo2-dev : Depends: libfontconfig1-dev (>= 2.2.95) but it is not going to be installed`
`                 Depends: libfreetype6-dev (>= 2.1.10) but it is not going to be installed`
`                 Depends: libpng-dev`
`                 Depends: libglib2.0-dev but it is not going to be installed`
` libjpeg8-dev : Depends: libjpeg-turbo8-dev (>= 1.1.90+svn722-1ubuntu6) but it is not going to be installed`
` libpango1.0-dev : Depends: libfontconfig1-dev (>= 2.10.91) but it is not going to be installed`
`                   Depends: libfreetype6-dev but it is not going to be installed`
`                   Depends: libglib2.0-dev (>= 2.34.0) but it is not going to be installed`
`                   Depends: libxft-dev but it is not going to be installed`
`E: Unable to correct problems, you have held broken packages.`

I'm using Ubuntu 16.04 , same on my other VM.

**Comment by zbjornson** [comment]
Try running `sudo apt update` and then the install command again. Sounds like your package manager is out of date.

**Comment by WernerderChamp** [comment]
I still get the same error after doing this

**Comment by WernerderChamp** [comment]
guess I will delete the server and retry

**Comment by WernerderChamp** [comment]
No problems on Ubuntu 14.04

I hope it still works when I update the system again...

**Comment by zbjornson** [comment]
I install the dependencies a few times a week from scratch on Ubuntu 16.04 without problems, so I think you just got unlucky/in a broken state.

Your first error says `you have held broken packages`, so I think you needed to run `sudo apt-get autoremove` to purge those before trying again. There's more discussion here if it helps: http://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages

**Comment by WernerderChamp** [comment]
Setted up the server new, did work now
