### ISSUE TITLE
Unable to install on Windows with latest Node, NPM and node-gyp

### ISSUE THREAD

**Issue by JonWallsten** [Automattic/node-canvas#884]
I tried to install node-canvas@1.6.4 on Windows 10 with latest Node.js, NPM and node-gyp.
Node: 7.7.0
NPM: 4.4.0
node-gyp: 3.5.0

I have followed the instructions here:
https://github.com/Automattic/node-canvas/wiki/Installation---Windows
and 
https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

But could not get it to work. However installing with older version did work.
What I ended up with was:
Node 7.2.0
NPM: 3.10.9
node-gyp: 3.5.0

Is this a problem with node-canvas or with node/npm?

Install log:
```
C:\{my-folder-path}>npm i canvas

> canvas@1.6.4 install C:\{my-folder-path}\node_modules\canvas
> node-gyp rebuild


C:\{my-folder-path}\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
C:\{user}\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Cannot open include file: 'tracing/trace_event.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [C:\{my-folder-path}\node_modules\canvas\build\canvas.vcxproj]
  color.cc
C:\{user}\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Cannot open include file: 'tracing/trace_event.h': No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\{my-folder-path}\node_modules\canvas\build\canvas.vcxproj]
C:\{user}\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Cannot open include file: 'tracing/trace_event.h': No such file or directory (compiling source file ..\src\Canvas.cc) [C:\{my-folder-path}\node_modules\canvas\build\canvas.vcxproj]
  Image.cc
  ImageData.cc
  init.cc
C:\{user}\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Cannot open include file: 'tracing/trace_event.h': No such file or directory (compiling source file ..\src\CanvasGradient.cc) [C:\{my-folder-path}\node_modules\canvas\build\canvas.vcxproj]
  win_delay_load_hook.cc
C:\{user}\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Cannot open include file: 'tracing/trace_event.h': No such file or directory (compiling source file ..\src\ImageData.cc) [C:\{my-folder-path}\node_modules\canvas\build\canvas.vcxproj]
C:\{user}\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Cannot open include file: 'tracing/trace_event.h': No such file or directory (compiling source file ..\src\Image.cc) [C:\{my-folder-path}\node_modules\canvas\build\canvas.vcxproj]
C:\{user}\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Cannot open include file: 'tracing/trace_event.h': No such file or directory (compiling source file ..\src\init.cc) [C:\{my-folder-path}\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\{my-folder-path}\node_modules\canvas
gyp ERR! node -v v7.7.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\{my-folder-path}\node_modules\resolve\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "canvas"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\{my-folder-path}\npm-debug.log
```

**Comment by SrikanthGurunathan** [comment]
Unable to install canvas 

C:\Users\SrikanthG\AppData\Roaming\npm\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\SrikanthG\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not fo
und. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solu
tion". [C:\Users\SrikanthG\AppData\Roaming\npm\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\SrikanthG\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\InstalledSoftware\\nodejs\\node.exe" "C:\\Users\\SrikanthG\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\SrikanthG\AppData\Roaming\npm\node_modules\canvas
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\SrikanthG\AppData\Roaming\npm\node_modules\canvas\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\SrikanthG\AppData\Roaming\npm\node_modules\canvas\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\SrikanthG\\AppData\\Roaming\\npm\\node_modules\\canvas\\node_modules' }
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\InstalledSoftware\\nodejs\\node.exe" "C:\\Users\\SrikanthG\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "canvas"
npm ERR! node v7.4.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! canvas@1.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SrikanthG\AppData\Roaming\npm-cache\_logs\2017-03-02T08_29_17_175Z-debug.log

c:\Srikanth\Arimughamweb24012017>npm bugs canvas

**Comment by JonWallsten** [comment]
@SrikanthGurunathan:
Install VC++ Build Tools Technical Preview, choose Custom Install, and select both Windows 8.1 and Windows 10 SDKs.

**Comment by zbjornson** [comment]
@JonWallsten I think you hit this bug, which was just fixed:

https://nodejs.org/en/blog/release/v7.7.1/

**Comment by JonWallsten** [comment]
Sure seems so! Thanks for pointing it out.

**Comment by rahulserver** [comment]
Downloading VC++ Build Tools Technical Preview (wiht custom install) looks like a Life Sentence, if not capital punishment. 
For me its asking for 7GB of space. 

It would be great if we could use this package without having to use any native dependencies.

**Comment by rahulserver** [comment]
@zbjornson for me its not working even with node 7.7.1

**Comment by zbjornson** [comment]
@rahulserver try out [canvas-prebuilt](https://github.com/node-gfx/node-canvas-prebuilt): `npm install canvas-prebuilt`.
