### ISSUE TITLE
for windows

### ISSUE THREAD

**Issue by Jabinzou** [Automattic/node-canvas#885]
sorry i meet the same question,the installation on windows seems not success,i have read the steps told,but it seems not very useful!

**Comment by zbjornson** [comment]
Can you post some info about where things went wrong, what node version and what Windows version you've got?

**Comment by Jabinzou** [comment]
ok!
![2017-03-02_112714](https://cloud.githubusercontent.com/assets/14176629/23491750/3feac8a8-ff3b-11e6-806f-7c7a3854d6a3.png)
python 2.7.13,GTK:gtk+-bundle_2.24.10-20120208_win32. have been added in path

**Comment by zbjornson** [comment]
Looks like you might be behind a proxy. If you can't connect directly, check out the tips here: https://github.com/nodejs/node-gyp/issues/845#issuecomment-168169107.

**Comment by Jabinzou** [comment]
thanks,only i  have to set proxy,can i solve this?
At the same time,i have checked the npm config, i found that there is noting about http-proxy

**Comment by zbjornson** [comment]
If I'm not mistaken, the HTTP request that is failing is the one to download the node.js header files when node-gyp runs. I've never dealt with node behind proxies myself, so the best I can offer is to point you to what was suggested in the issue I linked to previously:

> download the appropriate source tarball from https://nodejs.org/dist/ and point npm / node-gyp to it with the --nodedir switch or the npm_config_nodedir environment variable.

or the other node-gyp issues that have to do with proxies: https://github.com/nodejs/node-gyp/issues?utf8=%E2%9C%93&q=is%3Aissue%20proxy

(Maybe someone else watching this repo has dealt with proxies and can help...)

**Comment by Jabinzou** [comment]
ok,thanks,
I'll try my best
