### ISSUE TITLE
node-gyp rebuild fails while installing popcorntime-desktop

### ISSUE THREAD

**Issue by githubdispostable** [Automattic/node-canvas#886]
This is the message is get:

```

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

I am on a Linux Mint 18 with xfce 64-bit (based on Ubuntu Xenial), 4.4.0-64-generic  x86_64 x86_64 x86_64 GNU/Linux

Attached in the npm debug file
[npm-debug.log.txt](https://github.com/Automattic/node-canvas/files/813666/npm-debug.log.txt)

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = new Canvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by RobertCorey** [comment]
you need to install dependencies, it'd be nice if this were included in the error logs
sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
