### ISSUE TITLE
Some lines but not others not being drawn on canvas when compiled as Android app

### ISSUE THREAD

**Issue by dvams** [Automattic/node-canvas#887]
## Issue or Feature
I'm currently converting an HTML/Javascript browser based tool into an Android app. I'm just about there, but there are just a couple of issues I'm having trouble with. 

At the end of the results page, a bell curve is shown with a vertical dotted line representing the current score. To the left of this line the curve is white, and to the right of this line the curve is grey. First the vertical line is drawn, then the bell curve is generated by the for-next loop. Finally the mean and standard deviation are displayed below the bell curve.

This works fine from a browser, but when I compile and install the app with the .apk file I get a problem: Though the vertical line and the mean and S.D. shows fine, something within the for-next loop is not working in the app version and the lines for the bell curve are not generated. I have attached a file showing how it works ordinarily (left) and then from within the app (right). 

When I put debug alerts in to check the values, the colours show the right values, and prob*7000 - which defines the height of the curve at each division - is showing correct values, starting low then rising to 200 or so then falling again throughout the iterations of the for-next loop (indicating that the gaussian function returns the correct values). But nothing is getting drawn! Why?

Another issue is that the app is not scaling itself to the tablet display, so I have to scroll around to operate controls that are off screen. 

![bell_error](https://cloud.githubusercontent.com/assets/26122889/23537853/cb33c186-ffc6-11e6-98b7-a992228cf4f9.jpg)

I'd really appreciate help (particularly the bell curve issue). I'm just stumped.  

## Steps to Reproduce
[requires library "gaussian.js"]

            var bell_filled = '#ffffff'; //Colour for filled part of bell curve
            var bell_unfilled = '#888888'; //Colour for unfilled part of bell curve
            {...}

            //Draw bell curve chart
            //We need to express the mean value on bell curve based on 
            //SD and mean for our sample: Default from validation study sample (n=46)
            //Set coordinates and length of curve display
            var bcx = 110
            var xlen = 280
            var bcy = 1120 //VERT

            //Display vertical marker for score
            context.strokeStyle = '#cccccc';
            context.lineWidth = 2;
            context.setLineDash([2, 2]);
            context.beginPath();
            context.moveTo(bcx + (sc_mean_7 * (xlen / 100)), bcy);
            context.lineTo(bcx + (sc_mean_7 * (xlen / 100)), bcy - 144);
            context.stroke();

            //Set the distribution and calculate percentage below x (D-VAMS mean)
            var distribution = gaussian(dist_mean, dist_sd * dist_sd);
            var perc = distribution.cdf(sc_mean_7)*100;

            //Loop to draw distribution  intervals of 0.25
            //alert('bell_filled' + bell_filled);
            //alert('bell_unfilled' + bell_unfilled);
            for (i = 0; i <= 100; i += 0.25) {

		//context.beginPath();
		context.strokeStyle = bell_filled;
                context.lineWidth = 2;
                context.setLineDash([0]);

                if (i >= sc_mean_7) {
                    //context.stroke();
                    context.strokeStyle = bell_unfilled;
                }

                var prob = distribution.pdf(i);
                context.beginPath();
                context.moveTo(bcx + (i * (xlen / 100)), bcy);
                context.lineTo(bcx + (i * (xlen / 100)), bcy - (prob * 7000));
                //TEST
                //alert(prob * 7000);
                context.stroke();
            }
            //End of bell curve code
            context.fillStyle = "white";
            context.font = "bold 22px Arial";

            //Display percentage on bell curve
            var text = (perc.toFixed(1) + '%');
            context.fillText(text, bcx, 1060); //VERT

            var text = ("Percentile"); //PERCENTILE
            context.fillText(text, bcx, 1148); //VERT
            
            context.font = "bold 20px Arial";
            var text = ("(x̅:" + dist_mean + "; σ:" + dist_sd + ")"); //PERCENTILE
            context.fillText(text, bcx+120, 1148); //VERT
            context.stroke();
// etc.
```

## Your Environment
* Browsers: Chrome/Firefox latest
* Android 6.0.1

**Comment by dvams** [comment]
I found the problem for the drawing issue. The problem line was:

context.setLineDash([0]);

Though this works fine in browsers, it was being interpreted as a null line by the Android app. This is fixed by changing it to:

context.setLineDash([]);

**Comment by chearon** [comment]
Interesting find, node-canvas should probably match browser behavior here. I'm not sure that it's really "wrong" either though. If you made a PR to fix it I'm sure it'd get accepted, although it was probably a simple fix on your end too.

**Comment by dvams** [comment]
Yes, it was easy to fix once I'd narrowed it down to that one line, - just tedious getting there. I'm new to this so don't know how to make a PR, but if you give me a link I'll do so.

The problem I'm having now is that the page is too big for the screen and I can't get it to automatically size to fill the display. I've detailed this here: 
[https://github.com/dvams/DVAMS/issues/1](url)

**Comment by asturur** [comment]
I guess the confunsion here is `compiled as an android App`.
What does it mean? are you using a transpiler to js --> java and you are using the android canvas instead of the webview canvas element?

**Comment by asturur** [comment]
also here

https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-set-dash

if all dashes are 0, you get an error state. I get if cairo refuse to stroke in that case.

**Comment by dvams** [comment]
I'm using PhoneGap connected to my GitHub repository. It compiles my app to an Android apk, and can also provide app install files for IOS and Windows Apps. Evidently, somewhere in that process it interprets that parameter differently and gives and error. My point is that browsers do not give an error with that code, but the app installed from the PhoneGap-compiled APK file does.

**Comment by asturur** [comment]
but why node-canvas? aren't phone gap app running in browser vewview?

**Comment by dvams** [comment]
I don't know.

**Comment by asturur** [comment]
i think this has been solved. I remember submitting a patch for this and has been merged.

**Comment by asturur** [comment]
pr #1060

**Comment by LinusU** [comment]
thx
