### ISSUE TITLE
Support image.src = <local path>

### ISSUE THREAD

**Issue by pannous** [Automattic/node-canvas#895]
to minimize friction, please make the constructor work as expected:
`new Image('path/to.jpg')`
 should handle the workflow 
` self.src=read_binary(path) `

**Comment by LinusU** [comment]
related: https://github.com/Automattic/node-canvas/issues/833

**Comment by pannous** [comment]
OK at least `img.src=path` should load and create that Image from the binary file

**Comment by zbjornson** [comment]
`img.src = <local file path>` already works -- for example:

https://github.com/Automattic/node-canvas/blob/b10d204c69a63b7d5c6f1c60ad30a67a51bc7167/examples/kraken.js#L15

If it's saying `img.complete == false` forever, there's probably an error happening; check if `img.onerror` is called.
