### ISSUE TITLE
live text, fonts in pdf creation

### ISSUE THREAD

**Issue by korenfine** [Automattic/node-canvas#896]
hi,
I've got canvas with few elements and i want to make pdf file from it.
I've been able to create the pdf from the canvas but i don't get the live text and fonts in the pdf.

this is my code:
var filename = uuid.v4() + '.pdf';
    var path = '/' + site + '/' + filename;

    var out = fs.createWriteStream(__dirname + path);

    var canvas = fabric.createCanvasForNode(designWidth, designHeight,'pdf');
    canvas.loadFromJSON(jsonStr, function () {
      canvas.renderAll.bind(canvas);
      canvas.backgroundColor = backgroundColor;
      zoomCanvas(width / designWidth);

      out.write(canvas.nodeCanvas.toBuffer(), function (err) {
        if (err) throw err
      });
    });

working on:
node-canvas v5.3.2
node v4.2.6

tnx

**Comment by kaelzhang** [comment]
Same issue

## Env
node-canvas 1.6.2
node 7.9.0

## How to reproduce

```js
const canvas = new Canvas(100, 100, 'pdf')
const ctx = canvas.getContext('2d')
ctx.font = '20px Helvetica'
ctx.fillText('hello', 10, 10)
ctx.addPage()

canvas.pdfStream().pipe(fs.createWritableStream('hello.pdf'))
```

Then there is nothing in hello.pdf.

**Comment by zbjornson** [comment]
Set `ctx.textDrawingMode = "glyph"`. See https://github.com/zbjornson/node-canvas/tree/readme#canvasrenderingcontext2dtextdrawingmode.
