### ISSUE TITLE
'document is not defined' in units-css/lib/utilities.js

### ISSUE THREAD

**Issue by lucaspenney** [Automattic/node-canvas#898]
It looks like commit #3d545056e2bb61b25f2d8bb1445c2e424a615163 that brought in units-css seems to break a fresh install for me, giving the following error:

```
ReferenceError: document is not defined
at /var/www/Project/node_modules/units-css/lib/utilities.js:114:43
```

I tried on multiple different node versions before realizing a recent commit was the issue - rolling back to the previous version seemed to fix it.

**Comment by chearon** [comment]
Wow that's not good, there should be no references to `document` in canvas... Was it a specific type of unit you were using that triggered this like `em`?

**Comment by lucaspenney** [comment]
I'm rendering CanvasJS server side so I'm not sure specifically where it fails without digging into it's code, but it looks like the units library is intended to only run in a browser. It looks like others experienced this and [created an issue](https://github.com/alexdunphy/units/issues/2) with the units library.

**Comment by LinusU** [comment]
Oh, this is not good... I'm currently on vacation and have very limited internet and time to devote to this...

Is it a speechify can unit that triggers it, it seems like the tests where working, maybe we missed something 🤔

**Comment by LinusU** [comment]
Hmm, it seems like this is only for the `rem` unit, I wonder how that unit worked before...

**Comment by chearon** [comment]
The regex didn't even match `rem`, it would have had no effect on the context I think... could add a test for that and bring back the old behavior. #899 seems much worse but I haven't had a chance to try to reproduce it yet

**Comment by zbjornson** [comment]
The dependency that caused this was removed a few weeks ago. Are you still having this problem with 2.0.0-alpha.5?

**Comment by LinusU** [comment]
Hmm, this is probably still a problem in 1.x 🤔 

If anyone wants to backport #944 to 1.x I'd be happy to merge it :)

**Comment by saschagehlich** [comment]
@LinusU I'm having a similar issue with 1.6.7, units-css seems to do some DOM stuff:

```js
/Users/saschagehlich/development/node/node-videorenderer/node_modules/units-css/lib/utilities.js:39
  parent.appendChild(element);
         ^

TypeError: Cannot read property 'appendChild' of undefined
```

I see that the units-css dependency has been removed lately, but 1.6.8 or 1.7 have not been released yet. Any ETA on the release? Current 1.6.7 is basically broken.

**Comment by zbjornson** [comment]
v1.6.8 was released on Dec 12. @saschagehlich let us know if you're still having issues after updating.
