### ISSUE TITLE
drawImage(video)

### ISSUE THREAD

**Issue by deniszgonjanin** [Automattic/node-canvas#90]
Currently it's not possible to feed a video source to node-canvas.
For some background, see: http://html5doctor.com/video-canvas-magic/

I understand this is probably impossible now, as you can't load videos with cairo and send them to the canvas frame by frame. It would be possible with something like ffmpeg, but it would make node-canvas very heavy.

The use cases for this are simple ways to do video and image editing on the server side, or creating video editing applications that run in the browser, with html5, where the edited videos are then saved on the server.

If anyone has any clever ideas on loading videos into node-canvas, please discuss.

**Comment by LinusU** [comment]
I think that this is outside the scope of this package, and would probably be best supported by a separate package...
