### ISSUE TITLE
does not compile on Windows 10 using --with_pango

### ISSUE THREAD

**Issue by dboleslawski** [Automattic/node-canvas#901]
i think after fighting with this problem for hours I need another pair of eyes looking at this to tell me i'm not going crazy

## Issue or Feature
trying to compile node-canvas with pango throws a bunch of error about not finding the file `pango/pangocairo.h` although it is located at `C:\GTK\include\pango-1.0\pango`

## Steps to Reproduce
node-gyp rebuild --with_pango

`...`
`c:\users\user\desktop\node-canvas-test\node_modules\canvas\src\Canvas.h(17): fatal error C1083: Cannot open include file: 'pango/pangocairo.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [C:\Users\user\Desktop\node-canvas-test\node_modules\ca
nvas\build\canvas.vcxproj]`
`... and so on`

## Your Environment
* Version of node-canvas: 1.6.5
* Environment: node.js v6.10.1 on Win 10 (installed using nvm-windows)

all help is greatly appreciated

**Comment by chearon** [comment]
I think the Windows build is hard-coded not to use Pango, did you edit the `binding.gyp`?

**Comment by dboleslawski** [comment]
yep, `binding.gyp` also includes conditions about pango for windows, although comments are dropped about freetype not running on win

maybe the `binding.gyp` is missing some lines to get the including of pango running. sadly im not too familiar with compiling on win to get this running..

**Comment by chearon** [comment]
I've done it before but I don't remember the details, I don't think passing `--with-pango` does anything, though, you need to have the `WITH_PANGO` macro set to enable the relevant sections of code. And then you have to the `.lib` files for Pango and all of its dependencies (there are several) to the gyp file.

This is why I made [canvas-prebuilt](https://github.com/chearon/node-canvas-prebuilt), which does have a windows Pango build by default

You can also try the [MSYS install](https://github.com/Automattic/node-canvas/wiki/Installation---Windows-%28with-MSYS2%29) but I didn't put all of the Pango details in there

**Comment by zbjornson** [comment]
This was fixed in 2.x 🚀
