### ISSUE TITLE
drawText renders text in wrong location on scaled Canvas

### ISSUE THREAD

**Issue by mvitale** [Automattic/node-canvas#903]
## Issue

After calling scale(scaleFactor, scaleFactor) on a Canvas instance that has been resized accordingly, text is drawn in the wrong location.
## Steps to Reproduce

```js
var fs = require('fs')
  , Canvas = require('canvas')
  , origCanvas = new Canvas(100, 100)
  , doubleCanvas = new Canvas(200, 200) // 2x size of origCanvas
  , origCtx = origCanvas.getContext('2d')
  , doubleCtx = doubleCanvas.getContext('2d')
  , origOut = null
  , origStream = null
  , doubleOut = null
  , doubleStream = null
  ;

doubleCtx.scale(2, 2); // Scale by factor of 2

draw(origCtx);
draw(doubleCtx);

origOut = fs.createWriteStream(__dirname + '/orig.png');
origStream = origCanvas.pngStream();
doubleOut = fs.createWriteStream(__dirname + '/double.png');
doubleStream = doubleCanvas.pngStream();

origStream.on('data', function(chunk) { origOut.write(chunk) });
origStream.on('end', function() { console.log('saved orig') });
doubleStream.on('data', function(chunk) { doubleOut.write(chunk) });
doubleStream.on('end', function() { console.log('saved double') });


function draw(ctx) {
  ctx.fillStyle = '#ddd';
  ctx.fillRect(0, 0, 100, 100);

  ctx.beginPath();
  ctx.strokeStyle = '#000';
  ctx.moveTo(0, 50);
  ctx.lineTo(100, 50);
  ctx.stroke();

  ctx.fillStyle = '#000';
  ctx.font = '18px Helvetica';
  ctx.fillText('test', 10, 48);
}
```

### orig.png
![orig](https://cloud.githubusercontent.com/assets/296803/24979604/da8a06f8-1fa2-11e7-8fe0-3aeae99adfec.png)

### double.png
![double](https://cloud.githubusercontent.com/assets/296803/24979616/e34dec8c-1fa2-11e7-985d-aa4fbc4df355.png)

I have verified that this is not the behavior in my browser (tested on Chrome ).

## Environment
* Version of node-canvas: 1.6.5
* Environment: Node v6.9.2 on macOS 10.12.3

**Comment by LinusU** [comment]
This should be fixed in version 1.6.6 🙌

**Comment by mvitale** [comment]
Awesome!

**Comment by mvitale** [comment]
Oddly, this is now working for me on macOS, but is broken on CentOS 7. Here is the visual test output (I tried both master and v1.x builds, with the same result. This is from up-to-date master.):

![image](https://user-images.githubusercontent.com/296803/32298677-49b3629c-bf29-11e7-9748-a010991990db.png)

If I rebuild with the yScale coefficient removed from this line
```
  case TEXT_BASELINE_BOTTOM:
    return ((pango_font_metrics_get_ascent(metrics) + pango_font_metrics_get_descent(metrics)) / PANGO_SCALE) * yScale;
```

so that it is just

```
  case TEXT_BASELINE_BOTTOM:
    return ((pango_font_metrics_get_ascent(metrics) + pango_font_metrics_get_descent(metrics)) / PANGO_SCALE);
```

the test output looks correct.

**Comment by zbjornson** [comment]
Weird... Works on MacOS and Windows, borked on CentOS 7 and Ubuntu 16.

The fact that removing `yScale` fixes it I think is coincidence. The value of `yScale` is the same on Windows and Ubuntu, and the upstream transform matrix values are likewise correct.

The `PangoFontMetrics` look suspiciously different though:

```
ascent, descent, PANGO_SCALE, yScale
// 1x scale
  19456,   5120, 1024,   1 Linux
  19456,   4096, 1024,   1 Win
// 0.1x scale
 194559,  51199, 1024, 0.1 Linux
1945599, 409599, 1024, 0.1 Win
```

Going from 1x to 0.1x on Linux is a 10x change; on Windows and MacOS it's a 100x change.

Fontstuffs are out of my area of expertise to help more, unfortunately. Caleb's good with this stuff if he has time.

**Comment by mvitale** [comment]
Yeah, I thought the 100x change was suspicious. If it's correct, then the yScale adjustment is likely also correct, but if the 10x change (which seems more correct intuitively, since the canvas is being scaled by a factor of 10) is, then the yScale adjustment is likely incorrect. Unfortunately, I don't have any expertise in this area either.

**Comment by mvitale** [comment]
FWIW, I've tracked the difference in behavior down to the `pango_cairo_update_layout(_context, _layout);` call in Context2d::setTextPath. On CentOS there is a small change:

```
ascent before cairo update: 185344
descent before cairo update: 43008
ascent after cairo update: 184319
descent after cairo update: 40959
```

But on macOS there is a 10x change:
```
ascent before cairo update: 185400
descent before cairo update: 43400
ascent after cairo update: 1853989
descent after cairo update: 433989
```
