### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Yording** [Automattic/node-canvas#905]
Hi, i have issue when require 'canvas' in my app

## Issue or Feature
Error: Cannot find module '../build/Release/canvas' from 'C:\Users\yording\proyectos\machine-learning\proyectos\predictionjs\node_modules\canvas\lib'
[1]     at C:\Users\yording\proyectos\machine-learning\proyectos\predictionjs\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
[1]     at load (C:\Users\yording\proyectos\machine-learning\proyectos\predictionjs\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
[1]     at onex (C:\Users\yording\proyectos\machine-learning\proyectos\predictionjs\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
[1]     at C:\Users\yording\proyectos\machine-learning\proyectos\predictionjs\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
[1]     at FSReqWrap.oncomplete (fs.js:123:15)

## Steps to Reproduce
var Canvas = require('canvas');

## Your Environment
* Version of node-canvas: 1.6.0
* Environment: node 6.10.0 on Windows 10 x64

**Comment by LinusU** [comment]
Did you get any errors when installing canvas?

**Comment by Yording** [comment]
@LinusU only warnings

**Comment by rbpinheiro** [comment]
Getting the same error on OSX Yosemite.

**Comment by rbpinheiro** [comment]
When installing with yarn it didn't trigger the node-gyp build process. After installing with npm it worked as expected.

**Comment by Alcasser** [comment]
I'm having this issue... I am working on an Ionic 2 app.
I'm on OSX Sierra.
After installing CamanJS I get canvas@1.6.5 dependency installed with no errors and the node-gyp rebuild is performed with the output:
```
SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
  SOLINK_MODULE(target) Release/canvas.node
```
If I "ls" the content of the folder node_modules/canvas/build/Release, I get:
canvas-postbuild.node
canvas.node          
obj.target

But when using the import " import { Caman } from 'caman' " I get the error:

Cannot find module "../build/Release/canvas"

Thanks.

**Comment by ManuChalela** [comment]
I try on **Lubuntu 16.04**, **Node 8.2.1** **npm 5.3.0** and don't find the module too. How to solve this? Thanks.

**Comment by LinusU** [comment]
We have added `.node` to the require path, could you all try with version **1.6.6** of node-canvas?
