### ISSUE TITLE
Adding on some more maintainers

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#914]
@zbjornson and @chearon have been doing an awesome job and submitted some great pull requests. We have talked about them helping me maintain canvas and I think it would be great 🙌 

Would it be possible for someone to add them to the repo? ping @TooTallNate 

🎉 😄

**Comment by TooTallNate** [comment]
👍

**Comment by dmsnell** [comment]
Added both! Thanks all for your hard work and patience with us on this! Thanks as well @TooTallNate for your legacy of useful libraries!

**Comment by zbjornson** [comment]
Woohoo, thank you 😀
