### ISSUE TITLE
Help me! installing canvas on window 7 64bit

### ISSUE THREAD

**Issue by lamtv36** [Automattic/node-canvas#919]
I'm trying to install canvas on window 7 64bit but i  encountered fail.
please help me resove this problem..
thanks

C:\Users\lamtv3\Desktop\vuejs_sample\FloatWindow>npm install canvas
> canvas@1.6.5 install C:\Users\lamtv3\Desktop\vuejs_sample\FloatWindow\node_modules\canvas
> node-gyp rebuild

C:\Users\lamtv3\Desktop\vuejs_sample\FloatWindow\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\bin\node
Traceback (most recent call last):
  File "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1900, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2010--global'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lamtv3\AppData\Roaming\nvm\v7.1.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lamtv3\\AppData\\Roaming\\nvm\\v7.1.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lamtv3\Desktop\vuejs_sample\FloatWindow\node_modules\canvas
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lamtv3\Desktop\vuejs_sample\FloatWindow\npm-debug.log

**Comment by wagenaartje** [comment]
Same problem here...

**Comment by zbjornson** [comment]
> KeyError: '2010--global'

That's supposed to be your detected MSVS version, but it looks like there was some issue detecting the correct one, or the command was invoked as `npm install canvas --msvs_version=2010--global` with a space missing, or something.

If you still need help, leave a comment and I'll reopen the issue.
