### ISSUE TITLE
Memory leak in version 2.0

### ISSUE THREAD

**Issue by azangru** [Automattic/node-canvas#922]
Hi!

I have come across what seems to be a memory leak in `node-canvas` version 2. I've put together a very basic repro case that you can find in [this repo](https://github.com/azangru/node-canvas-testing).

Briefly, the problem manifests like this:

- Start an app that uses node-canvas v.2
- Send multiple requests to it
- Observe the memory usage. Specifically, the `rss` portion of `process.memoryUsage` is quickly increasing despite garbage collection.

For example, in my repro case, the memory usage that started with:

```
{"rss":72290304,"heapTotal":21008384,"heapUsed":11065680}
```

rose after a 1000 requests to:

```
{"rss":643870720,"heapTotal":17862656,"heapUsed":11048840}
```

(notice the rise in `rss`).

This memory leak is not present in the 1.x branch of `node-canvas`.

I tried both `.pngStream()` and `.toBuffer()` methods in my repro case (since there is an issue regarding memory leaks with `pngStream`). None of this helped.

If you could suggest the place in the version 2 branch that is free from this leak, I would be super grateful. I've used the master branch of `node-canvas` in production this winter, and it seems like there was no such bug then.

**My environment:**
MacOS v. 10.11.6
node v6.7.0

**P.S.:** I have not bisected the git history to find the exact commit that has introduced the leak, but at least at the time of [this March commit](https://github.com/Automattic/node-canvas/tree/3d545056e2bb61b25f2d8bb1445c2e424a615163) memory seems to be managed fine.

**Comment by zbjornson** [comment]
Thanks for the nice repro case. I can try to look at this within the next week, but if anyone else gets to this before me, go ahead please!
