### ISSUE TITLE
npm install canvas removes Jest, why?

### ISSUE THREAD

**Issue by ChrisGitter** [Automattic/node-canvas#924]
I just want to know why Jest ist removed by the installation of Canvas.

- there were no errors and I have all the build tools installed

- my packages were all installed via Yarn

- only canvas was installed (and built) via `npm install canvas --save-dev`

`+ canvas@1.6.5
removed 1105 packages and updated 15 packages in 52.387s`

**Comment by LinusU** [comment]
This seems like a bug that should be opened on the npm repo. Is `yest` in your package.json?
