### ISSUE TITLE
problem with installation with jpeg support on windows 64 systems

### ISSUE THREAD

**Issue by maltekosian** [Automattic/node-canvas#932]
in binding.gyp the include path to libjpeg-turbo64 is missing
installation fails with jpeg support, though it seems to work generally
once fixed and running 
>> node-gyp rebuild --GTK_Root=C:\GTK --jpeg_root=C:\libjpeg-turbo64 --msvs_version=2015 --with-jpeg
the jpeg.lib is demanded from C:\GTK\lib , but it is still part of the libjpeg-turbo64

## Window 7 | 10 64x
* Version of node-canvas 8.1.3

**Comment by zbjornson** [comment]
The include path is added further down in binding.gyp, [here](https://github.com/Automattic/node-canvas/blob/master/binding.gyp#L143-L160).

What's your output for `node ./util/win_jpeg_lookup.js` (run from the root of the canvas directory)?

I don't quite understand the second part of your message. Does `node-gyp rebuild` without any other arguments work? Or is it only working when you add those arguments?

**Comment by maltekosian** [comment]
It does not work anyway. After rebuilding with node-gyp node does not find the installation of node-canvas. And there is no jpeg support. 
I#m working with the latest version of node 8.x and the latest master of (node-)canvas

**Comment by maltekosian** [comment]
doing node-gyp rebuild --with-jpeg leads to jpeglib.h not found.

**Comment by zbjornson** [comment]
If you're installing node-canvas as a dependency and it fails to build, npm will delete the node-canvas directory. To troubleshoot it's easier to clone this repo.

As long as you have libjpeg-turbo installed in `C:\`, and you've matched the architecture (x86 vs x64), then `npm install` from inside the cloned directory with no arguments should work. The `--with-jpeg` flag is unnecessary. If it doesn't work, please post the output from `node ./util/win_jpeg_lookup.js` run from the cloned directory.

**Comment by cnTomato** [comment]
the same problem

`
$ npm install

> electron@1.7.13 postinstall E:\github\process-excel\node_modules\electron
> node install.js


> sheetjs-electron@0.0.1 install E:\github\process-excel
> node-gyp rebuild


E:\github\process-excel>if not defined npm_config_node_gyp (node "C:\Users\panfan.CMBI\AppData\Roaming\nvm\v8.9.3\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:538
    throw err;
    ^

Error: Cannot find module 'E:\github\process-excel\util\win_jpeg_lookup'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
gyp: Call to 'node ./util/win_jpeg_lookup' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\panfan.CMBI\AppData\Roaming\nvm\v8.9.3\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\panfan.CMBI\\AppData\\Roaming\\nvm\\v8.9.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\github\process-excel
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sheetjs-electron@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sheetjs-electron@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\panfan.CMBI\AppData\Roaming\npm-cache\_logs\2018-04-10T02_26_05_265Z-debug.log

`

**Comment by cnTomato** [comment]
solved while download folder(src & util) then move to root of project

but a new problem as below
![image](https://user-images.githubusercontent.com/12791216/38533309-494944a2-3cab-11e8-8e6a-bafdaef46e58.png)

``
