### ISSUE TITLE
Move PNG_* constants to constructor, clean up toBuffer API

### ISSUE THREAD

**Issue by zbjornson** [Automattic/node-canvas#934]
Proposal for a breaking change in 2.0: move all the `PNG_*` constants from the Canvas prototype to be static members of the Canvas constructor. That is, this doc example:

```js
var buf2 = canvas.toBuffer(undefined, 3, canvas.PNG_FILTER_NONE);
```

would become

```js
var buf2 = canvas.toBuffer(undefined, 3, Canvas.PNG_FILTER_NONE);
```

The constants were added in https://github.com/Automattic/node-canvas/commit/14d9f587b6106dd900cabe0d6bc31117acb596c6. @kkoopa you added these -- do they need to be on the prototype?

**Comment by kkoopa** [comment]
I do not believe that they need to be on the prototype. The third argument was added in a strange backwards-compatible way, and you pass undefined first only in this case, so you can consider cleaning it up now.

**Comment by zbjornson** [comment]
I think this would be the wrong direction after all. If the Canvas spec ever gets an equivalent property, it won't be on the Canvas constructor, because there is no Canvas constructor. :)

Fine as-is methinks.
