### ISSUE TITLE
Stream Canvas To Backend

### ISSUE THREAD

**Issue by schuesslerf** [Automattic/node-canvas#936]
Hello,

just want to be sure that this is the right thing to go with. I'm trying to have a canvas where I can draw in and stream this canvas surface (so the drawings) into my backend (to then process it with ffmpeg for example) or directly send it as a udp stream to receive it with mpv or something like that.

Is this possible with node-canvas?

**Comment by Devidian** [comment]
Just a code snippet from my actual code (my original code is a bit bigger but just to give you a shot example)

```
var proc = spawn('ffmpeg',['-i','pipe:0','output.mp4'] );
let canvas = new Canvas(1920, 1080);
let imageStream = canvas.syncJPEGStream({
    bufsize: 4096,
    quality: 100,
    progressive: false
});

imageStream.on('data', (chunk) => {
    if (proc.stdin.writable) {
        proc.stdin.write(chunk);
    } else {
        console.log('Error: ffmpeg stdin closed!');
    }
});
imageStream.on('end', () => { });
imageStream.on('error', (err) => {
    console.log('ErrorOn_endAnimation', err.toString());
});
```

after the last frame streamed to ffmpeg you must close stdin or ffmpeg will wait for more. Currently i'm looking for a solution to get ffmpeg start rendering while receiving frames and not after stdin is closed, to save some time (currently rendering 20s video in 6 formats takes me ~1:10min, where the first 40s is node and the last 30s is ffmpeg taking)

Just a tip, don't use pngStream as it takes ~ 4-5 times more time.

**Comment by mario-jerkovic** [comment]
@Devidian Did you find a solution on how to get ffmpeg to start rendering while receiving frames?

**Comment by Devidian** [comment]
I noticed that the issue doesnt occure in My wsl Debian 9 test Setup. The Same Video Takes 40 seconds node time and only 2 seconds ffmpeg where it takes 40/20 on our Server with CentOS 7.

But i really dont have a solution yet to fix this in CentOS

// Sry for spelling issued, german t9 is the bad guy :-P

**Comment by zbjornson** [comment]
Using streams is probably making things significantly worse. I'd try just `canvas.toBuffer("image/jpeg")` instead, and pipe those full frames to ffmpeg.
