### ISSUE TITLE
JPEG errors not being caught correctly, node process hard exits

### ISSUE THREAD

**Issue by jhuckaby** [Automattic/node-canvas#938]
When node-canvas encounters an error loading a JPEG, `onerror` is not fired.  Instead, the entire Node.js process suddenly exits with a message printed to the console, which I cannot catch or control.

Example "broken" JPEG with some bad bytes after the header: 
https://pixlcore.com/temp/bad.jpg

Sample code:

```js
var Canvas = require('canvas');
var Image = Canvas.Image;
var img = new Image();

img.onerror = function (err) {
	console.error("CAUGHT ERROR!  img.onerror = " + err);
}

img.onload = function () {
	console.log("Loaded!  Image Dimensions: " + img.width + " x " + img.height);
}

img.src = "bad.jpg";
```

The problem here is that when loading the [bad.jpg](https://pixlcore.com/temp/bad.jpg) image, neither `onload` nor `onerror` fires.  Instead, the entire Node.js process simply exits with this message in my console / terminal:

```
Bogus Huffman table definition
```

The expected behavior for any bad image is for `onerror` to fire, so I can catch the error and provide proper error handling / bubbling in my application.

## My Environment
node-canvas 1.6.5
cairo 1.14.10
jpeg 8d
node v6.9.1
OS X 10.12.5

**Comment by jhuckaby** [comment]
Here's a GZIPed version of the corrupted image, if you have trouble downloading the direct JPEG link: pixlcore.com/temp/joe-corrupted.jpg.gz

**Comment by thenickdude** [comment]
I can confirm this is now fixed in HEAD:

```
CAUGHT ERROR!  img.onerror = Error: error while reading from input stream
```

**Comment by jhuckaby** [comment]
Thanks guys!

**Comment by jhuckaby** [comment]
@LinusU Wonderful, thank you!  I have yet to move over to the 2.x branch, so thank you very much for the backport!
