### ISSUE TITLE
ctx.measureText() ends the whole node.js process

### ISSUE THREAD

**Issue by camer0** [Automattic/node-canvas#941]
## Issue or Feature

So when I run ctx.measureText('some text') a few times (via a command in discord) it eventually exits the script with absolutely no error. No uncaught errors, nothing. 

## Steps to Reproduce

```js
for (i = 0; i < 41; i++) {
        var prev = i - 1
        ctx.font = prev + 'px futura';
        var tm = ctx.measureText(author).width
        if (tm + 165 < 500) {
          fontsize = i
        }
      }
```
where author is the username of the discord user, defined in previous code

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Windows

**Comment by zbjornson** [comment]
I can't reproduce this. Does it happen with fonts other than "futura"? I don't have that installed, and as far as I see that's the only difference in our setups.

(What version of node are you using? Shouldn't matter but to rule stuff out.)
