### ISSUE TITLE
Possible memory leak in 2.0.0-alpha.2

### ISSUE THREAD

**Issue by geuis** [Automattic/node-canvas#954]
## Issue or Feature
Memory grows continuously when creating new canvas instances.

## Steps to Reproduce
```js
const Canvas = require('canvas');

setInterval(() => {
  const mem = process.memoryUsage();
  
  for (let m in mem) {
    let str = mem[m].toString().split('').reverse().join('')
      .match(/.{1,3}/g).join(',').split('').reverse().join('');
    console.log(`${m}: ${str}`);
  }
  console.log('\n');

  new Canvas(1920, 1080);
}, 1000);
```

Sample output:

```
rss: 33,083,392
heapTotal: 9,428,992
heapUsed: 5,247,120
external: 49,212


rss: 34,004,992
heapTotal: 10,477,568
heapUsed: 6,012,352
external: 16,638,012


rss: 34,009,088
heapTotal: 10,477,568
heapUsed: 6,024,584
external: 33,226,812


rss: 34,009,088
heapTotal: 10,477,568
heapUsed: 6,034,480
external: 49,815,612


rss: 34,009,088
heapTotal: 10,477,568
heapUsed: 6,043,792
external: 66,404,412


rss: 34,082,816
heapTotal: 10,477,568
heapUsed: 6,053,544
external: 82,993,212


rss: 34,082,816
heapTotal: 10,477,568
heapUsed: 6,063,328
external: 99,582,012


rss: 34,324,480
heapTotal: 7,331,840
heapUsed: 5,204,784
external: 66,404,412


rss: 50,913,280
heapTotal: 7,331,840
heapUsed: 5,220,184
external: 82,993,212


rss: 67,514,368
heapTotal: 7,331,840
heapUsed: 5,236,936
external: 99,582,012


rss: 84,156,416
heapTotal: 7,331,840
heapUsed: 5,254,304
external: 116,170,812


rss: 84,168,704
heapTotal: 7,331,840
heapUsed: 5,276,168
external: 132,759,612


rss: 84,197,376
heapTotal: 7,331,840
heapUsed: 5,285,936
external: 149,348,412


rss: 84,197,376
heapTotal: 7,331,840
heapUsed: 5,298,984
external: 165,937,212
```

## Your Environment
* Version of node-canvas: 2.0.0-alpha.2
* Environment: node 8.1.2, Mac OS X 10.12.5

**Comment by zbjornson** [comment]
This was (hopefully) fixed in 5889663f55c6721665bfb28e55431d5ed733d713, but a release hasn't been tagged since that was merged.

**Comment by geuis** [comment]
@zbjornson that's good to hear. Any chance of getting a tag tomorrow?

**Comment by zbjornson** [comment]
*summons @LinusU* ⬆️ 

(Alternatively maybe you could install from github directly for the moment.)

**Comment by zbjornson** [comment]
@geuis `canvas@v2.0.0-alpha.3` is now published to npm, including the referenced fix.

**Comment by geuis** [comment]
@zbjornson Wondering if you can comment on this. When I re-run the test code I shared in the comments of the issue I'm now seeing negative external memory being reported after a few seconds. Not sure what this means.


![mem-mov](https://user-images.githubusercontent.com/53883/29887528-948c78fa-8d72-11e7-9ea1-22f93faa0431.gif)

**Comment by zbjornson** [comment]
Hrm. Will take a look sometime soon. Guessing that happens after the GC runs, and might be a signed/unsigned issue again. (This isn't really a harmful issue btw -- that amount is only used for hinting when the v8 GC should run.)

**Comment by geuis** [comment]
Sounds good. This is a huge fix for us. Thanks for the hard work.

**Comment by zbjornson** [comment]
No problem! Opened #979 for the issue you found above.
