### ISSUE TITLE
Building package failed while npm install

### ISSUE THREAD

**Issue by rhysd** [Automattic/node-canvas#956]
## Issue

`npm install canvas` causes an error with below error message:

```
> canvas@1.6.6 install /Users/rhysd/Develop/github.com/rhysd/neovim-component/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
```

I investigated a bit for this. `jpeglib.h` exists in `/usr/local/include` or `/usr/local/Cellar/jpeg/8d/include` (`/usr/local/include` is a symlink), but compiler cannot find it. I tried `export CXX="g++ -I/usr/local/include -L/usr/local/lib` and build was done successfully. I guess include path is not set properly.

## Steps to Reproduce

1. `$ brew install pkg-config cairo pango libpng jpeg giflib`
2. `$ npm install node`

## Your Environment
* Version of node-canvas: 1.6.6
* Environment: node 6.10.3 (npm 3.10.10) on macOS 10.12

**Comment by chearon** [comment]
macOS won't compile against `/usr/local` until you run `xcode-select --install`, did you do that?

See [this](https://stackoverflow.com/questions/32898887/boost-no-longer-works-with-homebrew-on-mac-el-capitan/32929012#32929012) and #927

**Comment by rhysd** [comment]
I'll check it on next Wednesday. I'm sorry for making you wait.

**Comment by rhysd** [comment]
I confirmed `xcode-select --install` fixed this problem. Thank you for guiding me. In my environment, Xcode was already installed and I thought CommandLineTools was already installed. But CommandLineTools is a separated module from Xcode and I needed to install it separately.
