### ISSUE TITLE
Canvas.registerFont is not a function (2.0.0)

### ISSUE THREAD

**Issue by kyranet** [Automattic/node-canvas#960]
## Issue or Feature
`Canvas.registerFont` is not a function.

Additionally, the REPL returns this:
```js
> require('canvas');
{ parseFont: [Function],
  createCanvas: [Function],
  createImageData: [Function],
  loadImage: [Function] }
```

## Steps to Reproduce
```js
const Canvas = require('canvas');
const { resolve } = require('path');
Canvas.registerFont(resolve('C:\Users\kyra\assets\fonts\Roboto-Bold.ttf'), { family: 'Roboto' });
```

## Your Environment
* Version of node-canvas: `canvas@2.0.0-alpha.2  (github:Automattic/node-canvas#947f3a43a816e3f3a16e099ea04c459323335079)`
* Environment: Node 7.3.0 on Windows 10 Pro (Creators Update).

**Comment by zbjornson** [comment]
Candidate fix in #943.

**Comment by kyranet** [comment]
I have downloaded your branch and seems to be working perfectly, thanks!
![image](https://user-images.githubusercontent.com/24852502/29357236-1c4cd4b2-8277-11e7-884a-08e800f5552a.png)

**Comment by LinusU** [comment]
Fixed in `v2.0.0-alpha.3` 🎉

**Comment by kyranet** [comment]
@zbjornson I saw #943 got merged and has breaking changes, I assume that it's:

```javascript
const { createCanvas, Image, registerFont } = require('canvas');
registerFont('Roboto.ttf', { family: 'Roboto' });
const bg = new Image();
const canvas = createCanvas(x, y);
// ...
```

As opposed to:

```javascript
const Canvas = require('canvas');
Canvas.registerFont('Roboto.ttf', { family: 'Roboto' });
const bg = new Canvas.Image();
const canvas = new Canvas(x, y);
// ...
```

Right?

**Comment by zbjornson** [comment]
@kyranet yes, that's correct! (All the examples in README.md and the examples directory should be updated now to reflect that as well.)
