### ISSUE TITLE
requestAnimationFrame()

### ISSUE THREAD

**Issue by piranna** [Automattic/node-canvas#965]
Make backends to offer a `requestAnimationFrame()` function optimized for each one of them (or defaulting to `setTimeout()` with 16ms, or `setInmediate()` or `setTimeout()` with 0ms to allow several contexts switches for full offscreen rendering backends like image or PDF) so drawing routines and animtions would stick to them without wating CPU resources or need to do hacks to improve performance.

**Comment by asturur** [comment]
I'm a loosy follower of the project.
requestAnimationFrame is not a canvas api.
I do not see the point of requesting an animation frame in a command line context where there is no screen to wait the refresh for.

using request animation frame to do not hog your cpu with a continuous drawing looks like more an application task that something that a canvas backend library should provide.

Just my opinion, take no offense.

**Comment by piranna** [comment]
`node-canvas` now supports several backends, with the explicit intention of drawing to screen surfaces. Although unmerged in master, so far it has been possible to directly draw on Linux framebuffer and with some errors on X11 window. `requestAnimationFrame()` does makes sense on these contexts to sync with the screen and terminal refreshes, and the same can be applied to offscreen rendering.

**Comment by asturur** [comment]
I think node is multi platform and so is node canvas. understanding what is the refresh rate and sync with it, will probably change from platform to platform.

**Comment by piranna** [comment]
> I think node is multi platform and so is node canvas. understanding what is the refresh rate and sync with it, will probably change from platform to platform.

That's why I proposed to make it backend specific.


> I also do not understand what is the concept of frame for node canvas.

With backends support and direct screen rendering, `node-canvas` it not anymore just only to render static images, and can be used to draw animations, so internally it needs some mechanism to don't hog the CPU continuously repainting a scene. Showing a public `requestAnimationFrame()` API is not needed but could be useful since it would work sync-ed with hardware, but for internal paint process, it's now mandatory to have it available for performance reasons.


> i m not saying is not useful, i just think is really application specific.

No, it isn't. As I told you, we need it now internally to don't hog the CPU.

**Comment by geuis** [comment]
@piranna I don't believe this should be included in node-canvas primarily because its out of scope. Node-canvas is specifically a server-side implementation of the browser Canvas api. Yes, you can create animations *with* Canvas, but Canvas itself does not create animations. It is simply a graphics platform for creating and rendering individual images. Your request doesn't apply.

**Comment by piranna** [comment]
> Node-canvas is specifically a server-side implementation of the browser Canvas api

After having backends support and being currently available to directly draw on the screen, this statement doesn't apply anymore.

**Comment by asturur** [comment]
The same point i was trying to underline is that node canvas can draw on whatever platform you want but should not provide you a frame or animation concept.

you do not have a way to batch render calls, each call is drawing a portion of a frame. many call a complex picture, many different composition of drawing calls can be an animation. handling the animation and resource required is up to you.

i mean is a completely new project that can be started on itself.

**Comment by piranna** [comment]
Ok, don't call it `requestAnimationFrame()` if you want, maybe `backend.vsync(callback)` or `backend.on('vsync', callback)` is a better concept for you?

**Comment by asturur** [comment]
vsync apply just on when you are drawing on a screen and can be a specific for only one kind of backend, with many complications with windows/linux/mac/arm.

it just does not fit here. what is wrong with a node utility that provides you a vsync callback? why it should be part of the node canvas project?

i have nothing against it, i m just expressing my idea of separation of roles between projects.

**Comment by piranna** [comment]
> what is wrong with a node utility that provides you a vsync callback? why it should be part of the node canvas project?

I don't know of anyone that provides support for that, and with the backends we already have access to the underlying APIs that provides that info. Doing it in a separate project would lead to a duplication and waste of efforts and resources.

**Comment by zbjornson** [comment]
It's totally valid to link against node-canvas's C++ API (just `#include` the header files you need), so if this isn't something that belongs in node-canvas, you could quite likely make it a separate module without duplicating any code.

**Comment by smartguy1196** [comment]
@piranna 
> i have nothing against it, i m just expressing my idea of __separation of roles between projects__
> @asturur 

> if this isn't something that belongs in node-canvas, you could quite likely make it a separate module
> @zbjornson 

I think this may add clarity.

The point of this module is to behave like a ___server-side service___, meaning that if animations were to be happening, they would not take place where node is running (how could a client see an animation, if the canvas exists on the server?). The reason it is designed as a _server-side service_ is that if you want client-side animations available over CLI, don't use node, use a headless browser like phantom.

Now, what I _can_ understanding asking is porting this library so that it can be used in a browser, because it adds some really cool non-standard APIs

**Comment by zbjornson** [comment]
Closing for now since this seems to be out of scope. I'm happy to help play with linking against canvas's C++ API for this.

BTW, I added an example of using node-canvas with a framebuffer to the wiki: https://github.com/Automattic/node-canvas/wiki/Using-with-framebuffer-devices

**Comment by piranna** [comment]
> BTW, I added an example of using node-canvas with a framebuffer to the wiki: https://github.com/Automattic/node-canvas/wiki/Using-with-framebuffer-devices

Well, it's a solution (a not bad one, in fact :-) ), but having the backends support, probably it would be better to left node-canvas/Cairo to write directly to the FrameBuffer instead of needing to copy and write the buffer by hand, that would lost performance. For static images it's ok, but for drawing animations in the FrameBuffer not so much... :-/

**Comment by jleonard-r7** [comment]
Any plans to support this? A combination of 3rd party libs I am attempting to use make its absence particularly unpleasant:
https://github.com/akira-cn/node-canvas-webgl
https://github.com/DougHamil/threeagent/blob/v1.0.1/src/main/threeagent/impl/scene.cljs#L282
