### ISSUE TITLE
thought about making prebuilt binaries?

### ISSUE THREAD

**Issue by ralphtheninja** [Automattic/node-canvas#967]
using e.g. [prebuild](https://github.com/mafintosh/prebuild) or similar?

**Comment by chearon** [comment]
I've already got prebuilt binaries in `canvas-prebuilt`, which links against system libraries in a way originally laid out in #641. There's #813 but there's been nothing done to get `prebuild` set up on CI, and it increases the build complexity a lot which might not be good for falling back to a build.

I'll probably just make a PR to have `canvas` download binaries from the `canvas-prebuilt` repo sometime soon.

**Comment by ralphtheninja** [comment]
You can setup `prebuild-ci` to run after tests pass, see [leveldown](https://github.com/Level/leveldown/blob/master/package.json#L59)
