### ISSUE TITLE
createCanvas not defined

### ISSUE THREAD

**Issue by wagenaartje** [Automattic/node-canvas#973]
## Issue
I'm trying to reproduce the example in the `REAMDE.md` but when I require canvas, it's `createCanvas` property is undefined.

```js
TypeError: createCanvas is not a function
```

This is what the `canvas` require returns:

```
{ [Function: Canvas]
  version: '1.6.6',
  cairoVersion: '1.10.2',
  Context2d: { [Function: CanvasRenderingContext2D] parseFont: [Function] },
  PNGStream: [Function: PNGStream],
  PDFStream: [Function: PDFStream],
  JPEGStream: [Function: JPEGStream],
  Image: { [Function: Image] MODE_IMAGE: 1, MODE_MIME: 2 },
  ImageData: [Function: ImageData] }
``` 

## Steps to Reproduce
So basically just this will throw an error:

```js
const { createCanvas } = require('canvas');
createCanvas(512, 512); // createCanvas is not a function
```

## Your Environment
* Windows 10
* Node version 8.4.0

**Comment by zbjornson** [comment]
That syntax is for node-canvas 2.0 (try `npm install canvas@v2.0.0-alpha.3`).

**Comment by wagenaartje** [comment]
Thanks! I skipped past the piece of text notifying me.
