### ISSUE TITLE
jsdom Compatibility broken after v2.0.0-alpha.2

### ISSUE THREAD

**Issue by hbar-digital** [Automattic/node-canvas#978]
It seems the following commit has broken support for using node-canvas with jsdom: https://github.com/Automattic/node-canvas/commit/6a29a230d44c066864c8b151587f9794b0453e89

```
// npm install jsdom canvas

var canvas = require('canvas');

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM()

console.log(dom.window.document.createElement('canvas').getContext('2d')); 

// Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
```

running node 6.10.3

**Comment by geuis** [comment]
I just tried @hbar-digital code with alpha.3 and did not get an error. I just see:

```
CanvasRenderingContext2D {
  canvas: HTMLCanvasElement {},
  createPattern: [Function],
  drawImage: [Function] }
```

**Comment by cmdelatorre** [comment]
I've run into this issue. It may be related to the fact that when `jsdom` requires `canvas` it expects a function and it is getting an object. See here: https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/utils.js#L193

```javascript

exports.Canvas = null;
["canvas", "canvas-prebuilt"].some(moduleName => {
  try {
    exports.Canvas = require(moduleName);
    if (typeof exports.Canvas !== "function") {
      // In browserify, the require will succeed but return an empty object
      exports.Canvas = null;
    }
  } catch (e) {
    exports.Canvas = null;
  }
  return exports.Canvas !== null;
});
```

With `canvas@1.6.6`
```node
$ node
> const canvas = require("canvas");
undefined
> typeof canvas
'function'
```

but with ` canvas@2.0.0-alpha.5`
```node
$ node
> const canvas = require("canvas");
undefined
> typeof canvas
'object'
```

**Comment by zbjornson** [comment]
I have a PR open with jsdom to fix this (https://github.com/tmpvar/jsdom/pull/1964), but they want Canvas 2.x to go out of alpha/beta before merging.

**Comment by cmdelatorre** [comment]
Awesome, thanks for the update.
