### ISSUE TITLE
Support toBuffer(cb, mimeType, quality)?

### ISSUE THREAD

**Issue by zbjornson** [Automattic/node-canvas#982]
Some discussion in https://github.com/Automattic/node-canvas/issues/743, but in essence there should be a non-streaming API for all formats with all config options (e.g. quality, PNG filter).

`toBuffer(cb: function, mimeType?: string, quality?: number)` would parallel [`toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob).

```typescript
toBuffer(cb, "image/jpeg", quality: number);
toBuffer(cb, "image/png", compressionLevel: number);
// accommodate non-standard options:
toBuffer(cb, "image/png", {compressionLevel?: number, filter?: number, palette?: Uint8ClampedArray, backgroundIndex?: number});
toBuffer(cb, "image/svg"); // throws if not an SVG canvas
toBuffer(cb, "raw"); // Maybe? No need for this to use a callback as it's just a memcpy.
toBuffer(cb, "image/gif"); // maybe in the future
```

Alternatively, @adamhooper proposed separate `toPNG`/`toJPEG` functions.

Should there be sync versions that return a value instead of accepting a callback?

See also #934 about cleaning up the PNG filter API.

I can work on this sometime soon. Feedback welcome.

**Comment by jimmywarting** [comment]
Can we depend on [fetch-blob](https://www.npmjs.com/package/fetch-blob) to make `canvas.toBlob` function in nodejs too?
