### ISSUE TITLE
Text baseline for rotated text is wrong in 2.0

### ISSUE THREAD

**Issue by zbjornson** [Automattic/node-canvas#983]
Since c927c809, this (new) test fails:

```js
tests['rotated baseline'] = function (ctx) {
  ctx.font = '12px Arial';
  ctx.fillStyle = 'black';
  ctx.textAlign = 'center';
  ctx.translate(50, 82.5);
  ctx.rotate(-Math.PI / 2);
  ctx.textBaseline = "bottom";
  ctx.fillText("Hello world!", 0, -18);
}
```

![pasted_image_at_2017_08_31_01_51_pm](https://user-images.githubusercontent.com/469365/29945291-79f43594-8e55-11e7-80a0-0f098f9c5078.png)
(I drew the line for clarity)

In this case, `yy` from the cairo matrix is `cos(pi/2)` ~= 0, so the baseline shift is effectively doing nothing.

**Comment by eNepper** [comment]
FYI: This issue is also present in v 1.6.6. Is this some thing you will be fixing or when will v2 be released?
