### ISSUE TITLE
failed to use in centOS anyone can Help?

### ISSUE THREAD

**Issue by zhuyuwaiting** [Automattic/node-canvas#986]
## Your Environment
* Version of node-canvas (e.g. 1.6.0):
* Environment (e.g. node 6.1.0  npm version 3.8.6,centOs version :release:6.9):

![Uploading node.png…](https://github.com/zhuyuwaiting/img/blob/master/node.png?raw=true)

![Uploading node.png…](https://github.com/zhuyuwaiting/img/blob/master/node2.png?raw=true)

**Comment by zbjornson** [comment]
I think the canvas build messages are non-fatal warnings, but they suggest that you have an ancient version of Cairo.

The error you have in the second screenshot appears to be about contextify, not node-canvas. (That error usually occurs if you compile on one platform and attempt to use the binary on another.)

**Comment by LinusU** [comment]
feel free to reopen if any further development happens...

**Comment by zhuyuwaiting** [comment]
thanks very much  ,finally I find out why. actually I use fabric,and fabricjs use node canvas .in my system I have not installed all dependences that node-canvas needs.
