### ISSUE TITLE
Canvas is not a constructor

### ISSUE THREAD

**Issue by alktbihd** [Automattic/node-canvas#997]
## Issue or Feature
it was working propery and when i changed my vps and I get this error in console and it wont buffer.

```js
var Canvas = require('canvas');

	const canvas = new Canvas.createCanvas(500, 500);
	const ctx = canvas.getContext('2d');
	const base = new Canvas();
	const generate = () => {
		// Environment Variables
		ctx.drawImage(base, 0, 0);
		ctx.scale(1, 1);
		ctx.patternQuality = 'billinear';
		ctx.filter = 'bilinear';
		ctx.antialias = 'subpixel';
		ctx.shadowColor = 'rgba(0, 0, 0, 0.4)';
		ctx.shadowOffsetY = 2;
		ctx.shadowBlur = 2;


		


		// Image

	};
	base.src = await request({
		uri: 'https://source.unsplash.com/500x500/?nature',
		encoding: null
	});

```

## My Environment
* Version of node-canvas (e.g. 1.4.0): next
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 8 on ubuntu 16.04

**Comment by chearon** [comment]
Use `Canvas.createCanvas`, the top-level exports object is no longer the Canvas constructor. If you did want the constructor directly, use `new Canvas.Canvas(500, 500)`

**Comment by LinusU** [comment]
Yes, as already said

```diff
- const canvas = new Canvas.createCanvas(500, 500);
+ const canvas = Canvas.createCanvas(500, 500);
```

and

```diff
- const base = new Canvas();
+ const base = Canvas.createCanvas();
```

**Comment by LinusU** [comment]
Also, it seems like you meant for `base` to be an `Image`, not a `Canvas`? So that would be

```diff
- const base = new Canvas();
+ const base = new Canvas.Image();
```

**Comment by AniruddhPurohit** [comment]
Here is what I did for the same error "Canvas is not a constructor"
After installing canvas using npm install command 

1. Open file "node_modules/canvas/dist/canvas.full.js"
2. Search: **this.canvas = new Canvas(this.imageWidth(), this.imageHeight());**
3. And replace with: **this.canvas = new Canvas.Canvas(this.imageWidth(), this.imageHeight());**

Working for me.
